proxygen::HTTPSessionStats Class Reference
#include <HTTPSessionStats.h>
Public Member Functions
~HTTPSessionStats () noexceptoverride
virtual void recordTransactionOpened () noexcept=0
virtual void recordTransactionClosed () noexcept=0
virtual void recordTransactionsServed (uint64_t) noexcept=0
virtual void recordSessionReused () noexcept=0
virtual void recordSessionIdleTime (std::chrono::seconds) noexcept
virtual void recordTransactionStalled () noexcept=0
virtual void recordSessionStalled () noexcept=0
Detailed Description
Definition at line 19 of file HTTPSessionStats.h.
Constructor & Destructor Documentation
proxygen::HTTPSessionStats::~HTTPSessionStats () [inline], [override], [noexcept]
Definition at line 21 of file HTTPSessionStats.h.
References recordSessionReused(), recordTransactionClosed(), recordTransactionOpened(), and recordTransactionsServed().
{}
Member Function Documentation
virtual void proxygen::HTTPSessionStats::recordSessionIdleTime (std::chrono::seconds) [inline], [virtual], [noexcept]
Definition at line 27 of file HTTPSessionStats.h.
References recordSessionStalled(), and recordTransactionStalled().
{}
virtual void proxygen::HTTPSessionStats::recordSessionReused () [pure virtual], [noexcept]
Implemented in proxygen::DummyHTTPSessionStats .
Referenced by proxygen::HTTPSession::createTransaction(), and ~HTTPSessionStats().
virtual void proxygen::HTTPSessionStats::recordSessionStalled () [pure virtual], [noexcept]
Implemented in proxygen::DummyHTTPSessionStats .
Referenced by proxygen::HTTPSession::onConnectionSendWindowClosed(), and recordSessionIdleTime().
virtual void proxygen::HTTPSessionStats::recordTransactionClosed () [pure virtual], [noexcept]
Implemented in proxygen::DummyHTTPSessionStats .
Referenced by ~HTTPSessionStats(), and proxygen::HTTPTransaction::~HTTPTransaction().
virtual void proxygen::HTTPSessionStats::recordTransactionOpened () [pure virtual], [noexcept]
Implemented in proxygen::DummyHTTPSessionStats .
Referenced by proxygen::HTTPTransaction::HTTPTransaction(), and ~HTTPSessionStats().
virtual void proxygen::HTTPSessionStats::recordTransactionsServed (uint64_t) [pure virtual], [noexcept]
Implemented in proxygen::DummyHTTPSessionStats .
Referenced by ~HTTPSessionStats().
virtual void proxygen::HTTPSessionStats::recordTransactionStalled () [pure virtual], [noexcept]
Implemented in proxygen::DummyHTTPSessionStats .
Referenced by recordSessionIdleTime(), and proxygen::HTTPTransaction::updateHandlerPauseState().
The documentation for this class was generated from the following file:
proxygen/lib/http/session/HTTPSessionStats.h