proxygen::HTTP2PriorityQueueBase Class Reference
#include <HTTP2PriorityQueue.h>
Classes
class BaseNode
Public Types
using Handle = BaseNode *
Public Member Functions
HTTP2PriorityQueueBase (HTTPCodec::StreamID rootNodeId)
virtual Handle addTransaction (HTTPCodec::StreamID id, http2::PriorityUpdate pri, HTTPTransaction *txn, bool permanent=false, uint64_t *depth=nullptr)=0
virtual Handle updatePriority (Handle handle, http2::PriorityUpdate pri, uint64_t *depth=nullptr)=0
virtual void removeTransaction (Handle handle)=0
virtual void signalPendingEgress (Handle h)=0
virtual void clearPendingEgress (Handle h)=0
HTTPCodec::StreamID getRootId ()
Protected Attributes
HTTPCodec::StreamID rootNodeId_ {0}
Detailed Description
Definition at line 27 of file HTTP2PriorityQueue.h.
Member Typedef Documentation
using proxygen::HTTP2PriorityQueueBase::Handle = BaseNode*
Definition at line 36 of file HTTP2PriorityQueue.h.
Constructor & Destructor Documentation
proxygen::HTTP2PriorityQueueBase::HTTP2PriorityQueueBase (HTTPCodec::StreamID rootNodeId) [inline], [explicit]
Definition at line 38 of file HTTP2PriorityQueue.h.
References addTransaction(), clearPendingEgress(), removeTransaction(), signalPendingEgress(), and updatePriority().
    : rootNodeId_(rootNodeId) {}
Member Function Documentation
virtual Handle proxygen::HTTP2PriorityQueueBase::addTransaction (HTTPCodec::StreamID id, http2::PriorityUpdate pri, HTTPTransaction * txn, bool permanent = false, uint64_t * depth = nullptr) [pure virtual]
Implemented in proxygen::HTTP2PriorityQueue .
Referenced by proxygen::HTTP2PriorityQueue::addPriorityNode(), proxygen::HTTP2PriorityQueue::dropPriorityNodes(), HTTP2PriorityQueueBase(), and proxygen::HTTPTransaction::HTTPTransaction().
virtual void proxygen::HTTP2PriorityQueueBase::clearPendingEgress (Handle h) [pure virtual]
Implemented in proxygen::HTTP2PriorityQueue .
Referenced by proxygen::HTTP2PriorityQueue::Node::clearTransaction(), HTTP2PriorityQueueBase(), proxygen::HTTPTransaction::notifyTransportPendingEgress(), and proxygen::HTTP2PriorityQueue::setMaxVirtualNodes().
HTTPCodec::StreamID proxygen::HTTP2PriorityQueueBase::getRootId () [inline]
Definition at line 61 of file HTTP2PriorityQueue.h.
References rootNodeId_.
Referenced by proxygen::HTTPTransaction::HTTPTransaction(), and proxygen::HTTPTransaction::onPriorityUpdate().
                                {
    return rootNodeId_;
  }
virtual void proxygen::HTTP2PriorityQueueBase::removeTransaction (Handle handle) [pure virtual]
Implemented in proxygen::HTTP2PriorityQueue .
Referenced by proxygen::HTTP2PriorityQueue::dropPriorityNodes(), HTTP2PriorityQueueBase(), and proxygen::HTTPTransaction::~HTTPTransaction().
virtual void proxygen::HTTP2PriorityQueueBase::signalPendingEgress (Handle h) [pure virtual]
Implemented in proxygen::HTTP2PriorityQueue .
Referenced by proxygen::HTTP2PriorityQueue::Node::clearTransaction(), HTTP2PriorityQueueBase(), proxygen::HTTPTransaction::notifyTransportPendingEgress(), and proxygen::HTTP2PriorityQueue::setMaxVirtualNodes().
virtual Handle proxygen::HTTP2PriorityQueueBase::updatePriority (Handle handle, http2::PriorityUpdate pri, uint64_t * depth = nullptr) [pure virtual]
Implemented in proxygen::HTTP2PriorityQueue .
Referenced by proxygen::HTTP2PriorityQueue::dropPriorityNodes(), HTTP2PriorityQueueBase(), proxygen::HTTPTransaction::onPriorityUpdate(), and proxygen::HTTPTransaction::updateAndSendPriority().
Member Data Documentation
HTTPCodec::StreamID proxygen::HTTP2PriorityQueueBase::rootNodeId_ {0} [protected]
Definition at line 66 of file HTTP2PriorityQueue.h.
Referenced by proxygen::HTTP2PriorityQueue::addTransaction(), proxygen::HTTP2PriorityQueue::find(), proxygen::HTTP2PriorityQueue::findInternal(), getRootId(), proxygen::HTTP2PriorityQueue::iterateBFS(), proxygen::HTTP2PriorityQueue::nextEgress(), and proxygen::HTTP2PriorityQueue::updatePriority().
The documentation for this class was generated from the following file:
proxygen/lib/http/session/HTTP2PriorityQueue.h