proxygen::MockHTTPTransactionTransport Class Reference
#include <HTTPTransactionMocks.h>
Public Member Functions
MockHTTPTransactionTransport ()
GMOCK_METHOD1_ (, noexcept,, pauseIngress, void(HTTPTransaction *))
GMOCK_METHOD1_ (, noexcept,, resumeIngress, void(HTTPTransaction *))
GMOCK_METHOD1_ (, noexcept,, transactionTimeout, void(HTTPTransaction *))
GMOCK_METHOD4_ (, noexcept,, sendHeaders, void(HTTPTransaction *, const HTTPMessage &, HTTPHeaderSize *, bool))
GMOCK_METHOD4_ (, noexcept,, sendBody, size_t(HTTPTransaction *, std::shared_ptr< folly::IOBuf >, bool, bool))
size_t sendBody (HTTPTransaction *txn, std::unique_ptr< folly::IOBuf > iob, bool eom, bool trackLastByteFlushed) noexceptoverride
GMOCK_METHOD2_ (, noexcept,, sendChunkHeader, size_t(HTTPTransaction *, size_t))
GMOCK_METHOD1_ (, noexcept,, sendChunkTerminator, size_t(HTTPTransaction *))
GMOCK_METHOD2_ (, noexcept,, sendEOM, size_t(HTTPTransaction *, const HTTPHeaders *))
GMOCK_METHOD2_ (, noexcept,, sendAbort, size_t(HTTPTransaction *, ErrorCode))
GMOCK_METHOD2_ (, noexcept,, sendPriority, size_t(HTTPTransaction *, const http2::PriorityUpdate &))
GMOCK_METHOD0_ (, noexcept,, notifyPendingEgress, void())
GMOCK_METHOD1_ (, noexcept,, detach, void(HTTPTransaction *))
GMOCK_METHOD2_ (, noexcept,, sendWindowUpdate, size_t(HTTPTransaction *, uint32_t))
GMOCK_METHOD1_ (, noexcept,, notifyIngressBodyProcessed, void(uint32_t))
GMOCK_METHOD1_ (, noexcept,, notifyEgressBodyBuffered, void(int64_t))
GMOCK_METHOD0_ (, noexcept,, getLocalAddressNonConst, const folly::SocketAddress &())
GMOCK_METHOD2_ (, noexcept,, newPushedTransaction, HTTPTransaction *(HTTPCodec::StreamID assocStreamId, HTTPTransaction::PushHandler *handler))
GMOCK_METHOD3_ (, noexcept,, newExTransaction, HTTPTransaction *(HTTPTransaction::Handler *handler, HTTPCodec::StreamID controlStream, bool unidirectional))
const folly::SocketAddress & getLocalAddress () const noexceptoverride
GMOCK_METHOD0_ (, noexcept,, getPeerAddressNonConst, const folly::SocketAddress &())
const folly::SocketAddress & getPeerAddress () const noexceptoverride
MOCK_CONST_METHOD1 (describe, void(std::ostream &))
GMOCK_METHOD0_ (, noexcept,, getSetupTransportInfoNonConst, const wangle::TransportInfo &())
const wangle::TransportInfo & getSetupTransportInfo () const noexceptoverride
MOCK_METHOD1 (getCurrentTransportInfo, bool(wangle::TransportInfo *))
GMOCK_METHOD0_ (, noexcept,, getCodecNonConst, const HTTPCodec &())
const HTTPCodec & getCodec () const noexceptoverride
MOCK_METHOD0 (drain, void())
MOCK_CONST_METHOD0 (isDraining, bool())
MOCK_CONST_METHOD0 (getSecurityProtocol, std::string())
MOCK_CONST_METHOD0 (getTransport, const folly::AsyncTransportWrapper *())
MOCK_METHOD0 (getTransport, folly::AsyncTransportWrapper *())
GMOCK_METHOD1_ (, noexcept,, addWaitingForReplaySafety, void(folly::AsyncTransport::ReplaySafetyCallback *))
GMOCK_METHOD1_ (, noexcept,, removeWaitingForReplaySafety, void(folly::AsyncTransport::ReplaySafetyCallback *))
MOCK_CONST_METHOD0 (needToBlockForReplaySafety, bool())
GMOCK_METHOD0_ (, noexcept,, getUnderlyingTransportNonConst, const folly::AsyncTransportWrapper *())
const folly::AsyncTransportWrapper * getUnderlyingTransport () const noexceptoverride
MOCK_CONST_METHOD0 (isReplaySafe, bool())
MOCK_METHOD1 (setHTTP2PrioritiesEnabled, void(bool))
MOCK_CONST_METHOD0 (getHTTP2PrioritiesEnabled, bool())
MOCK_METHOD1 (getHTTPPriority, folly::Optional< const HTTPMessage::HTTPPriority >(uint8_t level))
Public Attributes
MockHTTPCodec mockCodec_
Detailed Description
Definition at line 23 of file HTTPTransactionMocks.h.
Constructor & Destructor Documentation
proxygen::MockHTTPTransactionTransport::MockHTTPTransactionTransport () [inline]
Definition at line 25 of file HTTPTransactionMocks.h.
References GMOCK_METHOD1_(), GMOCK_METHOD4_(), mockCodec_, proxygen::HTTPTransaction::Transport::pauseIngress(), proxygen::HTTPTransaction::Transport::resumeIngress(), sendBody(), proxygen::HTTPTransaction::Transport::sendHeaders(), and proxygen::HTTPTransaction::Transport::transactionTimeout().
                                 {
    EXPECT_CALL(*this, getCodecNonConst())
      .WillRepeatedly(testing::ReturnRef(mockCodec_));
  }
Member Function Documentation
const HTTPCodec& proxygen::MockHTTPTransactionTransport::getCodec () const [inline], [override], [virtual], [noexcept]
Implements proxygen::HTTPTransaction::Transport .
Definition at line 93 of file HTTPTransactionMocks.h.
References proxygen::HTTPTransaction::Transport::addWaitingForReplaySafety(), proxygen::HTTPTransaction::Transport::drain(), proxygen::HTTPTransaction::Transport::getSecurityProtocol(), GMOCK_METHOD0_(), GMOCK_METHOD1_(), proxygen::HTTPTransaction::Transport::isDraining(), MOCK_CONST_METHOD0(), MOCK_METHOD0(), proxygen::HTTPTransaction::Transport::needToBlockForReplaySafety(), and proxygen::HTTPTransaction::Transport::removeWaitingForReplaySafety().
                                                      {
    return const_cast<MockHTTPTransactionTransport*>(this)
      ->getCodecNonConst();
  }
const folly::SocketAddress& proxygen::MockHTTPTransactionTransport::getLocalAddress () const [inline], [override], [virtual], [noexcept]
Implements proxygen::HTTPTransaction::Transport .
Definition at line 71 of file HTTPTransactionMocks.h.
References GMOCK_METHOD0_().
                            {
    return const_cast<MockHTTPTransactionTransport*>(this)
      ->getLocalAddressNonConst();
  }
const folly::SocketAddress& proxygen::MockHTTPTransactionTransport::getPeerAddress () const [inline], [override], [virtual], [noexcept]
Implements proxygen::HTTPTransaction::Transport .
Definition at line 78 of file HTTPTransactionMocks.h.
References proxygen::HTTPTransaction::Transport::describe(), GMOCK_METHOD0_(), and MOCK_CONST_METHOD1().
                            {
    return const_cast<MockHTTPTransactionTransport*>(this)
      ->getPeerAddressNonConst();
  }
const wangle::TransportInfo& proxygen::MockHTTPTransactionTransport::getSetupTransportInfo () const [inline], [override], [virtual], [noexcept]
Implements proxygen::HTTPTransaction::Transport .
Definition at line 86 of file HTTPTransactionMocks.h.
References proxygen::HTTPTransaction::Transport::getCurrentTransportInfo(), GMOCK_METHOD0_(), and MOCK_METHOD1().
                                                                             {
    return const_cast<MockHTTPTransactionTransport*>(this)
      ->getSetupTransportInfoNonConst();
  }
const folly::AsyncTransportWrapper* proxygen::MockHTTPTransactionTransport::getUnderlyingTransport () const [inline], [override], [virtual], [noexcept]
Implements proxygen::HTTPTransaction::Transport .
Definition at line 112 of file HTTPTransactionMocks.h.
References proxygen::HTTPTransaction::Transport::getHTTP2PrioritiesEnabled(), proxygen::HTTPTransaction::Transport::getHTTPPriority(), proxygen::HTTPTransaction::Transport::isReplaySafe(), MOCK_CONST_METHOD0(), MOCK_METHOD1(), and proxygen::HTTPTransaction::Transport::setHTTP2PrioritiesEnabled().
                              {
    return const_cast<MockHTTPTransactionTransport*>(this)
      ->getUnderlyingTransport();
  }
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD0_ (noexcept , notifyPendingEgress , void())
Referenced by getCodec(), getLocalAddress(), getPeerAddress(), getSetupTransportInfo(), proxygen::MockHTTPTransactionTransportCallback::MockHTTPTransactionTransportCallback(), and sendBody().
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD0_ (noexcept , getLocalAddressNonConst , const folly::SocketAddress & ())
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD0_ (noexcept , getPeerAddressNonConst , const folly::SocketAddress & ())
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD0_ (noexcept , getSetupTransportInfoNonConst , const wangle::TransportInfo & ())
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD0_ (noexcept , getCodecNonConst , const HTTPCodec & ())
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD0_ (noexcept , getUnderlyingTransportNonConst , const folly::AsyncTransportWrapper * ())
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD1_ (noexcept , pauseIngress , void(HTTPTransaction *))
Referenced by getCodec(), MockHTTPTransactionTransport(), proxygen::MockHTTPTransactionTransportCallback::MockHTTPTransactionTransportCallback(), and sendBody().
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD1_ (noexcept , resumeIngress , void(HTTPTransaction *))
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD1_ (noexcept , transactionTimeout , void(HTTPTransaction *))
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD1_ (noexcept , sendChunkTerminator , size_t(HTTPTransaction *))
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD1_ (noexcept , detach , void(HTTPTransaction *))
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD1_ (noexcept , notifyIngressBodyProcessed , void(uint32_t))
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD1_ (noexcept , notifyEgressBodyBuffered , void(int64_t))
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD1_ (noexcept , addWaitingForReplaySafety , void(folly::AsyncTransport::ReplaySafetyCallback *))
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD1_ (noexcept , removeWaitingForReplaySafety , void(folly::AsyncTransport::ReplaySafetyCallback *))
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD2_ (noexcept , sendChunkHeader , size_t(HTTPTransaction *, size_t))
Referenced by sendBody().
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD2_ (noexcept , sendEOM , size_t(HTTPTransaction *, const HTTPHeaders *))
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD2_ (noexcept , sendAbort , size_t(HTTPTransaction *, ErrorCode))
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD2_ (noexcept , sendPriority , size_t(HTTPTransaction *, const http2::PriorityUpdate &))
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD2_ (noexcept , sendWindowUpdate , size_t(HTTPTransaction *, uint32_t))
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD2_ (noexcept , newPushedTransaction , HTTPTransaction * HTTPCodec::StreamID assocStreamId, HTTPTransaction::PushHandler *handler)
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD3_ (noexcept , newExTransaction , HTTPTransaction * HTTPTransaction::Handler *handler, HTTPCodec::StreamID controlStream, bool unidirectional)
Referenced by sendBody().
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD4_ (noexcept , sendHeaders , void(HTTPTransaction *, const HTTPMessage &, HTTPHeaderSize *, bool))
Referenced by MockHTTPTransactionTransport().
proxygen::MockHTTPTransactionTransport::GMOCK_METHOD4_ (noexcept , sendBody , size_t(HTTPTransaction *, std::shared_ptr< folly::IOBuf >, bool, bool))
proxygen::MockHTTPTransactionTransport::MOCK_CONST_METHOD0 (isDraining , bool())
Referenced by getCodec(), getUnderlyingTransport(), proxygen::MockHTTPTransaction::MockHTTPTransaction(), proxygen::MockHTTPTransaction::sendBody(), and proxygen::MockHTTPTransaction::setHandlerUnmocked().
proxygen::MockHTTPTransactionTransport::MOCK_CONST_METHOD0 (getSecurityProtocol , std::string())
proxygen::MockHTTPTransactionTransport::MOCK_CONST_METHOD0 (getTransport , const folly::AsyncTransportWrapper * ())
proxygen::MockHTTPTransactionTransport::MOCK_CONST_METHOD0 (needToBlockForReplaySafety , bool())
proxygen::MockHTTPTransactionTransport::MOCK_CONST_METHOD0 (isReplaySafe , bool())
proxygen::MockHTTPTransactionTransport::MOCK_CONST_METHOD0 (getHTTP2PrioritiesEnabled , bool())
proxygen::MockHTTPTransactionTransport::MOCK_CONST_METHOD1 (describe , void(std::ostream &))
Referenced by getPeerAddress().
proxygen::MockHTTPTransactionTransport::MOCK_METHOD0 (drain , void())
Referenced by getCodec(), and proxygen::MockHTTPTransaction::sendBody().
proxygen::MockHTTPTransactionTransport::MOCK_METHOD0 (getTransport , folly::AsyncTransportWrapper * ())
proxygen::MockHTTPTransactionTransport::MOCK_METHOD1 (getCurrentTransportInfo , bool(wangle::TransportInfo *))
Referenced by getSetupTransportInfo(), getUnderlyingTransport(), proxygen::MockHTTPTransaction::MockHTTPTransaction(), proxygen::MockHTTPTransaction::sendBody(), and proxygen::MockHTTPTransaction::setHandlerUnmocked().
proxygen::MockHTTPTransactionTransport::MOCK_METHOD1 (setHTTP2PrioritiesEnabled , void(bool))
proxygen::MockHTTPTransactionTransport::MOCK_METHOD1 (getHTTPPriority , folly::Optional< const HTTPMessage::HTTPPriority > uint8_t level)
size_t proxygen::MockHTTPTransactionTransport::sendBody (HTTPTransaction * txn, std::unique_ptr< folly::IOBuf > iob, bool eom, bool trackLastByteFlushed) [inline], [override], [virtual], [noexcept]
Implements proxygen::HTTPTransaction::Transport .
Definition at line 40 of file HTTPTransactionMocks.h.
References proxygen::HTTPTransaction::Transport::detach(), GMOCK_METHOD0_(), GMOCK_METHOD1_(), GMOCK_METHOD2_(), GMOCK_METHOD3_(), proxygen::HTTPTransaction::Transport::newExTransaction(), proxygen::HTTPTransaction::Transport::newPushedTransaction(), proxygen::HTTPTransaction::Transport::notifyEgressBodyBuffered(), proxygen::HTTPTransaction::Transport::notifyIngressBodyProcessed(), proxygen::HTTPTransaction::Transport::notifyPendingEgress(), proxygen::HTTPTransaction::Transport::sendAbort(), proxygen::HTTPTransaction::Transport::sendChunkHeader(), proxygen::HTTPTransaction::Transport::sendChunkTerminator(), proxygen::HTTPTransaction::Transport::sendEOM(), proxygen::HTTPTransaction::Transport::sendPriority(), and proxygen::HTTPTransaction::Transport::sendWindowUpdate().
Referenced by MockHTTPTransactionTransport(), proxygen::MockHTTPTransaction::sendBody(), and proxygen::MockHTTPTransaction::setHandlerUnmocked().
                                                                         {
    return sendBody(txn,
      std::shared_ptr<folly::IOBuf>(iob.release()), eom, trackLastByteFlushed);
  }
Member Data Documentation
MockHTTPCodec proxygen::MockHTTPTransactionTransport::mockCodec_
Definition at line 124 of file HTTPTransactionMocks.h.
Referenced by proxygen::MockHTTPTransaction::enablePush(), proxygen::MockHTTPTransaction::MockHTTPTransaction(), and MockHTTPTransactionTransport().
The documentation for this class was generated from the following file:
proxygen/lib/http/session/test/HTTPTransactionMocks.h