proxygen::StructuredHeadersDecoder Class Reference
#include <StructuredHeadersDecoder.h>
Public Member Functions
StructuredHeadersDecoder (const std::string &s)
StructuredHeaders::DecodeError decodeItem (StructuredHeaderItem &result)
StructuredHeaders::DecodeError decodeList (std::vector< StructuredHeaderItem > &result)
StructuredHeaders::DecodeError decodeDictionary (Dictionary &result)
StructuredHeaders::DecodeError decodeParameterisedList (ParameterisedList &result)
Private Types
enum MapType { MapType::DICTIONARY = 0,
MapType::PARAMETERISED_MAP = 1
 }
Private Member Functions
StructuredHeaders::DecodeError decodeMap (std::unordered_map< std::string, StructuredHeaderItem > &result, MapType mapType)
Private Attributes
StructuredHeadersBuffer buf_
Detailed Description
Definition at line 18 of file StructuredHeadersDecoder.h.
Member Enumeration Documentation
enum proxygen::StructuredHeadersDecoder::MapType [strong], [private]
Enumerator
DICTIONARY
PARAMETERISED_MAP
Definition at line 34 of file StructuredHeadersDecoder.h.
                     {
    DICTIONARY = 0,
    PARAMETERISED_MAP = 1
  };
Constructor & Destructor Documentation
proxygen::StructuredHeadersDecoder::StructuredHeadersDecoder (const std::string & s) [inline], [explicit]
Definition at line 21 of file StructuredHeadersDecoder.h.
References decodeDictionary(), decodeItem(), decodeList(), and decodeParameterisedList().
: buf_(s) {}
Member Function Documentation
DecodeError proxygen::StructuredHeadersDecoder::decodeDictionary (Dictionary & result)
Definition at line 61 of file StructuredHeadersDecoder.cpp.
Referenced by StructuredHeadersDecoder(), and proxygen::TEST_F().
                                                                         {
  return decodeMap(result, MapType::DICTIONARY);
}
DecodeError proxygen::StructuredHeadersDecoder::decodeItem (StructuredHeaderItem & result)
Definition at line 17 of file StructuredHeadersDecoder.cpp.
References proxygen::StructuredHeaders::INVALID_CHARACTER, and proxygen::StructuredHeaders::OK.
Referenced by StructuredHeadersDecoder(), proxygen::TEST_F(), and proxygen::TEST_P().
                                {
    auto err = buf_.parseItem(result);
    if (err != DecodeError::OK) {
      return err;
    }
    return buf_.isEmpty() ?
      DecodeError::OK : buf_.handleDecodeError(DecodeError::INVALID_CHARACTER);
}
DecodeError proxygen::StructuredHeadersDecoder::decodeList (std::vector< StructuredHeaderItem > & result)
Definition at line 27 of file StructuredHeadersDecoder.cpp.
References proxygen::StructuredHeaders::OK, and proxygen::StructuredHeaders::UNEXPECTED_END_OF_BUFFER.
Referenced by StructuredHeadersDecoder(), proxygen::TEST_F(), and proxygen::TEST_P().
                                            {
  while (!buf_.isEmpty()) {
    StructuredHeaderItem item;
    auto err = buf_.parseItem(item);
    if (err != DecodeError::OK) {
      return err;
    }
    result.push_back(item);
    buf_.removeOptionalWhitespace();
    if (buf_.isEmpty()) {
      return DecodeError::OK;
    }
    err = buf_.removeSymbol(",", true);
    if (err != DecodeError::OK) {
      return err;
    }
    buf_.removeOptionalWhitespace();
    if (buf_.isEmpty()) {
      return buf_.handleDecodeError(DecodeError::UNEXPECTED_END_OF_BUFFER);
    }
  }
  return buf_.handleDecodeError(DecodeError::UNEXPECTED_END_OF_BUFFER);
}
DecodeError proxygen::StructuredHeadersDecoder::decodeMap (std::unordered_map< std::string, StructuredHeaderItem > & result, MapType mapType) [private]
Definition at line 104 of file StructuredHeadersDecoder.cpp.
References proxygen::StructuredHeaders::DUPLICATE_KEY, proxygen::StructuredHeaders::StructuredHeaderItem::NONE, proxygen::StructuredHeaders::OK, proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::UNEXPECTED_END_OF_BUFFER.
                   {
  std::string delimiter = (mapType == MapType::PARAMETERISED_MAP) ? ";" : ",";
  buf_.removeOptionalWhitespace();
  if ((mapType == MapType::PARAMETERISED_MAP) &&
      (buf_.removeSymbol(delimiter, false) != DecodeError::OK)) {
    return DecodeError::OK;
  }
  while (!buf_.isEmpty()) {
    buf_.removeOptionalWhitespace();
    std::string thisKey;
    auto err = buf_.parseIdentifier(thisKey);
    if (err != DecodeError::OK) {
      return err;
    }
    if (result.find(thisKey) != result.end()) {
      return buf_.handleDecodeError(DecodeError::DUPLICATE_KEY);
    }
    err = buf_.removeSymbol("=", mapType == MapType::DICTIONARY);
    if (err != DecodeError::OK) {
      if (mapType == MapType::DICTIONARY) {
        return err;
      } else {
        StructuredHeaderItem value;
        value.tag = StructuredHeaderItem::Type::NONE;
        result[thisKey] = value;
      }
    } else {
      StructuredHeaderItem value;
      err = buf_.parseItem(value);
      if (err != DecodeError::OK) {
        return err;
      }
      result[thisKey] = value;
    }
    buf_.removeOptionalWhitespace();
    if (buf_.isEmpty()) {
      return DecodeError::OK;
    }
    err = buf_.removeSymbol(delimiter, mapType == MapType::DICTIONARY);
    if (err != DecodeError::OK) {
      if (mapType == MapType::PARAMETERISED_MAP) {
        return DecodeError::OK;
      } else {
        return err;
      }
    }
  }
  return buf_.handleDecodeError(DecodeError::UNEXPECTED_END_OF_BUFFER);
}
DecodeError proxygen::StructuredHeadersDecoder::decodeParameterisedList (ParameterisedList & result)
Definition at line 65 of file StructuredHeadersDecoder.cpp.
References proxygen::StructuredHeaders::ParameterisedIdentifier::identifier, proxygen::StructuredHeaders::OK, proxygen::StructuredHeaders::ParameterisedIdentifier::parameterMap, and proxygen::StructuredHeaders::UNEXPECTED_END_OF_BUFFER.
Referenced by StructuredHeadersDecoder(), and proxygen::TEST_F().
                             {
  while (!buf_.isEmpty()) {
    ParameterisedIdentifier primaryIdentifier;
    auto err = buf_.parseIdentifier(primaryIdentifier.identifier);
    if (err != DecodeError::OK) {
      return err;
    }
    buf_.removeOptionalWhitespace();
    err = decodeMap(primaryIdentifier.parameterMap, MapType::PARAMETERISED_MAP);
    if (err != DecodeError::OK) {
      return err;
    }
    result.emplace_back(primaryIdentifier);
    buf_.removeOptionalWhitespace();
    if (buf_.isEmpty()) {
      return DecodeError::OK;
    }
    err = buf_.removeSymbol(",", true);
    if (err != DecodeError::OK) {
      return err;
    }
    buf_.removeOptionalWhitespace();
  }
  return buf_.handleDecodeError(DecodeError::UNEXPECTED_END_OF_BUFFER);
}
Member Data Documentation
StructuredHeadersBuffer proxygen::StructuredHeadersDecoder::buf_ [private]
Definition at line 43 of file StructuredHeadersDecoder.h.
The documentation for this class was generated from the following files:
proxygen/lib/http/structuredheaders/StructuredHeadersDecoder.h
proxygen/lib/http/structuredheaders/StructuredHeadersDecoder.cpp