proxygen::HTTP2PriorityQueue Class Reference
#include <HTTP2PriorityQueue.h>
Classes
class Node
Public Types
using NextEgressResult = std::vector< std::pair< HTTPTransaction *, double >>
Public Member Functions
HTTP2PriorityQueue (HTTPCodec::StreamID rootNodeId=0)
HTTP2PriorityQueue (const WheelTimerInstance &timeout, HTTPCodec::StreamID rootNodeId=0)
void attachThreadLocals (const WheelTimerInstance &timeout)
class HTTP2PriorityQueue
void detachThreadLocals ()
void setMaxVirtualNodes (uint32_t maxVirtualNodes)
void signalPendingEgress (Handle h) override
void clearPendingEgress (Handle h) override
void addPriorityNode (HTTPCodec::StreamID id, HTTPCodec::StreamID parent) override
void addOrUpdatePriorityNode (HTTPCodec::StreamID id, http2::PriorityUpdate pri)
void dropPriorityNodes ()
Handle addTransaction (HTTPCodec::StreamID id, http2::PriorityUpdate pri, HTTPTransaction *txn, bool permanent=false, uint64_t *depth=nullptr) override
Handle updatePriority (Handle handle, http2::PriorityUpdate pri, uint64_t *depth=nullptr) override
void removeTransaction (Handle handle) override
bool empty () const
uint64_t numPendingEgress () const
uint64_t numVirtualNodes () const
void iterate (const std::function< bool(HTTPCodec::StreamID, HTTPTransaction *, double)> &fn, const std::function< bool()> &stopFn, bool all)
void iterateBFS (const std::function< bool(HTTP2PriorityQueue &, HTTPCodec::StreamID, HTTPTransaction *, double)> &fn, const std::function< bool()> &stopFn, bool all)
void nextEgress (NextEgressResult &result, bool spdyMode=false)
void rebuildTree ()
Error handling code.
uint32_t getRebuildCount () const
bool isRebuilt () const
Static Public Member Functions
static void setNodeLifetime (std::chrono::milliseconds lifetime)
Private Types
using NodeMap = boost::intrusive::unordered_set< Node, boost::intrusive::constant_time_size< false >>
typedef boost::intrusive::link_mode< boost::intrusive::auto_unlink > link_mode
Private Member Functions
Node * find (HTTPCodec::StreamID id, uint64_t *depth=nullptr)
Node * findInternal (HTTPCodec::StreamID id)
bool allowDanglingNodes () const
void scheduleNodeExpiration (Node *node)
void updateEnqueuedWeight ()
Static Private Member Functions
static bool nextEgressResult (HTTP2PriorityQueue &queue, HTTPCodec::StreamID id, HTTPTransaction *txn, double r)
Private Attributes
NodeMap::bucket_type nodeBuckets_ [kNumBuckets]
NodeMap nodes_
Node root_
uint32_t rebuildCount_ {0}
uint64_t activeCount_ {0}
uint32_t maxVirtualNodes_ {50}
uint32_t numVirtualNodes_ {0}
bool pendingWeightChange_ {false}
WheelTimerInstance timeout_
NextEgressResult * nextEgressResults_ {nullptr}
Static Private Attributes
static const size_t kNumBuckets = 100
static uint32_t kMaxRebuilds_ = 3
static std::chrono::milliseconds kNodeLifetime_
Additional Inherited Members
Detailed Description
Definition at line 69 of file HTTP2PriorityQueue.h.
Member Typedef Documentation
typedef boost::intrusive::link_mode<boost::intrusive::auto_unlink> proxygen::HTTP2PriorityQueue::link_mode [private]
Definition at line 208 of file HTTP2PriorityQueue.h.
using proxygen::HTTP2PriorityQueue::NextEgressResult = std::vector<std::pair<HTTPTransaction*, double>>
Definition at line 163 of file HTTP2PriorityQueue.h.
using proxygen::HTTP2PriorityQueue::NodeMap = boost::intrusive::unordered_set< Node, boost::intrusive::constant_time_size<false>> [private]
Definition at line 74 of file HTTP2PriorityQueue.h.
Constructor & Destructor Documentation
proxygen::HTTP2PriorityQueue::HTTP2PriorityQueue (HTTPCodec::StreamID rootNodeId = 0) [inline]
Definition at line 80 of file HTTP2PriorityQueue.h.
      : HTTP2PriorityQueueBase(rootNodeId),
        nodes_(NodeMap::bucket_traits(nodeBuckets_, kNumBuckets)),
        root_(*this, nullptr, rootNodeId, 1, nullptr) {
    root_.setPermanent();
  }
proxygen::HTTP2PriorityQueue::HTTP2PriorityQueue (const WheelTimerInstance & timeout, HTTPCodec::StreamID rootNodeId = 0) [inline], [explicit]
Definition at line 87 of file HTTP2PriorityQueue.h.
      : HTTP2PriorityQueueBase(rootNodeId),
        nodes_(NodeMap::bucket_traits(nodeBuckets_, kNumBuckets)),
        root_(*this, nullptr, rootNodeId, 1, nullptr),
        timeout_(timeout) {
    root_.setPermanent();
  }
Member Function Documentation
void proxygen::HTTP2PriorityQueue::addOrUpdatePriorityNode (HTTPCodec::StreamID id, http2::PriorityUpdate pri)
Definition at line 444 of file HTTP2PriorityQueue.cpp.
References addTransaction(), find(), and updatePriority().
Referenced by proxygen::HTTPSession::onPriority(), and proxygen::HTTPSession::sendPriority().
                                                                     {
  auto handle = find(id);
  if (handle) {
    // already added
    CHECK(handle->getTransaction() == nullptr);
    updatePriority(handle, pri);
  } else {
    // brand new
    addTransaction(id, pri, nullptr, false /* not permanent */);
  }
}
void proxygen::HTTP2PriorityQueue::addPriorityNode (HTTPCodec::StreamID id, HTTPCodec::StreamID parent) [inline], [override], [virtual]
Implements proxygen::HTTPCodec::PriorityQueue .
Definition at line 110 of file HTTP2PriorityQueue.h.
References proxygen::HTTP2PriorityQueueBase::addTransaction().
                                                         {
    addTransaction(id, {parent, false, 0}, nullptr, true);
  }
HTTP2PriorityQueue::Handle proxygen::HTTP2PriorityQueue::addTransaction (HTTPCodec::StreamID id, http2::PriorityUpdate pri, HTTPTransaction * txn, bool permanent = false, uint64_t * depth = nullptr) [override], [virtual]
Implements proxygen::HTTP2PriorityQueueBase .
Definition at line 458 of file HTTP2PriorityQueue.cpp.
References proxygen::HTTP2PriorityQueue::Node::convertVirtualNode(), proxygen::http2::PriorityUpdate::exclusive, find(), proxygen::HTTP2PriorityQueue::Node::getID(), maxVirtualNodes_, numVirtualNodes_, pendingWeightChange_, root_, proxygen::HTTP2PriorityQueueBase::rootNodeId_, scheduleNodeExpiration(), proxygen::http2::PriorityUpdate::streamDependency, updatePriority(), and proxygen::http2::PriorityUpdate::weight.
Referenced by addOrUpdatePriorityNode(), and updatePriority().
                                                    {
  CHECK_NE(id, rootNodeId_);
  CHECK_NE(id, pri.streamDependency) << "Tried to create a loop in the tree";
  CHECK(!txn || !permanent);
  Node *existingNode = find(id, depth);
  if (existingNode) {
    CHECK(!permanent);
    existingNode->convertVirtualNode(CHECK_NOTNULL(txn));
    updatePriority(existingNode, pri);
    return existingNode;
  }
  if (!txn) {
    if (numVirtualNodes_ >= maxVirtualNodes_) {
      return nullptr;
    }
    numVirtualNodes_++;
  }
  Node* parent = &root_;
  if (depth) {
    *depth = 1;
  }
  if (pri.streamDependency != rootNodeId_) {
    Node* dep = find(pri.streamDependency, depth);
    if (dep == nullptr) {
      // specified a missing parent (timed out an idle node)?
      VLOG(4) << "assigning default priority to txn=" << id;
      // No point to try to instantiate one more virtual node
      // if we already reached the virtual node limit
      if (numVirtualNodes_ < maxVirtualNodes_) {
        // The parent node hasn't arrived yet. For now setting
        // its priority fields to default.
        parent = dynamic_cast<Node*>(
            addTransaction(pri.streamDependency,
                           {rootNodeId_,
                            http2::DefaultPriority.exclusive,
                            http2::DefaultPriority.weight},
                           nullptr,
                           permanent,
                           depth));
        CHECK_NOTNULL(parent);
        if (depth) {
          *depth += 1;
        }
      } else {
        VLOG(4) << "Virtual node limit reached, ignoring stream dependency "
                << pri.streamDependency << " for new node ID " << id;
      }
    } else {
      parent = dep;
      if (depth) {
        *depth += 1;
      }
    }
  }
  VLOG(4) << "Adding id=" << id << " with parent=" << parent->getID() <<
    " and weight=" << ((uint16_t)pri.weight + 1);
  auto node = std::make_unique<Node>(*this, parent, id, pri.weight, txn);
  if (permanent) {
    node->setPermanent();
  } else if (!txn) {
    scheduleNodeExpiration(node.get());
  }
  auto result = parent->emplaceNode(std::move(node), pri.exclusive);
  pendingWeightChange_ = true;
  return result;
}
bool proxygen::HTTP2PriorityQueue::allowDanglingNodes () const [inline], [private]
Definition at line 189 of file HTTP2PriorityQueue.h.
Referenced by removeTransaction().
                                  {
    return timeout_ && kNodeLifetime_.count() > 0;
  }
void proxygen::HTTP2PriorityQueue::attachThreadLocals (const WheelTimerInstance & timeout)
class HTTP2PriorityQueue
Definition at line 433 of file HTTP2PriorityQueue.cpp.
References timeout_.
Referenced by proxygen::HTTPUpstreamSession::attachThreadLocals().
                                                                             {
  timeout_ = timeout;
}
void proxygen::HTTP2PriorityQueue::clearPendingEgress (Handle h) [override], [virtual]
Implements proxygen::HTTP2PriorityQueueBase .
Definition at line 611 of file HTTP2PriorityQueue.cpp.
References activeCount_, and pendingWeightChange_.
                                                    {
  CHECK_GT(activeCount_, 0);
  // clear does a CHECK on handle->isEnqueued()
  CHECK_NOTNULL(dynamic_cast<HTTP2PriorityQueue::Node*>(handle))
    ->clearPendingEgress();
  activeCount_--;
  pendingWeightChange_ = true;
}
void proxygen::HTTP2PriorityQueue::detachThreadLocals ()
Definition at line 437 of file HTTP2PriorityQueue.cpp.
References proxygen::HTTP2PriorityQueue::Node::dropPriorityNodes(), and timeout_.
Referenced by proxygen::HTTPUpstreamSession::detachThreadLocals().
                                            {
  // a bit harsh, we could cancel and reschedule the timeout
  dropPriorityNodes();
  timeout_ = WheelTimerInstance();
}
void proxygen::HTTP2PriorityQueue::dropPriorityNodes () [inline]
Definition at line 118 of file HTTP2PriorityQueue.h.
References proxygen::HTTP2PriorityQueueBase::addTransaction(), proxygen::HTTP2PriorityQueueBase::removeTransaction(), and proxygen::HTTP2PriorityQueueBase::updatePriority().
Referenced by proxygen::HTTPSession::~HTTPSession().
                           {
    root_.dropPriorityNodes();
  }
bool proxygen::HTTP2PriorityQueue::empty () const [inline]
Definition at line 137 of file HTTP2PriorityQueue.h.
Referenced by proxygen::HTTPSession::getNextToSend(), proxygen::HTTPSession::hasMoreWrites(), proxygen::HTTPSession::onConnectionSendWindowClosed(), proxygen::HTTPSession::scheduleWrite(), and proxygen::HTTPSession::~HTTPSession().
                     {
    return activeCount_ == 0;
  }
HTTP2PriorityQueue::Node * proxygen::HTTP2PriorityQueue::find (HTTPCodec::StreamID id, uint64_t * depth = nullptr) [private]
Definition at line 700 of file HTTP2PriorityQueue.cpp.
References nodes_, and proxygen::HTTP2PriorityQueueBase::rootNodeId_.
Referenced by addOrUpdatePriorityNode(), addTransaction(), and updatePriority().
                                                              {
  if (id == rootNodeId_) {
    return nullptr;
  }
  auto it = nodes_.find(id, Node::IdHash(), Node::IdNodeEqual());
  if (it == nodes_.end()) {
    return nullptr;
  }
  if (depth) {
    *depth = it->calculateDepth();
  }
  return &(*it);
}
Node* proxygen::HTTP2PriorityQueue::findInternal (HTTPCodec::StreamID id) [inline], [private]
Definition at line 182 of file HTTP2PriorityQueue.h.
References proxygen::HTTP2PriorityQueueBase::rootNodeId_.
Referenced by iterateBFS().
                                           {
    if (id == rootNodeId_) {
      return &root_;
    }
    return find(id);
  }
uint32_t proxygen::HTTP2PriorityQueue::getRebuildCount () const [inline]
Definition at line 175 of file HTTP2PriorityQueue.h.
{ return rebuildCount_; }
bool proxygen::HTTP2PriorityQueue::isRebuilt () const [inline]
Definition at line 176 of file HTTP2PriorityQueue.h.
{ return rebuildCount_ > 0; }
void proxygen::HTTP2PriorityQueue::iterate (const std::function< bool(HTTPCodec::StreamID, HTTPTransaction *, double)> & fn, const std::function< bool()> & stopFn, bool all) [inline]
Definition at line 150 of file HTTP2PriorityQueue.h.
                                                            {
    updateEnqueuedWeight();
    root_.iterate(fn, stopFn, all);
  }
void proxygen::HTTP2PriorityQueue::iterateBFS (const std::function< bool(HTTP2PriorityQueue &, HTTPCodec::StreamID, HTTPTransaction *, double)> & fn, const std::function< bool()> & stopFn, bool all)
Definition at line 621 of file HTTP2PriorityQueue.cpp.
References findInternal(), root_, proxygen::HTTP2PriorityQueueBase::rootNodeId_, proxygen::HTTP2PriorityQueue::Node::updateEnqueuedWeight(), and proxygen::HTTP2PriorityQueue::Node::visitBFS().
Referenced by proxygen::HTTPSession::resumeTransactions().
                                               {
  Node::PendingList pendingNodes{{rootNodeId_, &root_, 1.0}};
  Node::PendingList newPendingNodes;
  bool stop = false;
  updateEnqueuedWeight();
  while (!stop && !stopFn() && !pendingNodes.empty()) {
    CHECK(newPendingNodes.empty());
    while (!stop && !pendingNodes.empty()) {
      Node* node = findInternal(pendingNodes.front().id);
      if (node) {
        stop = node->visitBFS(pendingNodes.front().ratio, fn, all,
                              newPendingNodes, false /* all children */);
      }
      pendingNodes.pop_front();
    }
    std::swap(pendingNodes, newPendingNodes);
  }
}
void proxygen::HTTP2PriorityQueue::nextEgress (HTTP2PriorityQueue::NextEgressResult & result, bool spdyMode = false)
Definition at line 653 of file HTTP2PriorityQueue.cpp.
References activeCount_, nextEgressResult(), nextEgressResults_, root_, proxygen::HTTP2PriorityQueueBase::rootNodeId_, proxygen::HTTP2PriorityQueue::Node::updateEnqueuedWeight(), and proxygen::HTTP2PriorityQueue::Node::visitBFS().
Referenced by proxygen::HTTPSession::getNextToSend().
                                              {
  struct WeightCmp {
    bool operator()(const std::pair<HTTPTransaction*, double>& t1,
                    const std::pair<HTTPTransaction*, double>& t2) {
      return t1.second > t2.second;
    }
  };
  result.reserve(activeCount_);
  nextEgressResults_ = &result;
  updateEnqueuedWeight();
  Node::PendingList pendingNodes;
  Node::PendingList pendingNodesTmp;
  pendingNodes.emplace_back(rootNodeId_, &root_, 1.0);
  bool stop = false;
  do {
    while (!stop && !pendingNodes.empty()) {
      Node* node = pendingNodes.front().node;
      if (node) {
        stop = node->visitBFS(pendingNodes.front().ratio, nextEgressResult,
                              false, pendingNodesTmp,
                              true /* enqueued children */);
      }
      pendingNodes.pop_front();
    }
    // In SPDY mode, we stop as soon one level of the tree produces results,
    // then normalize the ratios.
    if (spdyMode && !result.empty() && !pendingNodesTmp.empty()) {
      double totalRatio = 0;
      for (auto &txnPair: result) {
        totalRatio += txnPair.second;
      }
      CHECK_GT(totalRatio, 0);
      for (auto &txnPair: result) {
        txnPair.second = txnPair.second / totalRatio;
      }
      break;
    }
    std::swap(pendingNodes, pendingNodesTmp);
  } while (!stop && !pendingNodes.empty());
  std::sort(result.begin(), result.end(), WeightCmp());
  nextEgressResults_ = nullptr;
}
bool proxygen::HTTP2PriorityQueue::nextEgressResult (HTTP2PriorityQueue & queue, HTTPCodec::StreamID id, HTTPTransaction * txn, double r) [static], [private]
Definition at line 645 of file HTTP2PriorityQueue.cpp.
References nextEgressResults_.
Referenced by nextEgress().
                                                                     {
  queue.nextEgressResults_->emplace_back(txn, r);
  return false;
}
uint64_t proxygen::HTTP2PriorityQueue::numPendingEgress () const [inline]
Definition at line 142 of file HTTP2PriorityQueue.h.
Referenced by proxygen::HTTPSession::runLoopCallback().
                                    {
    return activeCount_;
  }
uint64_t proxygen::HTTP2PriorityQueue::numVirtualNodes () const [inline]
Definition at line 146 of file HTTP2PriorityQueue.h.
                                   {
    return numVirtualNodes_;
  }
void proxygen::HTTP2PriorityQueue::rebuildTree ()
Error handling code.
Definition at line 727 of file HTTP2PriorityQueue.cpp.
References proxygen::HTTP2PriorityQueue::Node::flattenSubtree(), kMaxRebuilds_, rebuildCount_, and root_.
                                {
  CHECK_LE(rebuildCount_ + 1, kMaxRebuilds_);
  root_.flattenSubtree();
  rebuildCount_++;
}
void proxygen::HTTP2PriorityQueue::removeTransaction (HTTP2PriorityQueue::Handle handle) [override], [virtual]
Implements proxygen::HTTP2PriorityQueueBase .
Definition at line 583 of file HTTP2PriorityQueue.cpp.
References allowDanglingNodes(), proxygen::HTTP2PriorityQueue::Node::clearPendingEgress(), proxygen::HTTP2PriorityQueue::Node::clearTransaction(), proxygen::HTTP2PriorityQueue::Node::getID(), proxygen::HTTP2PriorityQueue::Node::isEnqueued(), maxVirtualNodes_, numVirtualNodes_, pendingWeightChange_, proxygen::HTTP2PriorityQueue::Node::removeFromTree(), and scheduleNodeExpiration().
                                                                     {
  Node* node = CHECK_NOTNULL(dynamic_cast<HTTP2PriorityQueue::Node*>(handle));
  pendingWeightChange_ = true;
  // TODO: or require the node to do it?
  if (node->isEnqueued()) {
    clearPendingEgress(handle);
  }
  if (allowDanglingNodes() && numVirtualNodes_ < maxVirtualNodes_) {
    node->clearTransaction();
    numVirtualNodes_++;
    scheduleNodeExpiration(node);
  } else {
    VLOG(5) << "Deleting dangling node over max id=" << node->getID();
    node->removeFromTree();
  }
}
void proxygen::HTTP2PriorityQueue::scheduleNodeExpiration (Node * node) [inline], [private]
Definition at line 193 of file HTTP2PriorityQueue.h.
References proxygen::HTTP2PriorityQueue::Node::getID().
Referenced by addTransaction(), proxygen::HTTP2PriorityQueue::Node::detachChild(), and removeTransaction().
                                          {
    if (timeout_) {
      VLOG(5) << "scheduling expiration for node=" << node->getID();
      DCHECK_GT(kNodeLifetime_.count(), 0);
      timeout_.scheduleTimeout(node, kNodeLifetime_);
    }
  }
void proxygen::HTTP2PriorityQueue::setMaxVirtualNodes (uint32_t maxVirtualNodes) [inline]
Definition at line 100 of file HTTP2PriorityQueue.h.
References proxygen::HTTP2PriorityQueueBase::clearPendingEgress(), and proxygen::HTTP2PriorityQueueBase::signalPendingEgress().
                                                    {
    maxVirtualNodes_ = maxVirtualNodes;
  }
static void proxygen::HTTP2PriorityQueue::setNodeLifetime (std::chrono::milliseconds lifetime) [inline], [static]
Definition at line 167 of file HTTP2PriorityQueue.h.
                                                              {
    kNodeLifetime_ = lifetime;
  }
void proxygen::HTTP2PriorityQueue::signalPendingEgress (Handle h) [override], [virtual]
Implements proxygen::HTTP2PriorityQueueBase .
Definition at line 601 of file HTTP2PriorityQueue.cpp.
References activeCount_, proxygen::HTTP2PriorityQueueBase::BaseNode::isEnqueued(), and pendingWeightChange_.
                                                     {
  if (!handle->isEnqueued()) {
    CHECK_NOTNULL(dynamic_cast<HTTP2PriorityQueue::Node*>(handle))
      ->signalPendingEgress();
    activeCount_++;
    pendingWeightChange_ = true;
  }
}
void proxygen::HTTP2PriorityQueue::updateEnqueuedWeight () [private]
Definition at line 715 of file HTTP2PriorityQueue.cpp.
References activeCount_, pendingWeightChange_, root_, and proxygen::HTTP2PriorityQueue::Node::updateEnqueuedWeight().
                                         {
#ifndef NDEBUG
  if (pendingWeightChange_) {
    root_.updateEnqueuedWeight(activeCount_ > 0);
    pendingWeightChange_ = false;
  }
#endif
}
HTTP2PriorityQueue::Handle proxygen::HTTP2PriorityQueue::updatePriority (HTTP2PriorityQueue::Handle handle, http2::PriorityUpdate pri, uint64_t * depth = nullptr) [override], [virtual]
Implements proxygen::HTTP2PriorityQueueBase .
Definition at line 531 of file HTTP2PriorityQueue.cpp.
References addTransaction(), proxygen::HTTP2PriorityQueueBase::BaseNode::calculateDepth(), proxygen::HTTP2PriorityQueue::Node::calculateDepth(), proxygen::http2::PriorityUpdate::exclusive, find(), proxygen::HTTP2PriorityQueue::Node::getID(), proxygen::HTTP2PriorityQueue::Node::getParent(), proxygen::HTTP2PriorityQueue::Node::isDescendantOf(), maxVirtualNodes_, numVirtualNodes_, proxygen::HTTP2PriorityQueue::Node::parentID(), pendingWeightChange_, proxygen::HTTP2PriorityQueue::Node::reparent(), root_, proxygen::HTTP2PriorityQueueBase::rootNodeId_, proxygen::http2::PriorityUpdate::streamDependency, proxygen::HTTP2PriorityQueue::Node::updateWeight(), and proxygen::http2::PriorityUpdate::weight.
Referenced by addOrUpdatePriorityNode(), and addTransaction().
                                                    {
  Node* node = CHECK_NOTNULL(dynamic_cast<HTTP2PriorityQueue::Node*>(handle));
  pendingWeightChange_ = true;
  VLOG(4) << "Updating id=" << node->getID() << " with parent=" <<
    pri.streamDependency << " and weight=" << ((uint16_t)pri.weight + 1);
  node->updateWeight(pri.weight);
  CHECK_NE(pri.streamDependency, node->getID()) <<
    "Tried to create a loop in the tree";
  if (pri.streamDependency == node->parentID() && !pri.exclusive) {
    // no move
    if (depth) {
      *depth = handle->calculateDepth();
    }
    return handle;
  }
  Node* newParent = find(pri.streamDependency, depth);
  if (!newParent) {
    if (pri.streamDependency == rootNodeId_ ||
        numVirtualNodes_ >= maxVirtualNodes_) {
      newParent = &root_;
    } else {
      // allocate a virtual node for non-existing parent in my depenency tree
      // then do normal priority processing
      newParent = dynamic_cast<Node*>(
          addTransaction(pri.streamDependency,
                         {rootNodeId_,
                          http2::DefaultPriority.exclusive,
                          http2::DefaultPriority.weight},
                         nullptr,
                         false,
                         depth));
      CHECK_NOTNULL(newParent);
      VLOG(4) << "updatePriority missing parent, creating virtual parent="
              << newParent->getID() << " for txn=" << node->getID();
    }
  }
  if (newParent->isDescendantOf(node)) {
    newParent = newParent->reparent(node->getParent(), false);
  }
  node = node->reparent(newParent, pri.exclusive);
  if (depth) {
    *depth = node->calculateDepth();
  }
  return node;
}
Member Data Documentation
uint64_t proxygen::HTTP2PriorityQueue::activeCount_ {0} [private]
Definition at line 426 of file HTTP2PriorityQueue.h.
Referenced by clearPendingEgress(), nextEgress(), signalPendingEgress(), and updateEnqueuedWeight().
uint32_t proxygen::HTTP2PriorityQueue::kMaxRebuilds_ = 3 [static], [private]
Definition at line 425 of file HTTP2PriorityQueue.h.
Referenced by rebuildTree().
std::chrono::milliseconds proxygen::HTTP2PriorityQueue::kNodeLifetime_ [static], [private]
Initial value:
=
  std::chrono::seconds(30)
Definition at line 433 of file HTTP2PriorityQueue.h.
const size_t proxygen::HTTP2PriorityQueue::kNumBuckets = 100 [static], [private]
Definition at line 76 of file HTTP2PriorityQueue.h.
uint32_t proxygen::HTTP2PriorityQueue::maxVirtualNodes_ {50} [private]
Definition at line 427 of file HTTP2PriorityQueue.h.
Referenced by addTransaction(), removeTransaction(), and updatePriority().
NextEgressResult* proxygen::HTTP2PriorityQueue::nextEgressResults_ {nullptr} [private]
Definition at line 432 of file HTTP2PriorityQueue.h.
Referenced by nextEgress(), and nextEgressResult().
NodeMap::bucket_type proxygen::HTTP2PriorityQueue::nodeBuckets_[kNumBuckets] [private]
Definition at line 421 of file HTTP2PriorityQueue.h.
NodeMap proxygen::HTTP2PriorityQueue::nodes_ [private]
Definition at line 422 of file HTTP2PriorityQueue.h.
Referenced by find(), and proxygen::HTTP2PriorityQueue::Node::Node().
uint32_t proxygen::HTTP2PriorityQueue::numVirtualNodes_ {0} [private]
Definition at line 428 of file HTTP2PriorityQueue.h.
Referenced by addTransaction(), proxygen::HTTP2PriorityQueue::Node::convertVirtualNode(), removeTransaction(), updatePriority(), and proxygen::HTTP2PriorityQueue::Node::~Node().
bool proxygen::HTTP2PriorityQueue::pendingWeightChange_ {false} [private]
Definition at line 429 of file HTTP2PriorityQueue.h.
Referenced by addTransaction(), clearPendingEgress(), removeTransaction(), signalPendingEgress(), updateEnqueuedWeight(), and updatePriority().
uint32_t proxygen::HTTP2PriorityQueue::rebuildCount_ {0} [private]
Definition at line 424 of file HTTP2PriorityQueue.h.
Referenced by rebuildTree().
Node proxygen::HTTP2PriorityQueue::root_ [private]
Definition at line 423 of file HTTP2PriorityQueue.h.
Referenced by addTransaction(), iterateBFS(), nextEgress(), rebuildTree(), updateEnqueuedWeight(), and updatePriority().
WheelTimerInstance proxygen::HTTP2PriorityQueue::timeout_ [private]
Definition at line 430 of file HTTP2PriorityQueue.h.
Referenced by attachThreadLocals(), and detachThreadLocals().
The documentation for this class was generated from the following files:
proxygen/lib/http/session/HTTP2PriorityQueue.h
proxygen/lib/http/session/HTTP2PriorityQueue.cpp