proxygen::Base64 Class Reference
#include <Base64.h>
Static Public Member Functions
static std::string decode (const std::string &b64message, int padding)
static std::string urlDecode (const std::string &b64message)
static std::string encode (folly::ByteRange buffer)
static std::string urlEncode (folly::ByteRange buffer)
Detailed Description
Definition at line 20 of file Base64.h.
Member Function Documentation
std::string proxygen::Base64::decode (const std::string & b64message, int padding) [static]
Definition at line 51 of file Base64.cpp.
Referenced by TEST().
                                                                 {
  if (b64message.length() % 4 != 0 || padding >= 3) {
    return std::string();
  }
  std::unique_ptr<BIO, BIODeleter> bio, b64;
  size_t decodeLen = b64message.length() * 3/4 - padding;
  std::string result(decodeLen, '\0');
  bio.reset(BIO_new_mem_buf((void*)b64message.data(), -1));
  if (!bio) {
    return std::string();
  }
  b64.reset(BIO_new(BIO_f_base64()));
  if (!b64) {
    return std::string();
  }
  bio.reset(BIO_push(b64.release(), bio.release()));
  // Do not use newlines to flush buffer
  BIO_set_flags(bio.get(), BIO_FLAGS_BASE64_NO_NL);
  BIO_read(bio.get(), (char*)result.data(), b64message.length());
  DCHECK_LE(result.length(), decodeLen);
  if (result.length() < decodeLen) {
    return std::string();
  }
  return result;
}
std::string proxygen::Base64::encode (folly::ByteRange buffer) [static]
Definition at line 80 of file Base64.cpp.
Referenced by proxygen::HTTP1xCodec::generateWebsocketAccept(), and proxygen::HTTP1xCodec::generateWebsocketKey().
                                              {
  std::unique_ptr<BIO, BIODeleter> bio, b64;
  BUF_MEM* bufferPtr;
  b64.reset(BIO_new(BIO_f_base64()));
  if (!b64) {
    throw std::bad_alloc();
  }
  bio.reset(BIO_new(BIO_s_mem()));
  if (!bio) {
    throw std::bad_alloc();
  }
  bio.reset(BIO_push(b64.release(), bio.release()));
  // Ignore newlines - write everything in one line
  BIO_set_flags(bio.get(), BIO_FLAGS_BASE64_NO_NL);
  BIO_write(bio.get(), buffer.data(), buffer.size());
  (void)BIO_flush(bio.get());
  BIO_get_mem_ptr(bio.get(), &bufferPtr);
  (void)BIO_set_close(bio.get(), BIO_NOCLOSE);
  std::string result(bufferPtr->data, bufferPtr->length);
  BUF_MEM_free(bufferPtr);
  return result;
}
std::string proxygen::Base64::urlDecode (const std::string & b64message) [static]
Definition at line 26 of file Base64.cpp.
References proxygen::hpack::decode().
                                                          {
  std::unique_ptr<BIO, BIODeleter> bio, b64;
  uint8_t padding = (4 - urlB64message.length() % 4) % 4;
  if (padding == 3) {
    return std::string();
  }
  std::string b64message(urlB64message.length() + padding, 0);
  std::transform(
    urlB64message.begin(), urlB64message.end(), b64message.begin(),
    [](char c) {
      if (c == '-') {
        return '+';
      } else if (c == '_') {
        return '/';
      }
      return c;
    });
  for (auto i = urlB64message.length(); i < urlB64message.length() + padding;
       i++) {
    b64message[i] = '=';
  }
  return decode(b64message, padding);
}
std::string proxygen::Base64::urlEncode (folly::ByteRange buffer) [static]
Definition at line 107 of file Base64.cpp.
References encode().
                                                 {
  std::string result = encode(buffer);
  folly::StringPiece sp(result.data(), result.length());
  uint8_t padding = 0;
  std::transform(
    sp.begin(), sp.end(), result.begin(),
    [&padding](char c) {
      if (c == '+') {
        return '-';
      } else if (c == '/') {
        return '_';
      } else if (c == '=') {
        padding++;
      }
      return c;
    });
  DCHECK_LE(padding, result.length());
  result.resize(result.length() - padding);
  return result;
}
The documentation for this class was generated from the following files:
proxygen/lib/utils/Base64.h
proxygen/lib/utils/Base64.cpp