proxygen::HTTPCodecFactory Class Reference
#include <HTTPCodecFactory.h>
Public Member Functions
HTTPCodecFactory ()
virtual ~HTTPCodecFactory ()
virtual std::unique_ptr< HTTPCodec > getCodec (const std::string &protocolHint, TransportDirection direction, bool isTLS)=0
Static Public Member Functions
static std::unique_ptr< HTTPCodec > getCodec (CodecProtocol protocol, TransportDirection direction)
Detailed Description
Factory for produces HTTPCodec objects.
Definition at line 20 of file HTTPCodecFactory.h.
Constructor & Destructor Documentation
proxygen::HTTPCodecFactory::HTTPCodecFactory () [inline], [explicit]
Definition at line 22 of file HTTPCodecFactory.h.
{}
virtual proxygen::HTTPCodecFactory::~HTTPCodecFactory () [inline], [virtual]
Definition at line 23 of file HTTPCodecFactory.h.
References getCodec().
{}
Member Function Documentation
virtual std::unique_ptr<HTTPCodec> proxygen::HTTPCodecFactory::getCodec (const std::string & protocolHint, TransportDirection direction, bool isTLS) [pure virtual]
Get a codec instance
Implemented in proxygen::HTTPDefaultSessionCodecFactory , and proxygen::DefaultHTTPCodecFactory .
Referenced by proxygen::HTTPDownstreamSession::onNativeProtocolUpgrade(), and ~HTTPCodecFactory().
std::unique_ptr< HTTPCodec > proxygen::HTTPCodecFactory::getCodec (CodecProtocol protocol, TransportDirection direction) [static]
Definition at line 17 of file HTTPCodecFactory.cpp.
References proxygen::HTTP_1_1, proxygen::HTTP_2, proxygen::SPDY3, proxygen::SPDY3_1, proxygen::SPDY_3, and proxygen::SPDY_3_1.
                                                        {
  switch (protocol) {
    case CodecProtocol::HTTP_1_1:
      return std::make_unique<HTTP1xCodec>(direction);
    case CodecProtocol::SPDY_3:
      return std::make_unique<SPDYCodec>(direction, SPDYVersion::SPDY3);
    case CodecProtocol::SPDY_3_1:
      return std::make_unique<SPDYCodec>(direction, SPDYVersion::SPDY3_1);
    case CodecProtocol::HTTP_2:
      return std::make_unique<HTTP2Codec>(direction);
    default:
      LOG(FATAL) << "Unreachable";
      return nullptr;
  }
}
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/HTTPCodecFactory.h
proxygen/lib/http/codec/HTTPCodecFactory.cpp