proxygen::HPACKDecoderBase Class Reference
#include <HPACKDecoderBase.h>
Public Types
using headers_t = std::vector< HPACKHeader >
Public Member Functions
HPACKDecoderBase (uint32_t tableSize, uint32_t maxUncompressed)
HPACK::DecodeError getError () const
bool hasError () const
void setHeaderTableMaxSize (HeaderTable &table, uint32_t maxSize)
void setMaxUncompressed (uint64_t maxUncompressed)
Protected Member Functions
uint32_t emit (const HPACKHeader &header, HPACK::StreamingCallback *streamingCb, headers_t *emitted)
void completeDecode (HeaderCodec::Type type, HPACK::StreamingCallback *streamingCb, uint32_t compressedSize, uint32_t emittedSize, bool acknowledge=false)
void handleTableSizeUpdate (HPACKDecodeBuffer &dbuf, HeaderTable &table)
Protected Attributes
HPACK::DecodeError err_ {HPACK::DecodeError::NONE}
uint32_t maxTableSize_
uint64_t maxUncompressed_
Detailed Description
Common decoder functionality between HPACK and QPACK
Definition at line 24 of file HPACKDecoderBase.h.
Member Typedef Documentation
using proxygen::HPACKDecoderBase::headers_t = std::vector<HPACKHeader>
Definition at line 32 of file HPACKDecoderBase.h.
Constructor & Destructor Documentation
proxygen::HPACKDecoderBase::HPACKDecoderBase (uint32_t tableSize, uint32_t maxUncompressed) [inline]
Definition at line 26 of file HPACKDecoderBase.h.
      : maxTableSize_(tableSize)
      , maxUncompressed_(maxUncompressed) {}
Member Function Documentation
void proxygen::HPACKDecoderBase::completeDecode (HeaderCodec::Type type, HPACK::StreamingCallback * streamingCb, uint32_t compressedSize, uint32_t emittedSize, bool acknowledge = false) [protected]
Definition at line 27 of file HPACKDecoderBase.cpp.
References err_, proxygen::HPACK::HEADERS_TOO_LARGE, proxygen::HPACK::LITERAL_TOO_LARGE, proxygen::HPACK::NONE, proxygen::HPACK::StreamingCallback::onDecodeError(), proxygen::HPACK::StreamingCallback::onHeadersComplete(), proxygen::HeaderCodec::Stats::recordDecode(), proxygen::HeaderCodec::Stats::recordDecodeError(), proxygen::HeaderCodec::Stats::recordDecodeTooLarge(), and proxygen::HPACK::StreamingCallback::stats.
Referenced by proxygen::QPACKDecoder::decodeStreaming(), proxygen::HPACKDecoder::decodeStreaming(), proxygen::QPACKDecoder::decodeStreamingImpl(), and setMaxUncompressed().
                      {
  if (!streamingCb) {
    return;
  }
  if (err_ != HPACK::DecodeError::NONE) {
    if (streamingCb->stats) {
      if (err_ == HPACK::DecodeError::HEADERS_TOO_LARGE ||
          err_ == HPACK::DecodeError::LITERAL_TOO_LARGE) {
        streamingCb->stats->recordDecodeTooLarge(type);
      } else {
        streamingCb->stats->recordDecodeError(type);
      }
    }
    streamingCb->onDecodeError(err_);
  } else {
    HTTPHeaderSize decodedSize;
    decodedSize.compressed = compressedSize;
    decodedSize.uncompressed = emittedSize;
    if (streamingCb->stats) {
      streamingCb->stats->recordDecode(type, decodedSize);
    }
    streamingCb->onHeadersComplete(decodedSize, acknowledge);
  }
}
uint32_t proxygen::HPACKDecoderBase::emit (const HPACKHeader & header, HPACK::StreamingCallback * streamingCb, headers_t * emitted) [protected]
Definition at line 15 of file HPACKDecoderBase.cpp.
References proxygen::HPACKHeader::bytes(), proxygen::HPACKHeaderName::get(), proxygen::HPACKHeader::name, proxygen::HPACK::StreamingCallback::onHeader(), and proxygen::HPACKHeader::value.
Referenced by proxygen::HPACKDecoder::decodeIndexedHeader(), proxygen::QPACKDecoder::decodeIndexedHeaderQ(), proxygen::HPACKDecoder::decodeLiteralHeader(), proxygen::QPACKDecoder::decodeLiteralHeaderQ(), and setMaxUncompressed().
                                                    {
  if (streamingCb) {
    streamingCb->onHeader(header.name.get(), header.value);
  } else if (emitted) {
    // copying HPACKHeader
    emitted->emplace_back(header.name.get(), header.value);
  }
  return header.bytes();
}
HPACK::DecodeError proxygen::HPACKDecoderBase::getError () const [inline]
Definition at line 34 of file HPACKDecoderBase.h.
References err_.
Referenced by checkError(), and TEST_P().
                                    {
    return err_;
  }
void proxygen::HPACKDecoderBase::handleTableSizeUpdate (HPACKDecodeBuffer & dbuf, HeaderTable & table) [protected]
Definition at line 65 of file HPACKDecoderBase.cpp.
References proxygen::HPACKDecodeBuffer::decodeInteger(), err_, proxygen::ERROR, proxygen::HPACK::INVALID_TABLE_SIZE, maxTableSize_, proxygen::HPACK::NONE, proxygen::HeaderTable::setCapacity(), and proxygen::HPACK::TABLE_SIZE_UPDATE.
Referenced by proxygen::QPACKDecoder::decodeEncoderStreamInstruction(), proxygen::HPACKDecoder::decodeHeader(), and setMaxUncompressed().
                                                                 {
  uint64_t arg = 0;
  err_ = dbuf.decodeInteger(HPACK::TABLE_SIZE_UPDATE.prefixLength, arg);
  if (err_ != HPACK::DecodeError::NONE) {
    LOG(ERROR) << "Decode error decoding maxSize err_=" << err_;
    return;
  }
  if (arg > maxTableSize_) {
    LOG(ERROR) << "Tried to increase size of the header table to " << arg
               << " maxTableSize_=" << maxTableSize_;
    err_ = HPACK::DecodeError::INVALID_TABLE_SIZE;
    return;
  }
  VLOG(5) << "Received table size update, new size=" << arg;
  table.setCapacity(arg);
}
bool proxygen::HPACKDecoderBase::hasError () const [inline]
Definition at line 38 of file HPACKDecoderBase.h.
References err_, proxygen::HPACK::NONE, and setHeaderTableMaxSize().
Referenced by checkError(), proxygen::QPACKDecoder::decodeEncoderStream(), proxygen::QPACKDecoder::decodeEncoderStreamInstruction(), proxygen::HPACKDecoder::decodeStreaming(), proxygen::QPACKDecoder::decodeStreamingImpl(), proxygen::QPACKDecoder::drainQueue(), proxygen::hpack::encodeDecode(), TEST_F(), and TEST_P().
                        {
    return err_ != HPACK::DecodeError::NONE;
  }
void proxygen::HPACKDecoderBase::setHeaderTableMaxSize (HeaderTable & table, uint32_t maxSize)
Definition at line 57 of file HPACKDecoderBase.cpp.
References proxygen::HeaderTable::capacity(), maxTableSize_, and proxygen::HeaderTable::setCapacity().
Referenced by hasError(), proxygen::HPACKDecoder::setHeaderTableMaxSize(), and proxygen::QPACKDecoder::setHeaderTableMaxSize().
                                          {
  maxTableSize_ = maxSize;
  if (maxTableSize_ < table.capacity()) {
    CHECK(table.setCapacity(maxTableSize_));
  }
}
void proxygen::HPACKDecoderBase::setMaxUncompressed (uint64_t maxUncompressed) [inline]
Definition at line 44 of file HPACKDecoderBase.h.
References completeDecode(), emit(), handleTableSizeUpdate(), and maxUncompressed_.
Referenced by TEST().
                                                    {
    maxUncompressed_ = maxUncompressed;
  }
Member Data Documentation
HPACK::DecodeError proxygen::HPACKDecoderBase::err_ {HPACK::DecodeError::NONE} [protected]
Definition at line 62 of file HPACKDecoderBase.h.
Referenced by completeDecode(), proxygen::QPACKDecoder::decodeEncoderStream(), proxygen::HPACKDecoder::decodeIndexedHeader(), proxygen::QPACKDecoder::decodeIndexedHeaderQ(), proxygen::HPACKDecoder::decodeLiteralHeader(), proxygen::QPACKDecoder::decodeLiteralHeaderQ(), proxygen::QPACKDecoder::decodeStreaming(), proxygen::HPACKDecoder::decodeStreaming(), proxygen::QPACKDecoder::decodeStreamingImpl(), getError(), proxygen::QPACKDecoder::handleBaseIndex(), handleTableSizeUpdate(), and hasError().
uint32_t proxygen::HPACKDecoderBase::maxTableSize_ [protected]
Definition at line 63 of file HPACKDecoderBase.h.
Referenced by handleTableSizeUpdate(), and setHeaderTableMaxSize().
uint64_t proxygen::HPACKDecoderBase::maxUncompressed_ [protected]
Definition at line 64 of file HPACKDecoderBase.h.
Referenced by proxygen::QPACKDecoder::decodeBlock(), proxygen::QPACKDecoder::decodeEncoderStream(), proxygen::QPACKDecoder::decodeStreaming(), proxygen::HPACKDecoder::decodeStreaming(), proxygen::QPACKDecoder::decodeStreamingImpl(), and setMaxUncompressed().
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/compress/HPACKDecoderBase.h
proxygen/lib/http/codec/compress/HPACKDecoderBase.cpp