proxygen::compress::HPACKScheme Class Reference
#include <HPACKScheme.h>
Public Member Functions
HPACKScheme (CompressionSimulator *sim, uint32_t tableSize)
~HPACKScheme ()
std::unique_ptr< Ack > getAck (uint16_t) override
void recvAck (std::unique_ptr< Ack >) override
std::pair< FrameFlags, std::unique_ptr< folly::IOBuf > > encode (bool, std::vector< compress::Header > allHeaders, SimStats &stats) override
void decode (FrameFlags flags, std::unique_ptr< folly::IOBuf > encodedReq, SimStats &stats, SimStreamingCallback &callback) override
uint32_t getHolBlockCount () const override
Public Attributes
HPACKCodec client_ {TransportDirection::UPSTREAM}
HPACKCodec server_ {TransportDirection::DOWNSTREAM}
HPACKQueue serverQueue_ {server_}
bool allowOOO_ {false}
Additional Inherited Members
Detailed Description
Compression scheme for HPACK with a prepended sequence number
Definition at line 22 of file HPACKScheme.h.
Constructor & Destructor Documentation
proxygen::compress::HPACKScheme::HPACKScheme (CompressionSimulator * sim, uint32_t tableSize) [inline], [explicit]
Definition at line 24 of file HPACKScheme.h.
References allowOOO_, client_, proxygen::NoPathIndexingStrategy::getInstance(), server_, proxygen::HPACKCodec::setDecoderHeaderTableMaxSize(), proxygen::HeaderCodec::setEncodeHeadroom(), proxygen::HPACKCodec::setEncoderHeaderTableSize(), and proxygen::HPACKCodec::setHeaderIndexingStrategy().
      : CompressionScheme(sim) {
    client_.setEncodeHeadroom(2);
    client_.setHeaderIndexingStrategy(NoPathIndexingStrategy::getInstance());
    server_.setHeaderIndexingStrategy(NoPathIndexingStrategy::getInstance());
    client_.setEncoderHeaderTableSize(tableSize);
    server_.setDecoderHeaderTableMaxSize(tableSize);
    allowOOO_ = (tableSize == 0);
  }
proxygen::compress::HPACKScheme::~HPACKScheme () [inline]
Definition at line 34 of file HPACKScheme.h.
References proxygen::HPACKQueue::getQueuedBytes(), and serverQueue_.
                 {
    CHECK_EQ(serverQueue_.getQueuedBytes(), 0);
  }
Member Function Documentation
void proxygen::compress::HPACKScheme::decode (FrameFlags flags, std::unique_ptr< folly::IOBuf > encodedReq, SimStats & stats, SimStreamingCallback & callback) [inline], [override], [virtual]
Implements proxygen::compress::CompressionScheme .
Definition at line 60 of file HPACKScheme.h.
References proxygen::compress::FrameFlags::allowOOO, proxygen::HPACKQueue::enqueueHeaderBlock(), proxygen::HPACKQueue::getQueuedBytes(), proxygen::compress::SimStats::maxQueueBufferBytes, proxygen::compress::SimStreamingCallback::maybeMarkHolDelay(), proxygen::compress::SimStreamingCallback::requestIndex, proxygen::compress::SimStreamingCallback::seqn, and serverQueue_.
                                                       {
    folly::io::Cursor cursor(encodedReq.get());
    auto seqn = cursor.readBE<uint16_t>();
    callback.seqn = seqn;
    VLOG(1) << "Decoding request=" << callback.requestIndex
            << " header seqn=" << seqn;
    auto len = cursor.totalLength();
    encodedReq->trimStart(sizeof(uint16_t));
    serverQueue_.enqueueHeaderBlock(
        seqn, std::move(encodedReq), len, &callback, flags.allowOOO);
    callback.maybeMarkHolDelay();
    if (serverQueue_.getQueuedBytes() > stats.maxQueueBufferBytes) {
      stats.maxQueueBufferBytes = serverQueue_.getQueuedBytes();
    }
  }
std::pair<FrameFlags, std::unique_ptr<folly::IOBuf> > proxygen::compress::HPACKScheme::encode (bool , std::vector< compress::Header > allHeaders, SimStats & stats) [inline], [override], [virtual]
Implements proxygen::compress::CompressionScheme .
Definition at line 45 of file HPACKScheme.h.
References allowOOO_, client_, proxygen::compress::SimStats::compressed, proxygen::HPACKCodec::encode(), proxygen::HeaderCodec::getEncodedSize(), proxygen::compress::CompressionScheme::index, and proxygen::compress::SimStats::uncompressed.
                                {
    auto block = client_.encode(allHeaders);
    block->prepend(sizeof(uint16_t));
    folly::io::RWPrivateCursor c(block.get());
    c.writeBE<uint16_t>(index++);
    stats.uncompressed += client_.getEncodedSize().uncompressed;
    stats.compressed += client_.getEncodedSize().compressed;
    // OOO is allowed with 0 table size
    FrameFlags flags{allowOOO_};
    return {flags, std::move(block)};
  }
std::unique_ptr<Ack> proxygen::compress::HPACKScheme::getAck (uint16_t) [inline], [override], [virtual]
Implements proxygen::compress::CompressionScheme .
Definition at line 39 of file HPACKScheme.h.
                                                 {
    return nullptr;
  }
uint32_t proxygen::compress::HPACKScheme::getHolBlockCount () const [inline], [override], [virtual]
Implements proxygen::compress::CompressionScheme .
Definition at line 79 of file HPACKScheme.h.
References proxygen::HPACKQueue::getHolBlockCount(), and serverQueue_.
                                             {
    return serverQueue_.getHolBlockCount();
  }
void proxygen::compress::HPACKScheme::recvAck (std::unique_ptr< Ack >) [inline], [override], [virtual]
Implements proxygen::compress::CompressionScheme .
Definition at line 42 of file HPACKScheme.h.
                                              {
  }
Member Data Documentation
bool proxygen::compress::HPACKScheme::allowOOO_ {false}
Definition at line 86 of file HPACKScheme.h.
Referenced by encode(), and HPACKScheme().
HPACKCodec proxygen::compress::HPACKScheme::client_ {TransportDirection::UPSTREAM}
Definition at line 83 of file HPACKScheme.h.
Referenced by encode(), and HPACKScheme().
HPACKCodec proxygen::compress::HPACKScheme::server_ {TransportDirection::DOWNSTREAM}
Definition at line 84 of file HPACKScheme.h.
Referenced by HPACKScheme().
HPACKQueue proxygen::compress::HPACKScheme::serverQueue_ {server_}
Definition at line 85 of file HPACKScheme.h.
Referenced by decode(), getHolBlockCount(), and ~HPACKScheme().
The documentation for this class was generated from the following file:
proxygen/lib/http/codec/compress/experimental/simulator/HPACKScheme.h