proxygen::WheelTimerInstance Class Reference
#include <WheelTimerInstance.h>
Public Member Functions
WheelTimerInstance ()
WheelTimerInstance (std::chrono::milliseconds defaultTimeoutMS, folly::EventBase *eventBase=nullptr)
WheelTimerInstance (const WheelTimerInstance &timerInstance)
WheelTimerInstance (WheelTimerInstance &&timerInstance) noexcept
WheelTimerInstance (folly::HHWheelTimer *timer)
std::chrono::milliseconds getDefaultTimeout () const
void setDefaultTimeout (std::chrono::milliseconds timeout)
void scheduleTimeout (folly::HHWheelTimer::Callback *callback, std::chrono::milliseconds timeout)
void scheduleTimeout (folly::HHWheelTimer::Callback *callback)
WheelTimerInstance & operator= (const WheelTimerInstance &timer)
WheelTimerInstance & operator= (const WheelTimerInstance &&timer)
operator bool () const
folly::HHWheelTimer * getWheelTimer () const
Private Attributes
folly::HHWheelTimer * wheelTimerPtr_ {nullptr}
std::chrono::milliseconds defaultTimeoutMS_
Detailed Description
Definition at line 29 of file WheelTimerInstance.h.
Constructor & Destructor Documentation
proxygen::WheelTimerInstance::WheelTimerInstance ()
Definition at line 19 of file WheelTimerInstance.cpp.
                                       {
}
proxygen::WheelTimerInstance::WheelTimerInstance (std::chrono::milliseconds defaultTimeoutMS, folly::EventBase * eventBase = nullptr) [explicit]
Definition at line 31 of file WheelTimerInstance.cpp.
References wheelTimerPtr_.
                               : defaultTimeoutMS_(defaultTimeoutMS) {
  if (!eventBase) {
    eventBase = folly::EventBaseManager::get()->getEventBase();
  }
  wheelTimerPtr_ = &eventBase->timer();
}
proxygen::WheelTimerInstance::WheelTimerInstance (const WheelTimerInstance & timerInstance)
Definition at line 40 of file WheelTimerInstance.cpp.
  : wheelTimerPtr_(timerInstance.wheelTimerPtr_),
    defaultTimeoutMS_(timerInstance.defaultTimeoutMS_) {
}
proxygen::WheelTimerInstance::WheelTimerInstance (WheelTimerInstance && timerInstance) [noexcept]
Definition at line 45 of file WheelTimerInstance.cpp.
  : wheelTimerPtr_(std::move(timerInstance.wheelTimerPtr_)),
    defaultTimeoutMS_(std::move(timerInstance.defaultTimeoutMS_)) {
}
proxygen::WheelTimerInstance::WheelTimerInstance (folly::HHWheelTimer * timer) [explicit]
Definition at line 22 of file WheelTimerInstance.cpp.
References defaultTimeoutMS_.
                                                               :
  wheelTimerPtr_(timer) {
  if (timer) {
    // If you use an external timer with no default timeout set, you will get
    // a check failed if you attempt to schedule a default timeout.
    defaultTimeoutMS_ = timer->getDefaultTimeout();
  }
}
Member Function Documentation
std::chrono::milliseconds proxygen::WheelTimerInstance::getDefaultTimeout () const
Definition at line 51 of file WheelTimerInstance.cpp.
References defaultTimeoutMS_.
Referenced by proxygen::HTTPSession::createTransaction().
                                                                  {
  return defaultTimeoutMS_;
}
folly::HHWheelTimer* proxygen::WheelTimerInstance::getWheelTimer () const [inline]
Definition at line 61 of file WheelTimerInstance.h.
Referenced by proxygen::HTTPSession::createTransaction().
                                           {
    return wheelTimerPtr_;
  }
proxygen::WheelTimerInstance::operator bool () const [explicit]
Definition at line 88 of file WheelTimerInstance.cpp.
References wheelTimerPtr_.
                                        {
  return (wheelTimerPtr_ != nullptr);
}
WheelTimerInstance & proxygen::WheelTimerInstance::operator= (const WheelTimerInstance & timer)
Definition at line 75 of file WheelTimerInstance.cpp.
References defaultTimeoutMS_, and wheelTimerPtr_.
                                                                             {
  wheelTimerPtr_ = t.wheelTimerPtr_;
  defaultTimeoutMS_ = t.defaultTimeoutMS_;
  return *this;
}
WheelTimerInstance & proxygen::WheelTimerInstance::operator= (const WheelTimerInstance && timer)
Definition at line 82 of file WheelTimerInstance.cpp.
References defaultTimeoutMS_, and wheelTimerPtr_.
                                                {
  wheelTimerPtr_ = std::move(timer.wheelTimerPtr_);
  defaultTimeoutMS_ = std::move(timer.defaultTimeoutMS_);
  return *this;
}
void proxygen::WheelTimerInstance::scheduleTimeout (folly::HHWheelTimer::Callback * callback, std::chrono::milliseconds timeout)
Definition at line 59 of file WheelTimerInstance.cpp.
References wheelTimerPtr_.
Referenced by proxygen::HTTPSession::onConnectionSendWindowClosed(), proxygen::HTTPSession::onWriteSuccess(), proxygen::HTTPSession::readTimeoutExpired(), proxygen::HTTPSession::runLoopCallback(), and scheduleTimeout().
                                   {
  if (wheelTimerPtr_) {
    wheelTimerPtr_->scheduleTimeout(callback, timeout);
  } else {
    VLOG(2) << "Ingoring scheduleTimeout on an empty WheelTimerInstance";
  }
}
void proxygen::WheelTimerInstance::scheduleTimeout (folly::HHWheelTimer::Callback * callback)
Definition at line 69 of file WheelTimerInstance.cpp.
References defaultTimeoutMS_, and scheduleTimeout().
                                         {
  CHECK_GE(defaultTimeoutMS_.count(), 0);
  scheduleTimeout(callback, defaultTimeoutMS_);
}
void proxygen::WheelTimerInstance::setDefaultTimeout (std::chrono::milliseconds timeout)
Definition at line 55 of file WheelTimerInstance.cpp.
References defaultTimeoutMS_.
                                                                        {
  defaultTimeoutMS_ = timeout;
}
Member Data Documentation
std::chrono::milliseconds proxygen::WheelTimerInstance::defaultTimeoutMS_ [private]
Definition at line 71 of file WheelTimerInstance.h.
Referenced by getDefaultTimeout(), operator=(), scheduleTimeout(), setDefaultTimeout(), and WheelTimerInstance().
folly::HHWheelTimer* proxygen::WheelTimerInstance::wheelTimerPtr_ {nullptr} [private]
Definition at line 67 of file WheelTimerInstance.h.
Referenced by operator bool(), operator=(), scheduleTimeout(), and WheelTimerInstance().
The documentation for this class was generated from the following files:
proxygen/lib/utils/WheelTimerInstance.h
proxygen/lib/utils/WheelTimerInstance.cpp