TestPriorityAdapter Class Reference
Public Member Functions
virtual folly::Optional< const HTTPMessage::HTTPPriority > getHTTPPriority (uint8_t level) override
virtual ~TestPriorityAdapter ()=default
Public Attributes
std::map< uint8_t, HTTPMessage::HTTPPriority > priorityMap_
HTTPMessage::HTTPPriority minPriority_ {std::make_tuple(0, false, 0)}
HTTPCodec::StreamID parentId_ {0}
HTTPCodec::StreamID hiPriId_ {0}
HTTPCodec::StreamID loPriId_ {0}
HTTPMessage::HTTPPriority hiPri_ {std::make_tuple(0, false, 0)}
HTTPMessage::HTTPPriority loPri_ {std::make_tuple(0, false, 0)}
Detailed Description
Definition at line 51 of file HTTPUpstreamSessionTest.cpp.
Constructor & Destructor Documentation
virtual TestPriorityAdapter::~TestPriorityAdapter () [virtual], [default]
Member Function Documentation
virtual folly::Optional<const HTTPMessage::HTTPPriority> TestPriorityAdapter::getHTTPPriority (uint8_t level) [inline], [override], [virtual]
Definition at line 53 of file HTTPUpstreamSessionTest.cpp.
                              {
    if (priorityMap_.empty()) {
      return folly::none;
    }
    auto it = priorityMap_.find(level);
    if (it == priorityMap_.end()) {
      return minPriority_;
    }
    return it->second;
  }
Member Data Documentation
HTTPMessage::HTTPPriority TestPriorityAdapter::hiPri_ {std::make_tuple(0, false, 0)}
Definition at line 72 of file HTTPUpstreamSessionTest.cpp.
Referenced by TestPriorityMapBuilder::createVirtualStreams().
HTTPCodec::StreamID TestPriorityAdapter::hiPriId_ {0}
Definition at line 70 of file HTTPUpstreamSessionTest.cpp.
Referenced by TestPriorityMapBuilder::createVirtualStreams().
HTTPMessage::HTTPPriority TestPriorityAdapter::loPri_ {std::make_tuple(0, false, 0)}
Definition at line 73 of file HTTPUpstreamSessionTest.cpp.
Referenced by TestPriorityMapBuilder::createVirtualStreams().
HTTPCodec::StreamID TestPriorityAdapter::loPriId_ {0}
Definition at line 71 of file HTTPUpstreamSessionTest.cpp.
Referenced by TestPriorityMapBuilder::createVirtualStreams().
HTTPMessage::HTTPPriority TestPriorityAdapter::minPriority_ {std::make_tuple(0, false, 0)}
Definition at line 68 of file HTTPUpstreamSessionTest.cpp.
Referenced by TestPriorityMapBuilder::createVirtualStreams().
HTTPCodec::StreamID TestPriorityAdapter::parentId_ {0}
Definition at line 69 of file HTTPUpstreamSessionTest.cpp.
Referenced by TestPriorityMapBuilder::createVirtualStreams().
std::map<uint8_t, HTTPMessage::HTTPPriority> TestPriorityAdapter::priorityMap_
Definition at line 67 of file HTTPUpstreamSessionTest.cpp.
Referenced by TestPriorityMapBuilder::createVirtualStreams().
The documentation for this class was generated from the following file:
proxygen/lib/http/session/test/HTTPUpstreamSessionTest.cpp