proxygen::StateMachine< T > Class Template Reference
#include <StateMachine.h>
Public Types
using State = typename T::State
using Event = typename T::Event
Static Public Member Functions
static State getNewInstance ()
static bool transit (State &state, Event event)
static bool canTransit (const State state, Event event)
Detailed Description
template<typename T>
*
class proxygen::StateMachine< T >
Definition at line 18 of file StateMachine.h.
Member Typedef Documentation
template<typename T > using proxygen::StateMachine< T >::Event = typename T::Event
Definition at line 21 of file StateMachine.h.
template<typename T > using proxygen::StateMachine< T >::State = typename T::State
Definition at line 20 of file StateMachine.h.
Member Function Documentation
template<typename T > static bool proxygen::StateMachine< T >::canTransit (const State state, Event event) [inline], [static]
Definition at line 44 of file StateMachine.h.
Referenced by proxygen::HTTPTransaction::canSendHeaders().
                                                         {
    bool ok;
    std::tie(std::ignore, ok) = T::find(state, event);
    return ok;
  }
template<typename T > static State proxygen::StateMachine< T >::getNewInstance () [inline], [static]
Definition at line 23 of file StateMachine.h.
                                {
    return T::getInitialState();
  }
template<typename T > static bool proxygen::StateMachine< T >::transit (State & state, Event event) [inline], [static]
Definition at line 27 of file StateMachine.h.
References proxygen::ERROR.
Referenced by EgressStateMachineFixture::fail(), IngressStateMachineFixture::fail(), EgressStateMachineFixture::follow(), IngressStateMachineFixture::follow(), proxygen::HTTPTransaction::sendBody(), proxygen::HTTPTransaction::sendBodyNow(), proxygen::HTTPTransaction::sendChunkHeader(), proxygen::HTTPTransaction::sendChunkTerminator(), proxygen::HTTPTransaction::sendEOM(), proxygen::HTTPTransaction::sendEOMNow(), proxygen::HTTPTransaction::sendHeadersWithOptionalEOM(), proxygen::HTTPTransaction::sendTrailers(), and proxygen::HTTPTransaction::validateIngressStateTransition().
                                                 {
    bool ok;
    State newState;
    std::tie(newState, ok) = T::find(state, event);
    if (!ok) {
      LOG(ERROR) << T::getName() << ": invalid transition tried: " << state
                 << " " << event;
      return false;
    } else {
      VLOG(6) << T::getName() << ": transitioning from " << state << " to "
              << newState;
      state = newState;
      return true;
    }
  }
The documentation for this class was generated from the following file:
proxygen/lib/utils/StateMachine.h