proxygen::HeaderCodec::Stats Class Reference
#include <HeaderCodec.h>
Public Member Functions
Stats ()
virtual ~Stats ()
virtual void recordEncode (Type type, HTTPHeaderSize &size)=0
virtual void recordDecode (Type type, HTTPHeaderSize &size)=0
virtual void recordDecodeError (Type type)=0
virtual void recordDecodeTooLarge (Type type)=0
Detailed Description
Definition at line 45 of file HeaderCodec.h.
Constructor & Destructor Documentation
proxygen::HeaderCodec::Stats::Stats () [inline]
Definition at line 47 of file HeaderCodec.h.
{}
virtual proxygen::HeaderCodec::Stats::~Stats () [inline], [virtual]
Definition at line 48 of file HeaderCodec.h.
{}
Member Function Documentation
virtual void proxygen::HeaderCodec::Stats::recordDecode (Type type, HTTPHeaderSize & size) [pure virtual]
Implemented in proxygen::hpack::TestHeaderCodecStats .
Referenced by proxygen::HPACKDecoderBase::completeDecode(), and proxygen::GzipHeaderCodec::decode().
virtual void proxygen::HeaderCodec::Stats::recordDecodeError (Type type) [pure virtual]
Implemented in proxygen::hpack::TestHeaderCodecStats .
Referenced by proxygen::HPACKDecoderBase::completeDecode().
virtual void proxygen::HeaderCodec::Stats::recordDecodeTooLarge (Type type) [pure virtual]
Implemented in proxygen::hpack::TestHeaderCodecStats .
Referenced by proxygen::HPACKDecoderBase::completeDecode().
virtual void proxygen::HeaderCodec::Stats::recordEncode (Type type, HTTPHeaderSize & size) [pure virtual]
Implemented in proxygen::hpack::TestHeaderCodecStats .
Referenced by proxygen::GzipHeaderCodec::encode(), proxygen::HPACKCodec::recordCompressedSize(), and proxygen::QPACKCodec::recordCompressedSize().
The documentation for this class was generated from the following file:
proxygen/lib/http/codec/compress/HeaderCodec.h