proxygen::RequestWorker::FinishCallback Class Reference
#include <RequestWorker.h>
Public Member Functions
virtual ~FinishCallback () noexcept
virtual void workerStarted (RequestWorker *)=0
virtual void workerFinished (RequestWorker *)=0
Detailed Description
Definition at line 27 of file RequestWorker.h.
Constructor & Destructor Documentation
virtual proxygen::RequestWorker::FinishCallback::~FinishCallback () [inline], [virtual], [noexcept]
Definition at line 29 of file RequestWorker.h.
References proxygen::RequestWorker::nextRequestId(), proxygen::RequestWorker::RequestWorker(), workerFinished(), and workerStarted().
{}
Member Function Documentation
virtual void proxygen::RequestWorker::FinishCallback::workerFinished (RequestWorker *) [pure virtual]
Referenced by proxygen::RequestWorker::cleanup(), and ~FinishCallback().
virtual void proxygen::RequestWorker::FinishCallback::workerStarted (RequestWorker *) [pure virtual]
Referenced by proxygen::RequestWorker::setup(), and ~FinishCallback().
The documentation for this class was generated from the following file:
proxygen/lib/services/RequestWorker.h