proxygen::MockByteEventTracker Class Reference
#include <MockByteEventTracker.h>
Public Member Functions
MockByteEventTracker (Callback *callback)
MOCK_METHOD3 (addPingByteEvent, void(size_t, TimePoint, uint64_t))
MOCK_METHOD2 (addFirstBodyByteEvent, void(uint64_t, HTTPTransaction *))
MOCK_METHOD2 (addFirstHeaderByteEvent, void(uint64_t, HTTPTransaction *))
MOCK_METHOD0 (drainByteEvents, size_t())
MOCK_METHOD2 (processByteEvents, bool(std::shared_ptr< ByteEventTracker >, uint64_t))
GMOCK_METHOD2_ (, noexcept,, addTrackedByteEvent, void(HTTPTransaction *, uint64_t))
GMOCK_METHOD2_ (, noexcept,, addLastByteEvent, void(HTTPTransaction *, uint64_t))
MOCK_METHOD3 (preSend, uint64_t(bool *, bool *, uint64_t))
Additional Inherited Members
Detailed Description
Definition at line 17 of file MockByteEventTracker.h.
Constructor & Destructor Documentation
proxygen::MockByteEventTracker::MockByteEventTracker (Callback * callback) [inline], [explicit]
Definition at line 19 of file MockByteEventTracker.h.
References proxygen::ByteEventTracker::addFirstBodyByteEvent(), proxygen::ByteEventTracker::addFirstHeaderByteEvent(), proxygen::ByteEventTracker::addLastByteEvent(), proxygen::ByteEventTracker::addPingByteEvent(), proxygen::ByteEventTracker::addTrackedByteEvent(), proxygen::ByteEventTracker::drainByteEvents(), GMOCK_METHOD2_(), MOCK_METHOD0(), MOCK_METHOD2(), MOCK_METHOD3(), proxygen::ByteEventTracker::preSend(), and proxygen::ByteEventTracker::processByteEvents().
      : ByteEventTracker(callback) {}
Member Function Documentation
proxygen::MockByteEventTracker::GMOCK_METHOD2_ (noexcept , addTrackedByteEvent , void(HTTPTransaction *, uint64_t))
Referenced by MockByteEventTracker().
proxygen::MockByteEventTracker::GMOCK_METHOD2_ (noexcept , addLastByteEvent , void(HTTPTransaction *, uint64_t))
proxygen::MockByteEventTracker::MOCK_METHOD0 (drainByteEvents , size_t())
Referenced by MockByteEventTracker().
proxygen::MockByteEventTracker::MOCK_METHOD2 (addFirstBodyByteEvent , void(uint64_t, HTTPTransaction *))
Referenced by MockByteEventTracker().
proxygen::MockByteEventTracker::MOCK_METHOD2 (addFirstHeaderByteEvent , void(uint64_t, HTTPTransaction *))
proxygen::MockByteEventTracker::MOCK_METHOD2 (processByteEvents , bool(std::shared_ptr< ByteEventTracker >, uint64_t))
proxygen::MockByteEventTracker::MOCK_METHOD3 (addPingByteEvent , void(size_t, TimePoint, uint64_t))
Referenced by MockByteEventTracker().
proxygen::MockByteEventTracker::MOCK_METHOD3 (preSend , uint64_t(bool *, bool *, uint64_t))
The documentation for this class was generated from the following file:
proxygen/lib/http/session/test/MockByteEventTracker.h