proxygen::Exception Class Reference
#include <Exception.h>
Public Member Functions
Exception (std::string const &msg)
Exception (const Exception &)
Exception (Exception &other)
Exception (Exception &&) noexcept
template<typename... Args>
Exception (Args &&...args)
~Exception (void) noexceptoverride
const char * what (void) const noexceptoverride
void setCode (int code)
int getCode () const
bool hasProxygenError () const
void setProxygenError (ProxygenError proxygenError)
ProxygenError getProxygenError () const
Private Attributes
const std::string msg_
int code_
ProxygenError proxygenError_ {kErrorNone}
Detailed Description
Base class for all exceptions.
Definition at line 22 of file Exception.h.
Constructor & Destructor Documentation
proxygen::Exception::Exception (std::string const & msg) [explicit]
Definition at line 14 of file Exception.cpp.
Referenced by Exception().
: msg_(msg), code_(0) {}
proxygen::Exception::Exception (const Exception & other)
Definition at line 16 of file Exception.cpp.
    : msg_(other.msg_),
      code_(other.code_),
      proxygenError_(other.proxygenError_) {}
proxygen::Exception::Exception (Exception & other) [inline]
Definition at line 26 of file Exception.h.
References Exception().
: Exception(folly::as_const(other)) {} // @nolint
proxygen::Exception::Exception (Exception && other) [noexcept]
Definition at line 21 of file Exception.cpp.
    : msg_(other.msg_),
      code_(other.code_),
      proxygenError_(other.proxygenError_) {}
template<typename... Args> proxygen::Exception::Exception (Args &&... args) [inline], [explicit]
Definition at line 30 of file Exception.h.
      : msg_(folly::to<std::string>(std::forward<Args>(args)...)), code_(0) {}
proxygen::Exception::~Exception (void) [inline], [override], [noexcept]
Definition at line 33 of file Exception.h.
References what().
{}
Member Function Documentation
int proxygen::Exception::getCode () const [inline]
Definition at line 41 of file Exception.h.
References code_.
{ return code_; }
ProxygenError proxygen::Exception::getProxygenError () const [inline]
Definition at line 50 of file Exception.h.
References proxygenError_.
Referenced by proxygen::HTTPSessionBase::handleErrorDirectly(), proxygen::HTTPTransaction::onError(), proxygen::operator<<(), TEST_F(), MockCodecDownstreamTest::testConnFlowControlBlocked(), and TYPED_TEST_P().
{ return proxygenError_; }
bool proxygen::Exception::hasProxygenError () const [inline]
Definition at line 44 of file Exception.h.
References proxygen::kErrorNone, and proxygenError_.
Referenced by TEST_F().
{ return (proxygenError_ != kErrorNone); }
void proxygen::Exception::setCode (int code) [inline]
Definition at line 39 of file Exception.h.
References code_.
{ code_ = code; }
void proxygen::Exception::setProxygenError (ProxygenError proxygenError) [inline]
Definition at line 46 of file Exception.h.
References proxygenError_.
Referenced by proxygen::HTTPSession::errorOnTransactionIds(), proxygen::SPDYCodec::failSession(), proxygen::SPDYCodec::failStream(), proxygen::HTTPSession::onAbort(), proxygen::HTTPTransaction::onEgressTimeout(), proxygen::HTTPSession::onGoaway(), proxygen::HTTPChecks::onHeadersComplete(), proxygen::HTTPTransaction::onIngressBody(), proxygen::HTTPTransaction::onIngressEOM(), proxygen::HTTPTransaction::onIngressTimeout(), proxygen::HTTP1xCodec::onParserError(), proxygen::HTTPTransaction::sendBodyNow(), proxygen::HTTPSession::shutdownTransport(), TEST(), TEST_F(), and proxygen::HTTPTransaction::validateIngressStateTransition().
                                                     {
    proxygenError_ = proxygenError;
  }
const char * proxygen::Exception::what (void) const [override], [noexcept]
Definition at line 26 of file Exception.cpp.
References msg_.
Referenced by proxygen::HTTPCodecPrinter::onError(), proxygen::HTTPSession::onSessionParseError(), proxygen::operator<<(), TEST_F(), TYPED_TEST_P(), and ~Exception().
{ return msg_.c_str(); }
Member Data Documentation
int proxygen::Exception::code_ [private]
Definition at line 54 of file Exception.h.
Referenced by getCode(), and setCode().
const std::string proxygen::Exception::msg_ [private]
Definition at line 53 of file Exception.h.
Referenced by what().
ProxygenError proxygen::Exception::proxygenError_ {kErrorNone} [private]
Definition at line 55 of file Exception.h.
Referenced by getProxygenError(), hasProxygenError(), and setProxygenError().
The documentation for this class was generated from the following files:
proxygen/lib/utils/Exception.h
proxygen/lib/utils/Exception.cpp