proxygen::HTTPDownstreamSession Class Reference
#include <HTTPDownstreamSession.h>
Public Member Functions
HTTPDownstreamSession (const WheelTimerInstance &timeout, folly::AsyncTransportWrapper::UniquePtr &&sock, const folly::SocketAddress &localAddr, const folly::SocketAddress &peerAddr, HTTPSessionController *controller, std::unique_ptr< HTTPCodec > codec, const wangle::TransportInfo &tinfo, InfoCallback *infoCallback)
HTTPDownstreamSession (folly::HHWheelTimer *timer, folly::AsyncTransportWrapper::UniquePtr &&sock, const folly::SocketAddress &localAddr, const folly::SocketAddress &peerAddr, HTTPSessionController *controller, std::unique_ptr< HTTPCodec > codec, const wangle::TransportInfo &tinfo, InfoCallback *infoCallback)
void startNow () override
Private Member Functions
~HTTPDownstreamSession () override
void setupOnHeadersComplete (HTTPTransaction *txn, HTTPMessage *msg) override
HTTPTransaction::Handler * getTransactionTimeoutHandler (HTTPTransaction *txn) override
void onHeadersSent (const HTTPMessage &headers, bool codecWasReusable) override
bool allTransactionsStarted () const override
bool onNativeProtocolUpgrade (HTTPCodec::StreamID streamID, CodecProtocol protocol, const std::string &protocolString, HTTPMessage &msg) override
bool isDetachable (bool) const override
void attachThreadLocals (folly::EventBase *, folly::SSLContextPtr, const WheelTimerInstance &, HTTPSessionStats *, FilterIteratorFn, HeaderCodec::Stats *, HTTPSessionController *) override
void detachThreadLocals (bool) override
HTTPTransaction * newTransaction (HTTPTransaction::Handler *) override
bool isReplaySafe () const override
bool isReusable () const override
bool isClosing () const override
Additional Inherited Members
Detailed Description
Definition at line 18 of file HTTPDownstreamSession.h.
Constructor & Destructor Documentation
proxygen::HTTPDownstreamSession::HTTPDownstreamSession (const WheelTimerInstance & timeout, folly::AsyncTransportWrapper::UniquePtr && sock, const folly::SocketAddress & localAddr, const folly::SocketAddress & peerAddr, HTTPSessionController * controller, std::unique_ptr< HTTPCodec > codec, const wangle::TransportInfo & tinfo, InfoCallback * infoCallback) [inline]
Parameters
sock An open socket on which any applicable TLS handshaking has been completed already.
localAddr Address and port of the local end of the socket.
peerAddr Address and port of the remote end of the socket.
codec A codec with which to parse/generate messages in whatever HTTP-like wire format this session needs.
Definition at line 28 of file HTTPDownstreamSession.h.
References proxygen::HTTPSessionBase::codec_, proxygen::DOWNSTREAM, and proxygen::HTTPCodec::getTransportDirection().
                                 :
    HTTPSession(timeout, std::move(sock), localAddr, peerAddr,
                CHECK_NOTNULL(controller), std::move(codec), tinfo,
                infoCallback) {
      CHECK_EQ(codec_->getTransportDirection(), TransportDirection::DOWNSTREAM);
  }
proxygen::HTTPDownstreamSession::HTTPDownstreamSession (folly::HHWheelTimer * timer, folly::AsyncTransportWrapper::UniquePtr && sock, const folly::SocketAddress & localAddr, const folly::SocketAddress & peerAddr, HTTPSessionController * controller, std::unique_ptr< HTTPCodec > codec, const wangle::TransportInfo & tinfo, InfoCallback * infoCallback) [inline]
Definition at line 44 of file HTTPDownstreamSession.h.
References allTransactionsStarted(), getTransactionTimeoutHandler(), onHeadersSent(), onNativeProtocolUpgrade(), setupOnHeadersComplete(), startNow(), streamID, and ~HTTPDownstreamSession().
                                 :
    HTTPDownstreamSession(WheelTimerInstance(timer), std::move(sock), localAddr,
        peerAddr,CHECK_NOTNULL(controller), std::move(codec), tinfo,
        infoCallback) {
  }
proxygen::HTTPDownstreamSession::~HTTPDownstreamSession () [override], [private]
Definition at line 20 of file HTTPDownstreamSession.cpp.
Referenced by HTTPDownstreamSession().
                                              {
}
Member Function Documentation
bool proxygen::HTTPDownstreamSession::allTransactionsStarted () const [override], [private], [virtual]
Implements proxygen::HTTPSession .
Definition at line 96 of file HTTPDownstreamSession.cpp.
References proxygen::HTTPSession::transactions_.
Referenced by HTTPDownstreamSession().
                                                         {
  for (const auto& txn: transactions_) {
    if (txn.second.isPushed() && !txn.second.isEgressStarted()) {
      return false;
    }
  }
  return true;
}
void proxygen::HTTPDownstreamSession::attachThreadLocals (folly::EventBase * , folly::SSLContextPtr , const WheelTimerInstance & , HTTPSessionStats * , FilterIteratorFn , HeaderCodec::Stats * , HTTPSessionController *) [inline], [override], [private], [virtual]
Implements proxygen::HTTPSessionBase .
Definition at line 95 of file HTTPDownstreamSession.h.
                                                           {
    LOG(FATAL) << __func__ << " is an upstream interface";
  }
void proxygen::HTTPDownstreamSession::detachThreadLocals (bool) [inline], [override], [private], [virtual]
Implements proxygen::HTTPSessionBase .
Definition at line 105 of file HTTPDownstreamSession.h.
                                         {
    LOG(FATAL) << __func__ << " is an upstream interface";
  }
HTTPTransaction::Handler * proxygen::HTTPDownstreamSession::getTransactionTimeoutHandler (HTTPTransaction * txn) [override], [private], [virtual]
Called by transactionTimeout() in the downstream case. This function ensures that a handler is set for the transaction.
Implements proxygen::HTTPSession .
Definition at line 65 of file HTTPDownstreamSession.cpp.
References proxygen::HTTPSessionBase::getController(), proxygen::HTTPSession::getLocalAddress(), and proxygen::HTTPSessionController::getTransactionTimeoutHandler().
Referenced by HTTPDownstreamSession().
                        {
  return getController()->getTransactionTimeoutHandler(txn, getLocalAddress());
}
bool proxygen::HTTPDownstreamSession::isClosing () const [inline], [override], [private], [virtual]
Returns true if the session is shutting down
Implements proxygen::HTTPSessionBase .
Definition at line 124 of file HTTPDownstreamSession.h.
                                  {
    LOG(FATAL) << __func__ << " is an upstream interface";
    return false;
  }
bool proxygen::HTTPDownstreamSession::isDetachable (bool) const [inline], [override], [private], [virtual]
Implements proxygen::HTTPSessionBase .
Definition at line 90 of file HTTPDownstreamSession.h.
                                         {
    LOG(FATAL) << __func__ << " is an upstream interface";
    return false;
  }
bool proxygen::HTTPDownstreamSession::isReplaySafe () const [inline], [override], [private], [virtual]
Implements proxygen::HTTPSessionBase .
Definition at line 114 of file HTTPDownstreamSession.h.
                                     {
    LOG(FATAL) << __func__ << " is an upstream interface";
    return false;
  }
bool proxygen::HTTPDownstreamSession::isReusable () const [inline], [override], [private], [virtual]
Returns true if the underlying transport can be used again in a new request.
Implements proxygen::HTTPSessionBase .
Definition at line 119 of file HTTPDownstreamSession.h.
                                   {
    LOG(FATAL) << __func__ << " is an upstream interface";
    return false;
  }
HTTPTransaction* proxygen::HTTPDownstreamSession::newTransaction (HTTPTransaction::Handler * handler) [inline], [override], [private], [virtual]
Creates a new transaction on this upstream session. Invoking this function also has the side-affect of starting reads after this event loop completes.
Parameters
handler The request handler to attach to this transaction. It must not be null.
Implements proxygen::HTTPSessionBase .
Definition at line 109 of file HTTPDownstreamSession.h.
                                                                    {
    LOG(FATAL) << __func__ << " is an upstream interface";
    return nullptr;
  }
void proxygen::HTTPDownstreamSession::onHeadersSent (const HTTPMessage & headers, bool codecWasReusable) [override], [private], [virtual]
Invoked when headers have been sent.
Reimplemented from proxygen::HTTPSession .
Definition at line 71 of file HTTPDownstreamSession.cpp.
References proxygen::HTTPSessionBase::codec_, proxygen::ERR_RESP, proxygen::HTTPMessage::getStatusCode(), proxygen::HTTPCodec::isReusable(), proxygen::REMOTE_ERROR, proxygen::HTTPSessionBase::setCloseReason(), statusCode, and proxygen::UNKNOWN.
Referenced by HTTPDownstreamSession().
                                                            {
  if (!codec_->isReusable()) {
    // If the codec turned unreusable, some thing wrong must have happened.
    // Basically, the proxy decides the connection is not reusable.
    // e.g, an error message is being sent with Connection: close
    if (codecWasReusable) {
      uint32_t statusCode = headers.getStatusCode();
      if (statusCode >= 500) {
        setCloseReason(ConnectionCloseReason::REMOTE_ERROR);
      } else {
        if (statusCode >= 400) {
          setCloseReason(ConnectionCloseReason::ERR_RESP);
        } else {
          // should not be here
          setCloseReason(ConnectionCloseReason::UNKNOWN);
        }
      }
    } else {
      // shouldn't happen... this case is detected by REQ_NOTREUSABLE
      setCloseReason(ConnectionCloseReason::UNKNOWN);
    }
  }
}
bool proxygen::HTTPDownstreamSession::onNativeProtocolUpgrade (HTTPCodec::StreamID , CodecProtocol , const std::string & , HTTPMessage &) [override], [private], [virtual]
Called upon receipt of a valid protocol switch. Return false if protocol switch could not be completed.
Reimplemented from proxygen::HTTPCodec::Callback .
Definition at line 106 of file HTTPDownstreamSession.cpp.
References proxygen::HTTPCodec::addPriorityNodes(), proxygen::HTTPSessionBase::codec_, proxygen::DOWNSTREAM, proxygen::HTTPSession::findTransaction(), proxygen::HTTPCodecFactory::getCodec(), proxygen::HTTPMessage::getHeaders(), proxygen::HTTPSession::onNativeProtocolUpgradeImpl(), proxygen::HTTPHeaders::set(), proxygen::HTTPMessage::setHTTPVersion(), proxygen::HTTPMessage::setStatusCode(), proxygen::HTTPMessage::setStatusMessage(), proxygen::HTTPSession::txnEgressQueue_, and proxygen::HTTPSession::writeBuf_.
Referenced by HTTPDownstreamSession().
                    {
  VLOG(4) << *this << " onNativeProtocolUpgrade streamID=" << streamID <<
    " protocol=" << protocolString;
  auto txn = findTransaction(streamID);
  CHECK(txn);
  if (txn->canSendHeaders()) {
    // Create the new Codec
    auto codec = HTTPCodecFactory::getCodec(protocol,
                                            TransportDirection::DOWNSTREAM);
    CHECK(codec);
    if (!codec->onIngressUpgradeMessage(msg)) {
      VLOG(4) << *this << " codec rejected upgrade";
      return false;
    }
    // Send a 101 Switching Protocols message while we still have HTTP codec
    // Note: it's possible that the client timed out waiting for a
    // 100-continue and ended up here first. In this case the 100 may go
    // out in the new protocol
    HTTPMessage switchingProtos;
    switchingProtos.setHTTPVersion(1, 1);
    switchingProtos.setStatusCode(101);
    switchingProtos.setStatusMessage("Switching Protocols");
    switchingProtos.getHeaders().set(HTTP_HEADER_UPGRADE, protocolString);
    switchingProtos.getHeaders().set(HTTP_HEADER_CONNECTION, "Upgrade");
    txn->sendHeaders(switchingProtos);
    // no sendEOM for 1xx
    // This will actually switch the protocol
    bool ret = HTTPSession::onNativeProtocolUpgradeImpl(
      streamID, std::move(codec), protocolString);
    if (ret) {
      codec_->addPriorityNodes(txnEgressQueue_, writeBuf_, 0);
    }
    return ret;
  } else {
    VLOG(4) << *this << " plaintext upgrade failed due to early response";
    return false;
  }
}
void proxygen::HTTPDownstreamSession::setupOnHeadersComplete (HTTPTransaction * txn, HTTPMessage * msg) [override], [private], [virtual]
Called by onHeadersComplete().
Implements proxygen::HTTPSession .
Definition at line 33 of file HTTPDownstreamSession.cpp.
References proxygen::HTTPSessionBase::codec_, proxygen::ENABLE_EX_HEADERS, proxygen::HTTPSessionBase::getController(), proxygen::HTTPTransaction::getControlStream(), proxygen::HTTPTransaction::getHandler(), proxygen::HTTPTransaction::getID(), proxygen::HTTPCodec::getIngressSettings(), proxygen::HTTPSessionController::getRequestHandler(), proxygen::HTTPTransaction::setHandler(), proxygen::HTTPSession::setNewTransactionPauseState(), and settings.
Referenced by HTTPDownstreamSession().
                                                                {
  VLOG(5) << "setupOnHeadersComplete txn=" << txn << ", id=" << txn->getID()
          << ", handlder=" << txn->getHandler() << ", msg=" << msg;
  if (txn->getHandler()) {
    // handler is installed before setupOnHeadersComplete callback. It must be
    // an EX_HEADERS from client side, and ENABLE_EX_HEADERS == 1
    const auto* settings = codec_->getIngressSettings();
    CHECK(settings && settings->getSetting(SettingsId::ENABLE_EX_HEADERS, 0));
    CHECK(txn->getControlStream());
    return;
  }
  // We need to find a Handler to process the transaction.
  // Note: The handler is responsible for freeing itself
  // when it has finished processing the transaction. The
  // transaction is responsible for freeing itself when both the
  // ingress and egress messages have completed (or failed).
  HTTPTransaction::Handler* handler = nullptr;
  // In the general case, delegate to the handler factory to generate
  // a handler for the transaction.
  handler = getController()->getRequestHandler(*txn, msg);
  CHECK(handler);
  DestructorGuard dg(this);
  auto txnID = txn->getID();
  txn->setHandler(handler);
  setNewTransactionPauseState(txnID);
}
void proxygen::HTTPDownstreamSession::startNow () [override], [virtual]
Start reading from the transport and send any introductory messages to the remote side. This function must be called once per session to begin reads.
Implements proxygen::HTTPSessionBase .
Definition at line 24 of file HTTPDownstreamSession.cpp.
References proxygen::HTTPCodec::addPriorityNodes(), proxygen::HTTPSessionBase::codec_, proxygen::HTTPSession::startNow(), proxygen::HTTPSession::txnEgressQueue_, and proxygen::HTTPSession::writeBuf_.
Referenced by HTTPDownstreamSession(), proxygen::HTTPSessionAcceptor::onNewConnection(), and TEST().
                                {
  // Create virtual nodes should happen before startNow since ingress may come
  // before we can finish startNow. Since maxLevel = 0, this is a no-op unless
  // SPDY is used. And no frame will be sent to peer, so ignore returned value.
  codec_->addPriorityNodes(txnEgressQueue_, writeBuf_, 0);
  HTTPSession::startNow();
}
The documentation for this class was generated from the following files:
proxygen/lib/http/session/HTTPDownstreamSession.h
proxygen/lib/http/session/HTTPDownstreamSession.cpp