proxygen::HTTPArchive Class Reference
#include <HTTPArchive.h>
Static Public Member Functions
static std::vector< std::vector< HPACKHeader > > convertToHPACK (const std::vector< HTTPMessage > &msgs)
static std::unique_ptr< HTTPArchive > fromFile (const std::string &filename)
static std::unique_ptr< HTTPArchive > fromPublicFile (const std::string &fname)
static uint32_t getSize (const HTTPMessage &msg)
static uint32_t getSize (const std::vector< HPACKHeader > &headers)
Public Attributes
std::vector< HTTPMessage > requests
std::vector< HTTPMessage > responses
Detailed Description
Definition at line 22 of file HTTPArchive.h.
Member Function Documentation
std::vector< std::vector< HPACKHeader > > proxygen::HTTPArchive::convertToHPACK (const std::vector< HTTPMessage > & msgs) [static]
Definition at line 210 of file HTTPArchive.cpp.
References proxygen::HTTPHeaders::forEach(), and proxygen::HTTPMessage::getHeaders().
                                      {
  std::vector<std::vector<HPACKHeader>> result;
  for (const HTTPMessage& msg: msgs) {
    std::vector<HPACKHeader> headers;
    msg.getHeaders().forEach(
      [&headers] (const string& name, const string& value) {
        headers.emplace_back(name, value);
      });
    result.emplace_back(std::move(headers));
  }
  return result;
}
unique_ptr< HTTPArchive > proxygen::HTTPArchive::fromFile (const std::string & filename) [static]
Definition at line 148 of file HTTPArchive.cpp.
References proxygen::HTTPMessage::getHeaders(), proxygen::readFileToIOBuf(), and proxygen::HTTPHeaders::size().
                                                                    {
  unique_ptr<HTTPArchive> har = std::make_unique<HTTPArchive>();
  auto buffer = readFileToIOBuf(filename);
  if (!buffer) {
    return nullptr;
  }
  folly::dynamic jsonObj = folly::parseJson((const char *)buffer->data());
  auto entries = jsonObj["log"]["entries"];
  // go over all the transactions
  for (size_t i = 0; i < entries.size(); i++) {
    HTTPMessage msg = extractMessage(entries[i]["request"],
                                     entries[i]["startedDateTime"].asString(),
                                     true);
    if (msg.getHeaders().size() != 0) {
      har->requests.push_back(msg);
    }
    msg = extractMessage(entries[i]["response"], "", false);
    if (msg.getHeaders().size() != 0) {
      har->responses.push_back(msg);
    }
  }
  return har;
}
unique_ptr< HTTPArchive > proxygen::HTTPArchive::fromPublicFile (const std::string & fname) [static]
Definition at line 191 of file HTTPArchive.cpp.
References proxygen::HTTPMessage::getHeaders(), proxygen::readFileToIOBuf(), and proxygen::HTTPHeaders::size().
                                                                          {
  unique_ptr<HTTPArchive> har = std::make_unique<HTTPArchive>();
  auto buffer = readFileToIOBuf(filename);
  if (!buffer) {
    return nullptr;
  }
  folly::dynamic jsonObj = folly::parseJson((const char *)buffer->data());
  auto entries = jsonObj["cases"];
  // go over all the transactions
  for (size_t i = 0; i < entries.size(); i++) {
    HTTPMessage msg = extractMessageFromPublic(entries[i]);
    if (msg.getHeaders().size() != 0) {
      har->requests.emplace_back(msg);
    }
  }
  return har;
}
uint32_t proxygen::HTTPArchive::getSize (const HTTPMessage & msg) [static]
Definition at line 173 of file HTTPArchive.cpp.
References proxygen::HTTPHeaders::forEach(), and proxygen::HTTPMessage::getHeaders().
                                                    {
  uint32_t size = 0;
  msg.getHeaders().forEach([&size] (const string& name, const string& value) {
      size += name.size() + value.size() + 2;
    });
  return size;
}
uint32_t proxygen::HTTPArchive::getSize (const std::vector< HPACKHeader > & headers) [static]
Definition at line 182 of file HTTPArchive.cpp.
                                                                {
  uint32_t size = 0;
  for (const auto& header : headers) {
    size += header.name.size() + header.value.size() + 2;
  }
  return size;
}
Member Data Documentation
std::vector<HTTPMessage> proxygen::HTTPArchive::requests
Definition at line 24 of file HTTPArchive.h.
Referenced by proxygen::compress::CompressionSimulator::readInputFromFileAndSchedule().
std::vector<HTTPMessage> proxygen::HTTPArchive::responses
Definition at line 25 of file HTTPArchive.h.
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/compress/test/HTTPArchive.h
proxygen/lib/http/codec/compress/test/HTTPArchive.cpp