proxygen::QPACKEncoder Class Reference
#include <QPACKEncoder.h>
Classes
struct EncodeResult
struct OutstandingBlock
Public Types
using Buf = std::unique_ptr< folly::IOBuf >
Public Member Functions
QPACKEncoder (bool huffman, uint32_t tableSize=HPACK::kTableSize)
EncodeResult encode (const std::vector< HPACKHeader > &headers, uint32_t headroom, uint64_t streamId, uint32_t maxEncoderStreamBytes=std::numeric_limits< uint32_t >::max())
HPACK::DecodeError decodeDecoderStream (std::unique_ptr< folly::IOBuf > buf)
HPACK::DecodeError onTableStateSync (uint32_t inserts)
HPACK::DecodeError onHeaderAck (uint64_t streamId, bool all)
void setHeaderTableSize (uint32_t size)
void setMaxVulnerable (uint32_t maxVulnerable)
void setMinFreeForTesting (uint32_t minFree)
Private Types
using BlockReferences = std::set< uint32_t >
Private Member Functions
bool allowVulnerable () const
bool shouldIndex (const HPACKHeader &header) const
void encodeControl (const HPACKHeader &header)
std::pair< bool, uint32_t > maybeDuplicate (uint32_t relativeIndex)
QPACKEncoder::EncodeResult encodeQ (const std::vector< HPACKHeader > &headers, uint64_t streamId)
std::tuple< bool, uint32_t, uint32_t > getNameIndexQ (const HPACKHeaderName &headerName)
void encodeStreamLiteralQ (const HPACKHeader &header, bool isStaticName, uint32_t nameIndex, uint32_t absoluteNameIndex, uint32_t baseIndex, uint32_t *largestReference)
void encodeHeaderQ (const HPACKHeader &header, uint32_t baseIndex, uint32_t *largestReference)
void encodeInsertQ (const HPACKHeader &header, bool isStaticName, uint32_t nameIndex)
void encodeLiteralQ (const HPACKHeader &header, bool isStaticName, bool postBase, uint32_t nameIndex, const HPACK::Instruction &idxInstr)
uint32_t encodeLiteralQHelper (HPACKEncodeBuffer &buffer, const HPACKHeader &header, bool isStaticName, uint32_t nameIndex, uint8_t staticFlag, const HPACK::Instruction &idxInstr, const HPACK::Instruction &litInstr)
void trackReference (uint32_t index, uint32_t *largestReference)
void encodeDuplicate (uint32_t index)
HPACK::DecodeError decodeHeaderAck (HPACKDecodeBuffer &dbuf, uint8_t prefixLength, bool all)
bool lastEntryAvailable () const
Private Attributes
HPACKEncodeBuffer controlBuffer_
std::unordered_map< uint64_t, std::list< OutstandingBlock > > outstanding_
OutstandingBlock * curOutstanding_ {nullptr}
uint32_t maxDepends_ {0}
uint32_t maxVulnerable_ {HPACK::kDefaultBlocking}
uint32_t numVulnerable_ {0}
int64_t maxEncoderStreamBytes_ {0}
folly::IOBufQueue decoderIngress_ {folly::IOBufQueue::cacheChainLength()}
Additional Inherited Members
Detailed Description
Definition at line 25 of file QPACKEncoder.h.
Member Typedef Documentation
using proxygen::QPACKEncoder::BlockReferences = std::set<uint32_t> [private]
Definition at line 131 of file QPACKEncoder.h.
using proxygen::QPACKEncoder::Buf = std::unique_ptr<folly::IOBuf>
Encode the given headers.
Definition at line 35 of file QPACKEncoder.h.
Constructor & Destructor Documentation
proxygen::QPACKEncoder::QPACKEncoder (bool huffman, uint32_t tableSize = HPACK::kTableSize) [explicit]
Definition at line 17 of file QPACKEncoder.cpp.
References proxygen::HeaderIndexingStrategy::getDefaultInstance(), and proxygen::HPACKEncoderBase::setHeaderIndexingStrategy().
                                                           :
    // We only need the 'QPACK' table if we are using base index
    HPACKEncoderBase(huffman),
    QPACKContext(tableSize, true),
    controlBuffer_(kBufferGrowth, huffman) {
  // Default the encoder indexing strategy; it can be updated later as well
  setHeaderIndexingStrategy(HeaderIndexingStrategy::getDefaultInstance());
}
Member Function Documentation
bool proxygen::QPACKEncoder::allowVulnerable () const [inline], [private]
Definition at line 73 of file QPACKEncoder.h.
References decodeHeaderAck(), encodeControl(), encodeDuplicate(), encodeHeaderQ(), encodeInsertQ(), encodeLiteralQ(), encodeLiteralQHelper(), encodeQ(), encodeStreamLiteralQ(), getNameIndexQ(), maxVulnerable_, maybeDuplicate(), numVulnerable_, shouldIndex(), and trackReference().
Referenced by encodeHeaderQ(), encodeQ(), encodeStreamLiteralQ(), getNameIndexQ(), and maybeDuplicate().
                               {
    return numVulnerable_ < maxVulnerable_;
  }
HPACK::DecodeError proxygen::QPACKEncoder::decodeDecoderStream (std::unique_ptr< folly::IOBuf > buf)
Definition at line 305 of file QPACKEncoder.cpp.
References proxygen::HPACK::BUFFER_UNDERFLOW, decodeHeaderAck(), decoderIngress_, proxygen::ERROR, proxygen::HPACK::NONE, onTableStateSync(), proxygen::HPACK::Q_CANCEL_STREAM, proxygen::HPACK::Q_HEADER_ACK, and proxygen::HPACK::Q_TABLE_STATE_SYNC.
Referenced by proxygen::hpack::encodeDecode(), and TEST().
                                   {
  decoderIngress_.append(std::move(buf));
  folly::io::Cursor cursor(decoderIngress_.front());
  HPACKDecodeBuffer dbuf(cursor, decoderIngress_.chainLength(), 0);
  HPACK::DecodeError err = HPACK::DecodeError::NONE;
  uint32_t consumed = 0;
  while (err == HPACK::DecodeError::NONE && !dbuf.empty()) {
    consumed = dbuf.consumedBytes();
    auto byte = dbuf.peek();
    if (byte & HPACK::Q_HEADER_ACK.code) {
      err = decodeHeaderAck(dbuf, HPACK::Q_HEADER_ACK.prefixLength, false);
    } else if (byte & HPACK::Q_CANCEL_STREAM.code) {
      err = decodeHeaderAck(dbuf, HPACK::Q_CANCEL_STREAM.prefixLength, true);
    } else { // TABLE_STATE_SYNC
      uint64_t inserts = 0;
      err = dbuf.decodeInteger(HPACK::Q_TABLE_STATE_SYNC.prefixLength, inserts);
      if (err == HPACK::DecodeError::NONE) {
        err = onTableStateSync(inserts);
      } else if (err != HPACK::DecodeError::BUFFER_UNDERFLOW) {
        LOG(ERROR) << "Failed to decode num inserts, err=" << err;
      }
    }
  } // while
  if (err == HPACK::DecodeError::BUFFER_UNDERFLOW) {
    err = HPACK::DecodeError::NONE;
    decoderIngress_.trimStart(consumed);
  } else {
    decoderIngress_.trimStart(dbuf.consumedBytes());
  }
  return err;
}
HPACK::DecodeError proxygen::QPACKEncoder::decodeHeaderAck (HPACKDecodeBuffer & dbuf, uint8_t prefixLength, bool all) [private]
Definition at line 338 of file QPACKEncoder.cpp.
References proxygen::HPACK::BUFFER_UNDERFLOW, proxygen::HPACKDecodeBuffer::decodeInteger(), proxygen::ERROR, proxygen::HPACK::NONE, and onHeaderAck().
Referenced by allowVulnerable(), and decodeDecoderStream().
                                                           {
  uint64_t streamId = 0;
  auto err = dbuf.decodeInteger(prefixLength, streamId);
  if (err == HPACK::DecodeError::NONE) {
    err = onHeaderAck(streamId, all);
  } else if (err != HPACK::DecodeError::BUFFER_UNDERFLOW) {
    LOG(ERROR) << "Failed to decode streamId, err=" << err;
  }
  return err;
}
QPACKEncoder::EncodeResult proxygen::QPACKEncoder::encode (const std::vector< HPACKHeader > & headers, uint32_t headroom, uint64_t streamId, uint32_t maxEncoderStreamBytes = std::numeric_limits<uint32_t>::max())
Definition at line 27 of file QPACKEncoder.cpp.
References proxygen::HPACKEncodeBuffer::addHeadroom(), proxygen::HeaderTable::capacity(), controlBuffer_, encodeQ(), proxygen::HPACKEncoderBase::handlePendingContextUpdate(), maxEncoderStreamBytes_, proxygen::HPACKEncoderBase::streamBuffer_, and proxygen::QPACKContext::table_.
Referenced by proxygen::QPACKCodec::encode(), proxygen::hpack::encodeDecode(), and TEST().
                                                     {
  if (headroom) {
    streamBuffer_.addHeadroom(headroom);
  }
  maxEncoderStreamBytes_ = maxEncoderStreamBytes;
  maxEncoderStreamBytes_ -=
    handlePendingContextUpdate(controlBuffer_, table_.capacity());
  return encodeQ(headers, streamId);
}
void proxygen::QPACKEncoder::encodeControl (const HPACKHeader & header) [private]
Referenced by allowVulnerable().
void proxygen::QPACKEncoder::encodeDuplicate (uint32_t index) [private]
Definition at line 249 of file QPACKEncoder.cpp.
References controlBuffer_, proxygen::HPACKEncodeBuffer::encodeInteger(), maxEncoderStreamBytes_, and proxygen::HPACK::Q_DUPLICATE.
Referenced by allowVulnerable(), and maybeDuplicate().
                                                 {
  DCHECK_GT(index, 0);
  maxEncoderStreamBytes_ -=
    controlBuffer_.encodeInteger(index - 1, HPACK::Q_DUPLICATE);
}
void proxygen::QPACKEncoder::encodeHeaderQ (const HPACKHeader & header, uint32_t baseIndex, uint32_t * largestReference) [private]
Definition at line 91 of file QPACKEncoder.cpp.
References proxygen::QPACKHeaderTable::absoluteToRelative(), proxygen::QPACKHeaderTable::add(), allowVulnerable(), proxygen::QPACKHeaderTable::canIndex(), proxygen::HPACKHeader::copy(), encodeInsertQ(), proxygen::HPACKEncodeBuffer::encodeInteger(), encodeStreamLiteralQ(), proxygen::QPACKHeaderTable::getBaseIndex(), proxygen::HeaderTable::getIndex(), proxygen::QPACKHeaderTable::getIndex(), getNameIndexQ(), proxygen::QPACKContext::getStaticTable(), proxygen::QPACKHeaderTable::isValid(), lastEntryAvailable(), maxEncoderStreamBytes_, maybeDuplicate(), proxygen::HPACKHeader::name, proxygen::HPACK::Q_INDEXED, proxygen::HPACK::Q_INDEXED_POST, proxygen::HPACK::Q_INDEXED_STATIC, shouldIndex(), proxygen::HPACKEncoderBase::streamBuffer_, proxygen::QPACKContext::table_, trackReference(), and proxygen::QPACKHeaderTable::UNACKED.
Referenced by allowVulnerable(), and encodeQ().
                                                                             {
  uint32_t index = getStaticTable().getIndex(header);
  if (index > 0) {
    // static reference
    streamBuffer_.encodeInteger(index - 1,
                                HPACK::Q_INDEXED.code | HPACK::Q_INDEXED_STATIC,
                                HPACK::Q_INDEXED.prefixLength);
    return;
  }
  bool indexable = shouldIndex(header);
  if (indexable) {
    index = table_.getIndex(header, allowVulnerable());
    if (index == QPACKHeaderTable::UNACKED) {
      index = 0;
      indexable = false;
    }
  }
  if (index != 0) {
    // dynamic reference
    bool duplicated = false;
    std::tie(duplicated, index) = maybeDuplicate(index);
    // index is now 0 or absolute
    indexable &= (duplicated && index == 0);
  }
  if (index == 0) {
    // No valid entry matching header, see if there's a matching name
    uint32_t nameIndex = 0;
    uint32_t absoluteNameIndex = 0;
    bool isStaticName = false;
    std::tie(isStaticName, nameIndex, absoluteNameIndex) =
      getNameIndexQ(header.name);
    // Now check if we should emit an insertion on the control stream
    // Don't try to index if we're out of encoder flow control
    indexable &= maxEncoderStreamBytes_ > 0;
    if (indexable && table_.canIndex(header)) {
      encodeInsertQ(header, isStaticName, nameIndex);
      CHECK(table_.add(header.copy()));
      if (allowVulnerable() && lastEntryAvailable()) {
        index = table_.getBaseIndex();
      } else {
        index = 0;
        if (absoluteNameIndex > 0 &&
            !table_.isValid(table_.absoluteToRelative(absoluteNameIndex))) {
          // The insert may have invalidated the name index.
          isStaticName = true;
          nameIndex = 0;
          absoluteNameIndex = 0;
        }
      }
    }
    if (index == 0) {
      // Couldn't insert it: table full, not indexable, or table contains
      // vulnerable reference. Encode a literal on the request stream.
      encodeStreamLiteralQ(header, isStaticName, nameIndex, absoluteNameIndex,
                           baseIndex, largestReference);
      return;
    }
  }
  // Encoding a dynamic index reference
  DCHECK_NE(index, 0);
  trackReference(index, largestReference);
  if (index > baseIndex) {
    streamBuffer_.encodeInteger(index - baseIndex - 1, HPACK::Q_INDEXED_POST);
  } else {
    streamBuffer_.encodeInteger(baseIndex - index, HPACK::Q_INDEXED);
  }
}
void proxygen::QPACKEncoder::encodeInsertQ (const HPACKHeader & header, bool isStaticName, uint32_t nameIndex) [private]
Definition at line 255 of file QPACKEncoder.cpp.
References controlBuffer_, encodeLiteralQHelper(), maxEncoderStreamBytes_, proxygen::HPACK::Q_INSERT_NAME_REF, proxygen::HPACK::Q_INSERT_NAME_REF_STATIC, and proxygen::HPACK::Q_INSERT_NO_NAME_REF.
Referenced by allowVulnerable(), and encodeHeaderQ().
                                                     {
  auto encoded = encodeLiteralQHelper(
      controlBuffer_, header, isStaticName, nameIndex,
      HPACK::Q_INSERT_NAME_REF_STATIC, HPACK::Q_INSERT_NAME_REF,
      HPACK::Q_INSERT_NO_NAME_REF);
  maxEncoderStreamBytes_ -= encoded;
}
void proxygen::QPACKEncoder::encodeLiteralQ (const HPACKHeader & header, bool isStaticName, bool postBase, uint32_t nameIndex, const HPACK::Instruction & idxInstr) [private]
Definition at line 265 of file QPACKEncoder.cpp.
References encodeLiteralQHelper(), proxygen::HPACK::Q_LITERAL, proxygen::HPACK::Q_LITERAL_STATIC, and proxygen::HPACKEncoderBase::streamBuffer_.
Referenced by allowVulnerable(), and encodeStreamLiteralQ().
                                                                    {
  DCHECK(!isStaticName || !postBase);
  encodeLiteralQHelper(
      streamBuffer_, header, isStaticName, nameIndex,
      HPACK::Q_LITERAL_STATIC, idxInstr,
      HPACK::Q_LITERAL);
}
uint32_t proxygen::QPACKEncoder::encodeLiteralQHelper (HPACKEncodeBuffer & buffer, const HPACKHeader & header, bool isStaticName, uint32_t nameIndex, uint8_t staticFlag, const HPACK::Instruction & idxInstr, const HPACK::Instruction & litInstr) [private]
Definition at line 277 of file QPACKEncoder.cpp.
References proxygen::HPACK::Instruction::code, proxygen::HPACKEncodeBuffer::encodeInteger(), proxygen::HPACKEncodeBuffer::encodeLiteral(), proxygen::HPACKHeaderName::get(), proxygen::HPACKHeader::name, proxygen::HPACK::Instruction::prefixLength, proxygen::QPACKHeaderTable::UNACKED, and proxygen::HPACKHeader::value.
Referenced by allowVulnerable(), encodeInsertQ(), and encodeLiteralQ().
                                      {
  uint32_t encoded = 0;
  // name
  if (nameIndex) {
    VLOG(10) << "encoding name index=" << nameIndex;
    DCHECK_NE(nameIndex, QPACKHeaderTable::UNACKED);
    nameIndex -= 1; // we already know it's not 0
    uint8_t byte = idxInstr.code;
    if (isStaticName) {
      byte |= staticFlag;
    }
    encoded += buffer.encodeInteger(nameIndex, byte, idxInstr.prefixLength);
  } else {
    encoded += buffer.encodeLiteral(litInstr.code, litInstr.prefixLength,
                                    header.name.get());
  }
  // value
  encoded += buffer.encodeLiteral(header.value);
  return encoded;
}
QPACKEncoder::EncodeResult proxygen::QPACKEncoder::encodeQ (const std::vector< HPACKHeader > & headers, uint64_t streamId) [private]
Definition at line 41 of file QPACKEncoder.cpp.
References allowVulnerable(), controlBuffer_, curOutstanding_, encodeHeaderQ(), proxygen::HPACKEncodeBuffer::encodeInteger(), proxygen::QPACKHeaderTable::getBaseIndex(), proxygen::QPACKHeaderTable::getMaxEntries(), numVulnerable_, outstanding_, proxygen::HPACK::Q_DELTA_BASE, proxygen::HPACK::Q_DELTA_BASE_NEG, proxygen::HPACK::Q_DELTA_BASE_POS, proxygen::QPACKEncoder::OutstandingBlock::references, proxygen::HPACKEncodeBuffer::release(), proxygen::HPACKEncoderBase::streamBuffer_, proxygen::QPACKContext::table_, and proxygen::QPACKEncoder::OutstandingBlock::vulnerable.
Referenced by allowVulnerable(), and encode().
                                                                           {
  OutstandingBlock outstandingBlock;
  // curOutstanding_ points to a local stack variable, it's mostly for
  // convenience so other methods invoked from here can access it.
  curOutstanding_ = &outstandingBlock;
  auto baseIndex = table_.getBaseIndex();
  uint32_t largestReference = 0;
  for (const auto& header: headers) {
    encodeHeaderQ(header, baseIndex, &largestReference);
  }
  auto streamBlock = streamBuffer_.release();
  // encode the prefix
  if (largestReference == 0) {
    streamBuffer_.encodeInteger(0); // LR
    streamBuffer_.encodeInteger(0); // baseIndex
  } else {
    auto wireLR = (largestReference % (2 * table_.getMaxEntries())) + 1;
    streamBuffer_.encodeInteger(wireLR);
    if (largestReference > baseIndex) {
      streamBuffer_.encodeInteger(largestReference - baseIndex,
                                  HPACK::Q_DELTA_BASE_NEG,
                                  HPACK::Q_DELTA_BASE.prefixLength);
    } else {
      streamBuffer_.encodeInteger(baseIndex - largestReference,
                                  HPACK::Q_DELTA_BASE_POS,
                                  HPACK::Q_DELTA_BASE.prefixLength);
    }
  }
  auto streamBuffer = streamBuffer_.release();
  streamBuffer->prependChain(std::move(streamBlock));
  auto controlBuf = controlBuffer_.release();
  // curOutstanding_.references could be empty, if the block encodes only static
  // headers and/or literals. If so we don't track anything.
  if (!curOutstanding_->references.empty()) {
    if (curOutstanding_->vulnerable) {
      DCHECK(allowVulnerable());
      numVulnerable_++;
    }
    outstanding_[streamId].emplace_back(std::move(outstandingBlock));
  }
  // Clear the pointer to our stack
  curOutstanding_ = nullptr;
  return { std::move(controlBuf), std::move(streamBuffer) };
}
void proxygen::QPACKEncoder::encodeStreamLiteralQ (const HPACKHeader & header, bool isStaticName, uint32_t nameIndex, uint32_t absoluteNameIndex, uint32_t baseIndex, uint32_t * largestReference) [private]
Definition at line 209 of file QPACKEncoder.cpp.
References allowVulnerable(), encodeLiteralQ(), proxygen::HPACK::Q_LITERAL_NAME_REF, proxygen::HPACK::Q_LITERAL_NAME_REF_POST, and trackReference().
Referenced by allowVulnerable(), and encodeHeaderQ().
                                                                              {
  if (absoluteNameIndex > 0) {
    // Dynamic name reference, vulnerability checks already done
    CHECK(absoluteNameIndex <= baseIndex || allowVulnerable());
    trackReference(absoluteNameIndex, largestReference);
  }
  if (absoluteNameIndex > baseIndex) {
    encodeLiteralQ(header,
                   false, /* not static */
                   true, /* post base */
                   absoluteNameIndex - baseIndex,
                   HPACK::Q_LITERAL_NAME_REF_POST);
  } else {
    encodeLiteralQ(header,
                   isStaticName,
                   false, /* not post base */
                   isStaticName ? nameIndex : baseIndex - absoluteNameIndex + 1,
                   HPACK::Q_LITERAL_NAME_REF);
  }
}
std::tuple< bool, uint32_t, uint32_t > proxygen::QPACKEncoder::getNameIndexQ (const HPACKHeaderName & headerName) [private]
Definition at line 186 of file QPACKEncoder.cpp.
References proxygen::QPACKHeaderTable::absoluteToRelative(), allowVulnerable(), proxygen::QPACKContext::getStaticTable(), maybeDuplicate(), proxygen::HeaderTable::nameIndex(), proxygen::QPACKHeaderTable::nameIndex(), and proxygen::QPACKContext::table_.
Referenced by allowVulnerable(), and encodeHeaderQ().
                                     {
  uint32_t absoluteNameIndex = 0;
  uint32_t nameIndex = getStaticTable().nameIndex(headerName);
  bool isStatic = true;
  if (nameIndex == 0) {
    // check dynamic table
    nameIndex = table_.nameIndex(headerName, allowVulnerable());
    if (nameIndex != 0) {
      absoluteNameIndex = maybeDuplicate(nameIndex).second;
      if (absoluteNameIndex) {
        isStatic = false;
        nameIndex = table_.absoluteToRelative(absoluteNameIndex);
      } else {
        nameIndex = 0;
        absoluteNameIndex = 0;
      }
    }
  }
  return std::tuple<bool, uint32_t, uint32_t>(
    isStatic, nameIndex, absoluteNameIndex);
}
bool proxygen::QPACKEncoder::lastEntryAvailable () const [inline], [private]
Definition at line 126 of file QPACKEncoder.h.
References maxEncoderStreamBytes_.
Referenced by encodeHeaderQ(), and maybeDuplicate().
                                  {
    return maxEncoderStreamBytes_ >= 0;
  }
std::pair< bool, uint32_t > proxygen::QPACKEncoder::maybeDuplicate (uint32_t relativeIndex) [private]
Definition at line 169 of file QPACKEncoder.cpp.
References allowVulnerable(), encodeDuplicate(), lastEntryAvailable(), proxygen::QPACKHeaderTable::maybeDuplicate(), and proxygen::QPACKContext::table_.
Referenced by allowVulnerable(), encodeHeaderQ(), and getNameIndexQ().
                              {
  auto res = table_.maybeDuplicate(relativeIndex, allowVulnerable());
  if (res.first) {
    VLOG(4) << "Encoded duplicate index=" << relativeIndex;
    encodeDuplicate(relativeIndex);
    // Note we will emit duplications even when we are out of flow control,
    // but we won't reference them (eg: like we were at vulnerable max).
    if (!lastEntryAvailable()) {
      VLOG(4) << "Duplicate is not usable because it overran encoder flow "
        "control";
      return {true, 0};
    }
  }
  return res;
}
HPACK::DecodeError proxygen::QPACKEncoder::onHeaderAck (uint64_t streamId, bool all)
Definition at line 358 of file QPACKEncoder.cpp.
References proxygen::ERROR, proxygen::HPACK::INVALID_ACK, proxygen::HPACK::NONE, numVulnerable_, outstanding_, proxygen::QPACKHeaderTable::setMaxAcked(), proxygen::QPACKHeaderTable::subRef(), and proxygen::QPACKContext::table_.
Referenced by decodeHeaderAck(), and TEST().
                                                                      {
  auto it = outstanding_.find(streamId);
  if (it == outstanding_.end()) {
    if (!all) {
      LOG(ERROR) << "Received an ack with no outstanding header blocks stream="
                 << streamId;
      return HPACK::DecodeError::INVALID_ACK;
    } else {
      // all implies a reset, meaning it's not an error if there are no
      // outstanding blocks
      return HPACK::DecodeError::NONE;
    }
  }
  DCHECK(!it->second.empty()) << "Invariant violation: no blocks in stream "
     "record";
  VLOG(5) << ((all) ? "onCancelStream" : "onHeaderAck") << " streamId="
          << streamId;
  if (all) {
    // Happens when a stream is reset
    for (auto& block: it->second) {
      for (auto i: block.references) {
        VLOG(5) << "Decrementing refcount for absoluteIndex=" << i;
        table_.subRef(i);
      }
      if (block.vulnerable) {
        numVulnerable_--;
      }
    }
    it->second.clear();
  } else {
    auto block = std::move(it->second.front());
    it->second.pop_front();
    // a different stream, sub all the references
    for (auto i: block.references) {
      VLOG(5) << "Decrementing refcount for absoluteIndex=" << i;
      table_.subRef(i);
    }
    if (block.vulnerable) {
      numVulnerable_--;
    }
    // largest reference is implicitly acknowledged
    if (!block.references.empty()) {
      auto largestReference = *block.references.rbegin();
      VLOG(5) << "Implicitly acknowledging absoluteIndex=" << largestReference;
      table_.setMaxAcked(largestReference);
    }
  }
  if (it->second.empty()) {
    outstanding_.erase(it);
  }
  return HPACK::DecodeError::NONE;
}
HPACK::DecodeError proxygen::QPACKEncoder::onTableStateSync (uint32_t inserts)
Definition at line 351 of file QPACKEncoder.cpp.
References proxygen::HPACK::INVALID_ACK, proxygen::HPACK::NONE, proxygen::QPACKHeaderTable::onTableStateSync(), and proxygen::QPACKContext::table_.
Referenced by decodeDecoderStream(), and TEST().
                                                                {
  if (inserts == 0 || !table_.onTableStateSync(inserts)) {
    return HPACK::DecodeError::INVALID_ACK;
  }
  return HPACK::DecodeError::NONE;
}
void proxygen::QPACKEncoder::setHeaderTableSize (uint32_t size) [inline]
Definition at line 58 of file QPACKEncoder.h.
References proxygen::HPACKEncoderBase::setHeaderTableSize(), and proxygen::QPACKContext::table_.
Referenced by TEST().
                                         {
    HPACKEncoderBase::setHeaderTableSize(table_, size);
  }
void proxygen::QPACKEncoder::setMaxVulnerable (uint32_t maxVulnerable) [inline]
Definition at line 62 of file QPACKEncoder.h.
References maxVulnerable_.
Referenced by TEST().
                                                {
    maxVulnerable_ = maxVulnerable;
  }
void proxygen::QPACKEncoder::setMinFreeForTesting (uint32_t minFree) [inline]
Definition at line 68 of file QPACKEncoder.h.
References proxygen::QPACKHeaderTable::setMinFreeForTesting(), and proxygen::QPACKContext::table_.
Referenced by TEST().
                                              {
    table_.setMinFreeForTesting(minFree);
  }
bool proxygen::QPACKEncoder::shouldIndex (const HPACKHeader & header) const [private]
Definition at line 164 of file QPACKEncoder.cpp.
References proxygen::HPACKHeader::bytes(), proxygen::HeaderTable::capacity(), proxygen::HeaderIndexingStrategy::indexHeader(), proxygen::HPACKEncoderBase::indexingStrat_, and proxygen::QPACKContext::table_.
Referenced by allowVulnerable(), and encodeHeaderQ().
                                                              {
  return (header.bytes() <= table_.capacity()) &&
    (!indexingStrat_ || indexingStrat_->indexHeader(header));
}
void proxygen::QPACKEncoder::trackReference (uint32_t index, uint32_t * largestReference) [private]
Definition at line 232 of file QPACKEncoder.cpp.
References proxygen::QPACKHeaderTable::addRef(), curOutstanding_, proxygen::QPACKHeaderTable::isVulnerable(), proxygen::QPACKEncoder::OutstandingBlock::references, proxygen::QPACKContext::table_, and proxygen::QPACKEncoder::OutstandingBlock::vulnerable.
Referenced by allowVulnerable(), encodeHeaderQ(), and encodeStreamLiteralQ().
                                                              {
  CHECK_NE(absoluteIndex, 0);
  CHECK(curOutstanding_);
  if (absoluteIndex > *largestReference) {
    *largestReference = absoluteIndex;
    if (table_.isVulnerable(absoluteIndex)) {
      curOutstanding_->vulnerable = true;
    }
  }
  auto res = curOutstanding_->references.insert(absoluteIndex);
  if (res.second) {
    VLOG(5) << "Bumping refcount for absoluteIndex=" << absoluteIndex;
    table_.addRef(absoluteIndex);
  }
}
Member Data Documentation
HPACKEncodeBuffer proxygen::QPACKEncoder::controlBuffer_ [private]
Definition at line 130 of file QPACKEncoder.h.
Referenced by encode(), encodeDuplicate(), encodeInsertQ(), and encodeQ().
OutstandingBlock* proxygen::QPACKEncoder::curOutstanding_ {nullptr} [private]
Definition at line 138 of file QPACKEncoder.h.
Referenced by encodeQ(), and trackReference().
folly::IOBufQueue proxygen::QPACKEncoder::decoderIngress_ {folly::IOBufQueue::cacheChainLength()} [private]
Definition at line 143 of file QPACKEncoder.h.
Referenced by decodeDecoderStream().
uint32_t proxygen::QPACKEncoder::maxDepends_ {0} [private]
Definition at line 139 of file QPACKEncoder.h.
int64_t proxygen::QPACKEncoder::maxEncoderStreamBytes_ {0} [private]
Definition at line 142 of file QPACKEncoder.h.
Referenced by encode(), encodeDuplicate(), encodeHeaderQ(), encodeInsertQ(), and lastEntryAvailable().
uint32_t proxygen::QPACKEncoder::maxVulnerable_ {HPACK::kDefaultBlocking} [private]
Definition at line 140 of file QPACKEncoder.h.
Referenced by allowVulnerable(), and setMaxVulnerable().
uint32_t proxygen::QPACKEncoder::numVulnerable_ {0} [private]
Definition at line 141 of file QPACKEncoder.h.
Referenced by allowVulnerable(), encodeQ(), and onHeaderAck().
std::unordered_map<uint64_t, std::list<OutstandingBlock> > proxygen::QPACKEncoder::outstanding_ [private]
Definition at line 137 of file QPACKEncoder.h.
Referenced by encodeQ(), and onHeaderAck().
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/compress/QPACKEncoder.h
proxygen/lib/http/codec/compress/QPACKEncoder.cpp