shell_quoting.ShellQuoted Class Reference
Public Member Functions
def __new__ (cls, s)
def __str__ (self)
def __repr__ (self)
def format (self, kwargs)
Detailed Description
Wrap a string with this to make it transparent to shell_quote().  It
will almost always suffice to use ShellQuoted.format(), path_join(),
or shell_join().

If you really must, use raw_shell() to access the raw string.
Definition at line 26 of file shell_quoting.py.
Member Function Documentation
def shell_quoting.ShellQuoted.__new__ (cls, s)
Definition at line 37 of file shell_quoting.py.
    def __new__(cls, s):
        'No need to nest ShellQuoted.'
        return super(ShellQuoted, cls).__new__(
            cls, s.do_not_use_raw_str if isinstance(s, ShellQuoted) else s
        )
def shell_quoting.ShellQuoted.__repr__ (self)
Definition at line 49 of file shell_quoting.py.
References shell_quoting.ShellQuoted.format().
    def __repr__(self):
        return '{0}({1})'.format(
            self.__class__.__name__, repr(self.do_not_use_raw_str)
        )
def shell_quoting.ShellQuoted.__str__ (self)
Definition at line 43 of file shell_quoting.py.
References shell_quoting.ShellQuoted.format().
    def __str__(self):
        raise RuntimeError(
            'One does not simply convert {0} to a string -- use path_join() '
            'or ShellQuoted.format() instead'.format(repr(self))
        )
def shell_quoting.ShellQuoted.format (self, kwargs)
Use instead of str.format() when the arguments are either
`ShellQuoted()` or raw strings needing to be `shell_quote()`d.

Positional args are deliberately not supported since they are more
error-prone.
Definition at line 54 of file shell_quoting.py.
References shell_quoting.shell_quote().
Referenced by shell_quoting.ShellQuoted.__repr__(), and shell_quoting.ShellQuoted.__str__().
    def format(self, **kwargs):
        '''
        Use instead of str.format() when the arguments are either
        `ShellQuoted()` or raw strings needing to be `shell_quote()`d.
        Positional args are deliberately not supported since they are more
        error-prone.
        '''
        return ShellQuoted(self.do_not_use_raw_str.format(**dict(
            (k, shell_quote(v).do_not_use_raw_str) for k, v in kwargs.items()
        )))
The documentation for this class was generated from the following file:
build/fbcode_builder/shell_quoting.py