proxygen::HPACK::StreamingCallback Class Reference
#include <HPACKStreamingCallback.h>
Public Member Functions
virtual ~StreamingCallback ()
virtual void onHeader (const folly::fbstring &name, const folly::fbstring &value)=0
virtual void onHeadersComplete (HTTPHeaderSize decodedSize, bool acknowledge)=0
virtual void onDecodeError (HPACK::DecodeError decodeError)=0
Public Attributes
HeaderCodec::Stats * stats {nullptr}
Detailed Description
Definition at line 16 of file HPACKStreamingCallback.h.
Constructor & Destructor Documentation
virtual proxygen::HPACK::StreamingCallback::~StreamingCallback () [inline], [virtual]
Definition at line 18 of file HPACKStreamingCallback.h.
References name, onDecodeError(), onHeader(), and onHeadersComplete().
{}
Member Function Documentation
virtual void proxygen::HPACK::StreamingCallback::onDecodeError (HPACK::DecodeError decodeError) [pure virtual]
Implemented in proxygen::compress::SimStreamingCallback , proxygen::HTTP2Codec , and proxygen::TestStreamingCallback .
Referenced by proxygen::HPACKDecoderBase::completeDecode(), proxygen::HPACKQueue::enqueueHeaderBlock(), and ~StreamingCallback().
virtual void proxygen::HPACK::StreamingCallback::onHeader (const folly::fbstring & name, const folly::fbstring & value) [pure virtual]
Implemented in proxygen::compress::SimStreamingCallback , proxygen::HTTP2Codec , and proxygen::TestStreamingCallback .
Referenced by proxygen::HPACKDecoderBase::emit(), and ~StreamingCallback().
virtual void proxygen::HPACK::StreamingCallback::onHeadersComplete (HTTPHeaderSize decodedSize, bool acknowledge) [pure virtual]
Implemented in proxygen::compress::SimStreamingCallback , proxygen::HTTP2Codec , and proxygen::TestStreamingCallback .
Referenced by proxygen::HPACKDecoderBase::completeDecode(), and ~StreamingCallback().
Member Data Documentation
HeaderCodec::Stats* proxygen::HPACK::StreamingCallback::stats {nullptr}
Definition at line 25 of file HPACKStreamingCallback.h.
Referenced by proxygen::HPACKDecoderBase::completeDecode().
The documentation for this class was generated from the following file:
proxygen/lib/http/codec/compress/HPACKStreamingCallback.h