proxygen::AsyncTimeoutSet::TimeoutClock Class Reference
#include <AsyncTimeoutSet.h>
Public Member Functions
TimeoutClock ()
virtual ~TimeoutClock ()
virtual std::chrono::milliseconds millisecondsSinceEpoch ()=0
Detailed Description
Clock interface. Can be used for different time implementations (eg: monotonic, system) or mocking.
Definition at line 114 of file AsyncTimeoutSet.h.
Constructor & Destructor Documentation
proxygen::AsyncTimeoutSet::TimeoutClock::TimeoutClock () [inline]
Definition at line 116 of file AsyncTimeoutSet.h.
{}
virtual proxygen::AsyncTimeoutSet::TimeoutClock::~TimeoutClock () [inline], [virtual]
Definition at line 118 of file AsyncTimeoutSet.h.
References proxygen::AsyncTimeoutSet::Callback::AsyncTimeoutSet, proxygen::AsyncTimeoutSet::destroy(), and proxygen::millisecondsSinceEpoch().
{}
Member Function Documentation
virtual std::chrono::milliseconds proxygen::AsyncTimeoutSet::TimeoutClock::millisecondsSinceEpoch () [pure virtual]
Implemented in proxygen::SimpleTimeoutClock .
Referenced by proxygen::AsyncTimeoutSet::Callback::setScheduled().
The documentation for this class was generated from the following file:
proxygen/lib/utils/AsyncTimeoutSet.h