proxygen::DefaultHTTPCodecFactory Class Reference
#include <DefaultHTTPCodecFactory.h>
Public Member Functions
DefaultHTTPCodecFactory (bool forceHTTP1xCodecTo1_1)
~DefaultHTTPCodecFactory () override=default
std::unique_ptr< HTTPCodec > getCodec (const std::string &nextProtocol, TransportDirection direction, bool isTLS) override
void setForceHTTP1xCodecTo1_1 (bool forceHTTP1xCodecTo1_1)
Protected Attributes
bool forceHTTP1xCodecTo1_1_ {false}
Additional Inherited Members
Detailed Description
Definition at line 15 of file DefaultHTTPCodecFactory.h.
Constructor & Destructor Documentation
proxygen::DefaultHTTPCodecFactory::DefaultHTTPCodecFactory (bool forceHTTP1xCodecTo1_1) [explicit]
Definition at line 19 of file DefaultHTTPCodecFactory.cpp.
    : forceHTTP1xCodecTo1_1_(forceHTTP1xCodecTo1_1) {
}
proxygen::DefaultHTTPCodecFactory::~DefaultHTTPCodecFactory () [override], [default]
Member Function Documentation
std::unique_ptr< HTTPCodec > proxygen::DefaultHTTPCodecFactory::getCodec (const std::string & nextProtocol, TransportDirection direction, bool isTLS) [override], [virtual]
Get a codec instance
Implements proxygen::HTTPCodecFactory .
Definition at line 24 of file DefaultHTTPCodecFactory.cpp.
References proxygen::ERROR, forceHTTP1xCodecTo1_1_, proxygen::SPDYCodec::getVersion(), proxygen::http2::kProtocolCleartextString, proxygen::http2::kProtocolDraftString, proxygen::http2::kProtocolExperimentalString, proxygen::http2::kProtocolString, and proxygen::HTTP1xCodec::supportsNextProtocol().
Referenced by TEST().
            {
    auto spdyVersion = SPDYCodec::getVersion(chosenProto);
    if (spdyVersion) {
      return std::make_unique<SPDYCodec>(direction,
                                           *spdyVersion);
    } else if (chosenProto == proxygen::http2::kProtocolString ||
               chosenProto == proxygen::http2::kProtocolCleartextString ||
               chosenProto == proxygen::http2::kProtocolDraftString ||
               chosenProto == proxygen::http2::kProtocolExperimentalString) {
      return std::make_unique<HTTP2Codec>(direction);
    } else {
      if (!chosenProto.empty() &&
          !HTTP1xCodec::supportsNextProtocol(chosenProto)) {
        LOG(ERROR) << "Chosen upstream protocol " <<
          "\"" << chosenProto << "\" is unimplemented. " <<
          "Attempting to use HTTP/1.1";
      }
      return std::make_unique<HTTP1xCodec>(direction,
                                             forceHTTP1xCodecTo1_1_);
    }
}
void proxygen::DefaultHTTPCodecFactory::setForceHTTP1xCodecTo1_1 (bool forceHTTP1xCodecTo1_1) [inline]
Definition at line 27 of file DefaultHTTPCodecFactory.h.
References forceHTTP1xCodecTo1_1_.
                                                            {
    forceHTTP1xCodecTo1_1_ = forceHTTP1xCodecTo1_1;
  }
Member Data Documentation
bool proxygen::DefaultHTTPCodecFactory::forceHTTP1xCodecTo1_1_ {false} [protected]
Definition at line 31 of file DefaultHTTPCodecFactory.h.
Referenced by getCodec(), and setForceHTTP1xCodecTo1_1().
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/DefaultHTTPCodecFactory.h
proxygen/lib/http/codec/DefaultHTTPCodecFactory.cpp