ScopedServerTest Class Reference
Public Member Functions
void SetUp () override
Protected Member Functions
std::unique_ptr< ScopedHTTPServer > createScopedServer ()
std::unique_ptr< CurlClient > connectSSL (const std::string &caFile=``, const std::string &certFile=``, const std::string &keyFile=``)
std::unique_ptr< CurlClient > connectPlainText ()
virtual HTTPServerOptions createDefaultOpts ()
Protected Attributes
folly::EventBase evb_
folly::SocketAddress address_
HHWheelTimer::UniquePtr timer_
HTTPServer::IPConfig cfg_
Detailed Description
Definition at line 584 of file HTTPServerTest.cpp.
Member Function Documentation
std::unique_ptr<CurlClient> ScopedServerTest::connectPlainText () [inline], [protected]
Definition at line 625 of file HTTPServerTest.cpp.
References proxygen::HTTPConnector::connect().
                                               {
    URL url(
        folly::to<std::string>("http://localhost:", address_.getPort()));
    HTTPHeaders headers;
    auto client = std::make_unique<CurlClient>(
      &evb_, HTTPMethod::GET, url, nullptr, headers, "");
    client->setFlowControlSettings(64 * 1024);
    client->setLogging(false);
    HTTPConnector connector(client.get(), timer_.get());
    connector.connect(
      &evb_,
      address_,
      std::chrono::milliseconds(1000));
    evb_.loop();
    return client;
  }
std::unique_ptr<CurlClient> ScopedServerTest::connectSSL (const std::string & caFile = ``, const std::string & certFile = ``, const std::string & keyFile = ``) [inline], [protected]
Definition at line 604 of file HTTPServerTest.cpp.
References proxygen::HTTPConnector::connectSSL().
                                                                        {
    URL url(folly::to<std::string>("https://localhost:", address_.getPort()));
    HTTPHeaders headers;
    auto client = std::make_unique<CurlClient>(
      &evb_, HTTPMethod::GET, url, nullptr, headers, "");
    client->setFlowControlSettings(64 * 1024);
    client->setLogging(false);
    client->initializeSsl(caFile, "http/1.1", certFile, keyFile);
    HTTPConnector connector(client.get(), timer_.get());
    connector.connectSSL(
      &evb_,
      address_,
      client->getSSLContext(),
      nullptr,
      std::chrono::milliseconds(1000));
    evb_.loop();
    return client;
  }
virtual HTTPServerOptions ScopedServerTest::createDefaultOpts () [inline], [protected], [virtual]
Reimplemented in ConnectionFilterTest .
Definition at line 642 of file HTTPServerTest.cpp.
References proxygen::RequestHandlerChain::addThen(), proxygen::HTTPServerOptions::handlerFactories, and proxygen::HTTPServerOptions::threads.
                                                {
    HTTPServerOptions res;
    res.handlerFactories =
      RequestHandlerChain().addThen<TestHandlerFactory>().build();
    res.threads = 4;
    return res;
  }
std::unique_ptr<ScopedHTTPServer> ScopedServerTest::createScopedServer () [inline], [protected]
Definition at line 596 of file HTTPServerTest.cpp.
                       {
    auto opts = createDefaultOpts();
    auto res = ScopedHTTPServer::start(cfg_, std::move(opts));
    auto addresses = res->getAddresses();
    address_ = addresses.front().address;
    return res;
  }
void ScopedServerTest::SetUp () [inline], [override]
Definition at line 586 of file HTTPServerTest.cpp.
                        {
    timer_.reset(new HHWheelTimer(
        &evb_,
        std::chrono::milliseconds(HHWheelTimer::DEFAULT_TICK_INTERVAL),
        AsyncTimeout::InternalEnum::NORMAL,
        std::chrono::milliseconds(1000)));
  }
Member Data Documentation
folly::SocketAddress ScopedServerTest::address_ [protected]
Definition at line 651 of file HTTPServerTest.cpp.
HTTPServer::IPConfig ScopedServerTest::cfg_ [protected]
Initial value:
{
      folly::SocketAddress("127.0.0.1", 0),
        HTTPServer::Protocol::HTTP}
Definition at line 653 of file HTTPServerTest.cpp.
folly::EventBase ScopedServerTest::evb_ [protected]
Definition at line 650 of file HTTPServerTest.cpp.
HHWheelTimer::UniquePtr ScopedServerTest::timer_ [protected]
Definition at line 652 of file HTTPServerTest.cpp.
The documentation for this class was generated from the following file:
proxygen/httpserver/tests/HTTPServerTest.cpp