proxygen::MockResponseHandler Class Reference
#include <Mocks.h>
Public Member Functions
MockResponseHandler (RequestHandler *h)
GMOCK_METHOD1_ (, noexcept,, sendHeaders, void(HTTPMessage &))
GMOCK_METHOD1_ (, noexcept,, sendChunkHeader, void(size_t))
GMOCK_METHOD1_ (, noexcept,, sendBody, void(std::shared_ptr< folly::IOBuf >))
GMOCK_METHOD0_ (, noexcept,, sendChunkTerminator, void())
GMOCK_METHOD1_ (, noexcept,, sendTrailers, void(const HTTPHeaders &))
GMOCK_METHOD0_ (, noexcept,, sendEOM, void())
GMOCK_METHOD0_ (, noexcept,, sendAbort, void())
GMOCK_METHOD0_ (, noexcept,, refreshTimeout, void())
GMOCK_METHOD0_ (, noexcept,, pauseIngress, void())
GMOCK_METHOD0_ (, noexcept,, resumeIngress, void())
GMOCK_METHOD1_ (, noexcept,, newPushedResponse, ResponseHandler *(PushHandler *))
MOCK_CONST_METHOD1 (getCurrentTransportInfo, void(wangle::TransportInfo *))
const wangle::TransportInfo & getSetupTransportInfo () const noexceptoverride
void sendBody (std::unique_ptr< folly::IOBuf > body) noexceptoverride
Public Attributes
wangle::TransportInfo transportInfo
Additional Inherited Members
Detailed Description
Mocks to help with testing
Definition at line 22 of file Mocks.h.
Constructor & Destructor Documentation
proxygen::MockResponseHandler::MockResponseHandler (RequestHandler * h) [inline], [explicit]
Definition at line 24 of file Mocks.h.
References proxygen::ResponseHandler::getCurrentTransportInfo(), GMOCK_METHOD0_(), GMOCK_METHOD1_(), MOCK_CONST_METHOD1(), proxygen::ResponseHandler::newPushedResponse(), proxygen::ResponseHandler::pauseIngress(), proxygen::ResponseHandler::refreshTimeout(), proxygen::ResponseHandler::resumeIngress(), proxygen::ResponseHandler::sendAbort(), sendBody(), proxygen::ResponseHandler::sendChunkHeader(), proxygen::ResponseHandler::sendChunkTerminator(), proxygen::ResponseHandler::sendEOM(), and proxygen::ResponseHandler::sendHeaders().
: ResponseHandler(h) {}
Member Function Documentation
const wangle::TransportInfo& proxygen::MockResponseHandler::getSetupTransportInfo () const [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 49 of file Mocks.h.
References transportInfo.
                                                                             {
    return transportInfo;
  }
proxygen::MockResponseHandler::GMOCK_METHOD0_ (noexcept , sendChunkTerminator , void())
Referenced by MockResponseHandler().
proxygen::MockResponseHandler::GMOCK_METHOD0_ (noexcept , sendEOM , void())
proxygen::MockResponseHandler::GMOCK_METHOD0_ (noexcept , sendAbort , void())
proxygen::MockResponseHandler::GMOCK_METHOD0_ (noexcept , refreshTimeout , void())
proxygen::MockResponseHandler::GMOCK_METHOD0_ (noexcept , pauseIngress , void())
proxygen::MockResponseHandler::GMOCK_METHOD0_ (noexcept , resumeIngress , void())
proxygen::MockResponseHandler::GMOCK_METHOD1_ (noexcept , sendHeaders , void(HTTPMessage &))
Referenced by MockResponseHandler().
proxygen::MockResponseHandler::GMOCK_METHOD1_ (noexcept , sendChunkHeader , void(size_t))
proxygen::MockResponseHandler::GMOCK_METHOD1_ (noexcept , sendBody , void(std::shared_ptr< folly::IOBuf >))
proxygen::MockResponseHandler::GMOCK_METHOD1_ (noexcept , sendTrailers , void(const HTTPHeaders &))
proxygen::MockResponseHandler::GMOCK_METHOD1_ (noexcept , newPushedResponse , ResponseHandler * PushHandler *)
proxygen::MockResponseHandler::MOCK_CONST_METHOD1 (getCurrentTransportInfo , void(wangle::TransportInfo *))
Referenced by MockResponseHandler().
void proxygen::MockResponseHandler::sendBody (std::unique_ptr< folly::IOBuf > body) [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 53 of file Mocks.h.
Referenced by MockResponseHandler().
                                                                  {
    if (body) {
      sendBody(std::shared_ptr<folly::IOBuf>(body.release()));
    } else {
      sendBody(std::shared_ptr<folly::IOBuf>(nullptr));
    }
  }
Member Data Documentation
wangle::TransportInfo proxygen::MockResponseHandler::transportInfo
Definition at line 61 of file Mocks.h.
Referenced by getSetupTransportInfo().
The documentation for this class was generated from the following file:
proxygen/httpserver/Mocks.h