PushService::PushRequestHandler Class Reference
#include <PushRequestHandler.h>
Public Member Functions
PushRequestHandler (PushStats *stats)
void onRequest (std::unique_ptr< proxygen::HTTPMessage > headers) noexceptoverride
void onBody (std::unique_ptr< folly::IOBuf > body) noexceptoverride
void onEOM () noexceptoverride
void onUpgrade (proxygen::UpgradeProtocol proto) noexceptoverride
void requestComplete () noexceptoverride
void onError (proxygen::ProxygenError err) noexceptoverride
Private Attributes
PushStats *const stats_ {nullptr}
std::unique_ptr< folly::IOBuf > body_
proxygen::ResponseHandler * downstreamPush_ {nullptr}
Additional Inherited Members
Detailed Description
Definition at line 23 of file PushRequestHandler.h.
Constructor & Destructor Documentation
PushService::PushRequestHandler::PushRequestHandler (PushStats * stats) [explicit]
Definition at line 40 of file PushRequestHandler.cpp.
References PushService::gPushBody, and PushService::kPushFileName().
                                                       : stats_(stats) {
  if (gPushBody.empty()) {
    CHECK(folly::readFile(kPushFileName.c_str(), gPushBody))
      << "Failed to read push file=" << kPushFileName;
  }
}
Member Function Documentation
void PushService::PushRequestHandler::onBody (std::unique_ptr< folly::IOBuf > body) [override], [virtual], [noexcept]
Invoked when we get part of body for the request.
Implements proxygen::RequestHandler .
Definition at line 85 of file PushRequestHandler.cpp.
References body_.
                                                                       {
  if (body_) {
    body_->prependChain(std::move(body));
  } else {
    body_ = std::move(body);
  }
}
void PushService::PushRequestHandler::onEOM () [override], [virtual], [noexcept]
Invoked when we finish receiving the body.
Implements proxygen::RequestHandler .
Definition at line 93 of file PushRequestHandler.cpp.
References proxygen::ResponseBuilder::body(), body_, proxygen::RequestHandler::downstream_, PushService::PushStats::getRequestCount(), proxygen::ResponseBuilder::header(), proxygen::ResponseBuilder::sendWithEOM(), stats_, and proxygen::ResponseBuilder::status().
                                        {
  ResponseBuilder(downstream_)
    .status(200, "OK")
    .header("Request-Number",
            folly::to<std::string>(stats_->getRequestCount()))
    .body(std::move(body_))
    .sendWithEOM();
}
void PushService::PushRequestHandler::onError (proxygen::ProxygenError err) [override], [virtual], [noexcept]
Request failed. Maybe because of read/write error on socket or client not being able to send request in time.
NOTE: Can be invoked at any time (except for before onRequest).
No more callbacks will be invoked after this. You should clean up after yourself.
Implements proxygen::RequestHandler .
Definition at line 110 of file PushRequestHandler.cpp.
                                                         {
  delete this;
}
void PushService::PushRequestHandler::onRequest (std::unique_ptr< proxygen::HTTPMessage > headers) [override], [virtual], [noexcept]
Invoked when we have successfully fetched headers from client. This will always be the first callback invoked on your handler.
Implements proxygen::RequestHandler .
Definition at line 47 of file PushRequestHandler.cpp.
References proxygen::ResponseBuilder::body(), PushService::createLargeBody(), proxygen::RequestHandler::downstream_, downstreamPush_, PushService::generateUrl(), proxygen::ResponseHandler::newPushedResponse(), proxygen::ResponseBuilder::promise(), PushService::PushStats::recordRequest(), proxygen::ResponseBuilder::sendWithEOM(), stats_, and proxygen::ResponseBuilder::status().
                                               {
  stats_->recordRequest();
  if (!headers->getHeaders().getSingleOrEmpty("X-PushIt").empty()) {
    downstreamPush_ = downstream_->newPushedResponse(new PushHandler);
    if (!downstreamPush_) {
      // can't push
      return;
    }
    if(headers->getPath() == "/requestLargePush") {
      LOG(INFO) << "sending large push ";
      ResponseBuilder(downstreamPush_)
        .promise(generateUrl(*headers, "/largePush"),
                 headers->getHeaders().getSingleOrEmpty(HTTP_HEADER_HOST))
        .send();
      ResponseBuilder(downstreamPush_)
        .status(200, "OK")
        .body(createLargeBody())
        .sendWithEOM();
    } else {
      LOG(INFO) << "sending small push ";
      ResponseBuilder(downstreamPush_)
        .promise(generateUrl(*headers, "/pusheen"),
                 headers->getHeaders().getSingleOrEmpty(HTTP_HEADER_HOST))
        .send();
      ResponseBuilder(downstreamPush_)
        .status(200, "OK")
        .body(gPushBody)
        .sendWithEOM();
    }
  }
}
void PushService::PushRequestHandler::onUpgrade (proxygen::UpgradeProtocol prot) [override], [virtual], [noexcept]
Invoked when the session has been upgraded to a different protocol
Implements proxygen::RequestHandler .
Definition at line 102 of file PushRequestHandler.cpp.
                                                             {
  // handler doesn't support upgrades
}
void PushService::PushRequestHandler::requestComplete () [override], [virtual], [noexcept]
Invoked when request processing has been completed and nothing more needs to be done. This may be a good place to log some stats and clean up resources. This is distinct from onEOM() because it is invoked after the response is fully sent. Once this callback has been received, downstream_ should be considered invalid.
Implements proxygen::RequestHandler .
Definition at line 106 of file PushRequestHandler.cpp.
                                                  {
  delete this;
}
Member Data Documentation
std::unique_ptr<folly::IOBuf> PushService::PushRequestHandler::body_ [private]
Definition at line 43 of file PushRequestHandler.h.
Referenced by onBody(), and onEOM().
proxygen::ResponseHandler* PushService::PushRequestHandler::downstreamPush_ {nullptr} [private]
Definition at line 45 of file PushRequestHandler.h.
Referenced by onRequest().
PushStats* const PushService::PushRequestHandler::stats_ {nullptr} [private]
Definition at line 41 of file PushRequestHandler.h.
Referenced by onEOM(), and onRequest().
The documentation for this class was generated from the following files:
proxygen/httpserver/samples/push/PushRequestHandler.h
proxygen/httpserver/samples/push/PushRequestHandler.cpp