proxygen::HTTPHandlerBase Class Reference
#include <HTTPSessionMocks.h>
Public Types
using HeaderMap = std::map< std::string, std::string >
Public Member Functions
HTTPHandlerBase ()
HTTPHandlerBase (HTTPTransaction *txn, HTTPMessage *msg)
void terminate ()
void sendRequest ()
void sendRequest (HTTPMessage req)
void sendHeaders (uint32_t code, uint32_t content_length, bool keepalive=true, HeaderMap headers=HeaderMap())
void sendReply ()
void sendReplyCode (uint32_t code)
void sendBody (uint32_t content_length)
void sendBodyWithLastByteTracking (uint32_t content_length)
void sendReplyWithBody (uint32_t code, uint32_t content_length, bool keepalive=true, bool sendEOM=true, bool hasTrailers=false)
void sendEOM ()
void sendChunkedReplyWithBody (uint32_t code, uint32_t content_length, uint32_t chunkSize, bool hasTrailers, bool sendEOM=true)
Public Attributes
HTTPTransaction * txn_ {nullptr}
std::shared_ptr< HTTPMessage > msg_
Detailed Description
Definition at line 25 of file HTTPSessionMocks.h.
Member Typedef Documentation
using proxygen::HTTPHandlerBase::HeaderMap = std::map<std::string, std::string>
Definition at line 47 of file HTTPSessionMocks.h.
Constructor & Destructor Documentation
proxygen::HTTPHandlerBase::HTTPHandlerBase () [inline]
Definition at line 27 of file HTTPSessionMocks.h.
                    {
  }
proxygen::HTTPHandlerBase::HTTPHandlerBase (HTTPTransaction * txn, HTTPMessage * msg) [inline]
Definition at line 29 of file HTTPSessionMocks.h.
      : txn_(txn), msg_(msg) {
  }
Member Function Documentation
void proxygen::HTTPHandlerBase::sendBody (uint32_t content_length) [inline]
Definition at line 73 of file HTTPSessionMocks.h.
References proxygen::HTTPTransaction::sendBody(), and txn_.
Referenced by sendBodyWithLastByteTracking(), sendReplyWithBody(), and TEST_F().
                                         {
    while (content_length > 0) {
      uint32_t toSend = std::min(content_length, uint32_t(4096));
      char buf[toSend];
      memset(buf, 'a', toSend);
      txn_->sendBody(folly::IOBuf::copyBuffer(buf, toSend));
      content_length -= toSend;
    }
  }
void proxygen::HTTPHandlerBase::sendBodyWithLastByteTracking (uint32_t content_length) [inline]
Definition at line 83 of file HTTPSessionMocks.h.
References sendBody(), proxygen::HTTPTransaction::setLastByteFlushedTrackingEnabled(), and txn_.
                                                             {
    txn_->setLastByteFlushedTrackingEnabled(true);
    sendBody(content_length);
  }
void proxygen::HTTPHandlerBase::sendChunkedReplyWithBody (uint32_t code, uint32_t content_length, uint32_t chunkSize, bool hasTrailers, bool sendEOM = true) [inline]
Definition at line 109 of file HTTPSessionMocks.h.
References proxygen::HTTPHeaders::add(), proxygen::HTTPTransaction::sendBody(), proxygen::HTTPTransaction::sendChunkHeader(), proxygen::HTTPTransaction::sendChunkTerminator(), sendEOM(), proxygen::HTTPTransaction::sendEOM(), proxygen::HTTPTransaction::sendHeaders(), proxygen::HTTPTransaction::sendTrailers(), proxygen::HTTPMessage::setHTTPVersion(), proxygen::HTTPMessage::setIsChunked(), proxygen::HTTPMessage::setStatusCode(), and txn_.
                                                     {
    HTTPMessage reply;
    reply.setStatusCode(code);
    reply.setHTTPVersion(1, 1);
    reply.setIsChunked(true);
    txn_->sendHeaders(reply);
    while (content_length > 0) {
      uint32_t toSend = std::min(content_length, chunkSize);
      char buf[toSend];
      memset(buf, 'a', toSend);
      txn_->sendChunkHeader(toSend);
      txn_->sendBody(folly::IOBuf::copyBuffer(buf, toSend));
      txn_->sendChunkTerminator();
      content_length -= toSend;
    }
    if (hasTrailers) {
      HTTPHeaders trailers;
      trailers.add("X-Trailer1", "Foo");
      txn_->sendTrailers(trailers);
    }
    if (sendEOM) {
      txn_->sendEOM();
    }
  }
void proxygen::HTTPHandlerBase::sendEOM () [inline]
Definition at line 105 of file HTTPSessionMocks.h.
References proxygen::HTTPTransaction::sendEOM(), and txn_.
Referenced by sendChunkedReplyWithBody(), and sendReplyWithBody().
                 {
    txn_->sendEOM();
  }
void proxygen::HTTPHandlerBase::sendHeaders (uint32_t code, uint32_t content_length, bool keepalive = true, HeaderMap headers = HeaderMap()) [inline]
Definition at line 48 of file HTTPSessionMocks.h.
References proxygen::HTTPHeaders::add(), proxygen::HTTPMessage::getHeaders(), proxygen::HTTPTransaction::sendHeaders(), proxygen::HTTPMessage::setHTTPVersion(), proxygen::HTTPMessage::setStatusCode(), proxygen::HTTPMessage::setWantsKeepalive(), and txn_.
Referenced by sendReplyCode(), sendReplyWithBody(), and TEST_F().
                                                    {
    HTTPMessage reply;
    reply.setStatusCode(code);
    reply.setHTTPVersion(1, 1);
    reply.setWantsKeepalive(keepalive);
    reply.getHeaders().add(HTTP_HEADER_CONTENT_LENGTH,
                           folly::to<std::string>(content_length));
    for (auto& nv : headers) {
      reply.getHeaders().add(nv.first, nv.second);
    }
    txn_->sendHeaders(reply);
  }
void proxygen::HTTPHandlerBase::sendReply () [inline]
Definition at line 64 of file HTTPSessionMocks.h.
References sendReplyCode().
                   {
    sendReplyCode(200);
  }
void proxygen::HTTPHandlerBase::sendReplyCode (uint32_t code) [inline]
Definition at line 68 of file HTTPSessionMocks.h.
References proxygen::HTTPTransaction::sendEOM(), sendHeaders(), and txn_.
Referenced by sendReply().
                                    {
    sendHeaders(code, 0, true);
    txn_->sendEOM();
  }
void proxygen::HTTPHandlerBase::sendReplyWithBody (uint32_t code, uint32_t content_length, bool keepalive = true, bool sendEOM = true, bool hasTrailers = false) [inline]
Definition at line 88 of file HTTPSessionMocks.h.
References proxygen::HTTPHeaders::add(), sendBody(), sendEOM(), proxygen::HTTPTransaction::sendEOM(), sendHeaders(), proxygen::HTTPTransaction::sendTrailers(), and txn_.
Referenced by TEST_F().
                                                   {
    sendHeaders(code, content_length, keepalive);
    sendBody(content_length);
    if (hasTrailers) {
      HTTPHeaders trailers;
      trailers.add("X-Trailer1", "Foo");
      txn_->sendTrailers(trailers);
    }
    if (sendEOM) {
      txn_->sendEOM();
    }
  }
void proxygen::HTTPHandlerBase::sendRequest () [inline]
Definition at line 37 of file HTTPSessionMocks.h.
References proxygen::getGetRequest().
Referenced by TEST_F().
                     {
    sendRequest(getGetRequest());
  }
void proxygen::HTTPHandlerBase::sendRequest (HTTPMessage req) [inline]
Definition at line 41 of file HTTPSessionMocks.h.
References proxygen::HTTPTransaction::sendEOM(), proxygen::HTTPTransaction::sendHeaders(), and txn_.
                                    {
    // this copies but it's test code meh
    txn_->sendHeaders(req);
    txn_->sendEOM();
  }
void proxygen::HTTPHandlerBase::terminate () [inline]
Definition at line 33 of file HTTPSessionMocks.h.
References proxygen::HTTPTransaction::sendAbort(), and txn_.
Referenced by HTTPDownstreamTest< SPDY3_1CodecPair >::onEOMTerminateHandlerExpectShutdown().
                   {
    txn_->sendAbort();
  }
Member Data Documentation
std::shared_ptr<HTTPMessage> proxygen::HTTPHandlerBase::msg_
Definition at line 139 of file HTTPSessionMocks.h.
HTTPTransaction* proxygen::HTTPHandlerBase::txn_ {nullptr}
Definition at line 138 of file HTTPSessionMocks.h.
Referenced by proxygen::MockHTTPHandler::expectTransaction(), sendBody(), sendBodyWithLastByteTracking(), sendChunkedReplyWithBody(), sendEOM(), sendHeaders(), proxygen::MockHTTPPushHandler::sendPushHeaders(), sendReplyCode(), sendReplyWithBody(), sendRequest(), terminate(), and TEST_F().
The documentation for this class was generated from the following file:
proxygen/lib/http/session/test/HTTPSessionMocks.h