proxygen::StaticHeaderTable Class Reference
#include <StaticHeaderTable.h>
Public Member Functions
StaticHeaderTable (const char *entries[][2], int size)
Static Public Member Functions
static const StaticHeaderTable & get ()
static bool isHeaderCodeInTableWithNonEmptyValue (HTTPHeaderCode headerCode)
Additional Inherited Members
Detailed Description
Definition at line 17 of file StaticHeaderTable.h.
Constructor & Destructor Documentation
proxygen::StaticHeaderTable::StaticHeaderTable (const char * entries[][2], int size) [explicit]
Definition at line 110 of file StaticHeaderTable.cpp.
References proxygen::HeaderTable::add(), proxygen::HeaderTable::init(), and proxygen::HeaderTable::size().
    : HeaderTable(0) {
  // calculate the size
  list<HPACKHeader> hlist;
  uint32_t byteCount = 0;
  for (int i = 0; i < size; ++i) {
    hlist.push_back(HPACKHeader(entries[i][0], entries[i][1]));
    byteCount += hlist.back().bytes();
  }
  // initialize with a capacity that will exactly fit the static headers
  init(byteCount);
  hlist.reverse();
  for (auto& header : hlist) {
    add(std::move(header));
  }
}
Member Function Documentation
const StaticHeaderTable & proxygen::StaticHeaderTable::get () [static]
Definition at line 129 of file StaticHeaderTable.cpp.
Referenced by proxygen::HPACKContext::getStaticTable().
                                                {
  static const folly::Indestructible<StaticHeaderTable> table(
    s_tableEntries, kEntriesSize);
  return *table;
}
bool proxygen::StaticHeaderTable::isHeaderCodeInTableWithNonEmptyValue (HTTPHeaderCode headerCode) [static]
Definition at line 95 of file StaticHeaderTable.cpp.
Referenced by proxygen::HPACKContext::getIndex().
                               {
  switch(headerCode) {
    case HTTP_HEADER_COLON_METHOD:
    case HTTP_HEADER_COLON_PATH:
    case HTTP_HEADER_COLON_SCHEME:
    case HTTP_HEADER_COLON_STATUS:
    case HTTP_HEADER_ACCEPT_ENCODING:
      return true;
    default:
      return false;
  }
}
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/compress/StaticHeaderTable.h
proxygen/lib/http/codec/compress/StaticHeaderTable.cpp