proxygen::HTTPSessionBase::InfoCallback Class Reference
#include <HTTPSessionBase.h>
Public Member Functions
virtual ~InfoCallback ()
virtual void onCreate (const HTTPSessionBase &)
virtual void onTransportReady (const HTTPSessionBase &)
virtual void onConnectionError (const HTTPSessionBase &)
virtual void onFullHandshakeCompletion (const HTTPSessionBase &)
virtual void onIngressError (const HTTPSessionBase &, ProxygenError)
virtual void onIngressEOF ()
virtual void onRead (const HTTPSessionBase &, size_t)
virtual void onWrite (const HTTPSessionBase &, size_t)
virtual void onRequestBegin (const HTTPSessionBase &)
virtual void onRequestEnd (const HTTPSessionBase &, uint32_t)
virtual void onActivateConnection (const HTTPSessionBase &)
virtual void onDeactivateConnection (const HTTPSessionBase &)
virtual void onDestroy (const HTTPSessionBase &)
virtual void onIngressMessage (const HTTPSessionBase &, const HTTPMessage &)
virtual void onIngressLimitExceeded (const HTTPSessionBase &)
virtual void onIngressPaused (const HTTPSessionBase &)
virtual void onTransactionDetached (const HTTPSessionBase &)
virtual void onPingReplySent (int64_t)
virtual void onPingReplyReceived ()
virtual void onSettingsOutgoingStreamsFull (const HTTPSessionBase &)
virtual void onSettingsOutgoingStreamsNotFull (const HTTPSessionBase &)
virtual void onFlowControlWindowClosed (const HTTPSessionBase &)
virtual void onEgressBuffered (const HTTPSessionBase &)
virtual void onEgressBufferCleared (const HTTPSessionBase &)
virtual void onSettings (const HTTPSessionBase &, const SettingsList &)
virtual void onSettingsAck (const HTTPSessionBase &)
Detailed Description
Optional callback interface that the HTTPSessionBase notifies of connection lifecycle events.
Definition at line 47 of file HTTPSessionBase.h.
Constructor & Destructor Documentation
virtual proxygen::HTTPSessionBase::InfoCallback::~InfoCallback () [inline], [virtual]
Definition at line 49 of file HTTPSessionBase.h.
{}
Member Function Documentation
virtual void proxygen::HTTPSessionBase::InfoCallback::onActivateConnection (const HTTPSessionBase &) [inline], [virtual]
Definition at line 63 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::createTransaction().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onConnectionError (const HTTPSessionBase &) [inline], [virtual]
Definition at line 54 of file HTTPSessionBase.h.
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onCreate (const HTTPSessionBase &) [inline], [virtual]
Reimplemented in HTTPUpstreamTest< C > , and HTTPTargetSessionAcceptor .
Definition at line 52 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::WriteSegment::writeErr().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onDeactivateConnection (const HTTPSessionBase &) [inline], [virtual]
Definition at line 64 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::detach().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onDestroy (const HTTPSessionBase &) [inline], [virtual]
Reimplemented in HTTPUpstreamTest< C > .
Definition at line 66 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSessionBase::runDestroyCallbacks().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onEgressBufferCleared (const HTTPSessionBase &) [inline], [virtual]
Definition at line 78 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::onEgressBufferCleared().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onEgressBuffered (const HTTPSessionBase &) [inline], [virtual]
Definition at line 77 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::onEgressBuffered().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onFlowControlWindowClosed (const HTTPSessionBase &) [inline], [virtual]
Definition at line 76 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::onConnectionSendWindowClosed().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onFullHandshakeCompletion (const HTTPSessionBase &) [inline], [virtual]
Definition at line 55 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::onReplaySafe().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onIngressEOF () [inline], [virtual]
Definition at line 57 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::shutdownTransport().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onIngressError (const HTTPSessionBase & , ProxygenError) [inline], [virtual]
Definition at line 56 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSessionBase::handleErrorDirectly(), proxygen::HTTPSession::onError(), proxygen::HTTPSession::readEOF(), proxygen::HTTPSession::readErr(), proxygen::HTTPSession::shutdownTransport(), and proxygen::HTTPSession::transactionTimeout().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onIngressLimitExceeded (const HTTPSessionBase &) [inline], [virtual]
Definition at line 69 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSessionBase::onBodyImpl().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onIngressMessage (const HTTPSessionBase & , const HTTPMessage &) [inline], [virtual]
Definition at line 67 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::onHeadersComplete().
                                                      {}
virtual void proxygen::HTTPSessionBase::InfoCallback::onIngressPaused (const HTTPSessionBase &) [inline], [virtual]
Definition at line 70 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::pauseReadsImpl().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onPingReplyReceived () [inline], [virtual]
Definition at line 73 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::onPingReply().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onPingReplySent (int64_t) [inline], [virtual]
Definition at line 72 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::onPingReplyLatency().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onRead (const HTTPSessionBase & , size_t) [inline], [virtual]
Definition at line 58 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::readBufferAvailable(), and proxygen::HTTPSession::readDataAvailable().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onRequestBegin (const HTTPSessionBase &) [inline], [virtual]
Definition at line 60 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::onError(), proxygen::HTTPSession::onExMessageBegin(), proxygen::HTTPSession::onMessageBegin(), and proxygen::HTTPSession::onPushMessageBegin().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onRequestEnd (const HTTPSessionBase & , uint32_t) [inline], [virtual]
Definition at line 61 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::onEgressMessageFinished().
                                          {}
virtual void proxygen::HTTPSessionBase::InfoCallback::onSettings (const HTTPSessionBase & , const SettingsList &) [inline], [virtual]
Definition at line 79 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::onSettings().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onSettingsAck (const HTTPSessionBase &) [inline], [virtual]
Definition at line 80 of file HTTPSessionBase.h.
References proxygen::localAddr, and proxygen::peerAddr.
Referenced by proxygen::HTTPSession::onSettingsAck().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onSettingsOutgoingStreamsFull (const HTTPSessionBase &) [inline], [virtual]
Reimplemented in HTTPUpstreamTest< C > .
Definition at line 74 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::onSetMaxInitiatedStreams().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onSettingsOutgoingStreamsNotFull (const HTTPSessionBase &) [inline], [virtual]
Reimplemented in HTTPUpstreamTest< C > .
Definition at line 75 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::onSetMaxInitiatedStreams().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onTransactionDetached (const HTTPSessionBase &) [inline], [virtual]
Definition at line 71 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::detach().
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onTransportReady (const HTTPSessionBase &) [inline], [virtual]
Definition at line 53 of file HTTPSessionBase.h.
{}
virtual void proxygen::HTTPSessionBase::InfoCallback::onWrite (const HTTPSessionBase & , size_t) [inline], [virtual]
Definition at line 59 of file HTTPSessionBase.h.
Referenced by proxygen::HTTPSession::onWriteError(), and proxygen::HTTPSession::onWriteSuccess().
{}
The documentation for this class was generated from the following file:
proxygen/lib/http/session/HTTPSessionBase.h