proxygen::TimeUtilGeneric< ClockType > Class Template Reference
#include <Time.h>
Public Member Functions
virtual ~TimeUtilGeneric ()
virtual std::chrono::time_point< ClockType > now () const
virtual uint64_t msSinceEpoch ()
Static Public Member Functions
static const std::chrono::time_point< ClockType > & getZeroTimePoint ()
Detailed Description
template<typename ClockType = SteadyClock>
*
class proxygen::TimeUtilGeneric< ClockType >
Class used to get steady time. We use a separate class to mock it easier.
Definition at line 170 of file Time.h.
Constructor & Destructor Documentation
template<typename ClockType = SteadyClock> virtual proxygen::TimeUtilGeneric< ClockType >::~TimeUtilGeneric () [inline], [virtual]
Definition at line 172 of file Time.h.
{}
Member Function Documentation
template<typename ClockType = SteadyClock> static const std::chrono::time_point<ClockType>& proxygen::TimeUtilGeneric< ClockType >::getZeroTimePoint () [inline], [static]
Definition at line 178 of file Time.h.
Referenced by proxygen::compress::SimStreamingCallback::onHeadersComplete().
                                                                  {
    const static std::chrono::time_point<ClockType> kZeroTimePoint{};
    return kZeroTimePoint;
  }
template<typename ClockType = SteadyClock> virtual uint64_t proxygen::TimeUtilGeneric< ClockType >::msSinceEpoch () [inline], [virtual]
Please use strongly typed time_point. This is for avoiding the copy and garbage collection of time_point in Lua.
Definition at line 187 of file Time.h.
References proxygen::millisecondsSinceEpoch().
                                  {
    return millisecondsSinceEpoch().count();
  }
template<typename ClockType = SteadyClock> virtual std::chrono::time_point<ClockType> proxygen::TimeUtilGeneric< ClockType >::now () const [inline], [virtual]
Reimplemented in proxygen::MockTimeUtilGeneric< ClockType > .
Definition at line 174 of file Time.h.
Referenced by proxygen::TraceEvent::end(), and proxygen::TraceEvent::start().
                                                     {
    return getCurrentTime<ClockType>();
  }
The documentation for this class was generated from the following file:
proxygen/lib/utils/Time.h