proxygen::IOBufPrinter Class Reference
#include <Logging.h>
Public Types
enum Format : uint8_t { Format::HEX_FOLLY = 0,
Format::HEX_16 = 1,
Format::CHAIN_INFO = 2,
Format::BIN = 3
 }
Public Member Functions
IOBufPrinter ()
virtual ~IOBufPrinter ()
virtual std::string print (const folly::IOBuf *buf)=0
Static Public Member Functions
static std::string printChain (const folly::IOBuf *buf, Format format, bool coalesce)
static std::string printHexFolly (const folly::IOBuf *buf, bool coalesce=false)
static std::string printHex16 (const folly::IOBuf *buf, bool coalesce=false)
static std::string printChainInfo (const folly::IOBuf *buf)
static std::string printBin (const folly::IOBuf *buf, bool coalesce=false)
Detailed Description
Definition at line 114 of file Logging.h.
Member Enumeration Documentation
enum proxygen::IOBufPrinter::Format : uint8_t [strong]
Enumerator
HEX_FOLLY
HEX_16
CHAIN_INFO
BIN
Definition at line 116 of file Logging.h.
                    : uint8_t {
    HEX_FOLLY = 0,
    HEX_16 = 1,
    CHAIN_INFO = 2,
    BIN = 3,
  };
Constructor & Destructor Documentation
proxygen::IOBufPrinter::IOBufPrinter () [inline]
Definition at line 144 of file Logging.h.
{}
virtual proxygen::IOBufPrinter::~IOBufPrinter () [inline], [virtual]
Definition at line 145 of file Logging.h.
{}
Member Function Documentation
virtual std::string proxygen::IOBufPrinter::print (const folly::IOBuf * buf) [pure virtual]
Implemented in proxygen::BinPrinter , proxygen::ChainInfoPrinter , proxygen::HexFollyPrinter , and proxygen::Hex16Printer .
static std::string proxygen::IOBufPrinter::printBin (const folly::IOBuf * buf, bool coalesce = false) [inline], [static]
Definition at line 140 of file Logging.h.
Referenced by proxygen::HPACKEncodeBuffer::toBin().
                                                                        {
    return printChain(buf, Format::BIN, coalesce);
  }
string proxygen::IOBufPrinter::printChain (const folly::IOBuf * buf, Format format, bool coalesce) [static]
Definition at line 104 of file Logging.cpp.
References proxygen::ERROR.
                                               {
  uint8_t index = (uint8_t) format;
  if (printers.size() <= index) {
    LOG(ERROR) << "invalid format: " << index;
    return "";
  }
  auto printer = printers[index];
  // empty chain
  if (!buf) {
    return "";
  }
  unique_ptr<IOBuf> cbuf = nullptr;
  if (coalesce) {
    cbuf = buf->clone();
    cbuf->coalesce();
    buf = cbuf.get();
  }
  auto b = buf;
  string res;
  do {
    res += printer->print(b);
    b = b->next();
  } while (b != buf);
  return res;
}
static std::string proxygen::IOBufPrinter::printChainInfo (const folly::IOBuf * buf) [inline], [static]
Definition at line 136 of file Logging.h.
Referenced by proxygen::dumpBinToFile().
                                                         {
    return printChain(buf, Format::CHAIN_INFO, false);
  }
static std::string proxygen::IOBufPrinter::printHex16 (const folly::IOBuf * buf, bool coalesce = false) [inline], [static]
Definition at line 132 of file Logging.h.
                                                                          {
    return printChain(buf, Format::HEX_16, coalesce);
  }
static std::string proxygen::IOBufPrinter::printHexFolly (const folly::IOBuf * buf, bool coalesce = false) [inline], [static]
Definition at line 127 of file Logging.h.
Referenced by proxygen::HTTP2Codec::checkConnectionError(), proxygen::HTTP2Codec::parseHeadersDecodeFrames(), and proxygen::GzipHeaderCodec::parseNameValues().
                                                        {
    return printChain(buf, Format::HEX_FOLLY, coalesce);
  }
The documentation for this class was generated from the following files:
proxygen/lib/utils/Logging.h
proxygen/lib/utils/Logging.cpp