proxygen::MockSecondaryAuthManager Class Reference
#include <MockSecondaryAuthManager.h>
Public Member Functions
MOCK_METHOD2 (createAuthRequest, std::pair< uint16_t, std::unique_ptr< folly::IOBuf >>(std::shared_ptr< folly::IOBuf >, std::vector< fizz::Extension > &))
std::pair< uint16_t, std::unique_ptr< folly::IOBuf > > createAuthRequest (std::unique_ptr< folly::IOBuf > certRequestContext, std::vector< fizz::Extension > extensions) override
MOCK_METHOD4 (getAuthenticator, std::pair< uint16_t, std::unique_ptr< folly::IOBuf >>(const fizz::AsyncFizzBase &, TransportDirection, uint16_t, std::shared_ptr< folly::IOBuf >))
std::pair< uint16_t, std::unique_ptr< folly::IOBuf > > getAuthenticator (const fizz::AsyncFizzBase &transport, TransportDirection dir, uint16_t requestId, std::unique_ptr< folly::IOBuf > authRequest) override
MOCK_METHOD4 (validateAuthenticator, bool(const fizz::AsyncFizzBase &, TransportDirection, uint16_t, std::shared_ptr< folly::IOBuf >))
bool validateAuthenticator (const fizz::AsyncFizzBase &transport, TransportDirection dir, uint16_t certId, std::unique_ptr< folly::IOBuf > authenticator) override
Detailed Description
Definition at line 17 of file MockSecondaryAuthManager.h.
Member Function Documentation
std::pair<uint16_t, std::unique_ptr<folly::IOBuf> > proxygen::MockSecondaryAuthManager::createAuthRequest (std::unique_ptr< folly::IOBuf > certRequestContext, std::vector< fizz::Extension > extensions) [inline], [override], [virtual]
Generate an authenticator request given a certificate_request_context and a set of extensions.
Returns
(request ID, encoded authenticator request)
Reimplemented from proxygen::SecondaryAuthManager .
Definition at line 23 of file MockSecondaryAuthManager.h.
References getAuthenticator(), and MOCK_METHOD4().
                                                    {
    return createAuthRequest(
        std::shared_ptr<folly::IOBuf>(certRequestContext.release()),
        extensions);
  }
std::pair<uint16_t, std::unique_ptr<folly::IOBuf> > proxygen::MockSecondaryAuthManager::getAuthenticator (const fizz::AsyncFizzBase & transport, TransportDirection dir, uint16_t requestId, std::unique_ptr< folly::IOBuf > authRequest) [inline], [override], [virtual]
Generate an authenticator request given the Request-ID and authenticator request..
Returns
(cert ID, encoded authenticator)
Reimplemented from proxygen::SecondaryAuthManager .
Definition at line 36 of file MockSecondaryAuthManager.h.
References MOCK_METHOD4(), and validateAuthenticator().
Referenced by createAuthRequest().
                                                      {
    return getAuthenticator(
        transport,
        dir,
        requestId,
        std::shared_ptr<folly::IOBuf>(authRequest.release()));
  }
proxygen::MockSecondaryAuthManager::MOCK_METHOD2 (createAuthRequest , std::pair< uint16_t, std::unique_ptr< folly::IOBuf >> std::shared_ptr< folly::IOBuf >, std::vector< fizz::Extension > &)
proxygen::MockSecondaryAuthManager::MOCK_METHOD4 (getAuthenticator , std::pair< uint16_t, std::unique_ptr< folly::IOBuf >> const fizz::AsyncFizzBase &, TransportDirection, uint16_t, std::shared_ptr< folly::IOBuf >)
Referenced by createAuthRequest(), and getAuthenticator().
proxygen::MockSecondaryAuthManager::MOCK_METHOD4 (validateAuthenticator , bool(const fizz::AsyncFizzBase &, TransportDirection, uint16_t, std::shared_ptr< folly::IOBuf >))
bool proxygen::MockSecondaryAuthManager::validateAuthenticator (const fizz::AsyncFizzBase & transport, TransportDirection dir, uint16_t certId, std::unique_ptr< folly::IOBuf > authenticator) [inline], [override], [virtual]
Validate an authenticator and cache the received certificate along with the Cert-ID if it is valid.
Reimplemented from proxygen::SecondaryAuthManager .
Definition at line 52 of file MockSecondaryAuthManager.h.
Referenced by getAuthenticator().
                                                        {
    return validateAuthenticator(
        transport,
        dir,
        certId,
        std::shared_ptr<folly::IOBuf>(authenticator.release()));
  }
The documentation for this class was generated from the following file:
proxygen/lib/http/session/test/MockSecondaryAuthManager.h