proxygen::ZlibStreamDecompressor Class Reference
#include <ZlibStreamDecompressor.h>
Public Member Functions
ZlibStreamDecompressor (ZlibCompressionType type)
ZlibStreamDecompressor ()
~ZlibStreamDecompressor ()
void init (ZlibCompressionType type)
std::unique_ptr< folly::IOBuf > decompress (const folly::IOBuf *in)
int getStatus ()
bool hasError ()
bool finished ()
Private Attributes
ZlibCompressionType type_ {ZlibCompressionType::NONE}
z_stream zlibStream_
int status_ {-1}
Detailed Description
Definition at line 31 of file ZlibStreamDecompressor.h.
Constructor & Destructor Documentation
proxygen::ZlibStreamDecompressor::ZlibStreamDecompressor (ZlibCompressionType type) [explicit]
Definition at line 46 of file ZlibStreamDecompressor.cpp.
References init().
    : type_(ZlibCompressionType::NONE), status_(Z_OK) {
  init(type);
}
proxygen::ZlibStreamDecompressor::ZlibStreamDecompressor () [inline]
Definition at line 35 of file ZlibStreamDecompressor.h.
{ }
proxygen::ZlibStreamDecompressor::~ZlibStreamDecompressor ()
Definition at line 51 of file ZlibStreamDecompressor.cpp.
References proxygen::NONE, status_, type_, and zlibStream_.
                                                {
  if (type_ != ZlibCompressionType::NONE) {
    status_ = inflateEnd(&zlibStream_);
  }
}
Member Function Documentation
std::unique_ptr< IOBuf > proxygen::ZlibStreamDecompressor::decompress (const folly::IOBuf * in)
Definition at line 57 of file ZlibStreamDecompressor.cpp.
References proxygen::ERROR, status_, and zlibStream_.
Referenced by ZlibServerFilterTest::exercise_compression().
                                                                       {
  auto out = IOBuf::create(FLAGS_zlib_buffer_growth);
  auto appender = folly::io::Appender(out.get(),
      FLAGS_zlib_buffer_growth);
  const IOBuf* crtBuf = in;
  size_t offset = 0;
  while (true) {
    // Advance to the next IOBuf if necessary
    DCHECK_GE(crtBuf->length(), offset);
    if (crtBuf->length() == offset) {
      crtBuf = crtBuf->next();
      offset = 0;
      if (crtBuf == in) {
        // We hit the end of the IOBuf chain, and are done.
        break;
      }
    }
    if (status_ == Z_STREAM_END) {
      // we convert this into a stream error
      status_ = Z_STREAM_ERROR;
      // we should probably bump up a counter here
      LOG(ERROR) << "error uncompressing buffer: reached end of zlib data "
        "before the end of the buffer";
      return nullptr;
    }
    // Ensure there is space in the output IOBuf
    appender.ensure(FLAGS_zlib_buffer_minsize);
    DCHECK_GT(appender.length(), 0);
    const size_t origAvailIn = crtBuf->length() - offset;
    zlibStream_.next_in = const_cast<uint8_t*>(crtBuf->data() + offset);
    zlibStream_.avail_in = origAvailIn;
    zlibStream_.next_out = appender.writableData();
    zlibStream_.avail_out = appender.length();
    status_ = inflate(&zlibStream_, Z_PARTIAL_FLUSH);
    if (status_ != Z_OK && status_ != Z_STREAM_END) {
      LOG(INFO) << "error uncompressing buffer: r=" << status_;
      return nullptr;
    }
    // Adjust the input offset ahead
    auto inConsumed = origAvailIn - zlibStream_.avail_in;
    offset += inConsumed;
    // Move output buffer ahead
    auto outMove = appender.length() - zlibStream_.avail_out;
    appender.append(outMove);
  }
  return out;
}
bool proxygen::ZlibStreamDecompressor::finished () [inline]
Definition at line 47 of file ZlibStreamDecompressor.h.
{ return status_ == Z_STREAM_END; }
int proxygen::ZlibStreamDecompressor::getStatus () [inline]
Definition at line 43 of file ZlibStreamDecompressor.h.
Referenced by ZlibServerFilterTest::exercise_compression().
{ return status_; }
bool proxygen::ZlibStreamDecompressor::hasError () [inline]
Definition at line 45 of file ZlibStreamDecompressor.h.
Referenced by ZlibServerFilterTest::exercise_compression().
{ return status_ != Z_OK && status_ != Z_STREAM_END; }
void proxygen::ZlibStreamDecompressor::init (ZlibCompressionType type)
Definition at line 29 of file ZlibStreamDecompressor.cpp.
References proxygen::NONE, status_, type_, and zlibStream_.
Referenced by ZlibStreamDecompressor().
                                                          {
  DCHECK(type_ == ZlibCompressionType::NONE) << "Must be uninitialized";
  type_ = type;
  status_ = Z_OK;
  zlibStream_.zalloc = Z_NULL;
  zlibStream_.zfree = Z_NULL;
  zlibStream_.opaque = Z_NULL;
  zlibStream_.total_in = 0;
  zlibStream_.next_in = Z_NULL;
  zlibStream_.avail_in = 0;
  zlibStream_.avail_out = 0;
  zlibStream_.next_out = Z_NULL;
  DCHECK(type != ZlibCompressionType::NONE);
  status_ = inflateInit2(&zlibStream_, static_cast<int>(type_));
}
Member Data Documentation
int proxygen::ZlibStreamDecompressor::status_ {-1} [private]
Definition at line 52 of file ZlibStreamDecompressor.h.
Referenced by decompress(), init(), and ~ZlibStreamDecompressor().
ZlibCompressionType proxygen::ZlibStreamDecompressor::type_ {ZlibCompressionType::NONE} [private]
Definition at line 50 of file ZlibStreamDecompressor.h.
Referenced by init(), and ~ZlibStreamDecompressor().
z_stream proxygen::ZlibStreamDecompressor::zlibStream_ [private]
Definition at line 51 of file ZlibStreamDecompressor.h.
Referenced by decompress(), init(), and ~ZlibStreamDecompressor().
The documentation for this class was generated from the following files:
proxygen/lib/utils/ZlibStreamDecompressor.h
proxygen/lib/utils/ZlibStreamDecompressor.cpp