proxygen::MockHTTPTransaction Class Reference
#include <HTTPTransactionMocks.h>
Public Member Functions
MockHTTPTransaction (TransportDirection direction, HTTPCodec::StreamID id, uint32_t seqNo, const HTTP2PriorityQueue &egressQueue, folly::HHWheelTimer *timer=nullptr, const folly::Optional< std::chrono::milliseconds > &transactionTimeout=folly::Optional< std::chrono::milliseconds >(), HTTPSessionStats *stats=nullptr, bool useFlowControl=false, uint32_t receiveInitialWindowSize=0, uint32_t sendInitialWindowSize=0, http2::PriorityUpdate priority=http2::DefaultPriority, folly::Optional< HTTPCodec::StreamID > assocStreamId=HTTPCodec::NoStream, folly::Optional< HTTPCodec::ExAttributes > exAttributes=HTTPCodec::NoExAttributes)
MockHTTPTransaction (TransportDirection direction, HTTPCodec::StreamID id, uint32_t seqNo, const HTTP2PriorityQueue &egressQueue, const WheelTimerInstance &timeout, HTTPSessionStats *stats=nullptr, bool useFlowControl=false, uint32_t receiveInitialWindowSize=0, uint32_t sendInitialWindowSize=0, http2::PriorityUpdate priority=http2::DefaultPriority, folly::Optional< HTTPCodec::StreamID > assocStreamId=HTTPCodec::NoStream, folly::Optional< HTTPCodec::ExAttributes > exAttributes=HTTPCodec::NoExAttributes)
MockHTTPTransaction (TransportDirection direction, HTTPCodec::StreamID id, uint32_t seqNo, const HTTP2PriorityQueue &egressQueue, const WheelTimerInstance &timeout, folly::Optional< HTTPCodec::ExAttributes > exAttributes)
MOCK_CONST_METHOD0 (extraResponseExpected, bool())
MOCK_METHOD1 (setHandler, void(HTTPTransactionHandler *))
void setHandlerUnmocked (HTTPTransactionHandler *handler)
MOCK_CONST_METHOD0 (canSendHeaders, bool())
MOCK_METHOD1 (sendHeaders, void(const HTTPMessage &headers))
MOCK_METHOD1 (sendHeadersWithEOM, void(const HTTPMessage &headers))
MOCK_METHOD1 (sendBody, void(std::shared_ptr< folly::IOBuf >))
void sendBody (std::unique_ptr< folly::IOBuf > iob) noexceptoverride
MOCK_METHOD1 (sendChunkHeader, void(size_t))
MOCK_METHOD0 (sendChunkTerminator, void())
MOCK_METHOD1 (sendTrailers, void(const HTTPHeaders &trailers))
MOCK_METHOD0 (sendEOM, void())
MOCK_METHOD0 (sendAbort, void())
MOCK_METHOD0 (drop, void())
MOCK_METHOD0 (pauseIngress, void())
MOCK_METHOD0 (resumeIngress, void())
MOCK_CONST_METHOD0 (handlerEgressPaused, bool())
MOCK_METHOD1 (newPushedTransaction, HTTPTransaction *(HTTPPushTransactionHandler *))
MOCK_METHOD1 (setReceiveWindow, void(uint32_t))
MOCK_CONST_METHOD0 (getReceiveWindow, const Window &())
MOCK_METHOD1 (addWaitingForReplaySafety, void(folly::AsyncTransport::ReplaySafetyCallback *))
MOCK_METHOD1 (removeWaitingForReplaySafety, void(folly::AsyncTransport::ReplaySafetyCallback *))
void enablePush ()
Public Attributes
testing::NiceMock< MockHTTPTransactionTransport > mockTransport_
const folly::SocketAddress defaultAddress_
MockHTTPCodec mockCodec_
wangle::TransportInfo setupTransportInfo_
Additional Inherited Members
Detailed Description
Definition at line 127 of file HTTPTransactionMocks.h.
Constructor & Destructor Documentation
[MockHTTPTransaction(TransportDirection direction, HTTPCodec::StreamID id, uint32_t seqNo, const HTTP2PriorityQueue &egressQueue, folly::HHWheelTimer *timer=nullptr, const folly::Optional< std::chrono::milliseconds > &transactionTimeout=folly::Optional< std::chrono::milliseconds >(), HTTPSessionStats *stats=nullptr, bool useFlowControl=false, uint32_t receiveInitialWindowSize=0, uint32_t sendInitialWindowSize=0, http2::PriorityUpdate priority=http2::DefaultPriority, folly::Optional< HTTPCodec::StreamID > assocStreamId=HTTPCodec::NoStream, folly::Optional< HTTPCodec::ExAttributes > exAttributes=HTTPCodec::NoExAttributes)]proxygen::MockHTTPTransaction::MockHTTPTransaction (TransportDirection direction, HTTPCodec::StreamID id, uint32_t seqNo, const HTTP2PriorityQueue & egressQueue, folly::HHWheelTimer * timer = nullptr, const folly::Optional< std::chrono::milliseconds > & transactionTimeout = folly::Optional<std::chrono::milliseconds>(), HTTPSessionStats * stats = nullptr, bool useFlowControl = false, uint32_t receiveInitialWindowSize = 0, uint32_t sendInitialWindowSize = 0, http2::PriorityUpdate priority = http2::DefaultPriority, folly::Optional< HTTPCodec::StreamID > assocStreamId = HTTPCodec::NoStream, folly::Optional< HTTPCodec::ExAttributes > exAttributes = HTTPCodec::NoExAttributes) [inline]
Definition at line 129 of file HTTPTransactionMocks.h.
References proxygen::MockHTTPTransactionTransport::mockCodec_.
                                               :
      HTTPTransaction(direction, id, seqNo, mockTransport_,
                      const_cast<HTTP2PriorityQueue&>(egressQueue),
                      timer, transactionTimeout, stats, useFlowControl,
                      receiveInitialWindowSize,
                      sendInitialWindowSize,
                      priority, assocStreamId, exAttributes),
      defaultAddress_("127.0.0.1", 80) {
    EXPECT_CALL(mockTransport_, getLocalAddressNonConst())
      .WillRepeatedly(testing::ReturnRef(defaultAddress_));
    EXPECT_CALL(mockTransport_, getPeerAddressNonConst())
      .WillRepeatedly(testing::ReturnRef(defaultAddress_));
    EXPECT_CALL(mockTransport_, getCodecNonConst())
      .WillRepeatedly(testing::ReturnRef(mockCodec_));
    EXPECT_CALL(mockTransport_, getSetupTransportInfoNonConst())
      .WillRepeatedly(testing::ReturnRef(setupTransportInfo_));
    // Some tests unfortunately require a half-mocked HTTPTransaction.
    ON_CALL(*this, setHandler(testing::_))
      .WillByDefault(testing::Invoke([this] (HTTPTransactionHandler* handler) {
            this->setHandlerUnmocked(handler);
        }));
    // By default we expect canSendHeaders in test to return true
    // Tests that specifically require canSendHeaders to return false need
    // to set the behavior locally. This is due to the fact that the mocked
    // methods below imply internal state is not correctly tracked/managed
    // in the context of tests
    ON_CALL(*this, canSendHeaders()).WillByDefault(testing::Return(true));
  }
[MockHTTPTransaction(TransportDirection direction, HTTPCodec::StreamID id, uint32_t seqNo, const HTTP2PriorityQueue &egressQueue, const WheelTimerInstance &timeout, HTTPSessionStats *stats=nullptr, bool useFlowControl=false, uint32_t receiveInitialWindowSize=0, uint32_t sendInitialWindowSize=0, http2::PriorityUpdate priority=http2::DefaultPriority, folly::Optional< HTTPCodec::StreamID > assocStreamId=HTTPCodec::NoStream, folly::Optional< HTTPCodec::ExAttributes > exAttributes=HTTPCodec::NoExAttributes)]proxygen::MockHTTPTransaction::MockHTTPTransaction (TransportDirection direction, HTTPCodec::StreamID id, uint32_t seqNo, const HTTP2PriorityQueue & egressQueue, const WheelTimerInstance & timeout, HTTPSessionStats * stats = nullptr, bool useFlowControl = false, uint32_t receiveInitialWindowSize = 0, uint32_t sendInitialWindowSize = 0, http2::PriorityUpdate priority = http2::DefaultPriority, folly::Optional< HTTPCodec::StreamID > assocStreamId = HTTPCodec::NoStream, folly::Optional< HTTPCodec::ExAttributes > exAttributes = HTTPCodec::NoExAttributes) [inline]
Definition at line 177 of file HTTPTransactionMocks.h.
                                               :
  MockHTTPTransaction(direction,
                      id,
                      seqNo,
                      egressQueue,
                      timeout.getWheelTimer(),
                      timeout.getDefaultTimeout(),
                      stats,
                      useFlowControl,
                      receiveInitialWindowSize,
                      sendInitialWindowSize,
                      priority,
                      assocStreamId,
                      exAttributes) {}
proxygen::MockHTTPTransaction::MockHTTPTransaction (TransportDirection direction, HTTPCodec::StreamID id, uint32_t seqNo, const HTTP2PriorityQueue & egressQueue, const WheelTimerInstance & timeout, folly::Optional< HTTPCodec::ExAttributes > exAttributes) [inline]
Definition at line 206 of file HTTPTransactionMocks.h.
References proxygen::MockHTTPTransactionTransport::MOCK_CONST_METHOD0(), and proxygen::MockHTTPTransactionTransport::MOCK_METHOD1().
                                                                         :
  MockHTTPTransaction(direction,
                      id,
                      seqNo,
                      egressQueue,
                      timeout.getWheelTimer(),
                      timeout.getDefaultTimeout(),
                      nullptr,
                      false,
                      0,
                      0,
                      http2::DefaultPriority,
                      HTTPCodec::NoStream,
                      exAttributes) {}
Member Function Documentation
void proxygen::MockHTTPTransaction::enablePush () [inline]
Definition at line 261 of file HTTPTransactionMocks.h.
References proxygen::MockHTTPTransactionTransport::mockCodec_.
                    {
    EXPECT_CALL(mockCodec_, supportsPushTransactions())
      .WillRepeatedly(testing::Return(true));
  }
proxygen::MockHTTPTransaction::MOCK_CONST_METHOD0 (extraResponseExpected , bool())
proxygen::MockHTTPTransaction::MOCK_CONST_METHOD0 (canSendHeaders , bool())
proxygen::MockHTTPTransaction::MOCK_CONST_METHOD0 (handlerEgressPaused , bool())
proxygen::MockHTTPTransaction::MOCK_CONST_METHOD0 (getReceiveWindow , const Window & ())
proxygen::MockHTTPTransaction::MOCK_METHOD0 (sendChunkTerminator , void())
proxygen::MockHTTPTransaction::MOCK_METHOD0 (sendEOM , void())
proxygen::MockHTTPTransaction::MOCK_METHOD0 (sendAbort , void())
proxygen::MockHTTPTransaction::MOCK_METHOD0 (drop , void())
proxygen::MockHTTPTransaction::MOCK_METHOD0 (pauseIngress , void())
proxygen::MockHTTPTransaction::MOCK_METHOD0 (resumeIngress , void())
proxygen::MockHTTPTransaction::MOCK_METHOD1 (setHandler , void(HTTPTransactionHandler *))
proxygen::MockHTTPTransaction::MOCK_METHOD1 (sendHeaders , void(const HTTPMessage &headers))
proxygen::MockHTTPTransaction::MOCK_METHOD1 (sendHeadersWithEOM , void(const HTTPMessage &headers))
proxygen::MockHTTPTransaction::MOCK_METHOD1 (sendBody , void(std::shared_ptr< folly::IOBuf >))
proxygen::MockHTTPTransaction::MOCK_METHOD1 (sendChunkHeader , void(size_t))
proxygen::MockHTTPTransaction::MOCK_METHOD1 (sendTrailers , void(const HTTPHeaders &trailers))
proxygen::MockHTTPTransaction::MOCK_METHOD1 (newPushedTransaction , HTTPTransaction * HTTPPushTransactionHandler *)
proxygen::MockHTTPTransaction::MOCK_METHOD1 (setReceiveWindow , void(uint32_t))
proxygen::MockHTTPTransaction::MOCK_METHOD1 (addWaitingForReplaySafety , void(folly::AsyncTransport::ReplaySafetyCallback *))
proxygen::MockHTTPTransaction::MOCK_METHOD1 (removeWaitingForReplaySafety , void(folly::AsyncTransport::ReplaySafetyCallback *))
void proxygen::MockHTTPTransaction::sendBody (std::unique_ptr< folly::IOBuf > body) [inline], [override], [virtual], [noexcept]
Send part or all of the egress message body to the Transport. If flow control is enabled, the chunk boundaries may not be respected. This method does not actually write the message out on the wire immediately. All writes happen at the end of the event loop at the earliest. Note: This method may be called zero or more times per message.
Parameters
body Message body data; the Transport will take care of applying any necessary protocol framing, such as chunk headers.
Reimplemented from proxygen::HTTPTransaction .
Definition at line 239 of file HTTPTransactionMocks.h.
References proxygen::HTTPTransaction::Transport::addWaitingForReplaySafety(), proxygen::MockHTTPTransactionTransport::MOCK_CONST_METHOD0(), proxygen::MockHTTPTransactionTransport::MOCK_METHOD0(), proxygen::MockHTTPTransactionTransport::MOCK_METHOD1(), proxygen::HTTPTransaction::Transport::newPushedTransaction(), proxygen::HTTPTransaction::Transport::pauseIngress(), proxygen::HTTPTransaction::Transport::removeWaitingForReplaySafety(), proxygen::HTTPTransaction::Transport::resumeIngress(), proxygen::HTTPTransaction::Transport::sendAbort(), proxygen::MockHTTPTransactionTransport::sendBody(), proxygen::HTTPTransaction::Transport::sendChunkHeader(), proxygen::HTTPTransaction::Transport::sendChunkTerminator(), and proxygen::HTTPTransaction::Transport::sendEOM().
                                                                 {
    sendBody(std::shared_ptr<folly::IOBuf>(iob.release()));
  }
void proxygen::MockHTTPTransaction::setHandlerUnmocked (HTTPTransactionHandler * handler) [inline]
Definition at line 231 of file HTTPTransactionMocks.h.
References proxygen::MockHTTPTransactionTransport::MOCK_CONST_METHOD0(), proxygen::MockHTTPTransactionTransport::MOCK_METHOD1(), proxygen::MockHTTPTransactionTransport::sendBody(), proxygen::HTTPTransaction::Transport::sendHeaders(), and proxygen::HTTPTransaction::setHandler().
                                                           {
    HTTPTransaction::setHandler(handler);
  }
Member Data Documentation
const folly::SocketAddress proxygen::MockHTTPTransaction::defaultAddress_
Definition at line 267 of file HTTPTransactionMocks.h.
MockHTTPCodec proxygen::MockHTTPTransaction::mockCodec_
Definition at line 268 of file HTTPTransactionMocks.h.
testing::NiceMock<MockHTTPTransactionTransport> proxygen::MockHTTPTransaction::mockTransport_
Definition at line 266 of file HTTPTransactionMocks.h.
wangle::TransportInfo proxygen::MockHTTPTransaction::setupTransportInfo_
Definition at line 269 of file HTTPTransactionMocks.h.
The documentation for this class was generated from the following file:
proxygen/lib/http/session/test/HTTPTransactionMocks.h