proxygen::HTTPDirectResponseHandler Class Reference
#include <HTTPDirectResponseHandler.h>
Public Member Functions
HTTPDirectResponseHandler (unsigned statusCode, const std::string &statusMsg, const HTTPErrorPage *errorPage=nullptr)
void forceConnectionClose (bool close)
void setTransaction (HTTPTransaction *txn) noexceptoverride
void detachTransaction () noexceptoverride
void onHeadersComplete (std::unique_ptr< HTTPMessage > msg) noexceptoverride
void onBody (std::unique_ptr< folly::IOBuf > chain) noexceptoverride
void onTrailers (std::unique_ptr< HTTPHeaders > trailers) noexceptoverride
void onEOM () noexceptoverride
void onUpgrade (UpgradeProtocol protocol) noexceptoverride
void onError (const HTTPException &error) noexceptoverride
void onEgressPaused () noexceptoverride
void onEgressResumed () noexceptoverride
Private Member Functions
~HTTPDirectResponseHandler () override
Private Attributes
HTTPTransaction * txn_
const HTTPErrorPage * errorPage_
std::string statusMessage_
unsigned statusCode_
bool headersSent_:1
bool eomSent_:1
bool forceConnectionClose_:1
Detailed Description
Definition at line 18 of file HTTPDirectResponseHandler.h.
Constructor & Destructor Documentation
proxygen::HTTPDirectResponseHandler::HTTPDirectResponseHandler (unsigned statusCode, const std::string & statusMsg, const HTTPErrorPage * errorPage = nullptr)
Definition at line 21 of file HTTPDirectResponseHandler.cpp.
                                   :
  txn_(nullptr),
  errorPage_(errorPage),
  statusMessage_(statusMsg),
  statusCode_(statusCode),
  headersSent_(false),
  eomSent_(false),
  forceConnectionClose_(true) {
}
proxygen::HTTPDirectResponseHandler::~HTTPDirectResponseHandler () [override], [private]
Definition at line 33 of file HTTPDirectResponseHandler.cpp.
Referenced by onEgressResumed().
                                                      {
}
Member Function Documentation
void proxygen::HTTPDirectResponseHandler::detachTransaction () [override], [virtual], [noexcept]
Called once after a transaction successfully completes. It will be called even if a read or write error happened earlier. This is a terminal callback, which means that the HTTPTransaction object that gives this call will be invalid after this function completes.
Implements proxygen::HTTPTransactionHandler .
Definition at line 42 of file HTTPDirectResponseHandler.cpp.
Referenced by forceConnectionClose().
                                                      {
  delete this;
}
void proxygen::HTTPDirectResponseHandler::forceConnectionClose (bool close) [inline]
Definition at line 24 of file HTTPDirectResponseHandler.h.
References detachTransaction(), forceConnectionClose_, onBody(), onEOM(), onError(), onHeadersComplete(), onTrailers(), onUpgrade(), and setTransaction().
                                        {
    forceConnectionClose_ = close;
  }
void proxygen::HTTPDirectResponseHandler::onBody (std::unique_ptr< folly::IOBuf > chain) [override], [virtual], [noexcept]
Can be called multiple times per transaction. If you had previously called pauseIngress(), this callback will be delayed until you call resumeIngress().
Implements proxygen::HTTPTransactionHandler .
Definition at line 77 of file HTTPDirectResponseHandler.cpp.
Referenced by forceConnectionClose().
                                                                   {
  VLOG(4) << "discarding request body";
}
void proxygen::HTTPDirectResponseHandler::onEgressPaused () [inline], [override], [virtual], [noexcept]
If the remote side's receive buffer fills up, this callback will be invoked so you can attempt to stop sending to the remote side.
Implements proxygen::HTTPTransactionHandler .
Definition at line 37 of file HTTPDirectResponseHandler.h.
{};
void proxygen::HTTPDirectResponseHandler::onEgressResumed () [inline], [override], [virtual], [noexcept]
This callback lets you know that the remote side has resumed reading and you can now continue to send data.
Implements proxygen::HTTPTransactionHandler .
Definition at line 38 of file HTTPDirectResponseHandler.h.
References ~HTTPDirectResponseHandler().
{};
void proxygen::HTTPDirectResponseHandler::onEOM () [override], [virtual], [noexcept]
Can be called once per transaction. If you had previously called pauseIngress(), this callback will be delayed until you call resumeIngress(). After this callback is received, there will be no more normal ingress callbacks received (onEgress*() and onError() may still be invoked). The Handler should consider ingress complete after receiving this message. This Transaction is still valid, and work may still occur on it until detachTransaction is called.
Implements proxygen::HTTPTransactionHandler .
Definition at line 87 of file HTTPDirectResponseHandler.cpp.
References eomSent_, proxygen::HTTPTransaction::sendEOM(), and txn_.
Referenced by forceConnectionClose(), and onError().
                                          {
  eomSent_ = true;
  txn_->sendEOM();
}
void proxygen::HTTPDirectResponseHandler::onError (const HTTPException & error) [override], [virtual], [noexcept]
Can be called at any time before detachTransaction(). This callback implies that an error has occurred. To determine if ingress or egress is affected, check the direciont on the HTTPException. If the direction is INGRESS, it MAY still be possible to send egress.
Implements proxygen::HTTPTransactionHandler .
Definition at line 95 of file HTTPDirectResponseHandler.cpp.
References eomSent_, headersSent_, proxygen::HTTPException::INGRESS, proxygen::kErrorTimeout, onEOM(), and onHeadersComplete().
Referenced by forceConnectionClose().
                                                                           {
  if (error.getDirection() == HTTPException::Direction::INGRESS) {
    if (error.getProxygenError() == kErrorTimeout) {
      VLOG(4) << "processing ingress timeout";
      if (!headersSent_) {
        onHeadersComplete(nullptr);
      }
      if (!eomSent_) {
        onEOM();
      }
    } else {
      VLOG(4) << "processing ingress error";
      if (!headersSent_) {
        onHeadersComplete(nullptr);
      }
      if (!eomSent_) {
        onEOM();
      }
    }
  }
}
void proxygen::HTTPDirectResponseHandler::onHeadersComplete (std::unique_ptr< HTTPMessage > msg) [override], [virtual], [noexcept]
Called at most once per transaction. This is usually the first ingress callback. It is possible to get a read error before this however. If you had previously called pauseIngress(), this callback will be delayed until you call resumeIngress().
Implements proxygen::HTTPTransactionHandler .
Definition at line 46 of file HTTPDirectResponseHandler.cpp.
References proxygen::HTTPHeaders::add(), proxygen::HTTPErrorPage::Page::content, proxygen::HTTPErrorPage::Page::contentType, proxygen::empty_string, errorPage_, forceConnectionClose_, proxygen::HTTPErrorPage::generate(), proxygen::HTTPMessage::getDefaultReason(), proxygen::HTTPMessage::getHeaders(), headersSent_, proxygen::HTTPTransaction::sendBody(), proxygen::HTTPTransaction::sendHeaders(), proxygen::HTTPMessage::setHTTPVersion(), proxygen::HTTPMessage::setStatusCode(), proxygen::HTTPMessage::setStatusMessage(), statusCode_, statusMessage_, and txn_.
Referenced by forceConnectionClose(), and onError().
                                           {
  VLOG(4) << "processing request";
  headersSent_ = true;
  HTTPMessage response;
  std::unique_ptr<folly::IOBuf> responseBody;
  response.setHTTPVersion(1, 1);
  response.setStatusCode(statusCode_);
  if (!statusMessage_.empty()) {
    response.setStatusMessage(statusMessage_);
  } else {
    response.setStatusMessage(HTTPMessage::getDefaultReason(statusCode_));
  }
  if (forceConnectionClose_) {
    response.getHeaders().add(HTTP_HEADER_CONNECTION, "close");
  }
  if (errorPage_) {
    HTTPErrorPage::Page page = errorPage_->generate(0, statusCode_,
        statusMessage_, nullptr, empty_string);
    VLOG(4) << "sending error page with type " << page.contentType;
    response.getHeaders().add(HTTP_HEADER_CONTENT_TYPE, page.contentType);
    responseBody = std::move(page.content);
  }
  response.getHeaders().add(HTTP_HEADER_CONTENT_LENGTH, folly::to<string>(
    responseBody ? responseBody->computeChainDataLength() : 0));
  txn_->sendHeaders(response);
  if (responseBody) {
    txn_->sendBody(std::move(responseBody));
  }
}
void proxygen::HTTPDirectResponseHandler::onTrailers (std::unique_ptr< HTTPHeaders > trailers) [override], [virtual], [noexcept]
Can be called any number of times per transaction. If you had previously called pauseIngress(), this callback will be delayed until you call resumeIngress(). Trailers can be received once right before the EOM of a chunked HTTP/1.1 reponse or multiple times per transaction from SPDY and HTTP/2.0 HEADERS frames.
Implements proxygen::HTTPTransactionHandler .
Definition at line 81 of file HTTPDirectResponseHandler.cpp.
Referenced by forceConnectionClose().
                                        {
  VLOG(4) << "discarding request trailers";
}
void proxygen::HTTPDirectResponseHandler::onUpgrade (UpgradeProtocol protocol) [override], [virtual], [noexcept]
Can be called once per transaction. If you had previously called pauseIngress(), this callback will be delayed until you call resumeIngress(). After this callback is invoked, further data will be forwarded using the onBody() callback. Once the data transfer is completed (EOF recevied in case of CONNECT), onEOM() callback will be invoked.
Implements proxygen::HTTPTransactionHandler .
Definition at line 92 of file HTTPDirectResponseHandler.cpp.
Referenced by forceConnectionClose().
                                {}
void proxygen::HTTPDirectResponseHandler::setTransaction (HTTPTransaction * txn) [override], [virtual], [noexcept]
Called once per transaction. This notifies the handler of which transaction it should talk to and will receive callbacks from.
Implements proxygen::HTTPTransactionHandler .
Definition at line 37 of file HTTPDirectResponseHandler.cpp.
References txn_.
Referenced by forceConnectionClose().
                                                                       {
  txn_ = txn;
}
Member Data Documentation
bool proxygen::HTTPDirectResponseHandler::eomSent_ [private]
Definition at line 48 of file HTTPDirectResponseHandler.h.
Referenced by onEOM(), and onError().
const HTTPErrorPage* proxygen::HTTPDirectResponseHandler::errorPage_ [private]
Definition at line 44 of file HTTPDirectResponseHandler.h.
Referenced by onHeadersComplete().
bool proxygen::HTTPDirectResponseHandler::forceConnectionClose_ [private]
Definition at line 49 of file HTTPDirectResponseHandler.h.
Referenced by forceConnectionClose(), and onHeadersComplete().
bool proxygen::HTTPDirectResponseHandler::headersSent_ [private]
Definition at line 47 of file HTTPDirectResponseHandler.h.
Referenced by onError(), and onHeadersComplete().
unsigned proxygen::HTTPDirectResponseHandler::statusCode_ [private]
Definition at line 46 of file HTTPDirectResponseHandler.h.
Referenced by onHeadersComplete().
std::string proxygen::HTTPDirectResponseHandler::statusMessage_ [private]
Definition at line 45 of file HTTPDirectResponseHandler.h.
Referenced by onHeadersComplete().
HTTPTransaction* proxygen::HTTPDirectResponseHandler::txn_ [private]
Definition at line 43 of file HTTPDirectResponseHandler.h.
Referenced by onEOM(), onHeadersComplete(), and setTransaction().
The documentation for this class was generated from the following files:
proxygen/lib/http/session/HTTPDirectResponseHandler.h
proxygen/lib/http/session/HTTPDirectResponseHandler.cpp