proxygen::PassThroughHTTPCodecFilter Class Reference
#include <HTTPCodecFilter.h>
Public Member Functions
PassThroughHTTPCodecFilter (bool calls=true, bool callbacks=true)
void onMessageBegin (StreamID stream, HTTPMessage *msg) override
void onPushMessageBegin (StreamID stream, StreamID assocStream, HTTPMessage *msg) override
void onExMessageBegin (StreamID stream, StreamID controlStream, bool unidirectional, HTTPMessage *msg) override
void onHeadersComplete (StreamID stream, std::unique_ptr< HTTPMessage > msg) override
void onBody (StreamID stream, std::unique_ptr< folly::IOBuf > chain, uint16_t padding) override
void onChunkHeader (StreamID stream, size_t length) override
void onChunkComplete (StreamID stream) override
void onTrailersComplete (StreamID stream, std::unique_ptr< HTTPHeaders > trailers) override
void onMessageComplete (StreamID stream, bool upgrade) override
void onFrameHeader (StreamID stream_id, uint8_t flags, uint64_t length, uint8_t type, uint16_t version=0) override
void onError (StreamID stream, const HTTPException &error, bool newStream=false) override
void onAbort (StreamID stream, ErrorCode code) override
void onGoaway (uint64_t lastGoodStreamID, ErrorCode code, std::unique_ptr< folly::IOBuf > debugData=nullptr) override
void onPingRequest (uint64_t uniqueID) override
void onPingReply (uint64_t uniqueID) override
void onWindowUpdate (StreamID stream, uint32_t amount) override
void onSettings (const SettingsList &settings) override
void onSettingsAck () override
void onPriority (StreamID stream, const HTTPMessage::HTTPPriority &pri) override
bool onNativeProtocolUpgrade (StreamID stream, CodecProtocol protocol, const std::string &protocolString, HTTPMessage &msg) override
void onGenerateFrameHeader (StreamID streamID, uint8_t type, uint64_t length, uint16_t version) override
void onCertificateRequest (uint16_t requestId, std::unique_ptr< folly::IOBuf > authRequest) override
void onCertificate (uint16_t certId, std::unique_ptr< folly::IOBuf > authenticator) override
uint32_t numOutgoingStreams () const override
uint32_t numIncomingStreams () const override
CompressionInfo getCompressionInfo () const override
CodecProtocol getProtocol () const override
const std::string & getUserAgent () const override
TransportDirection getTransportDirection () const override
bool supportsStreamFlowControl () const override
bool supportsSessionFlowControl () const override
StreamID createStream () override
void setCallback (HTTPCodec::Callback *callback) override
bool isBusy () const override
void setParserPaused (bool paused) override
size_t onIngress (const folly::IOBuf &buf) override
void onIngressEOF () override
bool onIngressUpgradeMessage (const HTTPMessage &msg) override
bool isReusable () const override
bool isWaitingToDrain () const override
bool closeOnEgressComplete () const override
bool supportsParallelRequests () const override
bool supportsPushTransactions () const override
size_t generateConnectionPreface (folly::IOBufQueue &writeBuf) override
void generateHeader (folly::IOBufQueue &writeBuf, StreamID stream, const HTTPMessage &msg, bool eom, HTTPHeaderSize *size) override
void generatePushPromise (folly::IOBufQueue &writeBuf, StreamID stream, const HTTPMessage &msg, StreamID assocStream, bool eom, HTTPHeaderSize *size) override
void generateExHeader (folly::IOBufQueue &writeBuf, StreamID stream, const HTTPMessage &msg, const HTTPCodec::ExAttributes &exAttributes, bool eom, HTTPHeaderSize *size) override
size_t generateBody (folly::IOBufQueue &writeBuf, StreamID stream, std::unique_ptr< folly::IOBuf > chain, folly::Optional< uint8_t > padding, bool eom) override
size_t generateChunkHeader (folly::IOBufQueue &writeBuf, StreamID stream, size_t length) override
size_t generateChunkTerminator (folly::IOBufQueue &writeBuf, StreamID stream) override
size_t generateTrailers (folly::IOBufQueue &writeBuf, StreamID stream, const HTTPHeaders &trailers) override
size_t generateEOM (folly::IOBufQueue &writeBuf, StreamID stream) override
size_t generateRstStream (folly::IOBufQueue &writeBuf, StreamID stream, ErrorCode statusCode) override
size_t generateGoaway (folly::IOBufQueue &writeBuf, StreamID lastStream, ErrorCode statusCode, std::unique_ptr< folly::IOBuf > debugData=nullptr) override
size_t generatePingRequest (folly::IOBufQueue &writeBuf) override
size_t generatePingReply (folly::IOBufQueue &writeBuf, uint64_t uniqueID) override
size_t generateSettings (folly::IOBufQueue &writeBuf) override
size_t generateSettingsAck (folly::IOBufQueue &writeBuf) override
size_t generateWindowUpdate (folly::IOBufQueue &writeBuf, StreamID stream, uint32_t delta) override
size_t generatePriority (folly::IOBufQueue &writeBuf, StreamID stream, const HTTPMessage::HTTPPriority &pri) override
size_t generateCertificateRequest (folly::IOBufQueue &writeBuf, uint16_t requestId, std::unique_ptr< folly::IOBuf > chain) override
size_t generateCertificate (folly::IOBufQueue &writeBuf, uint16_t certId, std::unique_ptr< folly::IOBuf > certData) override
HTTPSettings * getEgressSettings () override
const HTTPSettings * getIngressSettings () const override
void setHeaderCodecStats (HeaderCodec::Stats *stats) override
void enableDoubleGoawayDrain () override
HTTPCodec::StreamID getLastIncomingStreamID () const override
uint32_t getDefaultWindowSize () const override
size_t addPriorityNodes (PriorityQueue &queue, folly::IOBufQueue &writeBuf, uint8_t maxLevel) override
StreamID mapPriorityToDependency (uint8_t priority) const override
int8_t mapDependencyToPriority (StreamID parent) const override
Additional Inherited Members
Detailed Description
An implementation of HTTPCodecFilter that passes through all calls. This is useful to subclass if you aren't interested in intercepting every function. See HTTPCodec.h for documentation on these methods.
Definition at line 28 of file HTTPCodecFilter.h.
Constructor & Destructor Documentation
proxygen::PassThroughHTTPCodecFilter::PassThroughHTTPCodecFilter (bool calls = true, bool callbacks = true) [inline], [explicit]
By default, the filter gets both calls and callbacks
Definition at line 33 of file HTTPCodecFilter.h.
References addPriorityNodes(), closeOnEgressComplete(), createStream(), enableDoubleGoawayDrain(), generateBody(), generateCertificate(), generateCertificateRequest(), generateChunkHeader(), generateChunkTerminator(), generateConnectionPreface(), generateEOM(), generateExHeader(), generateGoaway(), generateHeader(), generatePingReply(), generatePingRequest(), generatePriority(), generatePushPromise(), generateRstStream(), generateSettings(), generateSettingsAck(), generateTrailers(), generateWindowUpdate(), getCompressionInfo(), getDefaultWindowSize(), getEgressSettings(), getIngressSettings(), getLastIncomingStreamID(), getProtocol(), getTransportDirection(), getUserAgent(), isBusy(), isReusable(), isWaitingToDrain(), mapDependencyToPriority(), mapPriorityToDependency(), numIncomingStreams(), numOutgoingStreams(), onAbort(), onBody(), onCertificate(), onCertificateRequest(), onChunkComplete(), onChunkHeader(), onError(), onExMessageBegin(), onFrameHeader(), onGenerateFrameHeader(), onGoaway(), onHeadersComplete(), onIngress(), onIngressEOF(), onIngressUpgradeMessage(), onMessageBegin(), onMessageComplete(), onNativeProtocolUpgrade(), onPingReply(), onPingRequest(), onPriority(), onPushMessageBegin(), onSettings(), onSettingsAck(), onTrailersComplete(), onWindowUpdate(), setCallback(), proxygen::HTTPCodec::setCallback(), setHeaderCodecStats(), setParserPaused(), settings, statusCode, streamID, supportsParallelRequests(), supportsPushTransactions(), supportsSessionFlowControl(), and supportsStreamFlowControl().
                                                            :
      HTTPCodecFilter(calls, callbacks) {}
Member Function Documentation
size_t proxygen::PassThroughHTTPCodecFilter::addPriorityNodes (PriorityQueue & queue, folly::IOBufQueue & writeBuf, uint8_t maxLevel) [override]
Definition at line 386 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                      {
  return call_->addPriorityNodes(queue, writeBuf, maxLevel);
}
bool proxygen::PassThroughHTTPCodecFilter::closeOnEgressComplete () const [override]
Definition at line 214 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                             {
  return call_->closeOnEgressComplete();
}
HTTPCodec::StreamID proxygen::PassThroughHTTPCodecFilter::createStream () [override]
Definition at line 177 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                           {
  return call_->createStream();
}
void proxygen::PassThroughHTTPCodecFilter::enableDoubleGoawayDrain () [override]
Definition at line 367 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                         {
  return call_->enableDoubleGoawayDrain();
}
size_t proxygen::PassThroughHTTPCodecFilter::generateBody (folly::IOBufQueue & writeBuf, StreamID stream, std::unique_ptr< folly::IOBuf > chain, folly::Optional< uint8_t > padding, bool eom) [override]
Definition at line 260 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
              {
  return call_->generateBody(writeBuf, stream, std::move(chain), padding,
                             eom);
}
size_t proxygen::PassThroughHTTPCodecFilter::generateCertificate (folly::IOBufQueue & writeBuf, uint16_t certId, std::unique_ptr< folly::IOBuf > certData) [override]
Definition at line 352 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                        {
  return call_->generateCertificate(writeBuf, certId, std::move(certData));
}
size_t proxygen::PassThroughHTTPCodecFilter::generateCertificateRequest (folly::IOBufQueue & writeBuf, uint16_t requestId, std::unique_ptr< folly::IOBuf > chain) [override]
Definition at line 344 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                     {
  return call_->generateCertificateRequest(
      writeBuf, requestId, std::move(chain));
}
size_t proxygen::PassThroughHTTPCodecFilter::generateChunkHeader (folly::IOBufQueue & writeBuf, StreamID stream, size_t length) [override]
Definition at line 270 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                   {
  return call_->generateChunkHeader(writeBuf, stream, length);
}
size_t proxygen::PassThroughHTTPCodecFilter::generateChunkTerminator (folly::IOBufQueue & writeBuf, StreamID stream) [override]
Definition at line 277 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                     {
  return call_->generateChunkTerminator(writeBuf, stream);
}
size_t proxygen::PassThroughHTTPCodecFilter::generateConnectionPreface (folly::IOBufQueue & writeBuf) [override]
Definition at line 226 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                             {
  return call_->generateConnectionPreface(writeBuf);
}
size_t proxygen::PassThroughHTTPCodecFilter::generateEOM (folly::IOBufQueue & writeBuf, StreamID stream) [override]
Definition at line 290 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                {
  return call_->generateEOM(writeBuf, stream);
}
void proxygen::PassThroughHTTPCodecFilter::generateExHeader (folly::IOBufQueue & writeBuf, StreamID stream, const HTTPMessage & msg, const HTTPCodec::ExAttributes & exAttributes, bool eom, HTTPHeaderSize * size) [override]
Definition at line 249 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                        {
  return call_->generateExHeader(writeBuf, stream, msg, exAttributes,
                                 eom, size);
}
size_t proxygen::PassThroughHTTPCodecFilter::generateGoaway (folly::IOBufQueue & writeBuf, StreamID lastStream, ErrorCode statusCode, std::unique_ptr< folly::IOBuf > debugData = nullptr) [override]
Definition at line 302 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                         {
  return call_->generateGoaway(writeBuf, lastStream, statusCode,
                               std::move(debugData));
}
void proxygen::PassThroughHTTPCodecFilter::generateHeader (folly::IOBufQueue & writeBuf, StreamID stream, const HTTPMessage & msg, bool eom, HTTPHeaderSize * size) [override]
Definition at line 232 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                      {
  return call_->generateHeader(writeBuf, stream, msg, eom, size);
}
size_t proxygen::PassThroughHTTPCodecFilter::generatePingReply (folly::IOBufQueue & writeBuf, uint64_t uniqueID) [override]
Definition at line 316 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                       {
  return call_->generatePingReply(writeBuf, uniqueID);
}
size_t proxygen::PassThroughHTTPCodecFilter::generatePingRequest (folly::IOBufQueue & writeBuf) [override]
Definition at line 311 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                               {
  return call_->generatePingRequest(writeBuf);
}
size_t proxygen::PassThroughHTTPCodecFilter::generatePriority (folly::IOBufQueue & writeBuf, StreamID stream, const HTTPMessage::HTTPPriority & pri) [override]
Definition at line 337 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                      {
  return call_->generatePriority(writeBuf, stream, pri);
}
void proxygen::PassThroughHTTPCodecFilter::generatePushPromise (folly::IOBufQueue & writeBuf, StreamID stream, const HTTPMessage & msg, StreamID assocStream, bool eom, HTTPHeaderSize * size) [override]
Definition at line 240 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                           {
  return call_->generatePushPromise(buf, stream, msg, assocStream, eom, size);
}
size_t proxygen::PassThroughHTTPCodecFilter::generateRstStream (folly::IOBufQueue & writeBuf, StreamID stream, ErrorCode statusCode) [override]
Definition at line 295 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                    {
  return call_->generateRstStream(writeBuf, stream, code);
}
size_t proxygen::PassThroughHTTPCodecFilter::generateSettings (folly::IOBufQueue & writeBuf) [override]
Definition at line 322 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                        {
  return call_->generateSettings(buf);
}
size_t proxygen::PassThroughHTTPCodecFilter::generateSettingsAck (folly::IOBufQueue & writeBuf) [override]
Definition at line 326 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                           {
  return call_->generateSettingsAck(buf);
}
size_t proxygen::PassThroughHTTPCodecFilter::generateTrailers (folly::IOBufQueue & writeBuf, StreamID stream, const HTTPHeaders & trailers) [override]
Definition at line 283 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                 {
  return call_->generateTrailers(writeBuf, stream, trailers);
}
size_t proxygen::PassThroughHTTPCodecFilter::generateWindowUpdate (folly::IOBufQueue & writeBuf, StreamID stream, uint32_t delta) [override]
Definition at line 330 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                  {
  return call_->generateWindowUpdate(buf, stream, delta);
}
CompressionInfo proxygen::PassThroughHTTPCodecFilter::getCompressionInfo () const [override]
Definition at line 153 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                     {
  return call_->getCompressionInfo();
}
uint32_t proxygen::PassThroughHTTPCodecFilter::getDefaultWindowSize () const [override]
Definition at line 381 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by proxygen::FlowControlFilter::FlowControlFilter(), and PassThroughHTTPCodecFilter().
                                                                {
  return call_->getDefaultWindowSize();
}
HTTPSettings * proxygen::PassThroughHTTPCodecFilter::getEgressSettings () [override]
Definition at line 359 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                            {
  return call_->getEgressSettings();
}
const HTTPSettings * proxygen::PassThroughHTTPCodecFilter::getIngressSettings () const [override]
Definition at line 363 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                         {
  return call_->getIngressSettings();
}
HTTPCodec::StreamID proxygen::PassThroughHTTPCodecFilter::getLastIncomingStreamID () const [override]
Definition at line 377 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                          {
  return call_->getLastIncomingStreamID();
}
CodecProtocol proxygen::PassThroughHTTPCodecFilter::getProtocol () const [override]
Definition at line 157 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                            {
  return call_->getProtocol();
}
TransportDirection proxygen::PassThroughHTTPCodecFilter::getTransportDirection () const [override]
Definition at line 165 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                           {
  return call_->getTransportDirection();
}
const std::string & proxygen::PassThroughHTTPCodecFilter::getUserAgent () const [override]
Definition at line 161 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                {
  return call_->getUserAgent();
}
bool proxygen::PassThroughHTTPCodecFilter::isBusy () const [override]
Definition at line 185 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                              {
  return call_->isBusy();
}
bool proxygen::PassThroughHTTPCodecFilter::isReusable () const [override]
Definition at line 206 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                  {
  return call_->isReusable();
}
bool proxygen::PassThroughHTTPCodecFilter::isWaitingToDrain () const [override]
Definition at line 210 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                        {
  return call_->isWaitingToDrain();
}
int8_t proxygen::PassThroughHTTPCodecFilter::mapDependencyToPriority (StreamID parent) const [override]
Definition at line 399 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                         {
  return call_->mapDependencyToPriority(parent);
}
HTTPCodec::StreamID proxygen::PassThroughHTTPCodecFilter::mapPriorityToDependency (uint8_t priority) const [override]
Definition at line 394 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                          {
  return call_->mapPriorityToDependency(priority);
}
uint32_t proxygen::PassThroughHTTPCodecFilter::numIncomingStreams () const [override]
Definition at line 148 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                              {
  return callback_->numIncomingStreams();
}
uint32_t proxygen::PassThroughHTTPCodecFilter::numOutgoingStreams () const [override]
Definition at line 144 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                              {
  return callback_->numOutgoingStreams();
}
void proxygen::PassThroughHTTPCodecFilter::onAbort (StreamID stream, ErrorCode code) [override]
Definition at line 81 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                         {
  callback_->onAbort(stream, code);
}
void proxygen::PassThroughHTTPCodecFilter::onBody (StreamID stream, std::unique_ptr< folly::IOBuf > chain, uint16_t padding) [override]
Definition at line 39 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                          {
  callback_->onBody(stream, std::move(chain), padding);
}
void proxygen::PassThroughHTTPCodecFilter::onCertificate (uint16_t certId, std::unique_ptr< folly::IOBuf > authenticator) [override]
Definition at line 139 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                              {
  callback_->onCertificate(certId, std::move(authenticator));
}
void proxygen::PassThroughHTTPCodecFilter::onCertificateRequest (uint16_t requestId, std::unique_ptr< folly::IOBuf > authRequest) [override]
Definition at line 134 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                               {
  callback_->onCertificateRequest(requestId, std::move(authRequest));
}
void proxygen::PassThroughHTTPCodecFilter::onChunkComplete (StreamID stream) [override]
Definition at line 50 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                                {
  callback_->onChunkComplete(stream);
}
void proxygen::PassThroughHTTPCodecFilter::onChunkHeader (StreamID stream, size_t length) [override]
Definition at line 45 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                              {
  callback_->onChunkHeader(stream, length);
}
void proxygen::PassThroughHTTPCodecFilter::onError (StreamID stream, const HTTPException & error, bool newStream = false) [override]
Definition at line 74 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                    {
  callback_->onError(stream, error, newStream);
}
void proxygen::PassThroughHTTPCodecFilter::onExMessageBegin (StreamID stream, StreamID controlStream, bool unidirectional, HTTPMessage * msg) [override]
Definition at line 26 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                                    {
  callback_->onExMessageBegin(stream, controlStream, unidirectional, msg);
}
void proxygen::PassThroughHTTPCodecFilter::onFrameHeader (StreamID stream_id, uint8_t flags, uint64_t length, uint8_t type, uint16_t version = 0) [override]
Definition at line 65 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                      {
  callback_->onFrameHeader(stream_id, flags, length, type, version);
}
void proxygen::PassThroughHTTPCodecFilter::onGenerateFrameHeader (StreamID streamID, uint8_t type, uint64_t length, uint16_t version) [override]
Definition at line 127 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                                         {
   callback_->onGenerateFrameHeader(streamID, length, type, version);
}
void proxygen::PassThroughHTTPCodecFilter::onGoaway (uint64_t lastGoodStreamID, ErrorCode code, std::unique_ptr< folly::IOBuf > debugData = nullptr) [override]
Definition at line 86 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                       {
  callback_->onGoaway(lastGoodStreamID, code, std::move(debugData));
}
void proxygen::PassThroughHTTPCodecFilter::onHeadersComplete (StreamID stream, std::unique_ptr< HTTPMessage > msg) [override]
Definition at line 33 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                    {
  callback_->onHeadersComplete(stream, std::move(msg));
}
size_t proxygen::PassThroughHTTPCodecFilter::onIngress (const folly::IOBuf & buf) [override]
Definition at line 193 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                  {
  return call_->onIngress(buf);
}
void proxygen::PassThroughHTTPCodecFilter::onIngressEOF () [override]
Definition at line 197 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                              {
  call_->onIngressEOF();
}
bool proxygen::PassThroughHTTPCodecFilter::onIngressUpgradeMessage (const HTTPMessage & msg) [override]
Definition at line 201 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                          {
  return call_->onIngressUpgradeMessage(msg);
}
void proxygen::PassThroughHTTPCodecFilter::onMessageBegin (StreamID stream, HTTPMessage * msg) [override]
Definition at line 15 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                                  {
  callback_->onMessageBegin(stream, msg);
}
void proxygen::PassThroughHTTPCodecFilter::onMessageComplete (StreamID stream, bool upgrade) [override]
Definition at line 60 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                                 {
  callback_->onMessageComplete(stream, upgrade);
}
bool proxygen::PassThroughHTTPCodecFilter::onNativeProtocolUpgrade (StreamID stream, CodecProtocol protocol, const std::string & protocolString, HTTPMessage & msg) [override]
Definition at line 120 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                    {
  return callback_->onNativeProtocolUpgrade(streamID, protocol, protocolString,
                                            msg);
}
void proxygen::PassThroughHTTPCodecFilter::onPingReply (uint64_t uniqueID) [override]
Definition at line 97 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                              {
  callback_->onPingReply(uniqueID);
}
void proxygen::PassThroughHTTPCodecFilter::onPingRequest (uint64_t uniqueID) [override]
Definition at line 93 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                                {
  callback_->onPingRequest(uniqueID);
}
void proxygen::PassThroughHTTPCodecFilter::onPriority (StreamID stream, const HTTPMessage::HTTPPriority & pri) [override]
Definition at line 114 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                      {
  callback_->onPriority(stream, pri);
}
void proxygen::PassThroughHTTPCodecFilter::onPushMessageBegin (StreamID stream, StreamID assocStream, HTTPMessage * msg) [override]
Definition at line 20 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                                      {
  callback_->onPushMessageBegin(stream, assocStream, msg);
}
void proxygen::PassThroughHTTPCodecFilter::onSettings (const SettingsList & settings) [override]
Definition at line 106 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                                        {
  callback_->onSettings(settings);
}
void proxygen::PassThroughHTTPCodecFilter::onSettingsAck () [override]
Definition at line 110 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                               {
  callback_->onSettingsAck();
}
void proxygen::PassThroughHTTPCodecFilter::onTrailersComplete (StreamID stream, std::unique_ptr< HTTPHeaders > trailers) [override]
Definition at line 54 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                         {
  callback_->onTrailersComplete(stream, std::move(trailers));
}
void proxygen::PassThroughHTTPCodecFilter::onWindowUpdate (StreamID stream, uint32_t amount) [override]
Definition at line 101 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
Referenced by PassThroughHTTPCodecFilter().
                                                                 {
  callback_->onWindowUpdate(stream, amount);
}
void proxygen::PassThroughHTTPCodecFilter::setCallback (HTTPCodec::Callback * callback) [override]
Definition at line 181 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::setCallbackInternal().
Referenced by PassThroughHTTPCodecFilter().
                                                                        {
  setCallbackInternal(callback);
}
void proxygen::PassThroughHTTPCodecFilter::setHeaderCodecStats (HeaderCodec::Stats * stats) [override]
Definition at line 371 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                             {
  call_->setHeaderCodecStats(stats);
}
void proxygen::PassThroughHTTPCodecFilter::setParserPaused (bool paused) [override]
Definition at line 189 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                            {
  call_->setParserPaused(paused);
}
bool proxygen::PassThroughHTTPCodecFilter::supportsParallelRequests () const [override]
Definition at line 218 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                {
  return call_->supportsParallelRequests();
}
bool proxygen::PassThroughHTTPCodecFilter::supportsPushTransactions () const [override]
Definition at line 222 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                {
  return call_->supportsPushTransactions();
}
bool proxygen::PassThroughHTTPCodecFilter::supportsSessionFlowControl () const [override]
Definition at line 173 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                  {
  return call_->supportsSessionFlowControl();
}
bool proxygen::PassThroughHTTPCodecFilter::supportsStreamFlowControl () const [override]
Definition at line 169 of file HTTPCodecFilter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_.
Referenced by PassThroughHTTPCodecFilter().
                                                                 {
  return call_->supportsStreamFlowControl();
}
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/HTTPCodecFilter.h
proxygen/lib/http/codec/HTTPCodecFilter.cpp