proxygen::ResponseHandler Class Reference
#include <ResponseHandler.h>
Public Member Functions
ResponseHandler (RequestHandler *upstream)
virtual ~ResponseHandler ()
virtual void sendHeaders (HTTPMessage &msg) noexcept=0
virtual void sendChunkHeader (size_t len) noexcept=0
virtual void sendBody (std::unique_ptr< folly::IOBuf > body) noexcept=0
virtual void sendChunkTerminator () noexcept=0
virtual void sendEOM () noexcept=0
virtual void sendAbort () noexcept=0
virtual void refreshTimeout () noexcept=0
virtual void pauseIngress () noexcept=0
virtual void resumeIngress () noexcept=0
virtual ResponseHandler * newPushedResponse (PushHandler *pushHandler) noexcept=0
virtual ResponseHandler * newExMessage (ExMessageHandler *, bool=false) noexcept
virtual const wangle::TransportInfo & getSetupTransportInfo () const noexcept=0
virtual void getCurrentTransportInfo (wangle::TransportInfo *tinfo) const =0
HTTPTransaction * getTransaction () const noexcept
Protected Attributes
RequestHandler * upstream_ {nullptr}
HTTPTransaction * txn_ {nullptr}
Detailed Description
Interface that acts as client for RequestHandler. It also has a hook for the RequestHandler so that it is easy to chain these Request/Response handlers and be able to modify these chains.
The names are pretty much self explanatory. You only need to get into details about this interface if you are implementing filters.
NOTE: All the writes are done at the end of the event loop. So this is safe to do in your RequestHandler.
{ ... downstream_->sendHeader(...); downstream_->sendEOM(); }
You dont need to worry about any callbacks being invoked after sendHeader.
Consider using proxygen/httpserver/ResponseBuilder to send back the response. It will take care of chunking response if required and everything.
Definition at line 44 of file ResponseHandler.h.
Constructor & Destructor Documentation
proxygen::ResponseHandler::ResponseHandler (RequestHandler * upstream) [inline], [explicit]
Definition at line 46 of file ResponseHandler.h.
      : upstream_(CHECK_NOTNULL(upstream)) {
  }
virtual proxygen::ResponseHandler::~ResponseHandler () [inline], [virtual]
Definition at line 50 of file ResponseHandler.h.
References newPushedResponse(), pauseIngress(), refreshTimeout(), resumeIngress(), sendAbort(), sendBody(), sendChunkHeader(), sendChunkTerminator(), sendEOM(), and sendHeaders().
{}
Member Function Documentation
virtual void proxygen::ResponseHandler::getCurrentTransportInfo (wangle::TransportInfo * tinfo) const [pure virtual]
Implemented in proxygen::Filter , and proxygen::RequestHandlerAdaptor .
Referenced by proxygen::Filter::getCurrentTransportInfo(), proxygen::MockResponseHandler::MockResponseHandler(), and newExMessage().
virtual const wangle::TransportInfo& proxygen::ResponseHandler::getSetupTransportInfo () const [pure virtual], [noexcept]
Implemented in proxygen::Filter , proxygen::RequestHandlerAdaptor , and proxygen::MockResponseHandler .
Referenced by proxygen::Filter::getSetupTransportInfo(), and newExMessage().
HTTPTransaction* proxygen::ResponseHandler::getTransaction () const [inline], [noexcept]
Definition at line 92 of file ResponseHandler.h.
References txn_.
Referenced by proxygen::RequestHandlerAdaptor::newExMessage(), and proxygen::ResponseBuilder::send().
                                                   {
    return txn_;
  }
virtual ResponseHandler* proxygen::ResponseHandler::newExMessage (ExMessageHandler * , bool = false) [inline], [virtual], [noexcept]
Reimplemented in proxygen::RequestHandlerAdaptor .
Definition at line 80 of file ResponseHandler.h.
References getCurrentTransportInfo(), and getSetupTransportInfo().
               {
    LOG(FATAL) << "newExMessage not supported";
  }
virtual ResponseHandler* proxygen::ResponseHandler::newPushedResponse (PushHandler * pushHandler) [pure virtual], [noexcept]
Implemented in proxygen::Filter , and proxygen::RequestHandlerAdaptor .
Referenced by proxygen::MockResponseHandler::MockResponseHandler(), proxygen::Filter::newPushedResponse(), PushService::PushRequestHandler::onRequest(), and ~ResponseHandler().
virtual void proxygen::ResponseHandler::pauseIngress () [pure virtual], [noexcept]
Implemented in proxygen::Filter , and proxygen::RequestHandlerAdaptor .
Referenced by proxygen::MockResponseHandler::MockResponseHandler(), ProxyService::ProxyHandler::onRequest(), ProxyService::ProxyHandler::onServerEgressPaused(), proxygen::Filter::pauseIngress(), and ~ResponseHandler().
virtual void proxygen::ResponseHandler::refreshTimeout () [pure virtual], [noexcept]
Implemented in proxygen::Filter , proxygen::RejectConnectFilter , and proxygen::RequestHandlerAdaptor .
Referenced by proxygen::MockResponseHandler::MockResponseHandler(), proxygen::Filter::refreshTimeout(), and ~ResponseHandler().
virtual void proxygen::ResponseHandler::resumeIngress () [pure virtual], [noexcept]
Implemented in proxygen::Filter , and proxygen::RequestHandlerAdaptor .
Referenced by ProxyService::ProxyHandler::connectSuccess(), proxygen::MockResponseHandler::MockResponseHandler(), ProxyService::ProxyHandler::onServerEgressResumed(), proxygen::Filter::resumeIngress(), and ~ResponseHandler().
virtual void proxygen::ResponseHandler::sendAbort () [pure virtual], [noexcept]
Implemented in proxygen::Filter , proxygen::RejectConnectFilter , and proxygen::RequestHandlerAdaptor .
Referenced by ProxyService::ProxyHandler::abortDownstream(), proxygen::MockResponseHandler::MockResponseHandler(), proxygen::Filter::sendAbort(), and ~ResponseHandler().
virtual void proxygen::ResponseHandler::sendBody (std::unique_ptr< folly::IOBuf > body) [pure virtual], [noexcept]
Implemented in proxygen::Filter , proxygen::ZlibServerFilter , proxygen::RejectConnectFilter , proxygen::RequestHandlerAdaptor , and proxygen::MockResponseHandler .
Referenced by ProxyService::ProxyHandler::onServerBody(), ProxyService::ProxyHandler::readDataAvailable(), proxygen::ResponseBuilder::send(), proxygen::Filter::sendBody(), and ~ResponseHandler().
virtual void proxygen::ResponseHandler::sendChunkHeader (size_t len) [pure virtual], [noexcept]
Implemented in proxygen::Filter , proxygen::ZlibServerFilter , proxygen::RejectConnectFilter , and proxygen::RequestHandlerAdaptor .
Referenced by proxygen::MockResponseHandler::MockResponseHandler(), proxygen::ResponseBuilder::send(), proxygen::Filter::sendChunkHeader(), and ~ResponseHandler().
virtual void proxygen::ResponseHandler::sendChunkTerminator () [pure virtual], [noexcept]
Implemented in proxygen::Filter , proxygen::RejectConnectFilter , and proxygen::RequestHandlerAdaptor .
Referenced by proxygen::MockResponseHandler::MockResponseHandler(), proxygen::ResponseBuilder::send(), proxygen::Filter::sendChunkTerminator(), and ~ResponseHandler().
virtual void proxygen::ResponseHandler::sendEOM () [pure virtual], [noexcept]
Implemented in proxygen::ZlibServerFilter , proxygen::Filter , proxygen::RejectConnectFilter , proxygen::RequestHandlerAdaptor , and StubRequestHandlerAdaptor .
Referenced by proxygen::MockResponseHandler::MockResponseHandler(), ProxyService::ProxyHandler::onServerEOM(), proxygen::ResponseBuilder::rejectUpgradeRequest(), proxygen::ResponseBuilder::send(), proxygen::Filter::sendEOM(), and ~ResponseHandler().
virtual void proxygen::ResponseHandler::sendHeaders (HTTPMessage & msg) [pure virtual], [noexcept]
NOTE: We take response message as non-const reference, to allow filters between your handler and client to be able to modify response if they want to.
eg. a compression filter might want to change the content-encoding
Implemented in proxygen::Filter , proxygen::RejectConnectFilter , proxygen::RequestHandlerAdaptor , proxygen::ZlibServerFilter , and StubRequestHandlerAdaptor .
Referenced by proxygen::ResponseBuilder::acceptUpgradeRequest(), proxygen::MockResponseHandler::MockResponseHandler(), ProxyService::ProxyHandler::onServerHeadersComplete(), proxygen::ResponseBuilder::rejectUpgradeRequest(), proxygen::ResponseBuilder::send(), proxygen::Filter::sendHeaders(), and ~ResponseHandler().
Member Data Documentation
HTTPTransaction* proxygen::ResponseHandler::txn_ {nullptr} [protected]
Definition at line 98 of file ResponseHandler.h.
Referenced by proxygen::RequestHandlerAdaptor::getCurrentTransportInfo(), proxygen::RequestHandlerAdaptor::getSetupTransportInfo(), getTransaction(), proxygen::RequestHandlerAdaptor::newPushedResponse(), proxygen::RequestHandlerAdaptor::onError(), proxygen::RequestHandlerAdaptor::pauseIngress(), proxygen::RequestHandlerAdaptor::refreshTimeout(), proxygen::RequestHandlerAdaptor::resumeIngress(), proxygen::RequestHandlerAdaptor::sendAbort(), proxygen::RequestHandlerAdaptor::sendBody(), proxygen::RequestHandlerAdaptor::sendChunkHeader(), proxygen::RequestHandlerAdaptor::sendChunkTerminator(), proxygen::RequestHandlerAdaptor::sendEOM(), proxygen::RequestHandlerAdaptor::sendHeaders(), proxygen::Filter::setResponseHandler(), and proxygen::RequestHandlerAdaptor::setTransaction().
RequestHandler* proxygen::ResponseHandler::upstream_ {nullptr} [protected]
Definition at line 97 of file ResponseHandler.h.
Referenced by proxygen::Filter::canHandleExpect(), proxygen::RequestHandlerAdaptor::detachTransaction(), proxygen::Filter::getExHandler(), proxygen::RequestHandlerAdaptor::onBody(), proxygen::Filter::onBody(), proxygen::RequestHandlerAdaptor::onEgressPaused(), proxygen::Filter::onEgressPaused(), proxygen::RequestHandlerAdaptor::onEgressResumed(), proxygen::Filter::onEgressResumed(), proxygen::RequestHandlerAdaptor::onEOM(), proxygen::Filter::onEOM(), proxygen::RejectConnectFilter::onError(), proxygen::Filter::onError(), proxygen::RequestHandlerAdaptor::onExTransaction(), proxygen::RequestHandlerAdaptor::onHeadersComplete(), proxygen::RejectConnectFilter::onRequest(), proxygen::Filter::onRequest(), proxygen::Filter::onUpgrade(), proxygen::RequestHandlerAdaptor::onUpgrade(), proxygen::RejectConnectFilter::requestComplete(), proxygen::Filter::requestComplete(), proxygen::RequestHandlerAdaptor::setError(), proxygen::Filter::setResponseHandler(), and proxygen::RequestHandlerAdaptor::setTransaction().
The documentation for this class was generated from the following file:
proxygen/httpserver/ResponseHandler.h