proxygen::HTTPConnector::Callback Class Reference
#include <HTTPConnector.h>
Public Member Functions
virtual ~Callback ()
virtual void connectSuccess (HTTPUpstreamSession *session)=0
virtual void connectError (const folly::AsyncSocketException &ex)=0
Detailed Description
This class defines the pure virtual interface on which to receive the result on.
Definition at line 38 of file HTTPConnector.h.
Constructor & Destructor Documentation
virtual proxygen::HTTPConnector::Callback::~Callback () [inline], [virtual]
Definition at line 40 of file HTTPConnector.h.
References proxygen::HTTPConnector::connect(), connectError(), proxygen::HTTPConnector::connectSSL(), connectSuccess(), proxygen::HTTPConnector::HTTPConnector(), proxygen::HTTPConnector::reset(), proxygen::HTTPConnector::setHTTPVersionOverride(), proxygen::HTTPConnector::setPlaintextProtocol(), proxygen::HTTPConnector::timeElapsed(), and proxygen::HTTPConnector::~HTTPConnector().
{}
Member Function Documentation
virtual void proxygen::HTTPConnector::Callback::connectError (const folly::AsyncSocketException & ex) [pure virtual]
Implemented in ProxyService::ProxyHandler , and CurlService::CurlClient .
Referenced by proxygen::HTTPConnector::connectErr(), and ~Callback().
virtual void proxygen::HTTPConnector::Callback::connectSuccess (HTTPUpstreamSession * session) [pure virtual]
Implemented in ProxyService::ProxyHandler , and CurlService::CurlClient .
Referenced by proxygen::HTTPConnector::connectSuccess(), proxygen::HTTPConnector::setHTTPCodecFactory(), and ~Callback().
The documentation for this class was generated from the following file:
proxygen/lib/http/HTTPConnector.h