proxygen::StructuredHeadersEncoder Class Reference
#include <StructuredHeadersEncoder.h>
Public Member Functions
StructuredHeadersEncoder ()
EncodeError encodeParameterisedList (const ParameterisedList &input)
EncodeError encodeDictionary (const Dictionary &input)
EncodeError encodeList (const std::vector< StructuredHeaderItem > &input)
EncodeError encodeItem (const StructuredHeaderItem &input)
EncodeError encodeIdentifier (const std::string &input)
std::string get ()
Private Member Functions
EncodeError encodeBinaryContent (const std::string &input)
EncodeError encodeString (const std::string &input)
EncodeError encodeInteger (int64_t input)
EncodeError encodeFloat (double input)
EncodeError handleEncodeError (EncodeError err, const std::string &badContent)
EncodeError handleEncodeError (EncodeError err)
Private Attributes
std::string output_
string_buf buf_
std::ostream outputStream_
Detailed Description
Definition at line 28 of file StructuredHeadersEncoder.h.
Constructor & Destructor Documentation
proxygen::StructuredHeadersEncoder::StructuredHeadersEncoder ()
Definition at line 111 of file StructuredHeadersEncoder.cpp.
References proxygen::StructuredHeaders::kMaxValidFloatLength, and outputStream_.
                                                  :
   output_(),
   buf_(output_),
   outputStream_(&buf_) {
  outputStream_.precision(kMaxValidFloatLength - 1);
}
Member Function Documentation
EncodeError proxygen::StructuredHeadersEncoder::encodeBinaryContent (const std::string & input) [private]
Definition at line 142 of file StructuredHeadersEncoder.cpp.
References proxygen::StructuredHeaders::encodeBase64(), and outputStream_.
Referenced by encodeItem().
                           {
  outputStream_ << "*";
  outputStream_ << encodeBase64(input);
  outputStream_ << "*";
  return EncodeError::OK;
}
EncodeError proxygen::StructuredHeadersEncoder::encodeDictionary (const Dictionary & input)
Definition at line 43 of file StructuredHeadersEncoder.cpp.
References proxygen::StructuredHeaders::EMPTY_DATA_STRUCTURE, and proxygen::StructuredHeaders::OK.
Referenced by proxygen::TEST_F().
                           {
  if (input.empty()) {
    return handleEncodeError(EncodeError::EMPTY_DATA_STRUCTURE);
  }
  for (auto it = input.begin(); it != input.end(); it++) {
    auto err = encodeIdentifier(it->first);
    if (err != EncodeError::OK) {
      return err;
    }
    outputStream_ << "=";
    err = encodeItem(it->second);
    if (err != EncodeError::OK) {
      return err;
    }
    if (std::next(it, 1) != input.end()) {
      outputStream_ << ", ";
    }
  }
  return EncodeError::OK;
}
EncodeError proxygen::StructuredHeadersEncoder::encodeFloat (double input) [private]
Definition at line 178 of file StructuredHeadersEncoder.cpp.
References outputStream_.
Referenced by encodeItem().
                                                              {
  outputStream_ << input;
  return EncodeError::OK;
}
EncodeError proxygen::StructuredHeadersEncoder::encodeIdentifier (const std::string & input)
Definition at line 185 of file StructuredHeadersEncoder.cpp.
References handleEncodeError(), proxygen::StructuredHeaders::isValidIdentifier(), and outputStream_.
Referenced by proxygen::TEST_F().
                          {
  if (!isValidIdentifier(input)) {
    return handleEncodeError(EncodeError::BAD_IDENTIFIER, input);
  }
  outputStream_ << input;
  return EncodeError::OK;
}
EncodeError proxygen::StructuredHeadersEncoder::encodeInteger (int64_t input) [private]
Definition at line 171 of file StructuredHeadersEncoder.cpp.
References outputStream_.
Referenced by encodeItem().
                                                                 {
  outputStream_ << input;
  return EncodeError::OK;
}
EncodeError proxygen::StructuredHeadersEncoder::encodeItem (const StructuredHeaderItem & input)
Definition at line 118 of file StructuredHeadersEncoder.cpp.
References encodeBinaryContent(), encodeFloat(), encodeInteger(), encodeString(), handleEncodeError(), proxygen::StructuredHeaders::itemTypeMatchesContent(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
Referenced by proxygen::TEST_F().
                                     {
  if (!itemTypeMatchesContent(input)) {
    return handleEncodeError(EncodeError::ITEM_TYPE_MISMATCH);
  }
  switch (input.tag) {
    case StructuredHeaderItem::Type::STRING:
      return encodeString(boost::get<std::string>(input.value));
    case StructuredHeaderItem::Type::INT64:
      return encodeInteger(boost::get<int64_t>(input.value));
    case StructuredHeaderItem::Type::DOUBLE:
      return encodeFloat(boost::get<double>(input.value));
    case StructuredHeaderItem::Type::BINARYCONTENT:
      return encodeBinaryContent(
        boost::get<std::string>(input.value));
    default:
      return handleEncodeError(EncodeError::ENCODING_NULL_ITEM);
  }
  return EncodeError::OK;
}
EncodeError proxygen::StructuredHeadersEncoder::encodeList (const std::vector< StructuredHeaderItem > & input)
Definition at line 22 of file StructuredHeadersEncoder.cpp.
References proxygen::StructuredHeaders::EMPTY_DATA_STRUCTURE, and proxygen::StructuredHeaders::OK.
Referenced by proxygen::TEST_F().
                                                {
  if (input.empty()) {
    return handleEncodeError(EncodeError::EMPTY_DATA_STRUCTURE);
  }
  for (auto it = input.begin(); it != input.end(); it++) {
    auto err = encodeItem(*it);
    if (err != EncodeError::OK) {
      return err;
    }
    if (std::next(it, 1)!= input.end()) {
      outputStream_ << ", ";
    }
  }
  return EncodeError::OK;
}
EncodeError proxygen::StructuredHeadersEncoder::encodeParameterisedList (const ParameterisedList & input)
Definition at line 71 of file StructuredHeadersEncoder.cpp.
References proxygen::StructuredHeaders::EMPTY_DATA_STRUCTURE, proxygen::StructuredHeaders::StructuredHeaderItem::NONE, and proxygen::StructuredHeaders::OK.
Referenced by proxygen::TEST_F().
                                  {
  if (input.empty()) {
    return handleEncodeError(EncodeError::EMPTY_DATA_STRUCTURE);
  }
  for (auto it1 = input.begin(); it1 != input.end(); it1++) {
    auto err = encodeIdentifier(it1->identifier);
    if (err != EncodeError::OK) {
      return err;
    }
    for (auto it2 = it1->parameterMap.begin();
      it2 != it1->parameterMap.end(); it2++) {
      outputStream_ << "; ";
      err = encodeIdentifier(it2->first);
      if (err != EncodeError::OK) {
        return err;
      }
      if (it2->second.tag != StructuredHeaderItem::Type::NONE) {
        outputStream_ << "=";
        err = encodeItem(it2->second);
        if (err != EncodeError::OK) {
          return err;
        }
      }
    }
    if (std::next(it1, 1) != input.end()) {
      outputStream_ << ", ";
    }
  }
  return EncodeError::OK;
}
EncodeError proxygen::StructuredHeadersEncoder::encodeString (const std::string & input) [private]
Definition at line 152 of file StructuredHeadersEncoder.cpp.
References handleEncodeError(), proxygen::StructuredHeaders::isValidString(), and outputStream_.
Referenced by encodeItem().
                                                                         {
  if (!isValidString(input)) {
    return handleEncodeError(EncodeError::BAD_STRING, input);
  }
  outputStream_ << "\"";
  for (char c : input) {
    if (c == '"' || c == '\\') {
      outputStream_ << "\\";
    }
    outputStream_ << c;
  }
  outputStream_ << "\"";
  return EncodeError::OK;
}
std::string proxygen::StructuredHeadersEncoder::get ()
Definition at line 212 of file StructuredHeadersEncoder.cpp.
References output_, and outputStream_.
Referenced by proxygen::TEST_F().
                                        {
  outputStream_.flush();
  return std::move(output_);
}
EncodeError proxygen::StructuredHeadersEncoder::handleEncodeError (EncodeError err, const std::string & badContent) [private]
Definition at line 197 of file StructuredHeadersEncoder.cpp.
References proxygen::StructuredHeaders::encodeErrorDescription, and proxygen::ERROR.
Referenced by encodeIdentifier(), encodeItem(), and encodeString().
                            {
  LOG_EVERY_N(ERROR, 1000) << "Error message: " <<
    encodeErrorDescription.at(err) << " .The culprit was: " << culprit;
  return err;
}
EncodeError proxygen::StructuredHeadersEncoder::handleEncodeError (EncodeError err) [private]
Definition at line 206 of file StructuredHeadersEncoder.cpp.
References proxygen::StructuredHeaders::encodeErrorDescription, and proxygen::ERROR.
                                                                       {
  LOG_EVERY_N(ERROR, 1000) << "Error message: " <<
    encodeErrorDescription.at(err);
  return err;
}
Member Data Documentation
string_buf proxygen::StructuredHeadersEncoder::buf_ [private]
Definition at line 62 of file StructuredHeadersEncoder.h.
std::string proxygen::StructuredHeadersEncoder::output_ [private]
Definition at line 61 of file StructuredHeadersEncoder.h.
Referenced by get().
std::ostream proxygen::StructuredHeadersEncoder::outputStream_ [private]
Definition at line 63 of file StructuredHeadersEncoder.h.
Referenced by encodeBinaryContent(), encodeFloat(), encodeIdentifier(), encodeInteger(), encodeString(), get(), and StructuredHeadersEncoder().
The documentation for this class was generated from the following files:
proxygen/lib/http/structuredheaders/StructuredHeadersEncoder.h
proxygen/lib/http/structuredheaders/StructuredHeadersEncoder.cpp