proxygen::HTTPCodec Class Reference
#include <HTTPCodec.h>
Classes
class Callback
struct ExAttributes
class PriorityQueue
Public Types
using StreamID = uint64_t
Public Member Functions
virtual ~HTTPCodec ()
virtual CompressionInfo getCompressionInfo () const
virtual CodecProtocol getProtocol () const =0
virtual const std::string & getUserAgent () const =0
virtual TransportDirection getTransportDirection () const =0
virtual bool supportsStreamFlowControl () const
virtual bool supportsSessionFlowControl () const
virtual StreamID createStream ()=0
virtual void setCallback (Callback *callback)=0
virtual bool isBusy () const =0
virtual void setParserPaused (bool paused)=0
virtual size_t onIngress (const folly::IOBuf &buf)=0
virtual void onIngressEOF ()=0
virtual bool onIngressUpgradeMessage (const HTTPMessage &)
virtual bool isReusable () const =0
virtual bool isWaitingToDrain () const =0
virtual bool closeOnEgressComplete () const =0
virtual bool supportsParallelRequests () const =0
virtual bool supportsPushTransactions () const =0
virtual bool supportsExTransactions () const
virtual size_t generateConnectionPreface (folly::IOBufQueue &)
virtual void generateHeader (folly::IOBufQueue &writeBuf, StreamID stream, const HTTPMessage &msg, bool eom=false, HTTPHeaderSize *size=nullptr)=0
virtual void generatePushPromise (folly::IOBufQueue &, StreamID, const HTTPMessage &, StreamID, bool, HTTPHeaderSize *)
virtual void generateExHeader (folly::IOBufQueue &, StreamID, const HTTPMessage &, const HTTPCodec::ExAttributes &, bool, HTTPHeaderSize *)
virtual size_t generateBody (folly::IOBufQueue &writeBuf, StreamID stream, std::unique_ptr< folly::IOBuf > chain, folly::Optional< uint8_t > padding, bool eom)=0
virtual size_t generateChunkHeader (folly::IOBufQueue &writeBuf, StreamID stream, size_t length)=0
virtual size_t generateChunkTerminator (folly::IOBufQueue &writeBuf, StreamID stream)=0
virtual size_t generateTrailers (folly::IOBufQueue &writeBuf, StreamID stream, const HTTPHeaders &trailers)=0
virtual size_t generateEOM (folly::IOBufQueue &writeBuf, StreamID stream)=0
virtual size_t generateRstStream (folly::IOBufQueue &writeBuf, StreamID stream, ErrorCode code)=0
virtual size_t generateGoaway (folly::IOBufQueue &writeBuf, StreamID lastStream, ErrorCode code, std::unique_ptr< folly::IOBuf > debugData=nullptr)=0
virtual size_t generatePingRequest (folly::IOBufQueue &)
virtual size_t generatePingReply (folly::IOBufQueue &, uint64_t)
virtual size_t generateSettings (folly::IOBufQueue &)
virtual size_t generateSettingsAck (folly::IOBufQueue &)
virtual size_t generateWindowUpdate (folly::IOBufQueue &, StreamID, uint32_t)
virtual size_t generatePriority (folly::IOBufQueue &, StreamID, const HTTPMessage::HTTPPriority &)
virtual size_t generateCertificateRequest (folly::IOBufQueue &, uint16_t, std::unique_ptr< folly::IOBuf >)
virtual size_t generateCertificate (folly::IOBufQueue &, uint16_t, std::unique_ptr< folly::IOBuf >)
virtual HTTPSettings * getEgressSettings ()
virtual const HTTPSettings * getIngressSettings () const
virtual void enableDoubleGoawayDrain ()
virtual void setHeaderCodecStats (HeaderCodec::Stats *)
virtual StreamID getLastIncomingStreamID () const
virtual uint32_t getDefaultWindowSize () const
virtual size_t addPriorityNodes (PriorityQueue &, folly::IOBufQueue &, uint8_t)
virtual StreamID mapPriorityToDependency (uint8_t) const
virtual int8_t mapDependencyToPriority (StreamID) const
Static Public Attributes
static const folly::Optional< StreamID > NoStream
static const folly::Optional< uint8_t > NoPadding = folly::none
static const StreamID MAX_STREAM_ID = 1u << 31
static const folly::Optional< ExAttributes > NoExAttributes
Detailed Description
Interface for a parser&generator that can translate between an internal representation of an HTTP request and a wire format. The details of the wire format (e.g., HTTP/1.x encoding vs. SPDY encoding) are left for subclasses to implement.
Definition at line 36 of file HTTPCodec.h.
Member Typedef Documentation
using proxygen::HTTPCodec::StreamID = uint64_t
Key that uniquely identifies a request/response pair within (and only within) the scope of the codec. Code outside the codec should regard the StreamID as an opaque data structure; different subclasses of HTTPCodec are likely to use different conventions for generating StreamID values.
A value of zero indicates an uninitialized/unknown/unspecified StreamID.
Definition at line 49 of file HTTPCodec.h.
Constructor & Destructor Documentation
virtual proxygen::HTTPCodec::~HTTPCodec () [inline], [virtual]
Definition at line 332 of file HTTPCodec.h.
{}
Member Function Documentation
virtual size_t proxygen::HTTPCodec::addPriorityNodes (PriorityQueue & , folly::IOBufQueue & , uint8_t) [inline], [virtual]
Create virtual nodes in HTTP/2 priority tree. Some protocols (SPDY) have a linear priority structure which must be simulated in the HTTP/2 tree structure with `virtual` nodes representing different priority bands. There are other cases we simply want a `plain` linear priority structure even with HTTP/2. In that case a Priority frame will also be sent out for each virtual node created so that peer will have the same linear structure.
Parameters
queue the priority queue to add nodes
writeBuf IOBufQueue to append priority frames to send. For SPDY, the writeBuf will be ignored.
maxLavel the max level of virtual priority nodes to create. For SPDY, this value will be ignored.
Reimplemented in proxygen::HTTP2Codec , and proxygen::SPDYCodec .
Definition at line 696 of file HTTPCodec.h.
Referenced by proxygen::MockHTTPCodec::generateCertificate(), proxygen::HTTPDownstreamSession::onNativeProtocolUpgrade(), proxygen::HTTPUpstreamSession::onNativeProtocolUpgrade(), proxygen::HTTPDownstreamSession::startNow(), and proxygen::HTTPUpstreamSession::startNow().
                 {
    return 0;
  }
virtual bool proxygen::HTTPCodec::closeOnEgressComplete () const [pure virtual]
Checks whether the socket needs to be closed when EOM is sent. This is used during CONNECT when EOF needs to be sent after upgrade to notify the server
Implemented in proxygen::HTTP1xCodec , and proxygen::HTTPParallelCodec .
Referenced by onIngressUpgradeMessage(), and proxygen::HTTPSession::shutdownTransport().
virtual StreamID proxygen::HTTPCodec::createStream () [pure virtual]
Reserve a stream ID.
Returns
A stream ID on success, or zero on error.
Implemented in proxygen::HTTP1xCodec , and proxygen::HTTPParallelCodec .
Referenced by proxygen::HTTPSession::newExTransaction(), proxygen::HTTPSession::newPushedTransaction(), proxygen::HTTPUpstreamSession::newTransaction(), proxygen::HTTPSession::onNativeProtocolUpgradeImpl(), proxygen::HTTPSession::sendPriority(), and supportsSessionFlowControl().
virtual void proxygen::HTTPCodec::enableDoubleGoawayDrain () [inline], [virtual]
This enables HTTP/2 style behavior during graceful shutdown that allows 2 GOAWAYs to be sent during shutdown.
Reimplemented in proxygen::HTTPParallelCodec .
Definition at line 665 of file HTTPCodec.h.
Referenced by proxygen::HTTPSession::enableDoubleGoawayDrain(), and proxygen::MockHTTPCodec::generateCertificate().
{}
virtual size_t proxygen::HTTPCodec::generateBody (folly::IOBufQueue & writeBuf, StreamID stream, std::unique_ptr< folly::IOBuf > chain, folly::Optional< uint8_t > padding, bool eom) [pure virtual]
Write part of an egress message body.
This will automatically generate a chunk header and footer around the data if necessary (e.g. you haven't manually sent a chunk header and the message should be chunked).
Parameters
padding Optionally add padding bytes to the body if possible
eom implicitly generate the EOM marker with this body frame
Returns
number of bytes written
Implemented in proxygen::HTTP2Codec , proxygen::HTTP1xCodec , proxygen::SPDYCodec , and proxygen::MockHTTPCodec .
Referenced by generateExHeader(), and proxygen::HTTPSession::sendBody().
virtual size_t proxygen::HTTPCodec::generateCertificate (folly::IOBufQueue & , uint16_t , std::unique_ptr< folly::IOBuf >) [inline], [virtual]
Reimplemented in proxygen::MockHTTPCodec , and proxygen::HTTP2Codec .
Definition at line 642 of file HTTPCodec.h.
Referenced by proxygen::HTTPSession::onCertificateRequest().
                                   {
    return 0;
  }
virtual size_t proxygen::HTTPCodec::generateCertificateRequest (folly::IOBufQueue & , uint16_t , std::unique_ptr< folly::IOBuf >) [inline], [virtual]
Reimplemented in proxygen::HTTP2Codec , and proxygen::MockHTTPCodec .
Definition at line 631 of file HTTPCodec.h.
Referenced by proxygen::HTTPSession::sendCertificateRequest().
                                   {
    return 0;
  }
virtual size_t proxygen::HTTPCodec::generateChunkHeader (folly::IOBufQueue & writeBuf, StreamID stream, size_t length) [pure virtual]
Write a body chunk header, if relevant.
Implemented in proxygen::HTTP2Codec , proxygen::HTTP1xCodec , and proxygen::SPDYCodec .
Referenced by proxygen::MockHTTPCodec::generateBody(), generateExHeader(), and proxygen::HTTPSession::sendChunkHeader().
virtual size_t proxygen::HTTPCodec::generateChunkTerminator (folly::IOBufQueue & writeBuf, StreamID stream) [pure virtual]
Write a body chunk terminator, if relevant.
Implemented in proxygen::HTTP2Codec , proxygen::HTTP1xCodec , and proxygen::SPDYCodec .
Referenced by proxygen::MockHTTPCodec::generateBody(), generateExHeader(), and proxygen::HTTPSession::sendChunkTerminator().
virtual size_t proxygen::HTTPCodec::generateConnectionPreface (folly::IOBufQueue &) [inline], [virtual]
Generate a connection preface, if there is any for this protocol.
Returns
size of the generated message
Reimplemented in proxygen::HTTP2Codec .
Definition at line 475 of file HTTPCodec.h.
References generateHeader().
Referenced by HTTPParallelCodecTest::SetUp(), proxygen::HTTPSession::setupCodec(), and HTTPParallelCodecTest::SetUpUpstreamTest().
                                                               {
    return 0;
  }
virtual size_t proxygen::HTTPCodec::generateEOM (folly::IOBufQueue & writeBuf, StreamID stream) [pure virtual]
Generate any protocol framing needed to finalize an egress message. This method must be called to complete a stream.
Returns
number of bytes written
Implemented in proxygen::HTTP2Codec , proxygen::HTTP1xCodec , and proxygen::SPDYCodec .
Referenced by proxygen::MockHTTPCodec::generateBody(), generateExHeader(), and proxygen::HTTPSession::sendEOM().
virtual void proxygen::HTTPCodec::generateExHeader (folly::IOBufQueue & , StreamID , const HTTPMessage & , const HTTPCodec::ExAttributes & , bool , HTTPHeaderSize *) [inline], [virtual]
Reimplemented in proxygen::HTTP2Codec .
Definition at line 499 of file HTTPCodec.h.
References generateBody(), generateChunkHeader(), generateChunkTerminator(), generateEOM(), generateGoaway(), generateRstStream(), and generateTrailers().
Referenced by proxygen::HTTPSession::sendHeaders().
                                                   {}
virtual size_t proxygen::HTTPCodec::generateGoaway (folly::IOBufQueue & writeBuf, StreamID lastStream, ErrorCode code, std::unique_ptr< folly::IOBuf > debugData = nullptr) [pure virtual]
Generate any protocol framing needed to abort a connection.
Returns
number of bytes written
Implemented in proxygen::HTTP2Codec , proxygen::MockHTTPCodec , proxygen::HTTP1xCodec , and proxygen::SPDYCodec .
Referenced by proxygen::HTTPSession::closeWhenIdle(), proxygen::HTTPSession::drainImpl(), generateExHeader(), proxygen::HTTPSession::onSessionParseError(), proxygen::HTTPSession::shutdownTransport(), and proxygen::HTTPSession::startNow().
virtual void proxygen::HTTPCodec::generateHeader (folly::IOBufQueue & writeBuf, StreamID stream, const HTTPMessage & msg, bool eom = false, HTTPHeaderSize * size = nullptr) [pure virtual]
Write an egress message header. For pushed streams, you must specify the assocStream.
Return values
size the size of the generated message, both the actual size and the size of the uncompressed data.
Returns
None
Implemented in proxygen::HTTP1xCodec , proxygen::SPDYCodec , and proxygen::HTTP2Codec .
Referenced by generateConnectionPreface(), and proxygen::HTTPSession::sendHeaders().
virtual size_t proxygen::HTTPCodec::generatePingReply (folly::IOBufQueue & , uint64_t) [inline], [virtual]
Generate a reply to a ping message, if supported in the protocol implemented by the codec.
Reimplemented in proxygen::HTTP2Codec , and proxygen::SPDYCodec .
Definition at line 584 of file HTTPCodec.h.
Referenced by proxygen::MockHTTPCodec::generateGoaway(), and proxygen::HTTPSession::onPingRequest().
                  { return 0; }
virtual size_t proxygen::HTTPCodec::generatePingRequest (folly::IOBufQueue &) [inline], [virtual]
If the protocol supports it, generate a ping message that the other side should respond to.
Reimplemented in proxygen::HTTP2Codec , and proxygen::SPDYCodec .
Definition at line 576 of file HTTPCodec.h.
Referenced by proxygen::MockHTTPCodec::generateGoaway(), and proxygen::HTTPSession::sendPing().
                                                         {
    return 0;
  }
virtual size_t proxygen::HTTPCodec::generatePriority (folly::IOBufQueue & , StreamID , const HTTPMessage::HTTPPriority &) [inline], [virtual]
Reimplemented in proxygen::HTTP2Codec .
Definition at line 620 of file HTTPCodec.h.
Referenced by proxygen::HTTPSession::sendPriorityImpl().
                                        {
    return 0;
  }
virtual void proxygen::HTTPCodec::generatePushPromise (folly::IOBufQueue & , StreamID , const HTTPMessage & , StreamID , bool , HTTPHeaderSize *) [inline], [virtual]
Reimplemented in proxygen::HTTP2Codec , and proxygen::SPDYCodec .
Definition at line 492 of file HTTPCodec.h.
Referenced by proxygen::HTTPSession::sendHeaders().
                                                      {}
virtual size_t proxygen::HTTPCodec::generateRstStream (folly::IOBufQueue & writeBuf, StreamID stream, ErrorCode code) [pure virtual]
Generate any protocol framing needed to abort a stream.
Returns
number of bytes written
Implemented in proxygen::HTTP2Codec , proxygen::HTTP1xCodec , and proxygen::SPDYCodec .
Referenced by proxygen::MockHTTPCodec::generateBody(), generateExHeader(), proxygen::HTTPSession::onNewTransactionParseError(), and proxygen::HTTPSession::sendAbort().
virtual size_t proxygen::HTTPCodec::generateSettings (folly::IOBufQueue &) [inline], [virtual]
Generate a settings message, if supported in the protocol implemented by the codec.
Reimplemented in proxygen::HTTP2Codec , and proxygen::SPDYCodec .
Definition at line 592 of file HTTPCodec.h.
Referenced by proxygen::MockHTTPCodec::generateGoaway(), proxygen::HTTPSession::sendSettings(), HTTPParallelCodecTest::SetUpUpstreamTest(), and proxygen::HTTPSession::startNow().
                                                      {
    return 0;
  }
virtual size_t proxygen::HTTPCodec::generateSettingsAck (folly::IOBufQueue &) [inline], [virtual]
Generate a settings ack message, if supported in the protocol implemented by the codec.
Reimplemented in proxygen::HTTP2Codec .
Definition at line 600 of file HTTPCodec.h.
Referenced by proxygen::MockHTTPCodec::generateGoaway(), and proxygen::HTTPSession::onSettings().
                                                         {
    return 0;
  }
virtual size_t proxygen::HTTPCodec::generateTrailers (folly::IOBufQueue & writeBuf, StreamID stream, const HTTPHeaders & trailers) [pure virtual]
Write the message trailers
Returns
number of bytes written
Implemented in proxygen::HTTP2Codec , proxygen::HTTP1xCodec , and proxygen::SPDYCodec .
Referenced by proxygen::MockHTTPCodec::generateBody(), generateExHeader(), and proxygen::HTTPSession::sendEOM().
virtual size_t proxygen::HTTPCodec::generateWindowUpdate (folly::IOBufQueue & , StreamID , uint32_t) [inline], [virtual]
Reimplemented in proxygen::HTTP2Codec , and proxygen::SPDYCodec .
Definition at line 610 of file HTTPCodec.h.
Referenced by proxygen::FlowControlFilter::FlowControlFilter(), proxygen::MockHTTPCodec::generateGoaway(), and proxygen::HTTPSession::sendWindowUpdate().
                  {
    return 0;
  }
virtual CompressionInfo proxygen::HTTPCodec::getCompressionInfo () const [inline], [virtual]
Gets both the egress and ingress header table size, bytes stored in header table, and the number of headers stored in the header table
Reimplemented in proxygen::HTTP2Codec .
Definition at line 338 of file HTTPCodec.h.
References getProtocol(), getTransportDirection(), and getUserAgent().
Referenced by proxygen::HTTPTransaction::onIngressHeadersComplete(), and proxygen::HTTPTransaction::sendHeadersWithOptionalEOM().
                                                     {
    static CompressionInfo defaultCompressionInfo;
    return defaultCompressionInfo;
  }
virtual uint32_t proxygen::HTTPCodec::getDefaultWindowSize () const [inline], [virtual]
Get the default size of flow control windows for this protocol
Reimplemented in proxygen::HTTP2Codec , and proxygen::SPDYCodec .
Definition at line 680 of file HTTPCodec.h.
Referenced by HTTPUpstreamTest< SPDY3CodecPair >::commonSetUp(), proxygen::FlowControlFilter::FlowControlFilter(), proxygen::MockHTTPCodec::generateCertificate(), proxygen::HTTPSession::getCodecSendWindowSize(), proxygen::HTTPSession::onNativeProtocolUpgradeImpl(), and proxygen::HTTPSession::WriteSegment::writeErr().
{ return 0; }
virtual HTTPSettings* proxygen::HTTPCodec::getEgressSettings () [inline], [virtual]
Reimplemented in proxygen::HTTP2Codec , and proxygen::SPDYCodec .
Definition at line 653 of file HTTPCodec.h.
Referenced by proxygen::HTTPSessionBase::enableExHeadersSettings(), proxygen::MockHTTPCodec::generateCertificate(), proxygen::HTTPSession::newExTransaction(), proxygen::HTTPSession::onNativeProtocolUpgradeImpl(), proxygen::HTTPSession::sendCertificateRequest(), proxygen::HTTPSession::setEgressSettings(), proxygen::HTTPSession::setFlowControl(), proxygen::HTTPSession::setMaxConcurrentIncomingStreams(), and proxygen::HTTPSession::setupCodec().
                                            {
    return nullptr;
  }
virtual const HTTPSettings* proxygen::HTTPCodec::getIngressSettings () const [inline], [virtual]
Reimplemented in proxygen::HTTP2Codec , and proxygen::SPDYCodec .
Definition at line 657 of file HTTPCodec.h.
Referenced by proxygen::MockHTTPCodec::generateCertificate(), proxygen::HTTPSession::getCodecSendWindowSize(), proxygen::HTTPSession::sendCertificateRequest(), and proxygen::HTTPDownstreamSession::setupOnHeadersComplete().
                                                         {
    return nullptr;
  }
virtual StreamID proxygen::HTTPCodec::getLastIncomingStreamID () const [inline], [virtual]
Get the identifier of the last stream started by the remote.
Reimplemented in proxygen::HTTPParallelCodec .
Definition at line 675 of file HTTPCodec.h.
Referenced by proxygen::HTTPSession::closeWhenIdle(), proxygen::HTTPSession::getGracefulGoawayAck(), proxygen::HTTPSession::onSessionParseError(), and proxygen::HTTPSession::shutdownTransport().
{ return 0; }
virtual CodecProtocol proxygen::HTTPCodec::getProtocol () const [pure virtual]
Gets the session protocol currently used by the codec. This can be mapped to a string for logging and diagnostic use.
Implemented in proxygen::SPDYCodec , proxygen::HTTP2Codec , and proxygen::HTTP1xCodec .
Referenced by proxygen::HTTPSession::describe(), getCompressionInfo(), proxygen::HTTPSession::getNextToSend(), proxygen::HTTPSessionBase::initCodecHeaderIndexingStrategy(), proxygen::HTTPSession::newExTransaction(), proxygen::HTTPSession::onSessionParseError(), proxygen::HTTPSession::sendEOM(), and proxygen::HTTPSession::WriteSegment::writeErr().
virtual TransportDirection proxygen::HTTPCodec::getTransportDirection () const [pure virtual]
Get the transport direction of this codec: DOWNSTREAM if the codec receives requests from clients or UPSTREAM if the codec sends requests to servers.
Implemented in proxygen::HTTP1xCodec , and proxygen::HTTPParallelCodec .
Referenced by proxygen::HTTPSession::createTransaction(), getCompressionInfo(), proxygen::HTTPSessionBase::getParseErrorHandler(), proxygen::HTTPDownstreamSession::HTTPDownstreamSession(), proxygen::HTTPUpstreamSession::HTTPUpstreamSession(), proxygen::HTTPSession::isDownstream(), and proxygen::HTTPSession::isUpstream().
virtual const std::string& proxygen::HTTPCodec::getUserAgent () const [pure virtual]
Gets the user agent string of the client. Thus, it is only meaningful for a DOWNSTREAM session. Note that the value is available after onHeadersComplete(). It can help in diagnosing the interactions between different codec implementation.
Implemented in proxygen::SPDYCodec , proxygen::HTTP2Codec , and proxygen::HTTP1xCodec .
Referenced by proxygen::HTTPSession::describe(), and getCompressionInfo().
virtual bool proxygen::HTTPCodec::isBusy () const [pure virtual]
Check whether the codec still has at least one HTTP stream to parse.
Implemented in proxygen::HTTP1xCodec , and proxygen::HTTPParallelCodec .
Referenced by proxygen::HTTPSession::isBusy(), proxygen::HTTPUpstreamSession::isReusable(), and supportsSessionFlowControl().
virtual bool proxygen::HTTPCodec::isReusable () const [pure virtual]
Check whether the codec can process new streams. Typically, an implementing subclass will return true when a new codec is created and false once it encounters a situation that would prevent reuse of the underlying transport (e.g., a `Connection: close` in HTTP/1.x).
Note
A return value of true means that the codec can process new connections at some reasonable point in the future; that may mean `immediately,` for codecs that support pipelined or interleaved requests, or `upon completion of the current
      stream` for codecs that do not.
Implemented in proxygen::HTTP1xCodec , and proxygen::HTTPParallelCodec .
Referenced by proxygen::HTTPSession::drainImpl(), proxygen::HTTPSession::getGracefulGoawayAck(), proxygen::HTTPUpstreamSession::isReusable(), proxygen::HTTPSession::onEgressMessageFinished(), proxygen::HTTPSession::onError(), proxygen::HTTPSession::onHeadersComplete(), proxygen::HTTPDownstreamSession::onHeadersSent(), onIngressUpgradeMessage(), proxygen::HTTPSession::onMessageComplete(), proxygen::HTTPSession::onNewTransactionParseError(), proxygen::HTTPSession::onWriteSuccess(), proxygen::HTTPSession::sendAbort(), proxygen::HTTPSession::sendHeaders(), and proxygen::HTTPSession::shouldShutdown().
virtual bool proxygen::HTTPCodec::isWaitingToDrain () const [pure virtual]
Returns true if this codec is in a state where it accepting new requests but will soon begin to reject new requests. For SPDY and HTTP/2, this is true when the first GOAWAY NO_ERROR is sent during graceful shutdown.
Implemented in proxygen::HTTP1xCodec , and proxygen::HTTPParallelCodec .
Referenced by proxygen::HTTPSession::drainImpl(), proxygen::HTTPSession::getGracefulGoawayAck(), and onIngressUpgradeMessage().
virtual int8_t proxygen::HTTPCodec::mapDependencyToPriority (StreamID) const [inline], [virtual]
Map the parent back to the priority, -1 if this doesn't make sense.
Reimplemented in proxygen::SPDYCodec .
Definition at line 713 of file HTTPCodec.h.
                                                           {
    return -1;
  }
virtual StreamID proxygen::HTTPCodec::mapPriorityToDependency (uint8_t) const [inline], [virtual]
Map the given linear priority to the correct parent node dependency
Reimplemented in proxygen::HTTP2Codec , and proxygen::SPDYCodec .
Definition at line 706 of file HTTPCodec.h.
Referenced by proxygen::MockHTTPCodec::generateCertificate(), proxygen::HTTPSession::getMessagePriority(), and proxygen::HTTPTransaction::updateAndSendPriority().
                                                            {
    return 0;
  }
virtual size_t proxygen::HTTPCodec::onIngress (const folly::IOBuf & buf) [pure virtual]
Parse ingress data.
Parameters
buf A single IOBuf of data to parse
Returns
Number of bytes consumed.
Implemented in proxygen::SPDYCodec , proxygen::HTTP1xCodec , and proxygen::HTTP2Codec .
Referenced by HTTPParallelCodecTest::parseImpl(), HTTPUpstreamTest< SPDY3CodecPair >::parseOutput(), HTTPDownstreamTest< SPDY3_1CodecPair >::parseOutput(), proxygen::HTTPSession::processReadData(), and supportsSessionFlowControl().
virtual void proxygen::HTTPCodec::onIngressEOF () [pure virtual]
Finish parsing when the ingress stream has ended.
Implemented in proxygen::HTTP1xCodec , and proxygen::HTTPParallelCodec .
Referenced by proxygen::HTTPSession::shutdownTransport(), and supportsSessionFlowControl().
virtual bool proxygen::HTTPCodec::onIngressUpgradeMessage (const HTTPMessage &) [inline], [virtual]
Invoked on a codec that has been upgraded to via an HTTPMessage on a different codec. The codec may return false to halt the upgrade.
Reimplemented in proxygen::HTTPParallelCodec , and proxygen::HTTP2Codec .
Definition at line 418 of file HTTPCodec.h.
References closeOnEgressComplete(), isReusable(), isWaitingToDrain(), supportsParallelRequests(), and supportsPushTransactions().
                                                             {
    return true;
  }
virtual void proxygen::HTTPCodec::setCallback (Callback * callback) [pure virtual]
Set the callback to notify on ingress events
Parameters
callback The callback object
Implemented in proxygen::HTTP1xCodec , and proxygen::HTTPParallelCodec .
Referenced by proxygen::PassThroughHTTPCodecFilter::PassThroughHTTPCodecFilter(), and supportsSessionFlowControl().
virtual void proxygen::HTTPCodec::setHeaderCodecStats (HeaderCodec::Stats *) [inline], [virtual]
set stats for the header codec, if the protocol supports header compression
Reimplemented in proxygen::HTTP2Codec , and proxygen::SPDYCodec .
Definition at line 670 of file HTTPCodec.h.
Referenced by proxygen::HTTPUpstreamSession::attachThreadLocals(), proxygen::HTTPUpstreamSession::detachThreadLocals(), and proxygen::HTTPSession::setHeaderCodecStats().
{}
virtual void proxygen::HTTPCodec::setParserPaused (bool paused) [pure virtual]
Pause or resume the ingress parser
Parameters
paused Whether the caller wants the parser to be paused
Implemented in proxygen::HTTP1xCodec , and proxygen::HTTPParallelCodec .
Referenced by proxygen::HTTPSession::pauseReads(), proxygen::HTTPSession::processReadData(), proxygen::HTTPSession::resumeReadsImpl(), proxygen::HTTPSession::shutdownTransport(), and supportsSessionFlowControl().
virtual bool proxygen::HTTPCodec::supportsExTransactions () const [inline], [virtual]
Check whether the codec supports bidirectional communications between server and client.
Reimplemented in proxygen::HTTP2Codec .
Definition at line 466 of file HTTPCodec.h.
                                              {
    return false;
  }
virtual bool proxygen::HTTPCodec::supportsParallelRequests () const [pure virtual]
Check whether the codec supports the processing of multiple requests in parallel.
Implemented in proxygen::HTTP1xCodec , and proxygen::HTTPParallelCodec .
Referenced by proxygen::HTTPSession::invalidStream(), proxygen::HTTPUpstreamSession::isReusable(), proxygen::HTTPSession::maybeResumePausedPipelinedTransaction(), proxygen::HTTPSession::onError(), onIngressUpgradeMessage(), proxygen::HTTPSession::onMessageBegin(), proxygen::HTTPSession::onMessageComplete(), proxygen::HTTPSession::onNativeProtocolUpgradeImpl(), proxygen::HTTPSession::pauseReads(), proxygen::HTTPSession::resumeReads(), proxygen::HTTPTransaction::sendBody(), proxygen::HTTPSession::sendPriority(), proxygen::HTTPSession::setMaxConcurrentIncomingStreams(), proxygen::HTTPSession::setupCodec(), proxygen::HTTPSession::shouldShutdown(), and proxygen::HTTPSession::transactionTimeout().
virtual bool proxygen::HTTPCodec::supportsPushTransactions () const [pure virtual]
Check whether the codec supports pushing resources from server to client.
Implemented in proxygen::HTTP2Codec , proxygen::HTTP1xCodec , and proxygen::SPDYCodec .
Referenced by proxygen::HTTPSession::newPushedTransaction(), and onIngressUpgradeMessage().
virtual bool proxygen::HTTPCodec::supportsSessionFlowControl () const [inline], [virtual]
Returns true iff this codec supports session level flow control
Reimplemented in proxygen::SPDYCodec , and proxygen::HTTPParallelCodec .
Definition at line 374 of file HTTPCodec.h.
References createStream(), isBusy(), onIngress(), onIngressEOF(), setCallback(), and setParserPaused().
Referenced by proxygen::HTTPSession::setupCodec().
                                                  {
    return false;
  }
virtual bool proxygen::HTTPCodec::supportsStreamFlowControl () const [inline], [virtual]
Returns true iff this codec supports per stream flow control
Reimplemented in proxygen::SPDYCodec , and proxygen::HTTPParallelCodec .
Definition at line 367 of file HTTPCodec.h.
Referenced by proxygen::HTTPSession::createTransaction(), and proxygen::HTTPSession::onNativeProtocolUpgradeImpl().
                                                 {
    return false;
  }
Member Data Documentation
const StreamID proxygen::HTTPCodec::MAX_STREAM_ID = 1u << 31 [static]
Definition at line 55 of file HTTPCodec.h.
Referenced by proxygen::SPDYCodec::addPriorityNodes(), and proxygen::SPDYCodec::onSynCommon().
const folly::Optional< HTTPCodec::ExAttributes > proxygen::HTTPCodec::NoExAttributes [static]
Initial value:
=
    folly::none
Definition at line 66 of file HTTPCodec.h.
Referenced by proxygen::checkForProtocolUpgrade(), proxygen::HTTPSession::newPushedTransaction(), proxygen::HTTPUpstreamSession::newTransaction(), proxygen::HTTPSession::onError(), proxygen::HTTPSession::onMessageBegin(), and proxygen::HTTPSession::onPushMessageBegin().
const folly::Optional< uint8_t > proxygen::HTTPCodec::NoPadding = folly::none [static]
Definition at line 53 of file HTTPCodec.h.
Referenced by proxygen::checkForProtocolUpgrade(), proxygen::HTTPSession::sendBody(), TEST(), and TEST_F().
const folly::Optional< HTTPCodec::StreamID > proxygen::HTTPCodec::NoStream [static]
Initial value:
=
    folly::none
Definition at line 51 of file HTTPCodec.h.
Referenced by proxygen::checkForProtocolUpgrade(), proxygen::HTTPTransaction::getControlStream(), proxygen::HTTPSession::newExTransaction(), proxygen::HTTPUpstreamSession::newTransaction(), proxygen::HTTPSession::onError(), proxygen::HTTPSession::onExMessageBegin(), proxygen::HTTPSession::onGoaway(), and proxygen::HTTPSession::onMessageBegin().
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/HTTPCodec.h
proxygen/lib/http/codec/CodecProtocol.cpp