proxygen::MockHTTPCodecCallback Class Reference
#include <MockHTTPCodec.h>
Public Member Functions
MOCK_METHOD2 (onMessageBegin, void(HTTPCodec::StreamID, HTTPMessage *))
MOCK_METHOD3 (onPushMessageBegin, void(HTTPCodec::StreamID, HTTPCodec::StreamID, HTTPMessage *))
MOCK_METHOD4 (onExMessageBegin, void(HTTPCodec::StreamID, HTTPCodec::StreamID, bool, HTTPMessage *))
MOCK_METHOD2 (onHeadersComplete, void(HTTPCodec::StreamID, std::shared_ptr< HTTPMessage >))
void onHeadersComplete (HTTPCodec::StreamID stream, std::unique_ptr< HTTPMessage > msg) override
MOCK_METHOD3 (onBody, void(HTTPCodec::StreamID, std::shared_ptr< folly::IOBuf >, uint8_t))
void onBody (HTTPCodec::StreamID stream, std::unique_ptr< folly::IOBuf > chain, uint16_t padding) override
MOCK_METHOD2 (onChunkHeader, void(HTTPCodec::StreamID, size_t))
MOCK_METHOD1 (onChunkComplete, void(HTTPCodec::StreamID))
MOCK_METHOD2 (onTrailersComplete, void(HTTPCodec::StreamID, std::shared_ptr< HTTPHeaders >))
void onTrailersComplete (HTTPCodec::StreamID stream, std::unique_ptr< HTTPHeaders > trailers) override
MOCK_METHOD2 (onMessageComplete, void(HTTPCodec::StreamID, bool))
MOCK_METHOD3 (onError, void(HTTPCodec::StreamID, std::shared_ptr< HTTPException >, bool))
void onError (HTTPCodec::StreamID stream, const HTTPException &exc, bool newStream) override
MOCK_METHOD5 (onFrameHeader, void(uint64_t, uint8_t, uint64_t, uint8_t, uint16_t))
MOCK_METHOD2 (onAbort, void(HTTPCodec::StreamID, ErrorCode))
MOCK_METHOD3 (onGoaway, void(uint64_t, ErrorCode, std::shared_ptr< folly::IOBuf >))
void onGoaway (uint64_t lastGoodStreamID, ErrorCode code, std::unique_ptr< folly::IOBuf > debugData) override
MOCK_METHOD1 (onPingRequest, void(uint64_t))
MOCK_METHOD1 (onPingReply, void(uint64_t))
MOCK_METHOD2 (onWindowUpdate, void(HTTPCodec::StreamID, uint32_t))
MOCK_METHOD1 (onSettings, void(const SettingsList &))
MOCK_METHOD0 (onSettingsAck, void())
MOCK_METHOD2 (onPriority, void(HTTPCodec::StreamID, const HTTPMessage::HTTPPriority &))
MOCK_METHOD2 (onCertificateRequest, void(uint16_t, std::shared_ptr< folly::IOBuf >))
void onCertificateRequest (uint16_t requestId, std::unique_ptr< folly::IOBuf > certRequestData) override
MOCK_METHOD2 (onCertificate, void(uint16_t, std::shared_ptr< folly::IOBuf >))
void onCertificate (uint16_t certId, std::unique_ptr< folly::IOBuf > certData) override
MOCK_METHOD4 (onNativeProtocolUpgrade, bool(HTTPCodec::StreamID, CodecProtocol, const std::string &, HTTPMessage &))
MOCK_METHOD4 (onGenerateFrameHeader, void(HTTPCodec::StreamID, uint8_t, uint64_t, uint16_t))
MOCK_CONST_METHOD0 (numOutgoingStreams, uint32_t())
MOCK_CONST_METHOD0 (numIncomingStreams, uint32_t())
Detailed Description
Definition at line 136 of file MockHTTPCodec.h.
Member Function Documentation
proxygen::MockHTTPCodecCallback::MOCK_CONST_METHOD0 (numOutgoingStreams , uint32_t())
proxygen::MockHTTPCodecCallback::MOCK_CONST_METHOD0 (numIncomingStreams , uint32_t())
proxygen::MockHTTPCodecCallback::MOCK_METHOD0 (onSettingsAck , void())
proxygen::MockHTTPCodecCallback::MOCK_METHOD1 (onChunkComplete , void(HTTPCodec::StreamID))
proxygen::MockHTTPCodecCallback::MOCK_METHOD1 (onPingRequest , void(uint64_t))
proxygen::MockHTTPCodecCallback::MOCK_METHOD1 (onPingReply , void(uint64_t))
proxygen::MockHTTPCodecCallback::MOCK_METHOD1 (onSettings , void(const SettingsList &))
proxygen::MockHTTPCodecCallback::MOCK_METHOD2 (onMessageBegin , void(HTTPCodec::StreamID, HTTPMessage *))
proxygen::MockHTTPCodecCallback::MOCK_METHOD2 (onHeadersComplete , void(HTTPCodec::StreamID, std::shared_ptr< HTTPMessage >))
proxygen::MockHTTPCodecCallback::MOCK_METHOD2 (onChunkHeader , void(HTTPCodec::StreamID, size_t))
proxygen::MockHTTPCodecCallback::MOCK_METHOD2 (onTrailersComplete , void(HTTPCodec::StreamID, std::shared_ptr< HTTPHeaders >))
proxygen::MockHTTPCodecCallback::MOCK_METHOD2 (onMessageComplete , void(HTTPCodec::StreamID, bool))
proxygen::MockHTTPCodecCallback::MOCK_METHOD2 (onAbort , void(HTTPCodec::StreamID, ErrorCode))
proxygen::MockHTTPCodecCallback::MOCK_METHOD2 (onWindowUpdate , void(HTTPCodec::StreamID, uint32_t))
proxygen::MockHTTPCodecCallback::MOCK_METHOD2 (onPriority , void(HTTPCodec::StreamID, const HTTPMessage::HTTPPriority &))
proxygen::MockHTTPCodecCallback::MOCK_METHOD2 (onCertificateRequest , void(uint16_t, std::shared_ptr< folly::IOBuf >))
proxygen::MockHTTPCodecCallback::MOCK_METHOD2 (onCertificate , void(uint16_t, std::shared_ptr< folly::IOBuf >))
proxygen::MockHTTPCodecCallback::MOCK_METHOD3 (onPushMessageBegin , void(HTTPCodec::StreamID, HTTPCodec::StreamID, HTTPMessage *))
proxygen::MockHTTPCodecCallback::MOCK_METHOD3 (onBody , void(HTTPCodec::StreamID, std::shared_ptr< folly::IOBuf >, uint8_t))
proxygen::MockHTTPCodecCallback::MOCK_METHOD3 (onError , void(HTTPCodec::StreamID, std::shared_ptr< HTTPException >, bool))
proxygen::MockHTTPCodecCallback::MOCK_METHOD3 (onGoaway , void(uint64_t, ErrorCode, std::shared_ptr< folly::IOBuf >))
proxygen::MockHTTPCodecCallback::MOCK_METHOD4 (onExMessageBegin , void(HTTPCodec::StreamID, HTTPCodec::StreamID, bool, HTTPMessage *))
proxygen::MockHTTPCodecCallback::MOCK_METHOD4 (onNativeProtocolUpgrade , bool(HTTPCodec::StreamID, CodecProtocol, const std::string &, HTTPMessage &))
proxygen::MockHTTPCodecCallback::MOCK_METHOD4 (onGenerateFrameHeader , void(HTTPCodec::StreamID, uint8_t, uint64_t, uint16_t))
proxygen::MockHTTPCodecCallback::MOCK_METHOD5 (onFrameHeader , void(uint64_t, uint8_t, uint64_t, uint8_t, uint16_t))
void proxygen::MockHTTPCodecCallback::onBody (HTTPCodec::StreamID stream, std::unique_ptr< folly::IOBuf > chain, uint16_t padding) [inline], [override], [virtual]
Called for each block of message body data
Parameters
stream The stream ID
chain One or more buffers of body data. The codec will remove any protocol framing, such as HTTP/1.1 chunk headers, from the buffers before calling this function.
padding Number of pad bytes that came with the data segment
Implements proxygen::HTTPCodec::Callback .
Definition at line 154 of file MockHTTPCodec.h.
References proxygen::MockHTTPCodec::MOCK_METHOD1(), and proxygen::MockHTTPCodec::MOCK_METHOD2().
                                                                          {
    onBody(stream, std::shared_ptr<folly::IOBuf>(chain.release()), padding);
  }
void proxygen::MockHTTPCodecCallback::onCertificate (uint16_t , std::unique_ptr< folly::IOBuf >) [inline], [override], [virtual]
Called upon receipt of an authenticator, for protocols that support secondary certificate authentication.
Parameters
certId The Cert-ID identifying this authenticator
authenticator The authenticator request
Note
Not all protocols support secondary certificate authentication. HTTP/2 does, but HTTP/1.1 doesn't.
Reimplemented from proxygen::HTTPCodec::Callback .
Definition at line 203 of file MockHTTPCodec.h.
References proxygen::MockHTTPCodec::MOCK_CONST_METHOD0(), and proxygen::MockHTTPCodec::MOCK_METHOD4().
                                                                  {
    onCertificate(certId, std::shared_ptr<folly::IOBuf>(certData.release()));
  }
void proxygen::MockHTTPCodecCallback::onCertificateRequest (uint16_t , std::unique_ptr< folly::IOBuf >) [inline], [override], [virtual]
Called upon receipt of a certificate request frame, for protocols that support secondary certificate authentication.
Parameters
requestId The Request-ID identifying the certificate request
authRequest The authenticator request
Note
Not all protocols support secondary certificate authentication. HTTP/2 does, but HTTP/1.1 doesn't.
Reimplemented from proxygen::HTTPCodec::Callback .
Definition at line 196 of file MockHTTPCodec.h.
References proxygen::MockHTTPCodec::MOCK_METHOD2().
                                                          {
    onCertificateRequest(
        requestId, std::shared_ptr<folly::IOBuf>(certRequestData.release()));
  }
void proxygen::MockHTTPCodecCallback::onError (HTTPCodec::StreamID stream, const HTTPException & error, bool newTxn) [inline], [override], [virtual]
Called when a parsing or protocol error has occurred
Parameters
stream The stream ID
error Description of the error
newTxn true if onMessageBegin has not been called for txn
Implements proxygen::HTTPCodec::Callback .
Definition at line 170 of file MockHTTPCodec.h.
References proxygen::MockHTTPCodec::MOCK_METHOD2(), proxygen::MockHTTPCodec::MOCK_METHOD3(), and proxygen::MockHTTPCodec::MOCK_METHOD5().
                                        {
    onError(stream,
            std::shared_ptr<HTTPException>(new HTTPException(exc)),
            newStream);
  }
void proxygen::MockHTTPCodecCallback::onGoaway (uint64_t , ErrorCode , std::unique_ptr< folly::IOBuf >) [inline], [override], [virtual]
Called upon receipt of a goaway.
Parameters
lastGoodStreamID Last successful stream created by the receiver
code The code the connection was aborted with
debugData The additional debug data for diagnostic purpose
Note
Not all protocols have goaways. SPDY does, but HTTP/1.1 doesn't.
Reimplemented from proxygen::HTTPCodec::Callback .
Definition at line 182 of file MockHTTPCodec.h.
References proxygen::MockHTTPCodec::MOCK_METHOD0(), proxygen::MockHTTPCodec::MOCK_METHOD1(), and proxygen::MockHTTPCodec::MOCK_METHOD2().
                                                              {
    onGoaway(lastGoodStreamID, code,
             std::shared_ptr<folly::IOBuf>(debugData.release()));
  }
void proxygen::MockHTTPCodecCallback::onHeadersComplete (HTTPCodec::StreamID stream, std::unique_ptr< HTTPMessage > msg) [inline], [override], [virtual]
Called when all the headers of an ingress message have been parsed
Parameters
stream The stream ID
msg The message
size Size of the ingress header
Implements proxygen::HTTPCodec::Callback .
Definition at line 148 of file MockHTTPCodec.h.
References proxygen::MockHTTPCodec::MOCK_METHOD3().
                                                                  {
    onHeadersComplete(stream, std::shared_ptr<HTTPMessage>(msg.release()));
  }
void proxygen::MockHTTPCodecCallback::onTrailersComplete (HTTPCodec::StreamID stream, std::unique_ptr< HTTPHeaders > trailers) [inline], [override], [virtual]
Called when all the trailers of an ingress message have been parsed, but only if the number of trailers is nonzero.
Parameters
stream The stream ID
trailers The message trailers
Implements proxygen::HTTPCodec::Callback .
Definition at line 162 of file MockHTTPCodec.h.
References proxygen::MockHTTPCodec::MOCK_METHOD2(), and proxygen::MockHTTPCodec::MOCK_METHOD3().
                                                                        {
    onTrailersComplete(stream,
                       std::shared_ptr<HTTPHeaders>(trailers.release()));
  }
The documentation for this class was generated from the following file:
proxygen/lib/http/codec/test/MockHTTPCodec.h