proxygen::TTLBAStats Class Reference
#include <TTLBAStats.h>
Public Member Functions
virtual ~TTLBAStats () noexcept
virtual void recordTTLBAExceedLimit () noexcept=0
virtual void recordTTLBAIOBSplitByEom () noexcept=0
virtual void recordTTLBANotFound () noexcept=0
virtual void recordTTLBAReceived () noexcept=0
virtual void recordTTLBATimeout () noexcept=0
virtual void recordTTLBAEomPassed () noexcept=0
virtual void recordTTLBATracked () noexcept=0
Detailed Description
Definition at line 14 of file TTLBAStats.h.
Constructor & Destructor Documentation
virtual proxygen::TTLBAStats::~TTLBAStats () [inline], [virtual], [noexcept]
Definition at line 16 of file TTLBAStats.h.
References recordTTLBAEomPassed(), recordTTLBAExceedLimit(), recordTTLBAIOBSplitByEom(), recordTTLBANotFound(), recordTTLBAReceived(), recordTTLBATimeout(), and recordTTLBATracked().
{}
Member Function Documentation
virtual void proxygen::TTLBAStats::recordTTLBAEomPassed () [pure virtual], [noexcept]
Implemented in proxygen::DummyHTTPSessionStats .
Referenced by ~TTLBAStats().
virtual void proxygen::TTLBAStats::recordTTLBAExceedLimit () [pure virtual], [noexcept]
Implemented in proxygen::DummyHTTPSessionStats .
Referenced by ~TTLBAStats().
virtual void proxygen::TTLBAStats::recordTTLBAIOBSplitByEom () [pure virtual], [noexcept]
Implemented in proxygen::DummyHTTPSessionStats .
Referenced by proxygen::HTTPSession::getNextToSend(), and ~TTLBAStats().
virtual void proxygen::TTLBAStats::recordTTLBANotFound () [pure virtual], [noexcept]
Implemented in proxygen::DummyHTTPSessionStats .
Referenced by ~TTLBAStats().
virtual void proxygen::TTLBAStats::recordTTLBAReceived () [pure virtual], [noexcept]
Implemented in proxygen::DummyHTTPSessionStats .
Referenced by ~TTLBAStats().
virtual void proxygen::TTLBAStats::recordTTLBATimeout () [pure virtual], [noexcept]
Implemented in proxygen::DummyHTTPSessionStats .
Referenced by ~TTLBAStats().
virtual void proxygen::TTLBAStats::recordTTLBATracked () [pure virtual], [noexcept]
Implemented in proxygen::DummyHTTPSessionStats .
Referenced by ~TTLBAStats().
The documentation for this class was generated from the following file:
proxygen/lib/http/session/TTLBAStats.h