proxygen::RejectConnectFilter Class Reference
#include <RejectConnectFilter.h>
Public Member Functions
RejectConnectFilter (RequestHandler *upstream)
void onRequest (std::unique_ptr< HTTPMessage >) noexceptoverride
void onBody (std::unique_ptr< folly::IOBuf >) noexceptoverride
void onUpgrade (UpgradeProtocol) noexceptoverride
void onEOM () noexceptoverride
void requestComplete () noexceptoverride
void onError (ProxygenError err) noexceptoverride
void onEgressPaused () noexceptoverride
void onEgressResumed () noexceptoverride
void sendHeaders (HTTPMessage &) noexceptoverride
void sendChunkHeader (size_t) noexceptoverride
void sendBody (std::unique_ptr< folly::IOBuf >) noexceptoverride
void sendChunkTerminator () noexceptoverride
void sendEOM () noexceptoverride
void sendAbort () noexceptoverride
void refreshTimeout () noexceptoverride
Additional Inherited Members
Detailed Description
A filter that rejects CONNECT/UPGRADE requests.
Definition at line 21 of file RejectConnectFilter.h.
Constructor & Destructor Documentation
proxygen::RejectConnectFilter::RejectConnectFilter (RequestHandler * upstream) [inline], [explicit]
Definition at line 23 of file RejectConnectFilter.h.
Referenced by proxygen::RejectConnectFilterFactory::onRequest().
                                                        : Filter(upstream) {
  }
Member Function Documentation
void proxygen::RejectConnectFilter::onBody (std::unique_ptr< folly::IOBuf > body) [inline], [override], [virtual], [noexcept]
Invoked when we get part of body for the request.
Implements proxygen::RequestHandler .
Definition at line 33 of file RejectConnectFilter.h.
{}
void proxygen::RejectConnectFilter::onEgressPaused () [inline], [override], [virtual], [noexcept]
Signals from HTTP layer when client queue is full or empty. If you are sending a streaming response, consider implementing these and acting accordingly. Saves your server from running out of memory.
Reimplemented from proxygen::RequestHandler .
Definition at line 55 of file RejectConnectFilter.h.
                                          {
  }
void proxygen::RejectConnectFilter::onEgressResumed () [inline], [override], [virtual], [noexcept]
Reimplemented from proxygen::RequestHandler .
Definition at line 58 of file RejectConnectFilter.h.
                                           {
  }
void proxygen::RejectConnectFilter::onEOM () [inline], [override], [virtual], [noexcept]
Invoked when we finish receiving the body.
Implements proxygen::RequestHandler .
Definition at line 37 of file RejectConnectFilter.h.
                                 {
  }
void proxygen::RejectConnectFilter::onError (ProxygenError err) [inline], [override], [virtual], [noexcept]
Request failed. Maybe because of read/write error on socket or client not being able to send request in time.
NOTE: Can be invoked at any time (except for before onRequest).
No more callbacks will be invoked after this. You should clean up after yourself.
Implements proxygen::RequestHandler .
Definition at line 45 of file RejectConnectFilter.h.
References proxygen::RequestHandler::onError(), and proxygen::ResponseHandler::upstream_.
                                                    {
    // If onError is invoked before we forward the error
    if (upstream_) {
      upstream_->onError(err);
      upstream_ = nullptr;
    }
    delete this;
  }
void proxygen::RejectConnectFilter::onRequest (std::unique_ptr< HTTPMessage > headers) [inline], [override], [virtual], [noexcept]
Invoked when we have successfully fetched headers from client. This will always be the first callback invoked on your handler.
Implements proxygen::RequestHandler .
Definition at line 26 of file RejectConnectFilter.h.
References proxygen::RequestHandler::downstream_, proxygen::kErrorMethodNotSupported, proxygen::RequestHandler::onError(), proxygen::ResponseBuilder::rejectUpgradeRequest(), and proxygen::ResponseHandler::upstream_.
                                                                 {
    upstream_->onError(kErrorMethodNotSupported);
    upstream_ = nullptr;
    ResponseBuilder(downstream_).rejectUpgradeRequest();
  }
void proxygen::RejectConnectFilter::onUpgrade (UpgradeProtocol prot) [inline], [override], [virtual], [noexcept]
Invoked when the session has been upgraded to a different protocol
Implements proxygen::RequestHandler .
Definition at line 35 of file RejectConnectFilter.h.
{}
void proxygen::RejectConnectFilter::refreshTimeout () [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 77 of file RejectConnectFilter.h.
                                          {
  }
void proxygen::RejectConnectFilter::requestComplete () [inline], [override], [virtual], [noexcept]
Invoked when request processing has been completed and nothing more needs to be done. This may be a good place to log some stats and clean up resources. This is distinct from onEOM() because it is invoked after the response is fully sent. Once this callback has been received, downstream_ should be considered invalid.
Implements proxygen::RequestHandler .
Definition at line 40 of file RejectConnectFilter.h.
References proxygen::ResponseHandler::upstream_.
                                           {
    CHECK(!upstream_);
    delete this;
  }
void proxygen::RejectConnectFilter::sendAbort () [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 74 of file RejectConnectFilter.h.
                                     {
  }
void proxygen::RejectConnectFilter::sendBody (std::unique_ptr< folly::IOBuf >) [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 66 of file RejectConnectFilter.h.
{}
void proxygen::RejectConnectFilter::sendChunkHeader (size_t) [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 64 of file RejectConnectFilter.h.
{}
void proxygen::RejectConnectFilter::sendChunkTerminator () [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 68 of file RejectConnectFilter.h.
                                               {
  }
void proxygen::RejectConnectFilter::sendEOM () [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 71 of file RejectConnectFilter.h.
                                   {
  }
void proxygen::RejectConnectFilter::sendHeaders (HTTPMessage & msg) [inline], [override], [virtual], [noexcept]
NOTE: We take response message as non-const reference, to allow filters between your handler and client to be able to modify response if they want to.
eg. a compression filter might want to change the content-encoding
Implements proxygen::ResponseHandler .
Definition at line 62 of file RejectConnectFilter.h.
{}
The documentation for this class was generated from the following file:
proxygen/httpserver/filters/RejectConnectFilter.h