proxygen::HPACKEncoderBase Class Reference
#include <HPACKEncoderBase.h>
Public Member Functions
HPACKEncoderBase (bool huffman)
void setHeaderTableSize (HeaderTable &table, uint32_t size)
void setHeaderIndexingStrategy (const HeaderIndexingStrategy *indexingStrat)
const HeaderIndexingStrategy * getHeaderIndexingStrategy () const
Static Public Attributes
static const uint32_t kBufferGrowth = 4000
Protected Member Functions
uint32_t handlePendingContextUpdate (HPACKEncodeBuffer &buf, uint32_t tableCapacity)
Protected Attributes
const HeaderIndexingStrategy * indexingStrat_
HPACKEncodeBuffer streamBuffer_
bool pendingContextUpdate_ {false}
Detailed Description
Common encoder functionality between HPACK and QPACK
Definition at line 21 of file HPACKEncoderBase.h.
Constructor & Destructor Documentation
proxygen::HPACKEncoderBase::HPACKEncoderBase (bool huffman) [inline], [explicit]
Definition at line 24 of file HPACKEncoderBase.h.
References proxygen::HeaderIndexingStrategy::getDefaultInstance(), and indexingStrat_.
    : streamBuffer_(kBufferGrowth, huffman) {
    indexingStrat_ = HeaderIndexingStrategy::getDefaultInstance();
  }
Member Function Documentation
const HeaderIndexingStrategy* proxygen::HPACKEncoderBase::getHeaderIndexingStrategy () const [inline]
Definition at line 46 of file HPACKEncoderBase.h.
References handlePendingContextUpdate(), and indexingStrat_.
                                                                  {
    return indexingStrat_;
  }
uint32_t proxygen::HPACKEncoderBase::handlePendingContextUpdate (HPACKEncodeBuffer & buf, uint32_t tableCapacity) [protected]
Definition at line 14 of file HPACKEncoderBase.cpp.
References proxygen::HPACKEncodeBuffer::encodeInteger(), pendingContextUpdate_, proxygen::HPACK::Q_TABLE_SIZE_UPDATE, and proxygen::HPACK::TABLE_SIZE_UPDATE.
Referenced by proxygen::HPACKEncoder::encode(), proxygen::QPACKEncoder::encode(), and getHeaderIndexingStrategy().
                                                                              {
  CHECK_EQ(HPACK::TABLE_SIZE_UPDATE.code, HPACK::Q_TABLE_SIZE_UPDATE.code) <<
    "Code assumes these are equal";
  uint32_t encoded = 0;
  if (pendingContextUpdate_) {
    VLOG(5) << "Encoding table size update size=" << tableCapacity;
    encoded = buf.encodeInteger(tableCapacity, HPACK::TABLE_SIZE_UPDATE);
    pendingContextUpdate_ = false;
  }
  return encoded;
}
void proxygen::HPACKEncoderBase::setHeaderIndexingStrategy (const HeaderIndexingStrategy * indexingStrat) [inline]
Definition at line 43 of file HPACKEncoderBase.h.
References indexingStrat_.
Referenced by proxygen::QPACKEncoder::QPACKEncoder().
                                                                              {
    indexingStrat_ = indexingStrat;
  }
void proxygen::HPACKEncoderBase::setHeaderTableSize (HeaderTable & table, uint32_t size) [inline]
Definition at line 36 of file HPACKEncoderBase.h.
References proxygen::HeaderTable::capacity(), pendingContextUpdate_, and proxygen::HeaderTable::setCapacity().
Referenced by proxygen::HPACKEncoder::setHeaderTableSize(), and proxygen::QPACKEncoder::setHeaderTableSize().
                                                             {
    if (size != table.capacity()) {
      CHECK(table.setCapacity(size));
      pendingContextUpdate_ = true;
    }
  }
Member Data Documentation
const HeaderIndexingStrategy* proxygen::HPACKEncoderBase::indexingStrat_ [protected]
Definition at line 55 of file HPACKEncoderBase.h.
Referenced by proxygen::HPACKEncoder::encodeHeader(), getHeaderIndexingStrategy(), HPACKEncoderBase(), setHeaderIndexingStrategy(), and proxygen::QPACKEncoder::shouldIndex().
const uint32_t proxygen::HPACKEncoderBase::kBufferGrowth = 4000 [static]
Size of a new IOBuf which is added to the chain
jemalloc will round up to 4k - overhead
Definition at line 34 of file HPACKEncoderBase.h.
bool proxygen::HPACKEncoderBase::pendingContextUpdate_ {false} [protected]
Definition at line 57 of file HPACKEncoderBase.h.
Referenced by handlePendingContextUpdate(), and setHeaderTableSize().
HPACKEncodeBuffer proxygen::HPACKEncoderBase::streamBuffer_ [protected]
Definition at line 56 of file HPACKEncoderBase.h.
Referenced by proxygen::HPACKEncoder::encode(), proxygen::QPACKEncoder::encode(), proxygen::HPACKEncoder::encodeAsIndex(), proxygen::QPACKEncoder::encodeHeaderQ(), proxygen::HPACKEncoder::encodeLiteral(), proxygen::QPACKEncoder::encodeLiteralQ(), and proxygen::QPACKEncoder::encodeQ().
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/compress/HPACKEncoderBase.h
proxygen/lib/http/codec/compress/HPACKEncoderBase.cpp