shell_builder.ShellFBCodeBuilder Class Reference
Public Member Functions
def workdir (self, dir)
def run (self, shell_cmd)
def step (self, name, actions)
def setup (self)
def comment (self, comment)
def copy_local_repo (self, dir, dest_name)
Private Member Functions
def _render_impl (self, steps)
Additional Inherited Members
Detailed Description
Definition at line 32 of file shell_builder.py.
Member Function Documentation
def shell_builder.ShellFBCodeBuilder._render_impl (self, steps) [private]
Definition at line 33 of file shell_builder.py.
References shell_quoting.raw_shell(), utils.recursively_flatten_list(), and shell_quoting.shell_join().
Referenced by fbcode_builder.FBCodeBuilder.render().
    def _render_impl(self, steps):
        return raw_shell(shell_join('\n', recursively_flatten_list(steps)))
def shell_builder.ShellFBCodeBuilder.comment (self, comment)
Definition at line 66 of file shell_builder.py.
References shell_quoting.shell_comment().
Referenced by fbcode_builder.FBCodeBuilder.diagnostics().
    def comment(self, comment):
        return shell_comment(comment)
def shell_builder.ShellFBCodeBuilder.copy_local_repo (self, dir, dest_name)
Definition at line 69 of file shell_builder.py.
    def copy_local_repo(self, dir, dest_name):
        return [
            ShellQuoted('cp -r {dir} {dest_name}').format(
                dir=dir,
                dest_name=dest_name
            ),
        ]
def shell_builder.ShellFBCodeBuilder.run (self, shell_cmd)
Definition at line 43 of file shell_builder.py.
    def run(self, shell_cmd):
        return ShellQuoted('{cmd}').format(cmd=shell_cmd)
def shell_builder.ShellFBCodeBuilder.setup (self)
Definition at line 51 of file shell_builder.py.
References fbcode_builder.FBCodeBuilder.has_option(), and fbcode_builder.FBCodeBuilder.option().
    def setup(self):
        steps = [
            ShellQuoted('set -exo pipefail'),
        ]
        if self.has_option('ccache_dir'):
            ccache_dir = self.option('ccache_dir')
            steps += [
                ShellQuoted(
                    # Set CCACHE_DIR before the `ccache` invocations below.
                    'export CCACHE_DIR={ccache_dir} '
                    'CC="ccache ${{CC:-gcc}}" CXX="ccache ${{CXX:-g++}}"'
                ).format(ccache_dir=ccache_dir)
            ]
        return steps
def shell_builder.ShellFBCodeBuilder.step (self, name, actions)
Definition at line 46 of file shell_builder.py.
    def step(self, name, actions):
        assert '\n' not in name, 'Name {0} would span > 1 line'.format(name)
        b = ShellQuoted('')
        return [ShellQuoted('### {0} ###'.format(name)), b] + actions + [b]
def shell_builder.ShellFBCodeBuilder.workdir (self, dir)
Definition at line 36 of file shell_builder.py.
    def workdir(self, dir):
        return [
            ShellQuoted('mkdir -p {d} && cd {d}').format(
                d=dir
            ),
        ]
The documentation for this class was generated from the following file:
build/fbcode_builder/shell_builder.py