proxygen::Filter Class Reference
#include <Filters.h>
Public Member Functions
Filter (RequestHandler *upstream)
void setResponseHandler (ResponseHandler *handler) noexceptoverride
void onRequest (std::unique_ptr< HTTPMessage > headers) noexceptoverride
void onBody (std::unique_ptr< folly::IOBuf > body) noexceptoverride
void onUpgrade (UpgradeProtocol protocol) noexceptoverride
void onEOM () noexceptoverride
void requestComplete () noexceptoverride
void onError (ProxygenError err) noexceptoverride
void onEgressPaused () noexceptoverride
void onEgressResumed () noexceptoverride
bool canHandleExpect () noexceptoverride
ExMessageHandler * getExHandler () noexceptoverride
void sendHeaders (HTTPMessage &msg) noexceptoverride
void sendChunkHeader (size_t len) noexceptoverride
void sendBody (std::unique_ptr< folly::IOBuf > body) noexceptoverride
void sendChunkTerminator () noexceptoverride
void sendEOM () noexceptoverride
void sendAbort () noexceptoverride
void refreshTimeout () noexceptoverride
void pauseIngress () noexceptoverride
void resumeIngress () noexceptoverride
ResponseHandler * newPushedResponse (PushHandler *handler) noexceptoverride
const wangle::TransportInfo & getSetupTransportInfo () const noexceptoverride
void getCurrentTransportInfo (wangle::TransportInfo *tinfo) const override
Additional Inherited Members
Detailed Description
Filters are a way to add functionality to HTTPServer without complicating app specific RequestHandler. The basic idea is
App-handler <=> Filter-1 <=> Filter-2 <=> Client
The data flows through these filters between client and handler. They can do things like modify the data flowing through them, can update stats, create traces and even send direct response if they feel like.
The default implementation just lets everything pass through.
Definition at line 29 of file Filters.h.
Constructor & Destructor Documentation
proxygen::Filter::Filter (RequestHandler * upstream) [inline], [explicit]
Definition at line 31 of file Filters.h.
      : ResponseHandler(upstream) {
  }
Member Function Documentation
bool proxygen::Filter::canHandleExpect () [inline], [override], [virtual], [noexcept]
Returns true if the handler is responsible for responding to Expect headers, false otherwise.
Reimplemented from proxygen::RequestHandler .
Definition at line 79 of file Filters.h.
References proxygen::RequestHandler::canHandleExpect(), and proxygen::ResponseHandler::upstream_.
                                           {
    return upstream_->canHandleExpect();
  }
void proxygen::Filter::getCurrentTransportInfo (wangle::TransportInfo * tinfo) const [inline], [override], [virtual]
Implements proxygen::ResponseHandler .
Definition at line 132 of file Filters.h.
References proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::getCurrentTransportInfo().
                                                                          {
    downstream_->getCurrentTransportInfo(tinfo);
  }
ExMessageHandler* proxygen::Filter::getExHandler () [inline], [override], [virtual], [noexcept]
Implement in control stream handler to support incoming child EX streams.
Reimplemented from proxygen::RequestHandler .
Definition at line 83 of file Filters.h.
References proxygen::RequestHandler::getExHandler(), and proxygen::ResponseHandler::upstream_.
                                                     {
    return upstream_->getExHandler();
  }
const wangle::TransportInfo& proxygen::Filter::getSetupTransportInfo () const [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 128 of file Filters.h.
References proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::getSetupTransportInfo().
                                                                             {
    return downstream_->getSetupTransportInfo();
  }
ResponseHandler* proxygen::Filter::newPushedResponse (PushHandler * handler) [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 124 of file Filters.h.
References proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::newPushedResponse().
                                                                             {
    return downstream_->newPushedResponse(handler);
  }
void proxygen::Filter::onBody (std::unique_ptr< folly::IOBuf > body) [inline], [override], [virtual], [noexcept]
Invoked when we get part of body for the request.
Implements proxygen::RequestHandler .
Definition at line 47 of file Filters.h.
References proxygen::RequestHandler::onBody(), and proxygen::ResponseHandler::upstream_.
                                                                {
    upstream_->onBody(std::move(body));
  }
void proxygen::Filter::onEgressPaused () [inline], [override], [virtual], [noexcept]
Signals from HTTP layer when client queue is full or empty. If you are sending a streaming response, consider implementing these and acting accordingly. Saves your server from running out of memory.
Reimplemented from proxygen::RequestHandler .
Definition at line 71 of file Filters.h.
References proxygen::RequestHandler::onEgressPaused(), and proxygen::ResponseHandler::upstream_.
                                          {
    upstream_->onEgressPaused();
  }
void proxygen::Filter::onEgressResumed () [inline], [override], [virtual], [noexcept]
Reimplemented from proxygen::RequestHandler .
Definition at line 75 of file Filters.h.
References proxygen::RequestHandler::onEgressResumed(), and proxygen::ResponseHandler::upstream_.
                                           {
    upstream_->onEgressResumed();
  }
void proxygen::Filter::onEOM () [inline], [override], [virtual], [noexcept]
Invoked when we finish receiving the body.
Implements proxygen::RequestHandler .
Definition at line 55 of file Filters.h.
References proxygen::RequestHandler::onEOM(), and proxygen::ResponseHandler::upstream_.
                                 {
    upstream_->onEOM();
  }
void proxygen::Filter::onError (ProxygenError err) [inline], [override], [virtual], [noexcept]
Request failed. Maybe because of read/write error on socket or client not being able to send request in time.
NOTE: Can be invoked at any time (except for before onRequest).
No more callbacks will be invoked after this. You should clean up after yourself.
Implements proxygen::RequestHandler .
Definition at line 65 of file Filters.h.
References proxygen::RequestHandler::downstream_, proxygen::RequestHandler::onError(), and proxygen::ResponseHandler::upstream_.
                                                    {
    downstream_ = nullptr;
    upstream_->onError(err);
    delete this;
  }
void proxygen::Filter::onRequest (std::unique_ptr< HTTPMessage > headers) [inline], [override], [virtual], [noexcept]
Invoked when we have successfully fetched headers from client. This will always be the first callback invoked on your handler.
Implements proxygen::RequestHandler .
Definition at line 43 of file Filters.h.
References proxygen::RequestHandler::onRequest(), and proxygen::ResponseHandler::upstream_.
                                                                       {
    upstream_->onRequest(std::move(headers));
  }
void proxygen::Filter::onUpgrade (UpgradeProtocol prot) [inline], [override], [virtual], [noexcept]
Invoked when the session has been upgraded to a different protocol
Implements proxygen::RequestHandler .
Definition at line 51 of file Filters.h.
References proxygen::RequestHandler::onUpgrade(), and proxygen::ResponseHandler::upstream_.
                                                             {
    upstream_->onUpgrade(protocol);
  }
void proxygen::Filter::pauseIngress () [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 116 of file Filters.h.
References proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::pauseIngress().
                                        {
    downstream_->pauseIngress();
  }
void proxygen::Filter::refreshTimeout () [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 112 of file Filters.h.
References proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::refreshTimeout().
                                          {
    downstream_->refreshTimeout();
  }
void proxygen::Filter::requestComplete () [inline], [override], [virtual], [noexcept]
Invoked when request processing has been completed and nothing more needs to be done. This may be a good place to log some stats and clean up resources. This is distinct from onEOM() because it is invoked after the response is fully sent. Once this callback has been received, downstream_ should be considered invalid.
Implements proxygen::RequestHandler .
Definition at line 59 of file Filters.h.
References proxygen::RequestHandler::downstream_, proxygen::RequestHandler::requestComplete(), and proxygen::ResponseHandler::upstream_.
                                           {
    downstream_ = nullptr;
    upstream_->requestComplete();
    delete this;
  }
void proxygen::Filter::resumeIngress () [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 120 of file Filters.h.
References proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::resumeIngress().
                                         {
    downstream_->resumeIngress();
  }
void proxygen::Filter::sendAbort () [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 108 of file Filters.h.
References proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::sendAbort().
Referenced by proxygen::ZlibServerFilter::fail().
                                     {
    downstream_->sendAbort();
  }
void proxygen::Filter::sendBody (std::unique_ptr< folly::IOBuf > body) [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 96 of file Filters.h.
References proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::sendBody().
Referenced by proxygen::ZlibServerFilter::sendBody(), and proxygen::ZlibServerFilter::sendEOM().
                                                                  {
    downstream_->sendBody(std::move(body));
  }
void proxygen::Filter::sendChunkHeader (size_t len) [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 92 of file Filters.h.
References proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::sendChunkHeader().
Referenced by proxygen::ZlibServerFilter::sendBody(), proxygen::ZlibServerFilter::sendChunkHeader(), and proxygen::ZlibServerFilter::sendEOM().
                                                     {
    downstream_->sendChunkHeader(len);
  }
void proxygen::Filter::sendChunkTerminator () [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 100 of file Filters.h.
References proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::sendChunkTerminator().
Referenced by proxygen::ZlibServerFilter::sendEOM().
                                               {
    downstream_->sendChunkTerminator();
  }
void proxygen::Filter::sendEOM () [inline], [override], [virtual], [noexcept]
Implements proxygen::ResponseHandler .
Definition at line 104 of file Filters.h.
References proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::sendEOM().
Referenced by proxygen::ZlibServerFilter::sendEOM().
                                   {
    downstream_->sendEOM();
  }
void proxygen::Filter::sendHeaders (HTTPMessage & msg) [inline], [override], [virtual], [noexcept]
NOTE: We take response message as non-const reference, to allow filters between your handler and client to be able to modify response if they want to.
eg. a compression filter might want to change the content-encoding
Implements proxygen::ResponseHandler .
Definition at line 88 of file Filters.h.
References proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::sendHeaders().
Referenced by proxygen::ZlibServerFilter::sendBody(), and proxygen::ZlibServerFilter::sendHeaders().
                                                       {
    downstream_->sendHeaders(msg);
  }
void proxygen::Filter::setResponseHandler (ResponseHandler * handler) [inline], [override], [virtual], [noexcept]
Saves the downstream handle with itself. Implementations of this interface should use downstream_ to send back response.
XXX: Only override this method if you are ABSOLUTELY sure what you are doing. If possible, just use downstream_ variable and dont mess with these things.
Reimplemented from proxygen::RequestHandler .
Definition at line 36 of file Filters.h.
References proxygen::RequestHandler::downstream_, proxygen::RequestHandler::setResponseHandler(), proxygen::ResponseHandler::txn_, and proxygen::ResponseHandler::upstream_.
                                                                      {
    // Save downstream handler and pass ourselves as downstream handler
    downstream_ = handler;
    txn_ = handler->getTransaction();
    upstream_->setResponseHandler(this);
  }
The documentation for this class was generated from the following file:
proxygen/httpserver/Filters.h