proxygen::HTTPException Class Reference
#include <HTTPException.h>
Public Types
enum Direction { Direction::INGRESS = 0,
Direction::EGRESS,
Direction::INGRESS_AND_EGRESS
 }
Public Member Functions
HTTPException (Direction dir, const std::string &msg)
HTTPException (const HTTPException &ex)
std::string describe () const
Direction getDirection () const
bool isIngressException () const
bool isEgressException () const
bool hasHttpStatusCode () const
void setHttpStatusCode (uint32_t statusCode)
uint32_t getHttpStatusCode () const
bool hasCodecStatusCode () const
void setCodecStatusCode (ErrorCode statusCode)
ErrorCode getCodecStatusCode () const
bool hasErrno () const
void setErrno (uint32_t e)
uint32_t getErrno () const
void setCurrentIngressBuf (std::unique_ptr< folly::IOBuf > buf)
std::unique_ptr< folly::IOBuf > moveCurrentIngressBuf ()
void setPartialMsg (std::unique_ptr< HTTPMessage > partialMsg)
std::unique_ptr< HTTPMessage > movePartialMsg ()
Private Attributes
Direction dir_
uint32_t httpStatusCode_ {0}
folly::Optional< ErrorCode > codecStatusCode_
uint32_t errno_ {0}
std::unique_ptr< folly::IOBuf > currentIngressBuf_
std::unique_ptr< HTTPMessage > partialMsg_
Detailed Description
This class encapsulates the various errors that can occur on an http session. Errors can occur at various levels: the connection can be closed for reads and/or writes, the message body may fail to parse, or various protocol constraints may be violated.
Definition at line 26 of file HTTPException.h.
Member Enumeration Documentation
enum proxygen::HTTPException::Direction [strong]
Indicates which direction of the data flow was affected by this exception. For instance, if a class receives HTTPException(INGRESS), then it should consider ingress callbacks finished (whether or not the underlying transport actually shut down). Likewise for HTTPException(EGRESS), the class should consider the write stream shut down. INGRESS_AND_EGRESS indicates both directions are finished.
Enumerator
INGRESS
EGRESS
INGRESS_AND_EGRESS
Definition at line 36 of file HTTPException.h.
                       {
    INGRESS = 0,
    EGRESS,
    INGRESS_AND_EGRESS,
  };
Constructor & Destructor Documentation
proxygen::HTTPException::HTTPException (Direction dir, const std::string & msg) [inline], [explicit]
Definition at line 42 of file HTTPException.h.
      : Exception(msg),
        dir_(dir) {}
proxygen::HTTPException::HTTPException (const HTTPException & ex) [inline]
Definition at line 46 of file HTTPException.h.
References currentIngressBuf_, describe(), and partialMsg_.
                                         :
      Exception(static_cast<const Exception&>(ex)),
      dir_(ex.dir_),
      httpStatusCode_(ex.httpStatusCode_),
      codecStatusCode_(ex.codecStatusCode_),
      errno_(ex.errno_) {
    if (ex.currentIngressBuf_) {
      currentIngressBuf_ = ex.currentIngressBuf_->clone();
    }
    if (ex.partialMsg_) {
      partialMsg_ = std::make_unique<HTTPMessage>(*ex.partialMsg_.get());
    }
  }
Member Function Documentation
std::string proxygen::HTTPException::describe () const
Returns a string representation of this exception. This function is intended for debugging and logging only. For the true exception string, use what()
Definition at line 18 of file HTTPException.cpp.
Referenced by HTTPException().
                                        {
  std::stringstream ss;
  ss << *this;
  return ss.str();
}
ErrorCode proxygen::HTTPException::getCodecStatusCode () const [inline]
Definition at line 101 of file HTTPException.h.
References codecStatusCode_, and hasCodecStatusCode().
Referenced by proxygen::SimpleController::getParseErrorHandler(), proxygen::HTTPTransaction::onError(), proxygen::HTTPSession::onNewTransactionParseError(), proxygen::HTTPSession::onSessionParseError(), proxygen::operator<<(), and TEST_F().
                                       {
    CHECK(hasCodecStatusCode());
    return *codecStatusCode_;
  }
Direction proxygen::HTTPException::getDirection () const [inline]
Definition at line 67 of file HTTPException.h.
References dir_.
Referenced by proxygen::HTTPTransaction::onError(), proxygen::operator<<(), and TEST_F().
                                 {
    return dir_;
  }
uint32_t proxygen::HTTPException::getErrno () const [inline]
Definition at line 113 of file HTTPException.h.
References errno_.
                            {
    return errno_;
  }
uint32_t proxygen::HTTPException::getHttpStatusCode () const [inline]
Definition at line 90 of file HTTPException.h.
References httpStatusCode_.
Referenced by proxygen::SimpleController::getParseErrorHandler(), and proxygen::operator<<().
                                     {
    return httpStatusCode_;
  }
bool proxygen::HTTPException::hasCodecStatusCode () const [inline]
Definition at line 95 of file HTTPException.h.
References codecStatusCode_.
Referenced by getCodecStatusCode(), proxygen::SimpleController::getParseErrorHandler(), proxygen::HTTPTransaction::onError(), proxygen::HTTPSession::onNewTransactionParseError(), proxygen::HTTPSession::onSessionParseError(), proxygen::operator<<(), and TEST_F().
                                  {
    return codecStatusCode_.hasValue();
  }
bool proxygen::HTTPException::hasErrno () const [inline]
Definition at line 107 of file HTTPException.h.
References errno_.
                        {
    return (errno_ != 0);
  }
bool proxygen::HTTPException::hasHttpStatusCode () const [inline]
Definition at line 82 of file HTTPException.h.
References httpStatusCode_.
Referenced by proxygen::SimpleController::getParseErrorHandler().
                                 {
    return (httpStatusCode_ != 0);
  }
bool proxygen::HTTPException::isEgressException () const [inline]
Definition at line 76 of file HTTPException.h.
References dir_, EGRESS, and INGRESS_AND_EGRESS.
                                 {
    return dir_ == Direction::EGRESS ||
      dir_ == Direction::INGRESS_AND_EGRESS;
  }
bool proxygen::HTTPException::isIngressException () const [inline]
Definition at line 71 of file HTTPException.h.
References dir_, INGRESS, and INGRESS_AND_EGRESS.
                                  {
    return dir_ == Direction::INGRESS ||
      dir_ == Direction::INGRESS_AND_EGRESS;
  }
std::unique_ptr<folly::IOBuf> proxygen::HTTPException::moveCurrentIngressBuf () [inline]
Definition at line 121 of file HTTPException.h.
References currentIngressBuf_.
                                                    {
    return std::move(currentIngressBuf_);
  }
std::unique_ptr<HTTPMessage> proxygen::HTTPException::movePartialMsg () [inline]
Definition at line 129 of file HTTPException.h.
References partialMsg_.
                                              {
    return std::move(partialMsg_);
  }
void proxygen::HTTPException::setCodecStatusCode (ErrorCode statusCode) [inline]
Definition at line 98 of file HTTPException.h.
References codecStatusCode_, and statusCode.
Referenced by proxygen::HTTP2Codec::checkConnectionError(), proxygen::SPDYCodec::failSession(), proxygen::SPDYCodec::failStream(), proxygen::HTTPSession::invalidStream(), proxygen::HTTPSession::onAbort(), proxygen::HTTPSession::onHeadersComplete(), proxygen::HTTPTransaction::onIngressTimeout(), proxygen::HTTPSession::onMessageBegin(), proxygen::HTTPSession::onPushMessageBegin(), proxygen::HTTPTransaction::sendBodyNow(), proxygen::HTTP2Codec::streamError(), TEST(), and TEST_F().
                                                {
    codecStatusCode_ = statusCode;
  }
void proxygen::HTTPException::setCurrentIngressBuf (std::unique_ptr< folly::IOBuf > buf) [inline]
Definition at line 117 of file HTTPException.h.
References currentIngressBuf_.
Referenced by proxygen::SPDYCodec::failSession(), proxygen::SPDYCodec::failStream(), and proxygen::HTTP1xCodec::onParserError().
                                                           {
    currentIngressBuf_ = std::move(buf);
  }
void proxygen::HTTPException::setErrno (uint32_t e) [inline]
Definition at line 110 of file HTTPException.h.
References errno_.
                            {
    errno_ = e;
  }
void proxygen::HTTPException::setHttpStatusCode (uint32_t statusCode) [inline]
Definition at line 86 of file HTTPException.h.
References httpStatusCode_, and statusCode.
Referenced by proxygen::SPDYCodec::failStream(), proxygen::HTTPChecks::onHeadersComplete(), proxygen::HTTP1xCodec::onParserError(), and TEST_F().
                                              {
    httpStatusCode_ = statusCode;
  }
void proxygen::HTTPException::setPartialMsg (std::unique_ptr< HTTPMessage > partialMsg) [inline]
Definition at line 125 of file HTTPException.h.
References partialMsg_.
Referenced by proxygen::SPDYCodec::failStream(), and proxygen::HTTP1xCodec::onParserError().
                                                            {
    partialMsg_ = std::move(partialMsg);
  }
Member Data Documentation
folly::Optional<ErrorCode> proxygen::HTTPException::codecStatusCode_ [private]
Definition at line 137 of file HTTPException.h.
Referenced by getCodecStatusCode(), hasCodecStatusCode(), and setCodecStatusCode().
std::unique_ptr<folly::IOBuf> proxygen::HTTPException::currentIngressBuf_ [private]
Definition at line 140 of file HTTPException.h.
Referenced by HTTPException(), moveCurrentIngressBuf(), and setCurrentIngressBuf().
Direction proxygen::HTTPException::dir_ [private]
Definition at line 135 of file HTTPException.h.
Referenced by getDirection(), isEgressException(), and isIngressException().
uint32_t proxygen::HTTPException::errno_ {0} [private]
Definition at line 138 of file HTTPException.h.
Referenced by getErrno(), hasErrno(), and setErrno().
uint32_t proxygen::HTTPException::httpStatusCode_ {0} [private]
Definition at line 136 of file HTTPException.h.
Referenced by getHttpStatusCode(), hasHttpStatusCode(), and setHttpStatusCode().
std::unique_ptr<HTTPMessage> proxygen::HTTPException::partialMsg_ [private]
Definition at line 142 of file HTTPException.h.
Referenced by HTTPException(), movePartialMsg(), and setPartialMsg().
The documentation for this class was generated from the following files:
proxygen/lib/http/HTTPException.h
proxygen/lib/http/HTTPException.cpp