proxygen::HTTPChecks Class Reference
#include <HTTPChecks.h>
Public Member Functions
void onHeadersComplete (StreamID stream, std::unique_ptr< HTTPMessage > msg) override
void generateHeader (folly::IOBufQueue &writeBuf, StreamID stream, const HTTPMessage &msg, bool eom, HTTPHeaderSize *sizeOut) override
Additional Inherited Members
Detailed Description
This class enforces certain higher-level HTTP semantics. It does not enforce conditions that require state to decide. That is, this class is stateless and only examines the calls and callbacks that go through it.
Definition at line 22 of file HTTPChecks.h.
Member Function Documentation
void proxygen::HTTPChecks::generateHeader (folly::IOBufQueue & writeBuf, StreamID stream, const HTTPMessage & msg, bool eom, HTTPHeaderSize * sizeOut) [override]
Definition at line 35 of file HTTPChecks.cpp.
References proxygen::RFC2616::bodyImplied(), proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_, proxygen::HTTPMessage::getHeaders(), proxygen::HTTPMessage::getMethod(), proxygen::HTTPMessage::isRequest(), proxygen::RFC2616::isRequestBodyAllowed(), and proxygen::RFC2616::NOT_ALLOWED.
                                                         {
  if (msg.isRequest() && RFC2616::bodyImplied(msg.getHeaders())) {
    CHECK(RFC2616::isRequestBodyAllowed(msg.getMethod()) !=
          RFC2616::BodyAllowed::NOT_ALLOWED);
    // We could also add a "strict" mode that disallows sending body on GET
    // requests here too.
  }
  call_->generateHeader(writeBuf, stream, msg, eom, sizeOut);
}
void proxygen::HTTPChecks::onHeadersComplete (StreamID stream, std::unique_ptr< HTTPMessage > msg) [override]
Definition at line 16 of file HTTPChecks.cpp.
References proxygen::RFC2616::bodyImplied(), proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_, proxygen::HTTPException::INGRESS, proxygen::RFC2616::isRequestBodyAllowed(), proxygen::kErrorParseHeader, proxygen::RFC2616::NOT_ALLOWED, proxygen::HTTPException::setHttpStatusCode(), and proxygen::Exception::setProxygenError().
                                                                   {
  if (msg->isRequest() && (RFC2616::isRequestBodyAllowed(msg->getMethod())
                           == RFC2616::BodyAllowed::NOT_ALLOWED) &&
      RFC2616::bodyImplied(msg->getHeaders())) {
    HTTPException ex(
      HTTPException::Direction::INGRESS, "RFC2616: Request Body Not Allowed");
    ex.setProxygenError(kErrorParseHeader);
    // setting the status code means that the error is at the HTTP layer and
    // that parsing succeeded.
    ex.setHttpStatusCode(400);
    callback_->onError(stream, ex, true);
    return;
  }
  callback_->onHeadersComplete(stream, std::move(msg));
}
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/HTTPChecks.h
proxygen/lib/http/codec/HTTPChecks.cpp