proxygen::HTTPTransactionEgressSMData Class Reference
#include <HTTPTransactionEgressSM.h>
Public Types
enum State : uint8_t {
*
State::Start,
State::HeadersSent,
State::RegularBodySent,
State::ChunkHeaderSent,
*
State::ChunkBodySent,
State::ChunkTerminatorSent,
State::TrailersSent,
State::EOMQueued,
*
State::SendingDone
 }
enum Event : uint8_t {
*
Event::sendHeaders,
Event::sendBody,
Event::sendChunkHeader,
Event::sendChunkTerminator,
*
Event::sendTrailers,
Event::sendEOM,
Event::eomFlushed
 }
Static Public Member Functions
static State getInitialState ()
static std::pair< State, bool > find (State s, Event e)
static const std::string getName ()
Detailed Description
Definition at line 17 of file HTTPTransactionEgressSM.h.
Member Enumeration Documentation
enum proxygen::HTTPTransactionEgressSMData::Event : uint8_t [strong]
Enumerator
sendHeaders
sendBody
sendChunkHeader
sendChunkTerminator
sendTrailers
sendEOM
eomFlushed
Definition at line 32 of file HTTPTransactionEgressSM.h.
                  : uint8_t {
    // API accessible transitions
    sendHeaders,
    sendBody,
    sendChunkHeader,
    sendChunkTerminator,
    sendTrailers,
    sendEOM,
    // Internal state transitions
    eomFlushed,
  };
enum proxygen::HTTPTransactionEgressSMData::State : uint8_t [strong]
Enumerator
Start
HeadersSent
RegularBodySent
ChunkHeaderSent
ChunkBodySent
ChunkTerminatorSent
TrailersSent
EOMQueued
SendingDone
Definition at line 20 of file HTTPTransactionEgressSM.h.
                  : uint8_t {
    Start,
    HeadersSent,
    RegularBodySent,
    ChunkHeaderSent,
    ChunkBodySent,
    ChunkTerminatorSent,
    TrailersSent,
    EOMQueued,
    SendingDone
  };
Member Function Documentation
std::pair< HTTPTransactionEgressSMData::State, bool > proxygen::HTTPTransactionEgressSMData::find (HTTPTransactionEgressSMData::State s, HTTPTransactionEgressSMData::Event e) [static]
Definition at line 20 of file HTTPTransactionEgressSM.cpp.
References ChunkBodySent, ChunkHeaderSent, ChunkTerminatorSent, eomFlushed, EOMQueued, HeadersSent, RegularBodySent, sendBody, sendChunkHeader, sendChunkTerminator, sendEOM, sendHeaders, SendingDone, sendTrailers, Start, and TrailersSent.
Referenced by getInitialState().
                                                                      {
  using State = HTTPTransactionEgressSMData::State;
  using Event = HTTPTransactionEgressSMData::Event;
  using TransitionTable =
      std::unordered_map<std::pair<State, Event>, State, folly::Hash>;
  // +--> ChunkHeaderSent -> ChunkBodySent
  // | ^ v
  // | | ChunkTerminatorSent -> TrailersSent
  // | |__________| | |
  // | | v
  // Start -> HeadersSent +----> EOMQueued --> SendingDone
  // | ^
  // +------------> RegularBodySent -------+
  static const folly::Indestructible<TransitionTable> transitions{
    TransitionTable{
      {{State::Start, Event::sendHeaders}, State::HeadersSent},
      // For HTTP sending 100 response, then a regular response
      {{State::HeadersSent, Event::sendHeaders}, State::HeadersSent},
      {{State::HeadersSent, Event::sendBody}, State::RegularBodySent},
      {{State::HeadersSent, Event::sendTrailers}, State::TrailersSent},
      {{State::HeadersSent, Event::sendChunkHeader}, State::ChunkHeaderSent},
      {{State::HeadersSent, Event::sendEOM}, State::EOMQueued},
      {{State::RegularBodySent, Event::sendBody}, State::RegularBodySent},
      {{State::RegularBodySent, Event::sendTrailers}, State::TrailersSent},
      {{State::RegularBodySent, Event::sendEOM}, State::EOMQueued},
      {{State::ChunkHeaderSent, Event::sendBody}, State::ChunkBodySent},
      {{State::ChunkBodySent, Event::sendBody}, State::ChunkBodySent},
      {{State::ChunkBodySent, Event::sendChunkTerminator},
       State::ChunkTerminatorSent},
      {{State::ChunkTerminatorSent, Event::sendChunkHeader},
       State::ChunkHeaderSent},
      {{State::ChunkTerminatorSent, Event::sendTrailers}, State::TrailersSent},
      {{State::ChunkTerminatorSent, Event::sendEOM}, State::EOMQueued},
      {{State::TrailersSent, Event::sendEOM}, State::EOMQueued},
      {{State::EOMQueued, Event::eomFlushed}, State::SendingDone}
    }
  };
  auto const &it = transitions->find(std::make_pair(s, e));
  if (it == transitions->end()) {
    return std::make_pair(s, false);
  }
  return std::make_pair(it->second, true);
}
static State proxygen::HTTPTransactionEgressSMData::getInitialState () [inline], [static]
Definition at line 44 of file HTTPTransactionEgressSM.h.
References find(), and Start.
                                 {
    return State::Start;
  }
static const std::string proxygen::HTTPTransactionEgressSMData::getName () [inline], [static]
Definition at line 50 of file HTTPTransactionEgressSM.h.
References proxygen::operator<<().
                                   {
    return "HTTPTransactionEgress";
  }
The documentation for this class was generated from the following files:
proxygen/lib/http/session/HTTPTransactionEgressSM.h
proxygen/lib/http/session/HTTPTransactionEgressSM.cpp