HTTP2CodecTest Class Reference
Public Member Functions
HTTP2CodecTest ()
void SetUp () override
void testHeaderListSize (bool oversized)
void testFrameSizeLimit (bool oversized)
Protected Attributes
HTTP2Codec upstreamCodec_ {TransportDirection::UPSTREAM}
HTTP2Codec downstreamCodec_ {TransportDirection::DOWNSTREAM}
Detailed Description
Definition at line 48 of file HTTP2CodecTest.cpp.
Constructor & Destructor Documentation
HTTP2CodecTest::HTTP2CodecTest () [inline]
Definition at line 51 of file HTTP2CodecTest.cpp.
    :HTTPParallelCodecTest(upstreamCodec_, downstreamCodec_) {}
Member Function Documentation
void HTTP2CodecTest::SetUp () [inline], [override]
Definition at line 54 of file HTTP2CodecTest.cpp.
References HTTPParallelCodecTest::SetUp().
                        {
    HTTPParallelCodecTest::SetUp();
  }
void HTTP2CodecTest::testFrameSizeLimit (bool oversized)
Definition at line 530 of file HTTP2CodecTest.cpp.
References proxygen::getBigGetRequest(), proxygen::http2::kMaxFramePayloadLengthMin, proxygen::MAX_FRAME_SIZE, proxygen::parse(), and settings.
                                                      {
  HTTPMessage req = getBigGetRequest("/guacamole");
  auto settings = downstreamCodec_.getEgressSettings();
  parse(); // consume preface
  if (oversized) {
    // trick upstream for sending a 2x bigger HEADERS frame
    settings->setSetting(SettingsId::MAX_FRAME_SIZE,
                         http2::kMaxFramePayloadLengthMin * 2);
    downstreamCodec_.generateSettings(output_);
    parseUpstream();
  }
  settings->setSetting(SettingsId::MAX_FRAME_SIZE,
                       http2::kMaxFramePayloadLengthMin);
  upstreamCodec_.generateHeader(output_, 1, req, true /* eom */);
  parse();
  // session error
  EXPECT_EQ(callbacks_.messageBegin, oversized ? 0 : 1);
  EXPECT_EQ(callbacks_.headersComplete, oversized ? 0 : 1);
  EXPECT_EQ(callbacks_.messageComplete, oversized ? 0 : 1);
  EXPECT_EQ(callbacks_.streamErrors, 0);
  EXPECT_EQ(callbacks_.sessionErrors, oversized ? 1 : 0);
}
void HTTP2CodecTest::testHeaderListSize (bool oversized)
Definition at line 509 of file HTTP2CodecTest.cpp.
References proxygen::HTTPHeaders::add(), proxygen::getGetRequest(), proxygen::HTTPMessage::getHeaders(), proxygen::MAX_HEADER_LIST_SIZE, proxygen::parse(), and settings.
                                                      {
  if (oversized) {
    auto settings = downstreamCodec_.getEgressSettings();
    settings->setSetting(SettingsId::MAX_HEADER_LIST_SIZE, 37);
  }
  HTTPMessage req = getGetRequest("/guacamole");
  req.getHeaders().add(HTTP_HEADER_USER_AGENT, "coolio");
  req.getHeaders().add("x-long-long-header",
                       "supercalafragalisticexpialadoshus");
  upstreamCodec_.generateHeader(output_, 1, req, true /* eom */);
  parse();
  // session error
  EXPECT_EQ(callbacks_.messageBegin, oversized ? 0 : 1);
  EXPECT_EQ(callbacks_.headersComplete, oversized ? 0 : 1);
  EXPECT_EQ(callbacks_.messageComplete, oversized ? 0 : 1);
  EXPECT_EQ(callbacks_.streamErrors, 0);
  EXPECT_EQ(callbacks_.sessionErrors, oversized ? 1 : 0);
}
Member Data Documentation
HTTP2Codec HTTP2CodecTest::downstreamCodec_ {TransportDirection::DOWNSTREAM} [protected]
Definition at line 62 of file HTTP2CodecTest.cpp.
HTTP2Codec HTTP2CodecTest::upstreamCodec_ {TransportDirection::UPSTREAM} [protected]
Definition at line 61 of file HTTP2CodecTest.cpp.
The documentation for this class was generated from the following file:
proxygen/lib/http/codec/test/HTTP2CodecTest.cpp