ProxyService::ProxyHandler Class Reference
#include <ProxyHandler.h>
Classes
class ServerTransactionHandler
Public Member Functions
ProxyHandler (ProxyStats *stats, folly::HHWheelTimer *timer)
~ProxyHandler () override
void onRequest (std::unique_ptr< proxygen::HTTPMessage > headers) noexceptoverride
void onBody (std::unique_ptr< folly::IOBuf > body) noexceptoverride
void onEOM () noexceptoverride
void onUpgrade (proxygen::UpgradeProtocol) noexceptoverride
void requestComplete () noexceptoverride
void onError (proxygen::ProxygenError err) noexceptoverride
void onEgressPaused () noexceptoverride
void onEgressResumed () noexceptoverride
void detachServerTransaction () noexcept
void onServerHeadersComplete (std::unique_ptr< proxygen::HTTPMessage > msg) noexcept
void onServerBody (std::unique_ptr< folly::IOBuf > chain) noexcept
void onServerEOM () noexcept
void onServerError (const proxygen::HTTPException &error) noexcept
void onServerEgressPaused () noexcept
void onServerEgressResumed () noexcept
Private Member Functions
void connectSuccess (proxygen::HTTPUpstreamSession *session) override
void connectError (const folly::AsyncSocketException &ex) override
void connectSuccess () noexceptoverride
void connectErr (const folly::AsyncSocketException &ex) noexceptoverride
void getReadBuffer (void **bufReturn, size_t *lenReturn) override
void readDataAvailable (size_t len) noexceptoverride
void readEOF () noexceptoverride
void readErr (const folly::AsyncSocketException &ex) noexceptoverride
void writeSuccess () noexceptoverride
void writeErr (size_t bytesWritten, const folly::AsyncSocketException &ex) noexceptoverride
void abortDownstream ()
bool checkForShutdown ()
Private Attributes
ProxyStats *const stats_ {nullptr}
proxygen::HTTPConnector connector_
ServerTransactionHandler serverHandler_
std::unique_ptr< SessionWrapper > session_
proxygen::HTTPTransaction * txn_ {nullptr}
bool clientTerminated_ {false}
std::unique_ptr< proxygen::HTTPMessage > request_
std::shared_ptr< folly::AsyncSocket > upstreamSock_
uint8_t sockStatus_ {0}
folly::IOBufQueue body_ {folly::IOBufQueue::cacheChainLength()}
bool downstreamIngressPaused_ {false}
bool upstreamEgressPaused_ {false}
Additional Inherited Members
Detailed Description
Definition at line 26 of file ProxyHandler.h.
Constructor & Destructor Documentation
ProxyService::ProxyHandler::ProxyHandler (ProxyStats * stats, folly::HHWheelTimer * timer)
Definition at line 39 of file ProxyHandler.cpp.
References serverHandler_.
                                                                     :
    stats_(stats),
    connector_{this, timer},
    serverHandler_(*this) {
}
ProxyService::ProxyHandler::~ProxyHandler () [override]
Definition at line 45 of file ProxyHandler.cpp.
                            {
  VLOG(4) << "deleting ProxyHandler";
}
Member Function Documentation
void ProxyService::ProxyHandler::abortDownstream () [private]
Definition at line 218 of file ProxyHandler.cpp.
References clientTerminated_, proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::sendAbort().
Referenced by connectError(), onServerError(), readErr(), and writeErr().
                                   {
  if (!clientTerminated_) {
    downstream_->sendAbort();
  }
}
bool ProxyService::ProxyHandler::checkForShutdown () [private]
Definition at line 224 of file ProxyHandler.cpp.
References clientTerminated_, sockStatus_, txn_, upstreamEgressPaused_, and upstreamSock_.
Referenced by connectError(), detachServerTransaction(), onError(), readErr(), requestComplete(), writeErr(), and writeSuccess().
                                    {
  if (clientTerminated_ && !txn_ &&
      (!upstreamSock_ || (sockStatus_ == CLOSED && !upstreamEgressPaused_))) {
    delete this;
    return true;
  }
  return false;
}
void ProxyService::ProxyHandler::connectErr (const folly::AsyncSocketException & ex) [override], [private], [noexcept]
Definition at line 242 of file ProxyHandler.cpp.
References connectError().
                                                                          {
  connectError(ex);
}
void ProxyService::ProxyHandler::connectError (const folly::AsyncSocketException & ex) [override], [private], [virtual]
Implements proxygen::HTTPConnector::Callback .
Definition at line 130 of file ProxyHandler.cpp.
References abortDownstream(), checkForShutdown(), clientTerminated_, proxygen::RequestHandler::downstream_, proxygen::ERROR, proxygen::ResponseBuilder::sendWithEOM(), and proxygen::ResponseBuilder::status().
Referenced by connectErr().
                                                                   {
  LOG(ERROR) << "Failed to connect: " << folly::exceptionStr(ex);
  if (!clientTerminated_) {
    ResponseBuilder(downstream_)
      .status(503, "Bad Gateway")
      .sendWithEOM();
  } else {
    abortDownstream();
    checkForShutdown();
  }
}
void ProxyService::ProxyHandler::connectSuccess (proxygen::HTTPUpstreamSession * session) [override], [private], [virtual]
Implements proxygen::HTTPConnector::Callback .
Definition at line 120 of file ProxyHandler.cpp.
References proxygen::RequestHandler::downstream_, proxygen::HTTPUpstreamSession::newTransaction(), request_, proxygen::ResponseHandler::resumeIngress(), serverHandler_, session_, and txn_.
                                                              {
  LOG(INFO) << "Established " << *session;
  session_ = std::make_unique<SessionWrapper>(session);
  txn_ = session->newTransaction(&serverHandler_);
  LOG(INFO) << "Forwarding client request: " << request_->getURL()
            << " to server";
  txn_->sendHeaders(*request_);
  downstream_->resumeIngress();
}
void ProxyService::ProxyHandler::connectSuccess () [override], [private], [noexcept]
Definition at line 233 of file ProxyHandler.cpp.
References proxygen::RequestHandler::downstream_, proxygen::ResponseHandler::resumeIngress(), proxygen::ResponseBuilder::send(), proxygen::ResponseBuilder::status(), and upstreamSock_.
                                           {
  LOG(INFO) << "Connected to upstream " << upstreamSock_;
  ResponseBuilder(downstream_)
    .status(200, "OK")
    .send();
  upstreamSock_->setReadCB(this);
  downstream_->resumeIngress();
}
void ProxyService::ProxyHandler::detachServerTransaction () [noexcept]
Definition at line 163 of file ProxyHandler.cpp.
References checkForShutdown(), and txn_.
Referenced by ProxyService::ProxyHandler::ServerTransactionHandler::detachTransaction().
                                                    {
  txn_ = nullptr;
  checkForShutdown();
}
void ProxyService::ProxyHandler::getReadBuffer (void ** bufReturn, size_t * lenReturn) [override], [private]
Definition at line 246 of file ProxyHandler.cpp.
References body_.
                                                                    {
  std::pair<void*,uint32_t> readSpace = body_.preallocate(kMinReadSize,
                                                          kMaxReadSize);
  *bufReturn = readSpace.first;
  *lenReturn = readSpace.second;
}
void ProxyService::ProxyHandler::onBody (std::unique_ptr< folly::IOBuf > body) [override], [virtual], [noexcept]
Invoked when we get part of body for the request.
Implements proxygen::RequestHandler .
Definition at line 89 of file ProxyHandler.cpp.
References downstreamIngressPaused_, onServerEgressPaused(), proxygen::HTTPTransaction::sendBody(), txn_, upstreamEgressPaused_, and upstreamSock_.
                                                                 {
  if (txn_) {
    LOG(INFO) << "Forwarding " <<
      ((body) ? body->computeChainDataLength() : 0) << " body bytes to server";
    txn_->sendBody(std::move(body));
  } else if (upstreamSock_) {
    upstreamEgressPaused_ = true;
    upstreamSock_->writeChain(this, std::move(body));
    if (upstreamEgressPaused_) {
      downstreamIngressPaused_ = true;
      onServerEgressPaused();
    }
  } else {
    LOG(WARNING) << "Dropping " <<
      ((body) ? body->computeChainDataLength() : 0) << " body bytes to server";
  }
}
void ProxyService::ProxyHandler::onEgressPaused () [override], [virtual], [noexcept]
Signals from HTTP layer when client queue is full or empty. If you are sending a streaming response, consider implementing these and acting accordingly. Saves your server from running out of memory.
Reimplemented from proxygen::RequestHandler .
Definition at line 202 of file ProxyHandler.cpp.
References proxygen::HTTPTransaction::pauseIngress(), txn_, and upstreamSock_.
                                           {
  if (txn_) {
    txn_->pauseIngress();
  } else if (upstreamSock_) {
    upstreamSock_->setReadCB(nullptr);
  }
}
void ProxyService::ProxyHandler::onEgressResumed () [override], [virtual], [noexcept]
Reimplemented from proxygen::RequestHandler .
Definition at line 210 of file ProxyHandler.cpp.
References proxygen::HTTPTransaction::resumeIngress(), txn_, and upstreamSock_.
                                            {
  if (txn_) {
    txn_->resumeIngress();
  } else if (upstreamSock_) {
    upstreamSock_->setReadCB(this);
  }
}
void ProxyService::ProxyHandler::onEOM () [override], [virtual], [noexcept]
Invoked when we finish receiving the body.
Implements proxygen::RequestHandler .
Definition at line 107 of file ProxyHandler.cpp.
References proxygen::HTTPTransaction::sendEOM(), sockStatus_, txn_, and upstreamSock_.
                                  {
  if (txn_) {
    LOG(INFO) << "Forwarding client EOM to server";
    txn_->sendEOM();
  } else if (upstreamSock_) {
    LOG(INFO) << "Closing upgraded socket";
    sockStatus_ |= WRITES_SHUTDOWN;
    upstreamSock_->shutdownWrite();
  } else {
    LOG(INFO) << "Dropping client EOM to server";
  }
}
void ProxyService::ProxyHandler::onError (proxygen::ProxygenError err) [override], [virtual], [noexcept]
Request failed. Maybe because of read/write error on socket or client not being able to send request in time.
NOTE: Can be invoked at any time (except for before onRequest).
No more callbacks will be invoked after this. You should clean up after yourself.
Implements proxygen::RequestHandler .
Definition at line 190 of file ProxyHandler.cpp.
References checkForShutdown(), clientTerminated_, proxygen::ERROR, proxygen::getErrorString(), proxygen::HTTPTransaction::sendAbort(), txn_, and upstreamSock_.
                                                     {
  LOG(ERROR) << "Client error: " << proxygen::getErrorString(err);
  clientTerminated_ = true;
  if (txn_) {
    LOG(ERROR) << "Aborting server txn: " << *txn_;
    txn_->sendAbort();
  } else if (upstreamSock_) {
    upstreamSock_.reset();
  }
  checkForShutdown();
}
void ProxyService::ProxyHandler::onRequest (std::unique_ptr< proxygen::HTTPMessage > headers) [override], [virtual], [noexcept]
Invoked when we have successfully fetched headers from client. This will always be the first callback invoked on your handler.
Implements proxygen::RequestHandler .
Definition at line 49 of file ProxyHandler.cpp.
References proxygen::ResponseBuilder::body(), proxygen::HTTPConnector::connect(), connector_, proxygen::RequestHandler::downstream_, proxygen::ResponseHandler::pauseIngress(), ProxyService::ProxyStats::recordRequest(), request_, proxygen::ResponseBuilder::sendWithEOM(), stats_, proxygen::ResponseBuilder::status(), and upstreamSock_.
                                                                        {
  // This HTTP proxy does not obey the rules in the spec, such as stripping
  // hop-by-hop headers. Example only!
  stats_->recordRequest();
  request_ = std::move(headers);
  proxygen::URL url(request_->getURL());
  folly::SocketAddress addr;
  try {
    // Note, this does a synchronous DNS lookup which is bad in event driven
    // code
    addr.setFromHostPort(url.getHost(), url.getPort());
  } catch (...) {
    ResponseBuilder(downstream_)
      .status(503, "Bad Gateway")
      .body(folly::to<string>("Could not parse server from URL: ",
                              request_->getURL()))
      .sendWithEOM();
    return;
  }
  downstream_->pauseIngress();
  LOG(INFO) << "Trying to connect to " << addr;
  auto evb = folly::EventBaseManager::get()->getEventBase();
  if (request_->getMethod() == HTTPMethod::CONNECT) {
    upstreamSock_ = folly::AsyncSocket::newSocket(evb);
    upstreamSock_->connect(this, addr, FLAGS_proxy_connect_timeout);
  } else {
    // A more sophisticated proxy would have a connection pool here
    const folly::AsyncSocket::OptionMap opts{
      {{SOL_SOCKET, SO_REUSEADDR}, 1}};
    downstream_->pauseIngress();
    connector_.connect(folly::EventBaseManager::get()->getEventBase(), addr,
                       std::chrono::milliseconds(FLAGS_proxy_connect_timeout),
                       opts);
  }
}
void ProxyService::ProxyHandler::onServerBody (std::unique_ptr< folly::IOBuf > chain) [noexcept]
Definition at line 149 of file ProxyHandler.cpp.
References clientTerminated_, proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::sendBody().
Referenced by ProxyService::ProxyHandler::ServerTransactionHandler::onBody().
                                                                        {
  CHECK(!clientTerminated_);
  LOG(INFO) << "Forwarding " <<
    ((chain) ? chain->computeChainDataLength() : 0) << " body bytes to client";
  downstream_->sendBody(std::move(chain));
}
void ProxyService::ProxyHandler::onServerEgressPaused () [noexcept]
Definition at line 173 of file ProxyHandler.cpp.
References clientTerminated_, proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::pauseIngress().
Referenced by onBody(), and ProxyService::ProxyHandler::ServerTransactionHandler::onEgressPaused().
                                                 {
  if (!clientTerminated_) {
    downstream_->pauseIngress();
  }
}
void ProxyService::ProxyHandler::onServerEgressResumed () [noexcept]
Definition at line 179 of file ProxyHandler.cpp.
References clientTerminated_, proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::resumeIngress().
Referenced by ProxyService::ProxyHandler::ServerTransactionHandler::onEgressResumed(), and writeSuccess().
                                                  {
  if (!clientTerminated_) {
    downstream_->resumeIngress();
  }
}
void ProxyService::ProxyHandler::onServerEOM () [noexcept]
Definition at line 156 of file ProxyHandler.cpp.
References clientTerminated_, proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::sendEOM().
Referenced by ProxyService::ProxyHandler::ServerTransactionHandler::onEOM(), and readEOF().
                                        {
  if (!clientTerminated_) {
    LOG(INFO) << "Forwarding server EOM to client";
    downstream_->sendEOM();
  }
}
void ProxyService::ProxyHandler::onServerError (const proxygen::HTTPException & error) [noexcept]
Definition at line 168 of file ProxyHandler.cpp.
References abortDownstream(), and proxygen::ERROR.
Referenced by ProxyService::ProxyHandler::ServerTransactionHandler::onError().
                                                                    {
  LOG(ERROR) << "Server error: " << error;
  abortDownstream();
}
void ProxyService::ProxyHandler::onServerHeadersComplete (std::unique_ptr< proxygen::HTTPMessage > msg) [noexcept]
Definition at line 142 of file ProxyHandler.cpp.
References clientTerminated_, proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::sendHeaders().
Referenced by ProxyService::ProxyHandler::ServerTransactionHandler::onHeadersComplete().
                                        {
  CHECK(!clientTerminated_);
  LOG(INFO) << "Forwarding " << msg->getStatusCode() << " response to client";
  downstream_->sendHeaders(*msg);
}
void ProxyService::ProxyHandler::onUpgrade (proxygen::UpgradeProtocol prot) [inline], [override], [virtual], [noexcept]
Invoked when the session has been upgraded to a different protocol
Implements proxygen::RequestHandler .
Definition at line 43 of file ProxyHandler.h.
{}
void ProxyService::ProxyHandler::readDataAvailable (size_t len) [override], [private], [noexcept]
Definition at line 253 of file ProxyHandler.cpp.
References body_, proxygen::RequestHandler::downstream_, and proxygen::ResponseHandler::sendBody().
                                                        {
  body_.postallocate(len);
  downstream_->sendBody(body_.move());
}
void ProxyService::ProxyHandler::readEOF () [override], [private], [noexcept]
Definition at line 258 of file ProxyHandler.cpp.
References onServerEOM(), and sockStatus_.
                                    {
  sockStatus_ |= READS_SHUTDOWN;
  onServerEOM();
}
void ProxyService::ProxyHandler::readErr (const folly::AsyncSocketException & ex) [override], [private], [noexcept]
Definition at line 263 of file ProxyHandler.cpp.
References abortDownstream(), checkForShutdown(), proxygen::ERROR, and upstreamSock_.
                                                                       {
  LOG(ERROR) << "Server read error: " << folly::exceptionStr(ex);
  abortDownstream();
  upstreamSock_.reset();
  checkForShutdown();
}
void ProxyService::ProxyHandler::requestComplete () [override], [virtual], [noexcept]
Invoked when request processing has been completed and nothing more needs to be done. This may be a good place to log some stats and clean up resources. This is distinct from onEOM() because it is invoked after the response is fully sent. Once this callback has been received, downstream_ should be considered invalid.
Implements proxygen::RequestHandler .
Definition at line 185 of file ProxyHandler.cpp.
References checkForShutdown(), and clientTerminated_.
                                            {
  clientTerminated_ = true;
  checkForShutdown();
}
void ProxyService::ProxyHandler::writeErr (size_t bytesWritten, const folly::AsyncSocketException & ex) [override], [private], [noexcept]
Definition at line 279 of file ProxyHandler.cpp.
References abortDownstream(), checkForShutdown(), proxygen::ERROR, upstreamEgressPaused_, and upstreamSock_.
                                                                          {
  LOG(ERROR) << "Server write error: " << folly::exceptionStr(ex);;
  upstreamEgressPaused_ = false;
  abortDownstream();
  upstreamSock_.reset();
  checkForShutdown();
}
void ProxyService::ProxyHandler::writeSuccess () [override], [private], [noexcept]
Definition at line 270 of file ProxyHandler.cpp.
References checkForShutdown(), downstreamIngressPaused_, onServerEgressResumed(), and upstreamEgressPaused_.
                                         {
  upstreamEgressPaused_ = false;
  if (downstreamIngressPaused_) {
    downstreamIngressPaused_ = false;
    onServerEgressResumed();
  }
  checkForShutdown();
}
Member Data Documentation
folly::IOBufQueue ProxyService::ProxyHandler::body_ {folly::IOBufQueue::cacheChainLength()} [private]
Definition at line 142 of file ProxyHandler.h.
Referenced by getReadBuffer(), and readDataAvailable().
bool ProxyService::ProxyHandler::clientTerminated_ {false} [private]
Definition at line 135 of file ProxyHandler.h.
Referenced by abortDownstream(), checkForShutdown(), connectError(), onError(), onServerBody(), onServerEgressPaused(), onServerEgressResumed(), onServerEOM(), onServerHeadersComplete(), and requestComplete().
proxygen::HTTPConnector ProxyService::ProxyHandler::connector_ [private]
Definition at line 131 of file ProxyHandler.h.
Referenced by onRequest().
bool ProxyService::ProxyHandler::downstreamIngressPaused_ {false} [private]
Definition at line 143 of file ProxyHandler.h.
Referenced by onBody(), and writeSuccess().
std::unique_ptr<proxygen::HTTPMessage> ProxyService::ProxyHandler::request_ [private]
Definition at line 137 of file ProxyHandler.h.
Referenced by connectSuccess(), and onRequest().
ServerTransactionHandler ProxyService::ProxyHandler::serverHandler_ [private]
Definition at line 132 of file ProxyHandler.h.
Referenced by connectSuccess(), and ProxyHandler().
std::unique_ptr<SessionWrapper> ProxyService::ProxyHandler::session_ [private]
Definition at line 133 of file ProxyHandler.h.
Referenced by connectSuccess().
uint8_t ProxyService::ProxyHandler::sockStatus_ {0} [private]
Definition at line 141 of file ProxyHandler.h.
Referenced by checkForShutdown(), onEOM(), and readEOF().
ProxyStats* const ProxyService::ProxyHandler::stats_ {nullptr} [private]
Definition at line 130 of file ProxyHandler.h.
Referenced by onRequest().
proxygen::HTTPTransaction* ProxyService::ProxyHandler::txn_ {nullptr} [private]
Definition at line 134 of file ProxyHandler.h.
Referenced by checkForShutdown(), connectSuccess(), detachServerTransaction(), onBody(), onEgressPaused(), onEgressResumed(), onEOM(), and onError().
bool ProxyService::ProxyHandler::upstreamEgressPaused_ {false} [private]
Definition at line 144 of file ProxyHandler.h.
Referenced by checkForShutdown(), onBody(), writeErr(), and writeSuccess().
std::shared_ptr<folly::AsyncSocket> ProxyService::ProxyHandler::upstreamSock_ [private]
Definition at line 140 of file ProxyHandler.h.
Referenced by checkForShutdown(), connectSuccess(), onBody(), onEgressPaused(), onEgressResumed(), onEOM(), onError(), onRequest(), readErr(), and writeErr().
The documentation for this class was generated from the following files:
proxygen/httpserver/samples/proxy/ProxyHandler.h
proxygen/httpserver/samples/proxy/ProxyHandler.cpp