proxygen::HTTPSettings Class Reference
#include <HTTPSettings.h>
Public Member Functions
HTTPSettings ()
HTTPSettings (const std::initializer_list< SettingPair > &initialSettings)
void setSetting (SettingsId id, SettingsValue val)
void unsetSetting (SettingsId id)
const HTTPSetting * getSetting (SettingsId id) const
SettingsValue getSetting (SettingsId id, SettingsValue defaultVal) const
std::size_t getNumSettings () const
const std::vector< HTTPSetting > & getAllSettings ()
void clearSettings ()
Private Member Functions
std::vector< HTTPSetting >::iterator getSettingIter (SettingsId id)
std::vector< HTTPSetting >::const_iterator getSettingConstIter (SettingsId id) const
Private Attributes
std::vector< HTTPSetting > settings_
Detailed Description
Definition at line 35 of file HTTPSettings.h.
Constructor & Destructor Documentation
proxygen::HTTPSettings::HTTPSettings () [inline]
Definition at line 38 of file HTTPSettings.h.
References proxygen::ENABLE_PUSH, proxygen::HEADER_TABLE_SIZE, and proxygen::MAX_FRAME_SIZE.
      : settings_({{SettingsId::HEADER_TABLE_SIZE, 4096},
                   {SettingsId::ENABLE_PUSH, 1},
                   {SettingsId::MAX_FRAME_SIZE, 16384}}) {
  }
proxygen::HTTPSettings::HTTPSettings (const std::initializer_list< SettingPair > & initialSettings) [inline], [explicit]
Definition at line 43 of file HTTPSettings.h.
                                                               {
    settings_.reserve(initialSettings.size());
    // TODO: setSetting involves looping over all settings so the below actually
    // models as O(n^2) which is pretty bad. Can't change it outright without
    // making sure we handle duplicates (same setting id)
    for (auto& setting : initialSettings) {
      setSetting(setting.first, setting.second);
    }
  }
Member Function Documentation
void proxygen::HTTPSettings::clearSettings () [inline]
Definition at line 64 of file HTTPSettings.h.
                       {
    settings_.clear();
  }
const std::vector<HTTPSetting>& proxygen::HTTPSettings::getAllSettings () [inline]
Definition at line 61 of file HTTPSettings.h.
Referenced by proxygen::SPDYCodec::generateSettings(), and proxygen::HTTP2Codec::generateSettings().
                                                 {
    return settings_;
  }
std::size_t proxygen::HTTPSettings::getNumSettings () const [inline]
Definition at line 58 of file HTTPSettings.h.
Referenced by proxygen::SPDYCodec::generateSettings(), and TEST().
                                   {
    return settings_.size();
  }
const HTTPSetting * proxygen::HTTPSettings::getSetting (SettingsId id) const
Definition at line 33 of file HTTPSettings.cpp.
References getSettingConstIter(), and settings_.
Referenced by proxygen::HTTP2Codec::encodeHeaders(), proxygen::HTTPSession::getCodecSendWindowSize(), proxygen::HTTP2Codec::handleSettings(), proxygen::HTTP2Codec::HTTP2Codec(), proxygen::HTTP2Codec::maxRecvFrameSize(), proxygen::HTTP2Codec::maxSendFrameSize(), proxygen::SPDYCodec::onSettings(), proxygen::SPDYCodec::onSynStream(), proxygen::HTTP2Codec::parseFrame(), proxygen::HTTP2Codec::parseHeadersCheckConcurrentStreams(), proxygen::HTTP2Codec::parsePushPromise(), proxygen::HTTP2Codec::peerHasWebsockets(), proxygen::HTTP2Codec::supportsExTransactions(), proxygen::HTTP2Codec::supportsPushTransactions(), TEST(), and TEST_F().
                                                               {
  auto iter = getSettingConstIter(id);
  if (iter != settings_.end()) {
    return &(*iter);
  } else {
    return nullptr;
  }
}
SettingsValue proxygen::HTTPSettings::getSetting (SettingsId id, SettingsValue defaultVal) const
Definition at line 42 of file HTTPSettings.cpp.
References getSettingConstIter(), and settings_.
                                                                         {
  auto iter = getSettingConstIter(id);
  if (iter != settings_.end()) {
    return (*iter).value;
  } else {
    return defaultValue;
  }
}
std::vector< HTTPSetting >::const_iterator proxygen::HTTPSettings::getSettingConstIter (SettingsId id) const [private]
Definition at line 58 of file HTTPSettings.cpp.
References settings_.
Referenced by getSetting().
                         {
  return std::find_if(settings_.begin(),
                      settings_.end(),
                      [&](HTTPSetting const& s) { return s.id == id; });
}
std::vector< HTTPSetting >::iterator proxygen::HTTPSettings::getSettingIter (SettingsId id) [private]
Definition at line 52 of file HTTPSettings.cpp.
References settings_.
Referenced by setSetting(), and unsetSetting().
                                                                         {
  return std::find_if(settings_.begin(),
                      settings_.end(),
                      [&](HTTPSetting const& s) { return s.id == id; });
}
void proxygen::HTTPSettings::setSetting (SettingsId id, SettingsValue val)
Definition at line 16 of file HTTPSettings.cpp.
References getSettingIter(), and settings_.
Referenced by proxygen::HTTPSessionBase::enableExHeadersSettings(), proxygen::HTTP2Codec::handleSettings(), HTTPDownstreamTest< SPDY3_1CodecPair >::HTTPDownstreamTest(), proxygen::HTTPSession::onNativeProtocolUpgradeImpl(), proxygen::SPDYCodec::onSettings(), proxygen::HTTPSession::setEgressSettings(), proxygen::HTTPSession::setFlowControl(), proxygen::HTTPSession::setMaxConcurrentIncomingStreams(), proxygen::HTTPSession::setupCodec(), TEST(), and TEST_F().
                                                              {
  auto iter = getSettingIter(id);
  if (iter != settings_.end()) {
    (*iter).value = val;
  } else {
    settings_.emplace_back(id, val);
  }
}
void proxygen::HTTPSettings::unsetSetting (SettingsId id)
Definition at line 25 of file HTTPSettings.cpp.
References getSettingIter(), and settings_.
Referenced by TEST().
                                             {
  auto iter = getSettingIter(id);
  if (iter != settings_.end()) {
    *iter = settings_.back();
    settings_.pop_back();
  }
}
Member Data Documentation
std::vector<HTTPSetting> proxygen::HTTPSettings::settings_ [private]
Definition at line 78 of file HTTPSettings.h.
Referenced by getSetting(), getSettingConstIter(), getSettingIter(), setSetting(), and unsetSetting().
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/HTTPSettings.h
proxygen/lib/http/codec/HTTPSettings.cpp