TestAsyncTransport::WriteEvent Class Reference
#include <TestAsyncTransport.h>
Public Member Functions
proxygen::TimePoint getTime () const
const struct iovec * getIoVec () const
size_t getCount () const
Static Public Member Functions
static std::shared_ptr< WriteEvent > newEvent (const struct iovec *vec, size_t count)
Private Member Functions
WriteEvent (proxygen::TimePoint time, size_t count)
~WriteEvent ()
Static Private Member Functions
static void destroyEvent (WriteEvent *event)
Private Attributes
proxygen::TimePoint time_
size_t count_
struct iovec vec_ []
Detailed Description
Definition at line 22 of file TestAsyncTransport.h.
Constructor & Destructor Documentation
TestAsyncTransport::WriteEvent::WriteEvent (proxygen::TimePoint time, size_t count) [private]
Definition at line 111 of file TestAsyncTransport.cpp.
References count_, and vec_.
Referenced by getCount(), and newEvent().
  : time_(time),
    count_(count) {
  // Initialize all of the iov_base pointers to nullptr. This way we won't free
  // an uninitialized pointer in the destructor if we fail to allocate any of
  // the buffers.
  for (size_t n = 0; n < count_; ++n) {
    vec_[n].iov_base = nullptr;
  }
}
TestAsyncTransport::WriteEvent::~WriteEvent () [private]
Definition at line 122 of file TestAsyncTransport.cpp.
References count_, and vec_.
Referenced by getCount().
                                          {
  for (size_t n = 0; n < count_; ++n) {
    free(vec_[n].iov_base);
  }
}
Member Function Documentation
void TestAsyncTransport::WriteEvent::destroyEvent (WriteEvent * event) [static], [private]
Definition at line 159 of file TestAsyncTransport.cpp.
References TestAsyncTransport::eventBase_, TestAsyncTransport::kStateOpen, TestAsyncTransport::readCallback_, TestAsyncTransport::readEvents_, TestAsyncTransport::readState_, TestAsyncTransport::sendTimeout_, TestAsyncTransport::TestAsyncTransport(), and TestAsyncTransport::writeState_.
Referenced by getCount(), and newEvent().
                                                            {
  event->~WriteEvent();
  free(event);
}
size_t TestAsyncTransport::WriteEvent::getCount () const [inline]
Definition at line 33 of file TestAsyncTransport.h.
References count_, destroyEvent(), WriteEvent(), and ~WriteEvent().
                            {
      return count_;
    }
const struct iovec* TestAsyncTransport::WriteEvent::getIoVec () const [inline]
Definition at line 30 of file TestAsyncTransport.h.
References vec_.
                                         {
      return vec_;
    }
proxygen::TimePoint TestAsyncTransport::WriteEvent::getTime () const [inline]
Definition at line 27 of file TestAsyncTransport.h.
References time_.
                                      {
      return time_;
    }
shared_ptr< TestAsyncTransport::WriteEvent > TestAsyncTransport::WriteEvent::newEvent (const struct iovec * vec, size_t count) [static]
Definition at line 129 of file TestAsyncTransport.cpp.
References destroyEvent(), proxygen::getCurrentTime(), and WriteEvent().
Referenced by TestAsyncTransport::writev().
                                                       {
  size_t bufLen = sizeof(WriteEvent) + (count * sizeof(struct iovec));
  void* buf = malloc(bufLen);
  if (buf == nullptr) {
    throw std::bad_alloc();
  }
  auto now = proxygen::getCurrentTime();
  shared_ptr<WriteEvent> event(new(buf) WriteEvent(now, count),
                               destroyEvent);
  for (size_t n = 0; n < count; ++n) {
    size_t len = vec[n].iov_len;
    event->vec_[n].iov_len = len;
    if (len == 0) {
      event->vec_[n].iov_base = nullptr;
      continue;
    }
    event->vec_[n].iov_base = malloc(len);
    if (event->vec_[n].iov_base == nullptr) {
      throw std::bad_alloc();
    }
    memcpy(event->vec_[n].iov_base, vec[n].iov_base, len);
  }
  return event;
}
Member Data Documentation
size_t TestAsyncTransport::WriteEvent::count_ [private]
Definition at line 44 of file TestAsyncTransport.h.
Referenced by getCount(), WriteEvent(), and ~WriteEvent().
proxygen::TimePoint TestAsyncTransport::WriteEvent::time_ [private]
Definition at line 43 of file TestAsyncTransport.h.
Referenced by getTime().
struct iovec TestAsyncTransport::WriteEvent::vec_[] [private]
Definition at line 45 of file TestAsyncTransport.h.
Referenced by getIoVec(), WriteEvent(), and ~WriteEvent().
The documentation for this class was generated from the following files:
proxygen/lib/test/TestAsyncTransport.h
proxygen/lib/test/TestAsyncTransport.cpp