proxygen::HeaderIndexingStrategy Class Reference
#include <HeaderIndexingStrategy.h>
Public Member Functions
HeaderIndexingStrategy ()
virtual ~HeaderIndexingStrategy ()
virtual bool indexHeader (const HPACKHeader &header) const
Static Public Member Functions
static const HeaderIndexingStrategy * getDefaultInstance ()
Detailed Description
Definition at line 16 of file HeaderIndexingStrategy.h.
Constructor & Destructor Documentation
proxygen::HeaderIndexingStrategy::HeaderIndexingStrategy () [inline]
Definition at line 24 of file HeaderIndexingStrategy.h.
Referenced by getDefaultInstance().
{}
virtual proxygen::HeaderIndexingStrategy::~HeaderIndexingStrategy () [inline], [virtual]
Definition at line 25 of file HeaderIndexingStrategy.h.
References indexHeader().
{}
Member Function Documentation
const HeaderIndexingStrategy * proxygen::HeaderIndexingStrategy::getDefaultInstance () [static]
Definition at line 14 of file HeaderIndexingStrategy.cpp.
References HeaderIndexingStrategy().
Referenced by proxygen::HPACKEncoderBase::HPACKEncoderBase(), and proxygen::QPACKEncoder::QPACKEncoder().
                                                                         {
  static const HeaderIndexingStrategy* instance = new HeaderIndexingStrategy();
  return instance;
}
bool proxygen::HeaderIndexingStrategy::indexHeader (const HPACKHeader & header) const [virtual]
Reimplemented in proxygen::NoPathIndexingStrategy .
Definition at line 19 of file HeaderIndexingStrategy.cpp.
References proxygen::HPACKHeaderName::getHeaderCode(), proxygen::HTTP_HEADER_NONE, proxygen::HPACKHeader::name, and proxygen::HPACKHeader::value.
Referenced by proxygen::HPACKEncoder::encodeHeader(), proxygen::NoPathIndexingStrategy::indexHeader(), proxygen::QPACKEncoder::shouldIndex(), TEST_F(), and ~HeaderIndexingStrategy().
                                                                        {
  // Handle all the cases where we want to return false in the switch statement
  // below; else let the code fall through and return true
  switch(header.name.getHeaderCode()) {
    case HTTP_HEADER_COLON_PATH:
      if (header.value.find('=') != std::string::npos) {
        return false;
      }
      if (header.value.find("jpg") != std::string::npos) {
        return false;
      }
      break;
    // The wrapped header should never be HTTP_HEADER_NONE but for completeness
    // the condition is included below
    case HTTP_HEADER_NONE:
    case HTTP_HEADER_CONTENT_LENGTH:
    case HTTP_HEADER_IF_MODIFIED_SINCE:
    case HTTP_HEADER_LAST_MODIFIED:
      return false;
    default:
      break;
  }
  return true;
}
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/compress/HeaderIndexingStrategy.h
proxygen/lib/http/codec/compress/HeaderIndexingStrategy.cpp