proxygen::HPACKCodec Class Reference
#include <HPACKCodec.h>
Public Member Functions
HPACKCodec (TransportDirection direction)
~HPACKCodec () override
std::unique_ptr< folly::IOBuf > encode (std::vector< compress::Header > &headers) noexcept
void decodeStreaming (folly::io::Cursor &cursor, uint32_t length, HPACK::StreamingCallback *streamingCb) noexcept
void setEncoderHeaderTableSize (uint32_t size)
void setDecoderHeaderTableMaxSize (uint32_t size)
void describe (std::ostream &os) const
void setMaxUncompressed (uint64_t maxUncompressed) override
CompressionInfo getCompressionInfo () const
void setHeaderIndexingStrategy (const HeaderIndexingStrategy *indexingStrat)
const HeaderIndexingStrategy * getHeaderIndexingStrategy () const
Protected Attributes
HPACKEncoder encoder_
HPACKDecoder decoder_
Private Member Functions
void recordCompressedSize (const folly::IOBuf *buf)
Private Attributes
std::vector< HPACKHeader > decodedHeaders_
Additional Inherited Members
Detailed Description
Definition at line 41 of file HPACKCodec.h.
Constructor & Destructor Documentation
proxygen::HPACKCodec::HPACKCodec (TransportDirection direction) [explicit]
Definition at line 44 of file HPACKCodec.cpp.
    : encoder_(true, HPACK::kTableSize),
      decoder_(HPACK::kTableSize, maxUncompressed_) {}
proxygen::HPACKCodec::~HPACKCodec () [inline], [override]
Definition at line 44 of file HPACKCodec.h.
References encode().
{}
Member Function Documentation
void proxygen::HPACKCodec::decodeStreaming (folly::io::Cursor & cursor, uint32_t length, HPACK::StreamingCallback * streamingCb) [noexcept]
Definition at line 67 of file HPACKCodec.cpp.
References decoder_, proxygen::HPACKDecoder::decodeStreaming(), and proxygen::HeaderCodec::stats_.
Referenced by proxygen::HPACKQueue::decodeBlock(), isLowercase(), and proxygen::HTTP2Codec::parseHeadersDecodeFrames().
                                                  {
  streamingCb->stats = stats_;
  decoder_.decodeStreaming(cursor, length, streamingCb);
}
void proxygen::HPACKCodec::describe (std::ostream & os) const
Definition at line 75 of file HPACKCodec.cpp.
References decoder_, and encoder_.
Referenced by proxygen::operator<<().
                                                  {
  stream << "DecoderTable:\n" << decoder_;
  stream << "EncoderTable:\n" << encoder_;
}
unique_ptr< IOBuf > proxygen::HPACKCodec::encode (std::vector< compress::Header > & headers) [noexcept]
Definition at line 48 of file HPACKCodec.cpp.
References proxygen::HPACKEncoder::encode(), proxygen::HeaderCodec::encodedSize_, proxygen::HeaderCodec::encodeHeadroom_, encoder_, proxygen::compress::prepareHeaders(), and recordCompressedSize().
Referenced by proxygen::compress::HPACKScheme::encode(), proxygen::HTTP2Codec::encodeHeaders(), isLowercase(), and TEST_F().
                                                                     {
  auto prepared = compress::prepareHeaders(headers);
  encodedSize_.uncompressed = prepared.second;
  auto buf = encoder_.encode(prepared.first, encodeHeadroom_);
  recordCompressedSize(buf.get());
  return buf;
}
CompressionInfo proxygen::HPACKCodec::getCompressionInfo () const [inline]
Definition at line 69 of file HPACKCodec.h.
Referenced by proxygen::HTTP2Codec::getCompressionInfo().
                                             {
    return CompressionInfo(encoder_.getTableSize(),
                           encoder_.getBytesStored(),
                           encoder_.getHeadersStored(),
                           decoder_.getTableSize(),
                           decoder_.getBytesStored(),
                           decoder_.getHeadersStored());
  }
const HeaderIndexingStrategy* proxygen::HPACKCodec::getHeaderIndexingStrategy () const [inline]
Definition at line 81 of file HPACKCodec.h.
Referenced by proxygen::HTTP2Codec::getHeaderIndexingStrategy().
                                                                  {
    return encoder_.getHeaderIndexingStrategy();
  }
void proxygen::HPACKCodec::recordCompressedSize (const folly::IOBuf * buf) [private]
Definition at line 56 of file HPACKCodec.cpp.
References proxygen::HeaderCodec::encodedSize_, proxygen::HeaderCodec::HPACK, proxygen::HeaderCodec::Stats::recordEncode(), and proxygen::HeaderCodec::stats_.
Referenced by encode().
                       {
  encodedSize_.compressed = 0;
  if (stream) {
    encodedSize_.compressed += stream->computeChainDataLength();
  }
  if (stats_) {
    stats_->recordEncode(Type::HPACK, encodedSize_);
  }
}
void proxygen::HPACKCodec::setDecoderHeaderTableMaxSize (uint32_t size) [inline]
Definition at line 58 of file HPACKCodec.h.
Referenced by proxygen::HTTP2Codec::handleSettingsAck(), and proxygen::compress::HPACKScheme::HPACKScheme().
                                                   {
    decoder_.setHeaderTableMaxSize(size);
  }
void proxygen::HPACKCodec::setEncoderHeaderTableSize (uint32_t size) [inline]
Definition at line 54 of file HPACKCodec.h.
Referenced by proxygen::HTTP2Codec::handleSettings(), and proxygen::compress::HPACKScheme::HPACKScheme().
                                                {
    encoder_.setHeaderTableSize(size);
  }
void proxygen::HPACKCodec::setHeaderIndexingStrategy (const HeaderIndexingStrategy * indexingStrat) [inline]
Definition at line 78 of file HPACKCodec.h.
Referenced by proxygen::compress::HPACKScheme::HPACKScheme(), and proxygen::HTTP2Codec::setHeaderIndexingStrategy().
                                                                              {
    encoder_.setHeaderIndexingStrategy(indexingStrat);
  }
void proxygen::HPACKCodec::setMaxUncompressed (uint64_t maxUncompressed) [inline], [override], [virtual]
Reimplemented from proxygen::HeaderCodec .
Definition at line 64 of file HPACKCodec.h.
Referenced by proxygen::HTTP2Codec::generateSettings(), and proxygen::HTTP2Codec::HTTP2Codec().
                                                             {
    HeaderCodec::setMaxUncompressed(maxUncompressed);
    decoder_.setMaxUncompressed(maxUncompressed);
  }
Member Data Documentation
std::vector<HPACKHeader> proxygen::HPACKCodec::decodedHeaders_ [private]
Definition at line 92 of file HPACKCodec.h.
HPACKDecoder proxygen::HPACKCodec::decoder_ [protected]
Definition at line 87 of file HPACKCodec.h.
Referenced by decodeStreaming(), and describe().
HPACKEncoder proxygen::HPACKCodec::encoder_ [protected]
Definition at line 86 of file HPACKCodec.h.
Referenced by describe(), and encode().
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/compress/HPACKCodec.h
proxygen/lib/http/codec/compress/HPACKCodec.cpp