proxygen::RFC1867Codec::Callback Class Reference
#include <RFC1867.h>
Public Member Functions
virtual ~Callback ()
virtual int onFieldStart (const std::string &name, folly::Optional< std::string > filename, std::unique_ptr< HTTPMessage > msg, uint64_t postBytesProcessed)=0
virtual int onFieldData (std::unique_ptr< folly::IOBuf >, uint64_t postBytesProcessed)=0
virtual void onFieldEnd (bool endedOnBoundary, uint64_t postBytesProcessed)=0
virtual void onError ()=0
Detailed Description
Definition at line 27 of file RFC1867.h.
Constructor & Destructor Documentation
virtual proxygen::RFC1867Codec::Callback::~Callback () [inline], [virtual]
Definition at line 29 of file RFC1867.h.
References name, onError(), onFieldData(), onFieldEnd(), and onFieldStart().
{}
Member Function Documentation
virtual void proxygen::RFC1867Codec::Callback::onError () [pure virtual]
Referenced by ~Callback().
virtual int proxygen::RFC1867Codec::Callback::onFieldData (std::unique_ptr< folly::IOBuf > , uint64_t postBytesProcessed) [pure virtual]
Implemented in proxygen::Mock1867Callback .
Referenced by ~Callback().
virtual void proxygen::RFC1867Codec::Callback::onFieldEnd (bool endedOnBoundary, uint64_t postBytesProcessed) [pure virtual]
On reading to end of a part indicated by boundary
Parameters
endedOnBoundary indicate successful part end
Referenced by ~Callback().
virtual int proxygen::RFC1867Codec::Callback::onFieldStart (const std::string & name, folly::Optional< std::string > filename, std::unique_ptr< HTTPMessage > msg, uint64_t postBytesProcessed) [pure virtual]
Referenced by ~Callback().
The documentation for this class was generated from the following file:
proxygen/lib/http/experimental/RFC1867.h