proxygen::URL Class Reference
#include <URL.h>
Public Member Functions
URL (const std::string &url=``) noexcept
URL (const std::string scheme, const std::string host, uint16_t port=0, const std::string path=``, const std::string query=``, const std::string fragment=``) noexcept
bool isValid () const noexcept
const std::string & getUrl () const noexcept
uint16_t getPort () const noexcept
const std::string & getScheme () const noexcept
bool isSecure () const noexcept
bool hasHost () const noexcept
const std::string & getHost () const noexcept
std::string getHostAndPort () const noexcept
const std::string & getPath () const noexcept
const std::string & getQuery () const noexcept
const std::string & getFragment () const noexcept
std::string makeRelativeURL () const noexcept
Static Public Member Functions
static std::string createUrl (const std::string &scheme, const std::string &hostAndPort, const std::string &path, const std::string &query, const std::string &fragment) noexcept
Private Attributes
std::string scheme_
std::string host_
uint16_t port_
std::string path_
std::string query_
std::string fragment_
std::string url_
bool valid_ {false}
Friends
bool operator== (const URL &lhs, const URL &rhs)
bool operator!= (const URL &lhs, const URL &rhs)
Detailed Description
Struct representing a URL.
Definition at line 22 of file URL.h.
Constructor & Destructor Documentation
proxygen::URL::URL (const std::string & url = ``) [inline], [explicit], [noexcept]
Definition at line 24 of file URL.h.
References proxygen::ParseURL::fragment(), fragment_, host_, proxygen::ParseURL::hostNoBrackets(), isSecure(), proxygen::ParseURL::path(), path_, proxygen::ParseURL::port(), port_, proxygen::ParseURL::query(), query_, proxygen::ParseURL::scheme(), scheme_, proxygen::ParseURL::url(), url_, and valid_.
                                                   {
    valid_ = false;
    ParseURL parseUrl(url);
    scheme_ = parseUrl.scheme().str();
    host_ = parseUrl.hostNoBrackets().str();
    path_ = parseUrl.path().str();
    query_ = parseUrl.query().str();
    fragment_ = parseUrl.fragment().str();
    url_ = parseUrl.url().str();
    scheme_ = parseUrl.scheme().str();
    std::transform(scheme_.begin(),
                   scheme_.end(),
                   scheme_.begin(),
                   ::tolower);
    valid_ = (scheme_ == "http" || scheme_ == "https");
    if (parseUrl.port()) {
      port_ = parseUrl.port();
    } else {
      port_ = isSecure() ? 443 : 80;
    }
  }
proxygen::URL::URL (const std::string scheme, const std::string host, uint16_t port = 0, const std::string path = ``, const std::string query = ``, const std::string fragment = ``) [inline], [noexcept]
Definition at line 68 of file URL.h.
References isSecure(), port_, and valid_.
                                              :
    scheme_(scheme),
    host_(host),
    port_(port),
    path_(path),
    query_(query),
    fragment_(fragment),
    url_(createUrl(scheme_, getHostAndPort(), path_, query_, fragment_)) {
    std::transform(scheme_.begin(),
                   scheme_.end(),
                   scheme_.begin(),
                   ::tolower);
    valid_ = (scheme == "http" || scheme == "https");
    if (port_ == 0) {
      port_ = isSecure() ? 443 : 80;
    }
  }
Member Function Documentation
static std::string proxygen::URL::createUrl (const std::string & scheme, const std::string & hostAndPort, const std::string & path, const std::string & query, const std::string & fragment) [inline], [static], [noexcept]
Definition at line 51 of file URL.h.
                                          {
    std::ostringstream out;
    out << scheme << "://" << hostAndPort << '/' << path;
    if (!query.empty()) {
      out << '?' << query;
    }
    if (!fragment.empty()) {
      out << '#' << fragment;
    }
    return out.str();
  }
const std::string& proxygen::URL::getFragment () const [inline], [noexcept]
Definition at line 134 of file URL.h.
References fragment_.
                                                {
    return fragment_;
  }
const std::string& proxygen::URL::getHost () const [inline], [noexcept]
Definition at line 118 of file URL.h.
References host_.
Referenced by CurlService::CurlClient::getServerName(), and main().
                                            {
    return host_;
  }
std::string proxygen::URL::getHostAndPort () const [inline], [noexcept]
Definition at line 122 of file URL.h.
References host_, and port_.
Referenced by CurlService::CurlClient::connectError(), and CurlService::CurlClient::sendRequest().
                                            {
    return port_ ? folly::to<std::string>(host_, ":", port_) : host_;
  }
const std::string& proxygen::URL::getPath () const [inline], [noexcept]
Definition at line 126 of file URL.h.
References path_.
                                            {
    return path_;
  }
uint16_t proxygen::URL::getPort () const [inline], [noexcept]
Definition at line 102 of file URL.h.
References port_.
Referenced by main().
                                    {
    return port_;
  }
const std::string& proxygen::URL::getQuery () const [inline], [noexcept]
Definition at line 130 of file URL.h.
References query_.
                                             {
    return query_;
  }
const std::string& proxygen::URL::getScheme () const [inline], [noexcept]
Definition at line 106 of file URL.h.
References scheme_.
                                              {
    return scheme_;
  }
const std::string& proxygen::URL::getUrl () const [inline], [noexcept]
Definition at line 98 of file URL.h.
References url_.
Referenced by CurlService::CurlClient::CurlClient(), and CurlService::CurlClient::sendRequest().
                                           {
    return url_;
  }
bool proxygen::URL::hasHost () const [inline], [noexcept]
Definition at line 114 of file URL.h.
References host_, and valid_.
                                {
    return valid_ && !host_.empty();
  }
bool proxygen::URL::isSecure () const [inline], [noexcept]
Definition at line 110 of file URL.h.
References scheme_.
Referenced by CurlService::CurlClient::connectSuccess(), main(), CurlService::CurlClient::sendRequest(), and URL().
                                 {
    return scheme_ == "https";
  }
bool proxygen::URL::isValid () const [inline], [noexcept]
Definition at line 94 of file URL.h.
References valid_.
                                {
    return valid_;
  }
std::string proxygen::URL::makeRelativeURL () const [inline], [noexcept]
Definition at line 138 of file URL.h.
References fragment_, path_, and query_.
Referenced by CurlService::CurlClient::sendRequest().
                                             {
    return folly::to<std::string>(
      path_.empty() ? "/" : path_,
      query_.empty() ? "" : folly::to<std::string>('?', query_),
      fragment_.empty() ? "" : folly::to<std::string>('#', fragment_));
  }
Friends And Related Function Documentation
bool operator!= (const URL & lhs, const URL & rhs) [friend]
Definition at line 156 of file URL.h.
                                                         {
    return !(lhs == rhs);
  }
bool operator== (const URL & lhs, const URL & rhs) [friend]
Definition at line 146 of file URL.h.
                                                         {
    return lhs.getScheme() == rhs.getScheme() &&
      lhs.getHost() == rhs.getHost() &&
      lhs.getPort() == rhs.getPort() &&
      lhs.getPath() == rhs.getPath() &&
      lhs.getQuery() == rhs.getQuery() &&
      lhs.getFragment() == rhs.getFragment() &&
      lhs.getUrl() == rhs.getUrl();
  }
Member Data Documentation
std::string proxygen::URL::fragment_ [private]
Definition at line 166 of file URL.h.
Referenced by getFragment(), makeRelativeURL(), and URL().
std::string proxygen::URL::host_ [private]
Definition at line 162 of file URL.h.
Referenced by getHost(), getHostAndPort(), hasHost(), and URL().
std::string proxygen::URL::path_ [private]
Definition at line 164 of file URL.h.
Referenced by getPath(), makeRelativeURL(), and URL().
uint16_t proxygen::URL::port_ [private]
Definition at line 163 of file URL.h.
Referenced by getHostAndPort(), getPort(), and URL().
std::string proxygen::URL::query_ [private]
Definition at line 165 of file URL.h.
Referenced by getQuery(), makeRelativeURL(), and URL().
std::string proxygen::URL::scheme_ [private]
Definition at line 161 of file URL.h.
Referenced by getScheme(), isSecure(), and URL().
std::string proxygen::URL::url_ [private]
Definition at line 168 of file URL.h.
Referenced by getUrl(), and URL().
bool proxygen::URL::valid_ {false} [private]
Definition at line 171 of file URL.h.
Referenced by hasHost(), isValid(), and URL().
The documentation for this class was generated from the following file:
proxygen/lib/utils/URL.h