proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp > Class Template Reference
#include <FilterChain.h>
Public Types
using Filter = GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >
Public Member Functions
GenericFilter (bool calls, bool callbacks)
~GenericFilter () override
void append (Filter *nextFilter)
Public Attributes
const bool kWantsCalls_
const bool kWantsCallbacks_
Protected Member Functions
void setCallbackInternal (T2 *cb)
void drop ()
Protected Attributes
T1 * call_ {nullptr}
T2 * callback_ {nullptr}
Private Member Functions
void setCallbackInternalImpl (T2 *cb, T2 *sourceSet)
Private Attributes
Filter * next_ {nullptr}
Filter * prev_ {nullptr}
Filter * callSource_ {nullptr}
T1 * callbackSource_ {nullptr}
Friends
template<class A , class B , class F , void(A::*)(B *) fn, bool Own>
class FilterChain
Detailed Description
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>>
*
class proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >
A generic two-way filter. That is, this filter intercepts calls from an object A to some object B on an interface T1. It also intercepts calls from B to A on an interface T2.
Subclass GenericFilter templatized on the appropriate interfaces to intercept calls between T1 and T2.
T2 must have the ability to tell T1 to call it back using a certain object. Many different callback patterns have a different name for this function, but this filter needs to be informed when the callback object changes. Therefore, when you subclass this object, you must call
void setCallbackInternal(T2*);
from the appropriate virtual function and not forward that function call along the chain, or the filter will not work and may have errors!
Definition at line 40 of file FilterChain.h.
Member Typedef Documentation
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>> using proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::Filter = GenericFilter<T1, T2, set_callback, TakeOwnership, Dp>
Definition at line 42 of file FilterChain.h.
Constructor & Destructor Documentation
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>> proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::GenericFilter (bool calls, bool callbacks) [inline]
Parameters
calls You will intercept calls to T1 interface iff you pass true for this parameter.
callbacks You will intercept calls to T2 interface iff you pass true for this parameter.
Definition at line 49 of file FilterChain.h.
                                           :
      kWantsCalls_(calls),
      kWantsCallbacks_(callbacks) {}
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>> proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::~GenericFilter () [inline], [override]
Definition at line 53 of file FilterChain.h.
                            {
    if (TakeOwnership) {
      callbackSource_ = nullptr;
    }
    // For the last filter in the chain, next_ is null, and call_ points
    // to the concrete implementation object.
    auto next = next_ ? next_ : call_;
    drop();
    if (TakeOwnership && next) {
      Dp()(next);
    }
  }
Member Function Documentation
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>> void proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::append (Filter * nextFilter) [inline]
Parameters
nextFilter the new filter to insert after this filter
Definition at line 69 of file FilterChain.h.
                                  {
    nextFilter->next_ = next_;
    nextFilter->prev_ = this;
    nextFilter->call_ = call_;
    nextFilter->callback_ = kWantsCallbacks_ ? this : callback_;
    nextFilter->callSource_ = kWantsCalls_ ? this : callSource_;
    nextFilter->callbackSource_ = callbackSource_;
    if (next_) {
      next_->prev_ = nextFilter;
    }
    if (nextFilter->kWantsCalls_) {
      if (kWantsCalls_) {
        call_ = nextFilter;
      } else {
        callSource_->call_ = nextFilter;
      }
      if (next_) {
        next_->callSource_ = nextFilter;
      }
    }
    if (nextFilter->kWantsCallbacks_) {
      // Find the first filter before this one that wants callbacks
      auto cur = this;
      while (cur->prev_ && !cur->kWantsCallbacks_) {
        cur = cur->prev_;
      }
      cur->callbackSource_ = nextFilter;
      // Make sure nextFilter gets callbacks
      ((nextFilter->callbackSource_)->*(set_callback))(nextFilter);
    }
    next_ = nextFilter;
  }
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>> void proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::drop () [inline], [protected]
Removes this filter from the chain. For owning chains the caller must manually delete the filter
Definition at line 119 of file FilterChain.h.
              {
    if (prev_) {
      prev_->next_ = next_;
    }
    if (next_) {
      next_->prev_ = prev_;
    }
    // TODO: could call fn gated by std::enable_if
    if (kWantsCalls_ && callSource_) {
      callSource_->call_ = call_;
      if (call_) {
        auto callFilter = dynamic_cast<Filter*>(call_);
        if (callFilter) {
          callFilter->callSource_ = callSource_;
        }
      }
    }
    // TODO: could call fn gated by std::enable_if
    if (kWantsCallbacks_ && callbackSource_) {
      ((callbackSource_)->*(set_callback))(callback_);
      if (callback_) {
        auto callbackFilter = dynamic_cast<Filter*>(callback_);
        if (callbackFilter) {
          callbackFilter->callbackSource_ = callbackSource_;
        }
      }
    }
    call_ = callbackSource_ = nullptr;
    callback_ = nullptr;
    callSource_ = next_ = prev_ = nullptr;
  }
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>> void proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::setCallbackInternal (T2 * cb) [inline], [protected]
Note: you MUST override the set_callback function and call setCallbackInternal() from your derived class.
Definition at line 111 of file FilterChain.h.
Referenced by proxygen::PassThroughHTTPCodecFilter::setCallback().
                                   {
    setCallbackInternalImpl(cb, this);
  }
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>> void proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::setCallbackInternalImpl (T2 * cb, T2 * sourceSet) [inline], [private]
Definition at line 158 of file FilterChain.h.
                                                      {
    if (callback_ != cb) {
      callback_ = cb;
      ((callbackSource_)->*(set_callback))(cb ? sourceSet : nullptr);
    }
  }
Friends And Related Function Documentation
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>> template<class A , class B , class F , void(A::*)(B *) fn, bool Own> friend class FilterChain [friend]
Definition at line 177 of file FilterChain.h.
Member Data Documentation
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>> T1* proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_ {nullptr} [protected]
Definition at line 152 of file FilterChain.h.
Referenced by proxygen::PassThroughHTTPCodecFilter::addPriorityNodes(), proxygen::GenericFilter< TesterInterface, TesterInterface::Callback,&TesterInterface::setCallback, Owned >::append(), proxygen::PassThroughHTTPCodecFilter::closeOnEgressComplete(), proxygen::PassThroughHTTPCodecFilter::createStream(), proxygen::PassThroughHTTPCodecFilter::enableDoubleGoawayDrain(), proxygen::FlowControlFilter::generateBody(), proxygen::PassThroughHTTPCodecFilter::generateBody(), proxygen::PassThroughHTTPCodecFilter::generateCertificate(), proxygen::PassThroughHTTPCodecFilter::generateCertificateRequest(), proxygen::PassThroughHTTPCodecFilter::generateChunkHeader(), proxygen::PassThroughHTTPCodecFilter::generateChunkTerminator(), proxygen::PassThroughHTTPCodecFilter::generateConnectionPreface(), proxygen::PassThroughHTTPCodecFilter::generateEOM(), proxygen::PassThroughHTTPCodecFilter::generateExHeader(), proxygen::PassThroughHTTPCodecFilter::generateGoaway(), proxygen::HTTPChecks::generateHeader(), proxygen::PassThroughHTTPCodecFilter::generateHeader(), proxygen::PassThroughHTTPCodecFilter::generatePingReply(), proxygen::PassThroughHTTPCodecFilter::generatePingRequest(), proxygen::PassThroughHTTPCodecFilter::generatePriority(), proxygen::PassThroughHTTPCodecFilter::generatePushPromise(), proxygen::PassThroughHTTPCodecFilter::generateRstStream(), proxygen::PassThroughHTTPCodecFilter::generateSettings(), proxygen::PassThroughHTTPCodecFilter::generateSettingsAck(), proxygen::PassThroughHTTPCodecFilter::generateTrailers(), proxygen::FlowControlFilter::generateWindowUpdate(), proxygen::PassThroughHTTPCodecFilter::generateWindowUpdate(), proxygen::PassThroughHTTPCodecFilter::getCompressionInfo(), proxygen::PassThroughHTTPCodecFilter::getDefaultWindowSize(), proxygen::PassThroughHTTPCodecFilter::getEgressSettings(), proxygen::PassThroughHTTPCodecFilter::getIngressSettings(), proxygen::PassThroughHTTPCodecFilter::getLastIncomingStreamID(), proxygen::PassThroughHTTPCodecFilter::getProtocol(), proxygen::PassThroughHTTPCodecFilter::getTransportDirection(), proxygen::PassThroughHTTPCodecFilter::getUserAgent(), proxygen::FlowControlFilter::ingressBytesProcessed(), proxygen::PassThroughHTTPCodecFilter::isBusy(), proxygen::FlowControlFilter::isReusable(), proxygen::PassThroughHTTPCodecFilter::isReusable(), proxygen::PassThroughHTTPCodecFilter::isWaitingToDrain(), proxygen::PassThroughHTTPCodecFilter::mapDependencyToPriority(), proxygen::PassThroughHTTPCodecFilter::mapPriorityToDependency(), proxygen::HTTPCodecPrinter::onFrameHeader(), proxygen::PassThroughHTTPCodecFilter::onIngress(), proxygen::PassThroughHTTPCodecFilter::onIngressEOF(), proxygen::PassThroughHTTPCodecFilter::onIngressUpgradeMessage(), proxygen::FilterChain< HTTPCodec, HTTPCodec::Callback, PassThroughHTTPCodecFilter,&HTTPCodec::setCallback, true >::setDestination(), proxygen::PassThroughHTTPCodecFilter::setHeaderCodecStats(), proxygen::PassThroughHTTPCodecFilter::setParserPaused(), proxygen::FlowControlFilter::setReceiveWindowSize(), proxygen::PassThroughHTTPCodecFilter::supportsParallelRequests(), proxygen::PassThroughHTTPCodecFilter::supportsPushTransactions(), proxygen::PassThroughHTTPCodecFilter::supportsSessionFlowControl(), and proxygen::PassThroughHTTPCodecFilter::supportsStreamFlowControl().
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>> T2* proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_ {nullptr} [protected]
Definition at line 154 of file FilterChain.h.
Referenced by proxygen::GenericFilter< TesterInterface, TesterInterface::Callback,&TesterInterface::setCallback, Owned >::append(), proxygen::PassThroughHTTPCodecFilter::numIncomingStreams(), proxygen::PassThroughHTTPCodecFilter::numOutgoingStreams(), proxygen::HTTPCodecPrinter::onAbort(), proxygen::PassThroughHTTPCodecFilter::onAbort(), proxygen::HTTPCodecPrinter::onBody(), proxygen::PassThroughHTTPCodecFilter::onBody(), proxygen::FlowControlFilter::onBody(), proxygen::PassThroughHTTPCodecFilter::onCertificate(), proxygen::PassThroughHTTPCodecFilter::onCertificateRequest(), proxygen::PassThroughHTTPCodecFilter::onChunkComplete(), proxygen::PassThroughHTTPCodecFilter::onChunkHeader(), proxygen::HTTPCodecPrinter::onError(), proxygen::PassThroughHTTPCodecFilter::onError(), proxygen::PassThroughHTTPCodecFilter::onExMessageBegin(), proxygen::HTTPCodecPrinter::onFrameHeader(), proxygen::PassThroughHTTPCodecFilter::onFrameHeader(), proxygen::PassThroughHTTPCodecFilter::onGenerateFrameHeader(), proxygen::PassThroughHTTPCodecFilter::onGoaway(), proxygen::HTTPCodecPrinter::onGoaway(), proxygen::HTTPChecks::onHeadersComplete(), proxygen::PassThroughHTTPCodecFilter::onHeadersComplete(), proxygen::HTTPCodecPrinter::onHeadersComplete(), proxygen::PassThroughHTTPCodecFilter::onMessageBegin(), proxygen::HTTPCodecPrinter::onMessageComplete(), proxygen::PassThroughHTTPCodecFilter::onMessageComplete(), proxygen::PassThroughHTTPCodecFilter::onNativeProtocolUpgrade(), proxygen::PassThroughHTTPCodecFilter::onPingReply(), proxygen::HTTPCodecPrinter::onPingReply(), proxygen::PassThroughHTTPCodecFilter::onPingRequest(), proxygen::HTTPCodecPrinter::onPingRequest(), proxygen::PassThroughHTTPCodecFilter::onPriority(), proxygen::PassThroughHTTPCodecFilter::onPushMessageBegin(), proxygen::HTTPCodecPrinter::onSettings(), proxygen::PassThroughHTTPCodecFilter::onSettings(), proxygen::HTTPCodecPrinter::onSettingsAck(), proxygen::PassThroughHTTPCodecFilter::onSettingsAck(), proxygen::PassThroughHTTPCodecFilter::onTrailersComplete(), proxygen::HTTPCodecPrinter::onWindowUpdate(), proxygen::PassThroughHTTPCodecFilter::onWindowUpdate(), and proxygen::FlowControlFilter::onWindowUpdate().
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>> T1* proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callbackSource_ {nullptr} [private]
Definition at line 174 of file FilterChain.h.
Referenced by proxygen::GenericFilter< TesterInterface, TesterInterface::Callback,&TesterInterface::setCallback, Owned >::append(), proxygen::GenericFilter< TesterInterface, TesterInterface::Callback,&TesterInterface::setCallback, Owned >::drop(), and proxygen::FilterChain< HTTPCodec, HTTPCodec::Callback, PassThroughHTTPCodecFilter,&HTTPCodec::setCallback, true >::setDestination().
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>> Filter* proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callSource_ {nullptr} [private]
Definition at line 171 of file FilterChain.h.
Referenced by proxygen::GenericFilter< TesterInterface, TesterInterface::Callback,&TesterInterface::setCallback, Owned >::append(), and proxygen::GenericFilter< TesterInterface, TesterInterface::Callback,&TesterInterface::setCallback, Owned >::drop().
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>> const bool proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::kWantsCallbacks_
Definition at line 104 of file FilterChain.h.
Referenced by proxygen::GenericFilter< TesterInterface, TesterInterface::Callback,&TesterInterface::setCallback, Owned >::append(), and proxygen::FilterChain< HTTPCodec, HTTPCodec::Callback, PassThroughHTTPCodecFilter,&HTTPCodec::setCallback, true >::setDestination().
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>> const bool proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::kWantsCalls_
Definition at line 103 of file FilterChain.h.
Referenced by proxygen::GenericFilter< TesterInterface, TesterInterface::Callback,&TesterInterface::setCallback, Owned >::append(), and proxygen::FilterChain< HTTPCodec, HTTPCodec::Callback, PassThroughHTTPCodecFilter,&HTTPCodec::setCallback, true >::setDestination().
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>> Filter* proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::next_ {nullptr} [private]
Definition at line 166 of file FilterChain.h.
Referenced by proxygen::GenericFilter< TesterInterface, TesterInterface::Callback,&TesterInterface::setCallback, Owned >::append(), and proxygen::FilterChain< HTTPCodec, HTTPCodec::Callback, PassThroughHTTPCodecFilter,&HTTPCodec::setCallback, true >::setDestination().
template<typename T1, typename T2, void(T1::*)(T2 *) set_callback, bool TakeOwnership, typename Dp = std::default_delete<T1>> Filter* proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::prev_ {nullptr} [private]
Definition at line 168 of file FilterChain.h.
Referenced by proxygen::GenericFilter< TesterInterface, TesterInterface::Callback,&TesterInterface::setCallback, Owned >::append().
The documentation for this class was generated from the following file:
proxygen/lib/utils/FilterChain.h