TestingHuffTree Class Reference
Public Member Functions
TestingHuffTree (const HuffTree &tree)
const SuperHuffNode * getInternalTable ()
Static Public Member Functions
static TestingHuffTree getHuffTree ()
Additional Inherited Members
Detailed Description
Class used in testing to expose the internal tables for requests and responses
Definition at line 264 of file HuffmanTests.cpp.
Constructor & Destructor Documentation
TestingHuffTree::TestingHuffTree (const HuffTree & tree) [inline], [explicit]
Definition at line 267 of file HuffmanTests.cpp.
: HuffTree(tree) {}
Member Function Documentation
static TestingHuffTree TestingHuffTree::getHuffTree () [inline], [static]
Definition at line 273 of file HuffmanTests.cpp.
References proxygen::huffman::huffTree().
Referenced by TEST_F().
                                       {
    TestingHuffTree reqTree(huffTree());
    return reqTree;
  }
const SuperHuffNode* TestingHuffTree::getInternalTable () [inline]
Definition at line 269 of file HuffmanTests.cpp.
Referenced by TEST_F().
                                          {
    return table_;
  }
The documentation for this class was generated from the following file:
proxygen/lib/http/codec/compress/test/HuffmanTests.cpp