proxygen::HTTP2PriorityQueueBase::BaseNode Class Reference
#include <HTTP2PriorityQueue.h>
Public Member Functions
virtual ~BaseNode ()
virtual bool isEnqueued () const =0
virtual uint64_t calculateDepth (bool includeVirtual=true) const =0
Detailed Description
Definition at line 29 of file HTTP2PriorityQueue.h.
Constructor & Destructor Documentation
virtual proxygen::HTTP2PriorityQueueBase::BaseNode::~BaseNode () [inline], [virtual]
Definition at line 31 of file HTTP2PriorityQueue.h.
References calculateDepth(), and isEnqueued().
{}
Member Function Documentation
virtual uint64_t proxygen::HTTP2PriorityQueueBase::BaseNode::calculateDepth (bool includeVirtual = true) const [pure virtual]
Referenced by proxygen::HTTPTransaction::updateContentionsCount(), proxygen::HTTP2PriorityQueue::updatePriority(), and ~BaseNode().
virtual bool proxygen::HTTP2PriorityQueueBase::BaseNode::isEnqueued () const [pure virtual]
Referenced by proxygen::HTTP2PriorityQueue::Node::inEgressTree(), proxygen::HTTP2PriorityQueue::signalPendingEgress(), and ~BaseNode().
The documentation for this class was generated from the following file:
proxygen/lib/http/session/HTTP2PriorityQueue.h