proxygen::MockHTTPMessageFilter Class Reference
#include <MockHTTPMessageFilter.h>
Public Member Functions
GMOCK_METHOD1_ (, noexcept,, onHeadersComplete, void(std::shared_ptr< HTTPMessage >))
void onHeadersComplete (std::unique_ptr< HTTPMessage > msg) noexceptoverride
GMOCK_METHOD1_ (, noexcept,, onBody, void(std::shared_ptr< folly::IOBuf >))
void onBody (std::unique_ptr< folly::IOBuf > chain) noexceptoverride
GMOCK_METHOD1_ (, noexcept,, onChunkHeader, void(size_t))
GMOCK_METHOD0_ (, noexcept,, onChunkComplete, void())
GMOCK_METHOD1_ (, noexcept,, onTrailers, void(std::shared_ptr< HTTPHeaders > trailers))
void onTrailers (std::unique_ptr< HTTPHeaders > trailers) noexceptoverride
GMOCK_METHOD0_ (, noexcept,, onEOM, void())
GMOCK_METHOD1_ (, noexcept,, onUpgrade, void(UpgradeProtocol))
GMOCK_METHOD1_ (, noexcept,, onError, void(const HTTPException &))
void nextOnHeadersCompletePublic (std::shared_ptr< HTTPMessage > msg)
const std::string & getFilterName () noexceptoverride
std::unique_ptr< HTTPMessageFilter > clone () noexceptoverride
void nextOnEOMPublic ()
Additional Inherited Members
Detailed Description
Definition at line 18 of file MockHTTPMessageFilter.h.
Member Function Documentation
std::unique_ptr<HTTPMessageFilter> proxygen::MockHTTPMessageFilter::clone () [inline], [override], [virtual], [noexcept]
Implements proxygen::HTTPMessageFilter .
Definition at line 50 of file MockHTTPMessageFilter.h.
References getFilterName().
                                                                          {
    LOG(FATAL) << "clone() not implemented for filter: "
               << this->getFilterName();
  };
const std::string& proxygen::MockHTTPMessageFilter::getFilterName () [inline], [override], [virtual], [noexcept]
Reimplemented from proxygen::HTTPMessageFilter .
Definition at line 46 of file MockHTTPMessageFilter.h.
References proxygen::kMockFilterName.
Referenced by clone().
                                                     {
    return kMockFilterName;
  }
proxygen::MockHTTPMessageFilter::GMOCK_METHOD0_ (noexcept , onChunkComplete , void())
Referenced by onBody(), and onTrailers().
proxygen::MockHTTPMessageFilter::GMOCK_METHOD0_ (noexcept , onEOM , void())
proxygen::MockHTTPMessageFilter::GMOCK_METHOD1_ (noexcept , onHeadersComplete , void(std::shared_ptr< HTTPMessage >))
Referenced by onBody(), onHeadersComplete(), and onTrailers().
proxygen::MockHTTPMessageFilter::GMOCK_METHOD1_ (noexcept , onBody , void(std::shared_ptr< folly::IOBuf >))
proxygen::MockHTTPMessageFilter::GMOCK_METHOD1_ (noexcept , onChunkHeader , void(size_t))
proxygen::MockHTTPMessageFilter::GMOCK_METHOD1_ (noexcept , onTrailers , void(std::shared_ptr< HTTPHeaders > trailers))
proxygen::MockHTTPMessageFilter::GMOCK_METHOD1_ (noexcept , onUpgrade , void(UpgradeProtocol))
proxygen::MockHTTPMessageFilter::GMOCK_METHOD1_ (noexcept , onError , void(const HTTPException &))
void proxygen::MockHTTPMessageFilter::nextOnEOMPublic () [inline]
Definition at line 55 of file MockHTTPMessageFilter.h.
References proxygen::HTTPMessageFilter::nextOnEOM().
                         {
    nextOnEOM();
  }
void proxygen::MockHTTPMessageFilter::nextOnHeadersCompletePublic (std::shared_ptr< HTTPMessage > msg) [inline]
Definition at line 41 of file MockHTTPMessageFilter.h.
References proxygen::HTTPMessageFilter::nextOnHeadersComplete().
                                                                   {
    std::unique_ptr<HTTPMessage> msgU(new HTTPMessage(*msg));
    nextOnHeadersComplete(std::move(msgU));
  }
void proxygen::MockHTTPMessageFilter::onBody (std::unique_ptr< folly::IOBuf > chain) [inline], [override], [virtual], [noexcept]
Can be called multiple times per transaction. If you had previously called pauseIngress(), this callback will be delayed until you call resumeIngress().
Reimplemented from proxygen::HTTPMessageFilter .
Definition at line 27 of file MockHTTPMessageFilter.h.
References GMOCK_METHOD0_(), GMOCK_METHOD1_(), proxygen::HTTPMessageFilter::onChunkComplete(), proxygen::HTTPMessageFilter::onChunkHeader(), and onTrailers().
Referenced by onHeadersComplete().
                                                                 {
    onBody(std::shared_ptr<folly::IOBuf>(chain.release()));
  }
void proxygen::MockHTTPMessageFilter::onHeadersComplete (std::unique_ptr< HTTPMessage > msg) [inline], [override], [virtual], [noexcept]
Called at most once per transaction. This is usually the first ingress callback. It is possible to get a read error before this however. If you had previously called pauseIngress(), this callback will be delayed until you call resumeIngress().
Reimplemented from proxygen::HTTPMessageFilter .
Definition at line 22 of file MockHTTPMessageFilter.h.
References GMOCK_METHOD1_(), and onBody().
                                                                           {
    onHeadersComplete(std::shared_ptr<HTTPMessage>(msg.release()));
  }
void proxygen::MockHTTPMessageFilter::onTrailers (std::unique_ptr< HTTPHeaders > trailers) [inline], [override], [virtual], [noexcept]
Can be called any number of times per transaction. If you had previously called pauseIngress(), this callback will be delayed until you call resumeIngress(). Trailers can be received once right before the EOM of a chunked HTTP/1.1 reponse or multiple times per transaction from SPDY and HTTP/2.0 HEADERS frames.
Reimplemented from proxygen::HTTPMessageFilter .
Definition at line 34 of file MockHTTPMessageFilter.h.
References GMOCK_METHOD0_(), GMOCK_METHOD1_(), proxygen::HTTPMessageFilter::onEOM(), proxygen::HTTPMessageFilter::onError(), and proxygen::HTTPMessageFilter::onUpgrade().
Referenced by onBody().
                                                                         {
    onTrailers(std::shared_ptr<HTTPHeaders>(trailers.release()));
  }
The documentation for this class was generated from the following file:
proxygen/lib/http/test/MockHTTPMessageFilter.h