proxygen::SimpleController Class Reference
#include <SimpleController.h>
Public Member Functions
SimpleController (HTTPSessionAcceptor *acceptor)
HTTPTransactionHandler * getRequestHandler (HTTPTransaction &txn, HTTPMessage *msg) override
HTTPTransactionHandler * getParseErrorHandler (HTTPTransaction *txn, const HTTPException &error, const folly::SocketAddress &localAddress) override
HTTPTransactionHandler * getTransactionTimeoutHandler (HTTPTransaction *txn, const folly::SocketAddress &localAddress) override
void attachSession (HTTPSessionBase *) override
void detachSession (const HTTPSessionBase *) override
std::chrono::milliseconds getGracefulShutdownTimeout () const override
Protected Member Functions
HTTPTransactionHandler * createErrorHandler (uint32_t statusCode, const std::string &statusMessage, const HTTPErrorPage *errorPage)
Protected Attributes
HTTPSessionAcceptor *const acceptor_ {nullptr}
Detailed Description
This simple controller provides some basic default behaviors. When errors occur, it will install an appropriate handler. Otherwise, it will install the acceptor's default handler.
Definition at line 25 of file SimpleController.h.
Constructor & Destructor Documentation
proxygen::SimpleController::SimpleController (HTTPSessionAcceptor * acceptor) [explicit]
Definition at line 18 of file SimpleController.cpp.
    : acceptor_(acceptor) {
}
Member Function Documentation
void proxygen::SimpleController::attachSession (HTTPSessionBase * session) [override], [virtual]
Inform the controller it is associated with this particular session.
Implements proxygen::HTTPSessionController .
Definition at line 49 of file SimpleController.cpp.
{}
HTTPTransactionHandler * proxygen::SimpleController::createErrorHandler (uint32_t statusCode, const std::string & statusMessage, const HTTPErrorPage * errorPage) [protected]
Definition at line 53 of file SimpleController.cpp.
Referenced by getParseErrorHandler(), and getTransactionTimeoutHandler().
                                    {
  return new HTTPDirectResponseHandler(statusCode,
                                       statusMessage,
                                       errorPage);
}
void proxygen::SimpleController::detachSession (const HTTPSessionBase * session) [override], [virtual]
Informed at the end when the given HTTPSession is going away.
Implements proxygen::HTTPSessionController .
Definition at line 51 of file SimpleController.cpp.
{}
std::chrono::milliseconds proxygen::SimpleController::getGracefulShutdownTimeout () const [override], [virtual]
Optionally allow the session to query custom graceful shutdown timeout.
Reimplemented from proxygen::HTTPSessionController .
Definition at line 63 of file SimpleController.cpp.
References acceptor_.
                                                                         {
  return acceptor_->getGracefulShutdownTimeout();
}
HTTPTransactionHandler * proxygen::SimpleController::getParseErrorHandler (HTTPTransaction * txn, const HTTPException & error, const folly::SocketAddress & localAddress) [override], [virtual]
Will be invoked when HTTPSession is unable to parse a new request on the connection because of bad input.
error contains specific information about what went wrong
Implements proxygen::HTTPSessionController .
Definition at line 27 of file SimpleController.cpp.
References acceptor_, createErrorHandler(), proxygen::HTTPException::getCodecStatusCode(), proxygen::HTTPSessionAcceptor::getErrorPage(), proxygen::HTTPException::getHttpStatusCode(), proxygen::HTTPException::hasCodecStatusCode(), and proxygen::HTTPException::hasHttpStatusCode().
                                            {
  if (error.hasCodecStatusCode()) {
    return new CodecErrorResponseHandler(error.getCodecStatusCode());
  }
  auto errorPage = acceptor_->getErrorPage(localAddress);
  return createErrorHandler(error.hasHttpStatusCode() ?
                            error.getHttpStatusCode() : 400,
                            "Bad Request", errorPage);
}
HTTPTransactionHandler * proxygen::SimpleController::getRequestHandler (HTTPTransaction & txn, HTTPMessage * msg) [override], [virtual]
Will be invoked whenever HTTPSession successfully parses a request
Implements proxygen::HTTPSessionController .
Definition at line 22 of file SimpleController.cpp.
References acceptor_, and proxygen::HTTPSessionAcceptor::newHandler().
                                          {
  return acceptor_->newHandler(txn, msg);
}
HTTPTransactionHandler * proxygen::SimpleController::getTransactionTimeoutHandler (HTTPTransaction * txn, const folly::SocketAddress & localAddress) [override], [virtual]
Will be invoked when HTTPSession times out parsing a new request.
Implements proxygen::HTTPSessionController .
Definition at line 42 of file SimpleController.cpp.
References acceptor_, createErrorHandler(), and proxygen::HTTPSessionAcceptor::getErrorPage().
                                                                {
  auto errorPage = acceptor_->getErrorPage(localAddress);
  return createErrorHandler(408, "Client timeout", errorPage);
}
Member Data Documentation
HTTPSessionAcceptor* const proxygen::SimpleController::acceptor_ {nullptr} [protected]
Definition at line 64 of file SimpleController.h.
Referenced by getGracefulShutdownTimeout(), getParseErrorHandler(), getRequestHandler(), and getTransactionTimeoutHandler().
The documentation for this class was generated from the following files:
proxygen/lib/http/session/SimpleController.h
proxygen/lib/http/session/SimpleController.cpp