proxygen::RequestWorker Class Reference
#include <RequestWorker.h>
Classes
class FinishCallback
Public Member Functions
RequestWorker (FinishCallback &callback, uint8_t threadId, const std::string &evbName=std::string())
void addServiceWorker (Service *service, ServiceWorker *sw)
ServiceWorker * getServiceWorker (Service *service) const
void flushStats ()
Static Public Member Functions
static uint64_t nextRequestId ()
static RequestWorker * getRequestWorker ()
Private Member Functions
void setup () override
void cleanup () override
Private Attributes
uint64_t nextRequestId_
std::map< Service *, ServiceWorker * > serviceWorkers_
FinishCallback & callback_
Additional Inherited Members
Detailed Description
RequestWorker extends WorkerThread, and also contains a list of ServiceWorkers running in this thread.
Definition at line 25 of file RequestWorker.h.
Constructor & Destructor Documentation
proxygen::RequestWorker::RequestWorker (FinishCallback & callback, uint8_t threadId, const std::string & evbName = std::string())
Create a new RequestWorker.
Parameters
proxygen The object to notify when this worker finishes.
threadId A unique ID for this worker.
evbName The event base will ne named to this name (thread name)
Definition at line 17 of file RequestWorker.cpp.
Referenced by proxygen::RequestWorker::FinishCallback::~FinishCallback().
    : WorkerThread(folly::EventBaseManager::get(), evbName),
      nextRequestId_(static_cast<uint64_t>(threadId) << 56),
      callback_(callback) {
}
Member Function Documentation
void proxygen::RequestWorker::addServiceWorker (Service * service, ServiceWorker * sw) [inline]
Track the ServiceWorker objects in-use by this worker.
Definition at line 57 of file RequestWorker.h.
References serviceWorkers_.
Referenced by proxygen::Service::addServiceWorker().
                                                             {
    CHECK(serviceWorkers_.find(service) == serviceWorkers_.end());
    serviceWorkers_[service] = sw;
  }
void proxygen::RequestWorker::cleanup () [override], [private], [virtual]
Reimplemented from proxygen::WorkerThread .
Definition at line 40 of file RequestWorker.cpp.
References callback_, proxygen::WorkerThread::cleanup(), and proxygen::RequestWorker::FinishCallback::workerFinished().
Referenced by getServiceWorker().
                            {
  WorkerThread::cleanup();
  callback_.workerFinished(this);
}
void proxygen::RequestWorker::flushStats ()
Flush any thread-local stats being tracked by our ServiceWorkers.
This must be invoked from within worker's thread.
Definition at line 28 of file RequestWorker.cpp.
References proxygen::WorkerThread::getEventBase(), and serviceWorkers_.
Referenced by getServiceWorker().
                               {
  CHECK(getEventBase()->isInEventBaseThread());
  for (auto& p: serviceWorkers_) {
    p.second->flushStats();
  }
}
static RequestWorker* proxygen::RequestWorker::getRequestWorker () [inline], [static]
Definition at line 47 of file RequestWorker.h.
References proxygen::WorkerThread::getCurrentWorkerThread().
Referenced by nextRequestId().
                                           {
    RequestWorker* self = dynamic_cast<RequestWorker*>(
      WorkerThread::getCurrentWorkerThread());
    CHECK_NOTNULL(self);
    return self;
  }
ServiceWorker* proxygen::RequestWorker::getServiceWorker (Service * service) const [inline]
For a given service, returns the ServiceWorker associated with this RequestWorker
Definition at line 66 of file RequestWorker.h.
References cleanup(), flushStats(), serviceWorkers_, and setup().
                                                          {
    auto it = serviceWorkers_.find(service);
    CHECK(it != serviceWorkers_.end());
    return it->second;
  }
uint64_t proxygen::RequestWorker::nextRequestId () [static]
Definition at line 24 of file RequestWorker.cpp.
References getRequestWorker(), and nextRequestId_.
Referenced by proxygen::RequestWorker::FinishCallback::~FinishCallback().
                                      {
  return getRequestWorker()->nextRequestId_++;
}
void proxygen::RequestWorker::setup () [override], [private], [virtual]
Reimplemented from proxygen::WorkerThread .
Definition at line 35 of file RequestWorker.cpp.
References callback_, proxygen::WorkerThread::setup(), and proxygen::RequestWorker::FinishCallback::workerStarted().
Referenced by getServiceWorker().
                          {
  WorkerThread::setup();
  callback_.workerStarted(this);
}
Member Data Documentation
FinishCallback& proxygen::RequestWorker::callback_ [private]
Definition at line 90 of file RequestWorker.h.
Referenced by cleanup(), and setup().
uint64_t proxygen::RequestWorker::nextRequestId_ [private]
Definition at line 85 of file RequestWorker.h.
Referenced by nextRequestId().
std::map<Service*, ServiceWorker*> proxygen::RequestWorker::serviceWorkers_ [private]
Definition at line 88 of file RequestWorker.h.
Referenced by addServiceWorker(), flushStats(), and getServiceWorker().
The documentation for this class was generated from the following files:
proxygen/lib/services/RequestWorker.h
proxygen/lib/services/RequestWorker.cpp