proxygen::TraceEvent Class Reference
#include <TraceEvent.h>
Classes
class Iterator
struct MetaData
Public Types
using MetaDataMap = std::map< TraceFieldType, MetaData >
Public Member Functions
FB_EXPORT TraceEvent (TraceEventType type, uint32_t parentID=0)
void start (const TimeUtil &tm)
void start (TimePoint startTime)
void end (const TimeUtil &tm)
void end (TimePoint endTime)
bool hasStarted () const
bool hasEnded () const
TimePoint getStartTime () const
TimePoint getEndTime () const
TraceEventType getType () const
uint32_t getID () const
void setParentID (uint32_t parent)
uint32_t getParentID () const
bool hasTraceField (TraceFieldType field) const
template<typename T >
T getTraceFieldDataAs (TraceFieldType field) const
void setMetaData (MetaDataMap &&input)
const MetaDataMap & getMetaData () const
Iterator getMetaDataItr () const
template<typename T >
bool addMeta (TraceFieldType key, T &&value)
template<typename T >
bool addMeta (TraceFieldType key, const T &value)
template<typename T >
bool readIntMeta (TraceFieldType key, T &dest) const
bool readBoolMeta (TraceFieldType key, bool &dest) const
bool readStrMeta (TraceFieldType key, std::string &dest) const
std::string toString () const
Private Types
enum State { NOT_STARTED = 0,
STARTED = 1,
ENDED = 2
 }
Private Member Functions
template<typename T >
bool readMeta (TraceFieldType key, T &dest) const
FB_EXPORT bool addMetaInternal (TraceFieldType key, MetaData &&val)
Private Attributes
uint8_t stateFlags_ {0}
TraceEventType type_
uint32_t id_
uint32_t parentID_
TimePoint start_
TimePoint end_
MetaDataMap metaData_
Friends
class Iterator
std::ostream & operator<< (std::ostream &out, const TraceEvent &event)
Detailed Description
Simple structure to track timing of event in request flow then we can report back to the application.
Definition at line 38 of file TraceEvent.h.
Member Typedef Documentation
using proxygen::TraceEvent::MetaDataMap = std::map<TraceFieldType, MetaData>
Definition at line 100 of file TraceEvent.h.
Member Enumeration Documentation
enum proxygen::TraceEvent::State [private]
Enumerator
NOT_STARTED
STARTED
ENDED
Definition at line 267 of file TraceEvent.h.
             {
    NOT_STARTED = 0,
    STARTED = 1,
    ENDED = 2,
  };
Constructor & Destructor Documentation
proxygen::TraceEvent::TraceEvent (TraceEventType type, uint32_t parentID = 0) [explicit]
Definition at line 30 of file TraceEvent.cpp.
References id_.
                                                            :
  type_(type),
  parentID_(parentID) {
  static std::atomic<uint32_t> counter(0);
  id_ = counter++;
}
Member Function Documentation
template<typename T > bool proxygen::TraceEvent::addMeta (TraceFieldType key, T && value) [inline]
Definition at line 219 of file TraceEvent.h.
References addMetaInternal().
Referenced by TEST().
                                              {
    MetaData val(std::forward<T>(value));
    return addMetaInternal(key, std::move(val));
  }
template<typename T > bool proxygen::TraceEvent::addMeta (TraceFieldType key, const T & value) [inline]
Definition at line 225 of file TraceEvent.h.
References addMetaInternal().
                                                   {
    MetaData val(value);
    return addMetaInternal(key, std::move(val));
  }
bool proxygen::TraceEvent::addMetaInternal (TraceFieldType key, MetaData && val) [private]
Definition at line 72 of file TraceEvent.cpp.
References metaData_.
Referenced by addMeta(), and readMeta().
                                                                     {
  auto rc = metaData_.emplace(key, value);
  // replace if key already exist
  if (!rc.second) {
    rc.first->second = value;
  }
  return rc.second;
}
void proxygen::TraceEvent::end (const TimeUtil & tm)
Sets the end time to the current time according to the TimeUtil.
Definition at line 47 of file TraceEvent.cpp.
References end_, proxygen::TimeUtilGeneric< ClockType >::now(), and stateFlags_.
Referenced by TEST().
                                       {
  stateFlags_ |= State::ENDED;
  end_ = tm.now();
}
void proxygen::TraceEvent::end (TimePoint endTime)
Sets the end time to the given TimePoint.
Definition at line 52 of file TraceEvent.cpp.
References end_, and stateFlags_.
                                      {
  stateFlags_ |= State::ENDED;
  end_ = endTime;
}
TimePoint proxygen::TraceEvent::getEndTime () const [inline]
Definition at line 175 of file TraceEvent.h.
References end_.
                               {
    return end_;
  }
uint32_t proxygen::TraceEvent::getID () const [inline]
Definition at line 183 of file TraceEvent.h.
References id_.
Referenced by TEST().
                         {
    return id_;
  }
const MetaDataMap& proxygen::TraceEvent::getMetaData () const [inline]
Definition at line 210 of file TraceEvent.h.
References metaData_.
                                         {
    return metaData_;
  }
Iterator proxygen::TraceEvent::getMetaDataItr () const [inline]
Definition at line 214 of file TraceEvent.h.
References Iterator.
Referenced by TEST(), and toString().
                                  {
    return Iterator(*this);
  }
uint32_t proxygen::TraceEvent::getParentID () const [inline]
Definition at line 191 of file TraceEvent.h.
References parentID_.
                               {
    return parentID_;
  }
TimePoint proxygen::TraceEvent::getStartTime () const [inline]
Definition at line 171 of file TraceEvent.h.
References start_.
                                 {
    return start_;
  }
template<typename T > T proxygen::TraceEvent::getTraceFieldDataAs (TraceFieldType field) const [inline]
Definition at line 200 of file TraceEvent.h.
References metaData_, and T.
Referenced by TEST().
                                                    {
    const auto itr = metaData_.find(field);
    CHECK(itr != metaData_.end());
    return itr->second.getValueAs<T>();
  }
TraceEventType proxygen::TraceEvent::getType () const [inline]
Definition at line 179 of file TraceEvent.h.
References type_.
                                 {
    return type_;
  }
bool proxygen::TraceEvent::hasEnded () const
true iff end() has been called on this TraceEvent.
Definition at line 61 of file TraceEvent.cpp.
References stateFlags_.
                                {
  return stateFlags_ & State::ENDED;
}
bool proxygen::TraceEvent::hasStarted () const
true iff start() has been called on this TraceEvent.
Definition at line 57 of file TraceEvent.cpp.
References stateFlags_.
                                  {
  return stateFlags_ & State::STARTED;
}
bool proxygen::TraceEvent::hasTraceField (TraceFieldType field) const [inline]
Definition at line 195 of file TraceEvent.h.
References metaData_.
                                                 {
    return metaData_.count(field);
  }
bool proxygen::TraceEvent::readBoolMeta (TraceFieldType key, bool & dest) const
Definition at line 65 of file TraceEvent.cpp.
References readMeta().
Referenced by readIntMeta().
                                                                  {
  return readMeta(key, dest);
}
template<typename T > bool proxygen::TraceEvent::readIntMeta (TraceFieldType key, T & dest) const [inline]
Definition at line 231 of file TraceEvent.h.
References operator<<, readBoolMeta(), readMeta(), readStrMeta(), and toString().
                                                      {
    static_assert(std::is_integral<T>::value && !std::is_same<T, bool>::value,
        "readIntMeta should take an intergral type of paremeter");
    return readMeta(key, dest);
  }
template<typename T > bool proxygen::TraceEvent::readMeta (TraceFieldType key, T & dest) const [inline], [private]
Definition at line 250 of file TraceEvent.h.
References addMetaInternal(), FB_EXPORT, metaData_, and T.
Referenced by readBoolMeta(), readIntMeta(), and readStrMeta().
                                                   {
    const auto itr = metaData_.find(key);
    if (itr != metaData_.end()) {
      return folly::catch_exception<std::exception const&>(
          [&]() -> bool {
            dest = itr->second.getValueAs<T>();
            return true;
          },
          [](auto&&) -> bool {
            return false;
          });
    }
    return false;
  }
bool proxygen::TraceEvent::readStrMeta (TraceFieldType key, std::string & dest) const
Definition at line 69 of file TraceEvent.cpp.
References readMeta().
Referenced by readIntMeta().
                                                                      {
  return readMeta(key, dest);
}
void proxygen::TraceEvent::setMetaData (MetaDataMap && input) [inline]
Definition at line 206 of file TraceEvent.h.
References metaData_.
                                        {
    metaData_ = input;
  }
void proxygen::TraceEvent::setParentID (uint32_t parent) [inline]
Definition at line 187 of file TraceEvent.h.
References parentID_.
                                    {
    parentID_ = parent;
  }
void proxygen::TraceEvent::start (const TimeUtil & tm)
Sets the start time to the current time according to the TimeUtil.
Definition at line 37 of file TraceEvent.cpp.
References proxygen::TimeUtilGeneric< ClockType >::now(), start_, and stateFlags_.
Referenced by TEST().
                                         {
  stateFlags_ |= State::STARTED;
  start_ = tm.now();
}
void proxygen::TraceEvent::start (TimePoint startTime)
Sets the start time to the given TimePoint.
Definition at line 42 of file TraceEvent.cpp.
References start_, and stateFlags_.
                                          {
  stateFlags_ |= State::STARTED;
  start_ = startTime;
}
std::string proxygen::TraceEvent::toString () const
Definition at line 83 of file TraceEvent.cpp.
References end_, getMetaDataItr(), id_, parentID_, start_, and type_.
Referenced by readIntMeta(), and TEST().
                                     {
  std::ostringstream out;
  int startSinceEpoch = std::chrono::duration_cast<std::chrono::milliseconds>(
    start_.time_since_epoch()).count();
  int endSinceEpoch = std::chrono::duration_cast<std::chrono::milliseconds>(
    end_.time_since_epoch()).count();
  out << "TraceEvent(";
  out << "type='" << getTraceEventTypeString(type_) << "', ";
  out << "id='" << id_ << "', ";
  out << "parentID='" << parentID_ << "', ";
  out << "start='" << startSinceEpoch << "', ";
  out << "end='" << endSinceEpoch << "', ";
  out << "metaData='{";
  auto itr = getMetaDataItr();
  while (itr.isValid()) {
    out << getTraceFieldTypeString(itr.getKey()) << ": "
        << itr.getValueAs<std::string>() << ", ";
    itr.next();
  }
  out << "}')";
  return out.str();
}
Friends And Related Function Documentation
friend class Iterator [friend]
Definition at line 246 of file TraceEvent.h.
Referenced by getMetaDataItr().
std::ostream& operator<< (std::ostream & out, const TraceEvent & event) [friend]
Definition at line 116 of file TraceEvent.cpp.
Referenced by readIntMeta().
                                                                   {
  out << event.toString();
  return out;
}
Member Data Documentation
TimePoint proxygen::TraceEvent::end_ [private]
Definition at line 278 of file TraceEvent.h.
Referenced by end(), getEndTime(), and toString().
uint32_t proxygen::TraceEvent::id_ [private]
Definition at line 275 of file TraceEvent.h.
Referenced by getID(), toString(), and TraceEvent().
MetaDataMap proxygen::TraceEvent::metaData_ [private]
Definition at line 279 of file TraceEvent.h.
Referenced by addMetaInternal(), getMetaData(), getTraceFieldDataAs(), hasTraceField(), readMeta(), and setMetaData().
uint32_t proxygen::TraceEvent::parentID_ [private]
Definition at line 276 of file TraceEvent.h.
Referenced by getParentID(), setParentID(), and toString().
TimePoint proxygen::TraceEvent::start_ [private]
Definition at line 277 of file TraceEvent.h.
Referenced by getStartTime(), start(), and toString().
uint8_t proxygen::TraceEvent::stateFlags_ {0} [private]
Definition at line 273 of file TraceEvent.h.
Referenced by end(), hasEnded(), hasStarted(), and start().
TraceEventType proxygen::TraceEvent::type_ [private]
Definition at line 274 of file TraceEvent.h.
Referenced by getType(), and toString().
The documentation for this class was generated from the following files:
proxygen/lib/utils/TraceEvent.h
proxygen/lib/utils/TraceEvent.cpp