proxygen::HPACKHeaderName Class Reference
#include <HPACKHeaderName.h>
Public Member Functions
HPACKHeaderName ()
HPACKHeaderName (folly::StringPiece name)
HPACKHeaderName (const HPACKHeaderName &headerName)
HPACKHeaderName (HPACKHeaderName &&goner) noexcept
HPACKHeaderName & operator= (folly::StringPiece name)
HPACKHeaderName & operator= (const HPACKHeaderName &headerName)
HPACKHeaderName & operator= (HPACKHeaderName &&goner) noexcept
~HPACKHeaderName ()
bool operator== (const HPACKHeaderName &headerName) const
bool operator!= (const HPACKHeaderName &headerName) const
bool operator> (const HPACKHeaderName &headerName) const
bool operator< (const HPACKHeaderName &headerName) const
bool operator>= (const HPACKHeaderName &headerName) const
bool operator<= (const HPACKHeaderName &headerName) const
const std::string & get () const
HTTPHeaderCode getHeaderCode () const
bool isCommonHeader () const
uint32_t size () const
const char * c_str () const
Private Member Functions
void storeAddress (folly::StringPiece name)
void copyAddress (const HPACKHeaderName &headerName)
void moveAddress (HPACKHeaderName &goner)
void resetAddress ()
bool isAllocated () const
Private Attributes
const std::string * address_ = nullptr
Detailed Description
Definition at line 29 of file HPACKHeaderName.h.
Constructor & Destructor Documentation
proxygen::HPACKHeaderName::HPACKHeaderName () [inline]
Definition at line 31 of file HPACKHeaderName.h.
{}
proxygen::HPACKHeaderName::HPACKHeaderName (folly::StringPiece name) [inline], [explicit]
Definition at line 33 of file HPACKHeaderName.h.
References storeAddress().
                                                  {
    storeAddress(name);
  }
proxygen::HPACKHeaderName::HPACKHeaderName (const HPACKHeaderName & headerName) [inline]
Definition at line 36 of file HPACKHeaderName.h.
References copyAddress().
                                                     {
    copyAddress(headerName);
  }
proxygen::HPACKHeaderName::HPACKHeaderName (HPACKHeaderName && goner) [inline], [noexcept]
Definition at line 39 of file HPACKHeaderName.h.
References moveAddress().
                                                    {
    moveAddress(goner);
  }
proxygen::HPACKHeaderName::~HPACKHeaderName () [inline]
Definition at line 62 of file HPACKHeaderName.h.
References resetAddress().
                     {
    resetAddress();
  }
Member Function Documentation
const char* proxygen::HPACKHeaderName::c_str () const [inline]
Definition at line 132 of file HPACKHeaderName.h.
References address_.
                            {
    return address_->c_str();
  }
void proxygen::HPACKHeaderName::copyAddress (const HPACKHeaderName & headerName) [inline], [private]
Definition at line 157 of file HPACKHeaderName.h.
References address_, get(), and isAllocated().
Referenced by HPACKHeaderName(), and operator=().
                                                      {
    if (headerName.isAllocated()) {
      address_ = new std::string(headerName.get());
    } else {
      address_ = headerName.address_;
    }
  }
const std::string& proxygen::HPACKHeaderName::get () const [inline]
Definition at line 107 of file HPACKHeaderName.h.
References address_.
Referenced by copyAddress(), proxygen::HPACKDecoderBase::emit(), proxygen::HPACKEncoder::encodeLiteral(), proxygen::QPACKEncoder::encodeLiteralQHelper(), std::hash< proxygen::HPACKHeaderName >::operator()(), proxygen::operator<<(), TEST_F(), and TEST_P().
                               {
    return *address_;
  }
HTTPHeaderCode proxygen::HPACKHeaderName::getHeaderCode () const [inline]
Definition at line 114 of file HPACKHeaderName.h.
References address_, proxygen::HTTPCommonHeaders::getHeaderCodeFromTableCommonHeaderName(), and proxygen::TABLE_LOWERCASE.
Referenced by proxygen::HPACKContext::getIndex(), proxygen::NoPathIndexingStrategy::indexHeader(), proxygen::HeaderIndexingStrategy::indexHeader(), and TEST_F().
                                       {
    return HTTPCommonHeaders::getHeaderCodeFromTableCommonHeaderName(
      address_, TABLE_LOWERCASE);
  }
bool proxygen::HPACKHeaderName::isAllocated () const [inline], [private]
Definition at line 187 of file HPACKHeaderName.h.
References address_, proxygen::HTTPCommonHeaders::isHeaderNameFromTable(), and proxygen::TABLE_LOWERCASE.
Referenced by copyAddress(), operator<(), operator>(), and resetAddress().
                           {
    if (address_ == nullptr) {
      return false;
    } else {
      return !HTTPCommonHeaders::isHeaderNameFromTable(
        address_, TABLE_LOWERCASE);
    }
  }
bool proxygen::HPACKHeaderName::isCommonHeader () const [inline]
Definition at line 122 of file HPACKHeaderName.h.
References address_, proxygen::HTTPCommonHeaders::isHeaderNameFromTable(), and proxygen::TABLE_LOWERCASE.
Referenced by proxygen::HPACKContext::getIndex(), and TEST_F().
                              {
    return HTTPCommonHeaders::isHeaderNameFromTable(address_, TABLE_LOWERCASE);
  }
void proxygen::HPACKHeaderName::moveAddress (HPACKHeaderName & goner) [inline], [private]
Definition at line 168 of file HPACKHeaderName.h.
References address_.
Referenced by HPACKHeaderName(), and operator=().
                                           {
    address_ = goner.address_;
    goner.address_ = nullptr;
  }
bool proxygen::HPACKHeaderName::operator!= (const HPACKHeaderName & headerName) const [inline]
Definition at line 73 of file HPACKHeaderName.h.
                                                           {
    // Utilize the == overloaded operator
    return !(*this == headerName);
  }
bool proxygen::HPACKHeaderName::operator< (const HPACKHeaderName & headerName) const [inline]
Definition at line 86 of file HPACKHeaderName.h.
References address_, and isAllocated().
                                                          {
    if (!isAllocated() && !headerName.isAllocated()) {
      // Common header tables are aligned alphabetically (unit tested as well
      // to ensure it isn't accidentally changed)
      return address_ < headerName.address_;
    } else {
      return *address_ < *(headerName.address_);
    }
  }
bool proxygen::HPACKHeaderName::operator<= (const HPACKHeaderName & headerName) const [inline]
Definition at line 99 of file HPACKHeaderName.h.
                                                           {
    // Utilize existing > overload operator
    return !(*this > headerName);
  }
HPACKHeaderName& proxygen::HPACKHeaderName::operator= (folly::StringPiece name) [inline]
Definition at line 42 of file HPACKHeaderName.h.
References resetAddress(), and storeAddress().
                                                    {
    resetAddress();
    storeAddress(name);
    return *this;
  }
HPACKHeaderName& proxygen::HPACKHeaderName::operator= (const HPACKHeaderName & headerName) [inline]
Definition at line 47 of file HPACKHeaderName.h.
References copyAddress(), and resetAddress().
                                                                {
    if (this != &headerName) {
      resetAddress();
      copyAddress(headerName);
    }
    return *this;
  }
HPACKHeaderName& proxygen::HPACKHeaderName::operator= (HPACKHeaderName && goner) [inline], [noexcept]
Definition at line 54 of file HPACKHeaderName.h.
References moveAddress(), and resetAddress().
                                                               {
    if (this != &goner) {
      resetAddress();
      moveAddress(goner);
    }
    return *this;
  }
bool proxygen::HPACKHeaderName::operator== (const HPACKHeaderName & headerName) const [inline]
Definition at line 69 of file HPACKHeaderName.h.
References address_.
                                                           {
    return address_ == headerName.address_ ||
      *address_ == *(headerName.address_);
  }
bool proxygen::HPACKHeaderName::operator> (const HPACKHeaderName & headerName) const [inline]
Definition at line 77 of file HPACKHeaderName.h.
References address_, and isAllocated().
                                                          {
    if (!isAllocated() && !headerName.isAllocated()) {
      // Common header tables are aligned alphabetically (unit tested as well
      // to ensure it isn't accidentally changed)
      return address_ > headerName.address_;
    } else {
      return *address_ > *(headerName.address_);
    }
  }
bool proxygen::HPACKHeaderName::operator>= (const HPACKHeaderName & headerName) const [inline]
Definition at line 95 of file HPACKHeaderName.h.
                                                           {
    // Utilize existing < overloaded operator
    return !(*this < headerName);
  }
void proxygen::HPACKHeaderName::resetAddress () [inline], [private]
Definition at line 176 of file HPACKHeaderName.h.
References address_, and isAllocated().
Referenced by operator=(), and ~HPACKHeaderName().
                      {
    if (isAllocated()) {
      delete address_;
    }
    address_ = nullptr;
  }
uint32_t proxygen::HPACKHeaderName::size () const [inline]
Definition at line 129 of file HPACKHeaderName.h.
References address_.
Referenced by proxygen::HPACKHeader::bytes(), and TEST_F().
                        {
    return (uint32_t)(address_->size());
  }
void proxygen::HPACKHeaderName::storeAddress (folly::StringPiece name) [inline], [private]
Definition at line 140 of file HPACKHeaderName.h.
References address_, proxygen::HTTPCommonHeaders::getPointerToHeaderName(), proxygen::HTTPCommonHeaders::hash(), proxygen::HTTP_HEADER_NONE, proxygen::HTTP_HEADER_OTHER, and proxygen::TABLE_LOWERCASE.
Referenced by HPACKHeaderName(), and operator=().
                                           {
    HTTPHeaderCode headerCode = HTTPCommonHeaders::hash(
      name.data(), name.size());
    if (headerCode == HTTPHeaderCode::HTTP_HEADER_NONE ||
        headerCode == HTTPHeaderCode::HTTP_HEADER_OTHER) {
      std::string* newAddress = new std::string(name.size(), 0);
      std::transform(name.begin(), name.end(), newAddress->begin(), ::tolower);
      address_ = newAddress;
    } else {
      address_ = HTTPCommonHeaders::getPointerToHeaderName(
        headerCode, TABLE_LOWERCASE);
    }
  }
Member Data Documentation
const std::string* proxygen::HPACKHeaderName::address_ = nullptr [private]
Definition at line 200 of file HPACKHeaderName.h.
Referenced by c_str(), copyAddress(), get(), getHeaderCode(), isAllocated(), isCommonHeader(), moveAddress(), operator<(), operator==(), operator>(), resetAddress(), size(), and storeAddress().
The documentation for this class was generated from the following file:
proxygen/lib/http/codec/compress/HPACKHeaderName.h