proxygen::QPACKCodec Class Reference
#include <QPACKCodec.h>
Public Member Functions
QPACKCodec ()
~QPACKCodec () override
QPACKEncoder::EncodeResult encode (std::vector< compress::Header > &headers, uint64_t id, uint32_t maxEncoderStreamBytes=std::numeric_limits< uint32_t >::max()) noexcept
HPACK::DecodeError decodeEncoderStream (std::unique_ptr< folly::IOBuf > buf)
void decodeStreaming (uint64_t streamId, std::unique_ptr< folly::IOBuf > block, uint32_t length, HPACK::StreamingCallback *streamingCb) noexcept
void setEncoderHeaderTableSize (uint32_t size)
void setDecoderHeaderTableMaxSize (uint32_t size)
HPACK::DecodeError decodeDecoderStream (std::unique_ptr< folly::IOBuf > buf)
void onStreamReset (uint64_t streamId)
std::unique_ptr< folly::IOBuf > encodeTableStateSync ()
std::unique_ptr< folly::IOBuf > encodeHeaderAck (uint64_t streamId)
std::unique_ptr< folly::IOBuf > encodeCancelStream (uint64_t streamId)
void describe (std::ostream &os) const
void setMaxUncompressed (uint64_t maxUncompressed) override
CompressionInfo getCompressionInfo () const
void setHeaderIndexingStrategy (const HeaderIndexingStrategy *indexingStrat)
const HeaderIndexingStrategy * getHeaderIndexingStrategy () const
uint64_t getHolBlockCount () const
uint64_t getQueuedBytes () const
void setMaxVulnerable (uint32_t maxVulnerable)
void setMaxBlocking (uint32_t maxBlocking)
Protected Attributes
QPACKEncoder encoder_
QPACKDecoder decoder_
Private Member Functions
void recordCompressedSize (const QPACKEncoder::EncodeResult &encodeRes)
Private Attributes
std::vector< HPACKHeader > decodedHeaders_
Additional Inherited Members
Detailed Description
Definition at line 36 of file QPACKCodec.h.
Constructor & Destructor Documentation
proxygen::QPACKCodec::QPACKCodec ()
Definition at line 29 of file QPACKCodec.cpp.
    : encoder_(true, HPACK::kTableSize),
      decoder_(HPACK::kTableSize, maxUncompressed_) {}
proxygen::QPACKCodec::~QPACKCodec () [inline], [override]
Definition at line 39 of file QPACKCodec.h.
References encode().
{}
Member Function Documentation
HPACK::DecodeError proxygen::QPACKCodec::decodeDecoderStream (std::unique_ptr< folly::IOBuf > buf) [inline]
Definition at line 69 of file QPACKCodec.h.
Referenced by proxygen::compress::QPACKScheme::recvAck().
                                     {
    return encoder_.decodeDecoderStream(std::move(buf));
  }
HPACK::DecodeError proxygen::QPACKCodec::decodeEncoderStream (std::unique_ptr< folly::IOBuf > buf) [inline]
Definition at line 47 of file QPACKCodec.h.
Referenced by proxygen::compress::QPACKScheme::decode().
                                                                      {
    // stats?
    return decoder_.decodeEncoderStream(std::move(buf));
  }
void proxygen::QPACKCodec::decodeStreaming (uint64_t streamId, std::unique_ptr< folly::IOBuf > block, uint32_t length, HPACK::StreamingCallback * streamingCb) [noexcept]
Definition at line 59 of file QPACKCodec.cpp.
References decoder_, proxygen::QPACKDecoder::decodeStreaming(), proxygen::HeaderCodec::stats_, and streamID.
Referenced by proxygen::compress::QPACKScheme::decode().
                                                  {
  if (streamingCb) {
    streamingCb->stats = stats_;
  }
  decoder_.decodeStreaming(streamID, std::move(block), length, streamingCb);
}
void proxygen::QPACKCodec::describe (std::ostream & os) const
Definition at line 70 of file QPACKCodec.cpp.
References decoder_, and encoder_.
Referenced by proxygen::operator<<().
                                                  {
  stream << "DecoderTable:\n" << decoder_;
  stream << "EncoderTable:\n" << encoder_;
}
QPACKEncoder::EncodeResult proxygen::QPACKCodec::encode (std::vector< compress::Header > & headers, uint64_t id, uint32_t maxEncoderStreamBytes = std::numeric_limits<uint32_t>::max()) [noexcept]
Definition at line 47 of file QPACKCodec.cpp.
References proxygen::QPACKEncoder::encode(), proxygen::HeaderCodec::encodedSize_, proxygen::HeaderCodec::encodeHeadroom_, encoder_, proxygen::compress::prepareHeaders(), and recordCompressedSize().
Referenced by proxygen::compress::QPACKScheme::encode().
                                             {
  auto prepared = compress::prepareHeaders(headers);
  encodedSize_.uncompressed = prepared.second;
  auto res = encoder_.encode(prepared.first, encodeHeadroom_, streamId,
                             maxEncoderStreamBytes);
  recordCompressedSize(res);
  return res;
}
std::unique_ptr<folly::IOBuf> proxygen::QPACKCodec::encodeCancelStream (uint64_t streamId) [inline]
Definition at line 88 of file QPACKCodec.h.
                                                                  {
    return decoder_.encodeCancelStream(streamId);
  }
std::unique_ptr<folly::IOBuf> proxygen::QPACKCodec::encodeHeaderAck (uint64_t streamId) [inline]
Definition at line 84 of file QPACKCodec.h.
Referenced by proxygen::compress::QPACKScheme::getAck().
                                                               {
    return decoder_.encodeHeaderAck(streamId);
  }
std::unique_ptr<folly::IOBuf> proxygen::QPACKCodec::encodeTableStateSync () [inline]
Definition at line 80 of file QPACKCodec.h.
Referenced by proxygen::compress::QPACKScheme::getAck().
                                                   {
    return decoder_.encodeTableStateSync();
  }
CompressionInfo proxygen::QPACKCodec::getCompressionInfo () const [inline]
Definition at line 99 of file QPACKCodec.h.
                                             {
    return CompressionInfo(encoder_.getTableSize(),
                           encoder_.getBytesStored(),
                           encoder_.getHeadersStored(),
                           decoder_.getTableSize(),
                           decoder_.getBytesStored(),
                           decoder_.getHeadersStored());
  }
const HeaderIndexingStrategy* proxygen::QPACKCodec::getHeaderIndexingStrategy () const [inline]
Definition at line 111 of file QPACKCodec.h.
                                                                  {
    return encoder_.getHeaderIndexingStrategy();
  }
uint64_t proxygen::QPACKCodec::getHolBlockCount () const [inline]
Definition at line 115 of file QPACKCodec.h.
Referenced by proxygen::compress::QPACKScheme::getHolBlockCount().
                                    {
    return decoder_.getHolBlockCount();
  }
uint64_t proxygen::QPACKCodec::getQueuedBytes () const [inline]
Definition at line 119 of file QPACKCodec.h.
Referenced by proxygen::compress::QPACKScheme::decode(), and proxygen::compress::QPACKScheme::~QPACKScheme().
                                  {
    return decoder_.getQueuedBytes();
  }
void proxygen::QPACKCodec::onStreamReset (uint64_t streamId) [inline]
Definition at line 76 of file QPACKCodec.h.
                                        {
    encoder_.onHeaderAck(streamId, true);
  }
void proxygen::QPACKCodec::recordCompressedSize (const QPACKEncoder::EncodeResult & encodeRes) [private]
Definition at line 33 of file QPACKCodec.cpp.
References proxygen::QPACKEncoder::EncodeResult::control, proxygen::HeaderCodec::encodedSize_, proxygen::HeaderCodec::QPACK, proxygen::HeaderCodec::Stats::recordEncode(), proxygen::HeaderCodec::stats_, and proxygen::QPACKEncoder::EncodeResult::stream.
Referenced by encode().
                                             {
  encodedSize_.compressed = 0;
  if (encodeRes.control) {
    encodedSize_.compressed += encodeRes.control->computeChainDataLength();
  }
  if (encodeRes.stream) {
    encodedSize_.compressed += encodeRes.stream->computeChainDataLength();
  }
  if (stats_) {
    stats_->recordEncode(Type::QPACK, encodedSize_);
  }
}
void proxygen::QPACKCodec::setDecoderHeaderTableMaxSize (uint32_t size) [inline]
Definition at line 64 of file QPACKCodec.h.
Referenced by main(), and proxygen::compress::QPACKScheme::QPACKScheme().
                                                   {
    decoder_.setHeaderTableMaxSize(size);
  }
void proxygen::QPACKCodec::setEncoderHeaderTableSize (uint32_t size) [inline]
Definition at line 60 of file QPACKCodec.h.
Referenced by proxygen::compress::QPACKScheme::QPACKScheme().
                                                {
    encoder_.setHeaderTableSize(size);
  }
void proxygen::QPACKCodec::setHeaderIndexingStrategy (const HeaderIndexingStrategy * indexingStrat) [inline]
Definition at line 108 of file QPACKCodec.h.
Referenced by proxygen::compress::QPACKScheme::QPACKScheme().
                                                                              {
    encoder_.setHeaderIndexingStrategy(indexingStrat);
  }
void proxygen::QPACKCodec::setMaxBlocking (uint32_t maxBlocking) [inline]
Definition at line 127 of file QPACKCodec.h.
Referenced by main(), and proxygen::compress::QPACKScheme::QPACKScheme().
                                            {
    decoder_.setMaxBlocking(maxBlocking);
  }
void proxygen::QPACKCodec::setMaxUncompressed (uint64_t maxUncompressed) [inline], [override], [virtual]
Reimplemented from proxygen::HeaderCodec .
Definition at line 94 of file QPACKCodec.h.
                                                             {
    HeaderCodec::setMaxUncompressed(maxUncompressed);
    decoder_.setMaxUncompressed(maxUncompressed);
  }
void proxygen::QPACKCodec::setMaxVulnerable (uint32_t maxVulnerable) [inline]
Definition at line 123 of file QPACKCodec.h.
Referenced by proxygen::compress::QPACKScheme::QPACKScheme().
                                                {
    encoder_.setMaxVulnerable(maxVulnerable);
  }
Member Data Documentation
std::vector<HPACKHeader> proxygen::QPACKCodec::decodedHeaders_ [private]
Definition at line 138 of file QPACKCodec.h.
QPACKDecoder proxygen::QPACKCodec::decoder_ [protected]
Definition at line 133 of file QPACKCodec.h.
Referenced by decodeStreaming(), and describe().
QPACKEncoder proxygen::QPACKCodec::encoder_ [protected]
Definition at line 132 of file QPACKCodec.h.
Referenced by describe(), and encode().
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/compress/QPACKCodec.h
proxygen/lib/http/codec/compress/QPACKCodec.cpp