proxygen::compress::CompressionScheme Class Reference
#include <CompressionScheme.h>
Classes
struct Ack
Public Types
using BlockInfo = std::tuple< FrameFlags, bool, std::unique_ptr< folly::IOBuf >, SimStreamingCallback * >
Public Member Functions
CompressionScheme (CompressionSimulator *sim)
virtual ~CompressionScheme ()
virtual std::unique_ptr< Ack > getAck (uint16_t seqn)=0
virtual void recvAck (std::unique_ptr< Ack >)=0
virtual std::pair< FrameFlags, std::unique_ptr< folly::IOBuf > > encode (bool newPacket, std::vector< compress::Header > allHeaders, SimStats &stats)=0
virtual void decode (FrameFlags flags, std::unique_ptr< folly::IOBuf > encodedReq, SimStats &stats, SimStreamingCallback &cb)=0
virtual uint32_t getHolBlockCount () const =0
void runLoopCallback () noexceptoverride
Public Attributes
std::list< BlockInfo > encodedBlocks
std::list< BlockInfo > packetBlocks
size_t index {0}
std::chrono::milliseconds prev
size_t packetBytes {0}
std::chrono::milliseconds decodeDelay
std::list< uint16_t > packetIndices
Private Attributes
CompressionSimulator * simulator_
Detailed Description
Definition at line 20 of file CompressionScheme.h.
Member Typedef Documentation
using proxygen::compress::CompressionScheme::BlockInfo = std::tuple<FrameFlags, bool , std::unique_ptr<folly::IOBuf>, SimStreamingCallback*>
Definition at line 67 of file CompressionScheme.h.
Constructor & Destructor Documentation
proxygen::compress::CompressionScheme::CompressionScheme (CompressionSimulator * sim) [inline], [explicit]
Definition at line 22 of file CompressionScheme.h.
                                                        : simulator_(sim) {
  }
virtual proxygen::compress::CompressionScheme::~CompressionScheme () [inline], [virtual]
Definition at line 24 of file CompressionScheme.h.
                               {
  }
Member Function Documentation
virtual void proxygen::compress::CompressionScheme::decode (FrameFlags flags, std::unique_ptr< folly::IOBuf > encodedReq, SimStats & stats, SimStreamingCallback & cb) [pure virtual]
Implemented in proxygen::compress::QMINScheme , proxygen::compress::QPACKScheme , and proxygen::compress::HPACKScheme .
Referenced by proxygen::compress::CompressionSimulator::decode(), and proxygen::compress::CompressionScheme::Ack::~Ack().
virtual std::pair<FrameFlags, std::unique_ptr<folly::IOBuf> > proxygen::compress::CompressionScheme::encode (bool newPacket, std::vector< compress::Header > allHeaders, SimStats & stats) [pure virtual]
Implemented in proxygen::compress::QMINScheme , proxygen::compress::QPACKScheme , and proxygen::compress::HPACKScheme .
Referenced by proxygen::compress::CompressionSimulator::encode(), and proxygen::compress::CompressionScheme::Ack::~Ack().
virtual std::unique_ptr<Ack> proxygen::compress::CompressionScheme::getAck (uint16_t seqn) [pure virtual]
Implemented in proxygen::compress::QMINScheme , proxygen::compress::QPACKScheme , and proxygen::compress::HPACKScheme .
Referenced by proxygen::compress::CompressionScheme::Ack::~Ack().
virtual uint32_t proxygen::compress::CompressionScheme::getHolBlockCount () const [pure virtual]
Implemented in proxygen::compress::QMINScheme , proxygen::compress::QPACKScheme , and proxygen::compress::HPACKScheme .
Referenced by proxygen::compress::CompressionScheme::Ack::~Ack().
virtual void proxygen::compress::CompressionScheme::recvAck (std::unique_ptr< Ack >) [pure virtual]
Implemented in proxygen::compress::QMINScheme , proxygen::compress::QPACKScheme , and proxygen::compress::HPACKScheme .
Referenced by proxygen::compress::CompressionSimulator::recvAck(), and proxygen::compress::CompressionScheme::Ack::~Ack().
void proxygen::compress::CompressionScheme::runLoopCallback () [override], [noexcept]
Definition at line 182 of file CompressionSimulator.cpp.
Referenced by proxygen::compress::CompressionScheme::Ack::~Ack().
                                                 {
  simulator_->flushSchemePackets(this);
}
Member Data Documentation
std::chrono::milliseconds proxygen::compress::CompressionScheme::decodeDelay
Definition at line 79 of file CompressionScheme.h.
Referenced by proxygen::compress::CompressionSimulator::flushPacket(), and proxygen::compress::CompressionSimulator::flushSchemePackets().
std::list<BlockInfo> proxygen::compress::CompressionScheme::encodedBlocks
Definition at line 68 of file CompressionScheme.h.
Referenced by proxygen::compress::CompressionSimulator::flushSchemePackets().
size_t proxygen::compress::CompressionScheme::index {0}
Definition at line 73 of file CompressionScheme.h.
Referenced by proxygen::compress::HPACKScheme::encode(), and proxygen::compress::QPACKScheme::encode().
std::list<BlockInfo> proxygen::compress::CompressionScheme::packetBlocks
Definition at line 70 of file CompressionScheme.h.
Referenced by proxygen::compress::CompressionSimulator::flushPacket(), and proxygen::compress::CompressionSimulator::flushSchemePackets().
size_t proxygen::compress::CompressionScheme::packetBytes {0}
Definition at line 78 of file CompressionScheme.h.
Referenced by proxygen::compress::CompressionSimulator::flushPacket(), and proxygen::compress::CompressionSimulator::flushSchemePackets().
std::list<uint16_t> proxygen::compress::CompressionScheme::packetIndices
Definition at line 81 of file CompressionScheme.h.
Referenced by proxygen::compress::CompressionSimulator::flushRequests().
std::chrono::milliseconds proxygen::compress::CompressionScheme::prev
Definition at line 76 of file CompressionScheme.h.
Referenced by proxygen::compress::CompressionSimulator::flushRequests().
CompressionSimulator* proxygen::compress::CompressionScheme::simulator_ [private]
Definition at line 84 of file CompressionScheme.h.
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/compress/experimental/simulator/CompressionScheme.h
proxygen/lib/http/codec/compress/experimental/simulator/CompressionSimulator.cpp