proxygen::compress::SimStreamingCallback Class Reference
#include <SimStreamingCallback.h>
Public Member Functions
SimStreamingCallback (uint16_t index, std::function< void(std::chrono::milliseconds)> cb, bool isP=false)
SimStreamingCallback (SimStreamingCallback &&goner) noexcept
void onHeader (const folly::fbstring &name, const folly::fbstring &value) override
void onHeadersComplete (HTTPHeaderSize, bool ack) override
void onDecodeError (HPACK::DecodeError decodeError) override
folly::Expected< proxygen::HTTPMessage *, HPACK::DecodeError > getResult ()
void maybeMarkHolDelay ()
Public Attributes
uint16_t requestIndex {0}
uint16_t seqn {0}
HPACK::DecodeError error {HPACK::DecodeError::NONE}
proxygen::HTTPMessage msg
std::function< void(std::chrono::milliseconds)> headersCompleteCb
TimePoint holStart {TimeUtil::getZeroTimePoint()}
bool complete {false}
bool isPublic {false}
bool acknowledge {false}
Detailed Description
Definition at line 19 of file SimStreamingCallback.h.
Constructor & Destructor Documentation
proxygen::compress::SimStreamingCallback::SimStreamingCallback (uint16_t index, std::function< void(std::chrono::milliseconds)> cb, bool isP = false) [inline]
Definition at line 21 of file SimStreamingCallback.h.
      : requestIndex(index), headersCompleteCb(cb), isPublic(isP) {
  }
proxygen::compress::SimStreamingCallback::SimStreamingCallback (SimStreamingCallback && goner) [inline], [noexcept]
Definition at line 27 of file SimStreamingCallback.h.
References error, headersCompleteCb, msg, requestIndex, and seqn.
                                                              {
    std::swap(msg, goner.msg);
    requestIndex = goner.requestIndex;
    seqn = goner.seqn;
    error = goner.error;
    std::swap(headersCompleteCb, goner.headersCompleteCb);
  }
Member Function Documentation
folly::Expected<proxygen::HTTPMessage*, HPACK::DecodeError> proxygen::compress::SimStreamingCallback::getResult () [inline]
Definition at line 79 of file SimStreamingCallback.h.
References error, msg, and proxygen::HPACK::NONE.
                                                                    {
    if (error == HPACK::DecodeError::NONE) {
      return &msg;
    } else {
      return folly::makeUnexpected(error);
    }
  }
void proxygen::compress::SimStreamingCallback::maybeMarkHolDelay () [inline]
Definition at line 87 of file SimStreamingCallback.h.
References complete, proxygen::getCurrentTime(), and holStart.
Referenced by proxygen::compress::HPACKScheme::decode(), and proxygen::compress::QPACKScheme::decode().
                           {
    if (!complete) {
      holStart = getCurrentTime();
    }
  }
void proxygen::compress::SimStreamingCallback::onDecodeError (HPACK::DecodeError decodeError) [inline], [override], [virtual]
Implements proxygen::HPACK::StreamingCallback .
Definition at line 74 of file SimStreamingCallback.h.
References error.
                                                            {
    error = decodeError;
    DCHECK(false) << "Unexpected error in simulator";
  }
void proxygen::compress::SimStreamingCallback::onHeader (const folly::fbstring & name, const folly::fbstring & value) [inline], [override], [virtual]
Implements proxygen::HPACK::StreamingCallback .
Definition at line 35 of file SimStreamingCallback.h.
References proxygen::HTTPHeaders::add(), proxygen::HTTPMessage::getHeaders(), isPublic, proxygen::headers::kAuthority, proxygen::headers::kHttps, proxygen::headers::kMethod, proxygen::headers::kPath, proxygen::headers::kScheme, proxygen::headers::kStatus, msg, proxygen::HTTPMessage::setMethod(), proxygen::HTTPMessage::setSecure(), proxygen::HTTPMessage::setStatusCode(), and proxygen::HTTPMessage::setURL().
Referenced by proxygen::compress::QMINScheme::decode().
                                                     {
    if (name[0] == ':' && !isPublic) {
      if (name == headers::kMethod) {
        msg.setMethod(value);
      } else if (name == headers::kScheme) {
        if (value == headers::kHttps) {
          msg.setSecure(true);
        }
      } else if (name == headers::kAuthority) {
        msg.getHeaders().add(HTTP_HEADER_HOST, value.toStdString());
      } else if (name == headers::kPath) {
        msg.setURL(value.toStdString());
      } else if (name == headers::kStatus) {
        msg.setStatusCode(folly::to<uint16_t>(value.toStdString()));
      } else {
        DCHECK(false) << "Bad header name=" << name << " value=" << value;
      }
    } else {
      msg.getHeaders().add(name.toStdString(), value.toStdString());
    }
  }
void proxygen::compress::SimStreamingCallback::onHeadersComplete (HTTPHeaderSize , bool ack) [inline], [override], [virtual]
Implements proxygen::HPACK::StreamingCallback .
Definition at line 58 of file SimStreamingCallback.h.
References acknowledge, proxygen::HTTPHeaders::combine(), complete, proxygen::HTTPMessage::getHeaders(), proxygen::TimeUtilGeneric< ClockType >::getZeroTimePoint(), headersCompleteCb, holStart, proxygen::millisecondsSince(), msg, and proxygen::HTTPHeaders::set().
Referenced by proxygen::compress::QMINScheme::decode().
                                                            {
    auto combinedCookie = msg.getHeaders().combine(HTTP_HEADER_COOKIE, "; ");
    if (!combinedCookie.empty()) {
      msg.getHeaders().set(HTTP_HEADER_COOKIE, combinedCookie);
    }
    std::chrono::milliseconds holDelay(0);
    if (holStart != TimeUtil::getZeroTimePoint()) {
      holDelay = millisecondsSince(holStart);
    }
    acknowledge = ack;
    complete = true;
    if (headersCompleteCb) {
      headersCompleteCb(holDelay);
    }
  }
Member Data Documentation
bool proxygen::compress::SimStreamingCallback::acknowledge {false}
Definition at line 103 of file SimStreamingCallback.h.
Referenced by onHeadersComplete().
bool proxygen::compress::SimStreamingCallback::complete {false}
Definition at line 101 of file SimStreamingCallback.h.
Referenced by maybeMarkHolDelay(), and onHeadersComplete().
HPACK::DecodeError proxygen::compress::SimStreamingCallback::error {HPACK::DecodeError::NONE}
Definition at line 97 of file SimStreamingCallback.h.
Referenced by getResult(), onDecodeError(), and SimStreamingCallback().
std::function<void(std::chrono::milliseconds)> proxygen::compress::SimStreamingCallback::headersCompleteCb
Definition at line 99 of file SimStreamingCallback.h.
Referenced by onHeadersComplete(), and SimStreamingCallback().
TimePoint proxygen::compress::SimStreamingCallback::holStart {TimeUtil::getZeroTimePoint()}
Definition at line 100 of file SimStreamingCallback.h.
Referenced by maybeMarkHolDelay(), and onHeadersComplete().
bool proxygen::compress::SimStreamingCallback::isPublic {false}
Definition at line 102 of file SimStreamingCallback.h.
Referenced by onHeader().
proxygen::HTTPMessage proxygen::compress::SimStreamingCallback::msg
Definition at line 98 of file SimStreamingCallback.h.
Referenced by getResult(), onHeader(), onHeadersComplete(), and SimStreamingCallback().
uint16_t proxygen::compress::SimStreamingCallback::requestIndex {0}
Definition at line 94 of file SimStreamingCallback.h.
Referenced by proxygen::compress::HPACKScheme::decode(), proxygen::compress::QPACKScheme::decode(), and SimStreamingCallback().
uint16_t proxygen::compress::SimStreamingCallback::seqn {0}
Definition at line 96 of file SimStreamingCallback.h.
Referenced by proxygen::compress::HPACKScheme::decode(), proxygen::compress::QPACKScheme::decode(), and SimStreamingCallback().
The documentation for this class was generated from the following file:
proxygen/lib/http/codec/compress/experimental/simulator/SimStreamingCallback.h