proxygen::ByteEventTracker::Callback Class Reference
#include <ByteEventTracker.h>
Public Member Functions
virtual ~Callback ()
virtual void onPingReplyLatency (int64_t latency) noexcept=0
virtual void onLastByteEvent (HTTPTransaction *txn, uint64_t offset, bool eomTracked) noexcept=0
virtual void onDeleteAckEvent () noexcept=0
Detailed Description
Definition at line 31 of file ByteEventTracker.h.
Constructor & Destructor Documentation
virtual proxygen::ByteEventTracker::Callback::~Callback () [inline], [virtual]
Definition at line 33 of file ByteEventTracker.h.
References onDeleteAckEvent(), onLastByteEvent(), onPingReplyLatency(), and proxygen::ByteEventTracker::~ByteEventTracker().
{}
Member Function Documentation
virtual void proxygen::ByteEventTracker::Callback::onDeleteAckEvent () [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by ~Callback().
virtual void proxygen::ByteEventTracker::Callback::onLastByteEvent (HTTPTransaction * txn, uint64_t offset, bool eomTracked) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::ByteEventTracker::processByteEvents(), and ~Callback().
virtual void proxygen::ByteEventTracker::Callback::onPingReplyLatency (int64_t latency) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::ByteEventTracker::processByteEvents(), and ~Callback().
The documentation for this class was generated from the following file:
proxygen/lib/http/session/ByteEventTracker.h