proxygen::PushHandler::InnerPushHandler Class Reference
Public Member Functions
InnerPushHandler (PushHandler &handler)
void setTransaction (HTTPTransaction *) noexceptoverride
void detachTransaction () noexceptoverride
void onError (const HTTPException &error) noexceptoverride
void onEgressPaused () noexceptoverride
void onEgressResumed () noexceptoverride
Private Attributes
PushHandler & handler_
Detailed Description
Definition at line 31 of file PushHandler.h.
Constructor & Destructor Documentation
proxygen::PushHandler::InnerPushHandler::InnerPushHandler (PushHandler & handler) [inline], [explicit]
Definition at line 33 of file PushHandler.h.
      : handler_(handler) {}
Member Function Documentation
void proxygen::PushHandler::InnerPushHandler::detachTransaction () [inline], [override], [virtual], [noexcept]
Called once after a transaction successfully completes. It will be called even if a read or write error happened earlier. This is a terminal callback, which means that the HTTPTransaction object that gives this call will be invalid after this function completes.
Implements proxygen::HTTPTransactionHandler .
Definition at line 37 of file PushHandler.h.
References handler_, and proxygen::PushHandler::requestComplete().
{ handler_.requestComplete(); }
void proxygen::PushHandler::InnerPushHandler::onEgressPaused () [inline], [override], [virtual], [noexcept]
If the remote side's receive buffer fills up, this callback will be invoked so you can attempt to stop sending to the remote side.
Implements proxygen::HTTPTransactionHandler .
Definition at line 41 of file PushHandler.h.
References handler_, and proxygen::RequestHandler::onEgressPaused().
                                            {
      handler_.onEgressPaused();
    }
void proxygen::PushHandler::InnerPushHandler::onEgressResumed () [inline], [override], [virtual], [noexcept]
This callback lets you know that the remote side has resumed reading and you can now continue to send data.
Implements proxygen::HTTPTransactionHandler .
Definition at line 44 of file PushHandler.h.
References handler_, and proxygen::RequestHandler::onEgressResumed().
                                             {
      handler_.onEgressResumed();
    }
void proxygen::PushHandler::InnerPushHandler::onError (const HTTPException & error) [inline], [override], [virtual], [noexcept]
Can be called at any time before detachTransaction(). This callback implies that an error has occurred. To determine if ingress or egress is affected, check the direciont on the HTTPException. If the direction is INGRESS, it MAY still be possible to send egress.
Implements proxygen::HTTPTransactionHandler .
Definition at line 38 of file PushHandler.h.
References handler_, and proxygen::PushHandler::onError().
                                                               {
      handler_.onError(error.getProxygenError());
    }
void proxygen::PushHandler::InnerPushHandler::setTransaction (HTTPTransaction * txn) [inline], [override], [virtual], [noexcept]
Called once per transaction. This notifies the handler of which transaction it should talk to and will receive callbacks from.
Implements proxygen::HTTPTransactionHandler .
Definition at line 36 of file PushHandler.h.
{}
Member Data Documentation
PushHandler& proxygen::PushHandler::InnerPushHandler::handler_ [private]
Definition at line 49 of file PushHandler.h.
Referenced by detachTransaction(), onEgressPaused(), onEgressResumed(), and onError().
The documentation for this class was generated from the following file:
proxygen/httpserver/PushHandler.h