TestHandlerFactory::TestHandler Class Reference
Private Member Functions
void onRequest (std::unique_ptr< HTTPMessage >) noexceptoverride
void onBody (std::unique_ptr< folly::IOBuf >) noexceptoverride
void onUpgrade (UpgradeProtocol) noexceptoverride
void onEOM () noexceptoverride
void requestComplete () noexceptoverride
void onError (ProxygenError) noexceptoverride
Additional Inherited Members
Detailed Description
Definition at line 206 of file HTTPServerTest.cpp.
Member Function Documentation
void TestHandlerFactory::TestHandler::onBody (std::unique_ptr< folly::IOBuf > body) [inline], [override], [private], [virtual], [noexcept]
Invoked when we get part of body for the request.
Implements proxygen::RequestHandler .
Definition at line 209 of file HTTPServerTest.cpp.
{}
void TestHandlerFactory::TestHandler::onEOM () [inline], [override], [private], [virtual], [noexcept]
Invoked when we finish receiving the body.
Implements proxygen::RequestHandler .
Definition at line 213 of file HTTPServerTest.cpp.
References proxygen::ResponseBuilder::body(), proxygen::ResponseBuilder::header(), proxygen::ResponseBuilder::sendWithEOM(), and proxygen::ResponseBuilder::status().
                                   {
      std::string certHeader("");
      auto txn = CHECK_NOTNULL(downstream_->getTransaction());
      auto& transport = txn->getTransport();
      if (auto cert = transport.getUnderlyingTransport()->getPeerCert()) {
        certHeader = OpenSSLCertUtils::getCommonName(*cert).value_or("");
      }
      ResponseBuilder(downstream_)
          .status(200, "OK")
          .header("X-Client-CN", certHeader)
          .body(IOBuf::copyBuffer("hello"))
          .sendWithEOM();
    }
void TestHandlerFactory::TestHandler::onError (ProxygenError err) [inline], [override], [private], [virtual], [noexcept]
Request failed. Maybe because of read/write error on socket or client not being able to send request in time.
NOTE: Can be invoked at any time (except for before onRequest).
No more callbacks will be invoked after this. You should clean up after yourself.
Implements proxygen::RequestHandler .
Definition at line 229 of file HTTPServerTest.cpp.
{ delete this; }
void TestHandlerFactory::TestHandler::onRequest (std::unique_ptr< HTTPMessage > headers) [inline], [override], [private], [virtual], [noexcept]
Invoked when we have successfully fetched headers from client. This will always be the first callback invoked on your handler.
Implements proxygen::RequestHandler .
Definition at line 207 of file HTTPServerTest.cpp.
                                                                 {
    }
void TestHandlerFactory::TestHandler::onUpgrade (UpgradeProtocol prot) [inline], [override], [private], [virtual], [noexcept]
Invoked when the session has been upgraded to a different protocol
Implements proxygen::RequestHandler .
Definition at line 210 of file HTTPServerTest.cpp.
                                                      {
    }
void TestHandlerFactory::TestHandler::requestComplete () [inline], [override], [private], [virtual], [noexcept]
Invoked when request processing has been completed and nothing more needs to be done. This may be a good place to log some stats and clean up resources. This is distinct from onEOM() because it is invoked after the response is fully sent. Once this callback has been received, downstream_ should be considered invalid.
Implements proxygen::RequestHandler .
Definition at line 227 of file HTTPServerTest.cpp.
{ delete this; }
The documentation for this class was generated from the following file:
proxygen/httpserver/tests/HTTPServerTest.cpp