proxygen::HTTPRequestVerifier Class Reference
#include <HTTPRequestVerifier.h>
Public Member Functions
HTTPRequestVerifier ()
void reset (HTTPMessage *msg)
bool setMethod (folly::StringPiece method)
bool setPath (folly::StringPiece path)
bool setScheme (folly::StringPiece scheme)
bool setAuthority (folly::StringPiece authority)
bool setUpgradeProtocol (folly::StringPiece protocol)
bool validate ()
void setMessage (HTTPMessage *msg)
void setHasMethod (bool hasMethod)
void setHasPath (bool hasPath)
void setHasScheme (bool hasScheme)
void setHasAuthority (bool hasAuthority)
void setHasUpgradeProtocol (bool val)
bool hasUpgradeProtocol ()
Public Attributes
std::string error
Private Attributes
HTTPMessage * msg_ {nullptr}
bool hasMethod_ {false}
bool hasPath_ {false}
bool hasScheme_ {false}
bool hasAuthority_ {false}
bool hasUpgradeProtocol_ {false}
Detailed Description
Definition at line 18 of file HTTPRequestVerifier.h.
Constructor & Destructor Documentation
proxygen::HTTPRequestVerifier::HTTPRequestVerifier () [inline], [explicit]
Definition at line 20 of file HTTPRequestVerifier.h.
{}
Member Function Documentation
bool proxygen::HTTPRequestVerifier::hasUpgradeProtocol () [inline]
Definition at line 150 of file HTTPRequestVerifier.h.
References hasUpgradeProtocol_.
Referenced by proxygen::HTTP2Codec::onHeadersComplete().
                            {
    return hasUpgradeProtocol_;
  }
void proxygen::HTTPRequestVerifier::reset (HTTPMessage * msg) [inline]
Definition at line 22 of file HTTPRequestVerifier.h.
References error, hasAuthority_, hasMethod_, hasPath_, hasScheme_, hasUpgradeProtocol_, and msg_.
Referenced by proxygen::HeaderDecodeInfo::init().
                               {
    msg_ = msg;
    error = "";
    hasMethod_ = false;
    hasPath_ = false;
    hasScheme_ = false;
    hasAuthority_ = false;
    hasUpgradeProtocol_ = false;
  }
bool proxygen::HTTPRequestVerifier::setAuthority (folly::StringPiece authority) [inline]
Definition at line 81 of file HTTPRequestVerifier.h.
References proxygen::HTTPHeaders::add(), error, proxygen::HTTPMessage::getHeaders(), hasAuthority_, msg_, proxygen::CodecUtil::STRICT, and proxygen::CodecUtil::validateHeaderValue().
Referenced by proxygen::HeaderDecodeInfo::onHeader().
                                                {
    if (hasAuthority_) {
      error = "Duplicate authority";
      return false;
    }
    if (!CodecUtil::validateHeaderValue(authority, CodecUtil::STRICT)) {
      error = "Invalid authority";
      return false;
    }
    hasAuthority_ = true;
    assert(msg_ != nullptr);
    msg_->getHeaders().add(HTTP_HEADER_HOST, authority.str());
    return true;
  }
void proxygen::HTTPRequestVerifier::setHasAuthority (bool hasAuthority) [inline]
Definition at line 142 of file HTTPRequestVerifier.h.
References hasAuthority_.
                                          {
    hasAuthority_ = hasAuthority;
  }
void proxygen::HTTPRequestVerifier::setHasMethod (bool hasMethod) [inline]
Definition at line 130 of file HTTPRequestVerifier.h.
References hasMethod_.
                                    {
    hasMethod_ = hasMethod;
  }
void proxygen::HTTPRequestVerifier::setHasPath (bool hasPath) [inline]
Definition at line 134 of file HTTPRequestVerifier.h.
References hasPath_.
                                {
    hasPath_ = hasPath;
  }
void proxygen::HTTPRequestVerifier::setHasScheme (bool hasScheme) [inline]
Definition at line 138 of file HTTPRequestVerifier.h.
References hasScheme_.
                                    {
    hasScheme_ = hasScheme;
  }
void proxygen::HTTPRequestVerifier::setHasUpgradeProtocol (bool val) [inline]
Definition at line 146 of file HTTPRequestVerifier.h.
References hasUpgradeProtocol_.
Referenced by setUpgradeProtocol().
                                       {
    hasUpgradeProtocol_ = val;
  }
void proxygen::HTTPRequestVerifier::setMessage (HTTPMessage * msg) [inline]
Definition at line 126 of file HTTPRequestVerifier.h.
References msg_.
                                    {
    msg_ = msg;
  }
bool proxygen::HTTPRequestVerifier::setMethod (folly::StringPiece method) [inline]
Definition at line 32 of file HTTPRequestVerifier.h.
References error, hasMethod_, msg_, proxygen::HTTPMessage::setMethod(), and proxygen::CodecUtil::validateMethod().
Referenced by proxygen::HeaderDecodeInfo::onHeader().
                                          {
    if (hasMethod_) {
      error = "Duplicate method";
      return false;
    }
    if (!CodecUtil::validateMethod(method)) {
      error = "Invalid method";
      return false;
    }
    hasMethod_ = true;
    assert(msg_ != nullptr);
    msg_->setMethod(method);
    return true;
  }
bool proxygen::HTTPRequestVerifier::setPath (folly::StringPiece path) [inline]
Definition at line 47 of file HTTPRequestVerifier.h.
References error, hasPath_, msg_, proxygen::HTTPMessage::setURL(), and proxygen::CodecUtil::validateURL().
Referenced by proxygen::HeaderDecodeInfo::onHeader().
                                      {
    if (hasPath_) {
      error = "Duplicate path";
      return false;
    }
    if (!CodecUtil::validateURL(path)) {
      error = "Invalid url";
      return false;
    }
    hasPath_ = true;
    assert(msg_ != nullptr);
    msg_->setURL(path.str());
    return true;
  }
bool proxygen::HTTPRequestVerifier::setScheme (folly::StringPiece scheme) [inline]
Definition at line 62 of file HTTPRequestVerifier.h.
References error, hasScheme_, proxygen::headers::kHttps, msg_, proxygen::HTTPMessage::setSecure(), and proxygen::CodecUtil::validateMethod().
Referenced by proxygen::HeaderDecodeInfo::onHeader().
                                          {
    if (hasScheme_) {
      error = "Duplicate scheme";
      return false;
    }
    // This just checks for alpha chars
    if (!CodecUtil::validateMethod(scheme)) {
      error = "Invalid scheme";
      return false;
    }
    hasScheme_ = true;
    // TODO support non http/https schemes
    if (scheme == headers::kHttps) {
      assert(msg_ != nullptr);
      msg_->setSecure(true);
    }
    return true;
  }
bool proxygen::HTTPRequestVerifier::setUpgradeProtocol (folly::StringPiece protocol) [inline]
Definition at line 96 of file HTTPRequestVerifier.h.
References error, hasUpgradeProtocol_, msg_, setHasUpgradeProtocol(), and proxygen::HTTPMessage::setUpgradeProtocol().
Referenced by proxygen::HeaderDecodeInfo::onHeader().
                                                     {
    if (hasUpgradeProtocol_) {
      error = "Duplicate protocol";
      return false;
    }
    setHasUpgradeProtocol(true);
    msg_->setUpgradeProtocol(folly::to<std::string>(protocol));
    return true;
  }
bool proxygen::HTTPRequestVerifier::validate () [inline]
Definition at line 106 of file HTTPRequestVerifier.h.
References proxygen::CONNECT, error, proxygen::HTTPMessage::getMethod(), hasAuthority_, hasMethod_, hasPath_, hasScheme_, hasUpgradeProtocol_, and msg_.
Referenced by proxygen::HeaderDecodeInfo::onHeadersComplete().
                  {
    if (error.size()) {
      return false;
    }
    if (msg_->getMethod() == HTTPMethod::CONNECT) {
      if ((!hasUpgradeProtocol_ &&
           (!hasMethod_ || !hasAuthority_ || hasScheme_ || hasPath_)) ||
          (hasUpgradeProtocol_ && (!hasScheme_ || !hasPath_))) {
        error = folly::to<std::string>("Malformed CONNECT request m/a/s/pa/pr=",
                                hasMethod_, hasAuthority_,
                                hasScheme_, hasPath_, hasUpgradeProtocol_);
      }
    } else if (hasUpgradeProtocol_ || !hasMethod_ || !hasScheme_ || !hasPath_) {
      error = folly::to<std::string>("Malformed request m/a/s/pa/pr=",
                                hasMethod_, hasAuthority_,
                                hasScheme_, hasPath_, hasUpgradeProtocol_);
    }
    return error.empty();
  }
Member Data Documentation
std::string proxygen::HTTPRequestVerifier::error
Definition at line 154 of file HTTPRequestVerifier.h.
Referenced by proxygen::HeaderDecodeInfo::onHeadersComplete(), reset(), setAuthority(), setMethod(), setPath(), setScheme(), setUpgradeProtocol(), and validate().
bool proxygen::HTTPRequestVerifier::hasAuthority_ {false} [private]
Definition at line 161 of file HTTPRequestVerifier.h.
Referenced by reset(), setAuthority(), setHasAuthority(), and validate().
bool proxygen::HTTPRequestVerifier::hasMethod_ {false} [private]
Definition at line 158 of file HTTPRequestVerifier.h.
Referenced by reset(), setHasMethod(), setMethod(), and validate().
bool proxygen::HTTPRequestVerifier::hasPath_ {false} [private]
Definition at line 159 of file HTTPRequestVerifier.h.
Referenced by reset(), setHasPath(), setPath(), and validate().
bool proxygen::HTTPRequestVerifier::hasScheme_ {false} [private]
Definition at line 160 of file HTTPRequestVerifier.h.
Referenced by reset(), setHasScheme(), setScheme(), and validate().
bool proxygen::HTTPRequestVerifier::hasUpgradeProtocol_ {false} [private]
Definition at line 162 of file HTTPRequestVerifier.h.
Referenced by hasUpgradeProtocol(), reset(), setHasUpgradeProtocol(), setUpgradeProtocol(), and validate().
HTTPMessage* proxygen::HTTPRequestVerifier::msg_ {nullptr} [private]
Definition at line 157 of file HTTPRequestVerifier.h.
Referenced by reset(), setAuthority(), setMessage(), setMethod(), setPath(), setScheme(), setUpgradeProtocol(), and validate().
The documentation for this class was generated from the following file:
proxygen/lib/http/codec/HTTPRequestVerifier.h