proxygen::HTTPUpstreamSession Class Reference
#include <HTTPUpstreamSession.h>
Public Types
using FilterIteratorFn = std::function< void(HTTPCodecFilter *)>
Public Member Functions
HTTPUpstreamSession (const WheelTimerInstance &timeout, folly::AsyncTransportWrapper::UniquePtr &&sock, const folly::SocketAddress &localAddr, const folly::SocketAddress &peerAddr, std::unique_ptr< HTTPCodec > codec, const wangle::TransportInfo &tinfo, InfoCallback *infoCallback, uint8_t maxVirtualPri=0, std::shared_ptr< const PriorityMapFactory > priorityMapFactory=std::shared_ptr< const PriorityMapFactory >())
HTTPUpstreamSession (folly::HHWheelTimer *timeout, folly::AsyncTransportWrapper::UniquePtr &&sock, const folly::SocketAddress &localAddr, const folly::SocketAddress &peerAddr, std::unique_ptr< HTTPCodec > codec, const wangle::TransportInfo &tinfo, InfoCallback *infoCallback, uint8_t maxVirtualPri=0, std::shared_ptr< const PriorityMapFactory > priorityMapFactory=std::shared_ptr< const PriorityMapFactory >())
void detachTransactions ()
void attachThreadLocals (folly::EventBase *eventBase, folly::SSLContextPtr sslContext, const WheelTimerInstance &timeout, HTTPSessionStats *stats, FilterIteratorFn fn, HeaderCodec::Stats *headerCodecStats, HTTPSessionController *controller) override
void detachThreadLocals (bool detachSSLContext=false) override
void startNow () override
HTTPTransaction * newTransaction (HTTPTransaction::Handler *handler) override
bool isReplaySafe () const override
bool isReusable () const override
bool isClosing () const override
void drain () override
virtual folly::Optional< const HTTPMessage::HTTPPriority > getHTTPPriority (uint8_t level) override
Private Member Functions
~HTTPUpstreamSession () override
void setupOnHeadersComplete (HTTPTransaction *, HTTPMessage *) override
HTTPTransaction::Handler * getTransactionTimeoutHandler (HTTPTransaction *txn) override
bool allTransactionsStarted () const override
bool onNativeProtocolUpgrade (HTTPCodec::StreamID streamID, CodecProtocol protocol, const std::string &protocolString, HTTPMessage &msg) override
void maybeAttachSSLContext (folly::SSLContextPtr sslContext) const
void maybeDetachSSLContext () const
Private Attributes
uint8_t maxVirtualPriorityLevel_ {0}
std::shared_ptr< const PriorityMapFactory > priorityMapFactory_
std::unique_ptr< PriorityAdapter > priorityAdapter_
Additional Inherited Members
Detailed Description
Definition at line 22 of file HTTPUpstreamSession.h.
Member Typedef Documentation
using proxygen::HTTPUpstreamSession::FilterIteratorFn = std::function<void(HTTPCodecFilter*)>
Definition at line 89 of file HTTPUpstreamSession.h.
Constructor & Destructor Documentation
proxygen::HTTPUpstreamSession::HTTPUpstreamSession (const WheelTimerInstance & timeout, folly::AsyncTransportWrapper::UniquePtr && sock, const folly::SocketAddress & localAddr, const folly::SocketAddress & peerAddr, std::unique_ptr< HTTPCodec > codec, const wangle::TransportInfo & tinfo, InfoCallback * infoCallback, uint8_t maxVirtualPri = 0, std::shared_ptr< const PriorityMapFactory > priorityMapFactory = std::shared_ptr<const PriorityMapFactory>()) [inline]
Parameters
sock An open socket on which any applicable TLS handshaking has been completed already.
localAddr Address and port of the local end of the socket.
peerAddr Address and port of the remote end of the socket.
codec A codec with which to parse/generate messages in whatever HTTP-like wire format this session needs.
maxVirtualPri Number of virtual priority nodes to represent fixed priority levels.
Definition at line 34 of file HTTPUpstreamSession.h.
References proxygen::HTTPSessionBase::codec_, proxygen::HTTPCodec::getTransportDirection(), proxygen::HTTPSession::sock_, and proxygen::UPSTREAM.
                                                     :
    HTTPSession(
        timeout,
        std::move(sock),
        localAddr,
        peerAddr,
        nullptr,
        std::move(codec),
        tinfo,
        infoCallback),
    maxVirtualPriorityLevel_(priorityMapFactory ? 0 : maxVirtualPri),
    priorityMapFactory_(priorityMapFactory) {
    if (sock_) {
      auto asyncSocket = sock_->getUnderlyingTransport<folly::AsyncSocket>();
      if (asyncSocket) {
        asyncSocket->setBufferCallback(this);
      }
    }
    CHECK_EQ(codec_->getTransportDirection(), TransportDirection::UPSTREAM);
  }
proxygen::HTTPUpstreamSession::HTTPUpstreamSession (folly::HHWheelTimer * timeout, folly::AsyncTransportWrapper::UniquePtr && sock, const folly::SocketAddress & localAddr, const folly::SocketAddress & peerAddr, std::unique_ptr< HTTPCodec > codec, const wangle::TransportInfo & tinfo, InfoCallback * infoCallback, uint8_t maxVirtualPri = 0, std::shared_ptr< const PriorityMapFactory > priorityMapFactory = std::shared_ptr<const PriorityMapFactory>()) [inline]
Definition at line 66 of file HTTPUpstreamSession.h.
                                                     :
    HTTPUpstreamSession(
        WheelTimerInstance(timeout),
        std::move(sock),
        localAddr,
        peerAddr,
        std::move(codec),
        tinfo,
        infoCallback,
        maxVirtualPri,
        priorityMapFactory) {
  }
proxygen::HTTPUpstreamSession::~HTTPUpstreamSession () [override], [private]
Definition at line 20 of file HTTPUpstreamSession.cpp.
Referenced by getHTTPPriority().
{}
Member Function Documentation
bool proxygen::HTTPUpstreamSession::allTransactionsStarted () const [override], [private], [virtual]
Implements proxygen::HTTPSession .
Definition at line 119 of file HTTPUpstreamSession.cpp.
References proxygen::HTTPSession::transactions_.
Referenced by setupOnHeadersComplete().
                                                       {
  for (const auto& txn: transactions_) {
    if (!txn.second.isPushed() && !txn.second.isEgressStarted()) {
      return false;
    }
  }
  return true;
}
void proxygen::HTTPUpstreamSession::attachThreadLocals (folly::EventBase * eventBase, folly::SSLContextPtr sslContext, const WheelTimerInstance & timeout, HTTPSessionStats * stats, FilterIteratorFn fn, HeaderCodec::Stats * headerCodecStats, HTTPSessionController * controller) [override], [virtual]
Implements proxygen::HTTPSessionBase .
Definition at line 166 of file HTTPUpstreamSession.cpp.
References proxygen::HTTP2PriorityQueue::attachThreadLocals(), proxygen::HTTPSessionBase::codec_, proxygen::FilterChain< T1, T2, FilterType, set_callback, TakeOwnership >::foreach(), maybeAttachSSLContext(), proxygen::HTTPSession::rescheduleLoopCallbacks(), proxygen::HTTPSession::resumeReadsImpl(), proxygen::HTTPSessionBase::setController(), proxygen::HTTPCodec::setHeaderCodecStats(), proxygen::HTTPSession::setSessionStats(), proxygen::HTTPSession::sock_, proxygen::HTTPSession::timeout_, and proxygen::HTTPSession::txnEgressQueue_.
                                     {
  txnEgressQueue_.attachThreadLocals(timeout);
  timeout_ = timeout;
  setController(controller);
  setSessionStats(stats);
  if (sock_) {
    sock_->attachEventBase(eventBase);
    maybeAttachSSLContext(sslContext);
  }
  codec_.foreach(fn);
  codec_->setHeaderCodecStats(headerCodecStats);
  resumeReadsImpl();
  rescheduleLoopCallbacks();
}
void proxygen::HTTPUpstreamSession::detachThreadLocals (bool detachSSLContext = false) [override], [virtual]
Implements proxygen::HTTPSessionBase .
Definition at line 198 of file HTTPUpstreamSession.cpp.
References proxygen::HTTPSession::cancelLoopCallbacks(), proxygen::HTTPSessionBase::codec_, proxygen::HTTP2PriorityQueue::detachThreadLocals(), maybeDetachSSLContext(), proxygen::HTTPSession::pauseReadsImpl(), proxygen::HTTPSessionBase::setController(), proxygen::HTTPCodec::setHeaderCodecStats(), proxygen::HTTPSession::setSessionStats(), proxygen::HTTPSession::sock_, proxygen::HTTPSession::transactions_, and proxygen::HTTPSession::txnEgressQueue_.
                                                             {
  CHECK(transactions_.empty());
  cancelLoopCallbacks();
  pauseReadsImpl();
  if (sock_) {
    if (detachSSLContext) {
      maybeDetachSSLContext();
    }
    sock_->detachEventBase();
  }
  txnEgressQueue_.detachThreadLocals();
  setController(nullptr);
  setSessionStats(nullptr);
  // The codec filters *shouldn't* be accessible while the socket is detached,
  // I hope
  codec_->setHeaderCodecStats(nullptr);
  auto cm = getConnectionManager();
  if (cm) {
    cm->removeConnection(this);
  }
}
void proxygen::HTTPUpstreamSession::detachTransactions ()
Definition at line 158 of file HTTPUpstreamSession.cpp.
References proxygen::HTTPSession::detach(), and proxygen::HTTPSession::transactions_.
                                             {
  while (!transactions_.empty()) {
    auto txn = transactions_.begin();
    detach(&txn->second);
  }
}
void proxygen::HTTPUpstreamSession::drain () [inline], [override], [virtual]
Drains the current transactions and prevents new transactions from being created on this session. When the number of transactions reaches zero, this session will shutdown the transport and delete itself.
Reimplemented from proxygen::HTTPSession .
Definition at line 135 of file HTTPUpstreamSession.h.
References proxygen::HTTPSession::drain().
Referenced by ProxyService::SessionWrapper::~SessionWrapper().
                        {
    HTTPSession::drain();
  }
virtual folly::Optional<const HTTPMessage::HTTPPriority> proxygen::HTTPUpstreamSession::getHTTPPriority (uint8_t level) [inline], [override], [virtual]
Reimplemented from proxygen::HTTPSession .
Definition at line 139 of file HTTPUpstreamSession.h.
References proxygen::HTTPSession::getHTTPPriority(), priorityAdapter_, and ~HTTPUpstreamSession().
                             {
   if (!priorityAdapter_) {
     return HTTPSession::getHTTPPriority(level);
   }
   return priorityAdapter_->getHTTPPriority(level);
 }
HTTPTransaction::Handler * proxygen::HTTPUpstreamSession::getTransactionTimeoutHandler (HTTPTransaction * txn) [override], [private], [virtual]
Called by transactionTimeout() if the transaction has no handler.
Implements proxygen::HTTPSession .
Definition at line 113 of file HTTPUpstreamSession.cpp.
Referenced by setupOnHeadersComplete().
                        {
  // No special handler for upstream requests that time out
  return nullptr;
}
bool proxygen::HTTPUpstreamSession::isClosing () const [override], [virtual]
Returns true if the session is shutting down
Implements proxygen::HTTPSessionBase .
Definition at line 52 of file HTTPUpstreamSession.cpp.
References proxygen::HTTPSession::draining_, proxygen::HTTPSession::readsShutdown(), proxygen::HTTPSession::resetAfterDrainingWrites_, proxygen::HTTPSession::sock_, proxygen::HTTPSession::writesDraining_, and proxygen::HTTPSession::writesShutdown().
Referenced by isReusable().
                                          {
  VLOG(5) << "isClosing: " << *this
    << ", sock_->good()=" << sock_->good()
    << ", draining_=" << draining_
    << ", readsShutdown()=" << readsShutdown()
    << ", writesShutdown()=" << writesShutdown()
    << ", writesDraining_=" << writesDraining_
    << ", resetAfterDrainingWrites_=" << resetAfterDrainingWrites_;
  return
    !sock_->good() ||
    draining_ ||
    readsShutdown() ||
    writesShutdown() ||
    writesDraining_ ||
    resetAfterDrainingWrites_;
}
bool proxygen::HTTPUpstreamSession::isReplaySafe () const [override], [virtual]
Returns true if the underlying transport has completed full handshake.
Implements proxygen::HTTPSessionBase .
Definition at line 22 of file HTTPUpstreamSession.cpp.
References proxygen::HTTPSession::sock_.
                                             {
  return sock_ ? sock_->isReplaySafe() : false;
}
bool proxygen::HTTPUpstreamSession::isReusable () const [override], [virtual]
Returns true if this session has no open transactions and the underlying transport can be used again in a new request.
Implements proxygen::HTTPSessionBase .
Definition at line 26 of file HTTPUpstreamSession.cpp.
References proxygen::HTTPSessionBase::codec_, proxygen::HTTPSession::hasMoreWrites(), proxygen::HTTPSession::ingressError_, proxygen::HTTPCodec::isBusy(), isClosing(), proxygen::HTTPCodec::isReusable(), proxygen::HTTPSession::liveTransactions_, proxygen::HTTPSession::numActiveWrites_, proxygen::HTTPSession::sock_, proxygen::HTTPCodec::supportsParallelRequests(), and proxygen::HTTPSession::writeTimeout_.
                                           {
  VLOG(4) << "isReusable: " << *this
    << ", liveTransactions_=" << liveTransactions_
    << ", isClosing()=" << isClosing()
    << ", sock_->connecting()=" << sock_->connecting()
    << ", codec_->isReusable()=" << codec_->isReusable()
    << ", codec_->isBusy()=" << codec_->isBusy()
    << ", numActiveWrites_=" << numActiveWrites_
    << ", writeTimeout_.isScheduled()=" << writeTimeout_.isScheduled()
    << ", ingressError_=" << ingressError_
    << ", hasMoreWrites()=" << hasMoreWrites()
    << ", codec_->supportsParallelRequests()="
         << codec_->supportsParallelRequests();
  return
    !isClosing() &&
    !sock_->connecting() &&
    codec_->isReusable() &&
    !codec_->isBusy() &&
    !ingressError_ &&
    (codec_->supportsParallelRequests() || (
      // These conditions only apply to serial codec sessions
      !hasMoreWrites() &&
      liveTransactions_ == 0 &&
      !writeTimeout_.isScheduled()));
}
void proxygen::HTTPUpstreamSession::maybeAttachSSLContext (folly::SSLContextPtr sslContext) const [private]
Definition at line 187 of file HTTPUpstreamSession.cpp.
References proxygen::HTTPSession::sock_.
Referenced by attachThreadLocals(), and setupOnHeadersComplete().
                                         {
#ifndef NO_ASYNCSSLSOCKET
  auto sslSocket = sock_->getUnderlyingTransport<folly::AsyncSSLSocket>();
  if (sslSocket && sslContext) {
    sslSocket->attachSSLContext(sslContext);
  }
#endif
}
void proxygen::HTTPUpstreamSession::maybeDetachSSLContext () const [private]
Definition at line 220 of file HTTPUpstreamSession.cpp.
References proxygen::HTTPSession::sock_.
Referenced by detachThreadLocals(), and setupOnHeadersComplete().
                                                      {
#ifndef NO_ASYNCSSLSOCKET
  auto sslSocket = sock_->getUnderlyingTransport<folly::AsyncSSLSocket>();
  if (sslSocket) {
    sslSocket->detachSSLContext();
  }
#endif
}
HTTPTransaction * proxygen::HTTPUpstreamSession::newTransaction (HTTPTransaction::Handler * handler) [override], [virtual]
Creates a new transaction on this upstream session. Invoking this function also has the side-affect of starting reads after this event loop completes.
Parameters
handler The request handler to attach to this transaction. It must not be null.
Implements proxygen::HTTPSessionBase .
Definition at line 91 of file HTTPUpstreamSession.cpp.
References proxygen::HTTPSessionBase::codec_, proxygen::HTTPCodec::createStream(), proxygen::HTTPSession::createTransaction(), proxygen::HTTPSession::draining_, proxygen::HTTPCodec::NoExAttributes, proxygen::HTTPCodec::NoStream, proxygen::HTTPSession::setNewTransactionPauseState(), proxygen::HTTPSession::started_, startNow(), and proxygen::HTTPSessionBase::supportsMoreTransactions().
Referenced by CurlService::CurlClient::connectSuccess(), and ProxyService::ProxyHandler::connectSuccess().
                                                                   {
  if (!supportsMoreTransactions() || draining_) {
    // This session doesn't support any more parallel transactions
    return nullptr;
  }
  if (!started_) {
    startNow();
  }
  auto txn = createTransaction(codec_->createStream(), HTTPCodec::NoStream,
                               HTTPCodec::NoExAttributes);
  if (txn) {
    DestructorGuard dg(this);
    auto txnID = txn->getID();
    txn->setHandler(CHECK_NOTNULL(handler));
    setNewTransactionPauseState(txnID);
  }
  return txn;
}
bool proxygen::HTTPUpstreamSession::onNativeProtocolUpgrade (HTTPCodec::StreamID , CodecProtocol , const std::string & , HTTPMessage &) [override], [private], [virtual]
Called upon receipt of a valid protocol switch. Return false if protocol switch could not be completed.
Reimplemented from proxygen::HTTPCodec::Callback .
Definition at line 128 of file HTTPUpstreamSession.cpp.
References proxygen::HTTPCodec::addPriorityNodes(), proxygen::HTTPSessionBase::codec_, proxygen::HTTP_2, maxVirtualPriorityLevel_, proxygen::HTTPSession::onNativeProtocolUpgradeImpl(), proxygen::HTTPSession::scheduleWrite(), proxygen::HTTPSession::txnEgressQueue_, proxygen::UPSTREAM, and proxygen::HTTPSession::writeBuf_.
Referenced by setupOnHeadersComplete().
                {
  VLOG(4) << *this << " onNativeProtocolUpgrade streamID=" << streamID <<
    " protocol=" << protocolString;
  if (protocol != CodecProtocol::HTTP_2) {
    return false;
  }
  // Create the new Codec
  std::unique_ptr<HTTPCodec> codec =
      std::make_unique<HTTP2Codec>(TransportDirection::UPSTREAM);
  bool ret = onNativeProtocolUpgradeImpl(streamID, std::move(codec),
                                         protocolString);
  if (ret) {
    auto bytes = codec_->addPriorityNodes(
      txnEgressQueue_,
      writeBuf_,
      maxVirtualPriorityLevel_);
    if (bytes) {
      scheduleWrite();
    }
  }
  return ret;
}
void proxygen::HTTPUpstreamSession::setupOnHeadersComplete (HTTPTransaction * , HTTPMessage *) [inline], [override], [private], [virtual]
Called by onHeadersComplete(). Currently a no-op for upstream.
Implements proxygen::HTTPSession .
Definition at line 153 of file HTTPUpstreamSession.h.
References allTransactionsStarted(), getTransactionTimeoutHandler(), maybeAttachSSLContext(), maybeDetachSSLContext(), onNativeProtocolUpgrade(), and streamID.
                                                   {}
void proxygen::HTTPUpstreamSession::startNow () [override], [virtual]
Start reading from the transport and send any introductory messages to the remote side. This function must be called once per session to begin reads.
Reimplemented from proxygen::HTTPSession .
Definition at line 69 of file HTTPUpstreamSession.cpp.
References proxygen::HTTPCodec::addPriorityNodes(), proxygen::HTTPSessionBase::codec_, maxVirtualPriorityLevel_, priorityAdapter_, priorityMapFactory_, proxygen::HTTPSession::scheduleWrite(), proxygen::HTTPSession::startNow(), proxygen::HTTPSession::txnEgressQueue_, and proxygen::HTTPSession::writeBuf_.
Referenced by newTransaction().
                                   {
  // startNow in base class CHECKs this session has not started.
  HTTPSession::startNow();
  // Upstream specific:
  // create virtual priority nodes and send Priority frames to peer if necessary
  if (priorityMapFactory_) {
    priorityAdapter_ = priorityMapFactory_->createVirtualStreams(this);
    scheduleWrite();
  } else {
    // TODO/T17420249 Move this to the PriorityAdapter and remove it from the
    // codec.
    auto bytes = codec_->addPriorityNodes(
        txnEgressQueue_,
        writeBuf_,
        maxVirtualPriorityLevel_);
    if (bytes) {
      scheduleWrite();
    }
  }
}
Member Data Documentation
uint8_t proxygen::HTTPUpstreamSession::maxVirtualPriorityLevel_ {0} [private]
Definition at line 172 of file HTTPUpstreamSession.h.
Referenced by onNativeProtocolUpgrade(), and startNow().
std::unique_ptr<PriorityAdapter> proxygen::HTTPUpstreamSession::priorityAdapter_ [private]
Definition at line 175 of file HTTPUpstreamSession.h.
Referenced by getHTTPPriority(), and startNow().
std::shared_ptr<const PriorityMapFactory> proxygen::HTTPUpstreamSession::priorityMapFactory_ [private]
Definition at line 174 of file HTTPUpstreamSession.h.
Referenced by startNow().
The documentation for this class was generated from the following files:
proxygen/lib/http/session/HTTPUpstreamSession.h
proxygen/lib/http/session/HTTPUpstreamSession.cpp