proxygen::QPACKContext Class Reference
#include <QPACKContext.h>
Public Member Functions
QPACKContext (uint32_t tableSize, bool trackReferences)
~QPACKContext ()
const HPACKHeader & getHeader (bool isStatic, uint32_t index, uint32_t base, bool aboveBase)
const QPACKHeaderTable & getTable () const
uint32_t getTableSize () const
uint32_t getBytesStored () const
uint32_t getHeadersStored () const
void seedHeaderTable (std::vector< HPACKHeader > &headers)
void describe (std::ostream &os) const
Protected Member Functions
const StaticHeaderTable & getStaticTable () const
Protected Attributes
QPACKHeaderTable table_
Detailed Description
Definition at line 18 of file QPACKContext.h.
Constructor & Destructor Documentation
proxygen::QPACKContext::QPACKContext (uint32_t tableSize, bool trackReferences)
Definition at line 14 of file QPACKContext.cpp.
                                                                   :
    table_(tableSize, trackReferences) {
}
proxygen::QPACKContext::~QPACKContext () [inline]
Definition at line 21 of file QPACKContext.h.
References getHeader().
{}
Member Function Documentation
void proxygen::QPACKContext::describe (std::ostream & os) const
Definition at line 39 of file QPACKContext.cpp.
References table_.
Referenced by getHeadersStored(), and proxygen::operator<<().
                                                {
  os << table_;
}
uint32_t proxygen::QPACKContext::getBytesStored () const [inline]
Definition at line 37 of file QPACKContext.h.
References proxygen::HeaderTable::bytes(), and table_.
                                  {
    return table_.bytes();
  }
const HPACKHeader & proxygen::QPACKContext::getHeader (bool isStatic, uint32_t index, uint32_t base, bool aboveBase)
Returns
header at the given index by composing dynamic and static tables
Definition at line 18 of file QPACKContext.cpp.
References proxygen::HeaderTable::getHeader(), proxygen::QPACKHeaderTable::getHeader(), getStaticTable(), and table_.
Referenced by proxygen::QPACKDecoder::decodeIndexedHeaderQ(), proxygen::QPACKDecoder::decodeLiteralHeaderQ(), TEST(), and ~QPACKContext().
                                                           {
  if (isStatic) {
    return getStaticTable().getHeader(index);
  }
  if (aboveBase) {
    base += index;
    index = 1;
  }
  return table_.getHeader(index, base);
}
uint32_t proxygen::QPACKContext::getHeadersStored () const [inline]
Definition at line 41 of file QPACKContext.h.
References describe(), seedHeaderTable(), proxygen::HeaderTable::size(), and table_.
Referenced by TEST().
                                    {
    return table_.size();
  }
const StaticHeaderTable& proxygen::QPACKContext::getStaticTable () const [inline], [protected]
Definition at line 50 of file QPACKContext.h.
References proxygen::QPACKStaticHeaderTable::get().
Referenced by proxygen::QPACKEncoder::encodeHeaderQ(), getHeader(), proxygen::QPACKEncoder::getNameIndexQ(), and proxygen::QPACKDecoder::isValid().
                                                  {
    return QPACKStaticHeaderTable::get();
  }
const QPACKHeaderTable& proxygen::QPACKContext::getTable () const [inline]
Definition at line 29 of file QPACKContext.h.
References table_.
Referenced by proxygen::hpack::encodeDecode(), and TEST().
                                           {
    return table_;
  }
uint32_t proxygen::QPACKContext::getTableSize () const [inline]
Definition at line 33 of file QPACKContext.h.
References proxygen::HeaderTable::capacity(), and table_.
                                {
    return table_.capacity();
  }
void proxygen::QPACKContext::seedHeaderTable (std::vector< HPACKHeader > & headers)
Definition at line 32 of file QPACKContext.cpp.
References proxygen::QPACKHeaderTable::add(), and table_.
Referenced by getHeadersStored().
                                   {
  for (auto& header: headers) {
    table_.add(std::move(header));
  }
}
Member Data Documentation
QPACKHeaderTable proxygen::QPACKContext::table_ [protected]
Definition at line 54 of file QPACKContext.h.
Referenced by proxygen::QPACKDecoder::decodeEncoderStreamInstruction(), proxygen::QPACKDecoder::decodeLiteralHeaderQ(), proxygen::QPACKDecoder::decodeStreaming(), describe(), proxygen::QPACKDecoder::drainQueue(), proxygen::QPACKEncoder::encode(), proxygen::QPACKEncoder::encodeHeaderQ(), proxygen::QPACKEncoder::encodeQ(), proxygen::QPACKDecoder::encodeTableStateSync(), proxygen::QPACKDecoder::enqueueHeaderBlock(), getBytesStored(), getHeader(), getHeadersStored(), proxygen::QPACKEncoder::getNameIndexQ(), getTable(), getTableSize(), proxygen::QPACKDecoder::handleBaseIndex(), proxygen::QPACKDecoder::isValid(), proxygen::QPACKEncoder::maybeDuplicate(), proxygen::QPACKEncoder::onHeaderAck(), proxygen::QPACKEncoder::onTableStateSync(), seedHeaderTable(), proxygen::QPACKDecoder::setHeaderTableMaxSize(), proxygen::QPACKEncoder::setHeaderTableSize(), proxygen::QPACKEncoder::setMinFreeForTesting(), proxygen::QPACKEncoder::shouldIndex(), and proxygen::QPACKEncoder::trackReference().
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/compress/QPACKContext.h
proxygen/lib/http/codec/compress/QPACKContext.cpp