proxygen::HTTPTransactionTransportCallback Class Reference
#include <HTTPTransaction.h>
Public Member Functions
virtual void firstHeaderByteFlushed () noexcept=0
virtual void firstByteFlushed () noexcept=0
virtual void lastByteFlushed () noexcept=0
virtual void trackedByteFlushed () noexcept
virtual void lastByteAcked (std::chrono::milliseconds latency) noexcept=0
virtual void headerBytesGenerated (HTTPHeaderSize &size) noexcept=0
virtual void headerBytesReceived (const HTTPHeaderSize &size) noexcept=0
virtual void bodyBytesGenerated (size_t nbytes) noexcept=0
virtual void bodyBytesReceived (size_t size) noexcept=0
virtual ~HTTPTransactionTransportCallback ()
Detailed Description
Callback interface to be notified of events on the byte stream.
Definition at line 301 of file HTTPTransaction.h.
Constructor & Destructor Documentation
virtual proxygen::HTTPTransactionTransportCallback::~HTTPTransactionTransportCallback () [inline], [virtual]
Definition at line 321 of file HTTPTransaction.h.
{}
Member Function Documentation
virtual void proxygen::HTTPTransactionTransportCallback::bodyBytesGenerated (size_t nbytes) [pure virtual], [noexcept]
Referenced by proxygen::HTTPTransaction::sendDeferredBody(), proxygen::HTTPTransaction::sendEOM(), and proxygen::HTTPTransaction::sendHeadersWithOptionalEOM().
virtual void proxygen::HTTPTransactionTransportCallback::bodyBytesReceived (size_t size) [pure virtual], [noexcept]
Referenced by proxygen::HTTPTransaction::onIngressBody().
virtual void proxygen::HTTPTransactionTransportCallback::firstByteFlushed () [pure virtual], [noexcept]
Referenced by proxygen::HTTPTransaction::onEgressBodyFirstByte().
virtual void proxygen::HTTPTransactionTransportCallback::firstHeaderByteFlushed () [pure virtual], [noexcept]
Referenced by proxygen::HTTPTransaction::onEgressHeaderFirstByte().
virtual void proxygen::HTTPTransactionTransportCallback::headerBytesGenerated (HTTPHeaderSize & size) [pure virtual], [noexcept]
Referenced by proxygen::HTTPTransaction::sendAbort(), and proxygen::HTTPTransaction::sendHeadersWithOptionalEOM().
virtual void proxygen::HTTPTransactionTransportCallback::headerBytesReceived (const HTTPHeaderSize & size) [pure virtual], [noexcept]
Referenced by proxygen::HTTPTransaction::onIngressHeadersComplete().
virtual void proxygen::HTTPTransactionTransportCallback::lastByteAcked (std::chrono::milliseconds latency) [pure virtual], [noexcept]
Referenced by proxygen::HTTPTransaction::onEgressLastByteAck().
virtual void proxygen::HTTPTransactionTransportCallback::lastByteFlushed () [pure virtual], [noexcept]
Referenced by proxygen::HTTPTransaction::onEgressBodyLastByte().
virtual void proxygen::HTTPTransactionTransportCallback::trackedByteFlushed () [inline], [virtual], [noexcept]
Definition at line 309 of file HTTPTransaction.h.
Referenced by proxygen::HTTPTransaction::onEgressTrackedByte().
{}
The documentation for this class was generated from the following file:
proxygen/lib/http/session/HTTPTransaction.h