proxygen::HTTPDefaultSessionCodecFactory Class Reference
#include <HTTPDefaultSessionCodecFactory.h>
Public Member Functions
HTTPDefaultSessionCodecFactory (const AcceptorConfiguration &accConfig)
~HTTPDefaultSessionCodecFactory () override
std::unique_ptr< HTTPCodec > getCodec (const std::string &nextProtocol, TransportDirection direction, bool isTLS) override
Protected Attributes
const AcceptorConfiguration & accConfig_
folly::Optional< SPDYVersion > alwaysUseSPDYVersion_ {}
folly::Optional< bool > alwaysUseHTTP2_ {}
Additional Inherited Members
Detailed Description
Definition at line 18 of file HTTPDefaultSessionCodecFactory.h.
Constructor & Destructor Documentation
proxygen::HTTPDefaultSessionCodecFactory::HTTPDefaultSessionCodecFactory (const AcceptorConfiguration & accConfig) [explicit]
Definition at line 19 of file HTTPDefaultSessionCodecFactory.cpp.
References alwaysUseHTTP2_, alwaysUseSPDYVersion_, proxygen::SPDYCodec::getVersion(), proxygen::http2::kProtocolCleartextString, and proxygen::AcceptorConfiguration::plaintextProtocol.
    : accConfig_(accConfig) {
  // set up codec defaults in the case of plaintext connections
  auto version = SPDYCodec::getVersion(accConfig.plaintextProtocol);
  if (version) {
    alwaysUseSPDYVersion_ = *version;
  } else if (accConfig.plaintextProtocol == http2::kProtocolCleartextString) {
    alwaysUseHTTP2_ = true;
  }
}
proxygen::HTTPDefaultSessionCodecFactory::~HTTPDefaultSessionCodecFactory () [inline], [override]
Definition at line 22 of file HTTPDefaultSessionCodecFactory.h.
References getCodec().
{}
Member Function Documentation
std::unique_ptr< HTTPCodec > proxygen::HTTPDefaultSessionCodecFactory::getCodec (const std::string & nextProtocol, TransportDirection direction, bool isTLS) [override], [virtual]
Get a codec instance
Implements proxygen::HTTPCodecFactory .
Definition at line 31 of file HTTPDefaultSessionCodecFactory.cpp.
References accConfig_, proxygen::AcceptorConfiguration::allowedPlaintextUpgradeProtocols, alwaysUseHTTP2_, alwaysUseSPDYVersion_, proxygen::SPDYCodec::getVersion(), proxygen::http2::kProtocolDraftString, proxygen::http2::kProtocolExperimentalString, proxygen::http2::kProtocolString, proxygen::AcceptorConfiguration::spdyCompressionLevel, and proxygen::HTTP1xCodec::supportsNextProtocol().
Referenced by TEST(), and ~HTTPDefaultSessionCodecFactory().
                                                                             {
  if (!isTLS && alwaysUseSPDYVersion_) {
    return std::make_unique<SPDYCodec>(direction,
                                       alwaysUseSPDYVersion_.value(),
                                       accConfig_.spdyCompressionLevel);
  } else if (!isTLS && alwaysUseHTTP2_) {
    return std::make_unique<HTTP2Codec>(direction);
  } else if (nextProtocol.empty() ||
             HTTP1xCodec::supportsNextProtocol(nextProtocol)) {
    auto codec = std::make_unique<HTTP1xCodec>(direction);
    if (!isTLS) {
      codec->setAllowedUpgradeProtocols(
        accConfig_.allowedPlaintextUpgradeProtocols);
    }
    return std::move(codec);
  } else if (auto version = SPDYCodec::getVersion(nextProtocol)) {
    return std::make_unique<SPDYCodec>(direction, *version,
                                         accConfig_.spdyCompressionLevel);
  } else if (nextProtocol == http2::kProtocolString ||
             nextProtocol == http2::kProtocolDraftString ||
             nextProtocol == http2::kProtocolExperimentalString) {
    return std::make_unique<HTTP2Codec>(direction);
  } else {
    VLOG(2) << "Client requested unrecognized next protocol " << nextProtocol;
  }
  return nullptr;
}
Member Data Documentation
const AcceptorConfiguration& proxygen::HTTPDefaultSessionCodecFactory::accConfig_ [protected]
Definition at line 32 of file HTTPDefaultSessionCodecFactory.h.
Referenced by getCodec().
folly::Optional<bool> proxygen::HTTPDefaultSessionCodecFactory::alwaysUseHTTP2_ {} [protected]
Definition at line 34 of file HTTPDefaultSessionCodecFactory.h.
Referenced by getCodec(), and HTTPDefaultSessionCodecFactory().
folly::Optional<SPDYVersion> proxygen::HTTPDefaultSessionCodecFactory::alwaysUseSPDYVersion_ {} [protected]
Definition at line 33 of file HTTPDefaultSessionCodecFactory.h.
Referenced by getCodec(), and HTTPDefaultSessionCodecFactory().
The documentation for this class was generated from the following files:
proxygen/lib/http/session/HTTPDefaultSessionCodecFactory.h
proxygen/lib/http/session/HTTPDefaultSessionCodecFactory.cpp