EchoService::EchoHandler Class Reference
#include <EchoHandler.h>
Public Member Functions
EchoHandler (EchoStats *stats)
void onRequest (std::unique_ptr< proxygen::HTTPMessage > headers) noexceptoverride
void onBody (std::unique_ptr< folly::IOBuf > body) noexceptoverride
void onEOM () noexceptoverride
void onUpgrade (proxygen::UpgradeProtocol proto) noexceptoverride
void requestComplete () noexceptoverride
void onError (proxygen::ProxygenError err) noexceptoverride
Private Attributes
EchoStats *const stats_ {nullptr}
std::unique_ptr< folly::IOBuf > body_
Additional Inherited Members
Detailed Description
Definition at line 23 of file EchoHandler.h.
Constructor & Destructor Documentation
EchoService::EchoHandler::EchoHandler (EchoStats * stats) [explicit]
Definition at line 21 of file EchoHandler.cpp.
                                        : stats_(stats) {
}
Member Function Documentation
void EchoService::EchoHandler::onBody (std::unique_ptr< folly::IOBuf > body) [override], [virtual], [noexcept]
Invoked when we get part of body for the request.
Implements proxygen::RequestHandler .
Definition at line 28 of file EchoHandler.cpp.
References body_.
                                                                {
  if (body_) {
    body_->prependChain(std::move(body));
  } else {
    body_ = std::move(body);
  }
}
void EchoService::EchoHandler::onEOM () [override], [virtual], [noexcept]
Invoked when we finish receiving the body.
Implements proxygen::RequestHandler .
Definition at line 36 of file EchoHandler.cpp.
References proxygen::ResponseBuilder::body(), body_, proxygen::RequestHandler::downstream_, EchoService::EchoStats::getRequestCount(), proxygen::ResponseBuilder::header(), proxygen::ResponseBuilder::sendWithEOM(), stats_, and proxygen::ResponseBuilder::status().
                                 {
  ResponseBuilder(downstream_)
    .status(200, "OK")
    .header("Request-Number",
            folly::to<std::string>(stats_->getRequestCount()))
    .body(std::move(body_))
    .sendWithEOM();
}
void EchoService::EchoHandler::onError (proxygen::ProxygenError err) [override], [virtual], [noexcept]
Request failed. Maybe because of read/write error on socket or client not being able to send request in time.
NOTE: Can be invoked at any time (except for before onRequest).
No more callbacks will be invoked after this. You should clean up after yourself.
Implements proxygen::RequestHandler .
Definition at line 53 of file EchoHandler.cpp.
{ delete this; }
void EchoService::EchoHandler::onRequest (std::unique_ptr< proxygen::HTTPMessage > headers) [override], [virtual], [noexcept]
Invoked when we have successfully fetched headers from client. This will always be the first callback invoked on your handler.
Implements proxygen::RequestHandler .
Definition at line 24 of file EchoHandler.cpp.
References EchoService::EchoStats::recordRequest(), and stats_.
                                                                 {
  stats_->recordRequest();
}
void EchoService::EchoHandler::onUpgrade (proxygen::UpgradeProtocol prot) [override], [virtual], [noexcept]
Invoked when the session has been upgraded to a different protocol
Implements proxygen::RequestHandler .
Definition at line 45 of file EchoHandler.cpp.
                                                      {
  // handler doesn't support upgrades
}
void EchoService::EchoHandler::requestComplete () [override], [virtual], [noexcept]
Invoked when request processing has been completed and nothing more needs to be done. This may be a good place to log some stats and clean up resources. This is distinct from onEOM() because it is invoked after the response is fully sent. Once this callback has been received, downstream_ should be considered invalid.
Implements proxygen::RequestHandler .
Definition at line 49 of file EchoHandler.cpp.
                                           {
  delete this;
}
Member Data Documentation
std::unique_ptr<folly::IOBuf> EchoService::EchoHandler::body_ [private]
Definition at line 43 of file EchoHandler.h.
Referenced by onBody(), and onEOM().
EchoStats* const EchoService::EchoHandler::stats_ {nullptr} [private]
Definition at line 41 of file EchoHandler.h.
Referenced by onEOM(), and onRequest().
The documentation for this class was generated from the following files:
proxygen/httpserver/samples/echo/EchoHandler.h
proxygen/httpserver/samples/echo/EchoHandler.cpp