proxygen::HTTPCodecPrinter Class Reference
#include <HTTPCodecPrinter.h>
Public Member Functions
void onFrameHeader (StreamID stream_id, uint8_t flags, uint64_t length, uint8_t type, uint16_t version=0) override
void onError (StreamID stream, const HTTPException &error, bool newStream=false) override
void onBody (StreamID stream, std::unique_ptr< folly::IOBuf > chain, uint16_t padding) override
void onMessageComplete (StreamID stream, bool upgrade) override
void onHeadersComplete (StreamID stream, std::unique_ptr< HTTPMessage > msg) override
void onAbort (StreamID stream, ErrorCode code) override
void onWindowUpdate (StreamID stream, uint32_t amount) override
void onSettings (const SettingsList &settings) override
void onSettingsAck () override
void onGoaway (uint64_t lastGoodStreamID, ErrorCode code, std::unique_ptr< folly::IOBuf > debugData=nullptr) override
void onPingRequest (uint64_t uniqueID) override
void onPingReply (uint64_t uniqueID) override
Protected Member Functions
void printPing (uint64_t uniqueID)
Additional Inherited Members
Detailed Description
This class enforces certain higher-level HTTP semantics. It does not enforce conditions that require state to decide. That is, this class is stateless and only examines the calls and callbacks that go through it.
Definition at line 22 of file HTTPCodecPrinter.h.
Member Function Documentation
void proxygen::HTTPCodecPrinter::onAbort (StreamID stream, ErrorCode code) [override]
Definition at line 94 of file HTTPCodecPrinter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_, and proxygen::getErrorCodeString().
                                                              {
  std::cout << "RST_STREAM: stream_id=" << stream << ", error="
            << getErrorCodeString(code) << std::endl;
  callback_->onAbort(stream, code);
}
void proxygen::HTTPCodecPrinter::onBody (StreamID stream, std::unique_ptr< folly::IOBuf > chain, uint16_t padding) [override]
Definition at line 62 of file HTTPCodecPrinter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
                                                {
  std::cout << "DataChunk: stream_id=" << stream
            << ", length=" << chain->length()
            << ", padding=" << padding << std::endl;
  callback_->onBody(stream, std::move(chain), padding);
}
void proxygen::HTTPCodecPrinter::onError (StreamID stream, const HTTPException & error, bool newStream = false) [override]
Definition at line 55 of file HTTPCodecPrinter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_, and proxygen::Exception::what().
                                               {
  std::cout << "[Exception] " << error.what() << std::endl;
  callback_->onError(stream, error, newStream);
}
void proxygen::HTTPCodecPrinter::onFrameHeader (StreamID stream_id, uint8_t flags, uint64_t length, uint8_t type, uint16_t version = 0) [override]
Definition at line 16 of file HTTPCodecPrinter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::call_, proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_, proxygen::HTTP_1_1, proxygen::HTTP_2, proxygen::SPDY_3, and proxygen::SPDY_3_1.
                      {
  switch (call_->getProtocol()) {
    case CodecProtocol::SPDY_3:
    case CodecProtocol::SPDY_3_1:
      if (version > 0) {
        // Print frame header info of SPDY control frames
        std::cout << "[CTRL FRAME] version=" << version << ", flags="
                  << std::hex << folly::to<unsigned int>(flags) << std::dec
                  << ", length=" << length
                  << ", type=" << type
                  << std::endl;
      } else {
        // Print frame header info of SPDY data frames and HTTP/2 frames
        std::cout << "[DATA FRAME] stream_id=" << stream_id << ", flags="
                  << std::hex << folly::to<unsigned int>(flags) << std::dec
                  << ", length=" << length
                  << ", type=" << type
                  << std::endl;
      }
      break;
    case CodecProtocol::HTTP_2:
      std::cout << "[FRAME] stream_id=" << stream_id << ", flags="
                << std::hex << folly::to<unsigned int>(flags) << std::dec
                << ", length=" << length
                << ", type=" << type
                << std::endl;
      break;
    case CodecProtocol::HTTP_1_1:
    default:
      break;
  }
  callback_->onFrameHeader(stream_id, flags, length, type, version);
}
void proxygen::HTTPCodecPrinter::onGoaway (uint64_t lastGoodStreamID, ErrorCode code, std::unique_ptr< folly::IOBuf > debugData = nullptr) [override]
Definition at line 100 of file HTTPCodecPrinter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_, and proxygen::getErrorCodeString().
                                                                     {
  std::string debugInfo = (debugData) ? ", debug info=" +
    std::string((char*)debugData->data(), debugData->length()) : "";
  std::cout << "GOAWAY: lastGoodStream=" << lastGoodStream
            << ", error=" << getErrorCodeString(code) << debugInfo << std::endl;
  callback_->onGoaway(lastGoodStream, code, std::move(debugData));
}
void proxygen::HTTPCodecPrinter::onHeadersComplete (StreamID stream, std::unique_ptr< HTTPMessage > msg) [override]
Definition at line 76 of file HTTPCodecPrinter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
                                    {
  std::cout << "HEADERS: stream_id=" << stream
            << ", numHeaders=" << msg->getHeaders().size() << std::endl;
  if (msg->isRequest()) {
    std::cout << "URL=" << msg->getURL() << std::endl;
  } else {
    std::cout << "Status=" << msg->getStatusCode() << std::endl;
  }
  msg->getHeaders().forEach([&] (
        const std::string& header,
        const std::string& val) {
      std::cout << "\t" << header << ": " << val << std::endl;
  });
  callback_->onHeadersComplete(stream, std::move(msg));
}
void proxygen::HTTPCodecPrinter::onMessageComplete (StreamID stream, bool upgrade) [override]
Definition at line 71 of file HTTPCodecPrinter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
                                                                      {
  std::cout << "DataComplete: stream_id=" << stream << std::endl;
  callback_->onMessageComplete(stream, upgrade);
}
void proxygen::HTTPCodecPrinter::onPingReply (uint64_t uniqueID) [override]
Definition at line 134 of file HTTPCodecPrinter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_, and printPing().
                                                     {
  printPing(unique_id);
  callback_->onPingReply(unique_id);
}
void proxygen::HTTPCodecPrinter::onPingRequest (uint64_t uniqueID) [override]
Definition at line 129 of file HTTPCodecPrinter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_, and printPing().
                                                       {
  printPing(unique_id);
  callback_->onPingRequest(unique_id);
}
void proxygen::HTTPCodecPrinter::onSettings (const SettingsList & settings) [override]
Definition at line 115 of file HTTPCodecPrinter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
                                                              {
  std::cout << "SETTINGS: num=" << settings.size() << std::endl;
  for (const auto& setting: settings) {
    std::cout << "\tid=" << folly::to<uint16_t>(setting.id)
              << ", value=" << setting.value << std::endl;
  }
  callback_->onSettings(settings);
}
void proxygen::HTTPCodecPrinter::onSettingsAck () [override]
Definition at line 124 of file HTTPCodecPrinter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
                                     {
  std::cout << "SETTINGS_ACK" << std::endl;
  callback_->onSettingsAck();
}
void proxygen::HTTPCodecPrinter::onWindowUpdate (StreamID stream, uint32_t amount) [override]
Definition at line 109 of file HTTPCodecPrinter.cpp.
References proxygen::GenericFilter< T1, T2, set_callback, TakeOwnership, Dp >::callback_.
                                                                      {
  std::cout << "WINDOW_UPDATE: stream_id=" << stream
            << ", delta_window_size=" << amount << std::endl;
  callback_->onWindowUpdate(stream, amount);
}
void proxygen::HTTPCodecPrinter::printPing (uint64_t uniqueID) [protected]
Definition at line 139 of file HTTPCodecPrinter.cpp.
Referenced by onPingReply(), and onPingRequest().
                                                   {
  std::cout << "PING: unique_id=" << unique_id << std::endl;
}
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/HTTPCodecPrinter.h
proxygen/lib/http/codec/HTTPCodecPrinter.cpp