proxygen::PassThroughTransportFilter Class Reference
#include <TransportFilter.h>
Public Member Functions
PassThroughTransportFilter (bool calls=true, bool callbacks=true)
void getReadBuffer (void **bufReturn, size_t *lenReturn) override
void readDataAvailable (size_t len) noexceptoverride
void readEOF () noexceptoverride
void readErr (const folly::AsyncSocketException &ex) noexceptoverride
void setReadCB (folly::AsyncTransportWrapper::ReadCallback *callback) override
folly::AsyncTransportWrapper::ReadCallback * getReadCallback () const override
void write (folly::AsyncTransportWrapper::WriteCallback *callback, const void *buf, size_t bytes, folly::WriteFlags flags) override
void writev (folly::AsyncTransportWrapper::WriteCallback *callback, const iovec *vec, size_t count, folly::WriteFlags flags) override
void writeChain (folly::AsyncTransportWrapper::WriteCallback *callback, std::unique_ptr< folly::IOBuf > &&iob, folly::WriteFlags flags) override
void close () override
void closeNow () override
void closeWithReset () override
void shutdownWrite () override
void shutdownWriteNow () override
bool good () const override
bool readable () const override
bool connecting () const override
bool error () const override
void attachEventBase (folly::EventBase *eventBase) override
void detachEventBase () override
bool isDetachable () const override
folly::EventBase * getEventBase () const override
void setSendTimeout (uint32_t milliseconds) override
uint32_t getSendTimeout () const override
void getLocalAddress (folly::SocketAddress *address) const override
void getPeerAddress (folly::SocketAddress *address) const override
void setEorTracking (bool track) override
size_t getAppBytesWritten () const override
size_t getRawBytesWritten () const override
size_t getAppBytesReceived () const override
size_t getRawBytesReceived () const override
Additional Inherited Members
Detailed Description
An implementation of Transport that passes through all calls and also properly calls setCallback(). This is useful to subclass if you aren't interested in intercepting every function. See AsyncTransport.h for documentation on these methods
Definition at line 31 of file TransportFilter.h.
Constructor & Destructor Documentation
proxygen::PassThroughTransportFilter::PassThroughTransportFilter (bool calls = true, bool callbacks = true) [inline], [explicit]
By default, the filter gets both calls and callbacks
Definition at line 36 of file TransportFilter.h.
References attachEventBase(), close(), closeNow(), closeWithReset(), connecting(), detachEventBase(), error(), getAppBytesReceived(), getAppBytesWritten(), getEventBase(), getLocalAddress(), getPeerAddress(), getRawBytesReceived(), getRawBytesWritten(), getReadBuffer(), getReadCallback(), getSendTimeout(), good(), isDetachable(), readable(), readDataAvailable(), readEOF(), readErr(), setEorTracking(), setReadCB(), setSendTimeout(), shutdownWrite(), shutdownWriteNow(), write(), writeChain(), and writev().
                                                            :
      TransportFilter(calls, callbacks) {}
Member Function Documentation
void proxygen::PassThroughTransportFilter::attachEventBase (folly::EventBase * eventBase) [override]
Definition at line 110 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                                     {
  call_->attachEventBase(eventBase);
}
void proxygen::PassThroughTransportFilter::close () [override]
Definition at line 71 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                       {
  call_->close();
  // wait for readEOF() to call destroy()
}
void proxygen::PassThroughTransportFilter::closeNow () [override]
Definition at line 76 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                          {
  call_->closeNow();
  // wait for readEOF() to call destroy()
}
void proxygen::PassThroughTransportFilter::closeWithReset () [override]
Definition at line 81 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                {
  call_->closeWithReset();
  // wait for readEOF() to call destroy()
}
bool proxygen::PassThroughTransportFilter::connecting () const [override]
Definition at line 102 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                  {
  return call_->connecting();
}
void proxygen::PassThroughTransportFilter::detachEventBase () [override]
Definition at line 114 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                 {
  call_->detachEventBase();
}
bool proxygen::PassThroughTransportFilter::error () const [override]
Definition at line 106 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                             {
  return call_->error();
}
size_t proxygen::PassThroughTransportFilter::getAppBytesReceived () const [override]
Definition at line 154 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                             {
  return call_->getAppBytesReceived();
}
size_t proxygen::PassThroughTransportFilter::getAppBytesWritten () const [override]
Definition at line 148 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                            {
  return call_->getAppBytesWritten();
}
EventBase * proxygen::PassThroughTransportFilter::getEventBase () const [override]
Definition at line 122 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                          {
  return call_->getEventBase();
}
void proxygen::PassThroughTransportFilter::getLocalAddress (folly::SocketAddress * address) const [override]
Definition at line 134 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                       {
  call_->getLocalAddress(address);
}
void proxygen::PassThroughTransportFilter::getPeerAddress (folly::SocketAddress * address) const [override]
Definition at line 139 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                       {
  call_->getPeerAddress(address);
}
size_t proxygen::PassThroughTransportFilter::getRawBytesReceived () const [override]
Definition at line 157 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                             {
  //new PassThroughTransportFilter();
  return call_->getRawBytesReceived();
}
size_t proxygen::PassThroughTransportFilter::getRawBytesWritten () const [override]
Definition at line 151 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                            {
  return call_->getRawBytesWritten();
}
void proxygen::PassThroughTransportFilter::getReadBuffer (void ** bufReturn, size_t * lenReturn) [override]
Definition at line 19 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                                  {
  callback_->getReadBuffer(bufReturn, lenReturn);
}
AsyncTransportWrapper::ReadCallback * proxygen::PassThroughTransportFilter::getReadCallback () const [override]
Definition at line 49 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                  {
  return call_->getReadCallback();
}
uint32_t proxygen::PassThroughTransportFilter::getSendTimeout () const [override]
Definition at line 130 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                          {
  return call_->getSendTimeout();
}
bool proxygen::PassThroughTransportFilter::good () const [override]
Definition at line 94 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                            {
  return call_->good();
}
bool proxygen::PassThroughTransportFilter::isDetachable () const [override]
Definition at line 118 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                    {
  return call_->isDetachable();
}
bool proxygen::PassThroughTransportFilter::readable () const [override]
Definition at line 98 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                {
  return call_->readable();
}
void proxygen::PassThroughTransportFilter::readDataAvailable (size_t len) [override], [noexcept]
Definition at line 24 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                                      {
  callback_->readDataAvailable(len);
}
void proxygen::PassThroughTransportFilter::readEOF () [override], [noexcept]
Definition at line 28 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                  {
  callback_->readEOF();
  destroy();
}
void proxygen::PassThroughTransportFilter::readErr (const folly::AsyncSocketException & ex) [override], [noexcept]
Definition at line 33 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                             {
  callback_->readErr(ex);
  destroy();
}
void proxygen::PassThroughTransportFilter::setEorTracking (bool track) [override]
Definition at line 144 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                          {
  call_->setEorTracking(track);
}
void proxygen::PassThroughTransportFilter::setReadCB (folly::AsyncTransportWrapper::ReadCallback * callback) [override]
Definition at line 41 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                 {
  // Important! The filter must call setCallbackInternal in its base class and
  // it must not forward the call.
  setCallbackInternal(callback);
}
void proxygen::PassThroughTransportFilter::setSendTimeout (uint32_t milliseconds) [override]
Definition at line 126 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                                     {
  call_->setSendTimeout(milliseconds);
}
void proxygen::PassThroughTransportFilter::shutdownWrite () [override]
Definition at line 86 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                               {
  call_->shutdownWrite();
}
void proxygen::PassThroughTransportFilter::shutdownWriteNow () [override]
Definition at line 90 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                  {
  call_->shutdownWriteNow();
}
void proxygen::PassThroughTransportFilter::write (folly::AsyncTransportWrapper::WriteCallback * callback, const void * buf, size_t bytes, folly::WriteFlags flags) [override]
Definition at line 53 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                     {
  call_->write(callback, buf, bytes, flags);
}
void proxygen::PassThroughTransportFilter::writeChain (folly::AsyncTransportWrapper::WriteCallback * callback, std::unique_ptr< folly::IOBuf > && iob, folly::WriteFlags flags) [override]
Definition at line 65 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                                                       {
  call_->writeChain(callback, std::move(iob), flags);
}
void proxygen::PassThroughTransportFilter::writev (folly::AsyncTransportWrapper::WriteCallback * callback, const iovec * vec, size_t count, folly::WriteFlags flags) [override]
Definition at line 59 of file TransportFilter.cpp.
Referenced by PassThroughTransportFilter().
                      {
  call_->writev(callback, vec, count, flags);
}
The documentation for this class was generated from the following files:
proxygen/lib/http/session/TransportFilter.h
proxygen/lib/http/session/TransportFilter.cpp