TestPriorityMapBuilder Class Reference
Public Member Functions
virtual std::unique_ptr< HTTPUpstreamSession::PriorityAdapter > createVirtualStreams (HTTPPriorityMapFactoryProvider *session) const override
virtual ~TestPriorityMapBuilder ()=default
Public Attributes
uint8_t hiPriWeight_ {18}
uint8_t hiPriLevel_ {0}
uint8_t loPriWeight_ {2}
uint8_t loPriLevel_ {2}
Detailed Description
Definition at line 38 of file HTTPUpstreamSessionTest.cpp.
Constructor & Destructor Documentation
virtual TestPriorityMapBuilder::~TestPriorityMapBuilder () [virtual], [default]
Member Function Documentation
std::unique_ptr< HTTPUpstreamSession::PriorityAdapter > TestPriorityMapBuilder::createVirtualStreams (HTTPPriorityMapFactoryProvider * session) const [override], [virtual]
Definition at line 77 of file HTTPUpstreamSessionTest.cpp.
References proxygen::HTTPHeaders::add(), proxygen::HTTPMessage::getHeaders(), proxygen::getPostRequest(), proxygen::getResponse(), TestPriorityAdapter::hiPri_, TestPriorityAdapter::hiPriId_, TestPriorityAdapter::loPri_, TestPriorityAdapter::loPriId_, makeBuf(), TestPriorityAdapter::minPriority_, TestPriorityAdapter::parentId_, TestPriorityAdapter::priorityMap_, proxygen::HTTPPriorityMapFactoryProvider::sendPriority(), proxygen::HTTPHeaders::set(), proxygen::HTTPMessage::setStatusCode(), and proxygen::HTTPMessage::setStatusMessage().
                                                       {
  std::unique_ptr<TestPriorityAdapter> a =
      std::make_unique<TestPriorityAdapter>();
  a->parentId_ = session->sendPriority({0, false, 1});
  std::get<0>(a->hiPri_) = a->parentId_;
  std::get<2>(a->hiPri_) = hiPriWeight_;
  a->hiPriId_ = session->sendPriority({a->parentId_, false, hiPriWeight_});
  a->priorityMap_[hiPriLevel_] = a->hiPri_;
  std::get<0>(a->loPri_) = a->parentId_;
  std::get<2>(a->loPri_) = loPriWeight_;
  a->loPriId_ = session->sendPriority({a->parentId_, false, loPriWeight_});
  a->priorityMap_[loPriLevel_] = a->loPri_;
  a->minPriority_ = a->loPri_;
  return std::move(a);
}
Member Data Documentation
uint8_t TestPriorityMapBuilder::hiPriLevel_ {0}
Definition at line 46 of file HTTPUpstreamSessionTest.cpp.
uint8_t TestPriorityMapBuilder::hiPriWeight_ {18}
Definition at line 45 of file HTTPUpstreamSessionTest.cpp.
uint8_t TestPriorityMapBuilder::loPriLevel_ {2}
Definition at line 48 of file HTTPUpstreamSessionTest.cpp.
uint8_t TestPriorityMapBuilder::loPriWeight_ {2}
Definition at line 47 of file HTTPUpstreamSessionTest.cpp.
The documentation for this class was generated from the following file:
proxygen/lib/http/session/test/HTTPUpstreamSessionTest.cpp