proxygen::HTTPTransaction::Transport Class Reference
#include <HTTPTransaction.h>
Public Member Functions
virtual ~Transport ()
virtual void pauseIngress (HTTPTransaction *txn) noexcept=0
virtual void resumeIngress (HTTPTransaction *txn) noexcept=0
virtual void transactionTimeout (HTTPTransaction *txn) noexcept=0
virtual void sendHeaders (HTTPTransaction *txn, const HTTPMessage &headers, HTTPHeaderSize *size, bool eom) noexcept=0
virtual size_t sendBody (HTTPTransaction *txn, std::unique_ptr< folly::IOBuf >, bool eom, bool trackLastByteFlushed) noexcept=0
virtual size_t sendChunkHeader (HTTPTransaction *txn, size_t length) noexcept=0
virtual size_t sendChunkTerminator (HTTPTransaction *txn) noexcept=0
virtual size_t sendEOM (HTTPTransaction *txn, const HTTPHeaders *trailers) noexcept=0
virtual size_t sendAbort (HTTPTransaction *txn, ErrorCode statusCode) noexcept=0
virtual size_t sendPriority (HTTPTransaction *txn, const http2::PriorityUpdate &pri) noexcept=0
virtual size_t sendWindowUpdate (HTTPTransaction *txn, uint32_t bytes) noexcept=0
virtual void notifyPendingEgress () noexcept=0
virtual void detach (HTTPTransaction *txn) noexcept=0
virtual void notifyIngressBodyProcessed (uint32_t bytes) noexcept=0
virtual void notifyEgressBodyBuffered (int64_t bytes) noexcept=0
virtual const folly::SocketAddress & getLocalAddress () const noexcept=0
virtual const folly::SocketAddress & getPeerAddress () const noexcept=0
virtual void describe (std::ostream &) const =0
virtual const wangle::TransportInfo & getSetupTransportInfo () const noexcept=0
virtual bool getCurrentTransportInfo (wangle::TransportInfo *tinfo)=0
virtual const HTTPCodec & getCodec () const noexcept=0
virtual void drain ()=0
virtual bool isDraining () const =0
virtual HTTPTransaction * newPushedTransaction (HTTPCodec::StreamID assocStreamId, HTTPTransaction::PushHandler *handler) noexcept=0
virtual HTTPTransaction * newExTransaction (HTTPTransaction::Handler *handler, HTTPCodec::StreamID controlStream, bool unidirectional) noexcept=0
virtual std::string getSecurityProtocol () const =0
virtual void addWaitingForReplaySafety (folly::AsyncTransport::ReplaySafetyCallback *callback) noexcept=0
virtual void removeWaitingForReplaySafety (folly::AsyncTransport::ReplaySafetyCallback *callback) noexcept=0
virtual bool needToBlockForReplaySafety () const =0
virtual const folly::AsyncTransportWrapper * getUnderlyingTransport () const noexcept=0
virtual bool isReplaySafe () const =0
virtual void setHTTP2PrioritiesEnabled (bool enabled)=0
virtual bool getHTTP2PrioritiesEnabled () const =0
virtual folly::Optional< const HTTPMessage::HTTPPriority > getHTTPPriority (uint8_t level)=0
Detailed Description
Definition at line 331 of file HTTPTransaction.h.
Constructor & Destructor Documentation
virtual proxygen::HTTPTransaction::Transport::~Transport () [inline], [virtual]
Definition at line 333 of file HTTPTransaction.h.
References statusCode.
{}
Member Function Documentation
virtual void proxygen::HTTPTransaction::Transport::addWaitingForReplaySafety (folly::AsyncTransport::ReplaySafetyCallback * callback) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::getCodec(), proxygen::MockHTTPTransaction::sendBody(), and TEST_F().
virtual void proxygen::HTTPTransaction::Transport::describe (std::ostream &) const [pure virtual]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::HTTPTransaction::describe(), and proxygen::MockHTTPTransactionTransport::getPeerAddress().
virtual void proxygen::HTTPTransaction::Transport::detach (HTTPTransaction * txn) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::HTTPTransaction::onDelayedDestroy(), and proxygen::MockHTTPTransactionTransport::sendBody().
virtual void proxygen::HTTPTransaction::Transport::drain () [pure virtual]
Implemented in proxygen::HTTPSession , and proxygen::HTTPUpstreamSession .
Referenced by proxygen::MockHTTPTransactionTransport::getCodec().
virtual const HTTPCodec& proxygen::HTTPTransaction::Transport::getCodec () const [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession , and proxygen::MockHTTPTransactionTransport .
Referenced by proxygen::HTTPTransaction::onIngressHeadersComplete(), proxygen::HTTPTransaction::sendBody(), proxygen::HTTPTransaction::sendHeadersWithOptionalEOM(), and proxygen::HTTPTransaction::updateAndSendPriority().
virtual bool proxygen::HTTPTransaction::Transport::getCurrentTransportInfo (wangle::TransportInfo * tinfo) [pure virtual]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::getSetupTransportInfo().
virtual bool proxygen::HTTPTransaction::Transport::getHTTP2PrioritiesEnabled () const [pure virtual]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::getUnderlyingTransport().
virtual folly::Optional<const HTTPMessage::HTTPPriority> proxygen::HTTPTransaction::Transport::getHTTPPriority (uint8_t level) [pure virtual]
Implemented in proxygen::HTTPSession , and proxygen::HTTPUpstreamSession .
Referenced by proxygen::MockHTTPTransactionTransport::getUnderlyingTransport().
virtual const folly::SocketAddress& proxygen::HTTPTransaction::Transport::getLocalAddress () const [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession , and proxygen::MockHTTPTransactionTransport .
virtual const folly::SocketAddress& proxygen::HTTPTransaction::Transport::getPeerAddress () const [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession , and proxygen::MockHTTPTransactionTransport .
virtual std::string proxygen::HTTPTransaction::Transport::getSecurityProtocol () const [pure virtual]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::getCodec().
virtual const wangle::TransportInfo& proxygen::HTTPTransaction::Transport::getSetupTransportInfo () const [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession , and proxygen::MockHTTPTransactionTransport .
virtual const folly::AsyncTransportWrapper* proxygen::HTTPTransaction::Transport::getUnderlyingTransport () const [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession , and proxygen::MockHTTPTransactionTransport .
virtual bool proxygen::HTTPTransaction::Transport::isDraining () const [pure virtual]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::getCodec(), and proxygen::HTTPTransaction::processIngressBody().
virtual bool proxygen::HTTPTransaction::Transport::isReplaySafe () const [pure virtual]
Returns true if the underlying transport has completed full handshake.
Implemented in proxygen::HTTPUpstreamSession , and proxygen::HTTPDownstreamSession .
Referenced by proxygen::MockHTTPTransactionTransport::getUnderlyingTransport().
virtual bool proxygen::HTTPTransaction::Transport::needToBlockForReplaySafety () const [pure virtual]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::getCodec().
virtual HTTPTransaction* proxygen::HTTPTransaction::Transport::newExTransaction (HTTPTransaction::Handler * handler, HTTPCodec::StreamID controlStream, bool unidirectional) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::sendBody().
virtual HTTPTransaction* proxygen::HTTPTransaction::Transport::newPushedTransaction (HTTPCodec::StreamID assocStreamId, HTTPTransaction::PushHandler * handler) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::sendBody(), and proxygen::MockHTTPTransaction::sendBody().
virtual void proxygen::HTTPTransaction::Transport::notifyEgressBodyBuffered (int64_t bytes) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::HTTPTransaction::markEgressComplete(), proxygen::HTTPTransaction::notifyTransportPendingEgress(), proxygen::MockHTTPTransactionTransport::sendBody(), and proxygen::HTTPTransaction::sendBody().
virtual void proxygen::HTTPTransaction::Transport::notifyIngressBodyProcessed (uint32_t bytes) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::HTTPTransaction::onDelayedDestroy(), proxygen::HTTPTransaction::processIngressBody(), and proxygen::MockHTTPTransactionTransport::sendBody().
virtual void proxygen::HTTPTransaction::Transport::notifyPendingEgress () [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::HTTPTransaction::notifyTransportPendingEgress(), proxygen::MockHTTPTransactionTransport::sendBody(), and proxygen::HTTPTransaction::sendEOM().
virtual void proxygen::HTTPTransaction::Transport::pauseIngress (HTTPTransaction * txn) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::MockHTTPTransactionTransport(), proxygen::HTTPTransaction::pauseIngress(), and proxygen::MockHTTPTransaction::sendBody().
virtual void proxygen::HTTPTransaction::Transport::removeWaitingForReplaySafety (folly::AsyncTransport::ReplaySafetyCallback * callback) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::getCodec(), and proxygen::MockHTTPTransaction::sendBody().
virtual void proxygen::HTTPTransaction::Transport::resumeIngress (HTTPTransaction * txn) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::MockHTTPTransactionTransport(), proxygen::HTTPTransaction::resumeIngress(), and proxygen::MockHTTPTransaction::sendBody().
virtual size_t proxygen::HTTPTransaction::Transport::sendAbort (HTTPTransaction * txn, ErrorCode statusCode) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::HTTPTransaction::sendAbort(), proxygen::MockHTTPTransactionTransport::sendBody(), and proxygen::MockHTTPTransaction::sendBody().
virtual size_t proxygen::HTTPTransaction::Transport::sendBody (HTTPTransaction * txn, std::unique_ptr< folly::IOBuf > , bool eom, bool trackLastByteFlushed) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession , and proxygen::MockHTTPTransactionTransport .
Referenced by proxygen::HTTPTransaction::sendBodyNow().
virtual size_t proxygen::HTTPTransaction::Transport::sendChunkHeader (HTTPTransaction * txn, size_t length) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::sendBody(), proxygen::MockHTTPTransaction::sendBody(), and proxygen::HTTPTransaction::sendDeferredBody().
virtual size_t proxygen::HTTPTransaction::Transport::sendChunkTerminator (HTTPTransaction * txn) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::sendBody(), proxygen::MockHTTPTransaction::sendBody(), and proxygen::HTTPTransaction::sendDeferredBody().
virtual size_t proxygen::HTTPTransaction::Transport::sendEOM (HTTPTransaction * txn, const HTTPHeaders * trailers) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::sendBody(), proxygen::MockHTTPTransaction::sendBody(), and proxygen::HTTPTransaction::sendEOMNow().
virtual void proxygen::HTTPTransaction::Transport::sendHeaders (HTTPTransaction * txn, const HTTPMessage & headers, HTTPHeaderSize * size, bool eom) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::MockHTTPTransactionTransport(), proxygen::HTTPTransaction::sendHeadersWithOptionalEOM(), and proxygen::MockHTTPTransaction::setHandlerUnmocked().
virtual size_t proxygen::HTTPTransaction::Transport::sendPriority (HTTPTransaction * txn, const http2::PriorityUpdate & pri) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::sendBody(), and proxygen::HTTPTransaction::updateAndSendPriority().
virtual size_t proxygen::HTTPTransaction::Transport::sendWindowUpdate (HTTPTransaction * txn, uint32_t bytes) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::HTTPTransaction::flushWindowUpdate(), and proxygen::MockHTTPTransactionTransport::sendBody().
virtual void proxygen::HTTPTransaction::Transport::setHTTP2PrioritiesEnabled (bool enabled) [pure virtual]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::getUnderlyingTransport().
virtual void proxygen::HTTPTransaction::Transport::transactionTimeout (HTTPTransaction * txn) [pure virtual], [noexcept]
Implemented in proxygen::HTTPSession .
Referenced by proxygen::MockHTTPTransactionTransport::MockHTTPTransactionTransport().
The documentation for this class was generated from the following file:
proxygen/lib/http/session/HTTPTransaction.h