proxygen::ScopedHandler< HandlerType > Class Template Reference
#include <ScopedHTTPServer.h>
Public Member Functions
ScopedHandler (HandlerType *ptr)
void onRequest (std::unique_ptr< HTTPMessage > headers) noexceptoverride
void onBody (std::unique_ptr< folly::IOBuf > body) noexceptoverride
void onUpgrade (proxygen::UpgradeProtocol) noexceptoverride
void onEOM () noexceptoverride
void requestComplete () noexceptoverride
void onError (ProxygenError) noexceptoverride
Private Attributes
HandlerType *const handlerPtr_ {nullptr}
std::unique_ptr< HTTPMessage > request_
folly::IOBufQueue requestBody_
Additional Inherited Members
Detailed Description
template<typename HandlerType>
*
class proxygen::ScopedHandler< HandlerType >
Definition at line 21 of file ScopedHTTPServer.h.
Constructor & Destructor Documentation
template<typename HandlerType > proxygen::ScopedHandler< HandlerType >::ScopedHandler (HandlerType * ptr) [inline], [explicit]
Definition at line 23 of file ScopedHTTPServer.h.
                                          : handlerPtr_(ptr) {
  }
Member Function Documentation
template<typename HandlerType > void proxygen::ScopedHandler< HandlerType >::onBody (std::unique_ptr< folly::IOBuf > body) [inline], [override], [virtual], [noexcept]
Invoked when we get part of body for the request.
Implements proxygen::RequestHandler .
Definition at line 30 of file ScopedHTTPServer.h.
References proxygen::ScopedHandler< HandlerType >::requestBody_.
                                                                {
    requestBody_.append(std::move(body));
  }
template<typename HandlerType > void proxygen::ScopedHandler< HandlerType >::onEOM () [inline], [override], [virtual], [noexcept]
Invoked when we finish receiving the body.
Implements proxygen::RequestHandler .
Definition at line 36 of file ScopedHTTPServer.h.
References proxygen::ResponseBuilder::body(), proxygen::RequestHandler::downstream_, proxygen::ScopedHandler< HandlerType >::request_, proxygen::ScopedHandler< HandlerType >::requestBody_, proxygen::ResponseBuilder::sendWithEOM(), and proxygen::ResponseBuilder::status().
                                 {
    try {
      ResponseBuilder r(downstream_);
      (*handlerPtr_)(*request_, requestBody_.move(), r);
      r.sendWithEOM();
    } catch (const std::exception& ex) {
      ResponseBuilder(downstream_)
          .status(500, "Internal Server Error")
          .body(ex.what())
          .sendWithEOM();
    } catch (...) {
      ResponseBuilder(downstream_)
          .status(500, "Internal Server Error")
          .body("Unknown exception thrown")
          .sendWithEOM();
    }
  }
template<typename HandlerType > void proxygen::ScopedHandler< HandlerType >::onError (ProxygenError err) [inline], [override], [virtual], [noexcept]
Request failed. Maybe because of read/write error on socket or client not being able to send request in time.
NOTE: Can be invoked at any time (except for before onRequest).
No more callbacks will be invoked after this. You should clean up after yourself.
Implements proxygen::RequestHandler .
Definition at line 56 of file ScopedHTTPServer.h.
{ delete this; }
template<typename HandlerType > void proxygen::ScopedHandler< HandlerType >::onRequest (std::unique_ptr< HTTPMessage > headers) [inline], [override], [virtual], [noexcept]
Invoked when we have successfully fetched headers from client. This will always be the first callback invoked on your handler.
Implements proxygen::RequestHandler .
Definition at line 26 of file ScopedHTTPServer.h.
References proxygen::ScopedHandler< HandlerType >::request_.
                                                                       {
    request_ = std::move(headers);
  }
template<typename HandlerType > void proxygen::ScopedHandler< HandlerType >::onUpgrade (proxygen::UpgradeProtocol prot) [inline], [override], [virtual], [noexcept]
Invoked when the session has been upgraded to a different protocol
Implements proxygen::RequestHandler .
Definition at line 34 of file ScopedHTTPServer.h.
{}
template<typename HandlerType > void proxygen::ScopedHandler< HandlerType >::requestComplete () [inline], [override], [virtual], [noexcept]
Invoked when request processing has been completed and nothing more needs to be done. This may be a good place to log some stats and clean up resources. This is distinct from onEOM() because it is invoked after the response is fully sent. Once this callback has been received, downstream_ should be considered invalid.
Implements proxygen::RequestHandler .
Definition at line 54 of file ScopedHTTPServer.h.
{ delete this; }
Member Data Documentation
template<typename HandlerType > HandlerType* const proxygen::ScopedHandler< HandlerType >::handlerPtr_ {nullptr} [private]
Definition at line 58 of file ScopedHTTPServer.h.
template<typename HandlerType > std::unique_ptr<HTTPMessage> proxygen::ScopedHandler< HandlerType >::request_ [private]
Definition at line 60 of file ScopedHTTPServer.h.
Referenced by proxygen::ScopedHandler< HandlerType >::onEOM(), and proxygen::ScopedHandler< HandlerType >::onRequest().
template<typename HandlerType > folly::IOBufQueue proxygen::ScopedHandler< HandlerType >::requestBody_ [private]
Definition at line 61 of file ScopedHTTPServer.h.
Referenced by proxygen::ScopedHandler< HandlerType >::onBody(), and proxygen::ScopedHandler< HandlerType >::onEOM().
The documentation for this class was generated from the following file:
proxygen/httpserver/ScopedHTTPServer.h