proxygen::HPACKContext Class Reference
#include <HPACKContext.h>
Public Member Functions
HPACKContext (uint32_t tableSize)
~HPACKContext ()
uint32_t getIndex (const HPACKHeader &header) const
uint32_t nameIndex (const HPACKHeaderName &headerName) const
bool isStatic (uint32_t index) const
const HPACKHeader & getHeader (uint32_t index)
const HeaderTable & getTable () const
uint32_t getTableSize () const
uint32_t getBytesStored () const
uint32_t getHeadersStored () const
void seedHeaderTable (std::vector< HPACKHeader > &headers)
void describe (std::ostream &os) const
Protected Member Functions
const StaticHeaderTable & getStaticTable () const
uint32_t globalToDynamicIndex (uint32_t index) const
uint32_t globalToStaticIndex (uint32_t index) const
uint32_t dynamicToGlobalIndex (uint32_t index) const
uint32_t staticToGlobalIndex (uint32_t index) const
Protected Attributes
HeaderTable table_
Detailed Description
Definition at line 18 of file HPACKContext.h.
Constructor & Destructor Documentation
proxygen::HPACKContext::HPACKContext (uint32_t tableSize) [explicit]
Definition at line 14 of file HPACKContext.cpp.
                                             :
    table_(tableSize) {
}
proxygen::HPACKContext::~HPACKContext () [inline]
Definition at line 21 of file HPACKContext.h.
References getHeader(), getIndex(), isStatic(), and nameIndex().
{}
Member Function Documentation
void proxygen::HPACKContext::describe (std::ostream & os) const
Definition at line 82 of file HPACKContext.cpp.
References table_.
Referenced by getHeadersStored(), and proxygen::operator<<().
                                                {
  os << table_;
}
uint32_t proxygen::HPACKContext::dynamicToGlobalIndex (uint32_t index) const [inline], [protected]
Definition at line 79 of file HPACKContext.h.
References getStaticTable(), and proxygen::HeaderTable::size().
Referenced by getIndex(), and nameIndex().
                                                      {
    return index + getStaticTable().size();
  }
uint32_t proxygen::HPACKContext::getBytesStored () const [inline]
Definition at line 56 of file HPACKContext.h.
References proxygen::HeaderTable::bytes(), and table_.
                                  {
    return table_.bytes();
  }
const HPACKHeader & proxygen::HPACKContext::getHeader (uint32_t index)
Returns
header at the given index by composing dynamic and static tables
Definition at line 68 of file HPACKContext.cpp.
References proxygen::HeaderTable::getHeader(), getStaticTable(), globalToDynamicIndex(), globalToStaticIndex(), isStatic(), and table_.
Referenced by proxygen::HPACKDecoder::decodeIndexedHeader(), proxygen::HPACKDecoder::decodeLiteralHeader(), TEST_F(), TEST_P(), and ~HPACKContext().
                                                         {
  if (isStatic(index)) {
    return getStaticTable().getHeader(globalToStaticIndex(index));
  }
  return table_.getHeader(globalToDynamicIndex(index));
}
uint32_t proxygen::HPACKContext::getHeadersStored () const [inline]
Definition at line 60 of file HPACKContext.h.
References describe(), seedHeaderTable(), proxygen::HeaderTable::size(), and table_.
                                    {
    return table_.size();
  }
uint32_t proxygen::HPACKContext::getIndex (const HPACKHeader & header) const
get the index of the given header by looking into both dynamic and static header table
Returns
0 if cannot be found
Definition at line 18 of file HPACKContext.cpp.
References dynamicToGlobalIndex(), proxygen::HPACKHeaderName::getHeaderCode(), proxygen::HeaderTable::getIndex(), getStaticTable(), proxygen::HPACKHeaderName::isCommonHeader(), proxygen::StaticHeaderTable::isHeaderCodeInTableWithNonEmptyValue(), proxygen::HPACKHeader::name, staticToGlobalIndex(), table_, and proxygen::HPACKHeader::value.
Referenced by proxygen::HPACKEncoder::encodeHeader(), TEST_F(), and ~HPACKContext().
                                                               {
  // First consult the static header table if applicable
  // Applicability is determined by the following guided optimizations:
  // 1) The set of CommonHeaders includes all StaticTable headers and so we can
  // quickly conclude that we need not check the StaticTable
  // for non-CommonHeaders
  // 2) The StaticTable only contains non empty values for a very small subset
  // of header names. As getIndex is only meaingful if both name and value
  // match, we know that if our header has a value and is not part of the very
  // small subset of header names, there is no point consulting the StaticTable
  bool consultStaticTable = false;
  if (header.value.empty()) {
    consultStaticTable = header.name.isCommonHeader();
  } else {
    consultStaticTable =
      StaticHeaderTable::isHeaderCodeInTableWithNonEmptyValue(
        header.name.getHeaderCode());
  }
  if (consultStaticTable) {
    uint32_t staticIndex = getStaticTable().getIndex(header);
    if (staticIndex) {
      return staticToGlobalIndex(staticIndex);
    }
  }
  // Else check the dynamic table
  uint32_t dynamicIndex = table_.getIndex(header);
  if (dynamicIndex) {
    return dynamicToGlobalIndex(dynamicIndex);
  } else {
    return dynamicIndex;
  }
}
const StaticHeaderTable& proxygen::HPACKContext::getStaticTable () const [inline], [protected]
Definition at line 69 of file HPACKContext.h.
References proxygen::StaticHeaderTable::get().
Referenced by dynamicToGlobalIndex(), getHeader(), getIndex(), globalToDynamicIndex(), isStatic(), proxygen::HPACKDecoder::isValid(), and nameIndex().
                                                  {
    return StaticHeaderTable::get();
  }
const HeaderTable& proxygen::HPACKContext::getTable () const [inline]
Definition at line 48 of file HPACKContext.h.
References table_.
Referenced by proxygen::hpack::encodeDecode(), TEST_F(), and TEST_P().
                                      {
    return table_;
  }
uint32_t proxygen::HPACKContext::getTableSize () const [inline]
Definition at line 52 of file HPACKContext.h.
References proxygen::HeaderTable::capacity(), and table_.
                                {
    return table_.capacity();
  }
uint32_t proxygen::HPACKContext::globalToDynamicIndex (uint32_t index) const [inline], [protected]
Definition at line 73 of file HPACKContext.h.
References getStaticTable(), and proxygen::HeaderTable::size().
Referenced by getHeader(), and proxygen::HPACKDecoder::isValid().
                                                      {
    return index - getStaticTable().size();
  }
uint32_t proxygen::HPACKContext::globalToStaticIndex (uint32_t index) const [inline], [protected]
Definition at line 76 of file HPACKContext.h.
Referenced by getHeader(), and proxygen::HPACKDecoder::isValid().
                                                     {
    return index;
  }
bool proxygen::HPACKContext::isStatic (uint32_t index) const
Returns
true if the given index points to a static header entry
Definition at line 64 of file HPACKContext.cpp.
References getStaticTable(), and proxygen::HeaderTable::size().
Referenced by getHeader(), proxygen::HPACKDecoder::isValid(), TEST_F(), and ~HPACKContext().
                                                {
  return index <= getStaticTable().size();
}
uint32_t proxygen::HPACKContext::nameIndex (const HPACKHeaderName & headerName) const
index of a header entry with the given name from dynamic or static table
Returns
0 if name not found
Definition at line 52 of file HPACKContext.cpp.
References dynamicToGlobalIndex(), getStaticTable(), proxygen::HeaderTable::nameIndex(), staticToGlobalIndex(), and table_.
Referenced by proxygen::HPACKEncoder::encodeAsLiteral(), proxygen::HPACKEncoder::encodeLiteral(), proxygen::HPACKEncoder::setHeaderTableSize(), and ~HPACKContext().
                                                                        {
  uint32_t index = getStaticTable().nameIndex(headerName);
  if (index) {
    return staticToGlobalIndex(index);
  }
  index = table_.nameIndex(headerName);
  if (index) {
    return dynamicToGlobalIndex(index);
  }
  return 0;
}
void proxygen::HPACKContext::seedHeaderTable (std::vector< HPACKHeader > & headers)
Definition at line 75 of file HPACKContext.cpp.
References proxygen::HeaderTable::add(), and table_.
Referenced by getHeadersStored().
                                   {
  for (auto& header: headers) {
    table_.add(std::move(header));
  }
}
uint32_t proxygen::HPACKContext::staticToGlobalIndex (uint32_t index) const [inline], [protected]
Definition at line 82 of file HPACKContext.h.
Referenced by getIndex(), and nameIndex().
                                                     {
    return index;
  }
Member Data Documentation
HeaderTable proxygen::HPACKContext::table_ [protected]
Definition at line 86 of file HPACKContext.h.
Referenced by proxygen::HPACKDecoder::decodeHeader(), proxygen::HPACKDecoder::decodeLiteralHeader(), describe(), proxygen::HPACKEncoder::encode(), proxygen::HPACKEncoder::encodeAsLiteral(), getBytesStored(), getHeader(), getHeadersStored(), getIndex(), getTable(), getTableSize(), proxygen::HPACKDecoder::isValid(), nameIndex(), seedHeaderTable(), proxygen::HPACKDecoder::setHeaderTableMaxSize(), and proxygen::HPACKEncoder::setHeaderTableSize().
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/compress/HPACKContext.h
proxygen/lib/http/codec/compress/HPACKContext.cpp