proxygen::NoPathIndexingStrategy Class Reference
#include <NoPathIndexingStrategy.h>
Public Member Functions
NoPathIndexingStrategy ()
bool indexHeader (const HPACKHeader &header) const override
Static Public Member Functions
static const NoPathIndexingStrategy * getInstance ()
Detailed Description
Definition at line 16 of file NoPathIndexingStrategy.h.
Constructor & Destructor Documentation
proxygen::NoPathIndexingStrategy::NoPathIndexingStrategy () [inline]
Definition at line 20 of file NoPathIndexingStrategy.h.
Referenced by getInstance().
    : HeaderIndexingStrategy() {}
Member Function Documentation
const NoPathIndexingStrategy * proxygen::NoPathIndexingStrategy::getInstance () [static]
Definition at line 14 of file NoPathIndexingStrategy.cpp.
References NoPathIndexingStrategy().
Referenced by proxygen::compress::HPACKScheme::HPACKScheme(), and proxygen::compress::QPACKScheme::QPACKScheme().
                                                                  {
  static const NoPathIndexingStrategy* instance = new NoPathIndexingStrategy();
  return instance;
}
bool proxygen::NoPathIndexingStrategy::indexHeader (const HPACKHeader & header) const [inline], [override], [virtual]
Reimplemented from proxygen::HeaderIndexingStrategy .
Definition at line 24 of file NoPathIndexingStrategy.h.
References proxygen::HPACKHeaderName::getHeaderCode(), proxygen::HeaderIndexingStrategy::indexHeader(), and proxygen::HPACKHeader::name.
                                                             {
    if (header.name.getHeaderCode() == HTTP_HEADER_COLON_PATH) {
      return false;
    } else {
      return HeaderIndexingStrategy::indexHeader(header);
    }
  }
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/compress/NoPathIndexingStrategy.h
proxygen/lib/http/codec/compress/NoPathIndexingStrategy.cpp