proxygen::HPACKEncoder Class Reference
#include <HPACKEncoder.h>
Public Member Functions
HPACKEncoder (bool huffman, uint32_t tableSize=HPACK::kTableSize)
std::unique_ptr< folly::IOBuf > encode (const std::vector< HPACKHeader > &headers, uint32_t headroom=0)
void setHeaderTableSize (uint32_t size)
Private Member Functions
void encodeAsIndex (uint32_t index)
void encodeHeader (const HPACKHeader &header)
bool encodeAsLiteral (const HPACKHeader &header, bool indexing)
void encodeLiteral (const HPACKHeader &header, uint32_t nameIndex, const HPACK::Instruction &instruction)
Additional Inherited Members
Detailed Description
Definition at line 19 of file HPACKEncoder.h.
Constructor & Destructor Documentation
proxygen::HPACKEncoder::HPACKEncoder (bool huffman, uint32_t tableSize = HPACK::kTableSize) [inline], [explicit]
Definition at line 22 of file HPACKEncoder.h.
References encode().
      : HPACKEncoderBase(huffman)
      , HPACKContext(tableSize) {}
Member Function Documentation
std::unique_ptr< folly::IOBuf > proxygen::HPACKEncoder::encode (const std::vector< HPACKHeader > & headers, uint32_t headroom = 0)
Encode the given headers.
Definition at line 17 of file HPACKEncoder.cpp.
References proxygen::HPACKEncodeBuffer::addHeadroom(), proxygen::HeaderTable::capacity(), encodeHeader(), proxygen::HPACKEncoderBase::handlePendingContextUpdate(), proxygen::HPACKEncodeBuffer::release(), proxygen::HPACKEncoderBase::streamBuffer_, and proxygen::HPACKContext::table_.
Referenced by encode(), proxygen::HPACKCodec::encode(), proxygen::hpack::encodeDecode(), HPACKEncoder(), TEST_F(), and TEST_P().
                                                                          {
  if (headroom) {
    streamBuffer_.addHeadroom(headroom);
  }
  handlePendingContextUpdate(streamBuffer_, table_.capacity());
  for (const auto& header : headers) {
    encodeHeader(header);
  }
  return streamBuffer_.release();
}
void proxygen::HPACKEncoder::encodeAsIndex (uint32_t index) [private]
Definition at line 63 of file HPACKEncoder.cpp.
References proxygen::HPACKEncodeBuffer::encodeInteger(), proxygen::HPACK::INDEX_REF, and proxygen::HPACKEncoderBase::streamBuffer_.
Referenced by encodeHeader(), and setHeaderTableSize().
                                               {
  VLOG(10) << "encoding index=" << index;
  streamBuffer_.encodeInteger(index, HPACK::INDEX_REF);
}
bool proxygen::HPACKEncoder::encodeAsLiteral (const HPACKHeader & header, bool indexing) [private]
Definition at line 28 of file HPACKEncoder.cpp.
References proxygen::HeaderTable::add(), proxygen::HPACKHeader::bytes(), proxygen::HeaderTable::capacity(), proxygen::HPACKHeader::copy(), encodeLiteral(), proxygen::HPACK::LITERAL, proxygen::HPACK::LITERAL_INC_INDEX, proxygen::HPACKHeader::name, proxygen::HPACKContext::nameIndex(), and proxygen::HPACKContext::table_.
Referenced by encodeHeader(), and setHeaderTableSize().
                                                                           {
  if (header.bytes() > table_.capacity()) {
    // May want to investigate further whether or not this is wanted.
    // Flushing the table on a large header frees up some memory,
    // however, there will be no compression due to an empty table, and
    // the table will fill up again fairly quickly
    indexing = false;
  }
  HPACK::Instruction instruction = (indexing) ?
    HPACK::LITERAL_INC_INDEX : HPACK::LITERAL;
  encodeLiteral(header, nameIndex(header.name), instruction);
  // indexed ones need to get added to the header table
  if (indexing) {
    CHECK(table_.add(header.copy()));
  }
  return true;
}
void proxygen::HPACKEncoder::encodeHeader (const HPACKHeader & header) [private]
Definition at line 68 of file HPACKEncoder.cpp.
References encodeAsIndex(), encodeAsLiteral(), proxygen::HPACKContext::getIndex(), proxygen::HeaderIndexingStrategy::indexHeader(), and proxygen::HPACKEncoderBase::indexingStrat_.
Referenced by encode(), and setHeaderTableSize().
                                                         {
  // First determine whether the header is defined as indexable using the
  // set strategy if applicable, else assume it is indexable
  bool indexable = !indexingStrat_ || indexingStrat_->indexHeader(header);
  // If the header was not defined as indexable, its a reasonable assumption
  // that it does not appear in either the static or dynamic table and should
  // not be searched. The only time this is not true is if the header indexing
  // strat specified an exact header/value pair that is in the static header
  // table although semantically the header indexing strategy should indeed act
  // as an override so we assume this is desired if such a case occurs
  uint32_t index = 0;
  if (indexable) {
    index = getIndex(header);
  }
  // Finally encode the header as determined above
  if (index) {
    encodeAsIndex(index);
  } else {
    encodeAsLiteral(header, indexable);
  }
}
void proxygen::HPACKEncoder::encodeLiteral (const HPACKHeader & header, uint32_t nameIndex, const HPACK::Instruction & instruction) [private]
Definition at line 48 of file HPACKEncoder.cpp.
References proxygen::HPACKEncodeBuffer::encodeInteger(), proxygen::HPACKEncodeBuffer::encodeLiteral(), proxygen::HPACKHeaderName::get(), proxygen::HPACKHeader::name, proxygen::HPACKContext::nameIndex(), proxygen::HPACKEncoderBase::streamBuffer_, and proxygen::HPACKHeader::value.
Referenced by encodeAsLiteral(), and setHeaderTableSize().
                                                                      {
  // name
  if (nameIndex) {
    VLOG(10) << "encoding name index=" << nameIndex;
    streamBuffer_.encodeInteger(nameIndex, instruction);
  } else {
    streamBuffer_.encodeInteger(0, instruction);
    streamBuffer_.encodeLiteral(header.name.get());
  }
  // value
  streamBuffer_.encodeLiteral(header.value);
}
void proxygen::HPACKEncoder::setHeaderTableSize (uint32_t size) [inline]
Definition at line 35 of file HPACKEncoder.h.
References encodeAsIndex(), encodeAsLiteral(), encodeHeader(), encodeLiteral(), proxygen::HPACKContext::nameIndex(), proxygen::HPACKEncoderBase::setHeaderTableSize(), and proxygen::HPACKContext::table_.
Referenced by TEST_P().
                                         {
    HPACKEncoderBase::setHeaderTableSize(table_, size);
  }
The documentation for this class was generated from the following files:
proxygen/lib/http/codec/compress/HPACKEncoder.h
proxygen/lib/http/codec/compress/HPACKEncoder.cpp