proxygen::HeaderCodec Class Reference
#include <HeaderCodec.h>
Classes
class Stats
Public Types
enum Type : uint8_t { Type::GZIP = 0,
Type::HPACK = 1,
Type::QPACK = 2
 }
Public Member Functions
HeaderCodec ()
virtual ~HeaderCodec ()
const HTTPHeaderSize & getEncodedSize ()
void setEncodeHeadroom (uint32_t headroom)
virtual void setMaxUncompressed (uint64_t maxUncompressed)
uint64_t getMaxUncompressed () const
void setStats (Stats *stats)
Static Public Attributes
static const uint32_t kMaxUncompressed = 128 * 1024
Protected Attributes
HTTPHeaderSize encodedSize_
uint32_t encodeHeadroom_ {0}
uint64_t maxUncompressed_ {kMaxUncompressed}
Stats * stats_ {nullptr}
Detailed Description
Definition at line 35 of file HeaderCodec.h.
Member Enumeration Documentation
enum proxygen::HeaderCodec::Type : uint8_t [strong]
Enumerator
GZIP
HPACK
QPACK
Definition at line 39 of file HeaderCodec.h.
                  : uint8_t {
    GZIP = 0,
    HPACK = 1,
    QPACK = 2
  };
Constructor & Destructor Documentation
proxygen::HeaderCodec::HeaderCodec () [inline]
Definition at line 56 of file HeaderCodec.h.
{}
virtual proxygen::HeaderCodec::~HeaderCodec () [inline], [virtual]
Definition at line 57 of file HeaderCodec.h.
{}
Member Function Documentation
const HTTPHeaderSize& proxygen::HeaderCodec::getEncodedSize () [inline]
compressed and uncompressed size of the last encode
Definition at line 62 of file HeaderCodec.h.
Referenced by proxygen::compress::HPACKScheme::encode(), proxygen::compress::QPACKScheme::encode(), proxygen::HTTP2Codec::encodeHeaders(), and proxygen::SPDYCodec::encodeHeaders().
                                         {
    return encodedSize_;
  }
uint64_t proxygen::HeaderCodec::getMaxUncompressed () const [inline]
Definition at line 77 of file HeaderCodec.h.
                                      {
    return maxUncompressed_;
  }
void proxygen::HeaderCodec::setEncodeHeadroom (uint32_t headroom) [inline]
amount of space to reserve as a headroom in the encode buffer
Definition at line 69 of file HeaderCodec.h.
Referenced by proxygen::HTTP2Codec::encodeHeaders(), proxygen::SPDYCodec::encodeHeaders(), and proxygen::compress::HPACKScheme::HPACKScheme().
                                            {
    encodeHeadroom_ = headroom;
  }
virtual void proxygen::HeaderCodec::setMaxUncompressed (uint64_t maxUncompressed) [inline], [virtual]
Reimplemented in proxygen::QPACKCodec , and proxygen::HPACKCodec .
Definition at line 73 of file HeaderCodec.h.
Referenced by proxygen::SPDYCodec::setMaxUncompressedHeaders(), and proxygen::SPDYCodec::SPDYCodec().
                                                            {
    maxUncompressed_ = maxUncompressed;
  }
void proxygen::HeaderCodec::setStats (Stats * stats) [inline]
set the stats object
Definition at line 84 of file HeaderCodec.h.
Referenced by proxygen::HTTP2Codec::setHeaderCodecStats().
                              {
    stats_ = stats;
  }
Member Data Documentation
HTTPHeaderSize proxygen::HeaderCodec::encodedSize_ [protected]
Definition at line 90 of file HeaderCodec.h.
Referenced by proxygen::QPACKCodec::encode(), proxygen::GzipHeaderCodec::encode(), proxygen::HPACKCodec::encode(), proxygen::HPACKCodec::recordCompressedSize(), and proxygen::QPACKCodec::recordCompressedSize().
uint32_t proxygen::HeaderCodec::encodeHeadroom_ {0} [protected]
Definition at line 91 of file HeaderCodec.h.
Referenced by proxygen::QPACKCodec::encode(), proxygen::GzipHeaderCodec::encode(), and proxygen::HPACKCodec::encode().
const uint32_t proxygen::HeaderCodec::kMaxUncompressed = 128 * 1024 [static]
Definition at line 37 of file HeaderCodec.h.
uint64_t proxygen::HeaderCodec::maxUncompressed_ {kMaxUncompressed} [protected]
Definition at line 92 of file HeaderCodec.h.
Referenced by proxygen::GzipHeaderCodec::decode(), and proxygen::GzipHeaderCodec::getHeaderBuf().
Stats* proxygen::HeaderCodec::stats_ {nullptr} [protected]
Definition at line 93 of file HeaderCodec.h.
Referenced by proxygen::GzipHeaderCodec::decode(), proxygen::HPACKCodec::decodeStreaming(), proxygen::QPACKCodec::decodeStreaming(), proxygen::GzipHeaderCodec::encode(), proxygen::HPACKCodec::recordCompressedSize(), and proxygen::QPACKCodec::recordCompressedSize().
The documentation for this class was generated from the following file:
proxygen/lib/http/codec/compress/HeaderCodec.h