proxygen/lib/http/codec/compress/test/HPACKBenchmark.cpp File Reference
#include <proxygen/lib/http/codec/compress/test/TestUtil.h>
*
#include <proxygen/lib/http/codec/compress/test/TestStreamingCallback.h>
*
#include <folly/Benchmark.h>
*
#include <folly/Range.h>
*
#include <algorithm>
*
Functions
unique_ptr< IOBuf > encode (vector< HPACKHeader > &headers, HPACKEncoder &encoder)
void encodeDecode (vector< HPACKHeader > &headers, HPACKEncoder &encoder, HPACKDecoder &decoder)
vector< HPACKHeader > getHeaders ()
void encodeBench (int reencodes, int iters)
void encodeDecodeBench (int reencodes, int iters)
BENCHMARK (Encode, iters)
BENCHMARK (Encode1, iters)
BENCHMARK (Encode2, iters)
BENCHMARK (EncodeDecode, iters)
BENCHMARK (EncodeDecode1, iters)
BENCHMARK (EncodeDecode2, iters)
int main (int argc, char **argv)
Function Documentation
BENCHMARK (Encode , iters)
Definition at line 81 of file HPACKBenchmark.cpp.
References encodeBench().
                         {
  encodeBench(0, iters);
}
BENCHMARK (Encode1 , iters)
Definition at line 85 of file HPACKBenchmark.cpp.
References encodeBench().
                          {
  encodeBench(1, iters);
}
BENCHMARK (Encode2 , iters)
Definition at line 89 of file HPACKBenchmark.cpp.
References encodeBench().
                          {
  encodeBench(2, iters);
}
BENCHMARK (EncodeDecode , iters)
Definition at line 93 of file HPACKBenchmark.cpp.
References encodeDecodeBench().
                               {
  encodeDecodeBench(0, iters);
}
BENCHMARK (EncodeDecode1 , iters)
Definition at line 97 of file HPACKBenchmark.cpp.
References encodeDecodeBench().
                                {
  encodeDecodeBench(1, iters);
}
BENCHMARK (EncodeDecode2 , iters)
Definition at line 101 of file HPACKBenchmark.cpp.
References encodeDecodeBench().
                                {
  encodeDecodeBench(2, iters);
}
unique_ptr<IOBuf> encode (vector< HPACKHeader > & headers, HPACKEncoder & encoder)
Definition at line 22 of file HPACKBenchmark.cpp.
References proxygen::HPACKEncoder::encode().
Referenced by encodeBench(), encodeDecode(), TEST(), proxygen::Base64::urlEncode(), proxygen::HPACKCodec::~HPACKCodec(), proxygen::huffman::HuffTree::~HuffTree(), and proxygen::QPACKCodec::~QPACKCodec().
                                                                              {
  return encoder.encode(headers);
}
void encodeBench (int reencodes, int iters)
Definition at line 60 of file HPACKBenchmark.cpp.
References encode().
Referenced by BENCHMARK().
                                           {
  for (int i = 0; i < iters; i++) {
    HPACKEncoder encoder(true);
    encode(headers, encoder);
    for (int j = 0; j < reencodes; j++) {
      encode(headers, encoder);
    }
  }
}
void encodeDecode (vector< HPACKHeader > & headers, HPACKEncoder & encoder, HPACKDecoder & decoder)
Definition at line 26 of file HPACKBenchmark.cpp.
References proxygen::HPACKDecoder::decodeStreaming(), encode(), and proxygen::TestStreamingCallback::hasError().
Referenced by encodeDecodeBench(), isLowercase(), TEST_F(), and TEST_P().
                                         {
  unique_ptr<IOBuf> encoded = encode(headers, encoder);
  CHECK(encoded);
  TestStreamingCallback cb;
  folly::io::Cursor c(encoded.get());
  decoder.decodeStreaming(c, c.totalLength(), &cb);
  CHECK(!cb.hasError());
}
void encodeDecodeBench (int reencodes, int iters)
Definition at line 70 of file HPACKBenchmark.cpp.
References encodeDecode().
Referenced by BENCHMARK().
                                                 {
  for (int i = 0; i < iters; i++) {
    HPACKEncoder encoder(true);
    HPACKDecoder decoder;
    encodeDecode(headers, encoder, decoder);
    for (int j = 0; j < reencodes; j++) {
      encodeDecode(headers, encoder, decoder);
    }
  }
}
vector<HPACKHeader> getHeaders ()
Definition at line 37 of file HPACKBenchmark.cpp.
                                 {
  vector<HPACKHeader> headers;
  headers.emplace_back(":authority", "www.facebook.com");
  headers.emplace_back(":method", "GET");
  headers.emplace_back(":path", "/graphql");
  headers.emplace_back(":scheme", "https");
  headers.emplace_back(
    "user-agent",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/60.0.3100.0 Safari/537.36");
  headers.emplace_back("accept-encoding", "gzip, deflate, br");
  headers.emplace_back("accept-language", "en-US,en;q=0.8");
  headers.emplace_back(
    "accept",
    "text/html,application/xhtml+xml,application/xml;q=0.9,image/"
    "webp,image/apng,*/*;q=0.8");
  return headers;
}
int main (int argc, char ** argv)
Definition at line 105 of file HPACKBenchmark.cpp.
                                {
  gflags::ParseCommandLineFlags(&argc, &argv, true);
  folly::runBenchmarks();
  return 0;
}