proxygen/lib/http/codec/compress/test/LoggingTests.cpp File Reference
#include <folly/portability/GTest.h>
*
#include <list>
*
#include <proxygen/lib/http/codec/compress/HPACKEncodeBuffer.h>
*
#include <proxygen/lib/http/codec/compress/HPACKHeader.h>
*
#include <proxygen/lib/http/codec/compress/Logging.h>
*
#include <sstream>
*
#include <vector>
*
Classes
class LoggingTests
Functions
TEST_F (LoggingTests, Refset)
TEST_F (LoggingTests, DumpHeaderVector)
TEST_F (LoggingTests, PrintDelta)
TEST_F (LoggingTests, DumpBin)
Function Documentation
TEST_F (LoggingTests , Refset)
Definition at line 25 of file LoggingTests.cpp.
                             {
  list<uint32_t> refset;
  refset.push_back(3);
  refset.push_back(5);
  stringstream out;
  out << &refset;
  EXPECT_EQ(out.str(), "\n[3 5 ]\n");
}
TEST_F (LoggingTests , DumpHeaderVector)
Definition at line 34 of file LoggingTests.cpp.
                                       {
  vector<HPACKHeader> headers;
  headers.push_back(HPACKHeader(":path", "index.html"));
  headers.push_back(HPACKHeader("content-type", "gzip"));
  stringstream out;
  out << headers;
  EXPECT_EQ(out.str(), ":path: index.html\ncontent-type: gzip\n\n");
}
TEST_F (LoggingTests , PrintDelta)
Definition at line 43 of file LoggingTests.cpp.
References proxygen::printDelta().
                                 {
  vector<HPACKHeader> v1;
  v1.push_back(HPACKHeader(":path", "/"));
  v1.push_back(HPACKHeader(":host", "www.facebook.com"));
  vector<HPACKHeader> v2;
  // empty v1 or v2
  EXPECT_EQ(printDelta(v1, v2), "\n + :path: /\n + :host: www.facebook.com\n");
  EXPECT_EQ(printDelta(v2, v1), "\n - :path: /\n - :host: www.facebook.com\n");
  // skip first header from v1
  v2.push_back(HPACKHeader(":path", "/"));
  EXPECT_EQ(printDelta(v1, v2), "\n + :host: www.facebook.com\n");
  v2.push_back(HPACKHeader(":path", "/"));
  EXPECT_EQ(printDelta(v2, v1),
            "\n - :host: www.facebook.com\n + :path: / (duplicate)\n");
  v2.pop_back();
  v1.clear();
  v1.push_back(HPACKHeader(":a", "b"));
  v1.push_back(HPACKHeader(":a", "b"));
  v1.push_back(HPACKHeader(":path", "/"));
  EXPECT_EQ(printDelta(v1, v2), "\n + :a: b\n duplicate :a: b\n");
}
TEST_F (LoggingTests , DumpBin)
Definition at line 69 of file LoggingTests.cpp.
References proxygen::HPACKEncodeBuffer::encodeLiteral(), and proxygen::HPACKEncodeBuffer::toBin().
                              {
  // test with an HPACKEncodeBuffer
  HPACKEncodeBuffer buf(128);
  buf.encodeLiteral("test");
  EXPECT_EQ(buf.toBin(),
            "00000100 01110100 t 01100101 e 01110011 s 01110100 t \n");
}