proxygen/lib/http/test/HTTPHeadersBenchmark.cpp File Reference
#include <algorithm>
*
#include <folly/Benchmark.h>
*
#include <proxygen/lib/http/HTTPCommonHeaders.h>
*
Functions
void HTTPCommonHeadersHashBench (int iters)
void HTTPCommonHeadersGetHeaderCodeFromTableCommonHeaderNameBench (int iters)
BENCHMARK (HTTPCommonHeadersHash, iters)
BENCHMARK (HTTPCommonHeadersGetHeaderCodeFromTableCommonHeaderName, iters)
void memchrBench (int iters)
void stdFindBench (int iters)
BENCHMARK (memchr, iters)
BENCHMARK (stdFind, iters)
int main (int argc, char **argv)
Function Documentation
BENCHMARK (HTTPCommonHeadersHash , iters)
Definition at line 78 of file HTTPHeadersBenchmark.cpp.
References HTTPCommonHeadersHashBench().
                                        {
  HTTPCommonHeadersHashBench(iters);
}
BENCHMARK (HTTPCommonHeadersGetHeaderCodeFromTableCommonHeaderName , iters)
Definition at line 82 of file HTTPHeadersBenchmark.cpp.
References HTTPCommonHeadersGetHeaderCodeFromTableCommonHeaderNameBench().
                                                                          {
  HTTPCommonHeadersGetHeaderCodeFromTableCommonHeaderNameBench(iters);
}
BENCHMARK (memchr , iters)
Definition at line 112 of file HTTPHeadersBenchmark.cpp.
References memchrBench().
                         {
  memchrBench(iters);
}
BENCHMARK (stdFind , iters)
Definition at line 116 of file HTTPHeadersBenchmark.cpp.
References stdFindBench().
                          {
  stdFindBench(iters);
}
void HTTPCommonHeadersGetHeaderCodeFromTableCommonHeaderNameBench (int iters)
Definition at line 68 of file HTTPHeadersBenchmark.cpp.
References proxygen::HTTPHeaderCodeCommonOffset, and proxygen::TABLE_CAMELCASE.
Referenced by BENCHMARK().
                                                                             {
  for (int i = 0; i < iters; ++i) {
    for (uint64_t j = HTTPHeaderCodeCommonOffset;
         j < HTTPCommonHeaders::num_header_codes; ++j) {
      HTTPCommonHeaders::getHeaderCodeFromTableCommonHeaderName(
        &testHeaderNames[j], TABLE_CAMELCASE);
    }
  }
}
void HTTPCommonHeadersHashBench (int iters)
Definition at line 60 of file HTTPHeadersBenchmark.cpp.
Referenced by BENCHMARK().
                                           {
  for (int i = 0; i < iters; ++i) {
    for (auto const& testHeaderString: testHeaderStrings) {
      HTTPCommonHeaders::hash(*testHeaderString);
    }
  }
}
int main (int argc, char ** argv)
Definition at line 120 of file HTTPHeadersBenchmark.cpp.
                                {
  gflags::ParseCommandLineFlags(&argc, &argv, true);
  folly::runBenchmarks();
  return 0;
}
void memchrBench (int iters)
Definition at line 86 of file HTTPHeadersBenchmark.cpp.
References proxygen::HTTPHeaderCodeCommonOffset.
Referenced by BENCHMARK().
                            {
  for (int i = 0; i < iters; ++i) {
    for (uint64_t j = HTTPHeaderCodeCommonOffset;
         j < HTTPCommonHeaders::num_header_codes; ++j) {
      CHECK(
        memchr(
          (void*)testHeaderCodes.data(), static_cast<HTTPHeaderCode>(j),
          testHeaderCodes.size()) != nullptr);
    }
  }
}
void stdFindBench (int iters)
Definition at line 98 of file HTTPHeadersBenchmark.cpp.
References proxygen::HTTPHeaderCodeCommonOffset.
Referenced by BENCHMARK().
                             {
  for (int i = 0; i < iters; ++i) {
    for (uint64_t j = HTTPHeaderCodeCommonOffset;
         j < HTTPCommonHeaders::num_header_codes; ++j) {
      auto address = HTTPCommonHeaders::getPointerToHeaderName(
        static_cast<HTTPHeaderCode>(j));
      CHECK(
        std::find(
          testHeaderStrings.begin(), testHeaderStrings.end(), address) !=
            testHeaderStrings.end());
    }
  }
}