proxygen/lib/http/session/test/HTTPDefaultSessionCodecFactoryTest.cpp File Reference
#include <proxygen/lib/http/session/HTTPDefaultSessionCodecFactory.h>
*
#include <folly/portability/GTest.h>
*
#include <proxygen/lib/http/codec/HTTP1xCodec.h>
*
#include <proxygen/lib/http/codec/HTTP2Codec.h>
*
#include <proxygen/lib/http/codec/HTTP2Constants.h>
*
#include <proxygen/lib/http/codec/SPDYCodec.h>
*
#include <proxygen/lib/services/AcceptorConfiguration.h>
*
Functions
TEST (HTTPDefaultSessionCodecFactoryTest, GetCodecSPDY)
TEST (HTTPDefaultSessionCodecFactoryTest, GetCodecH2)
TEST (HTTPDefaultSessionCodecFactoryTest, GetCodecUpgradeProtocols)
TEST (HTTPDefaultSessionCodecFactoryTest, GetCodec)
Function Documentation
TEST (HTTPDefaultSessionCodecFactoryTest , GetCodecSPDY)
Definition at line 21 of file HTTPDefaultSessionCodecFactoryTest.cpp.
References proxygen::DOWNSTREAM, proxygen::HTTPDefaultSessionCodecFactory::getCodec(), proxygen::HTTP2Codec::getProtocol(), proxygen::SPDYCodec::getProtocol(), proxygen::HTTP_2, proxygen::AcceptorConfiguration::plaintextProtocol, proxygen::SPDY_3, proxygen::SPDY_3_1, and proxygen::UPSTREAM.
                                                       {
  AcceptorConfiguration conf;
  // If set directly on the acceptor, we should always return the SPDY version.
  conf.plaintextProtocol = "spdy/3.1";
  HTTPDefaultSessionCodecFactory factory(conf);
  auto codec = factory.getCodec(
      "http/1.1", TransportDirection::UPSTREAM, false /* isTLS */);
  SPDYCodec* spdyCodec = dynamic_cast<SPDYCodec*>(codec.get());
  EXPECT_NE(spdyCodec, nullptr);
  EXPECT_EQ(spdyCodec->getProtocol(), CodecProtocol::SPDY_3_1);
  codec = factory.getCodec(
      "spdy/3", TransportDirection::UPSTREAM, false /* isTLS */);
  spdyCodec = dynamic_cast<SPDYCodec*>(codec.get());
  EXPECT_NE(spdyCodec, nullptr);
  EXPECT_EQ(spdyCodec->getProtocol(), CodecProtocol::SPDY_3_1);
  conf.plaintextProtocol = "spdy/3";
  HTTPDefaultSessionCodecFactory secondFactory(conf);
  codec = secondFactory.getCodec(
      "http/1.1", TransportDirection::UPSTREAM, false /* isTLS */);
  spdyCodec = dynamic_cast<SPDYCodec*>(codec.get());
  EXPECT_NE(spdyCodec, nullptr);
  EXPECT_EQ(spdyCodec->getProtocol(), CodecProtocol::SPDY_3);
  codec = secondFactory.getCodec(
      "spdy/3.1", TransportDirection::UPSTREAM, false /* isTLS */);
  spdyCodec = dynamic_cast<SPDYCodec*>(codec.get());
  EXPECT_NE(spdyCodec, nullptr);
  EXPECT_EQ(spdyCodec->getProtocol(), CodecProtocol::SPDY_3);
  // On a somewhat contrived example, if TLS we should return the version
  // negotiated through ALPN.
  codec = secondFactory.getCodec(
      "h2", TransportDirection::DOWNSTREAM, true /* isTLS */);
  HTTP2Codec* httpCodec = dynamic_cast<HTTP2Codec*>(codec.get());
  EXPECT_NE(httpCodec, nullptr);
  EXPECT_EQ(httpCodec->getProtocol(), CodecProtocol::HTTP_2);
}
TEST (HTTPDefaultSessionCodecFactoryTest , GetCodecH2)
Definition at line 63 of file HTTPDefaultSessionCodecFactoryTest.cpp.
References proxygen::DOWNSTREAM, proxygen::HTTPDefaultSessionCodecFactory::getCodec(), proxygen::HTTP1xCodec::getProtocol(), proxygen::HTTP2Codec::getProtocol(), proxygen::HTTP_1_1, proxygen::HTTP_2, proxygen::AcceptorConfiguration::plaintextProtocol, and proxygen::UPSTREAM.
                                                     {
  AcceptorConfiguration conf;
  // If set directly on the acceptor, we should always return the H2C version.
  conf.plaintextProtocol = "h2c";
  HTTPDefaultSessionCodecFactory factory(conf);
  auto codec = factory.getCodec(
      "http/1.1", TransportDirection::DOWNSTREAM, false /* isTLS */);
  HTTP2Codec* httpCodec = dynamic_cast<HTTP2Codec*>(codec.get());
  EXPECT_NE(httpCodec, nullptr);
  EXPECT_EQ(httpCodec->getProtocol(), CodecProtocol::HTTP_2);
  // On a somewhat contrived example, if TLS we should return the version
  // negotiated through ALPN.
  codec = factory.getCodec(
      "http/1.1", TransportDirection::UPSTREAM, true /* isTLS */);
  HTTP1xCodec* http1Codec = dynamic_cast<HTTP1xCodec*>(codec.get());
  EXPECT_NE(http1Codec, nullptr);
  EXPECT_EQ(http1Codec->getProtocol(), CodecProtocol::HTTP_1_1);
}
TEST (HTTPDefaultSessionCodecFactoryTest , GetCodecUpgradeProtocols)
Definition at line 83 of file HTTPDefaultSessionCodecFactoryTest.cpp.
References proxygen::AcceptorConfiguration::allowedPlaintextUpgradeProtocols, proxygen::DOWNSTREAM, proxygen::HTTP1xCodec::getAllowedUpgradeProtocols(), proxygen::HTTPDefaultSessionCodecFactory::getCodec(), and proxygen::http2::kProtocolCleartextString.
                                                                   {
  std::list<std::string> plainTextUpgrades = {http2::kProtocolCleartextString};
  AcceptorConfiguration conf;
  conf.allowedPlaintextUpgradeProtocols = plainTextUpgrades;
  HTTPDefaultSessionCodecFactory factory(conf);
  auto codec =
      factory.getCodec("http/1.1", TransportDirection::DOWNSTREAM, false);
  HTTP1xCodec* downstreamCodec = dynamic_cast<HTTP1xCodec*>(codec.get());
  EXPECT_NE(downstreamCodec, nullptr);
  EXPECT_FALSE(downstreamCodec->getAllowedUpgradeProtocols().empty());
  EXPECT_EQ(downstreamCodec->getAllowedUpgradeProtocols(),
            http2::kProtocolCleartextString);
  // If TLS, we should not attempt to upgrade.
  codec = factory.getCodec("http/1.1", TransportDirection::DOWNSTREAM, true);
  downstreamCodec = dynamic_cast<HTTP1xCodec*>(codec.get());
  EXPECT_NE(downstreamCodec, nullptr);
  EXPECT_TRUE(downstreamCodec->getAllowedUpgradeProtocols().empty());
}
TEST (HTTPDefaultSessionCodecFactoryTest , GetCodec)
Definition at line 104 of file HTTPDefaultSessionCodecFactoryTest.cpp.
References proxygen::DOWNSTREAM, proxygen::HTTPDefaultSessionCodecFactory::getCodec(), proxygen::HTTP1xCodec::getProtocol(), proxygen::HTTP2Codec::getProtocol(), proxygen::SPDYCodec::getProtocol(), proxygen::HTTP_1_1, proxygen::HTTP_2, proxygen::SPDY_3_1, and proxygen::UPSTREAM.
                                                   {
  AcceptorConfiguration conf;
  HTTPDefaultSessionCodecFactory factory(conf);
  // Empty protocol should default to http/1.1
  auto codec =
      factory.getCodec("", TransportDirection::DOWNSTREAM, false /* isTLS */);
  HTTP1xCodec* http1Codec = dynamic_cast<HTTP1xCodec*>(codec.get());
  EXPECT_NE(http1Codec, nullptr);
  EXPECT_EQ(http1Codec->getProtocol(), CodecProtocol::HTTP_1_1);
  codec = factory.getCodec(
      "spdy/3.1", TransportDirection::UPSTREAM, false /* isTLS */);
  SPDYCodec* spdyCodec = dynamic_cast<SPDYCodec*>(codec.get());
  EXPECT_NE(spdyCodec, nullptr);
  EXPECT_EQ(spdyCodec->getProtocol(), CodecProtocol::SPDY_3_1);
  codec =
      factory.getCodec("h2", TransportDirection::DOWNSTREAM, false /* isTLS */);
  HTTP2Codec* httpCodec = dynamic_cast<HTTP2Codec*>(codec.get());
  EXPECT_NE(httpCodec, nullptr);
  EXPECT_EQ(httpCodec->getProtocol(), CodecProtocol::HTTP_2);
  // Not supported protocols should return nullptr.
  codec = factory.getCodec(
      "not/supported", TransportDirection::DOWNSTREAM, false /* isTLS */);
  EXPECT_EQ(codec, nullptr);
}