PushService Namespace Reference
Classes
class PushRequestHandler
class PushStats
Functions
const std::string kPushFileName (`proxygen/httpserver/samples/push/pusheen.txt`)
std::string createLargeBody ()
std::string generateUrl (const HTTPMessage &message, const char *path)
Variables
std::string gPushBody
Function Documentation
std::string PushService::createLargeBody ()
Definition at line 26 of file PushRequestHandler.cpp.
References gPushBody.
Referenced by PushService::PushRequestHandler::onRequest().
                            {
  std::string data = gPushBody;
  while(data.size() < 1000*1000) {
    data += gPushBody;
  }
  return data;
}
std::string PushService::generateUrl (const HTTPMessage & message, const char * path)
Definition at line 34 of file PushRequestHandler.cpp.
References proxygen::HTTPMessage::createUrl(), proxygen::HTTPMessage::getHeaders(), proxygen::HTTPHeaders::getSingleOrEmpty(), and proxygen::HTTPMessage::isSecure().
Referenced by PushService::PushRequestHandler::onRequest().
                                                                    {
  return HTTPMessage::createUrl(
      message.isSecure() ? "https" : "http",
      message.getHeaders().getSingleOrEmpty(HTTP_HEADER_HOST), path, "", "");
}
const std::string PushService::kPushFileName (`proxygen/httpserver/samples/push/pusheen.txt`)
Referenced by PushService::PushRequestHandler::PushRequestHandler().
Variable Documentation
std::string PushService::gPushBody
Definition at line 23 of file PushRequestHandler.cpp.
Referenced by createLargeBody(), and PushService::PushRequestHandler::PushRequestHandler().