proxygen::http2 Namespace Reference
Classes
struct FrameHeader
struct PriorityUpdate
Typedefs
using Padding = folly::Optional< uint8_t >
Enumerations
enum FrameType : uint8_t {
*
FrameType::DATA = 0,
FrameType::HEADERS = 1,
PRIORITY = 2,
FrameType::RST_STREAM = 3,
*
FrameType::SETTINGS = 4,
FrameType::PUSH_PROMISE = 5,
FrameType::PING = 6,
FrameType::GOAWAY = 7,
*
FrameType::WINDOW_UPDATE = 8,
FrameType::CONTINUATION = 9,
FrameType::ALTSVC = 10,
FrameType::EX_HEADERS = 0xfb,
*
FrameType::CERTIFICATE_REQUEST = 0xf0,
FrameType::CERTIFICATE = 0xf1,
FrameType::CERTIFICATE_NEEDED = 0xf2,
FrameType::USE_CERTIFICATE = 0xf3
 }
enum Flags {
*
ACK = 0x1,
END_STREAM = 0x1,
END_HEADERS = 0x4,
PADDED = 0x8,
*
PRIORITY = 0x20,
PRIORITY = 2,
UNIDIRECTIONAL = 0x40,
UNSOLICITED = 0x1,
*
TO_BE_CONTINUED = 0x1
 }
Functions
ErrorCode filterInvalidStream (ErrorCode code)
ErrorCode errorCodeToGoaway (ErrorCode code)
ErrorCode errorCodeToReset (ErrorCode code)
const std::string kConnectionPreface (`PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n`)
const std::string kProtocolString (`h2`)
const std::string kProtocolDraftString (`h2-14`)
const std::string kProtocolExperimentalString (`h2-fb`)
const std::string kProtocolCleartextString (`h2c`)
const std::string kProtocolSettingsHeader (`HTTP2-Settings`)
bool isValidFrameType (FrameType type)
bool frameAffectsCompression (FrameType t)
bool frameHasPadding (const FrameHeader &header)
ErrorCode parseFrameHeader (Cursor &cursor, FrameHeader &header) noexcept
ErrorCode parseData (Cursor &cursor, const FrameHeader &header, std::unique_ptr< IOBuf > &outBuf, uint16_t &outPadding) noexcept
ErrorCode parseDataBegin (Cursor &cursor, const FrameHeader &header, size_t &, uint16_t &outPadding) noexcept
ErrorCode parseDataEnd (Cursor &cursor, const size_t bufLen, const size_t pendingDataFramePaddingBytes, size_t &toSkip) noexcept
ErrorCode parseHeaders (Cursor &cursor, const FrameHeader &header, folly::Optional< PriorityUpdate > &outPriority, std::unique_ptr< IOBuf > &outBuf) noexcept
ErrorCode parseExHeaders (Cursor &cursor, const FrameHeader &header, HTTPCodec::ExAttributes &outExAttributes, folly::Optional< PriorityUpdate > &outPriority, std::unique_ptr< IOBuf > &outBuf) noexcept
ErrorCode parsePriority (Cursor &cursor, const FrameHeader &header, PriorityUpdate &outPriority) noexcept
ErrorCode parseRstStream (Cursor &cursor, const FrameHeader &header, ErrorCode &outCode) noexcept
ErrorCode parseSettings (Cursor &cursor, const FrameHeader &header, std::deque< SettingPair > &settings) noexcept
ErrorCode parsePushPromise (Cursor &cursor, const FrameHeader &header, uint32_t &outPromisedStream, std::unique_ptr< IOBuf > &outBuf) noexcept
ErrorCode parsePing (Cursor &cursor, const FrameHeader &header, uint64_t &outOpaqueData) noexcept
ErrorCode parseGoaway (Cursor &cursor, const FrameHeader &header, uint32_t &outLastStreamID, ErrorCode &outCode, std::unique_ptr< IOBuf > &outDebugData) noexcept
ErrorCode parseWindowUpdate (Cursor &cursor, const FrameHeader &header, uint32_t &outAmount) noexcept
ErrorCode parseContinuation (Cursor &cursor, const FrameHeader &header, std::unique_ptr< IOBuf > &outBuf) noexcept
ErrorCode parseAltSvc (Cursor &cursor, const FrameHeader &header, uint32_t &outMaxAge, uint32_t &outPort, std::string &outProtocol, std::string &outHost, std::string &outOrigin) noexcept
ErrorCode parseCertificateRequest (folly::io::Cursor &cursor, const FrameHeader &header, uint16_t &outRequestId, std::unique_ptr< folly::IOBuf > &outAuthRequest) noexcept
ErrorCode parseCertificate (folly::io::Cursor &cursor, const FrameHeader &header, uint16_t &outCertId, std::unique_ptr< folly::IOBuf > &outAuthenticator) noexcept
size_t writeData (IOBufQueue &queue, std::unique_ptr< IOBuf > data, uint32_t stream, folly::Optional< uint8_t > padding, bool endStream, bool reuseIOBufHeadroom) noexcept
size_t writeHeaders (IOBufQueue &queue, std::unique_ptr< IOBuf > headers, uint32_t stream, folly::Optional< PriorityUpdate > priority, folly::Optional< uint8_t > padding, bool endStream, bool endHeaders) noexcept
size_t writeExHeaders (IOBufQueue &queue, std::unique_ptr< IOBuf > headers, uint32_t stream, const HTTPCodec::ExAttributes &exAttributes, const folly::Optional< PriorityUpdate > &priority, const folly::Optional< uint8_t > &padding, bool endStream, bool endHeaders) noexcept
size_t writePriority (IOBufQueue &queue, uint32_t stream, PriorityUpdate priority) noexcept
size_t writeRstStream (IOBufQueue &queue, uint32_t stream, ErrorCode errorCode) noexcept
size_t writeSettings (IOBufQueue &queue, const std::deque< SettingPair > &settings)
size_t writeSettingsAck (IOBufQueue &queue)
size_t writePushPromise (IOBufQueue &queue, uint32_t associatedStream, uint32_t promisedStream, std::unique_ptr< IOBuf > headers, folly::Optional< uint8_t > padding, bool endHeaders) noexcept
size_t writePing (IOBufQueue &queue, uint64_t opaqueData, bool ack) noexcept
size_t writeGoaway (IOBufQueue &queue, uint32_t lastStreamID, ErrorCode errorCode, std::unique_ptr< IOBuf > debugData) noexcept
size_t writeWindowUpdate (IOBufQueue &queue, uint32_t stream, uint32_t amount) noexcept
size_t writeContinuation (IOBufQueue &queue, uint32_t stream, bool endHeaders, std::unique_ptr< IOBuf > headers) noexcept
size_t writeAltSvc (IOBufQueue &queue, uint32_t stream, uint32_t maxAge, uint16_t port, StringPiece protocol, StringPiece host, StringPiece origin) noexcept
size_t writeCertificateRequest (folly::IOBufQueue &writeBuf, uint16_t requestId, std::unique_ptr< folly::IOBuf > authRequest)
size_t writeCertificate (folly::IOBufQueue &writeBuf, uint16_t certId, std::unique_ptr< folly::IOBuf > authenticator, bool toBeContinued)
const char * getFrameTypeString (FrameType type)
ErrorCode parseFrameHeader (folly::io::Cursor &cursor, FrameHeader &header) noexcept
ErrorCode parseData (folly::io::Cursor &cursor, const FrameHeader &header, std::unique_ptr< folly::IOBuf > &outBuf, uint16_t &padding) noexcept
ErrorCode parseDataBegin (folly::io::Cursor &cursor, const FrameHeader &header, size_t &parsed, uint16_t &outPadding) noexcept
ErrorCode parseDataEnd (folly::io::Cursor &cursor, const size_t bufLen, const size_t pendingDataFramePaddingBytes, size_t &toSkip) noexcept
ErrorCode parseHeaders (folly::io::Cursor &cursor, const FrameHeader &header, folly::Optional< PriorityUpdate > &outPriority, std::unique_ptr< folly::IOBuf > &outBuf) noexcept
ErrorCode parseExHeaders (folly::io::Cursor &cursor, const FrameHeader &header, HTTPCodec::ExAttributes &outExAttributes, folly::Optional< PriorityUpdate > &outPriority, std::unique_ptr< folly::IOBuf > &outBuf) noexcept
ErrorCode parsePriority (folly::io::Cursor &cursor, const FrameHeader &header, PriorityUpdate &outPriority) noexcept
ErrorCode parseRstStream (folly::io::Cursor &cursor, const FrameHeader &header, ErrorCode &outCode) noexcept
ErrorCode parseSettings (folly::io::Cursor &cursor, const FrameHeader &header, std::deque< SettingPair > &settings) noexcept
ErrorCode parsePushPromise (folly::io::Cursor &cursor, const FrameHeader &header, uint32_t &outPromisedStream, std::unique_ptr< folly::IOBuf > &outBuf) noexcept
ErrorCode parsePing (folly::io::Cursor &cursor, const FrameHeader &header, uint64_t &outData) noexcept
ErrorCode parseGoaway (folly::io::Cursor &cursor, const FrameHeader &header, uint32_t &outLastStreamID, ErrorCode &outCode, std::unique_ptr< folly::IOBuf > &outDebugData) noexcept
ErrorCode parseWindowUpdate (folly::io::Cursor &cursor, const FrameHeader &header, uint32_t &outAmount) noexcept
ErrorCode parseContinuation (folly::io::Cursor &cursor, const FrameHeader &header, std::unique_ptr< folly::IOBuf > &outBuf) noexcept
ErrorCode parseAltSvc (folly::io::Cursor &cursor, const FrameHeader &header, uint32_t &outMaxAge, uint32_t &outPort, std::string &outProtocol, std::string &outHost, std::string &outOrigin) noexcept
size_t writeData (folly::IOBufQueue &writeBuf, std::unique_ptr< folly::IOBuf > data, uint32_t stream, folly::Optional< uint8_t > padding, bool endStream, bool reuseIOBufHeadroom) noexcept
size_t writeHeaders (folly::IOBufQueue &writeBuf, std::unique_ptr< folly::IOBuf > headers, uint32_t stream, folly::Optional< PriorityUpdate > priority, folly::Optional< uint8_t > padding, bool endStream, bool endHeaders) noexcept
size_t writeExHeaders (folly::IOBufQueue &writeBuf, std::unique_ptr< folly::IOBuf > headers, uint32_t stream, const HTTPCodec::ExAttributes &exAttributes, const folly::Optional< PriorityUpdate > &priority, const folly::Optional< uint8_t > &padding, bool endStream, bool endHeaders) noexcept
size_t writePriority (folly::IOBufQueue &writeBuf, uint32_t stream, PriorityUpdate priority) noexcept
size_t writeRstStream (folly::IOBufQueue &writeBuf, uint32_t stream, ErrorCode errorCode) noexcept
size_t writeSettings (folly::IOBufQueue &writeBuf, const std::deque< SettingPair > &settings)
size_t writeSettingsAck (folly::IOBufQueue &writeBuf)
size_t writePushPromise (folly::IOBufQueue &writeBuf, uint32_t associatedStream, uint32_t promisedStream, std::unique_ptr< folly::IOBuf > headers, folly::Optional< uint8_t > padding, bool endHeaders) noexcept
size_t writePing (folly::IOBufQueue &writeBuf, uint64_t data, bool ack) noexcept
size_t writeGoaway (folly::IOBufQueue &writeBuf, uint32_t lastStreamID, ErrorCode errorCode, std::unique_ptr< folly::IOBuf > debugData=nullptr) noexcept
size_t writeWindowUpdate (folly::IOBufQueue &writeBuf, uint32_t stream, uint32_t amount) noexcept
size_t writeContinuation (folly::IOBufQueue &queue, uint32_t stream, bool endHeaders, std::unique_ptr< folly::IOBuf > headers) noexcept
size_t writeAltSvc (folly::IOBufQueue &writeBuf, uint32_t stream, uint32_t maxAge, uint16_t port, folly::StringPiece protocol, folly::StringPiece host, folly::StringPiece origin) noexcept
Variables
const uint32_t kFrameHeaderSize = 9
const uint32_t kFrameHeadersBaseMaxSize = kFramePrioritySize + 1
const uint32_t kFramePrioritySize = 5
const uint32_t kFrameStreamIDSize = 4
const uint32_t kFrameRstStreamSize = 4
const uint32_t kFramePushPromiseSize = 4
const uint32_t kFramePingSize = 8
const uint32_t kFrameGoawaySize = 8
const uint32_t kFrameWindowUpdateSize = 4
const uint32_t kFrameCertificateRequestSizeBase = 2
const uint32_t kFrameCertificateSizeBase = 2
const uint32_t kFrameAltSvcSizeBase = 8
const uint32_t kMaxFramePayloadLengthMin = (1u << 14)
const uint32_t kMaxFramePayloadLength = (1u << 24) - 1
const uint32_t kMaxStreamID = (1u << 31) - 1
const uint32_t kInitialWindow = (1u << 16) - 1
const uint32_t kMaxWindowUpdateSize = (1u << 31) - 1
const uint32_t kMaxHeaderTableSize = (1u << 16)
const uint32_t kMaxAuthenticatorBufSize = 0x20000
const std::string kConnectionPreface
const std::string kProtocolString
const std::string kProtocolDraftString
const std::string kProtocolExperimentalString
const std::string kProtocolCleartextString
const std::string kProtocolSettingsHeader
const uint8_t kMinExperimentalFrameType = 0xf0
const Padding kNoPadding = folly::none
const PriorityUpdate DefaultPriority {0, false, 15}
Typedef Documentation
using proxygen::http2::Padding = typedef folly::Optional<uint8_t>
Definition at line 30 of file HTTP2Framer.h.
Enumeration Type Documentation
enum proxygen::http2::Flags
Enumerator
ACK
END_STREAM
END_HEADERS
PADDED
PRIORITY
PRIORITY
UNIDIRECTIONAL
UNSOLICITED
TO_BE_CONTINUED
Definition at line 59 of file HTTP2Framer.h.
           {
  ACK = 0x1,
  END_STREAM = 0x1,
  END_HEADERS = 0x4,
  PADDED = 0x8,
  PRIORITY = 0x20,
  // experimental flag for EX stream only
  UNIDIRECTIONAL = 0x40,
  // for secondary certificate authentication frames
  UNSOLICITED = 0x1,
  TO_BE_CONTINUED = 0x1,
};
enum proxygen::http2::FrameType : uint8_t [strong]
Enumerator
DATA
HEADERS
PRIORITY
RST_STREAM
SETTINGS
PUSH_PROMISE
PING
GOAWAY
WINDOW_UPDATE
CONTINUATION
ALTSVC
EX_HEADERS
CERTIFICATE_REQUEST
CERTIFICATE
CERTIFICATE_NEEDED
USE_CERTIFICATE
Definition at line 35 of file HTTP2Framer.h.
                     : uint8_t {
  DATA = 0,
  HEADERS = 1,
  PRIORITY = 2,
  RST_STREAM = 3,
  SETTINGS = 4,
  PUSH_PROMISE = 5,
  PING = 6,
  GOAWAY = 7,
  WINDOW_UPDATE = 8,
  CONTINUATION = 9,
  ALTSVC = 10, // not in current draft so frame type has not been assigned
  // experimental use
  EX_HEADERS = 0xfb,
  // For secondary certificate authentication in HTTP/2 as specified in the
  // draft-ietf-httpbis-http2-secondary-certs-02.
  CERTIFICATE_REQUEST = 0xf0,
  CERTIFICATE = 0xf1,
  CERTIFICATE_NEEDED = 0xf2,
  USE_CERTIFICATE = 0xf3,
};
Function Documentation
ErrorCode proxygen::http2::errorCodeToGoaway (ErrorCode code)
Definition at line 22 of file HTTP2Constants.cpp.
References filterInvalidStream().
Referenced by proxygen::HTTP2Codec::generateGoaway().
                                            {
  return filterInvalidStream(code);
}
ErrorCode proxygen::http2::errorCodeToReset (ErrorCode code)
Definition at line 26 of file HTTP2Constants.cpp.
References filterInvalidStream().
Referenced by proxygen::HTTP2Codec::generateRstStream().
                                           {
  return filterInvalidStream(code);
}
ErrorCode proxygen::http2::filterInvalidStream (ErrorCode code)
Definition at line 14 of file HTTP2Constants.cpp.
References proxygen::_SPDY_INVALID_STREAM, and proxygen::STREAM_CLOSED.
Referenced by errorCodeToGoaway(), and errorCodeToReset().
                                              {
  // _SPDY_INVALID_STREAM is SPDY specific, filter it out
  if (code == ErrorCode::_SPDY_INVALID_STREAM) {
    return ErrorCode::STREAM_CLOSED;
  }
  return code;
}
bool proxygen::http2::frameAffectsCompression (FrameType t)
Definition at line 245 of file HTTP2Framer.cpp.
References proxygen::spdy::HEADERS.
Referenced by proxygen::HTTP2Codec::parseFrame().
                                          {
  return t == FrameType::HEADERS ||
    t == FrameType::PUSH_PROMISE ||
    t == FrameType::CONTINUATION;
}
bool proxygen::http2::frameHasPadding (const FrameHeader & header)
This function returns true if the padding bit is set in the header
Parameters
header The frame header.
Returns
true if the padding bit is set, false otherwise.
Definition at line 251 of file HTTP2Framer.cpp.
References proxygen::http2::FrameHeader::flags, and PADDED.
Referenced by parseData(), parseDataBegin(), and proxygen::HTTP2Codec::parseDataFrameData().
                                                  {
    return header.flags & PADDED;
  }
const char * proxygen::http2::getFrameTypeString (FrameType type)
Get the string representation of the given FrameType
Parameters
type frame type
Returns
string representation of the frame type
Definition at line 964 of file HTTP2Framer.cpp.
References proxygen::spdy::GOAWAY, proxygen::spdy::HEADERS, proxygen::spdy::PING, PRIORITY, proxygen::spdy::RST_STREAM, proxygen::spdy::SETTINGS, and proxygen::spdy::WINDOW_UPDATE.
Referenced by proxygen::HTTP2Codec::onIngress(), and proxygen::HTTP2Codec::parseFrame().
                                               {
  switch (type) {
    case FrameType::DATA: return "DATA";
    case FrameType::HEADERS: return "HEADERS";
    case FrameType::PRIORITY: return "PRIORITY";
    case FrameType::RST_STREAM: return "RST_STREAM";
    case FrameType::SETTINGS: return "SETTINGS";
    case FrameType::PUSH_PROMISE: return "PUSH_PROMISE";
    case FrameType::PING: return "PING";
    case FrameType::GOAWAY: return "GOAWAY";
    case FrameType::WINDOW_UPDATE: return "WINDOW_UPDATE";
    case FrameType::CONTINUATION: return "CONTINUATION";
    case FrameType::ALTSVC: return "ALTSVC";
    case FrameType::CERTIFICATE_REQUEST: return "CERTIFICATE_REQUEST";
    case FrameType::CERTIFICATE: return "CERTIFICATE";
    default:
      // can happen when type was cast from uint8_t
      return "Unknown";
  }
  LOG(FATAL) << "Unreachable";
  return "";
}
bool proxygen::http2::isValidFrameType (FrameType type)
Definition at line 227 of file HTTP2Framer.cpp.
                                      {
  auto val = static_cast<uint8_t>(type);
  if (val < kMinExperimentalFrameType) {
    return val <= static_cast<uint8_t>(FrameType::ALTSVC);
  } else {
    switch (type) {
      case FrameType::EX_HEADERS:
        // Include the frame types added into FrameType enum for secondary
        // authentication.
      case FrameType::CERTIFICATE_REQUEST:
      case FrameType::CERTIFICATE:
        return true;
      default:
        return false;
    }
  }
}
const std::string proxygen::http2::kConnectionPreface (`PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n`)
const std::string proxygen::http2::kProtocolCleartextString (`h2c`)
const std::string proxygen::http2::kProtocolDraftString (`h2-14`)
const std::string proxygen::http2::kProtocolExperimentalString (`h2-fb`)
const std::string proxygen::http2::kProtocolSettingsHeader (`HTTP2-Settings`)
const std::string proxygen::http2::kProtocolString (`h2`)
ErrorCode proxygen::http2::parseAltSvc (folly::io::Cursor & cursor, const FrameHeader & header, uint32_t & outMaxAge, uint32_t & outPort, std::string & outProtocol, std::string & outHost, std::string & outOrigin) [noexcept]
This function parses the section of the ALTSVC frame after the common frame header. The caller must ensure there is header.length bytes available in the cursor.
Parameters
cursor The cursor to pull data from.
header The frame header for the frame being parsed.
outMaxAge The max age field.
outPort The port the alternative service is on.
outProtocol The alternative service protocol string.
outHost The alternative service host name.
outOrigin The origin the alternative service is applicable to.
Returns
NO_ERROR for successful parse. The connection error code to return in a GOAWAY frame if failure.
ErrorCode proxygen::http2::parseAltSvc (Cursor & cursor, const FrameHeader & header, uint32_t & outMaxAge, uint32_t & outPort, std::string & outProtocol, std::string & outHost, std::string & outOrigin) [noexcept]
Definition at line 534 of file HTTP2Framer.cpp.
References kFrameAltSvcSizeBase.
Referenced by TEST_F().
                                           {
  DCHECK_LE(header.length, cursor.totalLength());
  if (header.length < kFrameAltSvcSizeBase) {
    return ErrorCode::FRAME_SIZE_ERROR;
  }
  std::unique_ptr<IOBuf> tmpBuf;
  outMaxAge = cursor.readBE<uint32_t>();
  outPort = cursor.readBE<uint16_t>();
  const auto protoLen = cursor.readBE<uint8_t>();
  if (header.length < kFrameAltSvcSizeBase + protoLen) {
    return ErrorCode::FRAME_SIZE_ERROR;
  }
  outProtocol = cursor.readFixedString(protoLen);
  const auto hostLen = cursor.readBE<uint8_t>();
  if (header.length < kFrameAltSvcSizeBase + protoLen + hostLen) {
    return ErrorCode::FRAME_SIZE_ERROR;
  }
  outHost = cursor.readFixedString(hostLen);
  const auto originLen = (header.length - kFrameAltSvcSizeBase -
                          protoLen - hostLen);
  outOrigin = cursor.readFixedString(originLen);
  return ErrorCode::NO_ERROR;
}
ErrorCode proxygen::http2::parseCertificate (folly::io::Cursor & cursor, const FrameHeader & header, uint16_t & outCertId, std::unique_ptr< folly::IOBuf > & outAuthenticator) [noexcept]
This function parses the section of the CERTIFICATE frame after the common frame header. It pulls header.length bytes from the cursor, so it is the caller's responsibility to ensure there is enough data available.
Parameters
cursor The cursor to pull data from.
header The frame header for the frame being parsed.
outCertId The Cert-ID identifying the frame.
outAuthenticator Authenticator fragment in the frame, if any.
Returns
NO_ERROR for successful parse. The connection error code to return in a CERTIFICATE frame if failure.
Definition at line 587 of file HTTP2Framer.cpp.
References kFrameCertificateSizeBase.
Referenced by proxygen::HTTP2Codec::parseCertificate(), and TEST_F().
                                                          {
  DCHECK_LE(header.length, cursor.totalLength());
  if (header.length < kFrameCertificateSizeBase) {
    return ErrorCode::FRAME_SIZE_ERROR;
  }
  if (header.stream != 0) {
    return ErrorCode::PROTOCOL_ERROR;
  }
  outCertId = cursor.readBE<uint16_t>();
  auto length = header.length;
  length -= kFrameCertificateSizeBase;
  if (length > 0) {
    cursor.clone(outAuthenticator, length);
  }
  return ErrorCode::NO_ERROR;
}
ErrorCode proxygen::http2::parseCertificateRequest (folly::io::Cursor & cursor, const FrameHeader & header, uint16_t & outRequestId, std::unique_ptr< folly::IOBuf > & outAuthRequest) [noexcept]
This function parses the section of the CERTIFICATE_REQUEST frame after the common frame header. It pulls header.length bytes from the cursor, so it is the caller's responsibility to ensure there is enough data available.
Parameters
cursor The cursor to pull data from.
header The frame header for the frame being parsed.
outRequestId The Request-ID identifying this certificate request.
outAuthRequest Authenticator request in the frame, if any.
Returns
NO_ERROR for successful parse. The connection error code to return in a CERTIFICATE_REQUEST frame if failure.
Definition at line 566 of file HTTP2Framer.cpp.
References kFrameCertificateRequestSizeBase.
Referenced by proxygen::HTTP2Codec::parseCertificateRequest(), and TEST_F().
                                                        {
  DCHECK_LE(header.length, cursor.totalLength());
  if (header.length < kFrameCertificateRequestSizeBase) {
    return ErrorCode::FRAME_SIZE_ERROR;
  }
  if (header.stream != 0) {
    return ErrorCode::PROTOCOL_ERROR;
  }
  outRequestId = cursor.readBE<uint16_t>();
  auto length = header.length;
  length -= kFrameCertificateRequestSizeBase;
  if (length > 0) {
    cursor.clone(outAuthRequest, length);
  }
  return ErrorCode::NO_ERROR;
}
ErrorCode proxygen::http2::parseContinuation (folly::io::Cursor & cursor, const FrameHeader & header, std::unique_ptr< folly::IOBuf > & outBuf) [noexcept]
This function parses the section of the CONTINUATION frame after the common frame header. The caller must ensure there is header.length bytes available in the cursor.
Parameters
cursor The cursor to pull data from.
header The frame header for the frame being parsed.
outBuf The buffer to fill with header data.
outAmount The amount to increment the stream's window by.
Returns
NO_ERROR for successful parse. The connection error code to return in a GOAWAY frame if failure.
ErrorCode proxygen::http2::parseContinuation (Cursor & cursor, const FrameHeader & header, std::unique_ptr< IOBuf > & outBuf) [noexcept]
Definition at line 521 of file HTTP2Framer.cpp.
Referenced by proxygen::HTTP2Codec::parseContinuation(), and TEST_F().
                                                         {
  DCHECK(header.type == FrameType::CONTINUATION);
  DCHECK_LE(header.length, cursor.totalLength());
  if (header.stream == 0) {
    return ErrorCode::PROTOCOL_ERROR;
  }
  cursor.clone(outBuf, header.length);
  return ErrorCode::NO_ERROR;
}
ErrorCode proxygen::http2::parseData (folly::io::Cursor & cursor, const FrameHeader & header, std::unique_ptr< folly::IOBuf > & outBuf, uint16_t & padding) [noexcept]
This function parses the section of the DATA frame after the common frame header. It discards any padding and returns the body data in outBuf. It pulls header.length bytes from the cursor, so it is the caller's responsibility to ensure there is enough data available.
Parameters
cursor The cursor to pull data from.
header The frame header for the frame being parsed.
outBuf The buf to fill with body data.
padding The number of padding bytes in this data frame
Returns
NO_ERROR for successful parse. The connection error code to return in a GOAWAY frame if failure.
ErrorCode proxygen::http2::parseData (Cursor & cursor, const FrameHeader & header, std::unique_ptr< IOBuf > & outBuf, uint16_t & outPadding) [noexcept]
Definition at line 271 of file HTTP2Framer.cpp.
References frameHasPadding(), and RETURN_IF_ERROR.
Referenced by HTTP2FramerTest::dataFrameTest(), proxygen::HTTP2Codec::parseAllData(), and TEST_F().
                                                     {
    DCHECK_LE(header.length, cursor.totalLength());
    if (header.stream == 0) {
      return ErrorCode::PROTOCOL_ERROR;
    }
    uint8_t padding;
    uint32_t lefttoparse;
    const auto err = parsePadding(cursor, header, padding, lefttoparse);
    RETURN_IF_ERROR(err);
    // outPadding is the total number of flow-controlled pad bytes, which
    // includes the length byte, if present.
    outPadding = padding + ((frameHasPadding(header)) ? 1 : 0);
    cursor.clone(outBuf, lefttoparse);
    return skipPadding(cursor, padding, kStrictPadding);
  }
ErrorCode proxygen::http2::parseDataBegin (folly::io::Cursor & cursor, const FrameHeader & header, size_t & parsed, uint16_t & outPadding) [noexcept]
ErrorCode proxygen::http2::parseDataBegin (Cursor & cursor, const FrameHeader & header, size_t & , uint16_t & outPadding) [noexcept]
Definition at line 291 of file HTTP2Framer.cpp.
References frameHasPadding(), and RETURN_IF_ERROR.
Referenced by proxygen::HTTP2Codec::parseDataFrameData().
                                                          {
    uint8_t padding;
    uint32_t lefttoparse;
    const auto err = http2::parsePadding(cursor, header, padding, lefttoparse);
    RETURN_IF_ERROR(err);
    // outPadding is the total number of flow-controlled pad bytes, which
    // includes the length byte, if present.
    outPadding = padding + ((frameHasPadding(header)) ? 1 : 0);
    return ErrorCode::NO_ERROR;
  }
ErrorCode proxygen::http2::parseDataEnd (folly::io::Cursor & cursor, const size_t bufLen, const size_t pendingDataFramePaddingBytes, size_t & toSkip) [noexcept]
ErrorCode proxygen::http2::parseDataEnd (Cursor & cursor, const size_t bufLen, const size_t pendingDataFramePaddingBytes, size_t & toSkip) [noexcept]
Definition at line 305 of file HTTP2Framer.cpp.
Referenced by proxygen::HTTP2Codec::parseDataFrameData().
                                                  {
    toSkip = std::min(pendingDataFramePaddingBytes, bufLen);
    return skipPadding(cursor, toSkip, kStrictPadding);
}
ErrorCode proxygen::http2::parseExHeaders (folly::io::Cursor & cursor, const FrameHeader & header, HTTPCodec::ExAttributes & outExAttributes, folly::Optional< PriorityUpdate > & outPriority, std::unique_ptr< folly::IOBuf > & outBuf) [noexcept]
ErrorCode proxygen::http2::parseExHeaders (Cursor & cursor, const FrameHeader & header, HTTPCodec::ExAttributes & outExAttributes, folly::Optional< PriorityUpdate > & outPriority, std::unique_ptr< IOBuf > & outBuf) [noexcept]
Definition at line 340 of file HTTP2Framer.cpp.
References kFramePrioritySize, kFrameStreamIDSize, PRIORITY, RETURN_IF_ERROR, and UNIDIRECTIONAL.
Referenced by proxygen::HTTP2Codec::parseExHeaders(), and TEST_F().
                                                      {
  DCHECK_LE(header.length, cursor.totalLength());
  if (header.stream == 0) {
    return ErrorCode::PROTOCOL_ERROR;
  }
  uint8_t padding;
  uint32_t lefttoparse;
  auto err = parsePadding(cursor, header, padding, lefttoparse);
  RETURN_IF_ERROR(err);
  // the regular HEADERS frame starts from here
  if (header.flags & PRIORITY) {
    if (lefttoparse < kFramePrioritySize) {
      return ErrorCode::FRAME_SIZE_ERROR;
    }
    outPriority = parsePriorityCommon(cursor);
    lefttoparse -= kFramePrioritySize;
  } else {
    outPriority = folly::none;
  }
  outExAttributes.unidirectional = header.flags & UNIDIRECTIONAL;
  if (lefttoparse < kFrameStreamIDSize) {
    return ErrorCode::FRAME_SIZE_ERROR;
  }
  outExAttributes.controlStream = parseUint31(cursor);
  lefttoparse -= kFrameStreamIDSize;
  if (!(outExAttributes.controlStream & 0x1)) {
    // control stream ID should be odd because it is initiated by client
    return ErrorCode::PROTOCOL_ERROR;
  }
  cursor.clone(outBuf, lefttoparse);
  return skipPadding(cursor, padding, kStrictPadding);
}
ErrorCode proxygen::http2::parseFrameHeader (folly::io::Cursor & cursor, FrameHeader & header) [noexcept]
This function parses the common HTTP/2 frame header. This function pulls kFrameHeaderSize bytes from the cursor, so the caller must check that that amount is available.
Parameters
cursor The cursor to pull data from.
header The frame header struct to populate.
Returns
Nothing if success. The connection error code if failure.
ErrorCode proxygen::http2::parseFrameHeader (Cursor & cursor, FrameHeader & header) [noexcept]
Definition at line 257 of file HTTP2Framer.cpp.
References kFrameHeaderSize.
Referenced by proxygen::HTTP2Codec::onIngress(), HTTP2FramerTest::parse(), and TEST_F().
                                                                             {
    FOLLY_SCOPED_TRACE_SECTION("HTTP2Framer - parseFrameHeader");
    DCHECK_LE(kFrameHeaderSize, cursor.totalLength());
    // MUST ignore the 2 bits before the length
    uint32_t lengthAndType = cursor.readBE<uint32_t>();
    header.length = kLengthMask & (lengthAndType >> 8);
    uint8_t type = lengthAndType & 0xff;
    header.type = FrameType(type);
    header.flags = cursor.readBE<uint8_t>();
    header.stream = parseUint31(cursor);
    return ErrorCode::NO_ERROR;
  }
ErrorCode proxygen::http2::parseGoaway (folly::io::Cursor & cursor, const FrameHeader & header, uint32_t & outLastStreamID, ErrorCode & outCode, std::unique_ptr< folly::IOBuf > & outDebugData) [noexcept]
This function parses the section of the GOAWAY frame after the common frame header. It pulls header.length bytes from the cursor, so it is the caller's responsibility to ensure there is enough data available.
Parameters
cursor The cursor to pull data from.
header The frame header for the frame being parsed.
outLastStreamID The last stream id accepted by the remote.
outCode The error code received in the frame.
outDebugData Additional debug-data in the frame, if any
Returns
NO_ERROR for successful parse. The connection error code to return in a GOAWAY frame if failure.
ErrorCode proxygen::http2::parseGoaway (Cursor & cursor, const FrameHeader & header, uint32_t & outLastStreamID, ErrorCode & outCode, std::unique_ptr< IOBuf > & outDebugData) [noexcept]
Definition at line 485 of file HTTP2Framer.cpp.
References kFrameGoawaySize, and RETURN_IF_ERROR.
Referenced by proxygen::HTTP2Codec::parseGoaway(), and TEST_F().
                                                         {
  DCHECK_LE(header.length, cursor.totalLength());
  if (header.length < kFrameGoawaySize) {
    return ErrorCode::FRAME_SIZE_ERROR;
  }
  if (header.stream != 0) {
    return ErrorCode::PROTOCOL_ERROR;
  }
  outLastStreamID = parseUint31(cursor);
  auto err = parseErrorCode(cursor, outCode);
  RETURN_IF_ERROR(err);
  auto length = header.length;
  length -= kFrameGoawaySize;
  if (length > 0) {
    cursor.clone(outDebugData, length);
  }
  return ErrorCode::NO_ERROR;
}
ErrorCode proxygen::http2::parseHeaders (folly::io::Cursor & cursor, const FrameHeader & header, folly::Optional< PriorityUpdate > & outPriority, std::unique_ptr< folly::IOBuf > & outBuf) [noexcept]
This function parses the section of the HEADERS frame after the common frame header. It discards any padding and returns the header data in outBuf. It pulls header.length bytes from the cursor, so it is the caller's responsibility to ensure there is enough data available.
Parameters
cursor The cursor to pull data from.
header The frame header for the frame being parsed.
outPriority If PRIORITY flag is set, this will be filled with the priority information from this frame.
outBuf The buf to fill with header data.
Returns
NO_ERROR for successful parse. The connection error code to return in a GOAWAY frame if failure.
ErrorCode proxygen::http2::parseHeaders (Cursor & cursor, const FrameHeader & header, folly::Optional< PriorityUpdate > & outPriority, std::unique_ptr< IOBuf > & outBuf) [noexcept]
Definition at line 314 of file HTTP2Framer.cpp.
References kFramePrioritySize, PRIORITY, and RETURN_IF_ERROR.
Referenced by proxygen::HTTP2Codec::parseHeaders(), and TEST_F().
                                                    {
  DCHECK_LE(header.length, cursor.totalLength());
  if (header.stream == 0) {
    return ErrorCode::PROTOCOL_ERROR;
  }
  uint8_t padding;
  uint32_t lefttoparse;
  auto err = parsePadding(cursor, header, padding, lefttoparse);
  RETURN_IF_ERROR(err);
  if (header.flags & PRIORITY) {
    if (lefttoparse < kFramePrioritySize) {
      return ErrorCode::FRAME_SIZE_ERROR;
    }
    outPriority = parsePriorityCommon(cursor);
    lefttoparse -= kFramePrioritySize;
  } else {
    outPriority = folly::none;
  }
  cursor.clone(outBuf, lefttoparse);
  return skipPadding(cursor, padding, kStrictPadding);
}
ErrorCode proxygen::http2::parsePing (folly::io::Cursor & cursor, const FrameHeader & header, uint64_t & outData) [noexcept]
This function parses the section of the PING frame after the common frame header. It pulls header.length bytes from the cursor, so it is the caller's responsibility to ensure there is enough data available.
Parameters
cursor The cursor to pull data from.
header The frame header for the frame being parsed.
outData The opaque data from the ping frame
Returns
NO_ERROR for successful parse. The connection error code to return in a GOAWAY frame if failure.
ErrorCode proxygen::http2::parsePing (Cursor & cursor, const FrameHeader & header, uint64_t & outOpaqueData) [noexcept]
Definition at line 468 of file HTTP2Framer.cpp.
References kFramePingSize.
Referenced by proxygen::HTTP2Codec::parsePing(), and TEST_F().
                                            {
  DCHECK_LE(header.length, cursor.totalLength());
  if (header.length != kFramePingSize) {
    return ErrorCode::FRAME_SIZE_ERROR;
  }
  if (header.stream != 0) {
    return ErrorCode::PROTOCOL_ERROR;
  }
  cursor.pull(&outOpaqueData, sizeof(outOpaqueData));
  return ErrorCode::NO_ERROR;
}
ErrorCode proxygen::http2::parsePriority (folly::io::Cursor & cursor, const FrameHeader & header, PriorityUpdate & outPriority) [noexcept]
This function parses the section of the PRIORITY frame after the common frame header. It pulls header.length bytes from the cursor, so it is the caller's responsibility to ensure there is enough data available.
Parameters
cursor The cursor to pull data from.
header The frame header for the frame being parsed.
outPriority On success, filled with the priority information from this frame.
Returns
NO_ERROR for successful parse. The connection error code to return in a GOAWAY frame if failure.
ErrorCode proxygen::http2::parsePriority (Cursor & cursor, const FrameHeader & header, PriorityUpdate & outPriority) [noexcept]
Definition at line 382 of file HTTP2Framer.cpp.
References kFramePrioritySize.
Referenced by proxygen::HTTP2Codec::parsePriority(), and TEST_F().
                                                    {
  DCHECK_LE(header.length, cursor.totalLength());
  if (header.length != kFramePrioritySize) {
    return ErrorCode::FRAME_SIZE_ERROR;
  }
  if (header.stream == 0) {
    return ErrorCode::PROTOCOL_ERROR;
  }
  outPriority = parsePriorityCommon(cursor);
  return ErrorCode::NO_ERROR;
}
ErrorCode proxygen::http2::parsePushPromise (folly::io::Cursor & cursor, const FrameHeader & header, uint32_t & outPromisedStream, std::unique_ptr< folly::IOBuf > & outBuf) [noexcept]
This function parses the section of the PUSH_PROMISE frame after the common frame header. It pulls header.length bytes from the cursor, so it is the caller's responsibility to ensure there is enough data available.
Parameters
cursor The cursor to pull data from.
header The frame header for the frame being parsed.
outPromisedStream The id of the stream promised by the remote.
outBuf The buffer to fill with header data.
Returns
NO_ERROR for successful parse. The connection error code to return in a GOAWAY frame if failure.
ErrorCode proxygen::http2::parsePushPromise (Cursor & cursor, const FrameHeader & header, uint32_t & outPromisedStream, std::unique_ptr< IOBuf > & outBuf) [noexcept]
Definition at line 437 of file HTTP2Framer.cpp.
References kFramePushPromiseSize, and RETURN_IF_ERROR.
Referenced by proxygen::HTTP2Codec::parsePushPromise(), and TEST_F().
                                                        {
  DCHECK_LE(header.length, cursor.totalLength());
  if (header.stream == 0) {
    return ErrorCode::PROTOCOL_ERROR;
  }
  uint8_t padding;
  uint32_t lefttoparse;
  auto err = parsePadding(cursor, header, padding, lefttoparse);
  RETURN_IF_ERROR(err);
  if (lefttoparse < kFramePushPromiseSize) {
    return ErrorCode::FRAME_SIZE_ERROR;
  }
  lefttoparse -= kFramePushPromiseSize;
  outPromisedStream = parseUint31(cursor);
  if (outPromisedStream == 0 ||
      outPromisedStream & 0x1) {
    // client MUST reserve an even stream id greater than 0
    return ErrorCode::PROTOCOL_ERROR;
  }
  if (lefttoparse < padding) {
    return ErrorCode::PROTOCOL_ERROR;
  }
  cursor.clone(outBuf, lefttoparse);
  return skipPadding(cursor, padding, kStrictPadding);
}
ErrorCode proxygen::http2::parseRstStream (folly::io::Cursor & cursor, const FrameHeader & header, ErrorCode & outCode) [noexcept]
This function parses the section of the RST_STREAM frame after the common frame header. It pulls header.length bytes from the cursor, so it is the caller's responsibility to ensure there is enough data available.
Parameters
cursor The cursor to pull data from.
header The frame header for the frame being parsed.
outCode The error code received in the frame.
Returns
NO_ERROR for successful parse. The connection error code to return in a GOAWAY frame if failure.
ErrorCode proxygen::http2::parseRstStream (Cursor & cursor, const FrameHeader & header, ErrorCode & outCode) [noexcept]
Definition at line 397 of file HTTP2Framer.cpp.
References kFrameRstStreamSize.
Referenced by proxygen::HTTP2Codec::parseRstStream(), and TEST_F().
                                            {
  DCHECK_LE(header.length, cursor.totalLength());
  if (header.length != kFrameRstStreamSize) {
    return ErrorCode::FRAME_SIZE_ERROR;
  }
  if (header.stream == 0) {
    return ErrorCode::PROTOCOL_ERROR;
  }
  return parseErrorCode(cursor, outCode);
}
ErrorCode proxygen::http2::parseSettings (folly::io::Cursor & cursor, const FrameHeader & header, std::deque< SettingPair > & settings) [noexcept]
This function parses the section of the SETTINGS frame after the common frame header. It pulls header.length bytes from the cursor, so it is the caller's responsibility to ensure there is enough data available.
Parameters
cursor The cursor to pull data from.
header The frame header for the frame being parsed.
settings The settings received in this frame.
Returns
NO_ERROR for successful parse. The connection error code to return in a GOAWAY frame if failure.
ErrorCode proxygen::http2::parseSettings (Cursor & cursor, const FrameHeader & header, std::deque< SettingPair > & settings) [noexcept]
Definition at line 411 of file HTTP2Framer.cpp.
References ACK, and settings.
Referenced by proxygen::HTTP2Codec::onIngressUpgradeMessage(), proxygen::HTTP2Codec::parseSettings(), and TEST_F().
                                                        {
  DCHECK_LE(header.length, cursor.totalLength());
  if (header.stream != 0) {
    return ErrorCode::PROTOCOL_ERROR;
  }
  if (header.flags & ACK) {
    if (header.length != 0) {
      return ErrorCode::FRAME_SIZE_ERROR;
    }
    return ErrorCode::NO_ERROR;
  }
  if (header.length % 6 != 0) {
    return ErrorCode::FRAME_SIZE_ERROR;
  }
  for (auto length = header.length; length > 0; length -= 6) {
    uint16_t id = cursor.readBE<uint16_t>();
    uint32_t val = cursor.readBE<uint32_t>();
    settings.push_back(std::make_pair(SettingsId(id), val));
  }
  return ErrorCode::NO_ERROR;
}
ErrorCode proxygen::http2::parseWindowUpdate (folly::io::Cursor & cursor, const FrameHeader & header, uint32_t & outAmount) [noexcept]
This function parses the section of the WINDOW_UPDATE frame after the common frame header. The caller must ensure there is header.length bytes available in the cursor.
Parameters
cursor The cursor to pull data from.
header The frame header for the frame being parsed.
outAmount The amount to increment the stream's window by.
Returns
NO_ERROR for successful parse. The connection error code to return in a GOAWAY frame if failure.
ErrorCode proxygen::http2::parseWindowUpdate (Cursor & cursor, const FrameHeader & header, uint32_t & outAmount) [noexcept]
Definition at line 509 of file HTTP2Framer.cpp.
References kFrameWindowUpdateSize.
Referenced by proxygen::HTTP2Codec::parseWindowUpdate(), and TEST_F().
                                                {
  DCHECK_LE(header.length, cursor.totalLength());
  if (header.length != kFrameWindowUpdateSize) {
    return ErrorCode::FRAME_SIZE_ERROR;
  }
  outAmount = parseUint31(cursor);
  return ErrorCode::NO_ERROR;
}
size_t proxygen::http2::writeAltSvc (folly::IOBufQueue & writeBuf, uint32_t stream, uint32_t maxAge, uint16_t port, folly::StringPiece protocol, folly::StringPiece host, folly::StringPiece origin) [noexcept]
Generate an entire ALTSVC frame, including the common frame header.
Parameters
writeBuf The output queue to write to. It may grow or add underlying buffers inside this function.
stream The stream to do Alt-Svc on. May be zero.
maxAge The max age field.
port The port the alternative service is on.
protocol The alternative service protocol string.
host The alternative service host name.
origin The origin the alternative service is applicable to.
Returns
The number of bytes written to writeBuf.
size_t proxygen::http2::writeAltSvc (IOBufQueue & queue, uint32_t stream, uint32_t maxAge, uint16_t port, StringPiece protocol, StringPiece host, StringPiece origin) [noexcept]
Definition at line 891 of file HTTP2Framer.cpp.
References kFrameAltSvcSizeBase, and kFrameHeaderSize.
Referenced by TEST_F().
                                         {
  const auto protoLen = protocol.size();
  const auto hostLen = host.size();
  const auto originLen = origin.size();
  const auto frameLen = protoLen + hostLen + originLen + kFrameAltSvcSizeBase;
  writeFrameHeader(queue, frameLen, FrameType::ALTSVC, 0, stream, kNoPadding,
                   folly::none, nullptr);
  QueueAppender appender(&queue, frameLen);
  appender.writeBE<uint32_t>(maxAge);
  appender.writeBE<uint16_t>(port);
  appender.writeBE<uint8_t>(protoLen);
  appender.push(reinterpret_cast<const uint8_t*>(protocol.data()), protoLen);
  appender.writeBE<uint8_t>(hostLen);
  appender.push(reinterpret_cast<const uint8_t*>(host.data()), hostLen);
  appender.push(reinterpret_cast<const uint8_t*>(origin.data()), originLen);
  return kFrameHeaderSize + frameLen;
}
size_t proxygen::http2::writeCertificate (folly::IOBufQueue & writeBuf, uint16_t certId, std::unique_ptr< folly::IOBuf > authenticator, bool toBeContinued)
Generate an entire CERTIFICATE frame, including the common frame header.
Parameters
writeBuf The output queue to write to. It may grow or add underlying buffers inside this function.
certId The opaque Cert-ID of this frame which is used to correlate subsequent certificate-related frames with this certificate.
authenticator The encoded authenticator fragment.
toBeContinued Indicates whether there is additional authenticator fragment.
Returns
The number of bytes written to writeBuf.
Definition at line 937 of file HTTP2Framer.cpp.
References kFrameCertificateSizeBase, kFrameHeaderSize, and TO_BE_CONTINUED.
Referenced by proxygen::HTTP2Codec::generateCertificate(), and TEST_F().
                                            {
  uint8_t flags = 0;
  if (toBeContinued) {
    flags |= TO_BE_CONTINUED;
  }
  const auto dataLen =
      authenticator
          ? kFrameCertificateSizeBase + authenticator->computeChainDataLength()
          : kFrameCertificateSizeBase;
  // The CERTIFICATE_REQUEST frame must be sent on stream 0.
  const auto frameLen = writeFrameHeader(writeBuf,
                                         dataLen,
                                         FrameType::CERTIFICATE,
                                         flags,
                                         0,
                                         kNoPadding,
                                         folly::none,
                                         nullptr);
  QueueAppender appender(&writeBuf, frameLen);
  appender.writeBE<uint16_t>(certId);
  writeBuf.append(std::move(authenticator));
  return kFrameHeaderSize + frameLen;
}
size_t proxygen::http2::writeCertificateRequest (folly::IOBufQueue & writeBuf, uint16_t requestId, std::unique_ptr< folly::IOBuf > authRequest)
Generate an entire CERTIFICATE_REQUEST frame, including the common frame header.
Parameters
writeBuf The output queue to write to. It may grow or add underlying buffers inside this function.
requestId The opaque Request-ID of this used to correlate subsequent certificate-related frames with this request.
authRequest The encoded authenticator request.
Returns
The number of bytes written to writeBuf.
Definition at line 916 of file HTTP2Framer.cpp.
References kFrameCertificateRequestSizeBase, and kFrameHeaderSize.
Referenced by proxygen::HTTP2Codec::generateCertificateRequest(), and TEST_F().
                                                                      {
  const auto dataLen = authRequest ? kFrameCertificateRequestSizeBase +
                                         authRequest->computeChainDataLength()
                                   : kFrameCertificateRequestSizeBase;
  // The CERTIFICATE_REQUEST frame must be sent on stream 0.
  const auto frameLen = writeFrameHeader(writeBuf,
                                         dataLen,
                                         FrameType::CERTIFICATE_REQUEST,
                                         0,
                                         0,
                                         kNoPadding,
                                         folly::none,
                                         nullptr);
  QueueAppender appender(&writeBuf, frameLen);
  appender.writeBE<uint16_t>(requestId);
  writeBuf.append(std::move(authRequest));
  return kFrameHeaderSize + frameLen;
}
size_t proxygen::http2::writeContinuation (folly::IOBufQueue & queue, uint32_t stream, bool endHeaders, std::unique_ptr< folly::IOBuf > headers) [noexcept]
Generate an entire CONTINUATION frame, including the common frame header. The combined length of the data buffer and the padding MUST NOT exceed 2^14 - 3, which is kMaxFramePayloadLength minus the two bytes to encode the length of the padding.
Parameters
writeBuf The output queue to write to. It may grow or add underlying buffers inside this function.
stream The stream identifier of the DATA frame.
endHeaders True iff more CONTINUATION frames will follow.
headers The encoded headers data to write out.
Returns
The number of bytes written to writeBuf.
size_t proxygen::http2::writeContinuation (IOBufQueue & queue, uint32_t stream, bool endHeaders, std::unique_ptr< IOBuf > headers) [noexcept]
Definition at line 873 of file HTTP2Framer.cpp.
References END_HEADERS, and kFrameHeaderSize.
Referenced by proxygen::HTTP2Codec::generateContinuation(), and TEST_F().
                                                         {
  DCHECK_NE(0, stream);
  const auto dataLen = headers->computeChainDataLength();
  const auto frameLen = writeFrameHeader(queue,
                                         dataLen,
                                         FrameType::CONTINUATION,
                                         endHeaders ? END_HEADERS : 0,
                                         stream,
                                         kNoPadding,
                                         folly::none,
                                         std::move(headers));
  return kFrameHeaderSize + frameLen;
}
size_t proxygen::http2::writeData (folly::IOBufQueue & writeBuf, std::unique_ptr< folly::IOBuf > data, uint32_t stream, folly::Optional< uint8_t > padding, bool endStream, bool reuseIOBufHeadroom) [noexcept]
Generate an entire DATA frame, including the common frame header. The combined length of the data buffer, the padding, and the padding length MUST NOT exceed 2^14 - 1, which is kMaxFramePayloadLength.
Parameters
writeBuf The output queue to write to. It may grow or add underlying buffers inside this function.
data The body data to write out, can be nullptr for 0 length
stream The stream identifier of the DATA frame.
padding If not kNoPadding, adds 1 byte pad len and pad bytes
endStream True iff this frame ends the stream.
reuseIOBufHeadroom If HTTP2Framer should reuse headroom in data if headroom is enough for frame header
Returns
The number of bytes written to writeBuf.
size_t proxygen::http2::writeData (IOBufQueue & queue, std::unique_ptr< IOBuf > data, uint32_t stream, folly::Optional< uint8_t > padding, bool endStream, bool reuseIOBufHeadroom) [noexcept]
Definition at line 611 of file HTTP2Framer.cpp.
References END_STREAM, and kFrameHeaderSize.
Referenced by HTTP2FramerTest::dataFrameTest(), proxygen::HTTP2Codec::generateBody(), proxygen::HTTP2Codec::generateEOM(), and TEST_F().
                                            {
  DCHECK_NE(0, stream);
  uint8_t flags = 0;
  if (endStream) {
    flags |= END_STREAM;
  }
  const uint64_t dataLen = data ? data->computeChainDataLength() : 0;
  // Caller must not exceed peer setting for MAX_FRAME_SIZE
  // TODO: look into using headroom from data to hold the frame header
  const auto frameLen = writeFrameHeader(queue,
                                         dataLen,
                                         FrameType::DATA,
                                         flags,
                                         stream,
                                         padding,
                                         folly::none,
                                         std::move(data),
                                         reuseIOBufHeadroom);
  writePadding(queue, padding);
  return kFrameHeaderSize + frameLen;
}
size_t proxygen::http2::writeExHeaders (folly::IOBufQueue & writeBuf, std::unique_ptr< folly::IOBuf > headers, uint32_t stream, const HTTPCodec::ExAttributes & exAttributes, const folly::Optional< PriorityUpdate > & priority, const folly::Optional< uint8_t > & padding, bool endStream, bool endHeaders) [noexcept]
Generate an experimental ExHEADERS frame, including the common frame header. The combined length of the data buffer and the padding and priority fields MUST NOT exceed 2^14 - 1, which is kMaxFramePayloadLength.
Parameters
writeBuf The output queue to write to. It may grow or add underlying buffers inside this function.
headers The encoded headers data to write out.
stream The stream identifier of the ExHEADERS frame.
exAttributes Attributes specific to ExHEADERS frame.
priority If present, the priority depedency information to update the stream with.
padding If not kNoPadding, adds 1 byte pad len and pad bytes
endStream True iff this frame ends the stream.
endHeaders True iff no CONTINUATION frames will follow this frame.
Returns
The number of bytes written to writeBuf.
size_t proxygen::http2::writeExHeaders (IOBufQueue & queue, std::unique_ptr< IOBuf > headers, uint32_t stream, const HTTPCodec::ExAttributes & exAttributes, const folly::Optional< PriorityUpdate > & priority, const folly::Optional< uint8_t > & padding, bool endStream, bool endHeaders) [noexcept]
Definition at line 672 of file HTTP2Framer.cpp.
References END_HEADERS, END_STREAM, kFrameHeaderSize, kFrameStreamIDSize, PRIORITY, and UNIDIRECTIONAL.
Referenced by proxygen::HTTP2Codec::generateHeaderImpl(), and TEST_F().
                                         {
  DCHECK_NE(0, stream);
  DCHECK_NE(0, exAttributes.controlStream);
  DCHECK_EQ(0, ~kUint31Mask & stream);
  DCHECK_EQ(0, ~kUint31Mask & exAttributes.controlStream);
  DCHECK(0x1 & exAttributes.controlStream) <<
    "controlStream should be initiated by client";
  const auto dataLen = (headers) ? headers->computeChainDataLength() : 0;
  uint32_t flags = 0;
  if (priority) {
    flags |= PRIORITY;
  }
  if (endStream) {
    flags |= END_STREAM;
  }
  if (endHeaders) {
    flags |= END_HEADERS;
  }
  if (exAttributes.unidirectional) {
    flags |= UNIDIRECTIONAL;
  }
  const auto frameLen = writeFrameHeader(queue,
                                         dataLen + kFrameStreamIDSize,
                                         FrameType::EX_HEADERS,
                                         flags,
                                         stream,
                                         padding,
                                         priority,
                                         nullptr);
  QueueAppender appender(&queue, frameLen);
  appender.writeBE<uint32_t>(exAttributes.controlStream);
  queue.append(std::move(headers));
  writePadding(queue, padding);
  return kFrameHeaderSize + frameLen;
}
size_t proxygen::http2::writeGoaway (folly::IOBufQueue & writeBuf, uint32_t lastStreamID, ErrorCode errorCode, std::unique_ptr< folly::IOBuf > debugData = nullptr) [noexcept]
Generate an entire GOAWAY frame, including the common frame header. We do not implement the optional opaque data.
Parameters
writeBuf The output queue to write to. It may grow or add underlying buffers inside this function.
lastStreamID The identifier of the last stream accepted.
errorCode The error code returned in the frame.
debugData Optional debug information to add to the frame
Returns
The number of bytes written to writeBuf.
size_t proxygen::http2::writeGoaway (IOBufQueue & queue, uint32_t lastStreamID, ErrorCode errorCode, std::unique_ptr< IOBuf > debugData) [noexcept]
Definition at line 832 of file HTTP2Framer.cpp.
References proxygen::spdy::GOAWAY, kFrameGoawaySize, and kFrameHeaderSize.
Referenced by proxygen::HTTP2Codec::generateGoaway(), and TEST_F().
                                                     {
  uint32_t debugLen = debugData ? debugData->computeChainDataLength() : 0;
  DCHECK_EQ(0, ~kLengthMask & debugLen);
  const auto frameLen = writeFrameHeader(queue,
                                         kFrameGoawaySize + debugLen,
                                         FrameType::GOAWAY,
                                         0,
                                         0,
                                         kNoPadding,
                                         folly::none,
                                         nullptr);
  QueueAppender appender(&queue, frameLen);
  appender.writeBE<uint32_t>(lastStreamID);
  appender.writeBE<uint32_t>(static_cast<uint32_t>(errorCode));
  queue.append(std::move(debugData));
  return kFrameHeaderSize + frameLen;
}
size_t proxygen::http2::writeHeaders (folly::IOBufQueue & writeBuf, std::unique_ptr< folly::IOBuf > headers, uint32_t stream, folly::Optional< PriorityUpdate > priority, folly::Optional< uint8_t > padding, bool endStream, bool endHeaders) [noexcept]
Generate an entire HEADERS frame, including the common frame header. The combined length of the data buffer and the padding and priority fields MUST NOT exceed 2^14 - 1, which is kMaxFramePayloadLength.
Parameters
writeBuf The output queue to write to. It may grow or add underlying buffers inside this function.
headers The encoded headers data to write out.
stream The stream identifier of the HEADERS frame.
priority If present, the priority depedency information to update the stream with.
padding If not kNoPadding, adds 1 byte pad len and pad bytes
endStream True iff this frame ends the stream.
endHeaders True iff no CONTINUATION frames will follow this frame.
Returns
The number of bytes written to writeBuf.
size_t proxygen::http2::writeHeaders (IOBufQueue & queue, std::unique_ptr< IOBuf > headers, uint32_t stream, folly::Optional< PriorityUpdate > priority, folly::Optional< uint8_t > padding, bool endStream, bool endHeaders) [noexcept]
Definition at line 639 of file HTTP2Framer.cpp.
References END_HEADERS, END_STREAM, proxygen::spdy::HEADERS, kFrameHeaderSize, and PRIORITY.
Referenced by proxygen::HTTP2Codec::generateHeaderImpl(), proxygen::HTTP2Codec::generateTrailers(), and TEST_F().
                                       {
  DCHECK_NE(0, stream);
  const auto dataLen = (headers) ? headers->computeChainDataLength() : 0;
  uint32_t flags = 0;
  if (priority) {
    flags |= PRIORITY;
  }
  if (endStream) {
    flags |= END_STREAM;
  }
  if (endHeaders) {
    flags |= END_HEADERS;
  }
  // padding flags handled directly inside writeFrameHeader()
  const auto frameLen = writeFrameHeader(queue,
                                         dataLen,
                                         FrameType::HEADERS,
                                         flags,
                                         stream,
                                         padding,
                                         priority,
                                         std::move(headers));
  writePadding(queue, padding);
  return kFrameHeaderSize + frameLen;
}
size_t proxygen::http2::writePing (folly::IOBufQueue & writeBuf, uint64_t data, bool ack) [noexcept]
Generate an entire PING frame, including the common frame header.
Parameters
writeBuf The output queue to write to. It may grow or add underlying buffers inside this function.
data The opaque data to include.
ack True iff this is a ping response.
Returns
The number of bytes written to writeBuf.
size_t proxygen::http2::writePing (IOBufQueue & queue, uint64_t opaqueData, bool ack) [noexcept]
Definition at line 816 of file HTTP2Framer.cpp.
References ACK, kFrameHeaderSize, kFramePingSize, and proxygen::spdy::PING.
Referenced by proxygen::HTTP2Codec::generatePingReply(), proxygen::HTTP2Codec::generatePingRequest(), and TEST_F().
                             {
  const auto frameLen = writeFrameHeader(queue,
                                         kFramePingSize,
                                         FrameType::PING,
                                         ack ? ACK : 0,
                                         0,
                                         kNoPadding,
                                         folly::none,
                                         nullptr);
  queue.append(&opaqueData, sizeof(opaqueData));
  return kFrameHeaderSize + frameLen;
}
size_t proxygen::http2::writePriority (folly::IOBufQueue & writeBuf, uint32_t stream, PriorityUpdate priority) [noexcept]
Generate an entire PRIORITY frame, including the common frame header.
Parameters
writeBuf The output queue to write to. It may grow or add underlying buffers inside this function.
stream The stream identifier of the DATA frame.
priority The priority depedency information to update the stream with.
Returns
The number of bytes written to writeBuf.
size_t proxygen::http2::writePriority (IOBufQueue & queue, uint32_t stream, PriorityUpdate priority) [noexcept]
Definition at line 718 of file HTTP2Framer.cpp.
References kFrameHeaderSize, kFramePrioritySize, and PRIORITY.
Referenced by proxygen::HTTP2Codec::generatePriority(), and TEST_F().
                                                {
  DCHECK_NE(0, stream);
  const auto frameLen = writeFrameHeader(queue,
                                         kFramePrioritySize,
                                         FrameType::PRIORITY,
                                         0,
                                         stream,
                                         kNoPadding,
                                         priority,
                                         nullptr);
  return kFrameHeaderSize + frameLen;
}
size_t proxygen::http2::writePushPromise (folly::IOBufQueue & writeBuf, uint32_t associatedStream, uint32_t promisedStream, std::unique_ptr< folly::IOBuf > headers, folly::Optional< uint8_t > padding, bool endHeaders) [noexcept]
Writes an entire PUSH_PROMISE frame, including the common frame header.
Parameters
writeBuf The output queue to write to. It may grow or add underlying buffers inside this function.
associatedStream The identifier of the stream the promised stream is associated with.
promisedStream The identifier of the promised stream.
headers The encoded headers to include in the push promise frame.
padding If not kNoPadding, adds 1 byte pad len and pad bytes
endHeaders True iff no CONTINUATION frames will follow this frame.
Returns
The number of bytes written to writeBuf/
size_t proxygen::http2::writePushPromise (IOBufQueue & queue, uint32_t associatedStream, uint32_t promisedStream, std::unique_ptr< IOBuf > headers, folly::Optional< uint8_t > padding, bool endHeaders) [noexcept]
Definition at line 787 of file HTTP2Framer.cpp.
References END_HEADERS, kFrameHeaderSize, and kFramePushPromiseSize.
Referenced by proxygen::HTTP2Codec::generateHeaderImpl(), and TEST_F().
                                           {
  DCHECK_NE(0, promisedStream);
  DCHECK_NE(0, associatedStream);
  DCHECK_EQ(0, 0x1 & promisedStream);
  DCHECK_EQ(1, 0x1 & associatedStream);
  DCHECK_EQ(0, ~kUint31Mask & promisedStream);
  const auto dataLen = headers->computeChainDataLength();
  const auto frameLen = writeFrameHeader(queue,
                                         dataLen + kFramePushPromiseSize,
                                         FrameType::PUSH_PROMISE,
                                         endHeaders ? END_HEADERS : 0,
                                         associatedStream,
                                         padding,
                                         folly::none,
                                         nullptr);
  QueueAppender appender(&queue, frameLen);
  appender.writeBE<uint32_t>(promisedStream);
  queue.append(std::move(headers));
  writePadding(queue, padding);
  return kFrameHeaderSize + frameLen;
}
size_t proxygen::http2::writeRstStream (folly::IOBufQueue & writeBuf, uint32_t stream, ErrorCode errorCode) [noexcept]
Generate an entire RST_STREAM frame, including the common frame header.
Parameters
writeBuf The output queue to write to. It may grow or add underlying buffers inside this function.
stream The identifier of the stream to reset.
errorCode The error code returned in the frame.
Returns
The number of bytes written to writeBuf.
size_t proxygen::http2::writeRstStream (IOBufQueue & queue, uint32_t stream, ErrorCode errorCode) [noexcept]
Definition at line 734 of file HTTP2Framer.cpp.
References kFrameHeaderSize, kFrameRstStreamSize, and proxygen::spdy::RST_STREAM.
Referenced by proxygen::HTTP2Codec::generateRstStream(), and TEST_F().
                                             {
  DCHECK_NE(0, stream);
  const auto frameLen = writeFrameHeader(queue,
                                         kFrameRstStreamSize,
                                         FrameType::RST_STREAM,
                                         0,
                                         stream,
                                         kNoPadding,
                                         folly::none,
                                         nullptr);
  QueueAppender appender(&queue, frameLen);
  appender.writeBE<uint32_t>(static_cast<uint32_t>(errorCode));
  return kFrameHeaderSize + frameLen;
}
size_t proxygen::http2::writeSettings (folly::IOBufQueue & writeBuf, const std::deque< SettingPair > & settings)
Generate an entire SETTINGS frame, including the common frame header.
Parameters
writeBuf The output queue to write to. It may grow or add underlying buffers inside this function.
settings The settings to send
Returns
The number of bytes written to writeBuf.
size_t proxygen::http2::writeSettings (IOBufQueue & queue, const std::deque< SettingPair > & settings)
Definition at line 752 of file HTTP2Framer.cpp.
References kFrameHeaderSize, and proxygen::spdy::SETTINGS.
Referenced by proxygen::HTTP2Codec::generateSettings(), and TEST_F().
                                                     {
  const auto settingsSize = settings.size() * 6;
  const auto frameLen = writeFrameHeader(queue,
                                         settingsSize,
                                         FrameType::SETTINGS,
                                         0,
                                         0,
                                         kNoPadding,
                                         folly::none,
                                         nullptr);
  QueueAppender appender(&queue, settingsSize);
  for (const auto& setting: settings) {
    DCHECK_LE(static_cast<uint32_t>(setting.first),
              std::numeric_limits<uint16_t>::max());
    appender.writeBE<uint16_t>(static_cast<uint16_t>(setting.first));
    appender.writeBE<uint32_t>(setting.second);
  }
  return kFrameHeaderSize + frameLen;
}
size_t proxygen::http2::writeSettingsAck (folly::IOBufQueue & writeBuf)
Writes an entire empty SETTINGS frame, including the common frame header. No settings can be transmitted with this frame.
size_t proxygen::http2::writeSettingsAck (IOBufQueue & queue)
Definition at line 774 of file HTTP2Framer.cpp.
References ACK, kFrameHeaderSize, and proxygen::spdy::SETTINGS.
Referenced by proxygen::HTTP2Codec::generateSettingsAck(), and TEST_F().
                                    {
  writeFrameHeader(queue,
                   0,
                   FrameType::SETTINGS,
                   ACK,
                   0,
                   kNoPadding,
                   folly::none,
                   nullptr);
  return kFrameHeaderSize;
}
size_t proxygen::http2::writeWindowUpdate (folly::IOBufQueue & writeBuf, uint32_t stream, uint32_t amount) [noexcept]
Generate an entire WINDOW_UPDATE frame, including the common frame header. |amount| MUST be between 1 to 2^31 - 1 inclusive
Parameters
writeBuf The output queue to write to. It may grow or add underlying buffers inside this function.
stream The stream to send a WINDOW_UPDATE on
amount The number of bytes to AK
Returns
The number of bytes written to writeBuf.
size_t proxygen::http2::writeWindowUpdate (IOBufQueue & queue, uint32_t stream, uint32_t amount) [noexcept]
Definition at line 854 of file HTTP2Framer.cpp.
References kFrameHeaderSize, kFrameWindowUpdateSize, and proxygen::spdy::WINDOW_UPDATE.
Referenced by proxygen::HTTP2Codec::generateWindowUpdate(), and TEST_F().
                                            {
  const auto frameLen = writeFrameHeader(queue,
                                         kFrameWindowUpdateSize,
                                         FrameType::WINDOW_UPDATE,
                                         0,
                                         stream,
                                         kNoPadding,
                                         folly::none,
                                         nullptr);
  DCHECK_EQ(0, ~kUint31Mask & amount);
  DCHECK_LT(0, amount);
  QueueAppender appender(&queue, kFrameWindowUpdateSize);
  appender.writeBE<uint32_t>(amount);
  return kFrameHeaderSize + frameLen;
}
Variable Documentation
FB_EXPORT const PriorityUpdate proxygen::http2::DefaultPriority {0, false, 15}
Definition at line 21 of file HTTP2Framer.cpp.
Referenced by proxygen::HTTPSession::getMessagePriority(), and proxygen::HTTPSession::sessionByteOffset().
const std::string proxygen::http2::kConnectionPreface
Referenced by proxygen::HTTP2Codec::generateConnectionPreface(), proxygen::HTTP2Codec::onIngress(), and TEST_F().
const uint32_t proxygen::http2::kFrameAltSvcSizeBase = 8
Definition at line 43 of file HTTP2Constants.cpp.
Referenced by parseAltSvc(), and writeAltSvc().
const uint32_t proxygen::http2::kFrameCertificateRequestSizeBase = 2
Definition at line 40 of file HTTP2Constants.cpp.
Referenced by parseCertificateRequest(), TEST_F(), and writeCertificateRequest().
const uint32_t proxygen::http2::kFrameCertificateSizeBase = 2
Definition at line 41 of file HTTP2Constants.cpp.
Referenced by parseCertificate(), TEST_F(), and writeCertificate().
const uint32_t proxygen::http2::kFrameGoawaySize = 8
Definition at line 38 of file HTTP2Constants.cpp.
Referenced by parseGoaway(), TEST_F(), and writeGoaway().
const uint32_t proxygen::http2::kFrameHeadersBaseMaxSize = kFramePrioritySize + 1
Definition at line 32 of file HTTP2Constants.cpp.
Referenced by proxygen::HTTP2Codec::encodeHeaders().
const uint32_t proxygen::http2::kFrameHeaderSize = 9
Definition at line 30 of file HTTP2Constants.cpp.
Referenced by proxygen::HTTP2Codec::encodeHeaders(), proxygen::HTTP2Codec::onIngress(), parseFrameHeader(), proxygen::HTTP2Codec::requestUpgrade(), TEST_F(), writeAltSvc(), writeCertificate(), writeCertificateRequest(), writeContinuation(), writeData(), writeExHeaders(), writeFrameHeaderManual(), writeGoaway(), writeHeaders(), writePing(), writePriority(), writePushPromise(), writeRstStream(), writeSettings(), writeSettingsAck(), and writeWindowUpdate().
const uint32_t proxygen::http2::kFramePingSize = 8
Definition at line 37 of file HTTP2Constants.cpp.
Referenced by parsePing(), and writePing().
const uint32_t proxygen::http2::kFramePrioritySize = 5
Definition at line 33 of file HTTP2Constants.cpp.
Referenced by proxygen::HTTP2Codec::generateHeaderImpl(), parseExHeaders(), parseHeaders(), parsePriority(), TEST_F(), and writePriority().
const uint32_t proxygen::http2::kFramePushPromiseSize = 4
Definition at line 36 of file HTTP2Constants.cpp.
Referenced by parsePushPromise(), and writePushPromise().
const uint32_t proxygen::http2::kFrameRstStreamSize = 4
Definition at line 35 of file HTTP2Constants.cpp.
Referenced by parseRstStream(), TEST_F(), and writeRstStream().
const uint32_t proxygen::http2::kFrameStreamIDSize = 4
Definition at line 34 of file HTTP2Constants.cpp.
Referenced by parseExHeaders(), and writeExHeaders().
const uint32_t proxygen::http2::kFrameWindowUpdateSize = 4
Definition at line 39 of file HTTP2Constants.cpp.
Referenced by parseWindowUpdate(), TEST_F(), and writeWindowUpdate().
const uint32_t proxygen::http2::kInitialWindow = (1u << 16) - 1
Definition at line 48 of file HTTP2Constants.cpp.
Referenced by proxygen::SPDYCodec::getDefaultWindowSize(), proxygen::HTTP2Codec::getDefaultWindowSize(), SPDY31DownstreamTest::SPDY31DownstreamTest(), TEST(), TEST_F(), and MockCodecDownstreamTest::testConnFlowControlBlocked().
const uint32_t proxygen::http2::kMaxAuthenticatorBufSize = 0x20000
Definition at line 52 of file HTTP2Constants.cpp.
Referenced by proxygen::HTTP2Codec::parseCertificate().
const uint32_t proxygen::http2::kMaxFramePayloadLength = (1u << 24) - 1
Definition at line 46 of file HTTP2Constants.cpp.
Referenced by HTTP2FramerTest::dataFrameTest(), proxygen::HTTP2Codec::handleSettings(), proxygen::HTTP2Codec::onIngressUpgradeMessage(), and TEST_F().
const uint32_t proxygen::http2::kMaxFramePayloadLengthMin = (1u << 14)
Definition at line 45 of file HTTP2Constants.cpp.
Referenced by proxygen::getBigGetRequest(), proxygen::HTTP2Codec::handleSettings(), proxygen::HTTP2Codec::maxRecvFrameSize(), proxygen::HTTP2Codec::maxSendFrameSize(), TEST_F(), and HTTP2CodecTest::testFrameSizeLimit().
const uint32_t proxygen::http2::kMaxHeaderTableSize = (1u << 16)
Definition at line 50 of file HTTP2Constants.cpp.
Referenced by proxygen::HTTP2Codec::handleSettings().
const uint32_t proxygen::http2::kMaxStreamID = (1u << 31) - 1
Definition at line 47 of file HTTP2Constants.cpp.
const uint32_t proxygen::http2::kMaxWindowUpdateSize = (1u << 31) - 1
Definition at line 49 of file HTTP2Constants.cpp.
Referenced by proxygen::HTTP2Codec::handleSettings(), and TEST_F().
const uint8_t proxygen::http2::kMinExperimentalFrameType = 0xf0
Definition at line 19 of file HTTP2Framer.cpp.
const Padding proxygen::http2::kNoPadding = folly::none
Definition at line 20 of file HTTP2Framer.cpp.
Referenced by proxygen::HTTP2Codec::generateEOM(), proxygen::HTTP2Codec::generateHeaderImpl(), proxygen::HTTP2Codec::generateTrailers(), and TEST_F().
const std::string proxygen::http2::kProtocolCleartextString
Referenced by proxygen::DefaultHTTPCodecFactory::getCodec(), proxygen::HTTPDefaultSessionCodecFactory::HTTPDefaultSessionCodecFactory(), proxygen::isValidCodecProtocolStr(), proxygen::HTTPServerAcceptor::makeConfig(), proxygen::HTTP2Codec::requestUpgrade(), TEST(), and HTTPDownstreamTest< C >::testSimpleUpgrade().
const std::string proxygen::http2::kProtocolDraftString
Referenced by proxygen::DefaultHTTPCodecFactory::getCodec(), and proxygen::HTTPDefaultSessionCodecFactory::getCodec().
const std::string proxygen::http2::kProtocolExperimentalString
Referenced by proxygen::DefaultHTTPCodecFactory::getCodec(), and proxygen::HTTPDefaultSessionCodecFactory::getCodec().
const std::string proxygen::http2::kProtocolSettingsHeader
Referenced by proxygen::HTTP2Codec::onIngressUpgradeMessage(), proxygen::HTTP2Codec::requestUpgrade(), and TEST_F().
const std::string proxygen::http2::kProtocolString
Referenced by proxygen::DefaultHTTPCodecFactory::getCodec(), proxygen::HTTPDefaultSessionCodecFactory::getCodec(), proxygen::isValidCodecProtocolStr(), proxygen::HTTP2Codec::onHeadersComplete(), and TEST().