shell_quoting Namespace Reference
Classes
class ShellQuoted
Functions
def shell_quote (s)
def raw_shell (s)
def shell_join (delim, it)
def path_join (args)
def shell_comment (c)
Function Documentation
def shell_quoting.path_join (args)
Definition at line 87 of file shell_quoting.py.
References raw_shell(), and shell_quote().
Referenced by fbcode_builder.FBCodeBuilder.github_project_workdir().
def path_join(*args):
    'Joins ShellQuoted and raw pieces of paths to make a shell-quoted path'
    return ShellQuoted(os.path.join(*[
        raw_shell(shell_quote(s)) for s in args
    ]))
def shell_quoting.raw_shell (s)
Definition at line 75 of file shell_quoting.py.
Referenced by shell_builder.ShellFBCodeBuilder._render_impl(), docker_builder.DockerFBCodeBuilder._render_impl(), parse_args.parse_args_to_fbcode_builder_opts(), path_join(), shell_comment(), and shell_join().
def raw_shell(s):
    'Not a member of ShellQuoted so we get a useful error for raw strings'
    if isinstance(s, ShellQuoted):
        return s.do_not_use_raw_str
    raise RuntimeError('{0} should have been ShellQuoted'.format(s))
def shell_quoting.shell_comment (c)
Definition at line 94 of file shell_quoting.py.
References raw_shell().
Referenced by shell_builder.ShellFBCodeBuilder.comment(), and docker_builder.DockerFBCodeBuilder.comment().
def shell_comment(c):
    'Do not shell-escape raw strings in comments, but do handle line breaks.'
    return ShellQuoted('# {c}').format(c=ShellQuoted(
        (raw_shell(c) if isinstance(c, ShellQuoted) else c)
            .replace('\n', '\n# ')
    ))
def shell_quoting.shell_join (delim, it)
Definition at line 82 of file shell_quoting.py.
References raw_shell().
Referenced by fbcode_builder.FBCodeBuilder._make_vars(), shell_builder.ShellFBCodeBuilder._render_impl(), docker_builder.DockerFBCodeBuilder._render_impl(), fbcode_builder.FBCodeBuilder.cmake_configure(), fbcode_builder.FBCodeBuilder.configure(), and fbcode_builder.FBCodeBuilder.install_debian_deps().
def shell_join(delim, it):
    'Joins an iterable of ShellQuoted with a delimiter between each two'
    return ShellQuoted(delim.join(raw_shell(s) for s in it))
def shell_quoting.shell_quote (s)
Definition at line 69 of file shell_quoting.py.
Referenced by shell_quoting.ShellQuoted.format(), and path_join().
def shell_quote(s):
    'Quotes a string if it is not already quoted'
    return s if isinstance(s, ShellQuoted) \
        else ShellQuoted("'" + str(s).replace("'", "'\\''") + "'")