utils Namespace Reference
Functions
def recursively_flatten_list (l)
def run_command (cmd, kwargs)
def make_temp_dir (d)
def _inner_read_config (path)
def read_fbcode_builder_config (filename)
def steps_for_spec (builder, spec, processed_modules=None)
def build_fbcode_builder_config (config)
Function Documentation
def utils._inner_read_config (path) [private]
Helper to read a named config file.
The grossness with the global is a workaround for this python bug:
https://bugs.python.org/issue21591
The bug prevents us from defining either a local function or a lambda
in the scope of read_fbcode_builder_config below.
Definition at line 42 of file utils.py.
References read_fbcode_builder_config().
def _inner_read_config(path):
    '''
    Helper to read a named config file.
    The grossness with the global is a workaround for this python bug:
    https://bugs.python.org/issue21591
    The bug prevents us from defining either a local function or a lambda
    in the scope of read_fbcode_builder_config below.
    '''
    global _project_dir
    full_path = os.path.join(_project_dir, path)
    return read_fbcode_builder_config(full_path)
def utils.build_fbcode_builder_config (config)
Definition at line 93 of file utils.py.
References steps_for_spec().
def build_fbcode_builder_config(config):
    return lambda builder: builder.build(
        steps_for_spec(builder, config['fbcode_builder_spec'](builder))
    )
def utils.make_temp_dir (d)
Definition at line 34 of file utils.py.
def make_temp_dir(d):
    os.mkdir(d)
    try:
        yield d
    finally:
        shutil.rmtree(d, ignore_errors=True)
def utils.read_fbcode_builder_config (filename)
Definition at line 55 of file utils.py.
Referenced by _inner_read_config().
def read_fbcode_builder_config(filename):
    # Allow one spec to read another
    # When doing so, treat paths as relative to the config's project directory.
    # _project_dir is a "local" for _inner_read_config; see the comments
    # in that function for an explanation of the use of global.
    global _project_dir
    _project_dir = os.path.dirname(filename)
    scope = {'read_fbcode_builder_config': _inner_read_config}
    with open(filename) as config_file:
        code = compile(config_file.read(), filename, mode='exec')
    exec(code, scope)
    return scope['config']
def utils.recursively_flatten_list (l)
Definition at line 19 of file utils.py.
Referenced by shell_builder.ShellFBCodeBuilder._render_impl(), and docker_builder.DockerFBCodeBuilder._render_impl().
def recursively_flatten_list(l):
    return itertools.chain.from_iterable(
        (recursively_flatten_list(i) if type(i) is list else (i,))
            for i in l
    )
def utils.run_command (cmd, kwargs)
Definition at line 26 of file utils.py.
Referenced by docker_builder.DockerFBCodeBuilder.copy_local_repo().
def run_command(*cmd, **kwargs):
    'The stdout of most fbcode_builder utilities is meant to be parsed.'
    logging.debug('Running: {0} with {1}'.format(cmd, kwargs))
    kwargs['stdout'] = sys.stderr
    subprocess.check_call(cmd, **kwargs)
@contextmanager
def utils.steps_for_spec (builder, spec, processed_modules = None)
Sets `builder` configuration, and returns all the builder steps
necessary to build `spec` and its dependencies.

Traverses the dependencies in depth-first order, honoring the sequencing
in each 'depends_on' list.
Definition at line 70 of file utils.py.
Referenced by build_fbcode_builder_config().
def steps_for_spec(builder, spec, processed_modules=None):
    '''
    Sets `builder` configuration, and returns all the builder steps
    necessary to build `spec` and its dependencies.
    Traverses the dependencies in depth-first order, honoring the sequencing
    in each 'depends_on' list.
    '''
    if processed_modules is None:
        processed_modules = set()
    steps = []
    for module in spec.get('depends_on', []):
        if module not in processed_modules:
            processed_modules.add(module)
            steps.extend(steps_for_spec(
                builder,
                module.fbcode_builder_spec(builder),
                processed_modules
            ))
    steps.extend(spec.get('steps', []))
    return steps