proxygen::huffman Namespace Reference
Classes
struct HuffNode
class HuffTree
struct SuperHuffNode
Functions
const HuffTree & huffTree ()
Variables
const uint32_t s_codesTable [kTableSize]
const uint8_t s_bitsTable [kTableSize]
const uint32_t kTableSize = 256
const uint32_t kEOSHpack = 0x3fffffff
Function Documentation
const HuffTree & proxygen::huffman::huffTree ()
Definition at line 252 of file Huffman.cpp.
References s_codesTable.
Referenced by proxygen::HPACKDecodeBuffer::decodeLiteral(), proxygen::HPACKEncodeBuffer::encodeHuffman(), TestingHuffTree::getHuffTree(), and TEST_F().
                           {
  static const folly::Indestructible<HuffTree> huffTree{
    HuffTree{s_codesTable, s_bitsTable}
  };
  return *huffTree;
}
Variable Documentation
const uint32_t proxygen::huffman::kEOSHpack = 0x3fffffff
Definition at line 25 of file Huffman.h.
const uint32_t proxygen::huffman::kTableSize = 256
Definition at line 21 of file Huffman.h.
Referenced by proxygen::huffman::HuffTree::buildTree().
const uint8_t proxygen::huffman::s_bitsTable[kTableSize]
Initial value:
= {
  13, 23, 28, 28, 28, 28, 28, 28, 28, 24, 30, 28, 28, 30, 28, 28, 28, 28, 28,
  28, 28, 28, 30, 28, 28, 28, 28, 28, 28, 28, 28, 28, 6, 10, 10, 12, 13, 6, 8,
  11, 10, 10, 8, 11, 8, 6, 6, 6, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 7, 8, 15, 6,
  12, 10, 13, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
  7, 7, 8, 7, 8, 13, 19, 13, 14, 6, 15, 5, 6, 5, 6, 5, 6, 6, 6, 5, 7, 7, 6, 6,
  6, 5, 6, 7, 6, 5, 5, 6, 7, 7, 7, 7, 7, 15, 11, 14, 13, 28, 20, 22, 20, 20,
  22, 22, 22, 23, 22, 23, 23, 23, 23, 23, 24, 23, 24, 24, 22, 23, 24, 23, 23,
  23, 23, 21, 22, 23, 22, 23, 23, 24, 22, 21, 20, 22, 22, 23, 23, 21, 23, 22,
  22, 24, 21, 22, 23, 23, 21, 21, 22, 21, 23, 22, 23, 23, 20, 22, 22, 22, 23,
  22, 22, 23, 26, 26, 20, 19, 22, 23, 22, 25, 26, 26, 26, 27, 27, 26, 24, 25,
  19, 21, 26, 27, 27, 26, 27, 24, 21, 21, 26, 26, 28, 27, 27, 27, 20, 24, 20,
  21, 22, 21, 21, 23, 22, 22, 25, 25, 24, 24, 26, 23, 26, 27, 26, 26, 27, 27,
  27, 27, 27, 28, 27, 27, 27, 27, 27, 26
}
Definition at line 236 of file Huffman.cpp.
const uint32_t proxygen::huffman::s_codesTable[kTableSize]
Definition at line 201 of file Huffman.cpp.
Referenced by huffTree().