proxygen Namespace Reference
Namespaces
 compress
 headers
 hpack
 HPACK
 http2
 huffman
 logging_details
 RFC2616
 spdy
 StructuredHeaders
Classes
struct AcceptorAddress
struct AcceptorConfiguration
class AcceptorFactory
class AckByteEvent
struct AckLatencyEvent
class AckTimeout
struct AsciiCaseUnderscoreInsensitive
class AsyncTimeoutSet
class Base64
class BinPrinter
class ByteEvent
class ByteEventTracker
class ChainInfoPrinter
class CobHelper
class CodecErrorResponseHandler
class CodecUtil
struct CompressionInfo
class ConsistentHash
class DanglingQueueTest
class DanglingQueueTestBase
class DefaultHTTPCodecFactory
class DirectResponseHandler
class DummyHTTPSessionStats
class DummyTimeout
class Exception
class ExMessageHandler
class FakeHTTPCodecCallback
class Filter
class FilterChain
class FlowControlFilter
class GenericFilter
class GzipHeaderCodec
class HandlerCallbacks
class HasHTTPHeaderMatcherImpl
class HeaderCodec
class HeaderDecodeInfo
struct HeaderDecodeResult
class HeaderIndexingStrategy
class HeaderTable
class HeaderTableTests
class Hex16Printer
class HexFollyPrinter
class HPACKCodec
class HPACKContext
class HPACKDecodeBuffer
class HPACKDecoder
class HPACKDecoderBase
class HPACKEncodeBuffer
class HPACKEncoder
class HPACKEncoderBase
class HPACKHeader
class HPACKHeaderName
class HPACKQueue
class HTTP1xCodec
struct HTTP1xCodecPair
class HTTP2Codec
struct HTTP2CodecPair
class HTTP2PriorityQueue
class HTTP2PriorityQueueBase
class HTTPAcceptor
class HTTPArchive
class HTTPChecks
class HTTPCodec
class HTTPCodecFactory
class HTTPCodecPrinter
class HTTPCommonHeaders
class HTTPConnector
class HTTPDefaultSessionCodecFactory
class HTTPDirectResponseHandler
class HTTPDownstreamSession
class HTTPErrorPage
class HTTPEvent
class HTTPException
class HTTPHandlerBase
class HTTPHeaders
class HTTPMessage
class HTTPMessageFilter
class HTTPParallelCodec
class HTTPPriorityMapFactoryProvider
class HTTPPushTransactionHandler
class HTTPRequestVerifier
class HTTPServer
class HTTPServerAcceptor
class HTTPServerOptions
class HTTPSession
class HTTPSessionAcceptor
class HTTPSessionBase
class HTTPSessionController
class HTTPSessionStats
struct HTTPSetting
class HTTPSettings
class HTTPStaticErrorPage
class HTTPTransaction
class HTTPTransactionEgressSMData
class HTTPTransactionHandler
class HTTPTransactionIngressSMData
class HTTPTransactionTransportCallback
class HTTPUpstreamSession
class HTTPUpstreamSessionController
class IllegalItemTest
class IllegalListTest
class IOBufPrinter
class LegalBinaryContentTests
class LegalFloatTests
class LegalIntegerTests
class LegalStringTests
class Mock1867Callback
class MockByteEventTracker
class MockController
class MockHTTPCodec
class MockHTTPCodecCallback
struct MockHTTPCodecPair
class MockHTTPHandler
class MockHTTPMessageFilter
class MockHTTPPushHandler
class MockHTTPSessionInfoCallback
class MockHTTPSessionStats
class MockHTTPTransaction
class MockHTTPTransactionTransport
class MockHTTPTransactionTransportCallback
class MockRequestHandler
class MockResponseHandler
class MockSecondaryAuthManager
class MockTimeUtilGeneric
class MockUpstreamController
class NoPathIndexingStrategy
class NullStream
struct NullTraceEventObserver
class ParseURL
class PassThroughHTTPCodecFilter
class PassThroughTransportFilter
class PerfectIndexMap
class PingByteEvent
class PushHandler
class QPACKCodec
class QPACKContext
class QPACKDecoder
class QPACKEncoder
class QPACKHeaderTable
class QPACKHeaderTableTests
class QPACKStaticHeaderTable
class QueueTest
class RejectConnectFilter
class RejectConnectFilterFactory
class RendezvousHash
class RequestHandler
class RequestHandlerAdaptor
class RequestHandlerChain
class RequestHandlerFactory
class RequestWorker
class ResponseBuilder
class ResponseHandler
class RFC1867Base
class RFC1867Codec
class RFC1867CR
class RFC1867Test
class ScopedHandler
class ScopedHandlerFactory
class ScopedHTTPServer
class SecondaryAuthManager
class SecondaryAuthManagerBase
class Service
class ServiceConfiguration
class ServiceWorker
class SignalHandler
class SimpleController
class SimpleTimeoutClock
struct SPDY3_1CodecPair
struct SPDY3CodecPair
class SPDYCodec
struct SPDYVersionSettings
class StackTracePrinterWithException
class StateMachine
class StaticHeaderTable
class StructuredHeadersBuffer
class StructuredHeadersBufferTest
class StructuredHeadersDecoder
class StructuredHeadersDecoderTest
class StructuredHeadersEncoder
class StructuredHeadersEncoderTest
class StructuredHeadersStandardTest
class TestStreamingCallback
class TimeUtilGeneric
class TraceEvent
class TraceEventContext
struct TraceEventObserver
class TransactionByteEvent
class TransactionInfo
class TTLBAStats
class URL
class WheelTimerInstance
class Window
class WorkerThread
class ZlibServerFilter
class ZlibServerFilterFactory
class ZlibStreamCompressor
class ZlibStreamDecompressor
class ZstdStreamDecompressor
Typedefs
typedef GenericFilter< HTTPCodec, HTTPCodec::Callback,&HTTPCodec::setCallback, true > HTTPCodecFilter
typedef FilterChain< HTTPCodec, HTTPCodec::Callback, PassThroughHTTPCodecFilter,&HTTPCodec::setCallback, true > HTTPCodecFilterChain
using SettingsValue = uint64_t
using SettingsList = std::vector< HTTPSetting >
using SettingPair = std::pair< SettingsId, uint32_t >
using HTTPHeaderSize = wangle::HTTPHeaderSize
using HTTPTransactionEgressSM = StateMachine< HTTPTransactionEgressSMData >
using HTTPTransactionIngressSM = StateMachine< HTTPTransactionIngressSMData >
using IDList = std::list< std::pair< HTTPCodec::StreamID, uint8_t >>
typedef GenericFilter< folly::AsyncTransportWrapper, folly::AsyncTransportWrapper::ReadCallback,&folly::AsyncTransportWrapper::setReadCB, true, folly::AsyncTransportWrapper::Destructor > TransportFilter
typedef FilterChain< folly::AsyncTransportWrapper, folly::AsyncTransportWrapper::ReadCallback, PassThroughTransportFilter,&folly::AsyncTransportWrapper::setReadCB, false > TransportFilterChain
using string_buf = boost::iostreams::stream_buffer< boost::iostreams::back_insert_device< std::string > >
using AcceptorType = AcceptorAddress::AcceptorType
using MockTimeUtil = MockTimeUtilGeneric<>
using SteadyClock = std::chrono::steady_clock
using SystemClock = std::chrono::system_clock
using TimePoint = SteadyClock::time_point
using SystemTimePoint = SystemClock::time_point
using TimeUtil = TimeUtilGeneric<>
Enumerations
enum CodecProtocol : uint8_t {
*
CodecProtocol::HTTP_1_1,
CodecProtocol::SPDY_3,
CodecProtocol::SPDY_3_1,
CodecProtocol::HTTP_2,
*
CodecProtocol::HQ
 }
enum GzipDecodeError : uint8_t {
*
GzipDecodeError::NONE = 0,
GzipDecodeError::BAD_ENCODING = 1,
GzipDecodeError::HEADERS_TOO_LARGE = 2,
GzipDecodeError::INFLATE_DICTIONARY = 3,
*
GzipDecodeError::EMPTY_HEADER_NAME = 4,
GzipDecodeError::EMPTY_HEADER_VALUE = 5,
GzipDecodeError::INVALID_HEADER_VALUE = 6
 }
enum ErrorCode : uint8_t {
*
ErrorCode::NO_ERROR = 0,
ErrorCode::PROTOCOL_ERROR = 1,
ErrorCode::INTERNAL_ERROR = 2,
ErrorCode::FLOW_CONTROL_ERROR = 3,
*
ErrorCode::SETTINGS_TIMEOUT = 4,
ErrorCode::STREAM_CLOSED = 5,
ErrorCode::FRAME_SIZE_ERROR = 6,
ErrorCode::REFUSED_STREAM = 7,
*
ErrorCode::CANCEL = 8,
ErrorCode::COMPRESSION_ERROR = 9,
ErrorCode::CONNECT_ERROR = 10,
ErrorCode::ENHANCE_YOUR_CALM = 11,
*
ErrorCode::INADEQUATE_SECURITY = 12,
ErrorCode::HTTP_1_1_REQUIRED = 13,
ErrorCode::_SPDY_INVALID_STREAM = 100
 }
enum SettingsId : uint64_t {
*
SettingsId::HEADER_TABLE_SIZE = 1,
SettingsId::ENABLE_PUSH = 2,
SettingsId::MAX_CONCURRENT_STREAMS = 3,
SettingsId::INITIAL_WINDOW_SIZE = 4,
*
SettingsId::MAX_FRAME_SIZE = 5,
SettingsId::MAX_HEADER_LIST_SIZE = 6,
SettingsId::ENABLE_CONNECT_PROTOCOL = 8,
SettingsId::THRIFT_CHANNEL_ID_DEPRECATED = 100,
*
SettingsId::ENABLE_EX_HEADERS = 0xfbfb,
SettingsId::THRIFT_CHANNEL_ID = 0xf100,
SettingsId::SETTINGS_HTTP_CERT_AUTH = 0xff00,
SettingsId::_SPDY_UPLOAD_BANDWIDTH = (1 << 16) | 1,
*
SettingsId::_SPDY_DOWNLOAD_BANDWIDTH = (1 << 16) | 2,
SettingsId::_SPDY_ROUND_TRIP_TIME = (1 << 16) | 3,
SettingsId::_SPDY_CURRENT_CWND = (1 << 16) | 5,
SettingsId::_SPDY_DOWNLOAD_RETRANS_RATE = (1 << 16) | 6,
*
SettingsId::_SPDY_CLIENT_CERTIFICATE_VECTOR_SIZE = (1 << 16) | 8,
SettingsId::_HQ_NUM_PLACEHOLDERS = (((uint64_t)1) << 32) | 3,
SettingsId::_HQ_QPACK_BLOCKED_STREAMS = (((uint64_t)1) << 32) | 7
 }
enum SPDYVersion { SPDYVersion::SPDY3 = 0,
SPDYVersion::SPDY3_1
 }
enum TransportDirection : uint8_t { TransportDirection::DOWNSTREAM,
TransportDirection::UPSTREAM
 }
enum HTTPHeaderCode : uint8_t { HTTP_HEADER_NONE = 0,
HTTP_HEADER_OTHER = 1
 }
enum HTTPCommonHeaderTableType : uint8_t { TABLE_CAMELCASE = 0,
TABLE_LOWERCASE = 1
 }
enum ConnectionCloseReason {
*
ConnectionCloseReason::SHUTDOWN,
ConnectionCloseReason::READ_EOF,
ConnectionCloseReason::GOAWAY,
ConnectionCloseReason::SESSION_PARSE_ERROR,
*
ConnectionCloseReason::REMOTE_ERROR,
ConnectionCloseReason::TRANSACTION_ABORT,
ConnectionCloseReason::TIMEOUT,
ConnectionCloseReason::IO_READ_ERROR,
*
ConnectionCloseReason::IO_WRITE_ERROR,
ConnectionCloseReason::REQ_NOTREUSABLE,
ConnectionCloseReason::ERR_RESP,
ConnectionCloseReason::UNKNOWN,
*
ConnectionCloseReason::FLOW_CONTROL,
ConnectionCloseReason::kMAX_REASON
 }
enum UpgradeProtocol : int { UpgradeProtocol::TCP
 }
enum HTTPMethod {
*
HTTPMethod::GET,
HTTPMethod::POST,
HTTPMethod::OPTIONS,
HTTPMethod::DELETE,
*
HTTPMethod::HEAD,
HTTPMethod::CONNECT,
HTTPMethod::PUT,
HTTPMethod::TRACE,
*
HTTPMethod::PATCH,
HTTPMethod::SUB,
HTTPMethod::PUB,
HTTPMethod::UNSUB
 }
enum ProxygenError {
*
kErrorNone,
kErrorMessage,
kErrorConnect,
kErrorConnectTimeout,
*
kErrorRead,
kErrorWrite,
kErrorTimeout,
kErrorHandshake,
*
kErrorNoServer,
kErrorMaxRedirects,
kErrorInvalidRedirect,
kErrorResponseAction,
*
kErrorMaxConnects,
kErrorDropped,
kErrorConnection,
kErrorConnectionReset,
*
kErrorParseHeader,
kErrorParseBody,
kErrorEOF,
kErrorClientRenegotiation,
*
kErrorUnknown,
kErrorBadDecompress,
kErrorSSL,
kErrorStreamAbort,
*
kErrorStreamUnacknowledged,
kErrorWriteTimeout,
kErrorAddressPrivate,
kErrorAddressFamilyNotSupported,
*
kErrorDNSNoResults,
kErrorMalformedInput,
kErrorUnsupportedExpectation,
kErrorMethodNotSupported,
*
kErrorUnsupportedScheme,
kErrorShutdown,
kErrorIngressStateTransition,
kErrorClientSilent,
*
kErrorCanceled,
kErrorParseResponse,
kErrorConnRefused,
kErrorDNSOtherServer,
*
kErrorDNSOtherClient,
kErrorDNSOtherCancelled,
kErrorDNSshutdown,
kErrorDNSgetaddrinfo,
*
kErrorDNSthreadpool,
kErrorDNSunimplemented,
kErrorNetwork,
kErrorConfiguration,
*
kErrorEarlyDataRejected,
kErrorEarlyDataFailed,
kErrorAuthRequired,
kErrorUnauthorized,
*
kErrorMax
 }
enum ZlibCompressionType : int { ZlibCompressionType::NONE = 0,
ZlibCompressionType::DEFLATE = 15,
ZlibCompressionType::GZIP = 31
 }
enum ZstdStatusType : int {
*
ZstdStatusType::NONE,
ZstdStatusType::SUCCESS,
ZstdStatusType::NODICT,
ZstdStatusType::CONTINUE,
*
ZstdStatusType::ERROR
 }
Functions
template<>
std::unique_ptr< ScopedHTTPServer > ScopedHTTPServer::start< std::unique_ptr< RequestHandlerFactory > > (std::unique_ptr< RequestHandlerFactory > f, int port, int numThreads, std::unique_ptr< wangle::SSLContextConfig > sslCfg)
const std::string & getCodecProtocolString (CodecProtocol proto)
bool isValidCodecProtocolStr (const std::string &protocolStr)
CodecProtocol getCodecProtocolFromStr (const std::string &protocolStr)
bool isSpdyCodecProtocol (CodecProtocol protocol)
bool isHTTP2CodecProtocol (CodecProtocol protocol)
bool isHQCodecProtocol (CodecProtocol protocol)
bool isParallelCodecProtocol (CodecProtocol protocol)
folly::Optional< std::pair< CodecProtocol, std::string > > checkForProtocolUpgrade (const std::string &clientUpgrade, const std::string &serverUpgrade, bool serverMode)
bool operator== (const HTTPMessage &msg1, const HTTPMessage &msg2)
std::ostream & operator<< (std::ostream &os, const HeaderTable &table)
std::ostream & operator<< (std::ostream &os, const HPACKCodec &codec)
std::ostream & operator<< (std::ostream &os, const HPACKContext &context)
std::ostream & operator<< (std::ostream &os, const HPACKHeader &h)
std::ostream & operator<< (std::ostream &os, const HPACKHeaderName &name)
ostream & operator<< (ostream &os, const std::list< uint32_t > *refset)
std::ostream & operator<< (std::ostream &os, const std::vector< HPACKHeader > &v)
string printDelta (const vector< HPACKHeader > &v1, const vector< HPACKHeader > &v2)
std::ostream & operator<< (std::ostream &os, const QPACKCodec &codec)
std::ostream & operator<< (std::ostream &os, const QPACKContext &context)
TEST_F (HeaderTableTests, IndexTranslation)
TEST_F (HeaderTableTests, Add)
TEST_F (HeaderTableTests, Evict)
TEST_F (HeaderTableTests, ReduceCapacity)
TEST_F (HeaderTableTests, Comparison)
TEST_F (HeaderTableTests, Print)
TEST_F (HeaderTableTests, IncreaseCapacity)
TEST_F (HeaderTableTests, VaryCapacity)
TEST_F (HeaderTableTests, VaryCapacityMalignHeadIndex)
TEST_F (HeaderTableTests, AddLargerThanTable)
TEST_F (HeaderTableTests, IncreaseLengthOfFullTable)
TEST_F (HeaderTableTests, SmallTable)
std::unique_ptr< IOBuf > readFileToIOBuf (const std::string &filename)
TEST_F (QPACKHeaderTableTests, Indexing)
TEST_F (QPACKHeaderTableTests, Eviction)
TEST_F (QPACKHeaderTableTests, BadEviction)
TEST_F (QPACKHeaderTableTests, Wrapcount)
TEST_F (QPACKHeaderTableTests, NameIndex)
TEST_F (QPACKHeaderTableTests, GetIndex)
TEST_F (QPACKHeaderTableTests, Duplication)
TEST_F (QPACKHeaderTableTests, CanEvictWithRoom)
TEST_F (QPACKHeaderTableTests, EvictNonDrained)
TEST_F (QPACKHeaderTableTests, BadSync)
const char * getErrorCodeString (ErrorCode error)
std::unique_ptr< HTTPMessage > getPriorityMessage (uint8_t priority)
std::unique_ptr< folly::IOBuf > makeBuf (uint32_t size)
std::unique_ptr< testing::NiceMock< MockHTTPCodec > > makeMockParallelCodec (TransportDirection dir)
std::unique_ptr< testing::NiceMock< MockHTTPCodec > > makeDownstreamParallelCodec ()
std::unique_ptr< testing::NiceMock< MockHTTPCodec > > makeUpstreamParallelCodec ()
HTTPMessage getGetRequest (const std::string &url)
HTTPMessage getBigGetRequest (const std::string &url)
std::unique_ptr< HTTPMessage > makeGetRequest ()
HTTPMessage getPostRequest (uint32_t contentLength)
HTTPMessage getChunkedPostRequest ()
std::unique_ptr< HTTPMessage > makePostRequest (uint32_t contentLength)
HTTPMessage getPubRequest (const std::string &url)
HTTPMessage getResponse (uint32_t code, uint32_t bodyLen)
std::unique_ptr< HTTPMessage > makeResponse (uint16_t statusCode)
std::tuple< std::unique_ptr< HTTPMessage >, std::unique_ptr< folly::IOBuf > > makeResponse (uint16_t statusCode, size_t len)
HTTPMessage getUpgradeRequest (const std::string &upgradeHeader, HTTPMethod method, uint32_t bodyLen)
void fakeMockCodec (MockHTTPCodec &codec)
template<class T >
size_t parse (T *codec, const uint8_t *inputData, uint32_t length, int32_t atOnce=0, std::function< bool()> stopFn=[]{return false;})
template<class T >
size_t parseUnidirectional (T *codec, const uint8_t *inputData, uint32_t length, int32_t atOnce=0, std::function< bool()> stopFn=[]{return false;})
MATCHER_P (PtrBufHasLen, n,``)
const char * getTransportDirectionString (TransportDirection dir)
TransportDirection operator! (TransportDirection dir)
std::ostream & operator<< (std::ostream &os, const TransportDirection dir)
TEST_F (RFC1867Test, TestSimplePost)
TEST_F (RFC1867Test, TestSplits)
TEST_F (RFC1867Test, TestSplitsWithFilename)
TEST_F (RFC1867Test, TestHeadersChunkExtraCr)
TEST_P (RFC1867CR, Test)
INSTANTIATE_TEST_CASE_P (ValueTest, RFC1867CR,::testing::Values(string(`zyx\r\nwvu`, 8), string(`\rzyxwvut`, 8), string(`zyxwvut\r`, 8), string(`\nzyxwvut`, 8), string(`zyxwvut\n`, 8), string(`\r\n\r\n\r\n\r\n`, 8), string(`\r\r\r\r\r\r\r\r`, 8)))
const char * getConnectionCloseReasonStringByIndex (unsigned int index)
const char * getConnectionCloseReasonString (ConnectionCloseReason r)
std::ostream & operator<< (std::ostream &os, const HTTPException &ex)
bool isLWS (char c)
std::ostream & operator<< (std::ostream &os, const HTTPMessage &msg)
template<typename Str >
std::string stripCntrlChars (const Str &str)
folly::Optional< HTTPMethod > stringToMethod (folly::StringPiece method)
const std::string & methodToString (HTTPMethod method)
std::ostream & operator<< (std::ostream &out, HTTPMethod method)
const char * getErrorString (ProxygenError error)
const char * getErrorStringByIndex (int i)
std::ostream & operator<< (std::ostream &os, const ByteEvent &be)
std::ostream & operator<< (std::ostream &os, HTTPEvent::Type e)
std::ostream & operator<< (std::ostream &os, const HTTPTransaction &txn)
std::ostream & operator<< (std::ostream &os, HTTPTransactionEgressSMData::State s)
std::ostream & operator<< (std::ostream &os, HTTPTransactionEgressSMData::Event e)
std::ostream & operator<< (std::ostream &os, HTTPTransactionIngressSMData::State s)
std::ostream & operator<< (std::ostream &os, HTTPTransactionIngressSMData::Event e)
TEST_F (QueueTest, Basic)
TEST_F (QueueTest, RemoveLeaf)
TEST_F (QueueTest, RemoveParent)
TEST_F (QueueTest, RemoveParentWeights)
TEST_F (QueueTest, NodeDepth)
TEST_F (QueueTest, UpdateWeight)
TEST_F (QueueTest, DuplicateID)
TEST_F (QueueTest, UpdateWeightNotEnqueued)
TEST_F (QueueTest, UpdateWeightExcl)
TEST_F (QueueTest, UpdateWeightExclDequeued)
TEST_F (QueueTest, UpdateWeightUnknownParent)
TEST_F (QueueTest, UpdateParentSibling)
TEST_F (QueueTest, UpdateParentSiblingExcl)
TEST_F (QueueTest, UpdateParentAncestor)
TEST_F (QueueTest, UpdateParentAncestorExcl)
TEST_F (QueueTest, UpdateParentDescendant)
TEST_F (QueueTest, UpdateParentDescendantExcl)
TEST_F (QueueTest, ExclusiveAdd)
TEST_F (QueueTest, AddUnknown)
TEST_F (QueueTest, AddMax)
TEST_F (QueueTest, Misc)
TEST_F (QueueTest, IterateBFS)
TEST_F (QueueTest, NextEgress)
TEST_F (QueueTest, NextEgressExclusiveAdd)
TEST_F (QueueTest, NextEgressExclusiveAddWithEgress)
TEST_F (QueueTest, UpdatePriorityReparentSubtree)
TEST_F (QueueTest, NextEgressRemoveParent)
TEST_F (QueueTest, AddExclusiveDescendantEnqueued)
TEST_F (QueueTest, NextEgressRemoveParentEnqueued)
TEST_F (QueueTest, NextEgressRemoveParentEnqueuedIndirect)
TEST_F (QueueTest, ChromeTest)
TEST_F (QueueTest, NextEgressSpdy)
TEST_F (QueueTest, AddOrUpdate)
TEST_F (DanglingQueueTest, Basic)
TEST_F (DanglingQueueTest, Chain)
TEST_F (DanglingQueueTest, Drop)
TEST_F (DanglingQueueTest, ExpireParentOfMismatchedTwins)
TEST_F (DanglingQueueTest, Refresh)
TEST_F (DanglingQueueTest, Max)
TEST_F (QueueTest, Rebuild)
ACTION_P (ExpectString, expected)
ACTION_P (ExpectBodyLen, expectedLen)
folly::HHWheelTimer::UniquePtr makeInternalTimeoutSet (EventBase *evb)
folly::HHWheelTimer::UniquePtr makeTimeoutSet (EventBase *evb)
testing::NiceMock< MockAsyncTransport > * newMockTransport (EventBase *evb)
folly::HHWheelTimer::UniquePtr makeInternalTimeoutSet (folly::EventBase *evb)
folly::HHWheelTimer::UniquePtr makeTimeoutSet (folly::EventBase *evb)
testing::NiceMock< folly::test::MockAsyncTransport > * newMockTransport (folly::EventBase *evb)
TEST_F (StructuredHeadersBufferTest, TestBinaryContent)
TEST_F (StructuredHeadersBufferTest, TestBinaryContentIllegalCharacters)
TEST_F (StructuredHeadersBufferTest, TestBinaryContentNoEndingAsterisk)
TEST_F (StructuredHeadersBufferTest, TestBinaryContentEmpty)
TEST_F (StructuredHeadersBufferTest, TestIdentifier)
TEST_F (StructuredHeadersBufferTest, TestIdentifierAllLegalCharacters)
TEST_F (StructuredHeadersBufferTest, TestIdentifierBeginningUnderscore)
TEST_F (StructuredHeadersBufferTest, TestString)
TEST_F (StructuredHeadersBufferTest, TestStringEscapedQuote)
TEST_F (StructuredHeadersBufferTest, TestStringEscapedBackslash)
TEST_F (StructuredHeadersBufferTest, TestStringStrayBackslash)
TEST_F (StructuredHeadersBufferTest, TestStringInvalidCharacter)
TEST_F (StructuredHeadersBufferTest, TestStringParsingRepeated)
TEST_F (StructuredHeadersBufferTest, TestInteger)
TEST_F (StructuredHeadersBufferTest, TestIntegerTwoNegatives)
TEST_F (StructuredHeadersBufferTest, TestIntegerEmptyAfterNegative)
TEST_F (StructuredHeadersBufferTest, TestIntegerNegative)
TEST_F (StructuredHeadersBufferTest, TestIntegerOverflow)
TEST_F (StructuredHeadersBufferTest, TestIntegerHighBorderline)
TEST_F (StructuredHeadersBufferTest, TestIntegerLowBorderline)
TEST_F (StructuredHeadersBufferTest, TestIntegerUnderflow)
TEST_F (StructuredHeadersBufferTest, TestFloat)
TEST_F (StructuredHeadersBufferTest, TestFloatPrecedingWhitespace)
TEST_F (StructuredHeadersBufferTest, TestFloatNoDigitPrecedingDecimal)
TEST_F (StructuredHeadersBufferTest, TestIntegerTooManyChars)
TEST_F (StructuredHeadersBufferTest, TestFloatTooManyChars)
TEST_F (StructuredHeadersBufferTest, TestFloatBorderlineNumChars)
TEST_F (StructuredHeadersBufferTest, TestFloatEndsWithDecimal)
TEST_F (StructuredHeadersBufferTest, TestConsumeComma)
TEST_F (StructuredHeadersBufferTest, TestConsumeEquals)
TEST_F (StructuredHeadersBufferTest, TestConsumeMessy)
TEST_F (StructuredHeadersBufferTest, TestInequalityOperator)
TEST_F (StructuredHeadersDecoderTest, TestItem)
TEST_F (StructuredHeadersDecoderTest, TestList)
TEST_F (StructuredHeadersDecoderTest, TestListBeginningWhitespace)
TEST_F (StructuredHeadersDecoderTest, TestListEndingWhitespace)
TEST_F (StructuredHeadersDecoderTest, TestListNoWhitespace)
TEST_F (StructuredHeadersDecoderTest, TestListOneItem)
TEST_F (StructuredHeadersDecoderTest, TestDictionaryManyElts)
TEST_F (StructuredHeadersDecoderTest, TestDictionaryOneElt)
TEST_F (StructuredHeadersDecoderTest, TestParamListOneElt)
TEST_F (StructuredHeadersDecoderTest, TestParamListManyElts)
TEST_F (StructuredHeadersDecoderTest, TestParamListNoParams)
TEST_F (StructuredHeadersDecoderTest, TestParamListWhitespace)
TEST_F (StructuredHeadersDecoderTest, TestParamListNullValues)
TEST_F (StructuredHeadersEncoderTest, TestInteger)
TEST_F (StructuredHeadersEncoderTest, TestIntegerNegative)
TEST_F (StructuredHeadersEncoderTest, TestFloat)
TEST_F (StructuredHeadersEncoderTest, TestFloatTooMuchPrecision)
TEST_F (StructuredHeadersEncoderTest, TestFloatNegative)
TEST_F (StructuredHeadersEncoderTest, TestString)
TEST_F (StructuredHeadersEncoderTest, TestStringBadContent)
TEST_F (StructuredHeadersEncoderTest, TestStringBackslash)
TEST_F (StructuredHeadersEncoderTest, TestStringQuote)
TEST_F (StructuredHeadersEncoderTest, TestBinaryContent)
TEST_F (StructuredHeadersEncoderTest, TestIdentifier)
TEST_F (StructuredHeadersEncoderTest, TestIdentifierBadContent)
TEST_F (StructuredHeadersEncoderTest, TestWrongType)
TEST_F (StructuredHeadersEncoderTest, TestListManyElts)
TEST_F (StructuredHeadersEncoderTest, TestListOneElt)
TEST_F (StructuredHeadersEncoderTest, TestListEmpty)
TEST_F (StructuredHeadersEncoderTest, TestListBadItem)
TEST_F (StructuredHeadersEncoderTest, TestDictionaryOneElt)
TEST_F (StructuredHeadersEncoderTest, TestDictionaryManyElts)
TEST_F (StructuredHeadersEncoderTest, TestDictionaryEmpty)
TEST_F (StructuredHeadersEncoderTest, TestDictionaryBadItem)
TEST_F (StructuredHeadersEncoderTest, TestDictionaryBadIdentifier)
TEST_F (StructuredHeadersEncoderTest, TestParamListOneElt)
TEST_F (StructuredHeadersEncoderTest, TestParamListSuccessiveNulls)
TEST_F (StructuredHeadersEncoderTest, TestParamListManyElts)
TEST_F (StructuredHeadersEncoderTest, TestParamListEmpty)
TEST_F (StructuredHeadersEncoderTest, TestParamListBadSecondaryIdentifier)
TEST_F (StructuredHeadersEncoderTest, TestParamListBadPrimaryIdentifier)
TEST_F (StructuredHeadersEncoderTest, TestParamListBadItems)
TEST_P (LegalStringTests, LegalStrings)
TEST_P (LegalBinaryContentTests, LegalBinaryContent)
TEST_P (LegalIntegerTests, LegalIntegers)
TEST_P (LegalFloatTests, LegalFloats)
TEST_P (IllegalItemTest, IllegalItem)
TEST_P (IllegalListTest, IllegalList)
INSTANTIATE_TEST_CASE_P (TestLegalStrings, LegalStringTests,::testing::ValuesIn(kLegalStringTests))
INSTANTIATE_TEST_CASE_P (TestLegalBinaryContent, LegalBinaryContentTests,::testing::ValuesIn(kLegalBinContentTests))
INSTANTIATE_TEST_CASE_P (TestLegalInts, LegalIntegerTests,::testing::ValuesIn(kLegalIntTests))
INSTANTIATE_TEST_CASE_P (TestLegalFloats, LegalFloatTests,::testing::ValuesIn(kLegalFloatTests))
INSTANTIATE_TEST_CASE_P (TestIllegalItems, IllegalItemTest,::testing::ValuesIn(kIllegalItemTests))
INSTANTIATE_TEST_CASE_P (TestIllegalLists, IllegalListTest,::testing::ValuesIn(kIllegalListTests))
TEST_F (StructuredHeadersStandardTest, TestBasicList)
TEST_F (StructuredHeadersStandardTest, TestSingleItemList)
TEST_F (StructuredHeadersStandardTest, TestNoWhitespaceList)
TEST_F (StructuredHeadersStandardTest, TestExtraWhitespaceList)
inline::testing::Matcher< HTTPHeaders & > HasHTTPHeader (std::string name)
inline::testing::Matcher< HTTPHeaders & > HasHTTPHeader (std::string name, std::string value)
bool operator< (const AcceptorAddress &lv, const AcceptorAddress &rv)
std::ostream & operator<< (std::ostream &os, const AcceptorAddress::AcceptorType &accType)
std::ostream & operator<< (std::ostream &os, const AcceptorAddress &accAddr)
AsyncTimeoutSet::TimeoutClock & getTimeoutClock ()
std::string base64Encode (folly::ByteRange text)
std::string md5Encode (folly::ByteRange text)
folly::Optional< int64_t > parseHTTPDateTime (const std::string &s)
string hexStr (StringPiece sp)
void dumpBinToFile (const string &filename, const IOBuf *buf)
template<class T >
NullStream & operator<< (NullStream &ns, const T &)
void dumpBinToFile (const std::string &filename, const folly::IOBuf *buf)
std::string hexStr (folly::StringPiece sp)
static bool validateScheme (folly::StringPiece url)
std::string getDateTimeStr (const ASN1_TIME *const time)
template<typename T >
bool durationInitialized (const T &duration)
template<typename T >
bool timePointInitialized (const T &time)
template<typename ClockType = SteadyClock>
std::chrono::time_point< ClockType > getCurrentTime ()
std::chrono::system_clock::time_point toSystemTimePoint (TimePoint t)
time_t toTimeT (TimePoint t)
std::chrono::milliseconds millisecondsSinceEpoch ()
std::chrono::seconds secondsSinceEpoch ()
std::chrono::milliseconds millisecondsSinceEpoch (TimePoint t)
std::chrono::seconds secondsSinceEpoch (TimePoint t)
template<typename ClockType = SteadyClock>
std::chrono::microseconds microsecondsBetween (std::chrono::time_point< ClockType > finish, std::chrono::time_point< ClockType > start)
template<typename ClockType = SteadyClock>
std::chrono::milliseconds millisecondsBetween (std::chrono::time_point< ClockType > finish, std::chrono::time_point< ClockType > start)
template<typename ClockType = SteadyClock>
std::chrono::seconds secondsBetween (std::chrono::time_point< ClockType > finish, std::chrono::time_point< ClockType > start)
template<typename ClockType = SteadyClock>
std::chrono::milliseconds millisecondsSince (std::chrono::time_point< ClockType > t)
template<typename ClockType = SteadyClock>
std::chrono::seconds secondsSince (std::chrono::time_point< ClockType > t)
void getDateTimeStr (char datebuf[32], char timebuf[32])
void getDateOffsetStr (char datebuf[32], int dayOffset)
std::string getDateTimeStr (TimePoint tp)
std::ostream & operator<< (std::ostream &os, TraceEventType eventType)
std::ostream & operator<< (std::ostream &os, TraceFieldType fieldType)
std::ostream & operator<< (std::ostream &out, const TraceEvent &event)
bool caseInsensitiveEqual (folly::StringPiece s, folly::StringPiece t)
bool caseUnderscoreInsensitiveEqual (folly::StringPiece s, folly::StringPiece t)
bool validateURL (folly::ByteRange url)
Variables
const char kSPDYv2Dictionary []
const unsigned char kSPDYv3Dictionary []
const uint8_t kMaxErrorCode = 12
constexpr folly::StringPiece kUpgradeToken = `websocket`
constexpr folly::StringPiece kUpgradeConnectionToken = `Upgrade`
constexpr folly::StringPiece kWSMagicString = `258EAFA5-E914-47DA-95CA-C5AB0DC85B11`
const HTTPSettings kDefaultIngressSettings
const uint8_t HTTPHeaderCodeCommonOffset = 2
const std::string empty_string
const char * connectionCloseStrings []
static const std::string kMessageFilterDefaultName_ = `Unknown`
const char *const kTypeStrings []
constexpr uint32_t kDefaultMaxConcurrentOutgoingStreams = 100
const wangle::TransportInfo mockTransportInfo = wangle::TransportInfo()
const SocketAddress localAddr {`127.0.0.1`, 80}
const SocketAddress peerAddr {`127.0.0.1`, 12345}
static const std::vector< std::pair< std::string, std::string > > kLegalStringTests
static const std::vector< std::pair< std::string, std::string > > kLegalBinContentTests
static const std::vector< std::pair< std::string, int64_t > > kLegalIntTests
static const std::vector< std::pair< std::string, double > > kLegalFloatTests
static const std::vector< std::string > kIllegalItemTests
static const std::vector< std::string > kIllegalListTests
static const std::string kMockFilterName = `MockFilter`
Typedef Documentation
using proxygen::AcceptorType = typedef AcceptorAddress::AcceptorType
Definition at line 59 of file AcceptorAddress.h.
typedef GenericFilter< HTTPCodec, HTTPCodec::Callback, &HTTPCodec::setCallback, true> proxygen::HTTPCodecFilter
Definition at line 21 of file HTTPCodecFilter.h.
typedef FilterChain< HTTPCodec, HTTPCodec::Callback, PassThroughHTTPCodecFilter, &HTTPCodec::setCallback, true> proxygen::HTTPCodecFilterChain
Definition at line 255 of file HTTPCodecFilter.h.
using proxygen::HTTPHeaderSize = typedef wangle::HTTPHeaderSize
Definition at line 18 of file HTTPHeaderSize.h.
using proxygen::HTTPTransactionEgressSM = typedef StateMachine<HTTPTransactionEgressSMData>
Definition at line 61 of file HTTPTransactionEgressSM.h.
using proxygen::HTTPTransactionIngressSM = typedef StateMachine<HTTPTransactionIngressSMData>
Definition at line 64 of file HTTPTransactionIngressSM.h.
using proxygen::IDList = typedef std::list<std::pair<HTTPCodec::StreamID, uint8_t>>
Definition at line 53 of file HTTP2PriorityQueueTest.cpp.
using proxygen::MockTimeUtil = typedef MockTimeUtilGeneric<>
Definition at line 42 of file MockTime.h.
using proxygen::SettingPair = typedef std::pair<SettingsId, uint32_t>
Definition at line 58 of file SettingsId.h.
using proxygen::SettingsList = typedef std::vector<HTTPSetting>
Definition at line 81 of file HTTPSettings.h.
using proxygen::SettingsValue = typedef uint64_t
Definition at line 25 of file HTTPSettings.h.
using proxygen::SteadyClock = typedef std::chrono::steady_clock
Definition at line 23 of file Time.h.
using proxygen::string_buf = typedef boost::iostreams::stream_buffer< boost::iostreams::back_insert_device<std::string> >
Definition at line 26 of file StructuredHeadersEncoder.h.
using proxygen::SystemClock = typedef std::chrono::system_clock
Definition at line 24 of file Time.h.
using proxygen::SystemTimePoint = typedef SystemClock::time_point
Definition at line 26 of file Time.h.
using proxygen::TimePoint = typedef SteadyClock::time_point
Definition at line 25 of file Time.h.
using proxygen::TimeUtil = typedef TimeUtilGeneric<>
Definition at line 194 of file Time.h.
typedef GenericFilter< folly::AsyncTransportWrapper, folly::AsyncTransportWrapper::ReadCallback, &folly::AsyncTransportWrapper::setReadCB, true, folly::AsyncTransportWrapper::Destructor> proxygen::TransportFilter
Definition at line 23 of file TransportFilter.h.
typedef FilterChain< folly::AsyncTransportWrapper, folly::AsyncTransportWrapper::ReadCallback, PassThroughTransportFilter, &folly::AsyncTransportWrapper::setReadCB, false> proxygen::TransportFilterChain
Definition at line 121 of file TransportFilter.h.
Enumeration Type Documentation
enum proxygen::CodecProtocol : uint8_t [strong]
Enumerator
HTTP_1_1
SPDY_3
SPDY_3_1
HTTP_2
HQ
Definition at line 19 of file CodecProtocol.h.
                         : uint8_t {
  HTTP_1_1,
  SPDY_3,
  SPDY_3_1,
  HTTP_2,
  HQ,
};
enum proxygen::ConnectionCloseReason [strong]
Enumerator
SHUTDOWN
READ_EOF
GOAWAY
SESSION_PARSE_ERROR
REMOTE_ERROR
TRANSACTION_ABORT
TIMEOUT
IO_READ_ERROR
IO_WRITE_ERROR
REQ_NOTREUSABLE
ERR_RESP
UNKNOWN
FLOW_CONTROL
kMAX_REASON
Definition at line 51 of file HTTPConstants.h.
                                 {
  CONNECTION_CLOSE_REASON_GEN(CONNECTION_CLOSE_REASON_ENUM)
enum proxygen::ErrorCode : uint8_t [strong]
Enumerator
NO_ERROR
PROTOCOL_ERROR
INTERNAL_ERROR
FLOW_CONTROL_ERROR
SETTINGS_TIMEOUT
STREAM_CLOSED
FRAME_SIZE_ERROR
REFUSED_STREAM
CANCEL
COMPRESSION_ERROR
CONNECT_ERROR
ENHANCE_YOUR_CALM
INADEQUATE_SECURITY
HTTP_1_1_REQUIRED
_SPDY_INVALID_STREAM
Definition at line 26 of file ErrorCode.h.
                    : uint8_t {
  NO_ERROR = 0,
  PROTOCOL_ERROR = 1,
  INTERNAL_ERROR = 2,
  FLOW_CONTROL_ERROR = 3,
  SETTINGS_TIMEOUT = 4,
  STREAM_CLOSED = 5,
  FRAME_SIZE_ERROR = 6,
  REFUSED_STREAM = 7,
  CANCEL = 8,
  COMPRESSION_ERROR = 9,
  CONNECT_ERROR = 10,
  ENHANCE_YOUR_CALM = 11,
  INADEQUATE_SECURITY = 12,
  HTTP_1_1_REQUIRED = 13,
  // This code is *NOT* to be used outside of SPDYCodec. Delete this
  // when we deprecate SPDY.
  _SPDY_INVALID_STREAM = 100,
};
enum proxygen::GzipDecodeError : uint8_t [strong]
Enumerator
NONE
BAD_ENCODING
HEADERS_TOO_LARGE
INFLATE_DICTIONARY
EMPTY_HEADER_NAME
EMPTY_HEADER_VALUE
INVALID_HEADER_VALUE
Definition at line 24 of file GzipHeaderCodec.h.
                           : uint8_t {
  NONE = 0,
  BAD_ENCODING = 1,
  HEADERS_TOO_LARGE = 2,
  INFLATE_DICTIONARY = 3,
  EMPTY_HEADER_NAME = 4,
  EMPTY_HEADER_VALUE = 5,
  INVALID_HEADER_VALUE = 6
};
enum proxygen::HTTPCommonHeaderTableType : uint8_t
Enumerator
TABLE_CAMELCASE
TABLE_LOWERCASE
Definition at line 46 of file HTTPCommonHeaders.template.h.
                              : uint8_t {
  TABLE_CAMELCASE = 0,
  TABLE_LOWERCASE = 1,
};
enum proxygen::HTTPHeaderCode : uint8_t
Codes (hashes) of common HTTP header names
Enumerator
HTTP_HEADER_NONE
HTTP_HEADER_OTHER
Definition at line 22 of file HTTPCommonHeaders.template.h.
                    : uint8_t {
  // code reserved to indicate the absence of an HTTP header
  HTTP_HEADER_NONE = 0,
  // code for any HTTP header name not in the list of common headers
  HTTP_HEADER_OTHER = 1,
  /* the following is a placeholder for the build script to generate a list
   * of enum values from the list in HTTPCommonHeaders.txt
   *
   * enum name of Some-Header is HTTP_HEADER_SOME_HEADER,
   * so an example fragment of the generated list could be:
   * ...
   * HTTP_HEADER_WARNING = 65,
   * HTTP_HEADER_WWW_AUTHENTICATE = 66,
   * HTTP_HEADER_X_BACKEND = 67,
   * HTTP_HEADER_X_BLOCKID = 68,
   * ...
   */
%%%%%
};
enum proxygen::HTTPMethod [strong]
See the definitions in RFC2616 5.1.1 for the source of this list. Today, proxygen only understands the methods defined in 5.1.1 and is not aware of any extension methods. If you wish to support extension methods, you must handle those separately from this enum.
Enumerator
GET
POST
OPTIONS
DELETE
HEAD
CONNECT
PUT
TRACE
PATCH
SUB
PUB
UNSUB
Definition at line 42 of file HTTPMethod.h.
                      {
  HTTP_METHOD_GEN(HTTP_METHOD_ENUM)
enum proxygen::ProxygenError
Enumerator
kErrorNone
kErrorMessage
kErrorConnect
kErrorConnectTimeout
kErrorRead
kErrorWrite
kErrorTimeout
kErrorHandshake
kErrorNoServer
kErrorMaxRedirects
kErrorInvalidRedirect
kErrorResponseAction
kErrorMaxConnects
kErrorDropped
kErrorConnection
kErrorConnectionReset
kErrorParseHeader
kErrorParseBody
kErrorEOF
kErrorClientRenegotiation
kErrorUnknown
kErrorBadDecompress
kErrorSSL
kErrorStreamAbort
kErrorStreamUnacknowledged
kErrorWriteTimeout
kErrorAddressPrivate
kErrorAddressFamilyNotSupported
kErrorDNSNoResults
kErrorMalformedInput
kErrorUnsupportedExpectation
kErrorMethodNotSupported
kErrorUnsupportedScheme
kErrorShutdown
kErrorIngressStateTransition
kErrorClientSilent
kErrorCanceled
kErrorParseResponse
kErrorConnRefused
kErrorDNSOtherServer
kErrorDNSOtherClient
kErrorDNSOtherCancelled
kErrorDNSshutdown
kErrorDNSgetaddrinfo
kErrorDNSthreadpool
kErrorDNSunimplemented
kErrorNetwork
kErrorConfiguration
kErrorEarlyDataRejected
kErrorEarlyDataFailed
kErrorAuthRequired
kErrorUnauthorized
kErrorMax
Definition at line 75 of file ProxygenErrorEnum.h.
                   {
  PROXYGEN_ERROR_GEN(PROXYGEN_ERROR_ENUM)
enum proxygen::SettingsId : uint64_t [strong]
Enumerator
HEADER_TABLE_SIZE
ENABLE_PUSH
MAX_CONCURRENT_STREAMS
INITIAL_WINDOW_SIZE
MAX_FRAME_SIZE
MAX_HEADER_LIST_SIZE
ENABLE_CONNECT_PROTOCOL
THRIFT_CHANNEL_ID_DEPRECATED
ENABLE_EX_HEADERS
THRIFT_CHANNEL_ID
SETTINGS_HTTP_CERT_AUTH
_SPDY_UPLOAD_BANDWIDTH
_SPDY_DOWNLOAD_BANDWIDTH
_SPDY_ROUND_TRIP_TIME
_SPDY_CURRENT_CWND
_SPDY_DOWNLOAD_RETRANS_RATE
_SPDY_CLIENT_CERTIFICATE_VECTOR_SIZE
_HQ_NUM_PLACEHOLDERS
_HQ_QPACK_BLOCKED_STREAMS
Definition at line 21 of file SettingsId.h.
                      : uint64_t {
  // From HTTP/2
  HEADER_TABLE_SIZE = 1,
  ENABLE_PUSH = 2,
  MAX_CONCURRENT_STREAMS = 3,
  INITIAL_WINDOW_SIZE = 4,
  MAX_FRAME_SIZE = 5,
  MAX_HEADER_LIST_SIZE = 6,
  ENABLE_CONNECT_PROTOCOL = 8,
  THRIFT_CHANNEL_ID_DEPRECATED = 100,
  // 0xf000 and 0xffff being reserved for Experimental Use
  ENABLE_EX_HEADERS = 0xfbfb,
  THRIFT_CHANNEL_ID = 0xf100,
  // For secondary authentication in HTTP/2
  SETTINGS_HTTP_CERT_AUTH = 0xff00,
  // From SPDY, mostly unused
  _SPDY_UPLOAD_BANDWIDTH = SPDY_SETTINGS_MASK | 1,
  _SPDY_DOWNLOAD_BANDWIDTH = SPDY_SETTINGS_MASK | 2,
  _SPDY_ROUND_TRIP_TIME = SPDY_SETTINGS_MASK | 3,
  // MAX_CONCURRENT_STREAMS = 4,
  _SPDY_CURRENT_CWND = SPDY_SETTINGS_MASK | 5,
  _SPDY_DOWNLOAD_RETRANS_RATE = SPDY_SETTINGS_MASK | 6,
  // INITIAL_WINDOW_SIZE = 7,
  _SPDY_CLIENT_CERTIFICATE_VECTOR_SIZE = SPDY_SETTINGS_MASK | 8,
  // From HQ
  //_HQ_HEADER_TABLE_SIZE = HQ_SETTINGS_MASK | 1, -- use HEADER_TABLE_SIZE
  _HQ_NUM_PLACEHOLDERS = HQ_SETTINGS_MASK | 3,
  //_HQ_MAX_HEADER_LIST_SIZE = HQ_SETTINGS_MASK | 6, -- use MAX_HEADER_LIST_SIZE
  _HQ_QPACK_BLOCKED_STREAMS = HQ_SETTINGS_MASK | 7,
};
enum proxygen::SPDYVersion [strong]
Enumerator
SPDY3
SPDY3_1
Definition at line 14 of file SPDYVersion.h.
{ SPDY3 = 0, SPDY3_1 };
enum proxygen::TransportDirection : uint8_t [strong]
Enumerator
DOWNSTREAM
UPSTREAM
Definition at line 17 of file TransportDirection.h.
                              : uint8_t {
  DOWNSTREAM, // toward the client
  UPSTREAM // toward the origin application or data
};
enum proxygen::UpgradeProtocol : int [strong]
Protocol to which the HTTPTransaction was upgraded
Enumerator
TCP
Definition at line 61 of file HTTPConstants.h.
                          : int {
  // We only support changing to TCP after CONNECT requests
  TCP
enum proxygen::ZlibCompressionType : int [strong]
Enumerator
NONE
DEFLATE
GZIP
Definition at line 25 of file ZlibStreamDecompressor.h.
                              : int {
  NONE = 0,
  DEFLATE = 15,
  GZIP = 31
};
enum proxygen::ZstdStatusType : int [strong]
Enumerator
NONE
SUCCESS
NODICT
CONTINUE
ERROR
Definition at line 28 of file ZstdStreamDecompressor.h.
                         : int {
  NONE,
  SUCCESS,
  NODICT,
  CONTINUE,
  ERROR,
 };
Function Documentation
proxygen::ACTION_P (ExpectString , expected)
Definition at line 404 of file HTTPSessionMocks.h.
                                 {
  std::string bodystr((const char*)arg0->data(), arg0->length());
  EXPECT_EQ(bodystr, expected);
}
proxygen::ACTION_P (ExpectBodyLen , expectedLen)
Definition at line 409 of file HTTPSessionMocks.h.
                                     {
  EXPECT_EQ(arg1->computeChainDataLength(), expectedLen);
}
std::string proxygen::base64Encode (folly::ByteRange text)
Definition at line 21 of file CryptUtil.cpp.
Referenced by TEST().
                                            {
  std::string result;
  BIO *b64 = BIO_new(BIO_f_base64());
  if (b64 == nullptr) {
    return result;
  }
  BIO *bmem = BIO_new(BIO_s_mem());
  if (bmem == nullptr) {
    BIO_free_all(b64);
    return result;
  }
  BUF_MEM *bptr;
  // chain base64 filter with the memory buffer
  // so that text will be encoded by base64 and flushed to buffer
  BIO *chain = BIO_push(b64, bmem);
  if (chain == nullptr) {
    BIO_free_all(b64);
    return result;
  }
  BIO_set_flags(chain, BIO_FLAGS_BASE64_NO_NL);
  BIO_write(chain, text.begin(), text.size());
  if (BIO_flush(chain) != 1) {
    BIO_free_all(chain);
    return result;
  }
  BIO_get_mem_ptr(chain, &bptr);
  if (bptr && bptr->length > 0) {
    result = std::string((char *)bptr->data, bptr->length);
  }
  // free the whole BIO chain (b64 and mem)
  BIO_free_all(chain);
  return result;
}
bool proxygen::caseInsensitiveEqual (folly::StringPiece s, folly::StringPiece t) [inline]
Definition at line 17 of file UtilInl.h.
Referenced by proxygen::HTTP1xCodec::generateHeader(), proxygen::SPDYCodec::isSPDYReserved(), proxygen::HTTP1xCodec::onHeadersComplete(), proxygen::SPDYCodec::parseHeaders(), proxygen::PerfectIndexMap< typename T::TKey, T::TOtherKey, T::TNoneKey, T::Hash, T::TAllowDuplicates, T::TCaseInsensitive >::searchForOtherKey(), stringToMethod(), and TEST().
                                                                         {
  if (s.size() != t.size()) {
    return false;
  }
  return std::equal(
      s.begin(), s.end(), t.begin(), folly::AsciiCaseInsensitive());
}
bool proxygen::caseUnderscoreInsensitiveEqual (folly::StringPiece s, folly::StringPiece t) [inline]
Definition at line 38 of file UtilInl.h.
                        {
  if (s.size() != t.size()) {
    return false;
  }
  bool result = std::equal(
      s.begin(), s.end(), t.begin(), AsciiCaseUnderscoreInsensitive());
  return result;
}
folly::Optional< std::pair< CodecProtocol, std::string > > proxygen::checkForProtocolUpgrade (const std::string & clientUpgrade, const std::string & serverUpgrade, bool serverMode)
Search the client and server protocol lists for a matching native CodecProtocol
Definition at line 91 of file CodecProtocol.cpp.
References getCodecProtocolFromStr(), proxygen::HTTPCodec::NoExAttributes, proxygen::HTTPCodec::NoPadding, and proxygen::HTTPCodec::NoStream.
Referenced by proxygen::HTTP1xCodec::onHeadersComplete().
                                         {
  CodecProtocol protocol;
  if (clientUpgrade.empty() || serverUpgrade.empty()) {
    return folly::none;
  }
  // Should be a comma separated list of protocols, like NPN
  std::vector<folly::StringPiece> clientProtocols;
  folly::split(",", clientUpgrade, clientProtocols, true /* ignore empty */);
  for (auto& clientProtocol: clientProtocols) {
    boost::algorithm::trim(clientProtocol);
  }
  // List of server chosen protocols in layer-ascending order. We can
  // only support one layer right now. We just skip anything that
  // isn't an HTTP transport protocol
  std::vector<folly::StringPiece> serverProtocols;
  folly::split(",", serverUpgrade, serverProtocols, true /* ignore empty */);
  for (auto& testProtocol: serverProtocols) {
    // Get rid of leading/trailing LWS
    boost::algorithm::trim(testProtocol);
    if (std::find(clientProtocols.begin(), clientProtocols.end(),
                  testProtocol) == clientProtocols.end()) {
      if (serverMode) {
        // client didn't offer this, try the next
        continue;
      } else {
        // The server returned a protocol the client didn't ask for
        return folly::none;
      }
    }
    protocol = getCodecProtocolFromStr(testProtocol);
    // Non-native upgrades get returned as HTTP_1_1/<actual protocol>
    return std::make_pair(protocol, testProtocol.str());
  }
  return folly::none;
}
void proxygen::dumpBinToFile (const string & filename, const IOBuf * buf)
Definition at line 133 of file Logging.cpp.
References ERROR, and proxygen::IOBufPrinter::printChainInfo().
Referenced by HTTPParallelCodecTest::dumpToFile(), and TEST_F().
                                                             {
  struct stat fstat;
  bool exists = (stat(filename.c_str(), &fstat) == 0);
  if (exists) {
    // don't write anything if the file exists
    return;
  }
  std::ofstream file(filename, std::ofstream::binary);
  if (!file.is_open()) {
    LOG(ERROR) << "cannot open file " << filename;
    return;
  }
  if (!buf) {
    file.close();
    return;
  }
  const IOBuf* first = buf;
  do {
    file.write((const char *)buf->data(), buf->length());
    buf = buf->next();
  } while (buf != first);
  file.close();
  LOG(INFO) << "wrote chain " << IOBufPrinter::printChainInfo(buf)
            << " to " << filename;
}
void proxygen::dumpBinToFile (const std::string & filename, const folly::IOBuf * buf)
write the entire binary content from all the buffers into a binary file
template<typename T > bool proxygen::durationInitialized (const T & duration)
Definition at line 29 of file Time.h.
References T.
                                            {
  static T zero(0);
  return duration != T::max() && duration >= zero;
}
void proxygen::fakeMockCodec (MockHTTPCodec & codec)
Definition at line 173 of file TestUtils.cpp.
References makeBuf().
Referenced by MATCHER_P(), and TEST_F().
                                         {
  // For each generate* function, write some data to the chain
  EXPECT_CALL(codec, generateHeader(_, _, _, _, _))
      .WillRepeatedly(Invoke(
          [](folly::IOBufQueue& writeBuf,
             HTTPCodec::StreamID /*stream*/,
             const HTTPMessage& /*msg*/,
             bool /*eom*/,
             HTTPHeaderSize* /*size*/) { writeBuf.append(makeBuf(10)); }));
  EXPECT_CALL(codec, generatePushPromise(_, _, _, _, _, _))
      .WillRepeatedly(Invoke(
          [](folly::IOBufQueue& writeBuf,
             HTTPCodec::StreamID /*stream*/,
             const HTTPMessage& /*msg*/,
             HTTPCodec::StreamID /*assocStream*/,
             bool /*eom*/,
             HTTPHeaderSize* /*size*/) { writeBuf.append(makeBuf(10)); }));
  EXPECT_CALL(codec, generateBody(_, _, _, _, _))
      .WillRepeatedly(Invoke([](folly::IOBufQueue& writeBuf,
                                HTTPCodec::StreamID /*stream*/,
                                std::shared_ptr<folly::IOBuf> chain,
                                folly::Optional<uint8_t> /*padding*/,
                                bool /*eom*/) {
        auto len = chain->computeChainDataLength();
        writeBuf.append(chain->clone());
        return len;
      }));
  EXPECT_CALL(codec, generateChunkHeader(_, _, _))
      .WillRepeatedly(Invoke([](folly::IOBufQueue& writeBuf,
                                HTTPCodec::StreamID /*stream*/,
                                size_t length) {
        writeBuf.append(makeBuf(length));
        return length;
      }));
  EXPECT_CALL(codec, generateChunkTerminator(_, _))
      .WillRepeatedly(Invoke(
          [](folly::IOBufQueue& writeBuf, HTTPCodec::StreamID /*stream*/) {
            writeBuf.append(makeBuf(4));
            return 4;
          }));
  EXPECT_CALL(codec, generateTrailers(_, _, _))
      .WillRepeatedly(Invoke([](folly::IOBufQueue& writeBuf,
                                HTTPCodec::StreamID /*stream*/,
                                const HTTPHeaders& /*trailers*/) {
        writeBuf.append(makeBuf(30));
        return 30;
      }));
  EXPECT_CALL(codec, generateEOM(_, _))
      .WillRepeatedly(Invoke(
          [](folly::IOBufQueue& writeBuf, HTTPCodec::StreamID /*stream*/) {
            writeBuf.append(makeBuf(6));
            return 6;
          }));
  EXPECT_CALL(codec, generateRstStream(_, _, _))
      .WillRepeatedly(Invoke([](folly::IOBufQueue& writeBuf,
                                HTTPCodec::StreamID /*stream*/,
                                ErrorCode /*code*/) {
        writeBuf.append(makeBuf(6));
        return 6;
      }));
  EXPECT_CALL(codec, generateGoaway(_, _, _, _))
      .WillRepeatedly(Invoke([](folly::IOBufQueue& writeBuf,
                                uint32_t /*lastStream*/,
                                ErrorCode,
                                std::shared_ptr<folly::IOBuf>) {
        writeBuf.append(makeBuf(6));
        return 6;
      }));
  EXPECT_CALL(codec, generatePingRequest(_))
    .WillRepeatedly(Invoke([] (folly::IOBufQueue& writeBuf) {
                             writeBuf.append(makeBuf(6));
                             return 6;
                           }));
  EXPECT_CALL(codec, generatePingReply(_, _))
      .WillRepeatedly(Invoke([](folly::IOBufQueue& writeBuf, uint64_t /*id*/) {
        writeBuf.append(makeBuf(6));
        return 6;
      }));
  EXPECT_CALL(codec, generateSettings(_))
    .WillRepeatedly(Invoke([] (folly::IOBufQueue& writeBuf) {
                             writeBuf.append(makeBuf(6));
                             return 6;
                           }));
  EXPECT_CALL(codec, generateWindowUpdate(_, _, _))
      .WillRepeatedly(Invoke([](folly::IOBufQueue& writeBuf,
                                HTTPCodec::StreamID /*stream*/,
                                uint32_t /*delta*/) {
        writeBuf.append(makeBuf(6));
        return 6;
      }));
  EXPECT_CALL(codec, generateCertificateRequest(_, _, _))
      .WillRepeatedly(Invoke([](folly::IOBufQueue& writeBuf,
                                uint16_t /*requestId*/,
                                std::shared_ptr<folly::IOBuf>) {
        writeBuf.append(makeBuf(6));
        return 6;
      }));
  EXPECT_CALL(codec, generateCertificate(_, _, _))
      .WillRepeatedly(Invoke([](folly::IOBufQueue& writeBuf,
                                uint16_t /*certId*/,
                                std::shared_ptr<folly::IOBuf>) {
        writeBuf.append(makeBuf(6));
        return 6;
      }));
}
HTTPMessage proxygen::getBigGetRequest (const std::string & url)
Definition at line 85 of file TestUtils.cpp.
References proxygen::HTTPHeaders::add(), proxygen::HTTPMessage::getHeaders(), proxygen::http2::kMaxFramePayloadLengthMin, proxygen::HTTPHeaders::set(), proxygen::HTTPMessage::setHTTPVersion(), proxygen::HTTPMessage::setMethod(), and proxygen::HTTPMessage::setURL().
Referenced by MATCHER_P(), TEST_F(), and HTTP2CodecTest::testFrameSizeLimit().
                                                   {
  HTTPMessage req;
  req.setMethod("GET");
  req.setURL(url);
  req.setHTTPVersion(1, 1);
  req.getHeaders().set(HTTP_HEADER_HOST, "www.foo.com");
  req.getHeaders().add(HTTP_HEADER_USER_AGENT, "coolio");
  req.getHeaders().add(
      "x-huge-header",
      std::string(http2::kMaxFramePayloadLengthMin, '!'));
  return req;
}
HTTPMessage proxygen::getChunkedPostRequest ()
Definition at line 113 of file TestUtils.cpp.
References proxygen::HTTPMessage::getHeaders(), proxygen::HTTPHeaders::set(), proxygen::HTTPMessage::setHTTPVersion(), proxygen::HTTPMessage::setIsChunked(), proxygen::HTTPMessage::setMethod(), and proxygen::HTTPMessage::setURL().
Referenced by MATCHER_P().
                                    {
  HTTPMessage req;
  req.setMethod("POST");
  req.setURL<string>("/");
  req.setHTTPVersion(1, 1);
  req.setIsChunked(true);
  req.getHeaders().set(HTTP_HEADER_HOST, "www.foo.com");
  req.getHeaders().set(HTTP_HEADER_TRANSFER_ENCODING, "chunked");
  return req;
}
CodecProtocol proxygen::getCodecProtocolFromStr (const std::string & protocolStr)
Get the protocol from the given debugging name. If it's an invalid string, return the default protocol.
Definition at line 69 of file CodecProtocol.cpp.
Referenced by checkForProtocolUpgrade().
                                                                           {
  return getCodecProtocolFromStr(folly::StringPiece(protocolStr));
}
const std::string & proxygen::getCodecProtocolString (CodecProtocol)
Returns a debugging name to refer to the given protocol.
Definition at line 47 of file CodecProtocol.cpp.
References HQ, HTTP_1_1, HTTP_2, SPDY_3, and SPDY_3_1.
Referenced by proxygen::HTTPSession::describe(), proxygen::HTTPSession::newExTransaction(), HTTPTargetSessionAcceptor::onCreate(), and proxygen::HTTP1xCodec::onHeadersComplete().
                                                                    {
  switch (proto) {
    case CodecProtocol::HTTP_1_1: return http_1_1;
    case CodecProtocol::SPDY_3: return spdy_3;
    case CodecProtocol::SPDY_3_1: return spdy_3_1;
    case CodecProtocol::HTTP_2: return http_2;
    case CodecProtocol::HQ: return hq;
  }
  LOG(FATAL) << "Unreachable";
  return empty;
}
const char * proxygen::getConnectionCloseReasonString (ConnectionCloseReason r)
Definition at line 28 of file HTTPConstants.cpp.
                                                                    {
  return connectionCloseStrings[(unsigned int)r];
}
const char * proxygen::getConnectionCloseReasonStringByIndex (unsigned int index)
Definition at line 20 of file HTTPConstants.cpp.
References kMAX_REASON.
                                                                      {
  if (index >= (unsigned int)ConnectionCloseReason::kMAX_REASON) {
    index = (unsigned int)ConnectionCloseReason::kMAX_REASON - 1;
  }
  return connectionCloseStrings[index];
}
template<typename ClockType = SteadyClock> std::chrono::time_point<ClockType> proxygen::getCurrentTime () [inline]
Definition at line 41 of file Time.h.
Referenced by TestAsyncTransport::addReadError(), proxygen::HTTPConnector::connect(), proxygen::HTTPConnector::connectSSL(), proxygen::HTTPConnector::connectSuccess(), TestAsyncTransport::fireNextReadEvent(), proxygen::HTTPTransaction::maybeDelayForRateLimit(), proxygen::compress::SimStreamingCallback::maybeMarkHolDelay(), TestAsyncTransport::WriteEvent::newEvent(), proxygen::HTTPSession::onPingRequest(), proxygen::HTTPTransaction::setEgressRateLimit(), proxygen::HTTPSessionBase::setLatestActive(), TestAsyncTransport::setReadCB(), TestAsyncTransport::startReadEvents(), TEST(), and TEST_F().
                                                       {
  return ClockType::now();
}
void proxygen::getDateOffsetStr (char datebuf[32], int dayOffset) [inline]
Get the current date + offset days in Y-m-d format.
Definition at line 129 of file Time.h.
References toTimeT().
                                                              {
  time_t t = toTimeT(getCurrentTime<SteadyClock>());
  t += dayOffset * 24 * 60 * 60;
  struct tm final_tm;
  localtime_r(&t, &final_tm);
  strftime(datebuf, sizeof(char) * 32, "%Y-%m-%d", &final_tm);
}
std::string proxygen::getDateTimeStr (const ASN1_TIME *const time)
Helper method to convert to OpenSSL type ASN1_TIME to a printable date and time string.
Parameters
time a pointer to the ASN1_TIME instance to be converted.
Returns
a human readable date and time string for the openssl type ASN1_TIME. If there is any error, returns empty string.
Definition at line 17 of file Time.cpp.
Referenced by getDateTimeStr(), and TEST().
                                                      {
  if (!time) {
    return "";
  }
  constexpr auto bufSize = 32;
  char buf[bufSize] = {0};
  auto bio = BIO_new(BIO_s_mem());
  if (!bio) {
    return "";
  }
  ASN1_TIME_print(bio, time);
  const auto readResult = BIO_read(bio, buf, bufSize - 1);
  BIO_free(bio);
  return ((readResult <= 0) ? "" : std::string(buf));
}
void proxygen::getDateTimeStr (char datebuf[32], char timebuf[32]) [inline]
Get the current date and time in string formats: Y-m-d and H:M:S.
Definition at line 114 of file Time.h.
References toTimeT().
                                                               {
  time_t now = toTimeT(getCurrentTime<SteadyClock>());
  struct tm now_tm;
  localtime_r(&now, &now_tm);
  if (datebuf) {
    strftime(datebuf, sizeof(char) * 32, "%Y-%m-%d", &now_tm);
  }
  if (timebuf) {
    strftime(timebuf, sizeof(char) * 32, "%H:%M:%S", &now_tm);
  }
}
std::string proxygen::getDateTimeStr (TimePoint tp) [inline]
Helper method to convert TimePoint to a printable date and time string. It will convert static time to system time.
Parameters
time TimePoint
Returns
a human readable date and time string at UTC timezone. If there is any error, returns empty string.
Definition at line 145 of file Time.h.
References getDateTimeStr(), and toTimeT().
                                              {
  time_t t = toTimeT(tp);
  struct tm final_tm;
  gmtime_r(&t, &final_tm);
  char buf[256];
  if (strftime(buf, sizeof(buf), "%Y-%m-%dT%H:%M:%S %z", &final_tm) > 0) {
    return std::string(buf);
  }
  return "";
}
const char * proxygen::getErrorCodeString (ErrorCode error)
Returns a string representation of the error code.
Definition at line 18 of file ErrorCode.cpp.
References _SPDY_INVALID_STREAM, CANCEL, COMPRESSION_ERROR, CONNECT_ERROR, ENHANCE_YOUR_CALM, FLOW_CONTROL_ERROR, FRAME_SIZE_ERROR, HTTP_1_1_REQUIRED, INADEQUATE_SECURITY, INTERNAL_ERROR, NO_ERROR, PROTOCOL_ERROR, REFUSED_STREAM, SETTINGS_TIMEOUT, and STREAM_CLOSED.
Referenced by proxygen::HTTP2Codec::checkConnectionError(), proxygen::SPDYCodec::generateGoaway(), proxygen::HTTP2Codec::generateGoaway(), proxygen::SPDYCodec::generateRstStream(), proxygen::HTTP2Codec::generateRstStream(), proxygen::HTTPCodecPrinter::onAbort(), proxygen::HTTPSession::onAbort(), proxygen::HTTPCodecPrinter::onGoaway(), proxygen::HTTPSession::onGoaway(), operator<<(), proxygen::HTTP2Codec::parseGoaway(), and proxygen::HTTP2Codec::parseRstStream().
                                                {
  switch (error) {
    case ErrorCode::NO_ERROR: return "NO_ERROR";
    case ErrorCode::PROTOCOL_ERROR: return "PROTOCOL_ERROR";
    case ErrorCode::INTERNAL_ERROR: return "INTERNAL_ERROR";
    case ErrorCode::FLOW_CONTROL_ERROR: return "FLOW_CONTROL_ERROR";
    case ErrorCode::SETTINGS_TIMEOUT: return "SETTINGS_TIMEOUT";
    case ErrorCode::STREAM_CLOSED: return "STREAM_CLOSED";
    case ErrorCode::FRAME_SIZE_ERROR: return "FRAME_SIZE_ERROR";
    case ErrorCode::REFUSED_STREAM: return "REFUSED_STREAM";
    case ErrorCode::CANCEL: return "CANCEL";
    case ErrorCode::COMPRESSION_ERROR: return "COMPRESSION_ERROR";
    case ErrorCode::CONNECT_ERROR: return "CONNECT_ERROR";
    case ErrorCode::ENHANCE_YOUR_CALM: return "ENHANCE_YOUR_CALM";
    case ErrorCode::INADEQUATE_SECURITY: return "INADEQUATE_SECURITY";
    case ErrorCode::HTTP_1_1_REQUIRED: return "HTTP_1_1_REQUIRED";
    case ErrorCode::_SPDY_INVALID_STREAM: return "_SPDY_INVALID_STREAM";
  }
  LOG(FATAL) << "Unreachable";
  return "";
}
const char * proxygen::getErrorString (ProxygenError error)
Definition at line 25 of file ProxygenErrorEnum.cpp.
References kErrorMax.
Referenced by proxygen::HTTPSession::errorOnTransactionIds(), ProxyService::ProxyHandler::onError(), proxygen::HTTPSession::onGoaway(), operator<<(), and proxygen::HTTPSession::shutdownTransport().
                                                {
  if (error < kErrorNone || error >= kErrorMax) {
    return errorStrings[kErrorMax];
  } else {
    return errorStrings[error];
  }
}
const char * proxygen::getErrorStringByIndex (int i)
Definition at line 33 of file ProxygenErrorEnum.cpp.
                                         {
  return errorStrings[i];
}
HTTPMessage proxygen::getGetRequest (const std::string & url)
Definition at line 76 of file TestUtils.cpp.
References proxygen::HTTPMessage::getHeaders(), proxygen::HTTPHeaders::set(), proxygen::HTTPMessage::setHTTPVersion(), proxygen::HTTPMessage::setMethod(), and proxygen::HTTPMessage::setURL().
Referenced by getUpgradeRequest(), makeGetRequest(), MATCHER_P(), proxygen::HTTPHandlerBase::sendRequest(), HTTPDownstreamTest< SPDY3_1CodecPair >::sendRequest(), TEST(), TEST_F(), HTTPUpstreamTest< C >::testBasicRequestHttp10(), HTTP2CodecTest::testHeaderListSize(), and TYPED_TEST_P().
                                                {
  HTTPMessage req;
  req.setMethod("GET");
  req.setURL(url);
  req.setHTTPVersion(1, 1);
  req.getHeaders().set(HTTP_HEADER_HOST, "www.foo.com");
  return req;
}
HTTPMessage proxygen::getPostRequest (uint32_t contentLength)
Definition at line 102 of file TestUtils.cpp.
References proxygen::HTTPMessage::getHeaders(), proxygen::HTTPHeaders::set(), proxygen::HTTPMessage::setHTTPVersion(), proxygen::HTTPMessage::setMethod(), and proxygen::HTTPMessage::setURL().
Referenced by TestPriorityMapBuilder::createVirtualStreams(), TestAbortPost< stage >::doAbortTest(), makePostRequest(), MATCHER_P(), and TEST_F().
                                                   {
  HTTPMessage req;
  req.setMethod("POST");
  req.setURL<string>("/");
  req.setHTTPVersion(1, 1);
  req.getHeaders().set(HTTP_HEADER_HOST, "www.foo.com");
  req.getHeaders().set(HTTP_HEADER_CONTENT_LENGTH,
                       folly::to<string>(contentLength));
  return req;
}
std::unique_ptr< HTTPMessage > proxygen::getPriorityMessage (uint8_t priority)
Definition at line 29 of file TestUtils.cpp.
References proxygen::spdy::kVersionStrv2.
Referenced by MATCHER_P().
                                                                {
  auto ret = std::make_unique<HTTPMessage>();
  ret->setAdvancedProtocolString(spdy::kVersionStrv2);
  ret->setPriority(priority);
  return ret;
}
HTTPMessage proxygen::getPubRequest (const std::string & url)
Definition at line 128 of file TestUtils.cpp.
References proxygen::HTTPMessage::getHeaders(), proxygen::HTTPHeaders::set(), proxygen::HTTPMessage::setHTTPVersion(), proxygen::HTTPMessage::setMethod(), and proxygen::HTTPMessage::setURL().
Referenced by MATCHER_P().
                                                {
  HTTPMessage req;
  req.setMethod("PUB");
  req.setURL(url);
  req.setHTTPVersion(1, 1);
  req.getHeaders().set(HTTP_HEADER_HOST, "www.foo.com");
  return req;
}
HTTPMessage proxygen::getResponse (uint32_t code, uint32_t bodyLen)
Definition at line 137 of file TestUtils.cpp.
References proxygen::HTTPMessage::getHeaders(), proxygen::HTTPHeaders::set(), and proxygen::HTTPMessage::setStatusCode().
Referenced by TestPriorityMapBuilder::createVirtualStreams(), MATCHER_P(), and TEST_F().
                                                         {
  HTTPMessage resp;
  resp.setStatusCode(code);
  if (bodyLen > 0) {
    resp.getHeaders().set(HTTP_HEADER_CONTENT_LENGTH,
                          folly::to<string>(bodyLen));
  }
  return resp;
}
AsyncTimeoutSet::TimeoutClock& proxygen::getTimeoutClock ()
Definition at line 26 of file AsyncTimeoutSet.cpp.
Referenced by proxygen::AsyncTimeoutSet::Callback::cancelTimeoutImpl().
                                               {
  static SimpleTimeoutClock timeoutClock;
  return timeoutClock;
}
const char * proxygen::getTransportDirectionString (TransportDirection dir)
Definition at line 16 of file TransportDirection.cpp.
References DOWNSTREAM, and UPSTREAM.
Referenced by proxygen::HTTP2Codec::generateSettings(), proxygen::HTTP2Codec::generateSettingsAck(), proxygen::HTTP2Codec::handleSettings(), proxygen::HTTP2Codec::HTTP2Codec(), and operator<<().
                                                                {
  switch (dir) {
    case TransportDirection::UPSTREAM: return "upstream";
    case TransportDirection::DOWNSTREAM: return "downstream";
  }
  // unreachable
  return "";
}
HTTPMessage proxygen::getUpgradeRequest (const std::string & upgradeHeader, HTTPMethod method, uint32_t bodyLen)
Definition at line 161 of file TestUtils.cpp.
References getGetRequest(), proxygen::HTTPMessage::getHeaders(), proxygen::HTTPHeaders::set(), and proxygen::HTTPMessage::setMethod().
Referenced by MATCHER_P(), TEST_F(), HTTPDownstreamTest< C >::testSimpleUpgrade(), and HTTPUpstreamTest< C >::testSimpleUpgrade().
                                                                   {
  HTTPMessage req = getGetRequest();
  req.setMethod(method);
  req.getHeaders().set(HTTP_HEADER_UPGRADE, upgradeHeader);
  if (bodyLen > 0) {
    req.getHeaders().set(HTTP_HEADER_CONTENT_LENGTH,
                         folly::to<std::string>(bodyLen));
  }
  return req;
}
inline ::testing::Matcher<HTTPHeaders&> proxygen::HasHTTPHeader (std::string name)
Definition at line 80 of file MockHTTPHeaders.h.
References proxygen::HasHTTPHeaderMatcherImpl::HasHTTPHeaderMatcherImpl().
                              {
  return ::testing::MakeMatcher(new HasHTTPHeaderMatcherImpl(name));
}
inline ::testing::Matcher<HTTPHeaders&> proxygen::HasHTTPHeader (std::string name, std::string value)
Definition at line 88 of file MockHTTPHeaders.h.
References proxygen::HasHTTPHeaderMatcherImpl::HasHTTPHeaderMatcherImpl().
                                               {
  return ::testing::MakeMatcher(new HasHTTPHeaderMatcherImpl(name, value));
}
string proxygen::hexStr (StringPiece sp)
Definition at line 48 of file Logging.cpp.
Referenced by TEST_F().
                              {
  string out;
  for (auto ch : sp) {
    out.append(folly::sformat("{:02x}", (uint8_t) ch));
  }
  return out;
}
std::string proxygen::hexStr (folly::StringPiece sp)
helper functions for printing in hex a byte array see unit test for example
[INSTANTIATE_TEST_CASE_P(ValueTest, RFC1867CR,::testing::Values(string(""zyx\r\nwvu"", 8), string(""\rzyxwvut"", 8), string(""zyxwvut\r"", 8), string(""\nzyxwvut"", 8), string(""zyxwvut\n"", 8), string(""\r\n\r\n\r\n\r\n"", 8), string(""\r\r\r\r\r\r\r\r"", 8)))]proxygen::INSTANTIATE_TEST_CASE_P (ValueTest , RFC1867CR , [::testing::Values(string(`zyx\r\nwvu`, 8), string(`\rzyxwvut`, 8), string(`zyxwvut\r`, 8), string(`\nzyxwvut`, 8), string(`zyxwvut\n`, 8), string(`\r\n\r\n\r\n\r\n`, 8), string(`\r\r\r\r\r\r\r\r`, 8))])
Referenced by TEST_P(), and TEST_P().
proxygen::INSTANTIATE_TEST_CASE_P (TestLegalStrings , LegalStringTests , ::testing::ValuesIn(kLegalStringTests))
proxygen::INSTANTIATE_TEST_CASE_P (TestLegalBinaryContent , LegalBinaryContentTests , ::testing::ValuesIn(kLegalBinContentTests))
proxygen::INSTANTIATE_TEST_CASE_P (TestLegalInts , LegalIntegerTests , ::testing::ValuesIn(kLegalIntTests))
proxygen::INSTANTIATE_TEST_CASE_P (TestLegalFloats , LegalFloatTests , ::testing::ValuesIn(kLegalFloatTests))
proxygen::INSTANTIATE_TEST_CASE_P (TestIllegalItems , IllegalItemTest , ::testing::ValuesIn(kIllegalItemTests))
proxygen::INSTANTIATE_TEST_CASE_P (TestIllegalLists , IllegalListTest , ::testing::ValuesIn(kIllegalListTests))
bool proxygen::isHQCodecProtocol (CodecProtocol protocol)
Check if the given protocol is HQ
Definition at line 82 of file CodecProtocol.cpp.
References HQ.
                                                      {
  return protocol == CodecProtocol::HQ;
}
bool proxygen::isHTTP2CodecProtocol (CodecProtocol protocol)
Check if the given protocol is HTTP2.
Definition at line 78 of file CodecProtocol.cpp.
References HTTP_2.
Referenced by proxygen::HTTPSessionBase::initCodecHeaderIndexingStrategy(), isParallelCodecProtocol(), proxygen::HTTPSession::onSessionParseError(), proxygen::HTTPSession::sendEOM(), and proxygen::HTTPSession::WriteSegment::writeErr().
                                                         {
  return protocol == CodecProtocol::HTTP_2;
}
bool proxygen::isLWS (char c) [inline]
Return true if the character is linear whitespace, as defined by the LWS definition in RFC 2616, and false otherwise
Definition at line 31 of file HTTPHeaders.h.
Referenced by proxygen::HTTPMessage::doHeaderTokenCheck(), and proxygen::HTTPHeaders::stripPerHopHeaders().
                          {
  // Technically \r and \n are only allowed in LWS if they appear together.
  if (c == ' ' || c == '\t' || c == '\r' || c == '\n') {
    return true;
  }
  return false;
}
bool proxygen::isParallelCodecProtocol (CodecProtocol protocol)
Check if the given protocol supports paraellel requests
Definition at line 86 of file CodecProtocol.cpp.
References isHTTP2CodecProtocol(), and isSpdyCodecProtocol().
Referenced by HTTPDownstreamTest< SPDY3_1CodecPair >::expectResponses().
                                                            {
  return isSpdyCodecProtocol(protocol) || isHTTP2CodecProtocol(protocol);
}
FB_EXPORT bool proxygen::isSpdyCodecProtocol (CodecProtocol protocol)
Check if the given protocol is SPDY.
Definition at line 73 of file CodecProtocol.cpp.
References SPDY_3, and SPDY_3_1.
Referenced by proxygen::HTTPSession::getNextToSend(), and isParallelCodecProtocol().
                                                        {
  return protocol == CodecProtocol::SPDY_3 ||
         protocol == CodecProtocol::SPDY_3_1;
}
bool proxygen::isValidCodecProtocolStr (const std::string & protocolStr)
Check if given debugging name refers to a valid protocol.
Definition at line 59 of file CodecProtocol.cpp.
References proxygen::http2::kProtocolCleartextString, and proxygen::http2::kProtocolString.
                                                                  {
  return protocolStr == http_1_1 ||
         protocolStr == spdy_3 ||
         protocolStr == spdy_3_1 ||
         protocolStr == http2::kProtocolString ||
         protocolStr == http2::kProtocolCleartextString ||
         protocolStr == http_2 ||
         protocolStr == hq;
}
std::unique_ptr< folly::IOBuf > proxygen::makeBuf (uint32_t size)
Definition at line 36 of file TestUtils.cpp.
Referenced by MATCHER_P(), FlowControlFilterTest< initSize >::SetUp(), DownstreamTransactionTest::setupRequestResponseFlow(), and TEST_F().
                                                 {
  auto out = folly::IOBuf::create(size);
  out->append(size);
  // fill with random junk
  RWPrivateCursor cursor(out.get());
  while (cursor.length() >= 8) {
    cursor.write<uint64_t>(folly::Random::rand64());
  }
  while (cursor.length()) {
    cursor.write<uint8_t>((uint8_t)folly::Random::rand32());
  }
  return out;
}
std::unique_ptr< testing::NiceMock< MockHTTPCodec > > proxygen::makeDownstreamParallelCodec ()
Definition at line 67 of file TestUtils.cpp.
References makeMockParallelCodec().
Referenced by MATCHER_P(), and TEST().
                              {
  return makeMockParallelCodec(TransportDirection::DOWNSTREAM);
}
std::unique_ptr< HTTPMessage > proxygen::makeGetRequest ()
Definition at line 98 of file TestUtils.cpp.
References getGetRequest().
Referenced by MATCHER_P(), TEST_F(), MockCodecDownstreamTest::testConnFlowControlBlocked(), and MockCodecDownstreamTest::testGoaway().
                                            {
  return std::make_unique<HTTPMessage>(getGetRequest());
}
folly::HHWheelTimer::UniquePtr proxygen::makeInternalTimeoutSet (EventBase * evb)
Definition at line 22 of file TestUtils.cpp.
Referenced by TEST().
                                                                  {
  folly::HHWheelTimer::UniquePtr t(folly::HHWheelTimer::newTimer(
      evb,
      std::chrono::milliseconds(folly::HHWheelTimer::DEFAULT_TICK_INTERVAL),
      TimeoutManager::InternalEnum::INTERNAL,
      std::chrono::milliseconds(500)));
  return t;
}
folly::HHWheelTimer::UniquePtr proxygen::makeInternalTimeoutSet (folly::EventBase * evb)
std::unique_ptr<testing::NiceMock<MockHTTPCodec> > proxygen::makeMockParallelCodec (TransportDirection dir)
Definition at line 51 of file TestUtils.cpp.
References kDefaultIngressSettings.
Referenced by makeDownstreamParallelCodec(), and makeUpstreamParallelCodec().
                                              {
  auto codec = std::make_unique<testing::NiceMock<MockHTTPCodec>>();
  EXPECT_CALL(*codec, supportsParallelRequests())
    .WillRepeatedly(testing::Return(true));
  EXPECT_CALL(*codec, getProtocol())
    .WillRepeatedly(testing::Return(CodecProtocol::SPDY_3_1));
  EXPECT_CALL(*codec, isReusable())
    .WillRepeatedly(testing::Return(true));
  EXPECT_CALL(*codec, getTransportDirection())
    .WillRepeatedly(testing::Return(dir));
  EXPECT_CALL(*codec, getIngressSettings())
    .WillRepeatedly(testing::Return(&kDefaultIngressSettings));
  return codec;
}
std::unique_ptr< HTTPMessage > proxygen::makePostRequest (uint32_t contentLength)
Definition at line 124 of file TestUtils.cpp.
References getPostRequest().
Referenced by MATCHER_P(), and TEST_F().
                                                                   {
  return std::make_unique<HTTPMessage>(getPostRequest(contentLength));
}
std::unique_ptr< HTTPMessage > proxygen::makeResponse (uint16_t statusCode)
Definition at line 147 of file TestUtils.cpp.
Referenced by TestAbortPost< stage >::doAbortTest(), MATCHER_P(), DownstreamTransactionTest::setupRequestResponseFlow(), TEST_F(), and MockCodecDownstreamTest::testConnFlowControlBlocked().
                                                             {
  auto resp = std::make_unique<HTTPMessage>();
  resp->setStatusCode(statusCode);
  resp->setHTTPVersion(1, 1);
  return resp;
}
std::tuple< std::unique_ptr< HTTPMessage >, std::unique_ptr< folly::IOBuf > > proxygen::makeResponse (uint16_t statusCode, size_t len)
Definition at line 155 of file TestUtils.cpp.
References makeBuf().
                                              {
  auto resp = makeResponse(statusCode);
  resp->getHeaders().set(HTTP_HEADER_CONTENT_LENGTH, folly::to<string>(len));
  return std::make_pair(std::move(resp), makeBuf(len));
}
folly::HHWheelTimer::UniquePtr proxygen::makeTimeoutSet (EventBase * evb)
Definition at line 31 of file TestUtils.cpp.
Referenced by HTTPDownstreamTest< SPDY3_1CodecPair >::HTTPDownstreamTest().
                                                          {
  folly::HHWheelTimer::UniquePtr t(folly::HHWheelTimer::newTimer(
      evb,
      std::chrono::milliseconds(folly::HHWheelTimer::DEFAULT_TICK_INTERVAL),
      folly::AsyncTimeout::InternalEnum::NORMAL,
      std::chrono::milliseconds(500)));
  return t;
}
folly::HHWheelTimer::UniquePtr proxygen::makeTimeoutSet (folly::EventBase * evb)
std::unique_ptr< testing::NiceMock< MockHTTPCodec > > proxygen::makeUpstreamParallelCodec ()
Definition at line 72 of file TestUtils.cpp.
References makeMockParallelCodec().
Referenced by MATCHER_P().
                            {
  return makeMockParallelCodec(TransportDirection::UPSTREAM);
}
proxygen::MATCHER_P (PtrBufHasLen , n , ``)
Definition at line 410 of file TestUtils.h.
References fakeMockCodec(), GET, getBigGetRequest(), getChunkedPostRequest(), getGetRequest(), getPostRequest(), getPriorityMessage(), getPubRequest(), getResponse(), getUpgradeRequest(), makeBuf(), makeDownstreamParallelCodec(), makeGetRequest(), makePostRequest(), makeResponse(), makeUpstreamParallelCodec(), proxygen::FakeHTTPCodecCallback::priority, and statusCode.
                               {
  return arg->computeChainDataLength() == n;
}
std::string proxygen::md5Encode (folly::ByteRange text)
Definition at line 60 of file CryptUtil.cpp.
Referenced by TEST().
                                         {
  static_assert(MD5_DIGEST_LENGTH == 16, "");
  unsigned char digest[MD5_DIGEST_LENGTH];
  MD5(text.begin(), text.size(), digest);
  // convert digest to hex string
  std::ostringstream ss;
  ss << std::hex << std::setfill('0');
  for(int i = 0; i < MD5_DIGEST_LENGTH; i++) {
    ss << std::setw(2) << (unsigned int)digest[i];
  }
  return ss.str();
}
const std::string & proxygen::methodToString (HTTPMethod method)
Returns a string representation of the method. If EXTENSION_METHOD is passed, then an empty string is returned
Definition at line 46 of file HTTPMethod.cpp.
Referenced by proxygen::HTTP1xCodec::generateHeader(), proxygen::HTTPMessage::getMethodString(), operator<<(), and proxygen::CodecUtil::prepareMessageForCompression().
                                                   {
  return getMethodStrings()[static_cast<unsigned>(method)];
}
template<typename ClockType = SteadyClock> std::chrono::microseconds proxygen::microsecondsBetween (std::chrono::time_point< ClockType > finish, std::chrono::time_point< ClockType > start) [inline]
Definition at line 77 of file Time.h.
                                          {
  return std::chrono::duration_cast<std::chrono::microseconds>(
    finish - start);
}
template<typename ClockType = SteadyClock> std::chrono::milliseconds proxygen::millisecondsBetween (std::chrono::time_point< ClockType > finish, std::chrono::time_point< ClockType > start) [inline]
Definition at line 85 of file Time.h.
Referenced by proxygen::HTTPTransaction::maybeDelayForRateLimit(), millisecondsSince(), proxygen::compress::CompressionSimulator::readInputFromFileAndSchedule(), and TEST_F().
                                          {
  return std::chrono::duration_cast<std::chrono::milliseconds>(
    finish - start);
}
template<typename ClockType = SteadyClock> std::chrono::milliseconds proxygen::millisecondsSince (std::chrono::time_point< ClockType > t) [inline]
Definition at line 101 of file Time.h.
References millisecondsBetween().
Referenced by proxygen::HTTPConnector::connectSuccess(), proxygen::HTTPSessionBase::getIdleTime(), proxygen::PingByteEvent::getLatency(), proxygen::compress::SimStreamingCallback::onHeadersComplete(), and proxygen::HTTPConnector::timeElapsed().
                                      {
  return millisecondsBetween(getCurrentTime<ClockType>(), t);
}
std::chrono::milliseconds proxygen::millisecondsSinceEpoch () [inline]
Definition at line 56 of file Time.h.
Referenced by proxygen::SimpleTimeoutClock::millisecondsSinceEpoch(), MockTimeoutClock::MockTimeoutClock(), proxygen::TimeUtilGeneric< ClockType >::msSinceEpoch(), TimeoutTest::setClock(), and proxygen::AsyncTimeoutSet::TimeoutClock::~TimeoutClock().
                                                      {
  return std::chrono::duration_cast<std::chrono::milliseconds>(
    std::chrono::system_clock::now().time_since_epoch());
}
std::chrono::milliseconds proxygen::millisecondsSinceEpoch (TimePoint t) [inline]
Definition at line 66 of file Time.h.
References toSystemTimePoint().
                                                                 {
  return std::chrono::duration_cast<std::chrono::milliseconds>(
    toSystemTimePoint(t).time_since_epoch());
}
testing::NiceMock<folly::test::MockAsyncTransport>* proxygen::newMockTransport (folly::EventBase * evb)
testing::NiceMock<MockAsyncTransport>* proxygen::newMockTransport (EventBase * evb)
Definition at line 40 of file TestUtils.cpp.
Referenced by TEST().
                                                                      {
  auto transport = new testing::NiceMock<MockAsyncTransport>();
  EXPECT_CALL(*transport, getEventBase())
    .WillRepeatedly(testing::Return(evb));
  return transport;
}
TransportDirection proxygen::operator! (TransportDirection dir)
Definition at line 25 of file TransportDirection.cpp.
References DOWNSTREAM, and UPSTREAM.
                                                     {
  return dir == TransportDirection::DOWNSTREAM ?
    TransportDirection::UPSTREAM : TransportDirection::DOWNSTREAM;
}
bool proxygen::operator< (const AcceptorAddress & lv, const AcceptorAddress & rv) [inline]
Definition at line 28 of file AcceptorAddress.h.
References proxygen::AcceptorAddress::address, and proxygen::AcceptorAddress::protocol.
                                                                            {
  if (lv.address < rv.address) {
    return true;
  }
  if (rv.address < lv.address) {
    return false;
  }
  return lv.protocol < rv.protocol;
}
std::ostream & proxygen::operator<< (std::ostream & os, const HPACKHeader & h)
Definition at line 14 of file HPACKHeader.cpp.
References proxygen::HPACKHeader::name, and proxygen::HPACKHeader::value.
                                                             {
  os << h.name << ": " << h.value;
  return os;
}
std::ostream & proxygen::operator<< (std::ostream & os, HTTPEvent::Type e)
Definition at line 16 of file HTTPEvent.cpp.
References proxygen::HTTPEvent::BODY, proxygen::HTTPEvent::CHUNK_COMPLETE, proxygen::HTTPEvent::CHUNK_HEADER, proxygen::HTTPEvent::HEADERS_COMPLETE, proxygen::HTTPEvent::MESSAGE_BEGIN, proxygen::HTTPEvent::MESSAGE_COMPLETE, proxygen::HTTPEvent::TRAILERS_COMPLETE, and proxygen::HTTPEvent::UPGRADE.
                                                        {
  switch (e) {
    case HTTPEvent::Type::MESSAGE_BEGIN:
      os << "message_begin";
      break;
    case HTTPEvent::Type::HEADERS_COMPLETE:
      os << "headers_complete";
      break;
    case HTTPEvent::Type::BODY:
      os << "body";
      break;
    case HTTPEvent::Type::CHUNK_HEADER:
      os << "chunk_header";
      break;
    case HTTPEvent::Type::CHUNK_COMPLETE:
      os << "chunk_complete";
      break;
    case HTTPEvent::Type::TRAILERS_COMPLETE:
      os << "trailers_complete";
      break;
    case HTTPEvent::Type::MESSAGE_COMPLETE:
      os << "message_complete";
      break;
    case HTTPEvent::Type::UPGRADE:
      os << "uprade";
      break;
  }
  return os;
}
FB_EXPORT std::ostream & proxygen::operator<< (std::ostream & os, TraceEventType eventType)
Definition at line 20 of file TraceEvent.cpp.
                                                                 {
  os << getTraceEventTypeString(eventType);
  return os;
}
std::ostream & proxygen::operator<< (ostream & os, const std::list< uint32_t > * refset)
Definition at line 21 of file Logging.cpp.
                                                                  {
  os << std::endl << '[';
  for (auto& ref : *refset) {
    os << ref << ' ';
  }
  os << ']' << std::endl;
  return os;
}
std::ostream & proxygen::operator<< (std::ostream & os, const ByteEvent & be)
Definition at line 23 of file ByteEvents.cpp.
References proxygen::ByteEvent::byteOffset_, and proxygen::ByteEvent::eventType_.
                                                            {
  os << folly::to<std::string>(
    "(", kTypeStrings[be.eventType_], ", ", be.byteOffset_, ")");
  return os;
}
std::ostream & proxygen::operator<< (std::ostream & os, const HTTPException & ex)
Definition at line 24 of file HTTPException.cpp.
References proxygen::HTTPException::getCodecStatusCode(), proxygen::HTTPException::getDirection(), getErrorCodeString(), getErrorString(), proxygen::HTTPException::getHttpStatusCode(), proxygen::Exception::getProxygenError(), proxygen::HTTPException::hasCodecStatusCode(), and proxygen::Exception::what().
                                                                {
  os << "what=\"" << ex.what()
     << "\", direction=" << static_cast<int>(ex.getDirection())
     << ", proxygenError=" << getErrorString(ex.getProxygenError())
     << ", codecStatusCode=" << (ex.hasCodecStatusCode() ?
                                 getErrorCodeString(ex.getCodecStatusCode()) :
                                 "-1")
     << ", httpStatusCode=" << ex.getHttpStatusCode();
  return os;
}
FB_EXPORT std::ostream & proxygen::operator<< (std::ostream & os, TraceFieldType fieldType)
Definition at line 25 of file TraceEvent.cpp.
                                                                 {
  os << getTraceFieldTypeString(fieldType);
  return os;
}
std::ostream & proxygen::operator<< (std::ostream & os, const TransportDirection dir)
Definition at line 30 of file TransportDirection.cpp.
References getTransportDirectionString().
                                                                     {
  os << getTransportDirectionString(dir);
  return os;
}
std::ostream & proxygen::operator<< (std::ostream & os, const std::vector< HPACKHeader > & v)
Definition at line 30 of file Logging.cpp.
                                                                        {
  for (const auto &h : v) {
    os << h.name << ": " << h.value << std::endl;
  }
  os << std::endl;
  return os;
}
std::ostream& proxygen::operator<< (std::ostream & os, const AcceptorAddress::AcceptorType & accType) [inline]
Definition at line 38 of file AcceptorAddress.h.
References proxygen::AcceptorAddress::TCP, and proxygen::AcceptorAddress::UDP.
                                                                            {
  switch (accType) {
    case AcceptorAddress::AcceptorType::TCP:
      os << "TCP";
      break;
    case AcceptorAddress::AcceptorType::UDP:
      os << "UDP";
      break;
    default:
      LOG(FATAL) << "Unknown Acceptor type.";
  }
  return os;
}
std::ostream & proxygen::operator<< (std::ostream & os, const QPACKContext & context)
Definition at line 43 of file QPACKContext.cpp.
References proxygen::QPACKContext::describe().
                                                                    {
  context.describe(os);
  return os;
}
std::ostream & proxygen::operator<< (std::ostream & out, HTTPMethod method)
Definition at line 50 of file HTTPMethod.cpp.
References methodToString().
                                                            {
  out << methodToString(method);
  return out;
}
std::ostream& proxygen::operator<< (std::ostream & os, const AcceptorAddress & accAddr) [inline]
Definition at line 53 of file AcceptorAddress.h.
References proxygen::AcceptorAddress::address, and proxygen::AcceptorAddress::protocol.
                                                                {
  os << accAddr.address << "<" << accAddr.protocol << ">";
  return os;
}
std::ostream & proxygen::operator<< (std::ostream & os, const QPACKCodec & codec)
Definition at line 75 of file QPACKCodec.cpp.
References proxygen::QPACKCodec::describe().
                                                                {
  codec.describe(os);
  return os;
}
std::ostream & proxygen::operator<< (std::ostream & os, HTTPTransactionEgressSMData::State s)
Definition at line 77 of file HTTPTransactionEgressSM.cpp.
References proxygen::HTTPTransactionEgressSMData::ChunkBodySent, proxygen::HTTPTransactionEgressSMData::ChunkHeaderSent, proxygen::HTTPTransactionEgressSMData::ChunkTerminatorSent, proxygen::HTTPTransactionEgressSMData::EOMQueued, proxygen::HTTPTransactionEgressSMData::HeadersSent, proxygen::HTTPTransactionEgressSMData::RegularBodySent, proxygen::HTTPTransactionEgressSMData::SendingDone, proxygen::HTTPTransactionEgressSMData::Start, and proxygen::HTTPTransactionEgressSMData::TrailersSent.
                                                             {
  switch (s) {
    case HTTPTransactionEgressSMData::State::Start:
      os << "Start";
      break;
    case HTTPTransactionEgressSMData::State::HeadersSent:
      os << "HeadersSent";
      break;
    case HTTPTransactionEgressSMData::State::RegularBodySent:
      os << "RegularBodySent";
      break;
    case HTTPTransactionEgressSMData::State::ChunkHeaderSent:
      os << "ChunkHeaderSent";
      break;
    case HTTPTransactionEgressSMData::State::ChunkBodySent:
      os << "ChunkBodySent";
      break;
    case HTTPTransactionEgressSMData::State::ChunkTerminatorSent:
      os << "ChunkTerminatorSent";
      break;
    case HTTPTransactionEgressSMData::State::TrailersSent:
      os << "TrailersSent";
      break;
    case HTTPTransactionEgressSMData::State::EOMQueued:
      os << "EOMQueued";
      break;
    case HTTPTransactionEgressSMData::State::SendingDone:
      os << "SendingDone";
      break;
  }
  return os;
}
template<class T > NullStream& proxygen::operator<< (NullStream & ns, const T &) [inline]
Definition at line 78 of file Logging.h.
                                                           {
  return ns;
}
std::ostream & proxygen::operator<< (std::ostream & os, const HPACKCodec & codec)
Definition at line 80 of file HPACKCodec.cpp.
References proxygen::HPACKCodec::describe().
                                                                {
  codec.describe(os);
  return os;
}
std::ostream & proxygen::operator<< (std::ostream & os, HTTPTransactionIngressSMData::State s)
Definition at line 84 of file HTTPTransactionIngressSM.cpp.
References proxygen::HTTPTransactionIngressSMData::ChunkBodyReceived, proxygen::HTTPTransactionIngressSMData::ChunkCompleted, proxygen::HTTPTransactionIngressSMData::ChunkHeaderReceived, proxygen::HTTPTransactionIngressSMData::EOMQueued, proxygen::HTTPTransactionIngressSMData::HeadersReceived, proxygen::HTTPTransactionIngressSMData::ReceivingDone, proxygen::HTTPTransactionIngressSMData::RegularBodyReceived, proxygen::HTTPTransactionIngressSMData::Start, proxygen::HTTPTransactionIngressSMData::TrailersReceived, and proxygen::HTTPTransactionIngressSMData::UpgradeComplete.
                                                              {
  switch (s) {
    case HTTPTransactionIngressSMData::State::Start:
      os << "Start";
      break;
    case HTTPTransactionIngressSMData::State::HeadersReceived:
      os << "HeadersReceived";
      break;
    case HTTPTransactionIngressSMData::State::RegularBodyReceived:
      os << "RegularBodyReceived";
      break;
    case HTTPTransactionIngressSMData::State::ChunkHeaderReceived:
      os << "ChunkHeaderReceived";
      break;
    case HTTPTransactionIngressSMData::State::ChunkBodyReceived:
      os << "ChunkBodyReceived";
      break;
    case HTTPTransactionIngressSMData::State::ChunkCompleted:
      os << "ChunkCompleted";
      break;
    case HTTPTransactionIngressSMData::State::TrailersReceived:
      os << "TrailersReceived";
      break;
    case HTTPTransactionIngressSMData::State::UpgradeComplete:
      os << "UpgradeComplete";
      break;
    case HTTPTransactionIngressSMData::State::EOMQueued:
      os << "EOMQueued";
      break;
    case HTTPTransactionIngressSMData::State::ReceivingDone:
      os << "ReceivingDone";
      break;
  }
  return os;
}
std::ostream & proxygen::operator<< (std::ostream & os, const HPACKContext & context)
Definition at line 86 of file HPACKContext.cpp.
References proxygen::HPACKContext::describe().
                                                                    {
  context.describe(os);
  return os;
}
std::ostream & proxygen::operator<< (std::ostream & os, HTTPTransactionEgressSMData::Event e)
Definition at line 112 of file HTTPTransactionEgressSM.cpp.
References proxygen::HTTPTransactionEgressSMData::eomFlushed, proxygen::HTTPTransactionEgressSMData::sendBody, proxygen::HTTPTransactionEgressSMData::sendChunkHeader, proxygen::HTTPTransactionEgressSMData::sendChunkTerminator, proxygen::HTTPTransactionEgressSMData::sendEOM, proxygen::HTTPTransactionEgressSMData::sendHeaders, and proxygen::HTTPTransactionEgressSMData::sendTrailers.
                                                             {
  switch (e) {
    case HTTPTransactionEgressSMData::Event::sendHeaders:
      os << "sendHeaders";
      break;
    case HTTPTransactionEgressSMData::Event::sendBody:
      os << "sendBody";
      break;
    case HTTPTransactionEgressSMData::Event::sendChunkHeader:
      os << "sendChunkHeader";
      break;
    case HTTPTransactionEgressSMData::Event::sendChunkTerminator:
      os << "sendChunkTerminator";
      break;
    case HTTPTransactionEgressSMData::Event::sendTrailers:
      os << "sendTrailers";
      break;
    case HTTPTransactionEgressSMData::Event::sendEOM:
      os << "sendEOM";
      break;
    case HTTPTransactionEgressSMData::Event::eomFlushed:
      os << "eomFlushed";
      break;
  }
  return os;
}
std::ostream& proxygen::operator<< (std::ostream & out, const TraceEvent & event)
Definition at line 116 of file TraceEvent.cpp.
                                                                   {
  out << event.toString();
  return out;
}
std::ostream & proxygen::operator<< (std::ostream & os, HTTPTransactionIngressSMData::Event e)
Definition at line 122 of file HTTPTransactionIngressSM.cpp.
References proxygen::HTTPTransactionIngressSMData::eomFlushed, proxygen::HTTPTransactionIngressSMData::onBody, proxygen::HTTPTransactionIngressSMData::onChunkComplete, proxygen::HTTPTransactionIngressSMData::onChunkHeader, proxygen::HTTPTransactionIngressSMData::onEOM, proxygen::HTTPTransactionIngressSMData::onHeaders, proxygen::HTTPTransactionIngressSMData::onTrailers, and proxygen::HTTPTransactionIngressSMData::onUpgrade.
                                                              {
  switch (e) {
    case HTTPTransactionIngressSMData::Event::onHeaders:
      os << "onHeaders";
      break;
    case HTTPTransactionIngressSMData::Event::onBody:
      os << "onBody";
      break;
    case HTTPTransactionIngressSMData::Event::onChunkHeader:
      os << "onChunkHeader";
      break;
    case HTTPTransactionIngressSMData::Event::onChunkComplete:
      os << "onChunkComplete";
      break;
    case HTTPTransactionIngressSMData::Event::onTrailers:
      os << "onTrailers";
      break;
    case HTTPTransactionIngressSMData::Event::onUpgrade:
      os << "onUpgrade";
      break;
    case HTTPTransactionIngressSMData::Event::onEOM:
      os << "onEOM";
      break;
    case HTTPTransactionIngressSMData::Event::eomFlushed:
      os << "eomFlushed";
      break;
  }
  return os;
}
std::ostream& proxygen::operator<< (std::ostream & os, const HPACKHeaderName & name) [inline]
Definition at line 203 of file HPACKHeaderName.h.
References proxygen::HPACKHeaderName::get().
                                                                           {
  os << name.get();
  return os;
}
std::ostream & proxygen::operator<< (std::ostream & os, const HeaderTable & table)
Definition at line 254 of file HeaderTable.cpp.
References proxygen::HPACKHeader::bytes(), proxygen::HeaderTable::bytes(), proxygen::HeaderTable::getHeader(), proxygen::HPACKHeader::name, proxygen::HeaderTable::size(), and proxygen::HPACKHeader::value.
Referenced by proxygen::HTTPTransactionEgressSMData::getName(), and proxygen::HTTPTransactionIngressSMData::getName().
                                                                 {
  os << std::endl;
  for (size_t i = 1; i <= table.size(); i++) {
    const HPACKHeader& h = table.getHeader(i);
    os << '[' << i << "] (s=" << h.bytes() << ") "
       << h.name << ": " << h.value << std::endl;
  }
  os << "total size: " << table.bytes() << std::endl;
  return os;
}
std::ostream & proxygen::operator<< (std::ostream & os, const HTTPMessage & msg)
Definition at line 671 of file HTTPMessage.cpp.
References proxygen::HTTPMessage::describe().
                                                               {
  msg.describe(os);
  return os;
}
std::ostream & proxygen::operator<< (std::ostream & os, const HTTPTransaction & txn)
Write a description of an HTTPTransaction to an ostream
Definition at line 1365 of file HTTPTransaction.cpp.
References proxygen::HTTPTransaction::describe().
                                                       {
  txn.describe(os);
  return os;
}
bool proxygen::operator== (const HTTPMessage & msg1, const HTTPMessage & msg2)
Definition at line 132 of file CompressionUtils.cpp.
References proxygen::HTTPMessage::getHeaders(), proxygen::HTTPMessage::getMethodString(), proxygen::HTTPMessage::getURL(), and proxygen::HTTPMessage::isSecure().
                                                                  {
  return (msg1.getMethodString() == msg2.getMethodString() &&
          msg1.getURL() == msg2.getURL() &&
          msg1.isSecure() == msg2.isSecure() &&
          containsAllHeaders(msg1.getHeaders(), msg2.getHeaders()) &&
          containsAllHeaders(msg2.getHeaders(), msg1.getHeaders()));
}
template<class T > size_t proxygen::parse (T * codec, const uint8_t * inputData, uint32_t length, int32_t atOnce = 0, std::function< bool()> stopFn = [] { return false; })
parse the input data using codec, using atOnce to determine how much data should go through the parser at one time
atOnce < 0: use random chunk lengths atOnce = 0: single chunk atOnce > 0: use specified chunk length
Definition at line 28 of file TestUtils.h.
Referenced by TEST_F(), HTTP2CodecTest::testFrameSizeLimit(), and HTTP2CodecTest::testHeaderListSize().
                                             { return false; }) {
  const uint8_t* start = inputData;
  size_t consumed = 0;
  std::uniform_int_distribution<uint32_t> lenDistribution(1, length / 2 + 1);
  std::mt19937 rng;
  if (atOnce == 0) {
    atOnce = length;
  }
  folly::IOBufQueue input(folly::IOBufQueue::cacheChainLength());
  while (length > 0 && !stopFn()) {
    if (consumed == 0) {
      // Parser wants more data
      uint32_t len = atOnce;
      if (atOnce < 0) {
        // use random chunks
        len = lenDistribution(rng);
      }
      uint32_t chunkLen = std::min(length, len);
      input.append(folly::IOBuf::copyBuffer(start, chunkLen));
      start += chunkLen;
      length -= chunkLen;
    }
    consumed = codec->onIngress(*input.front());
    input.split(consumed);
    if (input.front() == nullptr && consumed > 0) {
      consumed = 0;
    }
  }
  return input.chainLength();
}
folly::Optional< int64_t > proxygen::parseHTTPDateTime (const std::string & s)
Definition at line 18 of file HTTPTime.cpp.
Referenced by TEST().
                                                             {
  struct tm tm = {};
  if (s.empty()) {
    return folly::none;
  }
  // Sun, 06 Nov 1994 08:49:37 GMT ; RFC 822, updated by RFC 1123
  // Sunday, 06-Nov-94 08:49:37 GMT ; RFC 850, obsoleted by RFC 1036
  // Sun Nov 6 08:49:37 1994 ; ANSI C's asctime() format
  // Assume GMT as per rfc2616 (see HTTP-date):
  // - https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html
  if (strptime(s.c_str(), "%a, %d %b %Y %H:%M:%S GMT", &tm) != nullptr ||
      strptime(s.c_str(), "%a, %d-%b-%y %H:%M:%S GMT", &tm) != nullptr ||
      strptime(s.c_str(), "%a %b %d %H:%M:%S %Y", &tm) != nullptr) {
    return folly::Optional<int64_t>(timegm(&tm));
  }
  LOG(INFO) << "Invalid http time: " << s;
  return folly::none;
}
template<class T > size_t proxygen::parseUnidirectional (T * codec, const uint8_t * inputData, uint32_t length, int32_t atOnce = 0, std::function< bool()> stopFn = [] { return false; })
Definition at line 67 of file TestUtils.h.
                                                           { return false; }) {
  const uint8_t* start = inputData;
  size_t consumed = 0;
  std::uniform_int_distribution<uint32_t> lenDistribution(1, length / 2 + 1);
  std::mt19937 rng;
  if (atOnce == 0) {
    atOnce = length;
  }
  folly::IOBufQueue input(folly::IOBufQueue::cacheChainLength());
  while (length > 0 && !stopFn()) {
    if (consumed == 0) {
      // Parser wants more data
      uint32_t len = atOnce;
      if (atOnce < 0) {
        // use random chunks
        len = lenDistribution(rng);
      }
      uint32_t chunkLen = std::min(length, len);
      input.append(folly::IOBuf::copyBuffer(start, chunkLen));
      start += chunkLen;
      length -= chunkLen;
    }
    auto initialLength = input.chainLength();
    auto ret = codec->onUnidirectionalIngress(input.move());
    input.append(std::move(ret));
    consumed = initialLength - input.chainLength();
    if (input.front() == nullptr && consumed > 0) {
      consumed = 0;
    }
  }
  return input.chainLength();
}
std::string proxygen::printDelta (const std::vector< HPACKHeader > & v1, const std::vector< HPACKHeader > & v2)
print the difference between 2 sorted list of headers
Definition at line 38 of file Logging.cpp.
Referenced by TEST_F(), and proxygen::hpack::verifyHeaders().
                                                 {
  stringstream out;
  // similar with merge operation
  size_t i = 0;
  size_t j = 0;
  out << std::endl;
  while (i < v1.size() && j < v2.size()) {
    if (v1[i] < v2[j]) {
      if (i > 0 && v1[i - 1] == v1[i]) {
        out << " duplicate " << v1[i] << std::endl;
      } else {
        out << " + " << v1[i] << std::endl;
      }
      i++;
    } else if (v1[i] > v2[j]) {
      out << " - " << v2[j] << std::endl;
      j++;
    } else {
      i++;
      j++;
    }
  }
  while (i < v1.size()) {
    out << " + " << v1[i];
    if (i > 0 && v1[i - 1] == v1[i]) {
      out << " (duplicate)";
    }
    out << std::endl;
    i++;
  }
  while (j < v2.size()) {
    out << " - " << v2[j] << std::endl;
    j++;
  }
  return out.str();
}
std::unique_ptr<IOBuf> proxygen::readFileToIOBuf (const std::string & filename)
Definition at line 122 of file HTTPArchive.cpp.
References ERROR.
Referenced by proxygen::HTTPArchive::fromFile(), and proxygen::HTTPArchive::fromPublicFile().
                                                                {
  // read the contents of the file
  ifstream file(filename);
  if (!file.is_open()) {
    LOG(ERROR) << "could not open file '" << filename << "'";
    return nullptr;
  }
  file.seekg(0, ios::end);
  int64_t size = file.tellg();
  if (size < 0) {
    LOG(ERROR) << "failed to fetch the position at the end of the file";
    return nullptr;
  }
  file.seekg(0, ios::beg);
  unique_ptr<IOBuf> buffer = IOBuf::create(size + 1);
  file.read((char *)buffer->writableData(), size);
  buffer->writableData()[size] = 0;
  buffer->append(size + 1);
  if (!file) {
    LOG(ERROR) << "error occurred, was able to read only "
               << file.gcount() << " bytes out of " << size;
    return nullptr;
  }
  return buffer;
}
template<> std::unique_ptr<ScopedHTTPServer> proxygen::ScopedHTTPServer::start< std::unique_ptr< RequestHandlerFactory > > (std::unique_ptr< RequestHandlerFactory > f, int port, int numThreads, std::unique_ptr< wangle::SSLContextConfig > sslCfg) [inline]
Definition at line 154 of file ScopedHTTPServer.h.
References proxygen::HTTPServerOptions::handlerFactories, proxygen::HTTPServer::HTTP, and proxygen::HTTPServerOptions::threads.
                                                  {
  // This will handle both IPv4 and IPv6 cases
  folly::SocketAddress addr;
  addr.setFromLocalPort(port);
  HTTPServer::IPConfig cfg {
    addr,
    HTTPServer::Protocol::HTTP
  };
  if (sslCfg) {
    cfg.sslConfigs.push_back(*sslCfg);
  }
  HTTPServerOptions options;
  options.threads = numThreads;
  options.handlerFactories.push_back(std::move(f));
  return start(std::move(cfg), std::move(options));
}
template<typename ClockType = SteadyClock> std::chrono::seconds proxygen::secondsBetween (std::chrono::time_point< ClockType > finish, std::chrono::time_point< ClockType > start) [inline]
Definition at line 93 of file Time.h.
Referenced by secondsSince().
                                          {
  return std::chrono::duration_cast<std::chrono::seconds>(
    finish - start);
}
template<typename ClockType = SteadyClock> std::chrono::seconds proxygen::secondsSince (std::chrono::time_point< ClockType > t) [inline]
Definition at line 107 of file Time.h.
References secondsBetween().
Referenced by proxygen::HTTPSessionBase::onCreateTransaction().
                                                                       {
  return secondsBetween(getCurrentTime<ClockType>(), t);
}
std::chrono::seconds proxygen::secondsSinceEpoch () [inline]
Definition at line 61 of file Time.h.
                                            {
  return std::chrono::duration_cast<std::chrono::seconds>(
    std::chrono::system_clock::now().time_since_epoch());
}
std::chrono::seconds proxygen::secondsSinceEpoch (TimePoint t) [inline]
Definition at line 71 of file Time.h.
References toSystemTimePoint().
                                                       {
  return std::chrono::duration_cast<std::chrono::seconds>(
    toSystemTimePoint(t).time_since_epoch());
}
folly::Optional< HTTPMethod > proxygen::stringToMethod (folly::StringPiece method)
Returns the HTTPMethod that matches the method. Although RFC2616 5.1.1 says methods are case-sensitive, we ignore case here since most programmers probably really meant `GET` not `get`. If the method is not recognized, the return value will be None
Definition at line 37 of file HTTPMethod.cpp.
References caseInsensitiveEqual().
Referenced by main(), and proxygen::HTTPMessage::setMethod().
                                                                  {
  FOR_EACH_ENUMERATE(index, cur, getMethodStrings()) {
    if (caseInsensitiveEqual(*cur, method)) {
      return HTTPMethod(index);
    }
  }
  return folly::none;
}
template<typename Str > std::string proxygen::stripCntrlChars (const Str & str)
Returns a std::string that has the control characters removed from the input string.
Definition at line 849 of file HTTPMessage.h.
Referenced by proxygen::HTTPMessage::describe().
                                          {
  std::string res;
  res.reserve(str.length());
  for (size_t i = 0; i < str.size(); ++i) {
    if (!(str[i] <= 0x1F || str[i] == 0x7F)) {
      res += str[i];
    }
  }
  return res;
}
proxygen::TEST_F (StructuredHeadersDecoderTest , TestItem)
Definition at line 19 of file StructuredHeadersDecoderTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeItem(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                               {
  std::string input = "645643";
  StructuredHeadersDecoder shd(input);
  StructuredHeaderItem item;
  shd.decodeItem(item);
  EXPECT_EQ(item.tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(item, int64_t(645643));
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestInteger)
Definition at line 22 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeItem(), proxygen::StructuredHeadersEncoder::get(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                  {
  StructuredHeaderItem item;
  int64_t val = 2018;
  item.tag = StructuredHeaderItem::Type::INT64;
  item.value = val;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeItem(item);
  EXPECT_EQ(err, EncodeError::OK);
  EXPECT_EQ(encoder.get(), "2018");
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestBinaryContent)
Definition at line 23 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseItem(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                       {
  std::string input = "*bWF4aW0gaXMgdGhlIGJlc3Q=*";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::BINARYCONTENT);
  EXPECT_EQ(output, std::string("maxim is the best"));
}
proxygen::TEST_F (QPACKHeaderTableTests , Indexing)
Definition at line 28 of file QPACKHeaderTableTests.cpp.
References proxygen::HPACKHeader::copy().
                                        {
  HPACKHeader accept("accept-encoding", "gzip");
  HPACKHeader agent("user-agent", "SeaMonkey");
  EXPECT_EQ(table_.getBaseIndex(), 0);
  table_.add(accept.copy());
  EXPECT_EQ(table_.getBaseIndex(), 1);
  // Vulnerable - in the table
  EXPECT_EQ(table_.getIndex(accept, false),
            std::numeric_limits<uint32_t>::max());
  // Allow vulnerable, get the index
  EXPECT_EQ(table_.getIndex(accept, true), 1);
  EXPECT_TRUE(table_.onTableStateSync(1));
  EXPECT_EQ(table_.getIndex(accept, false), 1);
  table_.add(agent.copy());
  // Indexes move
  EXPECT_EQ(table_.getIndex(agent, true), 1);
  EXPECT_EQ(table_.getIndex(accept, true), 2);
}
proxygen::TEST_F (StructuredHeadersDecoderTest , TestList)
Definition at line 30 of file StructuredHeadersDecoderTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeList().
                                               {
  std::string input = "\"cookies\", 3.1415 , 74657";
  StructuredHeadersDecoder shd(input);
  std::vector<StructuredHeaderItem> v;
  shd.decodeList(v);
  EXPECT_EQ(v.size(), 3);
  EXPECT_EQ(v[0].tag, StructuredHeaderItem::Type::STRING);
  EXPECT_EQ(v[1].tag, StructuredHeaderItem::Type::DOUBLE);
  EXPECT_EQ(v[2].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(v[0], std::string("cookies"));
  EXPECT_EQ(v[1], 3.1415);
  EXPECT_EQ(v[2], int64_t(74657));
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestBinaryContentIllegalCharacters)
Definition at line 33 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, and proxygen::StructuredHeadersBuffer::parseItem().
                                                                        {
  std::string input = "*()645\t this is not a b64 encoded string ((({]}}}))*";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_NE(err, StructuredHeaders::DecodeError::OK);
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestIntegerNegative)
Definition at line 35 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeItem(), proxygen::StructuredHeadersEncoder::get(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                          {
  StructuredHeaderItem item;
  int64_t val = -2018;
  item.tag = StructuredHeaderItem::Type::INT64;
  item.value = val;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeItem(item);
  EXPECT_EQ(err, EncodeError::OK);
  EXPECT_EQ(encoder.get(), "-2018");
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestBinaryContentNoEndingAsterisk)
Definition at line 41 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, and proxygen::StructuredHeadersBuffer::parseItem().
                                                                       {
  std::string input = "*seattle";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_NE(err, StructuredHeaders::DecodeError::OK);
}
proxygen::TEST_F (StructuredHeadersDecoderTest , TestListBeginningWhitespace)
Definition at line 47 of file StructuredHeadersDecoderTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeList().
                                                                  {
  std::string input = " 19 , 95";
  StructuredHeadersDecoder shd(input);
  std::vector<StructuredHeaderItem> v;
  shd.decodeList(v);
  EXPECT_EQ(v.size(), 2);
  EXPECT_EQ(v[0].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(v[1].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(v[0], int64_t(19));
  EXPECT_EQ(v[1], int64_t(95));
}
proxygen::TEST_F (QPACKHeaderTableTests , Eviction)
Definition at line 48 of file QPACKHeaderTableTests.cpp.
References proxygen::HPACKHeader::bytes(), and proxygen::HPACKHeader::copy().
                                        {
  HPACKHeader accept("accept-encoding", "gzip");
  int32_t max = 4;
  uint32_t capacity = accept.bytes() * max;
  table_.setCapacity(capacity);
  for (auto i = 0; i < max; i++) {
    EXPECT_TRUE(table_.add(accept.copy()));
  }
  for (auto i = 1; i <= max; i++) {
    table_.addRef(i);
  }
  table_.setMaxAcked(max);
  EXPECT_FALSE(table_.canIndex(accept));
  EXPECT_FALSE(table_.add(accept.copy()));
  table_.subRef(1);
  EXPECT_TRUE(table_.canIndex(accept));
  EXPECT_TRUE(table_.add(accept.copy()));
  table_.subRef(3);
  EXPECT_FALSE(table_.canIndex(accept));
  table_.subRef(2);
  EXPECT_TRUE(table_.canIndex(accept));
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestFloat)
Definition at line 48 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeItem(), proxygen::StructuredHeadersEncoder::get(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                {
  StructuredHeaderItem item;
  double val = 3.1415926535;
  item.tag = StructuredHeaderItem::Type::DOUBLE;
  item.value = val;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeItem(item);
  EXPECT_EQ(err, EncodeError::OK);
  EXPECT_EQ(encoder.get(), "3.1415926535");
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestBinaryContentEmpty)
Definition at line 49 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseItem(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                            {
  std::string input = "**";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::BINARYCONTENT);
  EXPECT_EQ(output, std::string(""));
}
proxygen::TEST_F (HeaderTableTests , IndexTranslation)
Definition at line 54 of file HeaderTableTests.cpp.
                                           {
  // simple cases
  length_ = 10;
  head_ = 5;
  xcheck(0, 6);
  xcheck(3, 3);
  xcheck(5, 1);
  // wrap
  head_ = 1;
  xcheck(0, 2);
  xcheck(8, 4);
  xcheck(5, 7);
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestIdentifier)
Definition at line 59 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseIdentifier(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                    {
  std::string input = "abcdefg";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseIdentifier(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::IDENTIFIER);
  EXPECT_EQ(output, std::string("abcdefg"));
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestFloatTooMuchPrecision)
Definition at line 61 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeItem(), proxygen::StructuredHeadersEncoder::get(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                                {
  StructuredHeadersEncoder encoder;
  StructuredHeaderItem item;
  double val = 100000.8392758372647; // has 20 characters
  item.tag = StructuredHeaderItem::Type::DOUBLE;
  item.value = val;
  auto err = encoder.encodeItem(item);
  EXPECT_EQ(err, EncodeError::OK);
  EXPECT_EQ(encoder.get(), "100000.839275837");
}
proxygen::TEST_F (StructuredHeadersDecoderTest , TestListEndingWhitespace)
Definition at line 62 of file StructuredHeadersDecoderTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeList().
                                                               {
  std::string input = "19 , 95 ";
  StructuredHeadersDecoder shd(input);
  std::vector<StructuredHeaderItem> v;
  shd.decodeList(v);
  EXPECT_EQ(v.size(), 2);
  EXPECT_EQ(v[0].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(v[1].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(v[0], int64_t(19));
  EXPECT_EQ(v[1], int64_t(95));
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestIdentifierAllLegalCharacters)
Definition at line 69 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseIdentifier(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                                      {
  std::string input = "a0_-*/";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseIdentifier(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::IDENTIFIER);
  EXPECT_EQ(output, std::string("a0_-*/"));
}
proxygen::TEST_F (HeaderTableTests , Add)
Definition at line 69 of file HeaderTableTests.cpp.
References proxygen::HeaderTable::add(), proxygen::HPACKHeader::copy(), proxygen::HeaderTable::hasName(), proxygen::HPACKHeader::name, proxygen::HeaderTable::nameIndex(), and proxygen::HeaderTable::names().
                              {
  HeaderTable table(4096);
  HPACKHeader header("accept-encoding", "gzip");
  table.add(header.copy());
  table.add(header.copy());
  table.add(header.copy());
  EXPECT_EQ(table.names().size(), 1);
  EXPECT_EQ(table.hasName(header.name), true);
  auto it = table.names().find(header.name);
  EXPECT_EQ(it->second.size(), 3);
  EXPECT_EQ(table.nameIndex(header.name), 1);
}
proxygen::TEST_F (QPACKHeaderTableTests , BadEviction)
Definition at line 74 of file QPACKHeaderTableTests.cpp.
References proxygen::HPACKHeader::bytes(), and proxygen::HPACKHeader::copy().
                                           {
  HPACKHeader accept("accept-encoding", "gzip");
  int32_t max = 4;
  uint32_t capacity = accept.bytes() * max;
  table_.setCapacity(capacity);
  for (auto i = 0; i < max; i++) {
    EXPECT_TRUE(table_.add(accept.copy()));
  }
  EXPECT_EQ(table_.size(), max);
  EXPECT_FALSE(table_.setCapacity(capacity / 2));
  EXPECT_EQ(table_.size(), max);
  // Ack all headers but mark the first as in use
  table_.setMaxAcked(max);
  table_.addRef(1);
  EXPECT_FALSE(table_.setCapacity(capacity / 2));
  // Clear all refs
  table_.subRef(1);
  EXPECT_TRUE(table_.setCapacity(capacity / 2));
  EXPECT_EQ(table_.size(), max / 2);
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestFloatNegative)
Definition at line 74 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeItem(), proxygen::StructuredHeadersEncoder::get(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                        {
  StructuredHeaderItem item;
  double val = -3.141;
  item.tag = StructuredHeaderItem::Type::DOUBLE;
  item.value = val;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeItem(item);
  EXPECT_EQ(err, EncodeError::OK);
  EXPECT_EQ(encoder.get(), "-3.141");
}
proxygen::TEST_F (StructuredHeadersDecoderTest , TestListNoWhitespace)
Definition at line 77 of file StructuredHeadersDecoderTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeList().
                                                           {
  std::string input = "19,95";
  StructuredHeadersDecoder shd(input);
  std::vector<StructuredHeaderItem> v;
  shd.decodeList(v);
  EXPECT_EQ(v.size(), 2);
  EXPECT_EQ(v[0].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(v[1].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(v[0], int64_t(19));
  EXPECT_EQ(v[1], int64_t(95));
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestIdentifierBeginningUnderscore)
Definition at line 79 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, and proxygen::StructuredHeadersBuffer::parseIdentifier().
                                                                       {
  std::string input = "_af09d____****";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseIdentifier(output);
  EXPECT_NE(err, StructuredHeaders::DecodeError::OK);
}
proxygen::TEST_F (HeaderTableTests , Evict)
Definition at line 82 of file HeaderTableTests.cpp.
References proxygen::HeaderTable::add(), proxygen::HPACKHeader::bytes(), proxygen::HPACKHeader::copy(), proxygen::HeaderTable::getHeader(), name, proxygen::HeaderTable::names(), and proxygen::HeaderTable::size().
                                {
  HPACKHeaderName name("accept-encoding");
  HPACKHeader accept("accept-encoding", "gzip");
  HPACKHeader accept2("accept-encoding", "----"); // same size, different header
  HPACKHeader accept3("accept-encoding", "third"); // size is larger with 1 byte
  uint32_t max = 10;
  uint32_t capacity = accept.bytes() * max;
  HeaderTable table(capacity);
  // fill the table
  for (size_t i = 0; i < max; i++) {
    EXPECT_EQ(table.add(accept.copy()), true);
  }
  EXPECT_EQ(table.size(), max);
  EXPECT_EQ(table.add(accept2.copy()), true);
  // evict the first one
  EXPECT_EQ(table.getHeader(1), accept2);
  auto ilist = table.names().find(name)->second;
  EXPECT_EQ(ilist.size(), max);
  // evict all the 'accept' headers
  for (size_t i = 0; i < max - 1; i++) {
    EXPECT_EQ(table.add(accept2.copy()), true);
  }
  EXPECT_EQ(table.size(), max);
  EXPECT_EQ(table.getHeader(max), accept2);
  EXPECT_EQ(table.names().size(), 1);
  // add an entry that will cause 2 evictions
  EXPECT_EQ(table.add(accept3.copy()), true);
  EXPECT_EQ(table.getHeader(1), accept3);
  EXPECT_EQ(table.size(), max - 1);
  // add a super huge header
  string bigvalue;
  bigvalue.append(capacity, 'x');
  HPACKHeader bigheader("user-agent", bigvalue);
  EXPECT_EQ(table.add(bigheader.copy()), false);
  EXPECT_EQ(table.size(), 0);
  EXPECT_EQ(table.names().size(), 0);
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestString)
Definition at line 87 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseItem(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                {
  std::string input = "\"fsdfsdf\"sdfsdf\"";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::STRING);
  EXPECT_EQ(output, std::string("fsdfsdf"));
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestString)
Definition at line 87 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeItem(), proxygen::StructuredHeadersEncoder::get(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                 {
  StructuredHeaderItem item;
  std::string val = "seattle is the best";
  item.tag = StructuredHeaderItem::Type::STRING;
  item.value = val;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeItem(item);
  EXPECT_EQ(err, EncodeError::OK);
  EXPECT_EQ(encoder.get(), "\"seattle is the best\"");
}
proxygen::TEST_F (StructuredHeadersDecoderTest , TestListOneItem)
Definition at line 92 of file StructuredHeadersDecoderTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeList().
                                                      {
  std::string input = "*Zm9vZA==*";
  StructuredHeadersDecoder shd(input);
  std::vector<StructuredHeaderItem> v;
  shd.decodeList(v);
  EXPECT_EQ(v.size(), 1);
  EXPECT_EQ(v[0].tag, StructuredHeaderItem::Type::BINARYCONTENT);
  EXPECT_EQ(v[0], std::string("food"));
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestStringEscapedQuote)
Definition at line 97 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseItem(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                            {
  std::string input = "\"abc\\\"def\"";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::STRING);
  EXPECT_EQ(output, std::string("abc\"def"));
}
proxygen::TEST_F (QPACKHeaderTableTests , Wrapcount)
Definition at line 99 of file QPACKHeaderTableTests.cpp.
References proxygen::HPACKHeader::copy().
                                         {
  HPACKHeader accept("accept-encoding", "gzip");
  HPACKHeader agent("user-agent", "SeaMonkey");
  HPACKHeader cookie("Cookie", "choco=chip");
  for (auto i = 0; i < 10; i++) {
    EXPECT_TRUE(table_.add(accept.copy()));
    table_.setMaxAcked(i + 1);
  }
  EXPECT_TRUE(table_.add(cookie.copy()));
  EXPECT_TRUE(table_.add(agent.copy()));
  EXPECT_EQ(table_.getBaseIndex(), 12);
  EXPECT_EQ(table_.getIndex(agent, true), 1);
  EXPECT_EQ(table_.getIndex(cookie, true), 2);
  EXPECT_EQ(table_.getIndex(accept, true), 3);
  EXPECT_EQ(table_.getHeader(1, table_.getBaseIndex()), agent);
  EXPECT_EQ(table_.getHeader(2, table_.getBaseIndex()), cookie);
  EXPECT_EQ(table_.getHeader(table_.size(), table_.getBaseIndex()), accept);
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestStringBadContent)
Definition at line 100 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeItem(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                           {
  StructuredHeaderItem item;
  std::string val = "seattle \n is the best";
  item.tag = StructuredHeaderItem::Type::STRING;
  item.value = val;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeItem(item);
  EXPECT_NE(err, EncodeError::OK);
}
proxygen::TEST_F (StructuredHeadersDecoderTest , TestDictionaryManyElts)
Definition at line 105 of file StructuredHeadersDecoderTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeDictionary().
                                                             {
  std::string input = "age=87 , weight=150.8 , name=\"John Doe\"";
  StructuredHeadersDecoder shd(input);
  std::unordered_map<std::string, StructuredHeaderItem> m;
  shd.decodeDictionary(m);
  EXPECT_EQ(m.size(), 3);
  EXPECT_EQ(m["age"].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(m["weight"].tag, StructuredHeaderItem::Type::DOUBLE);
  EXPECT_EQ(m["name"].tag, StructuredHeaderItem::Type::STRING);
  EXPECT_EQ(m["age"], int64_t(87));
  EXPECT_EQ(m["weight"], 150.8);
  EXPECT_EQ(m["name"], std::string("John Doe"));
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestStringEscapedBackslash)
Definition at line 107 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseItem(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                                {
  std::string input = "\"abc\\\\def\"";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::STRING);
  EXPECT_EQ(output, std::string("abc\\def"));
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestStringBackslash)
Definition at line 112 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeItem(), proxygen::StructuredHeadersEncoder::get(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                          {
  StructuredHeaderItem item;
  std::string val = "seattle \\is the best";
  item.tag = StructuredHeaderItem::Type::STRING;
  item.value = val;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeItem(item);
  EXPECT_EQ(err, EncodeError::OK);
  EXPECT_EQ(encoder.get(), "\"seattle \\\\is the best\"");
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestStringStrayBackslash)
Definition at line 117 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, and proxygen::StructuredHeadersBuffer::parseItem().
                                                              {
  std::string input = "\"abc\\def\"";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_NE(err, StructuredHeaders::DecodeError::OK);
}
proxygen::TEST_F (QPACKHeaderTableTests , NameIndex)
Definition at line 120 of file QPACKHeaderTableTests.cpp.
References proxygen::HPACKHeader::copy(), and proxygen::HPACKHeader::name.
                                         {
  HPACKHeader accept("accept-encoding", "gzip");
  EXPECT_EQ(table_.nameIndex(accept.name), 0);
  EXPECT_TRUE(table_.add(accept.copy()));
  EXPECT_EQ(table_.nameIndex(accept.name), 1);
}
proxygen::TEST_F (HeaderTableTests , ReduceCapacity)
Definition at line 121 of file HeaderTableTests.cpp.
References proxygen::HeaderTable::add(), proxygen::HPACKHeader::bytes(), proxygen::HeaderTable::bytes(), proxygen::HPACKHeader::copy(), proxygen::HeaderTable::getMaxTableLength(), proxygen::HeaderTable::length(), proxygen::HeaderTable::setCapacity(), and proxygen::HeaderTable::size().
                                         {
  HPACKHeader accept("accept-encoding", "gzip");
  uint32_t max = 10;
  uint32_t capacity = accept.bytes() * max;
  HeaderTable table(capacity);
  EXPECT_LE(table.length(), table.getMaxTableLength(capacity));
  // fill the table
  for (size_t i = 0; i < max; i++) {
    EXPECT_EQ(table.add(accept.copy()), true);
  }
  // change capacity
  table.setCapacity(capacity / 2);
  EXPECT_EQ(table.size(), max / 2);
  EXPECT_EQ(table.bytes(), capacity / 2);
}
proxygen::TEST_F (StructuredHeadersDecoderTest , TestDictionaryOneElt)
Definition at line 122 of file StructuredHeadersDecoderTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeDictionary().
                                                           {
  std::string input = "bagel=*YXZvY2Fkbw==*";
  StructuredHeadersDecoder shd(input);
  std::unordered_map<std::string, StructuredHeaderItem> m;
  shd.decodeDictionary(m);
  EXPECT_EQ(m.size(), 1);
  EXPECT_EQ(m["bagel"].tag, StructuredHeaderItem::Type::BINARYCONTENT);
  EXPECT_EQ(m["bagel"], std::string("avocado"));
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestStringInvalidCharacter)
Definition at line 125 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, and proxygen::StructuredHeadersBuffer::parseItem().
                                                                {
  std::string input = "\"abcdefg\thij\"";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_NE(err, StructuredHeaders::DecodeError::OK);
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestStringQuote)
Definition at line 125 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeItem(), proxygen::StructuredHeadersEncoder::get(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                      {
  StructuredHeaderItem item;
  std::string val = "seattle \"is the best";
  item.tag = StructuredHeaderItem::Type::STRING;
  item.value = val;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeItem(item);
  EXPECT_EQ(err, EncodeError::OK);
  EXPECT_EQ(encoder.get(), "\"seattle \\\"is the best\"");
}
proxygen::TEST_F (QPACKHeaderTableTests , GetIndex)
Definition at line 127 of file QPACKHeaderTableTests.cpp.
References proxygen::HPACKHeader::copy().
                                        {
  HPACKHeader accept1("accept-encoding", "gzip");
  HPACKHeader accept2("accept-encoding", "blarf");
  EXPECT_EQ(table_.getIndex(accept1), 0);
  EXPECT_TRUE(table_.add(accept1.copy()));
  EXPECT_EQ(table_.getIndex(accept1), 1);
  EXPECT_EQ(table_.getIndex(accept2), 0);
}
proxygen::TEST_F (QueueTest , Basic)
Definition at line 131 of file HTTP2PriorityQueueTest.cpp.
                         {
  buildSimpleTree();
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 100}, {3, 25}, {5, 25}, {9, 100}, {7, 50}}));
  // Add another node, make sure we get the correct depth.
  uint64_t depth;
  addTransaction(11, {7, false, 15}, false, &depth);
  EXPECT_EQ(depth, 3);
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestStringParsingRepeated)
Definition at line 133 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseItem(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                               {
  std::string input = "\"proxy\"\"gen\"";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::STRING);
  EXPECT_EQ(output, std::string("proxy"));
  err = shd.parseItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::STRING);
  EXPECT_EQ(output, std::string("gen"));
}
proxygen::TEST_F (StructuredHeadersDecoderTest , TestParamListOneElt)
Definition at line 134 of file StructuredHeadersDecoderTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeParameterisedList().
                                                          {
  std::string input = "abc_123;a=1;b=2";
  StructuredHeadersDecoder shd(input);
  ParameterisedList pl;
  shd.decodeParameterisedList(pl);
  EXPECT_EQ(pl.size(), 1);
  EXPECT_EQ(pl[0].identifier, "abc_123");
  EXPECT_EQ(pl[0].parameterMap.size(), 2);
  EXPECT_EQ(pl[0].parameterMap["a"], int64_t(1));
  EXPECT_EQ(pl[0].parameterMap["b"], int64_t(2));
}
proxygen::TEST_F (QPACKHeaderTableTests , Duplication)
Definition at line 136 of file QPACKHeaderTableTests.cpp.
References proxygen::HPACKHeader::copy().
                                           {
  HPACKHeader accept("accept-encoding", "gzip");
  EXPECT_TRUE(table_.add(accept.copy()));
  // Unnecessary duplicate
  auto res = table_.maybeDuplicate(1, true);
  EXPECT_FALSE(res.first);
  EXPECT_EQ(res.second, 1);
  for (auto i = 0; i < 6; i++) {
    EXPECT_TRUE(table_.add(accept.copy()));
    // Ack the first few entries so they can be evicted
    table_.setMaxAcked(std::min(3u, table_.getBaseIndex()));
  }
  // successful duplicate, vulnerable allowed
  EXPECT_TRUE(table_.isDraining(table_.size()));
  res = table_.maybeDuplicate(table_.size(), true);
  EXPECT_TRUE(res.first);
  EXPECT_EQ(res.second, 8);
  EXPECT_EQ(table_.size(), 6); // evicted 1
  // successful duplicate, vulnerable disallowed
  EXPECT_TRUE(table_.onTableStateSync(3));
  res = table_.maybeDuplicate(table_.size(), false);
  EXPECT_TRUE(res.first);
  EXPECT_EQ(res.second, 0);
  EXPECT_EQ(table_.size(), 6); // evicted 2
  // Attempt to duplicate UNACKED
  res = table_.maybeDuplicate(QPACKHeaderTable::UNACKED, true);
  EXPECT_FALSE(res.first);
  EXPECT_EQ(res.second, 0);
  EXPECT_EQ(table_.size(), 6); // nothing changed
  EXPECT_EQ(table_.getBaseIndex(), 9);
  // Hold a ref to oldest entry, prevents eviction
  auto oldestAbsolute = table_.getBaseIndex() - table_.size() + 1;
  table_.addRef(oldestAbsolute);
  // Table should be full
  EXPECT_FALSE(table_.canIndex(accept));
  res = table_.maybeDuplicate(table_.size(), true);
  EXPECT_FALSE(res.first);
  EXPECT_EQ(res.second, 0);
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestBinaryContent)
Definition at line 138 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeItem(), proxygen::StructuredHeadersEncoder::get(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                        {
  StructuredHeaderItem item;
  std::string val = "seattle <3";
  item.tag = StructuredHeaderItem::Type::BINARYCONTENT;
  item.value = val;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeItem(item);
  EXPECT_EQ(err, EncodeError::OK);
  EXPECT_EQ(encoder.get(), "*c2VhdHRsZSA8Mw==*");
}
proxygen::TEST_F (HeaderTableTests , Comparison)
Definition at line 138 of file HeaderTableTests.cpp.
References proxygen::HeaderTable::add(), and proxygen::HPACKHeader::copy().
                                     {
  uint32_t capacity = 128;
  HeaderTable t1(capacity);
  HeaderTable t2(capacity);
  HPACKHeader h1("Content-Encoding", "gzip");
  HPACKHeader h2("Content-Encoding", "deflate");
  // different in number of elements
  t1.add(h1.copy());
  EXPECT_FALSE(t1 == t2);
  // different in size (bytes)
  t2.add(h2.copy());
  EXPECT_FALSE(t1 == t2);
  // make them the same
  t1.add(h2.copy());
  t2.add(h1.copy());
  EXPECT_TRUE(t1 == t2);
}
proxygen::TEST_F (QueueTest , RemoveLeaf)
Definition at line 142 of file HTTP2PriorityQueueTest.cpp.
                              {
  buildSimpleTree();
  removeTransaction(3);
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 100}, {5, 33}, {9, 100}, {7, 66}}));
}
proxygen::TEST_F (StructuredHeadersDecoderTest , TestParamListManyElts)
Definition at line 147 of file StructuredHeadersDecoderTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeParameterisedList().
                                                            {
  std::string input = "a_13;a=1;b=2; c_4, ghi;q=\"9\";r=*bWF4IGlzIGF3ZXNvbWU=*";
  StructuredHeadersDecoder shd(input);
  ParameterisedList pl;
  shd.decodeParameterisedList(pl);
  EXPECT_EQ(pl.size(), 2);
  EXPECT_EQ(pl[0].identifier, "a_13");
  EXPECT_EQ(pl[0].parameterMap.size(), 3);
  EXPECT_EQ(pl[0].parameterMap["a"].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(pl[0].parameterMap["b"].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(pl[0].parameterMap["c_4"].tag, StructuredHeaderItem::Type::NONE);
  EXPECT_EQ(pl[0].parameterMap["a"], int64_t(1));
  EXPECT_EQ(pl[0].parameterMap["b"], int64_t(2));
  EXPECT_EQ(pl[1].identifier, "ghi");
  EXPECT_EQ(pl[1].parameterMap.size(), 2);
  EXPECT_EQ(pl[1].parameterMap["q"].tag, StructuredHeaderItem::Type::STRING);
  EXPECT_EQ(pl[1].parameterMap["r"].tag,
    StructuredHeaderItem::Type::BINARYCONTENT);
  EXPECT_EQ(pl[1].parameterMap["q"], std::string("9"));
  EXPECT_EQ(pl[1].parameterMap["r"], std::string("max is awesome"));
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestInteger)
Definition at line 148 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseItem(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                 {
  std::string input = "843593";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(output, int64_t(843593));
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestIdentifier)
Definition at line 151 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeIdentifier(), and proxygen::StructuredHeadersEncoder::get().
                                                     {
  std::string result;
  std::string val = "abc_00123";
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeIdentifier(val);
  EXPECT_EQ(err, EncodeError::OK);
  EXPECT_EQ(encoder.get(), "abc_00123");
}
proxygen::TEST_F (QueueTest , RemoveParent)
Definition at line 151 of file HTTP2PriorityQueueTest.cpp.
                                {
  buildSimpleTree();
  removeTransaction(5);
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 100}, {3, 25}, {7, 50}, {9, 25}}));
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestIntegerTwoNegatives)
Definition at line 158 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, and proxygen::StructuredHeadersBuffer::parseItem().
                                                             {
  std::string input = "--843593";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_NE(err, StructuredHeaders::DecodeError::OK);
}
proxygen::TEST_F (HeaderTableTests , Print)
Definition at line 158 of file HeaderTableTests.cpp.
References proxygen::HeaderTable::add().
                                {
  stringstream out;
  HeaderTable t(128);
  t.add(HPACKHeader("Accept-Encoding", "gzip"));
  out << t;
  EXPECT_EQ(out.str(),
  "\n[1] (s=51) accept-encoding: gzip\ntotal size: 51\n");
}
proxygen::TEST_F (QueueTest , RemoveParentWeights)
Definition at line 160 of file HTTP2PriorityQueueTest.cpp.
                                       {
  // weight_ / totalChildWeight_ < 1
  addTransaction(0, {kRootNodeId, false, 0});
  addTransaction(3, {0, false, 255});
  addTransaction(5, {0, false, 255});
  removeTransaction(0);
  dump();
  EXPECT_EQ(nodes_, IDList({{3, 50}, {5, 50}}));
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestIdentifierBadContent)
Definition at line 162 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeIdentifier().
                                                               {
  std::string result;
  std::string val = "_abc_00123";
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeIdentifier(val);
  EXPECT_NE(err, EncodeError::OK);
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestIntegerEmptyAfterNegative)
Definition at line 166 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, and proxygen::StructuredHeadersBuffer::parseItem().
                                                                   {
  std::string input = "-";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_NE(err, StructuredHeaders::DecodeError::OK);
}
proxygen::TEST_F (HeaderTableTests , IncreaseCapacity)
Definition at line 167 of file HeaderTableTests.cpp.
References proxygen::HeaderTable::add(), proxygen::HPACKHeader::bytes(), proxygen::HPACKHeader::copy(), proxygen::HeaderTable::getIndex(), proxygen::HeaderTable::getMaxTableLength(), proxygen::HeaderTable::length(), proxygen::HeaderTable::setCapacity(), and proxygen::HeaderTable::size().
                                           {
  HPACKHeader accept("accept-encoding", "gzip");
  uint32_t max = 4;
  uint32_t capacity = accept.bytes() * max;
  HeaderTable table(capacity);
  EXPECT_LE(table.length(), table.getMaxTableLength(capacity));
  // fill the table
  uint32_t length = table.length() + 1;
  for (size_t i = 0; i < length; i++) {
    EXPECT_EQ(table.add(accept.copy()), true);
  }
  EXPECT_EQ(table.size(), max);
  EXPECT_EQ(table.getIndex(accept), 1);
  // head should be 0, tail should be 2
  max = 8;
  capacity = accept.bytes() * max;
  table.setCapacity(capacity);
  EXPECT_LE(table.length(), table.getMaxTableLength(capacity));
  // external index didn't change
  EXPECT_EQ(table.getIndex(accept), 1);
}
proxygen::TEST_F (StructuredHeadersDecoderTest , TestParamListNoParams)
Definition at line 172 of file StructuredHeadersDecoderTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeParameterisedList().
                                                            {
  std::string input = "apple12, cat14, dog22";
  StructuredHeadersDecoder shd(input);
  ParameterisedList pl;
  shd.decodeParameterisedList(pl);
  EXPECT_EQ(pl.size(), 3);
  EXPECT_EQ(pl[0].identifier, "apple12");
  EXPECT_EQ(pl[0].parameterMap.size(), 0);
  EXPECT_EQ(pl[1].identifier, "cat14");
  EXPECT_EQ(pl[1].parameterMap.size(), 0);
  EXPECT_EQ(pl[2].identifier, "dog22");
  EXPECT_EQ(pl[2].parameterMap.size(), 0);
}
proxygen::TEST_F (QueueTest , NodeDepth)
Definition at line 172 of file HTTP2PriorityQueueTest.cpp.
                             {
  uint64_t depth{33}; // initialize to some wrong value
  addTransaction(0, {kRootNodeId, false, 15}, false, &depth);
  EXPECT_EQ(depth, 1);
  addTransaction(3, {0, false, 3}, false, &depth);
  EXPECT_EQ(depth, 2);
  addTransaction(5, {3, true, 7}, false, &depth);
  EXPECT_EQ(depth, 3);
  addTransaction(9, {0, false, 3}, true, &depth);
  EXPECT_EQ(depth, 2);
  EXPECT_EQ(q_.numPendingEgress(), 3);
  EXPECT_EQ(q_.numVirtualNodes(), 1);
  depth = 55; // some unlikely depth
  addTransaction(9, {0, false, 31}, false, &depth);
  EXPECT_EQ(depth, 2);
  EXPECT_EQ(q_.numPendingEgress(), 4);
  EXPECT_EQ(q_.numVirtualNodes(), 0);
  addTransaction(11, {0, true, 7}, false, &depth);
  EXPECT_EQ(depth, 2);
  EXPECT_EQ(q_.numPendingEgress(), 5);
  EXPECT_EQ(q_.numVirtualNodes(), 0);
  addTransaction(13, {kRootNodeId, true, 23}, true, &depth);
  EXPECT_EQ(depth, 1);
  EXPECT_EQ(q_.numPendingEgress(), 5);
  EXPECT_EQ(q_.numVirtualNodes(), 1);
  depth = 77; // some unlikely depth
  addTransaction(13, {kRootNodeId, true, 33}, false, &depth);
  EXPECT_EQ(depth, 1);
  EXPECT_EQ(q_.numPendingEgress(), 6);
  EXPECT_EQ(q_.numVirtualNodes(), 0);
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestWrongType)
Definition at line 172 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeItem(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                    {
  StructuredHeaderItem item;
  double val = 3.1415;
  item.tag = StructuredHeaderItem::Type::INT64;
  item.value = val;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeItem(item);
  EXPECT_NE(err, EncodeError::OK);
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestIntegerNegative)
Definition at line 174 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseItem(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                         {
  std::string input = "-843593";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(output, int64_t(-843593));
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestIntegerOverflow)
Definition at line 184 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, and proxygen::StructuredHeadersBuffer::parseItem().
                                                         {
  std::string input = "9223372036854775808";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_NE(err, StructuredHeaders::DecodeError::OK);
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestListManyElts)
Definition at line 184 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeList(), proxygen::StructuredHeadersEncoder::get(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                       {
  std::vector<StructuredHeaderItem> vec;
  StructuredHeaderItem item;
  item.tag = StructuredHeaderItem::Type::DOUBLE;
  double val1 = 3.14;
  item.value = val1;
  vec.push_back(item);
  item.tag = StructuredHeaderItem::Type::BINARYCONTENT;
  std::string val2 = "pizza";
  item.value = val2;
  vec.push_back(item);
  item.tag = StructuredHeaderItem::Type::INT64;
  int64_t val3 = 65;
  item.value = val3;
  vec.push_back(item);
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeList(vec);
  EXPECT_EQ(err, EncodeError::OK);
  EXPECT_EQ(encoder.get(), "3.14, *cGl6emE=*, 65");
}
proxygen::TEST_F (QPACKHeaderTableTests , CanEvictWithRoom)
Definition at line 186 of file QPACKHeaderTableTests.cpp.
References proxygen::HPACKHeader::copy().
                                                {
  HPACKHeader thirtyNineBytes("abcd", "efg");
  HPACKHeader fortySevenBytes("abcd", "efghijklmno");
  for (auto i = 0; i < 8; i++) {
    EXPECT_TRUE(table_.add(thirtyNineBytes.copy()));
  }
  table_.setMaxAcked(table_.getBaseIndex());
  // abs index = 1 is evictable, but index = 2 is referenced, so we can
  // insert up to (320 - 8 * 39) + 39 = 47
  table_.addRef(2);
  EXPECT_TRUE(table_.canIndex(fortySevenBytes));
  EXPECT_TRUE(table_.add(fortySevenBytes.copy()));
}
proxygen::TEST_F (StructuredHeadersDecoderTest , TestParamListWhitespace)
Definition at line 189 of file StructuredHeadersDecoderTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeParameterisedList().
                                                              {
  std::string input = "am_95 ; abc=11.8 , foo ";
  StructuredHeadersDecoder shd(input);
  ParameterisedList pl;
  shd.decodeParameterisedList(pl);
  EXPECT_EQ(pl.size(), 2);
  EXPECT_EQ(pl[0].identifier, "am_95");
  EXPECT_EQ(pl[0].parameterMap.size(), 1);
  EXPECT_EQ(pl[0].parameterMap["abc"].tag, StructuredHeaderItem::Type::DOUBLE);
  EXPECT_EQ(pl[0].parameterMap["abc"], 11.8);
  EXPECT_EQ(pl[1].identifier, "foo");
  EXPECT_EQ(pl[1].parameterMap.size(), 0);
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestIntegerHighBorderline)
Definition at line 192 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseItem(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                               {
  std::string input = "9223372036854775807";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(output, std::numeric_limits<int64_t>::max());
}
proxygen::TEST_F (HeaderTableTests , VaryCapacity)
Definition at line 192 of file HeaderTableTests.cpp.
References proxygen::HeaderTable::add(), proxygen::HPACKHeader::bytes(), proxygen::HPACKHeader::copy(), proxygen::HeaderTable::length(), and proxygen::HeaderTable::size().
                                       {
  HPACKHeader accept("accept-encoding", "gzip");
  uint32_t max = 6;
  uint32_t capacity = accept.bytes() * max;
  HeaderTable table(capacity);
  // Fill the table (extra) and make sure we haven't violated our
  // size (bytes) limits (expected one entry to be evicted)
  for (size_t i = 0; i <= table.length(); ++i) {
    EXPECT_EQ(table.add(accept.copy()), true);
  }
  EXPECT_EQ(table.size(), max);
  // Size down the table and verify we are still honoring our size (bytes)
  // limits
  resizeAndFillTable(table, accept, 4, 5);
  // Size up the table (in between previous max and min within test) and verify
  // we are still horing our size (bytes) limits
  resizeAndFillTable(table, accept, 5, 6);
  // Finally reize up one last timestamps
  resizeAndFillTable(table, accept, 8, 9);
}
proxygen::TEST_F (RFC1867Test , TestSimplePost)
Definition at line 195 of file RFC1867Test.cpp.
                                    {
  size_t fileSize = 17;
  auto data = makePost(
      {{"foo", "bar"}, {"jojo", "binky"}}, {}, {{"file1", {"", fileSize}}});
  testSimple(std::move(data), 3 + 5 + fileSize, 0, 3);
}
proxygen::TEST_F (QPACKHeaderTableTests , EvictNonDrained)
Definition at line 200 of file QPACKHeaderTableTests.cpp.
References proxygen::HPACKHeader::copy().
                                               {
  HPACKHeader small("ab", "cd"); // 36 bytes
  HPACKHeader small2("abcd", std::string(14, 'b')); // 50 bytes
  HPACKHeader med(std::string(20, 'a'), std::string(20, 'b')); // 72
  HPACKHeader large(std::string(34, 'a'), std::string(34, 'b')); // 100
  table_.setCapacity(220);
  EXPECT_TRUE(table_.add(small.copy()));
  EXPECT_TRUE(table_.add(med.copy()));
  EXPECT_TRUE(table_.add(large.copy()));
  EXPECT_TRUE(table_.isDraining(3));
  EXPECT_FALSE(table_.isDraining(2));
  table_.setMaxAcked(3);
  // Evicts small and med
  EXPECT_TRUE(table_.add(small2.copy()));
  EXPECT_EQ(table_.size(), 2);
  EXPECT_FALSE(table_.isDraining(1));
  EXPECT_FALSE(table_.isDraining(2));
  // Now lg should be draining
  EXPECT_TRUE(table_.add(small.copy()));
  EXPECT_TRUE(table_.isDraining(3));
  // Evict large
  EXPECT_TRUE(table_.add(small.copy()));
}
proxygen::TEST_F (RFC1867Test , TestSplits)
Definition at line 202 of file RFC1867Test.cpp.
                                {
  for (size_t i = 1; i < 500; i++) {
    size_t fileSize = 1000 + i;
    auto data = makePost(
        {{"foo", "bar"}, {"jojo", "binky"}}, {}, {{"file1", {"", fileSize}}});
    testSimple(std::move(data), 3 + 5 + fileSize, i, 3);
  }
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestIntegerLowBorderline)
Definition at line 202 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseItem(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                              {
  std::string input = "-9223372036854775808";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(output, std::numeric_limits<int64_t>::min());
}
proxygen::TEST_F (StructuredHeadersDecoderTest , TestParamListNullValues)
Definition at line 206 of file StructuredHeadersDecoderTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeParameterisedList().
                                                              {
  std::string input = "beverages;water;juice, food;pizza;burger";
  StructuredHeadersDecoder shd(input);
  ParameterisedList pl;
  shd.decodeParameterisedList(pl);
  EXPECT_EQ(pl.size(), 2);
  EXPECT_EQ(pl[0].identifier, "beverages");
  EXPECT_EQ(pl[0].parameterMap.size(), 2);
  EXPECT_EQ(pl[0].parameterMap["water"].tag, StructuredHeaderItem::Type::NONE);
  EXPECT_EQ(pl[0].parameterMap["juice"].tag, StructuredHeaderItem::Type::NONE);
  EXPECT_EQ(pl[1].identifier, "food");
  EXPECT_EQ(pl[1].parameterMap.size(), 2);
  EXPECT_EQ(pl[1].parameterMap["pizza"].tag, StructuredHeaderItem::Type::NONE);
  EXPECT_EQ(pl[1].parameterMap["burger"].tag, StructuredHeaderItem::Type::NONE);
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestListOneElt)
Definition at line 210 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeList(), proxygen::StructuredHeadersEncoder::get(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                     {
  std::vector<StructuredHeaderItem> vec;
  StructuredHeaderItem item;
  item.tag = StructuredHeaderItem::Type::STRING;
  std::string val1 = "hello world";
  item.value = val1;
  vec.push_back(item);
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeList(vec);
  EXPECT_EQ(err, EncodeError::OK);
  EXPECT_EQ(encoder.get(), "\"hello world\"");
}
proxygen::TEST_F (RFC1867Test , TestSplitsWithFilename)
Definition at line 211 of file RFC1867Test.cpp.
                                            {
  for (size_t i = 1; i < 500; i++) {
    size_t fileSize = 1000 + i;
    auto data = makePost({{"foo", "bar"}, {"jojo", "binky"}},
                         {},
                         {{"file1", {"file1.txt", fileSize}}});
    testSimple(std::move(data), 3 + 5 + fileSize, i, 3);
  }
}
proxygen::TEST_F (QueueTest , UpdateWeight)
Definition at line 211 of file HTTP2PriorityQueueTest.cpp.
                                {
  buildSimpleTree();
  uint64_t depth = 0;
  updatePriority(5, {0, false, 7}, &depth);
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 100}, {3, 20}, {5, 40}, {9, 100}, {7, 40}}));
  EXPECT_EQ(depth, 2);
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestIntegerUnderflow)
Definition at line 212 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, and proxygen::StructuredHeadersBuffer::parseItem().
                                                          {
  std::string input = "-9223372036854775809";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_NE(err, StructuredHeaders::DecodeError::OK);
}
proxygen::TEST_F (HeaderTableTests , VaryCapacityMalignHeadIndex)
Definition at line 217 of file HeaderTableTests.cpp.
References proxygen::HeaderTable::add(), proxygen::HPACKHeader::bytes(), proxygen::HeaderTable::bytes(), proxygen::HPACKHeader::copy(), proxygen::HeaderTable::getMaxTableLength(), proxygen::HeaderTable::length(), and proxygen::HeaderTable::size().
                                                      {
  // Test checks for a previous bug/crash condition where due to resizing
  // the underlying table to a size lower than a previous max but up from the
  // current size and the position of the head_ index an out of bounds index
  // would occur
  // Initialize header table
  HPACKHeader accept("accept-encoding", "gzip");
  uint32_t max = 6;
  uint32_t capacity = accept.bytes() * max;
  HeaderTable table(capacity);
  // Push head_ to last index in underlying table before potential wrap
  // This is our max table size for the duration of the test
  for (size_t i = 0; i < table.getMaxTableLength(capacity); ++i) {
    EXPECT_EQ(table.add(accept.copy()), true);
  }
  EXPECT_EQ(table.size(), max);
  EXPECT_EQ(table.bytes(), capacity);
  // Flush underlying table (head_ remains the same at the previous max index)
  // Header guranteed to cause a flush as header itself requires 32 bytes plus
  // the sizes of the name and value anyways (which themselves would cause a
  // flush)
  string strLargerThanTableCapacity = string(capacity + 1, 'a');
  HPACKHeader flush("flush", strLargerThanTableCapacity);
  EXPECT_EQ(table.add(flush.copy()), false);
  EXPECT_EQ(table.size(), 0);
  // Now reduce capacity of table (in functional terms table.size() is lowered
  // but currently table.length() remains the same)
  max = 3;
  resizeTable(table, accept.bytes() * max, max);
  // Increase capacity of table (but smaller than all time max; head_ still at
  // previous max index). Previously (now fixed) this size up resulted in
  // incorrect resizing semantics
  max = 4;
  resizeTable(table, accept.bytes() * max, max);
  // Now try and add headers; there should be no crash with current position of
  // head_ in the underlying table. Note this is merely one possible way we
  // could force the test to crash as a result of the resize bug this test was
  // added for
  for (size_t i = 0; i <= table.length(); ++i) {
    EXPECT_EQ(table.add(accept.copy()), true);
  }
  EXPECT_EQ(table.size(), max);
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestFloat)
Definition at line 220 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseItem(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                               {
  std::string input = "3.1415926536";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::DOUBLE);
  EXPECT_EQ(output, 3.1415926536);
}
proxygen::TEST_F (RFC1867Test , TestHeadersChunkExtraCr)
Definition at line 221 of file RFC1867Test.cpp.
                                             {
  // We are testing here that we correctly chunk when the parser has just
  // finished parsing a CR.
  auto numCRs = 5;
  auto headerEndingSeq = "--" + string(numCRs, '\r') + "\n";
  auto fileSize = 10;
  auto data = makePost({{"foo", "bar"}, {"jojo", "binky"}},
                       {},
                       {{"file1", {"", fileSize}}},
                       headerEndingSeq);
  // Math ensures we the parser will chunk at a '\r' with a numCRs-1
  testSimple(std::move(data), 3 + 5 + fileSize, numCRs - 1, 3);
}
proxygen::TEST_F (QueueTest , DuplicateID)
Definition at line 224 of file HTTP2PriorityQueueTest.cpp.
                               {
  q_.addOrUpdatePriorityNode(0, {kRootNodeId, false, 15});
  addTransaction(0, {kRootNodeId, true, 15});
  q_.addOrUpdatePriorityNode(3, {0, false, 15});
  addTransaction(5, {3, false, 15});
  addTransaction(3, {5, false, 15});
  removeTransaction(5);
  auto stopFn = [] {
    return false;
  };
  dumpBFS(stopFn);
  EXPECT_EQ(nodes_, IDList({{0, 100}, {3, 100}}));
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestListEmpty)
Definition at line 226 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeList().
                                                    {
  std::vector<StructuredHeaderItem> vec;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeList(vec);
  EXPECT_NE(err, EncodeError::OK);
}
proxygen::TEST_F (QPACKHeaderTableTests , BadSync)
Definition at line 228 of file QPACKHeaderTableTests.cpp.
                                       {
  // Can't ack more than is in the table
  EXPECT_FALSE(table_.onTableStateSync(1));
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestFloatPrecedingWhitespace)
Definition at line 230 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseItem(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                                  {
  std::string input = " \t\t 66000.5645";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::DOUBLE);
  EXPECT_EQ(output, 66000.5645);
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestListBadItem)
Definition at line 235 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeList(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                      {
  std::vector<StructuredHeaderItem> vec;
  StructuredHeaderItem item;
  item.tag = StructuredHeaderItem::Type::STRING;
  std::string val1 = "hello \x10world";
  item.value = val1;
  vec.push_back(item);
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeList(vec);
  EXPECT_NE(err, EncodeError::OK);
}
proxygen::TEST_F (QueueTest , UpdateWeightNotEnqueued)
Definition at line 239 of file HTTP2PriorityQueueTest.cpp.
                                           {
  addTransaction(0, {kRootNodeId, false, 7});
  addTransaction(3, {0, false, 7});
  signalEgress(0, false);
  signalEgress(3, false);
  uint64_t depth = 0;
  updatePriority(0, {3, false, 7}, &depth);
  dump();
  EXPECT_EQ(nodes_, IDList({{3, 100}, {0, 100}}));
  EXPECT_EQ(depth, 2);
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestFloatNoDigitPrecedingDecimal)
Definition at line 240 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, and proxygen::StructuredHeadersBuffer::parseItem().
                                                                      {
  std::string input = ".1415926536";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_NE(err, StructuredHeaders::DecodeError::OK);
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestIntegerTooManyChars)
Definition at line 248 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, and proxygen::StructuredHeadersBuffer::parseItem().
                                                             {
  std::string input = "10000000000000000000"; // has 20 characters
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_NE(err, StructuredHeaders::DecodeError::OK);
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestDictionaryOneElt)
Definition at line 250 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeDictionary(), proxygen::StructuredHeadersEncoder::get(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                           {
  StructuredHeaders::Dictionary dict;
  StructuredHeaderItem item1;
  item1.tag = StructuredHeaderItem::Type::DOUBLE;
  double val1 = 2.71;
  item1.value = val1;
  dict["e"] = item1;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeDictionary(dict);
  EXPECT_EQ(err, EncodeError::OK);
  EXPECT_EQ(encoder.get(), "e=2.71");
}
proxygen::TEST_F (QueueTest , UpdateWeightExcl)
Definition at line 253 of file HTTP2PriorityQueueTest.cpp.
                                    {
  buildSimpleTree();
  updatePriority(5, {0, true, 7});
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 100}, {5, 100}, {9, 40}, {3, 20}, {7, 40}}));
  signalEgress(0, false);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{5, 100}}));
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestFloatTooManyChars)
Definition at line 256 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, and proxygen::StructuredHeadersBuffer::parseItem().
                                                           {
  std::string input = "111111111.1111111"; // has 17 characters
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_NE(err, StructuredHeaders::DecodeError::OK);
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestFloatBorderlineNumChars)
Definition at line 264 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseItem(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                                 {
  std::string input = "111111111.111111"; // has 16 characters
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::DOUBLE);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
}
proxygen::TEST_F (QueueTest , UpdateWeightExclDequeued)
Definition at line 265 of file HTTP2PriorityQueueTest.cpp.
                                            {
  buildSimpleTree();
  signalEgress(5, false);
  updatePriority(5, {0, true, 7});
  signalEgress(0, false);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{9, 40}, {7, 40}, {3, 20}}));
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestDictionaryManyElts)
Definition at line 267 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeDictionary(), proxygen::StructuredHeadersEncoder::get(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                             {
  StructuredHeaders::Dictionary dict;
  StructuredHeaderItem item;
  item.tag = StructuredHeaderItem::Type::INT64;
  int64_t val1 = 87;
  item.value = val1;
  dict["age"] = item;
  item.tag = StructuredHeaderItem::Type::STRING;
  std::string val2 = "John Doe";
  item.value = val2;
  dict["name"] = item;
  item.tag = StructuredHeaderItem::Type::BINARYCONTENT;
  std::string val3 = "password";
  item.value = val3;
  dict["password"] = item;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeDictionary(dict);
  EXPECT_EQ(err, EncodeError::OK);
  // A dictionary is an unordered mapping, so the ordering of specific elements
  // within the dictionary doesn't matter
  EXPECT_THAT(encoder.get(), AnyOf(
    Eq("age=87, name=\"John Doe\", password=*cGFzc3dvcmQ=*"),
    Eq("age=87, password=*cGFzc3dvcmQ=*, name=\"John Doe\""),
    Eq("name=\"John Doe\", age=87, password=*cGFzc3dvcmQ=*"),
    Eq("name=\"John Doe\", password=*cGFzc3dvcmQ=*, age=87"),
    Eq("password=*cGFzc3dvcmQ=*, name=\"John Doe\", age=87"),
    Eq("password=*cGFzc3dvcmQ=*, age=87, name=\"John Doe\"")
  ));
}
proxygen::TEST_F (HeaderTableTests , AddLargerThanTable)
Definition at line 267 of file HeaderTableTests.cpp.
References proxygen::HeaderTable::add(), proxygen::HeaderTable::hasName(), name, proxygen::HeaderTable::nameIndex(), and proxygen::HeaderTable::names().
                                             {
  // Construct a smallish table
  uint32_t capacityBytes = 256;
  HeaderTable table(capacityBytes);
  HPACKHeaderName name("accept-encoding");
  table.add(HPACKHeader("accept-encoding", "gzip")); // internal index = 0
  table.add(HPACKHeader("accept-encoding", "gzip")); // internal index = 1
  table.add(HPACKHeader("test-encoding", "gzip")); // internal index = 2
  EXPECT_EQ(table.names().size(), 2);
  // Attempt to add a header that is larger than our specified table capacity
  // bytes. This should result in a table flush.
  table.add(HPACKHeader(std::string(capacityBytes, 'a'), "gzip"));
  EXPECT_EQ(table.names().size(), 0);
  // Add the previous headers to the table again
  table.add(HPACKHeader("accept-encoding", "gzip")); // internal index = 3
  table.add(HPACKHeader("accept-encoding", "gzip")); // internal index = 4
  table.add(HPACKHeader("test-encoding", "gzip")); // internal index = 5
  EXPECT_EQ(table.names().size(), 2);
  EXPECT_EQ(table.hasName(name), true);
  auto it = table.names().find(name);
  EXPECT_EQ(it->second.size(), 2);
  // As nameIndex takes the last index added, we have head = 5, index = 4
  // and so yields a difference of one and as external indexing is 1 based,
  // we expect 2 here
  EXPECT_EQ(table.nameIndex(name), 2);
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestFloatEndsWithDecimal)
Definition at line 273 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, and proxygen::StructuredHeadersBuffer::parseItem().
                                                              {
  std::string input = "100.";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  auto err = shd.parseItem(output);
  EXPECT_NE(err, StructuredHeaders::DecodeError::OK);
}
proxygen::TEST_F (QueueTest , UpdateWeightUnknownParent)
Definition at line 276 of file HTTP2PriorityQueueTest.cpp.
                                             {
  buildSimpleTree();
  uint64_t depth = 0;
  updatePriority(5, {97, false, 15}, &depth);
  dump();
  EXPECT_EQ(
    nodes_,
    IDList({{0, 50}, {3, 33}, {7, 66}, {97, 50}, {5, 100}, {9, 100}})
  );
  EXPECT_EQ(depth, 2);
  depth = 0;
  updatePriority(9, {99, false, 15}, &depth);
  dump();
  EXPECT_EQ(
    nodes_,
    IDList({{0, 33}, {3, 33}, {7, 66}, {97, 33}, {5, 100}, {99, 33}, {9, 100}})
  );
  EXPECT_EQ(depth, 2);
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestConsumeComma)
Definition at line 281 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseItem(), proxygen::StructuredHeadersBuffer::removeSymbol(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                      {
  std::string input = ",5345346";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  shd.removeSymbol(",", true);
  auto err = shd.parseItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(output, int64_t(5345346));
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestConsumeEquals)
Definition at line 292 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseItem(), proxygen::StructuredHeadersBuffer::removeSymbol(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                       {
  std::string input = "=456346.646";
  StructuredHeadersBuffer shd(input);
  StructuredHeaderItem output;
  shd.removeSymbol("=", true);
  auto err = shd.parseItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::DOUBLE);
  EXPECT_EQ(output, 456346.646);
}
proxygen::TEST_F (StructuredHeadersStandardTest , TestBasicList)
Definition at line 296 of file StructuredHeadersStandardTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeList().
                                                     {
  std::string input("1, 42");
  StructuredHeadersDecoder shd(input);
  std::vector<StructuredHeaderItem> v;
  auto err = shd.decodeList(v);
  EXPECT_EQ(err, DecodeError::OK);
  EXPECT_EQ(v.size(), 2);
  EXPECT_EQ(v[0].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(v[1].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(v[0], int64_t(1));
  EXPECT_EQ(v[1], int64_t(42));
}
proxygen::TEST_F (HeaderTableTests , IncreaseLengthOfFullTable)
Definition at line 297 of file HeaderTableTests.cpp.
References proxygen::HeaderTable::add(), proxygen::HPACKHeader::copy(), proxygen::HeaderTable::getHeader(), and proxygen::HeaderTable::length().
                                                    {
  HPACKHeader largeHeader("Access-Control-Allow-Credentials", "true");
  HPACKHeader smallHeader("Accept", "All-Content");
  HeaderTable table(448);
  CHECK_EQ(table.length(), 7);
  for (uint8_t count = 0; count < 3; count++) {
    table.add(largeHeader.copy());
    table.add(smallHeader.copy());
  } // tail is at index 0
  CHECK_EQ(table.length(), 7);
  table.add(smallHeader.copy());
  table.add(smallHeader.copy()); // tail is at index 1
  table.add(smallHeader.copy()); // resize on this add
  EXPECT_EQ(table.length(), 11);
  // Check table is correct after resize
  CHECK_EQ(table.getHeader(1), smallHeader);
  CHECK_EQ(table.getHeader(2), smallHeader);
  CHECK_EQ(table.getHeader(3), smallHeader);
  CHECK_EQ(table.getHeader(4), smallHeader);
  CHECK_EQ(table.getHeader(5), largeHeader);
  CHECK_EQ(table.getHeader(6), smallHeader);
  CHECK_EQ(table.getHeader(7), largeHeader);
  CHECK_EQ(table.getHeader(8), smallHeader);
}
proxygen::TEST_F (QueueTest , UpdateParentSibling)
Definition at line 300 of file HTTP2PriorityQueueTest.cpp.
                                       {
  buildSimpleTree();
  updatePriority(5, {3, false, 3});
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 100}, {3, 33}, {5, 100},
                               {9, 100}, {7, 66}}));
  signalEgress(0, false);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{7, 66}, {3, 33}}));
  // Clear 5's egress (so it is only in the tree because 9 has egress) and move
  // it back. Hit's a slightly different code path in reparent
  signalEgress(5, false);
  updatePriority(5, {0, false, 3});
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 100}, {3, 25}, {7, 50}, {5, 25}, {9, 100}}));
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{7, 50}, {3, 25}, {9, 25}}));
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestConsumeMessy)
Definition at line 303 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::OK, proxygen::StructuredHeadersBuffer::parseIdentifier(), proxygen::StructuredHeadersBuffer::removeSymbol(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                      {
  std::string input = "asfgsdfg,asfgsdfg,";
  StructuredHeadersBuffer shd(input);
  for (int i = 0; i < 2; i++) {
    StructuredHeaderItem output;
    auto err = shd.parseIdentifier(output);
    EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
    EXPECT_EQ(output.tag, StructuredHeaderItem::Type::IDENTIFIER);
    EXPECT_EQ(output, std::string("asfgsdfg"));
    shd.removeSymbol(",", true);
  }
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestDictionaryEmpty)
Definition at line 303 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeDictionary().
                                                          {
  StructuredHeaders::Dictionary dict;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeDictionary(dict);
  EXPECT_NE(err, EncodeError::OK);
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestDictionaryBadItem)
Definition at line 312 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeDictionary(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                            {
  StructuredHeaders::Dictionary dict;
  StructuredHeaderItem item1;
  item1.tag = StructuredHeaderItem::Type::STRING;
  std::string val1 = "hi\nmy name is bob";
  item1.value = val1;
  dict["e"] = item1;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeDictionary(dict);
  EXPECT_NE(err, EncodeError::OK);
}
proxygen::TEST_F (StructuredHeadersStandardTest , TestSingleItemList)
Definition at line 313 of file StructuredHeadersStandardTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeList().
                                                          {
  std::string input("42");
  StructuredHeadersDecoder shd(input);
  std::vector<StructuredHeaderItem> v;
  auto err = shd.decodeList(v);
  EXPECT_EQ(err, DecodeError::OK);
  EXPECT_EQ(v.size(), 1);
  EXPECT_EQ(v[0].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(v[0], int64_t(42));
}
proxygen::TEST_F (StructuredHeadersBufferTest , TestInequalityOperator)
Definition at line 316 of file StructuredHeadersBufferTest.cpp.
References proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                            {
  StructuredHeaderItem integerItem;
  integerItem.value = int64_t(999);
  StructuredHeaderItem doubleItem;
  doubleItem.value = 11.43;
  StructuredHeaderItem stringItem;
  stringItem.value = std::string("hi");
  EXPECT_NE(integerItem, int64_t(998));
  EXPECT_NE(doubleItem, double(11.44));
  EXPECT_NE(stringItem, std::string("bye"));
}
proxygen::TEST_F (QueueTest , UpdateParentSiblingExcl)
Definition at line 324 of file HTTP2PriorityQueueTest.cpp.
                                           {
  buildSimpleTree();
  updatePriority(7, {5, true, 3});
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 100}, {3, 50}, {5, 50},
                              {7, 100}, {9, 100}}));
  signalEgress(0, false);
  signalEgress(3, false);
  signalEgress(5, false);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{7, 100}}));
}
proxygen::TEST_F (HeaderTableTests , SmallTable)
Definition at line 326 of file HeaderTableTests.cpp.
References proxygen::HeaderTable::add(), proxygen::HPACKHeader::copy(), proxygen::HeaderTable::length(), and proxygen::HeaderTable::size().
                                     {
  HeaderTable table(80);
  HPACKHeader foo("Foo", "bar");
  EXPECT_TRUE(table.add(foo.copy()));
  EXPECT_TRUE(table.add(foo.copy()));
  EXPECT_EQ(table.size(), 2);
  EXPECT_EQ(table.length(), 2);
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestDictionaryBadIdentifier)
Definition at line 328 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeDictionary(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                                  {
  StructuredHeaders::Dictionary dict;
  StructuredHeaderItem item1;
  item1.tag = StructuredHeaderItem::Type::STRING;
  std::string val1 = "hi";
  item1.value = val1;
  dict["_bad_identifier"] = item1;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeDictionary(dict);
  EXPECT_NE(err, EncodeError::OK);
}
proxygen::TEST_F (StructuredHeadersStandardTest , TestNoWhitespaceList)
Definition at line 328 of file StructuredHeadersStandardTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeList().
                                                            {
  std::string input("1,42");
  StructuredHeadersDecoder shd(input);
  std::vector<StructuredHeaderItem> v;
  auto err = shd.decodeList(v);
  EXPECT_EQ(err, DecodeError::OK);
  EXPECT_EQ(v.size(), 2);
  EXPECT_EQ(v[0].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(v[1].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(v[0], int64_t(1));
  EXPECT_EQ(v[1], int64_t(42));
}
proxygen::TEST_F (QueueTest , UpdateParentAncestor)
Definition at line 339 of file HTTP2PriorityQueueTest.cpp.
                                        {
  buildSimpleTree();
  updatePriority(9, {kRootNodeId, false, 15});
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 50}, {3, 25}, {5, 25}, {7, 50}, {9, 50}}));
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{0, 50}, {9, 50}}));
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestParamListOneElt)
Definition at line 344 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeParameterisedList(), proxygen::StructuredHeadersEncoder::get(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                          {
  ParameterisedList pl;
  std::unordered_map<std::string, StructuredHeaderItem> m;
  StructuredHeaderItem item;
  item.tag = StructuredHeaderItem::Type::INT64;
  int64_t val1 = 1;
  item.value = val1;
  m["abc"] = item;
  ParameterisedIdentifier pident = {"foo", m};
  pl.emplace_back(pident);
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeParameterisedList(pl);
  EXPECT_EQ(err, EncodeError::OK);
  EXPECT_EQ(encoder.get(), "foo; abc=1");
}
proxygen::TEST_F (StructuredHeadersStandardTest , TestExtraWhitespaceList)
Definition at line 345 of file StructuredHeadersStandardTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeList().
                                                               {
  std::string input("1 , 42");
  StructuredHeadersDecoder shd(input);
  std::vector<StructuredHeaderItem> v;
  auto err = shd.decodeList(v);
  EXPECT_EQ(err, DecodeError::OK);
  EXPECT_EQ(v.size(), 2);
  EXPECT_EQ(v[0].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(v[1].tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(v[0], int64_t(1));
  EXPECT_EQ(v[1], int64_t(42));
}
proxygen::TEST_F (QueueTest , UpdateParentAncestorExcl)
Definition at line 350 of file HTTP2PriorityQueueTest.cpp.
                                            {
  buildSimpleTree();
  updatePriority(9, {kRootNodeId, true, 15});
  dump();
  EXPECT_EQ(nodes_, IDList({{9, 100}, {0, 100}, {3, 25}, {5, 25}, {7, 50}}));
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{9, 100}}));
}
proxygen::TEST_F (QueueTest , UpdateParentDescendant)
Definition at line 361 of file HTTP2PriorityQueueTest.cpp.
                                          {
  buildSimpleTree();
  updatePriority(0, {5, false, 7});
  dump();
  EXPECT_EQ(nodes_, IDList({{5, 100}, {9, 50}, {0, 50}, {3, 33}, {7, 66}}));
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{5, 100}}));
  signalEgress(5, false);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{9, 50}, {0, 50}}));
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestParamListSuccessiveNulls)
Definition at line 367 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeParameterisedList(), proxygen::StructuredHeadersEncoder::get(), and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                                   {
  ParameterisedList pl;
  std::unordered_map<std::string, StructuredHeaderItem> m;
  StructuredHeaderItem item;
  item.tag = StructuredHeaderItem::Type::NONE;
  m["a"] = item;
  m["b"] = item;
  ParameterisedIdentifier pident = {"foo", m};
  pl.emplace_back(pident);
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeParameterisedList(pl);
  EXPECT_EQ(err, EncodeError::OK);
  EXPECT_THAT(encoder.get(), AnyOf(
    Eq("foo; a; b"),
    Eq("foo; b; a")
  ));
}
proxygen::TEST_F (QueueTest , UpdateParentDescendantExcl)
Definition at line 375 of file HTTP2PriorityQueueTest.cpp.
                                              {
  buildSimpleTree();
  updatePriority(0, {5, true, 7});
  dump();
  EXPECT_EQ(nodes_, IDList({{5, 100}, {0, 100}, {3, 20}, {7, 40}, {9, 40}}));
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{5, 100}}));
  signalEgress(5, false);
  signalEgress(0, false);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{7, 40}, {9, 40}, {3, 20}}));
}
proxygen::TEST_F (QueueTest , ExclusiveAdd)
Definition at line 390 of file HTTP2PriorityQueueTest.cpp.
                                {
  buildSimpleTree();
  addTransaction(11, {0, true, 100});
  dump();
  EXPECT_EQ(nodes_, IDList({
        {0, 100}, {11, 100}, {3, 25}, {5, 25}, {9, 100}, {7, 50}
      }));
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestParamListManyElts)
Definition at line 392 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeParameterisedList(), proxygen::StructuredHeadersEncoder::get(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                            {
  ParameterisedList pl;
  std::unordered_map<std::string, StructuredHeaderItem> m1;
  StructuredHeaderItem item;
  item.tag = StructuredHeaderItem::Type::DOUBLE;
  double val1 = 4234.234;
  item.value = val1;
  m1["foo"] = item;
  item.tag = StructuredHeaderItem::Type::BINARYCONTENT;
  std::string val2 = "+++!";
  item.value = val2;
  m1["goo"] = item;
  ParameterisedIdentifier pident1 = {"bar", m1};
  pl.emplace_back(pident1);
  std::unordered_map<std::string, StructuredHeaderItem> m2;
  item.tag = StructuredHeaderItem::Type::NONE;
  m2["foo"] = item;
  item.tag = StructuredHeaderItem::Type::INT64;
  int64_t val4 = 100;
  item.value = val4;
  m2["goo"] = item;
  ParameterisedIdentifier pident2 = {"far", m2};
  pl.emplace_back(pident2);
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeParameterisedList(pl);
  EXPECT_EQ(err, EncodeError::OK);
  // The order of the parameters of a particular identifier doesn't matter,
  // so any of these permutations is acceptable
  EXPECT_THAT(encoder.get(), AnyOf(
    Eq("bar; foo=4234.234; goo=*KysrIQ==*, far; foo; goo=100"),
    Eq("bar; foo=4234.234; goo=*KysrIQ==*, far; goo=100; foo"),
    Eq("bar; goo=*KysrIQ==*; foo=4234.234, far; foo; goo=100"),
    Eq("bar; goo=*KysrIQ==*; foo=4234.234, far; goo=100; foo"),
    Eq("far; foo; goo=100, bar; foo=4234.234; goo=*KysrIQ==*"),
    Eq("far; foo; goo=100, bar; goo=*KysrIQ==*; foo=4234.234"),
    Eq("far; goo=100; foo, bar; foo=4234.234; goo=*KysrIQ==*"),
    Eq("far; goo=100; foo, bar; goo=*KysrIQ==*; foo=4234.234")
  ));
}
proxygen::TEST_F (QueueTest , AddUnknown)
Definition at line 401 of file HTTP2PriorityQueueTest.cpp.
                              {
  buildSimpleTree();
  addTransaction(11, {75, false, 15});
  dump();
  EXPECT_EQ(nodes_, IDList({
        {0, 50}, {3, 25}, {5, 25}, {9, 100}, {7, 50}, {75, 50}, {11, 100}
      }));
  // Now let's add the missing parent node and check if it was
  // relocated properly
  addTransaction(75, {0, false, 7});
  dump();
  EXPECT_EQ(nodes_, IDList({
        {0, 100}, {3, 16}, {5, 16}, {9, 100}, {7, 33}, {75, 33}, {11, 100}
      }));
}
proxygen::TEST_F (QueueTest , AddMax)
Definition at line 421 of file HTTP2PriorityQueueTest.cpp.
                          {
  addTransaction(0, {kRootNodeId, false, 255});
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{0, 100}}));
}
proxygen::TEST_F (QueueTest , Misc)
Definition at line 428 of file HTTP2PriorityQueueTest.cpp.
                        {
  buildSimpleTree();
  EXPECT_FALSE(q_.empty());
  EXPECT_EQ(q_.numPendingEgress(), 5);
  signalEgress(0, false);
  EXPECT_EQ(q_.numPendingEgress(), 4);
  EXPECT_FALSE(q_.empty());
  removeTransaction(9);
  removeTransaction(0);
  dump();
  EXPECT_EQ(nodes_, IDList({{3, 25}, {5, 25}, {7, 50}}));
}
proxygen::TEST_F (QueueTest , IterateBFS)
Definition at line 442 of file HTTP2PriorityQueueTest.cpp.
                              {
  buildSimpleTree();
  auto stopFn = [this] {
    return nodes_.size() > 2;
  };
  dumpBFS(stopFn);
  EXPECT_EQ(nodes_, IDList({{0, 100}, {3, 25}, {5, 25}, {7, 50}}));
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestParamListEmpty)
Definition at line 445 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeParameterisedList().
                                                         {
  ParameterisedList pl;
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeParameterisedList(pl);
  EXPECT_NE(err, EncodeError::OK);
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestParamListBadSecondaryIdentifier)
Definition at line 453 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeParameterisedList(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                                          {
  ParameterisedList pl;
  std::unordered_map<std::string, StructuredHeaderItem> m;
  StructuredHeaderItem item;
  item.tag = StructuredHeaderItem::Type::STRING;
  std::string val1 = "ABC";
  item.value = val1;
  m["\nbbb"] = item;
  ParameterisedIdentifier pident = {"foo", m};
  pl.emplace_back(pident);
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeParameterisedList(pl);
  EXPECT_NE(err, EncodeError::OK);
}
proxygen::TEST_F (QueueTest , NextEgress)
Definition at line 453 of file HTTP2PriorityQueueTest.cpp.
                              {
  buildSimpleTree();
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{0, 100}}));
  addTransaction(11, {7, false, 15});
  signalEgress(0, false);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{7, 50}, {3, 25}, {5, 25}}));
  signalEgress(5, false);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{7, 50}, {3, 25}, {9, 25}}));
  signalEgress(5, true);
  signalEgress(3, false);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{7, 66}, {5, 33}}));
  signalEgress(5, false);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{7, 66}, {9, 33}}));
  signalEgress(7, false);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{11, 66}, {9, 33}}));
  signalEgress(9, false);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{11, 100}}));
  signalEgress(3, true);
  signalEgress(7, true);
  signalEgress(9, true);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{7, 50}, {3, 25}, {9, 25}}));
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestParamListBadPrimaryIdentifier)
Definition at line 474 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeParameterisedList(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                                        {
  ParameterisedList pl;
  std::unordered_map<std::string, StructuredHeaderItem> m;
  StructuredHeaderItem item;
  item.tag = StructuredHeaderItem::Type::INT64;
  int64_t val1 = 143;
  item.value = val1;
  m["abc"] = item;
  ParameterisedIdentifier pident = {"a+++", m};
  pl.emplace_back(pident);
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeParameterisedList(pl);
  EXPECT_NE(err, EncodeError::OK);
}
proxygen::TEST_F (QueueTest , NextEgressExclusiveAdd)
Definition at line 493 of file HTTP2PriorityQueueTest.cpp.
                                          {
  buildSimpleTree();
  // clear all egress
  signalEgress(0, false);
  signalEgress(3, false);
  signalEgress(5, false);
  signalEgress(7, false);
  signalEgress(9, false);
  // Add a transaction with exclusive dependency, clear its egress
  addTransaction(11, {0, true, 100});
  signalEgress(11, false);
  // signal egress for a child that got moved via exclusive dep
  signalEgress(3, true);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{3, 100}}));
  EXPECT_EQ(q_.numPendingEgress(), 1);
}
proxygen::TEST_F (StructuredHeadersEncoderTest , TestParamListBadItems)
Definition at line 495 of file StructuredHeadersEncoderTest.cpp.
References proxygen::StructuredHeadersEncoder::encodeParameterisedList(), proxygen::StructuredHeaders::StructuredHeaderItem::tag, and proxygen::StructuredHeaders::StructuredHeaderItem::value.
                                                            {
  ParameterisedList pl;
  std::unordered_map<std::string, StructuredHeaderItem> m;
  StructuredHeaderItem item;
  item.tag = StructuredHeaderItem::Type::STRING;
  std::string val1 = "AB\nC";
  item.value = val1;
  m["bbb"] = item;
  ParameterisedIdentifier pident = {"foo", m};
  pl.emplace_back(pident);
  StructuredHeadersEncoder encoder;
  auto err = encoder.encodeParameterisedList(pl);
  EXPECT_NE(err, EncodeError::OK);
}
proxygen::TEST_F (QueueTest , NextEgressExclusiveAddWithEgress)
Definition at line 514 of file HTTP2PriorityQueueTest.cpp.
                                                    {
  buildSimpleTree();
  // clear all egress, except 3
  signalEgress(0, false);
  signalEgress(5, false);
  signalEgress(7, false);
  signalEgress(9, false);
  // Add a transaction with exclusive dependency, clear its egress
  addTransaction(11, {0, true, 100});
  signalEgress(11, false);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{3, 100}}));
  EXPECT_EQ(q_.numPendingEgress(), 1);
}
proxygen::TEST_F (QueueTest , UpdatePriorityReparentSubtree)
Definition at line 531 of file HTTP2PriorityQueueTest.cpp.
                                                 {
  buildSimpleTree();
  // clear all egress, except 9
  signalEgress(0, false);
  signalEgress(3, false);
  signalEgress(5, false);
  signalEgress(7, false);
  // Update priority of non-enqueued but in egress tree node
  updatePriority(5, {0, false, 14}, nullptr);
  // update 9's weight and reparent
  updatePriority(9, {3, false, 14}, nullptr);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{9, 100}}));
}
proxygen::TEST_F (QueueTest , NextEgressRemoveParent)
Definition at line 550 of file HTTP2PriorityQueueTest.cpp.
                                          {
  buildSimpleTree();
  // Clear egress for all except txn=9
  signalEgress(0, false);
  signalEgress(3, false);
  signalEgress(5, false);
  signalEgress(7, false);
  // Remove parent of 9 (5)
  removeTransaction(5);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{9, 100}}));
  // signal egress for 9's new siblings to verify weights
  signalEgress(3, true);
  signalEgress(7, true);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{7, 50}, {9, 25}, {3, 25}}));
}
proxygen::TEST_F (QueueTest , AddExclusiveDescendantEnqueued)
Definition at line 572 of file HTTP2PriorityQueueTest.cpp.
                                                  {
  addTransaction(0, {kRootNodeId, false, 100});
  addTransaction(3, {0, false, 100});
  addTransaction(5, {3, false, 100});
  signalEgress(0, false);
  signalEgress(3, false);
  // add a new exclusive child of 1. 1's child 3 is not enqueued but is in the
  // the egress tree.
  addTransaction(7, {0, true, 100});
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{7, 100}}));
}
proxygen::TEST_F (QueueTest , NextEgressRemoveParentEnqueued)
Definition at line 585 of file HTTP2PriorityQueueTest.cpp.
                                                  {
  addTransaction(0, {kRootNodeId, false, 100});
  addTransaction(3, {0, false, 100});
  addTransaction(5, {3, false, 100});
  signalEgress(3, false);
  // When 3's children (5) are added to 1, both are already in the egress tree
  // and the signal does not need to propagate
  removeTransaction(3);
  signalEgress(0, false);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{5, 100}}));
}
proxygen::TEST_F (QueueTest , NextEgressRemoveParentEnqueuedIndirect)
Definition at line 598 of file HTTP2PriorityQueueTest.cpp.
                                                          {
  addTransaction(0, {kRootNodeId, false, 100});
  addTransaction(3, {0, false, 100});
  addTransaction(5, {3, false, 100});
  addTransaction(7, {0, false, 100});
  signalEgress(3, false);
  signalEgress(0, false);
  // When 3's children (5) are added to 1, both are already in the egress tree
  // and the signal does not need to propagate
  removeTransaction(3);
  nextEgress();
  EXPECT_EQ(nodes_, IDList({{7, 50}, {5, 50}}));
}
proxygen::TEST_F (QueueTest , ChromeTest)
Definition at line 612 of file HTTP2PriorityQueueTest.cpp.
                              {
  // Tries to simulate Chrome's current behavior by performing pseudo-random
  // add-exclusive, signal, clear and remove with 3 insertion points
  // (hi,mid,low). Note the test uses rand32() with a particular seed so the
  // output is predictable.
  HTTPCodec::StreamID pris[3] = {0, 3, 5};
  addTransaction(0, {kRootNodeId, true, 99});
  signalEgress(0, false);
  addTransaction(3, {0, true, 99});
  signalEgress(3, false);
  addTransaction(5, {3, true, 99});
  signalEgress(5, false);
  std::vector<HTTPCodec::StreamID> txns;
  std::vector<HTTPCodec::StreamID> active;
  std::vector<HTTPCodec::StreamID> inactive;
  HTTPCodec::StreamID txn = 0;
  uint64_t idx = 0;
  HTTPCodec::StreamID nextId = 7;
  auto gen = Random::create();
  gen.seed(12345); // luggage combo
  for (auto i = 4; i < 1000; i++) {
    uint8_t action = rand32(4, gen);
    if (action == 0) {
      // add exclusive on pseudo-random priority anchor
      uint8_t pri = rand32(3, gen);
      HTTPCodec::StreamID dep = pris[pri];
      txn = nextId;
      nextId += 2;
      VLOG(2) << "Adding txn=" << txn << " with dep=" << dep;
      addTransaction(txn, {(uint32_t)dep, true, 99});
      txns.push_back(txn);
      active.push_back(txn);
    } else if (action == 1 && !inactive.empty()) {
      // signal an inactive txn
      idx = rand32(inactive.size(), gen);
      txn = inactive[idx];
      VLOG(2) << "Activating txn=" << txn;
      signalEgress(txn, true);
      inactive.erase(inactive.begin() + idx);
      active.push_back(txn);
    } else if (action == 2 && !active.empty()) {
      // clear an active transaction
      idx = rand32(active.size(), gen);
      txn = active[idx];
      VLOG(2) << "Deactivating txn=" << txn;
      signalEgress(txn, false);
      active.erase(active.begin() + idx);
      inactive.push_back(txn);
    } else if (action == 3 && !txns.empty()) {
      // remove a transaction
      idx = rand32(txns.size(), gen);
      txn = txns[idx];
      VLOG(2) << "Removing txn=" << txn;
      removeTransaction(txn);
      txns.erase(txns.begin() + idx);
      auto it = std::find(active.begin(), active.end(), txn);
      if (it != active.end()) {
        active.erase(it);
      }
      it = std::find(inactive.begin(), inactive.end(), txn);
      if (it != inactive.end()) {
        inactive.erase(it);
      }
    }
    VLOG(2) << "Active nodes=" << q_.numPendingEgress();
    if (!q_.empty()) {
      nextEgress();
      EXPECT_GT(nodes_.size(), 0);
    }
  }
}
proxygen::TEST_F (QueueTest , NextEgressSpdy)
Definition at line 686 of file HTTP2PriorityQueueTest.cpp.
                                  {
  // 0 and 3 are vnodes representing pri 0 and 1
  addTransaction(0, {kRootNodeId, false, 0}, true);
  addTransaction(3, {0, false, 0}, true);
  // 7 and 9 are pri 0, 11 and 13 are pri 1
  addTransaction(7, {0, false, 15});
  addTransaction(9, {0, false, 15});
  addTransaction(11, {3, false, 15});
  addTransaction(13, {3, false, 15});
  nextEgress(true);
  EXPECT_EQ(nodes_, IDList({{7, 50}, {9, 50}}));
  signalEgress(7, false);
  nextEgress(true);
  EXPECT_EQ(nodes_, IDList({{9, 100}}));
  signalEgress(9, false);
  nextEgress(true);
  EXPECT_EQ(nodes_, IDList({{11, 50}, {13, 50}}));
}
proxygen::TEST_F (QueueTest , AddOrUpdate)
Definition at line 709 of file HTTP2PriorityQueueTest.cpp.
                               {
  q_.addOrUpdatePriorityNode(0, {kRootNodeId, false, 15});
  q_.addOrUpdatePriorityNode(3, {kRootNodeId, false, 15});
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 50}, {3, 50}}));
  q_.addOrUpdatePriorityNode(0, {kRootNodeId, false, 3});
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 20}, {3, 80}}));
}
proxygen::TEST_F (DanglingQueueTest , Basic)
Definition at line 766 of file HTTP2PriorityQueueTest.cpp.
                                 {
  addTransaction(0, {kRootNodeId, false, 15});
  removeTransaction(0);
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 100}}));
  expireNodes();
  dump();
  EXPECT_EQ(nodes_, IDList({}));
}
proxygen::TEST_F (DanglingQueueTest , Chain)
Definition at line 776 of file HTTP2PriorityQueueTest.cpp.
                                 {
  addTransaction(0, {kRootNodeId, false, 15}, true);
  addTransaction(3, {0, false, 15}, true);
  addTransaction(5, {3, false, 15}, true);
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 100}, {3, 100}, {5, 100}}));
  expireNodes();
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 100}, {3, 100}}));
  expireNodes();
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 100}}));
  expireNodes();
  dump();
  EXPECT_EQ(nodes_, IDList({}));
}
proxygen::TEST_F (DanglingQueueTest , Drop)
Definition at line 793 of file HTTP2PriorityQueueTest.cpp.
                                {
  addTransaction(0, {kRootNodeId, false, 15}, true);
  addTransaction(3, {0, false, 15}, true);
  addTransaction(5, {0, false, 15}, true);
  dump();
  q_.dropPriorityNodes();
  dump();
  EXPECT_EQ(nodes_, IDList({}));
}
proxygen::TEST_F (DanglingQueueTest , ExpireParentOfMismatchedTwins)
Definition at line 803 of file HTTP2PriorityQueueTest.cpp.
                                                         {
  addTransaction(0, {kRootNodeId, true, 219}, false);
  addTransaction(3, {0, false, 146}, false);
  addTransaction(5, {0, false, 146}, false);
  signalEgress(3, false);
  signalEgress(5, true);
  removeTransaction(0);
  dump();
  tick();
  expireNodes();
  dump();
  EXPECT_EQ(nodes_, IDList({{3, 50}, {5, 50}}));
}
proxygen::TEST_F (DanglingQueueTest , Refresh)
Definition at line 823 of file HTTP2PriorityQueueTest.cpp.
                                   {
  // Having a long running timeout prevents HHWheelTimer::Callback::setScheduled
  // from checking the real time
  DummyTimeout t;
  timer_.scheduleTimeout(&t, std::chrono::seconds(300));
  addTransaction(0, {kRootNodeId, false, 15});
  addTransaction(3, {kRootNodeId, false, 15});
  // 0 is now virtual
  removeTransaction(0);
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 50}, {3, 50}}));
  tick();
  // before 0 times out, change it's priority, should still be there
  updatePriority(0, {kRootNodeId, false, 3});
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 20}, {3, 80}}));
  tick();
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 20}, {3, 80}}));
  expireNodes();
  dump();
  EXPECT_EQ(nodes_, IDList({{3, 100}}));
}
proxygen::TEST_F (DanglingQueueTest , Max)
Definition at line 848 of file HTTP2PriorityQueueTest.cpp.
                               {
  buildSimpleTree();
  q_.setMaxVirtualNodes(3);
  for (auto i = 1; i <= 9; i += 2) {
    removeTransaction(i == 1 ? 0 : i);
  }
  dump();
  EXPECT_EQ(nodes_, IDList({{0, 100}, {3, 50}, {5, 50}}));
  // 0 expires first and it re-weights 3 and 5, which extends their lifetime
  expireNodes();
  dump();
  EXPECT_EQ(nodes_, IDList({{3, 50}, {5, 50}}));
  expireNodes();
  dump();
  EXPECT_EQ(nodes_, IDList());
}
proxygen::TEST_F (QueueTest , Rebuild)
Definition at line 865 of file HTTP2PriorityQueueTest.cpp.
                           {
  buildSimpleTree();
  q_.rebuildTree();
  dump();
  EXPECT_EQ(nodes_, IDList({{3, 20}, {9, 20}, {5, 20}, {7, 20}, {0, 20}}));
}
proxygen::TEST_P (LegalStringTests , LegalStrings)
Definition at line 220 of file StructuredHeadersStandardTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeItem(), proxygen::StructuredHeaders::OK, and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                       {
  std::string input(GetParam().first);
  StructuredHeadersDecoder shd(input);
  StructuredHeaderItem output;
  auto err = shd.decodeItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::STRING);
  EXPECT_EQ(output, GetParam().second);
}
proxygen::TEST_P (LegalBinaryContentTests , LegalBinaryContent)
Definition at line 230 of file StructuredHeadersStandardTest.cpp.
References proxygen::StructuredHeadersStandardTest::decode32(), proxygen::StructuredHeadersDecoder::decodeItem(), proxygen::StructuredHeaders::OK, and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                                    {
  std::string input(GetParam().first);
  std::string expectedOutputInBase32(GetParam().second);
  std::string expectedOutput;
  decode32(expectedOutputInBase32, expectedOutput);
  StructuredHeadersDecoder shd(input);
  StructuredHeaderItem output;
  auto err = shd.decodeItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::BINARYCONTENT);
  EXPECT_EQ(output, expectedOutput);
}
proxygen::TEST_P (RFC1867CR , Test)
Definition at line 243 of file RFC1867Test.cpp.
References INSTANTIATE_TEST_CASE_P().
                        {
  for (size_t i = 1; i < GetParam().size(); i++) {
    auto data = makePost({{"foo", "bar"}, {"jojo", "binky"}},
                         {{"file1", {"dummy file name", GetParam()}}},
                         {});
    testSimple(std::move(data), 3 + 5 + GetParam().size(), i, 3);
  }
}
proxygen::TEST_P (LegalIntegerTests , LegalIntegers)
Definition at line 244 of file StructuredHeadersStandardTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeItem(), proxygen::StructuredHeaders::OK, and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                         {
  std::string input(GetParam().first);
  StructuredHeadersDecoder shd(input);
  StructuredHeaderItem output;
  auto err = shd.decodeItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::INT64);
  EXPECT_EQ(output, GetParam().second);
}
proxygen::TEST_P (LegalFloatTests , LegalFloats)
Definition at line 254 of file StructuredHeadersStandardTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeItem(), proxygen::StructuredHeaders::OK, and proxygen::StructuredHeaders::StructuredHeaderItem::tag.
                                     {
  std::string input(GetParam().first);
  StructuredHeadersDecoder shd(input);
  StructuredHeaderItem output;
  auto err = shd.decodeItem(output);
  EXPECT_EQ(err, StructuredHeaders::DecodeError::OK);
  EXPECT_EQ(output.tag, StructuredHeaderItem::Type::DOUBLE);
  EXPECT_EQ(output, GetParam().second);
}
proxygen::TEST_P (IllegalItemTest , IllegalItem)
Definition at line 264 of file StructuredHeadersStandardTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeItem(), and proxygen::StructuredHeaders::OK.
                                     {
  StructuredHeadersDecoder shd(GetParam());
  StructuredHeaderItem output;
  auto err = shd.decodeItem(output);
  EXPECT_NE(err, StructuredHeaders::DecodeError::OK);
}
proxygen::TEST_P (IllegalListTest , IllegalList)
Definition at line 271 of file StructuredHeadersStandardTest.cpp.
References proxygen::StructuredHeadersDecoder::decodeList(), INSTANTIATE_TEST_CASE_P(), kLegalBinContentTests, kLegalStringTests, and proxygen::StructuredHeaders::OK.
                                     {
  StructuredHeadersDecoder shd(GetParam());
  std::vector<StructuredHeaderItem> output;
  auto err = shd.decodeList(output);
  EXPECT_NE(err, StructuredHeaders::DecodeError::OK);
}
template<typename T > bool proxygen::timePointInitialized (const T & time)
Definition at line 35 of file Time.h.
References T.
Referenced by TestAsyncTransport::addReadError(), TestAsyncTransport::fireNextReadEvent(), proxygen::HTTPSessionBase::getIdleTime(), TestAsyncTransport::setReadCB(), proxygen::AsyncTimeoutSet::Callback::setScheduled(), and proxygen::HTTPConnector::timeElapsed().
                                         {
  static T epoch;
  return time > epoch;
}
std::chrono::system_clock::time_point proxygen::toSystemTimePoint (TimePoint t) [inline]
Definition at line 46 of file Time.h.
Referenced by millisecondsSinceEpoch(), secondsSinceEpoch(), and toTimeT().
                               {
  return std::chrono::system_clock::now() +
    std::chrono::duration_cast<std::chrono::system_clock::duration>(
      t - SteadyClock::now());
}
time_t proxygen::toTimeT (TimePoint t) [inline]
Definition at line 52 of file Time.h.
References toSystemTimePoint().
Referenced by getDateOffsetStr(), and getDateTimeStr().
                                   {
  return std::chrono::system_clock::to_time_t(toSystemTimePoint(t));
}
static bool proxygen::validateScheme (folly::StringPiece url) [static]
According to RFC 3986, a generic HTTP URL is of the form: scheme:[//[user[:password]@]host[:port]][/path][?query][#fragment]
ParseURL use http_parser to parse internet url, that supports internet sematic url use double slash: http://host/path ftp://host/path rtmp://host/path
It does not support special scheme like: mailto:user:port news:path
And ParseURL support partial form (URI reference): host:port/path?query::fragment /path?query::fragment ?query #fragment
Definition at line 48 of file ParseURL.cpp.
Referenced by proxygen::ParseURL::parse().
                                                 {
  auto schemeEnd = url.find("://");
  if (schemeEnd == std::string::npos || schemeEnd == 0) {
    return false;
  }
  auto scheme = url.subpiece(0, schemeEnd);
  return std::all_of(scheme.begin(), scheme.end(), [](auto _) {
      return std::isalpha(_);
  });
}
bool proxygen::validateURL (folly::ByteRange url) [inline]
Definition at line 49 of file UtilInl.h.
Referenced by proxygen::ParseURL::parseNonFully(), and proxygen::CodecUtil::validateURL().
                                            {
  for (auto p: url) {
    if (p <= 0x20 || p == 0x7f) {
      // no controls or unescaped spaces
      return false;
      }
  }
  return true;
}
Variable Documentation
const char* proxygen::connectionCloseStrings[]
Initial value:
= {
}
Definition at line 15 of file HTTPConstants.cpp.
const std::string proxygen::empty_string
Definition at line 23 of file HTTPHeaders.cpp.
Referenced by proxygen::GzipHeaderCodec::encode(), proxygen::HTTPMessage::getMethodString(), proxygen::HTTPMessage::getQueryParam(), proxygen::HTTPHeaders::getSingleOrEmpty(), proxygen::HTTPDirectResponseHandler::onHeadersComplete(), proxygen::HTTP2Codec::parseGoaway(), and TEST().
const uint8_t proxygen::HTTPHeaderCodeCommonOffset = 2
Definition at line 44 of file HTTPCommonHeaders.template.h.
Referenced by HTTPCommonHeadersGetHeaderCodeFromTableCommonHeaderNameBench(), proxygen::HTTPCommonHeaders::isHeaderNameFromTable(), memchrBench(), stdFindBench(), and TEST_F().
const HTTPSettings proxygen::kDefaultIngressSettings
Initial value:
{
  {SettingsId::INITIAL_WINDOW_SIZE, 65536}
}
Definition at line 25 of file TestUtils.cpp.
constexpr uint32_t proxygen::kDefaultMaxConcurrentOutgoingStreams = 100
Definition at line 27 of file HTTPSessionBase.h.
const std::vector<std::string> proxygen::kIllegalItemTests [static]
Initial value:
=
  {
    "'foo'",
    "\"foo",
    "\"foo \\,\"",
    "\"foo \\",
    "*aGVsbG8*",
    "*aGVsbG8=",
    "*aGVsb G8=*",
    "*aGVsbG!8=*",
    "*aGVsbG!8=!*",
    "*iZ==*",
    "a23",
    "2,3",
    "-a23",
    "4-2",
    "9223372036854775808",
    "-9223372036854775809",
    "1.5.4",
    "1..4"
  }
Definition at line 58 of file StructuredHeadersStandardTest.cpp.
const std::vector<std::string> proxygen::kIllegalListTests [static]
Initial value:
=
  {
    "1, 42,",
    "1,,42"
  }
Definition at line 80 of file StructuredHeadersStandardTest.cpp.
const std::vector<std::pair<std::string, std::string> > proxygen::kLegalBinContentTests [static]
Initial value:
=
  {
    {"*aGVsbG8=*", "NBSWY3DP"},
    {"**", ""}
  }
Definition at line 33 of file StructuredHeadersStandardTest.cpp.
Referenced by TEST_P().
const std::vector<std::pair<std::string, double> > proxygen::kLegalFloatTests [static]
Initial value:
=
  {
    {"1.23", 1.23},
    {"-1.23", -1.23}
  }
Definition at line 52 of file StructuredHeadersStandardTest.cpp.
const std::vector<std::pair<std::string, int64_t> > proxygen::kLegalIntTests [static]
Initial value:
=
  {
    {"42", 42},
    {"0", 0},
    {"00", 0},
    {"-0", 0},
    {"-42", -42},
    {"042", 42},
    {"-042", -42},
    {"9223372036854775807", std::numeric_limits<int64_t>::max()},
    {"-9223372036854775808", std::numeric_limits<int64_t>::min()}
  }
Definition at line 39 of file StructuredHeadersStandardTest.cpp.
const std::vector<std::pair<std::string, std::string> > proxygen::kLegalStringTests [static]
Initial value:
=
  {
    {"\"foo\"", "foo"},
    {"\"foo \\\"bar\\\"\"", "foo \"bar\""}
  }
Definition at line 26 of file StructuredHeadersStandardTest.cpp.
Referenced by TEST_P().
const uint8_t proxygen::kMaxErrorCode = 12
Definition at line 16 of file ErrorCode.cpp.
const std::string proxygen::kMessageFilterDefaultName_ = `Unknown` [static]
Definition at line 18 of file HTTPMessageFilters.h.
Referenced by proxygen::HTTPMessageFilter::getFilterName().
const std::string proxygen::kMockFilterName = `MockFilter` [static]
Definition at line 16 of file MockHTTPMessageFilter.h.
Referenced by proxygen::MockHTTPMessageFilter::getFilterName().
const char proxygen::kSPDYv2Dictionary[]
Initial value:
=
    "optionsgetheadpostputdeletetraceacceptaccept-charsetaccept-encodingaccept-"
    "languageauthorizationexpectfromhostif-modified-sinceif-matchif-none-matchi"
    "f-rangeif-unmodifiedsincemax-forwardsproxy-authorizationrangerefererteuser"
    "-agent10010120020120220320420520630030130230330430530630740040140240340440"
    "5406407408409410411412413414415416417500501502503504505accept-rangesageeta"
    "glocationproxy-authenticatepublicretry-afterservervarywarningwww-authentic"
    "ateallowcontent-basecontent-encodingcache-controlconnectiondatetrailertran"
    "sfer-encodingupgradeviawarningcontent-languagecontent-lengthcontent-locati"
    "oncontent-md5content-rangecontent-typeetagexpireslast-modifiedset-cookieMo"
    "ndayTuesdayWednesdayThursdayFridaySaturdaySundayJanFebMarAprMayJunJulAugSe"
    "pOctNovDecchunkedtext/htmlimage/pngimage/jpgimage/gifapplication/xmlapplic"
    "ation/xhtmltext/plainpublicmax-agecharset=iso-8859-1utf-8gzipdeflateHTTP/1"
    ".1statusversionurl"
Compression dictionary for SPDYv2; note that the trailing null is included. From http://www.chromium.org/spdy/spdy-protocol/spdy-protocol-draft2
Definition at line 18 of file CodecDictionaries.h.
const unsigned char proxygen::kSPDYv3Dictionary[]
Compression dictionary for SPDYv3. Copied from: http://www.chromium.org/spdy/spdy-protocol/spdy-protocol-draft3
Definition at line 37 of file CodecDictionaries.h.
Referenced by proxygen::SPDYCodec::getVersionSettings().
const char* const proxygen::kTypeStrings[]
Initial value:
= {
  "FIRST_BYTE",
  "LAST_BYTE",
  "PING_REPLY_SENT",
  "FIRST_HEADER_BYTE",
}
Definition at line 16 of file ByteEvents.cpp.
constexpr folly::StringPiece proxygen::kUpgradeConnectionToken = `Upgrade`
Definition at line 313 of file HTTP1xCodec.cpp.
constexpr folly::StringPiece proxygen::kUpgradeToken = `websocket`
Definition at line 312 of file HTTP1xCodec.cpp.
constexpr folly::StringPiece proxygen::kWSMagicString = `258EAFA5-E914-47DA-95CA-C5AB0DC85B11`
Definition at line 316 of file HTTP1xCodec.cpp.
Referenced by proxygen::HTTP1xCodec::generateWebsocketAccept().
const folly::SocketAddress proxygen::localAddr {`127.0.0.1`, 80}
Definition at line 19 of file TestUtils.cpp.
Referenced by proxygen::HTTPSession::connCloseByRemote(), HTTPDownstreamTest< SPDY3_1CodecPair >::HTTPDownstreamTest(), MockCodecDownstreamTest::MockCodecDownstreamTest(), proxygen::HTTPSessionBase::InfoCallback::onSettingsAck(), TEST(), and proxygen::HTTPSession::WriteSegment::writeErr().
const wangle::TransportInfo proxygen::mockTransportInfo = wangle::TransportInfo()
Definition at line 18 of file TestUtils.cpp.
Referenced by HTTPDownstreamTest< SPDY3_1CodecPair >::HTTPDownstreamTest(), MockCodecDownstreamTest::MockCodecDownstreamTest(), and TEST().
const folly::SocketAddress proxygen::peerAddr {`127.0.0.1`, 12345}
Definition at line 20 of file TestUtils.cpp.
Referenced by proxygen::HTTPSession::connCloseByRemote(), HTTPDownstreamTest< SPDY3_1CodecPair >::HTTPDownstreamTest(), MockCodecDownstreamTest::MockCodecDownstreamTest(), proxygen::HTTPSessionBase::InfoCallback::onSettingsAck(), TEST(), and proxygen::HTTPSession::WriteSegment::writeErr().