proxygen/lib/utils/test/ParseURLTest.cpp File Reference
#include <folly/portability/GTest.h>
*
#include <proxygen/lib/utils/ParseURL.h>
*
Functions
void testParseURL (const string &url, const string &expectedScheme, const string &expectedPath, const string &expectedQuery, const string &expectedHost, const uint16_t expectedPort, const string &expectedAuthority, const bool expectedValid=true)
void testHostIsIpAddress (const string &url, const bool expected)
TEST (ParseURL, HostNoBrackets)
TEST (ParseURL, FullyFormedURL)
TEST (ParseURL, ValidNonHttpScheme)
TEST (ParseURL, InvalidScheme)
TEST (ParseURL, NoScheme)
TEST (ParseURL, NoSchemeIP)
TEST (ParseURL, PathOnly)
TEST (ParseURL, QueryIsURL)
TEST (ParseURL, InvalidURL)
TEST (ParseURL, IsHostIPAddress)
Function Documentation
TEST (ParseURL , HostNoBrackets)
Definition at line 46 of file ParseURLTest.cpp.
References proxygen::ParseURL::host(), and proxygen::ParseURL::hostNoBrackets().
                               {
  ParseURL p("/bar");
  EXPECT_EQ("", p.host());
  EXPECT_EQ("", p.hostNoBrackets());
}
TEST (ParseURL , FullyFormedURL)
Definition at line 53 of file ParseURLTest.cpp.
References testParseURL().
                               {
  testParseURL("http://localhost:80/foo?bar#qqq", "http", "/foo", "bar",
               "localhost", 80, "localhost:80");
  testParseURL("http://localhost:80/foo?bar", "http", "/foo", "bar",
               "localhost", 80, "localhost:80");
  testParseURL("http://localhost:80/foo", "http", "/foo", "",
               "localhost", 80, "localhost:80");
  testParseURL("http://localhost:80/", "http", "/", "",
               "localhost", 80, "localhost:80");
  testParseURL("http://localhost:80", "http", "", "",
               "localhost", 80, "localhost:80");
  testParseURL("http://localhost", "http", "", "",
               "localhost", 0, "localhost");
  testParseURL("http://[2401:db00:2110:3051:face:0:3f:0]/", "http", "/", "",
               "[2401:db00:2110:3051:face:0:3f:0]", 0,
               "[2401:db00:2110:3051:face:0:3f:0]");
}
TEST (ParseURL , ValidNonHttpScheme)
Definition at line 71 of file ParseURLTest.cpp.
References testParseURL().
                                   {
  testParseURL("https://localhost:80/foo?bar#qqq", "https", "/foo", "bar",
               "localhost", 80, "localhost:80");
  testParseURL("rtmp://localhost:80/foo?bar#qqq", "rtmp", "/foo", "bar",
               "localhost", 80, "localhost:80");
  testParseURL("ftp://localhost:80/foo?bar#qqq", "ftp", "/foo", "bar",
               "localhost", 80, "localhost:80");
  testParseURL("proxygen://localhost:80/foo?bar#qqq", "proxygen", "/foo", "bar",
               "localhost", 80, "localhost:80");
  testParseURL("test://localhost:80/foo?bar#qqq", "test", "/foo", "bar",
               "localhost", 80, "localhost:80");
}
TEST (ParseURL , InvalidScheme)
Definition at line 84 of file ParseURLTest.cpp.
References testParseURL().
                              {
  testParseURL("test123://localhost:80", "", "", "", "", 0, "", false);
  testParseURL("test.1://localhost:80", "", "", "", "", 0, "", false);
  testParseURL("://localhost:80", "", "", "", "", 0, "", false);
  testParseURL("123://localhost:80", "", "", "", "", 0, "", false);
  testParseURL("---://localhost:80", "", "", "", "", 0, "", false);
}
TEST (ParseURL , NoScheme)
Definition at line 92 of file ParseURLTest.cpp.
References testParseURL().
                         {
  testParseURL("localhost:80/foo?bar#qqq", "", "/foo", "bar",
               "localhost", 80, "localhost:80");
  testParseURL("localhost:80/foo?bar", "", "/foo", "bar",
               "localhost", 80, "localhost:80");
  testParseURL("localhost:80/foo", "", "/foo", "",
               "localhost", 80, "localhost:80");
  testParseURL("localhost:80/", "", "/", "",
               "localhost", 80, "localhost:80");
  testParseURL("localhost:80", "", "", "",
               "localhost", 80, "localhost:80");
  testParseURL("localhost", "", "", "",
               "localhost", 0, "localhost");
}
TEST (ParseURL , NoSchemeIP)
Definition at line 107 of file ParseURLTest.cpp.
References testParseURL().
                           {
  testParseURL("1.2.3.4:54321/foo?bar#qqq", "",
               "/foo", "bar", "1.2.3.4", 54321, "1.2.3.4:54321");
  testParseURL("[::1]:80/foo?bar", "", "/foo", "bar", "[::1]", 80, "[::1]:80");
  testParseURL("[::1]/foo?bar", "", "/foo", "bar", "[::1]", 0, "[::1]");
}
TEST (ParseURL , PathOnly)
Definition at line 114 of file ParseURLTest.cpp.
References testParseURL().
                         {
  testParseURL("/f/o/o?bar#qqq", "", "/f/o/o", "bar", "", 0, "");
  testParseURL("/f/o/o?bar", "", "/f/o/o", "bar", "", 0, "");
  testParseURL("/f/o/o", "", "/f/o/o", "", "", 0, "");
  testParseURL("/", "", "/", "", "", 0, "");
  testParseURL("?foo=bar", "", "", "foo=bar", "", 0, "");
  testParseURL("?#", "", "", "", "", 0, "");
  testParseURL("#/foo/bar", "", "", "", "", 0, "");
}
TEST (ParseURL , QueryIsURL)
Definition at line 124 of file ParseURLTest.cpp.
References testParseURL().
                           {
  testParseURL("/?ids=http://vlc.afreecodec.com/download/", "",
               "/", "ids=http://vlc.afreecodec.com/download/", "", 0, "");
  testParseURL("/plugins/facepile.php?href=http://www.vakan.nl/hotels",
               "", "/plugins/facepile.php",
               "href=http://www.vakan.nl/hotels", "", 0, "");
}
TEST (ParseURL , InvalidURL)
Definition at line 132 of file ParseURLTest.cpp.
References testParseURL().
                           {
  testParseURL("http://tel:198433511/", "", "", "", "", 0, "", false);
  testParseURL("localhost:80/foo#bar?qqq", "", "", "", "", 0, "", false);
  testParseURL("#?", "", "", "", "", 0, "", false);
  testParseURL("#?hello", "", "", "", "", 0, "", false);
  testParseURL("[::1/foo?bar", "", "", "", "", 0, "", false);
  testParseURL("", "", "", "", "", 0, "", false);
  testParseURL("http://tel:198433511/test\n", "", "", "", "", 0, "", false);
  testParseURL("/test\n", "", "", "", "", 0, "", false);
}
TEST (ParseURL , IsHostIPAddress)
Definition at line 143 of file ParseURLTest.cpp.
References testHostIsIpAddress().
                                {
  testHostIsIpAddress("http://127.0.0.1:80", true);
  testHostIsIpAddress("127.0.0.1", true);
  testHostIsIpAddress("http://[::1]:80", true);
  testHostIsIpAddress("[::1]", true);
  testHostIsIpAddress("[::AB]", true);
  testHostIsIpAddress("http://localhost:80", false);
  testHostIsIpAddress("http://localhost", false);
  testHostIsIpAddress("localhost", false);
  testHostIsIpAddress("1.2.3.-1", false);
  testHostIsIpAddress("1.2.3.999", false);
  testHostIsIpAddress("::1", false);
  testHostIsIpAddress("[::99999999]", false);
  // invalid url
  testHostIsIpAddress("", false);
  testHostIsIpAddress("127.0.0.1:80/foo#bar?qqq", false);
}
void testHostIsIpAddress (const string & url, const bool expected)
Definition at line 41 of file ParseURLTest.cpp.
References proxygen::ParseURL::hostIsIPAddress().
Referenced by TEST().
                                                                 {
  ParseURL u(url);
  EXPECT_EQ(expected, u.hostIsIPAddress());
}
void testParseURL (const string & url, const string & expectedScheme, const string & expectedPath, const string & expectedQuery, const string & expectedHost, const uint16_t expectedPort, const string & expectedAuthority, const bool expectedValid = true)
Definition at line 16 of file ParseURLTest.cpp.
References proxygen::ParseURL::authority(), proxygen::ParseURL::host(), proxygen::ParseURL::path(), proxygen::ParseURL::port(), proxygen::ParseURL::query(), proxygen::ParseURL::scheme(), proxygen::ParseURL::url(), and proxygen::ParseURL::valid().
Referenced by TEST().
                                                   {
  ParseURL u(url);
  if (expectedValid) {
    EXPECT_EQ(url, u.url());
    EXPECT_EQ(expectedScheme, u.scheme());
    EXPECT_EQ(expectedPath, u.path());
    EXPECT_EQ(expectedQuery, u.query());
    EXPECT_EQ(expectedHost, u.host());
    EXPECT_EQ(expectedPort, u.port());
    EXPECT_EQ(expectedAuthority, u.authority());
    EXPECT_EQ(expectedValid, u.valid());
  } else {
    // invalid, do not need to test values
    EXPECT_EQ(expectedValid, u.valid());
  }
}