proxygen/lib/http/codec/compress/experimental/simulator/QMINScheme.h File Reference
#include <assert.h>
*
#include <folly/String.h>
*
#include <proxygen/lib/http/codec/compress/HPACKCodec.h>
*
#include <proxygen/lib/http/codec/compress/HPACKQueue.h>
*
#include <proxygen/lib/http/codec/compress/NoPathIndexingStrategy.h>
*
#include <proxygen/lib/http/codec/compress/experimental/simulator/CompressionScheme.h>
*
#include <sys/queue.h>
*
Classes
struct qmin_ctl_out
struct stream_chunk
struct stream
class proxygen::compress::QMINScheme
struct proxygen::compress::QMINScheme::QMINAck
Namespaces
 proxygen
 proxygen::compress
Enumerations
enum qmin_index_type { QIT_YES,
QIT_NO,
QIT_NEVER
 }
enum { QSIDE_CLIENT,
QSIDE_SERVER
 }
enum qmin_encode_status { QES_OK,
QES_NOBUFS,
QES_ERR
 }
Functions
static struct qmin_enc * qmin_enc_new (int, unsigned, const struct qmin_ctl_out *, const char *)
static ssize_t qmin_enc_cmds_in (struct qmin_enc *, const void *, size_t)
static enum qmin_encode_status qmin_enc_encode (struct qmin_enc *, unsigned, const char *, unsigned, const char *, unsigned, enum qmin_index_type, unsigned char *, size_t, size_t *)
static int qmin_enc_end_stream_headers (struct qmin_enc *)
static char * qmin_enc_to_str (struct qmin_enc *, size_t *)
static void qmin_enc_destroy (struct qmin_enc *)
static struct qmin_dec * qmin_dec_new (int, unsigned, const struct qmin_ctl_out *, const char *)
static ssize_t qmin_dec_cmds_in (struct qmin_dec *, const void *, size_t)
static ssize_t qmin_dec_decode (struct qmin_dec *, const void *, size_t, char *, size_t, unsigned *, unsigned *)
static int qmin_dec_stream_done (struct qmin_dec *, unsigned)
static void qmin_dec_destroy (struct qmin_dec *)
TAILQ_HEAD (stream_chunks_head, stream_chunk)
Variables
static unsigned s_seq
Enumeration Type Documentation
anonymous enum
Enumerator
QSIDE_CLIENT
QSIDE_SERVER
Definition at line 32 of file QMINScheme.h.
     {
  QSIDE_CLIENT,
  QSIDE_SERVER,
};
enum qmin_encode_status
Enumerator
QES_OK
QES_NOBUFS
QES_ERR
Definition at line 36 of file QMINScheme.h.
                        {
  QES_OK,
  QES_NOBUFS,
  QES_ERR,
};
enum qmin_index_type
Enumerator
QIT_YES
QIT_NO
QIT_NEVER
Definition at line 27 of file QMINScheme.h.
                     {
  QIT_YES,
  QIT_NO,
  QIT_NEVER,
};
Function Documentation
static ssize_t qmin_dec_cmds_in (struct qmin_dec * , const void * , size_t) [static]
Definition at line 84 of file QMINScheme.h.
Referenced by proxygen::compress::QMINScheme::decode().
                                          {
  return -1;
}
static ssize_t qmin_dec_decode (struct qmin_dec * , const void * , size_t , char * , size_t , unsigned * , unsigned *) [static]
Definition at line 89 of file QMINScheme.h.
Referenced by proxygen::compress::QMINScheme::decode().
                                             {
  return -1;
}
static void qmin_dec_destroy (struct qmin_dec *) [static]
Definition at line 102 of file QMINScheme.h.
Referenced by proxygen::compress::QMINScheme::~QMINScheme().
                                                  {
}
static struct qmin_dec* qmin_dec_new (int , unsigned , const struct qmin_ctl_out * , const char *) [static]
Definition at line 78 of file QMINScheme.h.
Referenced by proxygen::compress::QMINScheme::QMINScheme().
                                                     {
  return NULL;
}
static int qmin_dec_stream_done (struct qmin_dec * , unsigned) [static]
Definition at line 98 of file QMINScheme.h.
Referenced by proxygen::compress::QMINScheme::decode().
                                            {
  return -1;
}
static ssize_t qmin_enc_cmds_in (struct qmin_enc * , const void * , size_t) [static]
Definition at line 52 of file QMINScheme.h.
Referenced by proxygen::compress::QMINScheme::recvAck().
                                          {
  return -1;
}
static void qmin_enc_destroy (struct qmin_enc *) [static]
Definition at line 75 of file QMINScheme.h.
Referenced by proxygen::compress::QMINScheme::~QMINScheme().
                                                  {
}
static enum qmin_encode_status qmin_enc_encode (struct qmin_enc * , unsigned , const char * , unsigned , const char * , unsigned , enum qmin_index_type, unsigned char * , size_t , size_t *) [static]
Definition at line 57 of file QMINScheme.h.
References QES_ERR.
Referenced by proxygen::compress::QMINScheme::encode().
                                                           {
  return QES_ERR;
}
static int qmin_enc_end_stream_headers (struct qmin_enc *) [static]
Definition at line 69 of file QMINScheme.h.
Referenced by proxygen::compress::QMINScheme::encode().
                                                            {
  return -1;
}
static struct qmin_enc* qmin_enc_new (int , unsigned , const struct qmin_ctl_out * , const char *) [static]
Definition at line 46 of file QMINScheme.h.
Referenced by proxygen::compress::QMINScheme::QMINScheme().
                                                     {
  return NULL;
}
static char* qmin_enc_to_str (struct qmin_enc * , size_t *) [static]
Definition at line 72 of file QMINScheme.h.
Referenced by proxygen::compress::QMINScheme::encode().
                                                              {
  return strdup("");
}
TAILQ_HEAD (stream_chunks_head , stream_chunk)
Variable Documentation
unsigned s_seq [static]
Definition at line 107 of file QMINScheme.h.
Referenced by proxygen::compress::QMINScheme::QMINScheme().