proxygen::compress::Header Struct Reference
#include <Header.h>
Public Member Functions
Header (HTTPHeaderCode c, const std::string &v)
Header (HTTPHeaderCode c, const std::string &n, const std::string &v)
bool operator< (const Header &h) const
Static Public Member Functions
static Header makeHeaderForTest (const std::string &n, const std::string &v)
Public Attributes
HTTPHeaderCode code
const std::string * name
const std::string * value
Private Member Functions
Header (const std::string &n, const std::string &v)
Detailed Description
Helper structure used when serializing the uncompressed representation of a header name/value list.
Definition at line 21 of file Header.h.
Constructor & Destructor Documentation
proxygen::compress::Header::Header (HTTPHeaderCode c, const std::string & v) [inline]
Definition at line 26 of file Header.h.
Referenced by makeHeaderForTest().
    : code(c), name(HTTPCommonHeaders::getPointerToHeaderName(c)), value(&v) {}
proxygen::compress::Header::Header (HTTPHeaderCode c, const std::string & n, const std::string & v) [inline]
Definition at line 30 of file Header.h.
    : code(c), name(&n), value(&v) {}
proxygen::compress::Header::Header (const std::string & n, const std::string & v) [inline], [private]
Definition at line 49 of file Header.h.
    : code(HTTPCommonHeaders::hash(n)), name(&n), value(&v) {}
Member Function Documentation
static Header proxygen::compress::Header::makeHeaderForTest (const std::string & n, const std::string & v) [inline], [static]
Definition at line 41 of file Header.h.
References Header().
Referenced by proxygen::hpack::headersFromArray(), and TEST_F().
                                                                          {
    return Header(n, v);
  }
bool proxygen::compress::Header::operator< (const Header & h) const [inline]
Definition at line 35 of file Header.h.
References code, and name.
                                        {
    return (code < h.code) ||
      ((code == h.code) && (*name < *h.name));
  }
Member Data Documentation
HTTPHeaderCode proxygen::compress::Header::code
Definition at line 22 of file Header.h.
Referenced by operator<().
const std::string* proxygen::compress::Header::name
Definition at line 23 of file Header.h.
Referenced by operator<().
const std::string* proxygen::compress::Header::value
Definition at line 24 of file Header.h.
The documentation for this struct was generated from the following file:
proxygen/lib/http/codec/compress/Header.h