proxygen::compress::CompressionScheme::Ack Struct Reference
#include <CompressionScheme.h>
Public Member Functions
virtual ~Ack ()
Detailed Description
Definition at line 28 of file CompressionScheme.h.
Constructor & Destructor Documentation
virtual proxygen::compress::CompressionScheme::Ack::~Ack () [inline], [virtual]
Definition at line 29 of file CompressionScheme.h.
References proxygen::compress::CompressionScheme::decode(), proxygen::compress::CompressionScheme::encode(), proxygen::compress::CompressionScheme::getAck(), proxygen::compress::CompressionScheme::getHolBlockCount(), proxygen::compress::CompressionScheme::recvAck(), and proxygen::compress::CompressionScheme::runLoopCallback().
                   {
    }
The documentation for this struct was generated from the following file:
proxygen/lib/http/codec/compress/experimental/simulator/CompressionScheme.h