proxygen/lib/utils/test/TraceEventTest.cpp File Reference
#include <proxygen/lib/utils/Exception.h>
*
#include <proxygen/lib/utils/TraceEvent.h>
*
#include <proxygen/lib/utils/TraceEventType.h>
*
#include <proxygen/lib/utils/TraceFieldType.h>
*
#include <folly/portability/GTest.h>
*
#include <folly/portability/GMock.h>
*
#include <string>
*
#include <vector>
*
Functions
TEST (TraceEventTest, IntegralDataIntegralValue)
TEST (TraceEventTest, IntegralDataStringValue)
TEST (TraceEventTest, IntegralDataVectorValue)
TEST (TraceEventTest, StringDataIntegralValueConvertible)
TEST (TraceEventTest, StringDataIntegralValueNonConvertible)
TEST (TraceEventTest, StringDataStringValue)
TEST (TraceEventTest, StringDataVectorValue)
TEST (TraceEventTest, VectorDataIntegralValue)
TEST (TraceEventTest, VectorDataStringValue)
TEST (TraceEventTest, VectorDataVectorValue)
TEST (TraceEventTest, IteratorValueTypeCheckInteger)
TEST (TraceEventTest, IteratorValueTypeCheckString)
TEST (TraceEventTest, IteratorValueTypeCheckStringArray)
TEST (TraceEventTest, IntegerValueToString)
TEST (TraceEventTest, StringValueToString)
TEST (TraceEventTest, StringArrayValueToString)
Function Documentation
TEST (TraceEventTest , IntegralDataIntegralValue)
Definition at line 23 of file TraceEventTest.cpp.
References proxygen::TraceEvent::addMeta(), proxygen::TraceEvent::getTraceFieldDataAs(), and TotalRequest.
                                                {
  TraceEvent traceEvent((TraceEventType::TotalRequest));
  int64_t data(13);
  traceEvent.addMeta(TraceFieldType::Protocol, data);
  ASSERT_EQ(data,
      traceEvent.getTraceFieldDataAs<int64_t>(TraceFieldType::Protocol));
}
TEST (TraceEventTest , IntegralDataStringValue)
Definition at line 33 of file TraceEventTest.cpp.
References proxygen::TraceEvent::addMeta(), proxygen::TraceEvent::getTraceFieldDataAs(), and TotalRequest.
                                              {
  TraceEvent traceEvent((TraceEventType::TotalRequest));
  int64_t intData(13);
  traceEvent.addMeta(TraceFieldType::Protocol, intData);
  std::string strData(std::to_string(intData));
  ASSERT_EQ(strData,
      traceEvent.getTraceFieldDataAs<std::string>(TraceFieldType::Protocol));
}
TEST (TraceEventTest , IntegralDataVectorValue)
Definition at line 45 of file TraceEventTest.cpp.
References proxygen::TraceEvent::addMeta(), proxygen::TraceEvent::getTraceFieldDataAs(), and TotalRequest.
                                              {
  TraceEvent traceEvent((TraceEventType::TotalRequest));
  int64_t data(13);
  traceEvent.addMeta(TraceFieldType::Protocol, data);
  ASSERT_THROW(
      traceEvent.getTraceFieldDataAs<std::vector<std::string>>(
          TraceFieldType::Protocol),
      Exception);
}
TEST (TraceEventTest , StringDataIntegralValueConvertible)
Definition at line 57 of file TraceEventTest.cpp.
References proxygen::TraceEvent::addMeta(), proxygen::TraceEvent::getTraceFieldDataAs(), and TotalRequest.
                                                         {
  TraceEvent traceEvent((TraceEventType::TotalRequest));
  int64_t intData(13);
  std::string strData(std::to_string(intData));
  traceEvent.addMeta(TraceFieldType::Protocol, strData);
  ASSERT_EQ(intData,
      traceEvent.getTraceFieldDataAs<int64_t>(TraceFieldType::Protocol));
}
TEST (TraceEventTest , StringDataIntegralValueNonConvertible)
Definition at line 68 of file TraceEventTest.cpp.
References proxygen::TraceEvent::addMeta(), proxygen::TraceEvent::getTraceFieldDataAs(), and TotalRequest.
                                                            {
  TraceEvent traceEvent((TraceEventType::TotalRequest));
  std::string data("Abc");
  traceEvent.addMeta(TraceFieldType::Protocol, data);
  ASSERT_ANY_THROW(
      traceEvent.getTraceFieldDataAs<int64_t>(TraceFieldType::Protocol));
}
TEST (TraceEventTest , StringDataStringValue)
Definition at line 78 of file TraceEventTest.cpp.
References proxygen::TraceEvent::addMeta(), proxygen::TraceEvent::getTraceFieldDataAs(), and TotalRequest.
                                            {
  TraceEvent traceEvent((TraceEventType::TotalRequest));
  std::string data("Abc");
  traceEvent.addMeta(TraceFieldType::Protocol, data);
  ASSERT_EQ(data,
      traceEvent.getTraceFieldDataAs<std::string>(TraceFieldType::Protocol));
}
TEST (TraceEventTest , StringDataVectorValue)
Definition at line 89 of file TraceEventTest.cpp.
References proxygen::TraceEvent::addMeta(), proxygen::TraceEvent::getTraceFieldDataAs(), and TotalRequest.
                                            {
  TraceEvent traceEvent((TraceEventType::TotalRequest));
  std::string data("Abc");
  traceEvent.addMeta(TraceFieldType::Protocol, data);
  ASSERT_THROW(
      traceEvent.getTraceFieldDataAs<std::vector<std::string>>(
          TraceFieldType::Protocol),
      Exception);
}
TEST (TraceEventTest , VectorDataIntegralValue)
Definition at line 101 of file TraceEventTest.cpp.
References proxygen::TraceEvent::addMeta(), proxygen::TraceEvent::getTraceFieldDataAs(), and TotalRequest.
                                              {
  TraceEvent traceEvent((TraceEventType::TotalRequest));
  std::vector<std::string> data;
  data.push_back("Abc");
  data.push_back("Hij");
  data.push_back("Xyz");
  traceEvent.addMeta(TraceFieldType::Protocol, data);
  ASSERT_THROW(
      traceEvent.getTraceFieldDataAs<int64_t>(TraceFieldType::Protocol),
      Exception);
}
TEST (TraceEventTest , VectorDataStringValue)
Definition at line 115 of file TraceEventTest.cpp.
References proxygen::TraceEvent::addMeta(), proxygen::TraceEvent::getTraceFieldDataAs(), and TotalRequest.
                                            {
  TraceEvent traceEvent((TraceEventType::TotalRequest));
  std::vector<std::string> data;
  data.push_back("A");
  data.push_back("B");
  data.push_back("C");
  traceEvent.addMeta(TraceFieldType::Protocol, data);
  ASSERT_EQ(
      "[\"A\",\"B\",\"C\"]",
      traceEvent.getTraceFieldDataAs<std::string>(TraceFieldType::Protocol));
}
TEST (TraceEventTest , VectorDataVectorValue)
Definition at line 129 of file TraceEventTest.cpp.
References proxygen::TraceEvent::addMeta(), proxygen::TraceEvent::getTraceFieldDataAs(), and TotalRequest.
                                            {
  TraceEvent traceEvent((TraceEventType::TotalRequest));
  std::vector<std::string> data;
  data.push_back("A");
  data.push_back("B");
  data.push_back("C");
  traceEvent.addMeta(TraceFieldType::Protocol, data);
  std::vector<std::string> extractedData(
      traceEvent.getTraceFieldDataAs<std::vector<std::string>>(
          TraceFieldType::Protocol));
  EXPECT_THAT(extractedData, testing::ContainerEq(data));
}
TEST (TraceEventTest , IteratorValueTypeCheckInteger)
Definition at line 145 of file TraceEventTest.cpp.
References proxygen::TraceEvent::addMeta(), proxygen::TraceEvent::getMetaDataItr(), proxygen::TraceEvent::Iterator::next(), and TotalRequest.
                                                    {
  TraceEvent traceEvent((TraceEventType::TotalRequest));
  int64_t intData(13);
  traceEvent.addMeta(TraceFieldType::Protocol, intData);
  auto itr = traceEvent.getMetaDataItr();
  ASSERT_TRUE(itr.isValid());
  ASSERT_EQ(TraceFieldType::Protocol, itr.getKey());
  ASSERT_EQ(typeid(int64_t), itr.type());
  itr.next();
  ASSERT_FALSE(itr.isValid());
}
TEST (TraceEventTest , IteratorValueTypeCheckString)
Definition at line 159 of file TraceEventTest.cpp.
References proxygen::TraceEvent::addMeta(), proxygen::TraceEvent::getMetaDataItr(), proxygen::TraceEvent::Iterator::next(), and TotalRequest.
                                                   {
  TraceEvent traceEvent((TraceEventType::TotalRequest));
  std::string strData("abc");
  traceEvent.addMeta(TraceFieldType::Protocol, strData);
  auto itr = traceEvent.getMetaDataItr();
  ASSERT_TRUE(itr.isValid());
  ASSERT_EQ(TraceFieldType::Protocol, itr.getKey());
  ASSERT_EQ(typeid(std::string), itr.type());
  itr.next();
  ASSERT_FALSE(itr.isValid());
}
TEST (TraceEventTest , IteratorValueTypeCheckStringArray)
Definition at line 173 of file TraceEventTest.cpp.
References proxygen::TraceEvent::addMeta(), proxygen::TraceEvent::getMetaDataItr(), proxygen::TraceEvent::Iterator::next(), and TotalRequest.
                                                        {
  TraceEvent traceEvent((TraceEventType::TotalRequest));
  std::vector<std::string> arrData;
  arrData.push_back("A");
  arrData.push_back("B");
  arrData.push_back("C");
  traceEvent.addMeta(TraceFieldType::Protocol, arrData);
  auto itr = traceEvent.getMetaDataItr();
  ASSERT_TRUE(itr.isValid());
  ASSERT_EQ(TraceFieldType::Protocol, itr.getKey());
  ASSERT_EQ(typeid(std::vector<std::string>), itr.type());
  itr.next();
  ASSERT_FALSE(itr.isValid());
}
TEST (TraceEventTest , IntegerValueToString)
Definition at line 191 of file TraceEventTest.cpp.
References proxygen::TraceEvent::addMeta(), proxygen::TraceEvent::end(), proxygen::TraceEvent::getID(), proxygen::TraceEvent::start(), proxygen::TraceEvent::toString(), and TotalRequest.
                                           {
  TraceEvent traceEvent(TraceEventType::TotalRequest, 1);
  traceEvent.start(TimePoint(std::chrono::milliseconds(100)));
  traceEvent.end(TimePoint(std::chrono::milliseconds(200)));
  int64_t intData(13);
  traceEvent.addMeta(TraceFieldType::Protocol, intData);
  std::ostringstream out;
  out << "TraceEvent(";
  out << "type='TotalRequest', ";
  out << "id='" << traceEvent.getID() << "', ";
  out << "parentID='1', ";
  out << "start='100', ";
  out << "end='200', ";
  out << "metaData='{protocol: 13, }')";
  ASSERT_EQ(out.str(), traceEvent.toString());
}
TEST (TraceEventTest , StringValueToString)
Definition at line 210 of file TraceEventTest.cpp.
References proxygen::TraceEvent::addMeta(), proxygen::TraceEvent::end(), proxygen::TraceEvent::getID(), proxygen::TraceEvent::start(), proxygen::TraceEvent::toString(), and TotalRequest.
                                          {
  TraceEvent traceEvent(TraceEventType::TotalRequest, 1);
  traceEvent.start(TimePoint(std::chrono::milliseconds(100)));
  traceEvent.end(TimePoint(std::chrono::milliseconds(200)));
  std::string strData("abc");
  traceEvent.addMeta(TraceFieldType::Protocol, strData);
  std::ostringstream out;
  out << "TraceEvent(";
  out << "type='TotalRequest', ";
  out << "id='" << traceEvent.getID() << "', ";
  out << "parentID='1', ";
  out << "start='100', ";
  out << "end='200', ";
  out << "metaData='{protocol: abc, }')";
  ASSERT_EQ(out.str(), traceEvent.toString());
}
TEST (TraceEventTest , StringArrayValueToString)
Definition at line 229 of file TraceEventTest.cpp.
References proxygen::TraceEvent::addMeta(), proxygen::TraceEvent::end(), proxygen::TraceEvent::getID(), proxygen::TraceEvent::start(), proxygen::TraceEvent::toString(), and TotalRequest.
                                               {
  TraceEvent traceEvent(TraceEventType::TotalRequest, 1);
  traceEvent.start(TimePoint(std::chrono::milliseconds(100)));
  traceEvent.end(TimePoint(std::chrono::milliseconds(200)));
  std::vector<std::string> arrData;
  arrData.push_back("A");
  arrData.push_back("B");
  arrData.push_back("C");
  traceEvent.addMeta(TraceFieldType::Protocol, arrData);
  std::ostringstream out;
  out << "TraceEvent(";
  out << "type='TotalRequest', ";
  out << "id='" << traceEvent.getID() << "', ";
  out << "parentID='1', ";
  out << "start='100', ";
  out << "end='200', ";
  out << "metaData='{protocol: [\"A\",\"B\",\"C\"], }')";
  ASSERT_EQ(out.str(), traceEvent.toString());
}